// 本文件由 `scripts/gen-cli.mjs` 生成，勿手改（`pnpm gen` 重生成，`pnpm gen:check` 验真）。
// 路由记录面（派生件）：运行期路由读它。顺序＝能力名升序＋声明出现序（确定性排序）。
// 技能级入口 3 行是登记行（不进能力目录，权威＝SKILL 的 help_wake_word＋lookup 口径）。
import type { HomeRouteSpec } from '../shared/commandSpec.js';

export const ROUTES_GENERATED: readonly HomeRouteSpec[] = [
  { phrase: '居家管家 帮助', key: 'home.help.lookup' },
  { phrase: '居家管家帮助', key: 'home.help.lookup' },
  { phrase: '居家管家能做什么', key: 'home.help.lookup' },
  { phrase: '查快递', key: 'home.shopping.query', preset: { kind: 'express' } },
  { phrase: '购物清单', key: 'home.shopping.query', preset: { kind: 'list' } },
  { phrase: '缺货检测', key: 'home.shopping.query', preset: { kind: 'missing' } },
  { phrase: '囤货盘点', key: 'home.shopping.query', preset: { kind: 'stock' } },
  { phrase: '改购物清单', key: 'home.shopping.write', preset: { op: 'check' } },
  { phrase: '查异常', key: 'home.care.query', preset: { kind: 'lint' } },
  { phrase: '借用', key: 'home.care.query', preset: { kind: 'borrow' } },
  { phrase: '借出', key: 'home.care.write', preset: { kind: 'borrow', op: 'borrow' } },
  { phrase: '借入', key: 'home.care.write', preset: { kind: 'borrow', op: 'borrow' } },
  { phrase: '归还', key: 'home.care.write', preset: { kind: 'borrow', op: 'return' } },
  { phrase: '催还', key: 'home.care.query', preset: { kind: 'borrow' } },
  { phrase: '家人档案', key: 'home.care.query', preset: { kind: 'member' } },
  { phrase: '首次使用', key: 'home.care.write', preset: { kind: 'init' } },
  { phrase: '备份导出', key: 'home.care.write', preset: { kind: 'backup' } },
  { phrase: '导入恢复', key: 'home.care.write', preset: { kind: 'import' } },
  { phrase: '查物品(HTML)', key: 'home.item.search' },
  { phrase: '查物品', key: 'home.item.search' },
  { phrase: '紧急定位', key: 'home.item.search', preset: { locate: true } },
  { phrase: '筛选浏览', key: 'home.item.search', preset: { browse: true } },
  { phrase: '拍照找物品', key: 'home.item.search', preset: { photo: true } },
  { phrase: '查重复', key: 'home.item.search', preset: { dupes: true } },
  { phrase: '照片墙', key: 'home.item.search', preset: { wall: true } },
  { phrase: '搜索物品', key: 'home.item.search' },
  { phrase: '找一下物品', key: 'home.item.search' },
  { phrase: '帮我找找', key: 'home.item.search' },
  { phrase: '看看家里有啥', key: 'home.item.search' },
  { phrase: '看物品(HTML)', key: 'home.item.detail', needs: ['id'] },
  { phrase: '看物品', key: 'home.item.detail', needs: ['id'] },
  { phrase: '查看照片', key: 'home.item.detail', needs: ['id'], preset: { view: 'photos' } },
  { phrase: '历史', key: 'home.item.detail', needs: ['id'], preset: { view: 'history' } },
  { phrase: '查看物品', key: 'home.item.detail', needs: ['id'] },
  { phrase: '物品详情', key: 'home.item.detail', needs: ['id'] },
  { phrase: '录物品', key: 'home.item.add' },
  { phrase: '拍物品', key: 'home.item.add', preset: { photo: '1' } },
  { phrase: '批量录入', key: 'home.item.add', preset: { op: 'batch' } },
  { phrase: '补录', key: 'home.item.add', preset: { op: 'backfill' } },
  { phrase: '登记物品', key: 'home.item.add' },
  { phrase: '添加物品', key: 'home.item.add' },
  { phrase: '帮我记一下', key: 'home.item.add' },
  { phrase: '家里又多了个东西', key: 'home.item.add' },
  { phrase: '新到货了', key: 'home.item.add' },
  { phrase: '改物品', key: 'home.item.update', needs: ['id'] },
  { phrase: '移物品', key: 'home.item.update', needs: ['id'], preset: { op: 'move' } },
  { phrase: '补物品', key: 'home.item.update', needs: ['id'], preset: { op: 'qty' } },
  { phrase: '减物品', key: 'home.item.update', needs: ['id'], preset: { op: 'qty' } },
  { phrase: '标物品', key: 'home.item.update', needs: ['id'], preset: { op: 'tags' } },
  { phrase: '废物品', key: 'home.item.update', needs: ['id'], preset: { op: 'status' } },
  { phrase: '借物品', key: 'home.item.update', needs: ['id'], preset: { op: 'status' } },
  { phrase: '修物品', key: 'home.item.update', needs: ['id'], preset: { op: 'status' } },
  { phrase: '合并物品', key: 'home.item.update', needs: ['id'], preset: { op: 'merge' } },
  { phrase: '撤销操作', key: 'home.item.update', preset: { op: 'undo' } },
  { phrase: '物品关联', key: 'home.item.update', needs: ['id'], preset: { op: 'relate' } },
  { phrase: '管照片', key: 'home.item.update', needs: ['id'], preset: { op: 'photo' } },
  { phrase: '数量变更', key: 'home.item.update', needs: ['id'], preset: { op: 'qty' } },
  { phrase: '状态变更', key: 'home.item.update', needs: ['id'], preset: { op: 'status' } },
  { phrase: '看标签', key: 'home.tag.query' },
  { phrase: '管标签', key: 'home.tag.write', preset: { op: 'overview' } },
  { phrase: '管分类', key: 'home.tag.write', preset: { op: 'category' } },
  { phrase: '整理建议', key: 'home.tag.write', preset: { op: 'tidy' } },
  { phrase: '合标签', key: 'home.tag.write', preset: { op: 'merge' } },
  { phrase: '盘物品', key: 'home.inventory.round', preset: { op: 'round' } },
  { phrase: '盘全部', key: 'home.inventory.round', preset: { op: 'round', scope: 'all' } },
  { phrase: '盘点', key: 'home.inventory.round', preset: { op: 'round' } },
  { phrase: '差异处理', key: 'home.inventory.round', preset: { op: 'resolve' } },
  { phrase: '搬家盘点', key: 'home.inventory.round', preset: { op: 'move' } },
  { phrase: '清点物品', key: 'home.inventory.round', preset: { op: 'round' } },
  { phrase: '核对库存', key: 'home.inventory.round', preset: { op: 'round' } },
  { phrase: '数数这里', key: 'home.inventory.round', preset: { op: 'round' } },
  { phrase: '盘点记录', key: 'home.inventory.records' },
  { phrase: '穿什么', key: 'home.outfit.pick' },
  { phrase: '衣橱分析', key: 'home.outfit.pick', preset: { kind: 'wardrobe' } },
  { phrase: '换季', key: 'home.outfit.pick', preset: { kind: 'season' } },
  { phrase: '旅行穿搭', key: 'home.outfit.pick', preset: { kind: 'trip-plan' } },
  { phrase: '带物品', key: 'home.trip.manage', preset: { mode: 'pack' } },
  { phrase: '归物品', key: 'home.trip.manage', preset: { mode: 'return' } },
  { phrase: '查账号', key: 'home.ticket.query', preset: { kind: 'account' } },
  { phrase: '存账号', key: 'home.ticket.write', preset: { kind: 'account', op: 'add' } },
  { phrase: '改账号', key: 'home.ticket.write', preset: { kind: 'account', op: 'update' } },
  { phrase: '看密码', key: 'home.ticket.write', preset: { kind: 'account', op: 'show' } },
  { phrase: '查购买记录', key: 'home.ticket.query', preset: { kind: 'purchase' } },
  { phrase: '查上月购买', key: 'home.ticket.query', preset: { kind: 'purchase', range: 'last-month' } },
  { phrase: '查今年花费', key: 'home.ticket.query', preset: { kind: 'purchase', range: 'year' } },
  { phrase: '查退货窗口', key: 'home.ticket.query', preset: { kind: 'purchase', range: 'return' } },
  { phrase: '登记购买记录', key: 'home.ticket.write', preset: { kind: 'purchase', op: 'add' } },
  { phrase: '查保修状态', key: 'home.ticket.query', preset: { kind: 'warranty' } },
  { phrase: '登记保修', key: 'home.ticket.write', preset: { kind: 'warranty', op: 'register' } },
  { phrase: '记录维修', key: 'home.ticket.write', preset: { kind: 'warranty', op: 'repair' } },
  { phrase: '设置保养周期', key: 'home.ticket.write', preset: { kind: 'warranty', op: 'cycle' } },
  { phrase: '执行保养', key: 'home.ticket.write', preset: { kind: 'warranty', op: 'maintain' } },
  { phrase: '查证件到期', key: 'home.ticket.query', preset: { kind: 'cert' } },
  { phrase: '登记证件', key: 'home.ticket.write', preset: { kind: 'cert', op: 'add' } },
  { phrase: '证件归档', key: 'home.ticket.write', preset: { kind: 'cert', op: 'archive' } },
  { phrase: '更新证件', key: 'home.ticket.write', preset: { kind: 'cert', op: 'update' } },
  { phrase: '推位置', key: 'home.location.query', needs: ['category_id'], preset: { mode: 'suggest' } },
  { phrase: '找位置', key: 'home.location.query', needs: ['reference'], preset: { mode: 'find' } },
  { phrase: '管位置', key: 'home.location.write', preset: { op: 'manage' } },
  { phrase: '固定位', key: 'home.location.write', preset: { op: 'fixed' } },
  { phrase: '收纳建议', key: 'home.location.query', preset: { mode: 'storage' } },
  { phrase: '空间视图', key: 'home.location.query', preset: { mode: 'space' } },
  { phrase: '位置管理', key: 'home.location.write', preset: { op: 'manage' } },
  { phrase: '整理一下家里的位置', key: 'home.location.write', preset: { op: 'manage' } },
  { phrase: '位置怎么分的', key: 'home.location.write', preset: { op: 'manage' } },
  { phrase: '设置固定位', key: 'home.location.write', preset: { op: 'fixed' } },
  { phrase: '给我定个固定位置', key: 'home.location.write', preset: { op: 'fixed' } },
  { phrase: '收纳位置建议', key: 'home.location.query', preset: { mode: 'storage' } },
  { phrase: '帮我找个地方放', key: 'home.location.query', preset: { mode: 'storage' } },
  { phrase: '浏览空间视图', key: 'home.location.query', preset: { mode: 'space' } },
  { phrase: '看看家里每个地方都有啥', key: 'home.location.query', preset: { mode: 'space' } },
  { phrase: '客厅里都有什么', key: 'home.location.query', preset: { mode: 'space' } },
  { phrase: '统物品(HTML)', key: 'home.stats.overview' },
  { phrase: '统物品', key: 'home.stats.overview', preset: { kind: 'summary' } },
  { phrase: '查高频', key: 'home.stats.overview', preset: { kind: 'summary' } },
  { phrase: '盘点统计', key: 'home.stats.overview', preset: { kind: 'inventory' } },
  { phrase: '统计物品', key: 'home.stats.overview', preset: { kind: 'summary' } },
  { phrase: '物品总览', key: 'home.stats.overview', preset: { kind: 'summary' } },
  { phrase: '家里都有啥', key: 'home.stats.overview', preset: { kind: 'summary' } },
  { phrase: '给我个总数', key: 'home.stats.overview', preset: { kind: 'summary' } },
  { phrase: '一共多少件', key: 'home.stats.overview', preset: { kind: 'summary' } },
  { phrase: '整体啥情况', key: 'home.stats.overview', preset: { kind: 'summary' } },
  { phrase: '查低频', key: 'home.stats.alert', preset: { kind: 'idle' } },
  { phrase: '查过期', key: 'home.stats.alert', preset: { kind: 'expiring' } },
  { phrase: '查闲置', key: 'home.stats.alert', preset: { kind: 'idle' } },
];
