/** #873 派生席 · 回执那两页的页内形状（结论条＋状态徽章／关系对图／说明段／动作行），兼页内样式唯一入口。
 *
 * 家族树那一族住同目录的 `treeShapes.ts`：两族的变化频率不同，拆开之后两件都在本包告警线 350 行以内。
 * 规则顺序与拆件前逐行相同（先回执族、后家族树族），因此产物一字不变。
 */

import { LF, relationTreeShapeCss, TONE, tint } from './treeShapes.js';

/** 本域三页的页内形状样式唯一产出者（回执两页 ＋ 家族树）。恒返回非空 CSS 文本。 */
export function relationShapeCss(): string {
  const root = '.ilife-page-ui ';
  const node = root + '.ilife-relation-node';
  return [
    '/* #873 派生席 · 页内形状（关系对图 ＋ 三层家族树），只命中本域三页 */',
    /* 结论条与状态徽章配成一行：判定句与它的状态在同一格里。 */
    root + '.ilife-relation-verdict {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: center;',
    '  gap: 10px;',
    '  margin: 0;',
    '}',
    root + '.ilife-relation-verdict > .ilife-block-conclusion {',
    '  flex: 1 1 200px;',
    '  min-width: 0;',
    '  margin: 0;',
    '}',
    root + '.ilife-relation-verdict > .ilife-status-badge {',
    '  flex: 0 0 auto;',
    '}',
    /* 关系对图：两格节点 ＋ 中间一格给关系类型与箭头。箭头自上而下由暖转主色，
       两端节点各带一条同色的左缘，读起来是「从这一头到那一头」。 */
    root + '.ilife-relation-pair {',
    '  display: grid;',
    '  grid-template-columns: minmax(0, 1fr) 52px minmax(0, 1fr);',
    '  align-items: center;',
    '  margin: 16px 0 0;',
    '}',
    node + ' {',
    '  position: relative;',
    '  display: flex;',
    '  align-items: center;',
    '  gap: 10px;',
    '  box-sizing: border-box;',
    '  min-width: 0;',
    '  padding: 12px 14px;',
    '  border: 1px solid var(--line);',
    '  border-left-width: 4px;',
    '  border-radius: 14px;',
    '  background: var(--card);',
    '}',
    node + '-up {',
    '  border-left-color: ' + TONE.up + ';',
    '  background: ' + tint(TONE.up, 12) + ';',
    '}',
    node + '-down {',
    '  border-left-color: ' + TONE.down + ';',
    '  background: ' + tint(TONE.down, 12) + ';',
    '}',
    root + '.ilife-relation-node-body {',
    '  min-width: 0;',
    '}',
    /* 图标位：一枚圆角方块底 ＋ 一枚箭头字形。纯装饰，字一个都不进样式。 */
    root + '.ilife-relation-icon {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  flex: 0 0 auto;',
    '  width: 22px;',
    '  height: 22px;',
    '  border-radius: 8px;',
    '  color: var(--card);',
    '  background: ' + TONE.up + ';',
    '}',
    root + '.ilife-relation-icon svg {',
    '  display: block;',
    '}',
    root + '.ilife-relation-icon-here {',
    '  background: ' + TONE.here + ';',
    '}',
    root + '.ilife-relation-icon-down {',
    '  background: ' + TONE.down + ';',
    '}',
    root + '.ilife-relation-role {',
    '  display: block;',
    '  color: var(--fg2);',
    '  font-size: 12px;',
    '}',
    root + '.ilife-relation-name {',
    '  display: block;',
    '  margin-top: 3px;',
    '  color: var(--fg);',
    '  font-size: 17px;',
    '  font-weight: 600;',
    '  overflow-wrap: anywhere;',
    '}',
    root + '.ilife-relation-link {',
    '  display: flex;',
    '  flex-direction: column;',
    '  align-items: center;',
    '  gap: 6px;',
    '  min-width: 0;',
    '  padding: 0 6px;',
    '}',
    root + '.ilife-relation-kind {',
    '  max-width: 100%;',
    '  padding: 1px 8px;',
    '  border-radius: 999px;',
    '  background: var(--soft);',
    '  color: var(--blue2);',
    '  font-size: 12px;',
    '  line-height: 1.5;',
    '  white-space: nowrap;',
    '  overflow: hidden;',
    '  text-overflow: ellipsis;',
    '}',
    root + '.ilife-relation-arrow {',
    '  position: relative;',
    '  display: block;',
    '  width: 100%;',
    '  height: 3px;',
    '  border-radius: 999px;',
    '  background-image: linear-gradient(90deg, ' + TONE.up + ', ' + TONE.here + ');',
    '}',
    root + '.ilife-relation-arrow::after {',
    '  content: "";',
    '  position: absolute;',
    '  top: 50%;',
    '  right: 0;',
    '  width: 0;',
    '  height: 0;',
    '  border-top: 5px solid transparent;',
    '  border-bottom: 5px solid transparent;',
    '  border-left: 9px solid ' + TONE.here + ';',
    '  transform: translateY(-50%);',
    '}',
    /* 说明段：一条暖色引线圈住这段正文（不写标签，也就没有「标签贴着值」那种懒写法）。 */
    root + '.ilife-relation-note {',
    '  margin: 14px 0 0;',
    '  padding: 2px 0 2px 12px;',
    '  border-left: 3px solid ' + TONE.up + ';',
    '}',
    root + '.ilife-relation-note > .ilife-block-prose {',
    '  margin: 0;',
    '}',
    /* 动作行：只有一颗按钮时让它铺满整行（两列栅格里一颗按钮只占左半格，读起来像贴边的小件）。 */
    root + '.ilife-relation-actions > .ilife-action-bar > .ilife-action-row > :only-child {',
    '  grid-column: 1 / -1;',
    '}',
    /* 宽档（≥1001px）加宽的是**箭头那一格**（52px→104px）：连线跟着变长，中段不再是一块空白。
       实测记一笔：这一条给第 42 格 -2、第 44 格 -1（两张卡被推开后首屏的紧凑感松了），已撤；
       留在这里的注释是给下一手省一次同样的试。 */
  ].join(LF) + LF + relationTreeShapeCss();
}
