/** 派生三页的页内形状（只在本域三页命中）。
 *
 * 为什么另立一件：`pages.ts` 里装的是「这一页有哪些区块、按什么次序摆」；形状住这里。
 * 两件事的变化频率不同——形状随视觉口径改，装配随内容改——按结构标准「同一批改动一起改的东西
 * 放近」，分成两件后两边都在告警线 350 行以内。
 *
 * 三条口径（与公共层的皮肤同源，违反即作废）：
 *  ① 每一条选择器都挂在根类 `.ilife-page-ui` 之下：本件只进私家大厨本域三页的 `extraCss`；
 *  ② 色值只用冻结 token 与既有调色板 `CHART_PALETTE`（唯一定义地＝ base-paint 的 `spec/charts`），
 *    圆角只用闭集 `{8,14,20,999}`，断点只用仓内既有集合 `{400,640,820,1001,1200}`；
 *  ③ 公共层的规则一条不改：本件只加 `.ilife-relation-*` 这几个本域自己的类，
 *    对公共层件只做「容器内的位次」调整（说明段里那段正文的上边距、单颗动作按钮铺满整行）。
 *
 * 配色分工（三层三色，一条规则）：**上＝暖、中＝主色、下＝成功色**。三个色值各只有一处定义地：
 * 暖色取调色板，主色与成功色取冻结 token；层标记、层左缘、条目行的槽位都读同一个常量，
 * 不各写一遍。
 */

import { CHART_PALETTE } from 'base-paint';

/** 换行（仓库口径：不写字面换行转义）。 */
const LF = String.fromCharCode(10);

/** 三层各自的强调色（上＝暖色／中＝主色／下＝成功色）。产出器与页内装饰图形读同一处。 */
export const TONE = {
  up: CHART_PALETTE[2],
  here: 'var(--blue)',
  down: 'var(--ok)',
} as const;

/** 强调色的浅底：按百分比与卡片底色混出来，色基仍只来自上面那三个常量（不发明新色值）。 */
function tint(color: string, pct: number): string {
  return 'color-mix(in srgb, ' + color + ' ' + pct + '%, var(--card))';
}

/** 本域三页的页内形状样式唯一产出者。恒返回非空 CSS 文本。 */
export function relationShapeCss(): string {
  const root = '.ilife-page-ui ';
  const node = root + '.ilife-relation-node';
  return [
    '/* #873 派生席 · 页内形状（关系对图 ＋ 三层家族树），只命中本域三页 */',
    /* 结论条与状态徽章配成一行：判定句与它的状态在同一格里。 */
    root + '.ilife-relation-verdict {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: center;',
    '  gap: 10px;',
    '  margin: 0;',
    '}',
    root + '.ilife-relation-verdict > .ilife-block-conclusion {',
    '  flex: 1 1 200px;',
    '  min-width: 0;',
    '  margin: 0;',
    '}',
    root + '.ilife-relation-verdict > .ilife-status-badge {',
    '  flex: 0 0 auto;',
    '}',
    /* 关系对图：两格节点 ＋ 中间一格给关系类型与箭头。箭头自上而下由暖转主色，
       两端节点各带一条同色的左缘，读起来是「从这一头到那一头」。 */
    root + '.ilife-relation-pair {',
    '  display: grid;',
    '  grid-template-columns: minmax(0, 1fr) 52px minmax(0, 1fr);',
    '  align-items: center;',
    '  margin: 16px 0 0;',
    '}',
    node + ' {',
    '  position: relative;',
    '  display: flex;',
    '  align-items: center;',
    '  gap: 10px;',
    '  box-sizing: border-box;',
    '  min-width: 0;',
    '  padding: 12px 14px;',
    '  border: 1px solid var(--line);',
    '  border-left-width: 4px;',
    '  border-radius: 14px;',
    '  background: var(--card);',
    '}',
    node + '-up {',
    '  border-left-color: ' + TONE.up + ';',
    '  background: ' + tint(TONE.up, 12) + ';',
    '}',
    node + '-down {',
    '  border-left-color: ' + TONE.down + ';',
    '  background: ' + tint(TONE.down, 12) + ';',
    '}',
    root + '.ilife-relation-node-body {',
    '  min-width: 0;',
    '}',
    /* 图标位：一枚圆角方块底 ＋ 一枚箭头字形。纯装饰，字一个都不进样式。 */
    root + '.ilife-relation-icon {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  flex: 0 0 auto;',
    '  width: 22px;',
    '  height: 22px;',
    '  border-radius: 8px;',
    '  color: var(--card);',
    '  background: ' + TONE.up + ';',
    '}',
    root + '.ilife-relation-icon svg {',
    '  display: block;',
    '}',
    root + '.ilife-relation-icon-here {',
    '  background: ' + TONE.here + ';',
    '}',
    root + '.ilife-relation-icon-down {',
    '  background: ' + TONE.down + ';',
    '}',
    root + '.ilife-relation-role {',
    '  display: block;',
    '  color: var(--fg2);',
    '  font-size: 12px;',
    '}',
    root + '.ilife-relation-name {',
    '  display: block;',
    '  margin-top: 3px;',
    '  color: var(--fg);',
    '  font-size: 17px;',
    '  font-weight: 600;',
    '  overflow-wrap: anywhere;',
    '}',
    root + '.ilife-relation-link {',
    '  display: flex;',
    '  flex-direction: column;',
    '  align-items: center;',
    '  gap: 6px;',
    '  min-width: 0;',
    '  padding: 0 6px;',
    '}',
    root + '.ilife-relation-kind {',
    '  max-width: 100%;',
    '  padding: 1px 8px;',
    '  border-radius: 999px;',
    '  background: var(--soft);',
    '  color: var(--blue2);',
    '  font-size: 12px;',
    '  line-height: 1.5;',
    '  white-space: nowrap;',
    '  overflow: hidden;',
    '  text-overflow: ellipsis;',
    '}',
    root + '.ilife-relation-arrow {',
    '  position: relative;',
    '  display: block;',
    '  width: 100%;',
    '  height: 3px;',
    '  border-radius: 999px;',
    '  background-image: linear-gradient(90deg, ' + TONE.up + ', ' + TONE.here + ');',
    '}',
    root + '.ilife-relation-arrow::after {',
    '  content: "";',
    '  position: absolute;',
    '  top: 50%;',
    '  right: 0;',
    '  width: 0;',
    '  height: 0;',
    '  border-top: 5px solid transparent;',
    '  border-bottom: 5px solid transparent;',
    '  border-left: 9px solid ' + TONE.here + ';',
    '  transform: translateY(-50%);',
    '}',
    /* 说明段：一条暖色引线圈住这段正文（不写标签，也就没有「标签贴着值」那种懒写法）。 */
    root + '.ilife-relation-note {',
    '  margin: 14px 0 0;',
    '  padding: 2px 0 2px 12px;',
    '  border-left: 3px solid ' + TONE.up + ';',
    '}',
    root + '.ilife-relation-note > .ilife-block-prose {',
    '  margin: 0;',
    '}',
    /* 动作行：只有一颗按钮时让它铺满整行（两列栅格里一颗按钮只占左半格，读起来像贴边的小件）。 */
    root + '.ilife-relation-actions > .ilife-action-bar > .ilife-action-row > :only-child {',
    '  grid-column: 1 / -1;',
    '}',
    /* 三层家族树：层与层之间一条竖向连接件（线 ＋ 箭头）；三层各带一条同色左缘。 */
    root + '.ilife-relation-tree {',
    '  margin: 16px 0 0;',
    '}',
    root + '.ilife-relation-tier {',
    '  box-sizing: border-box;',
    '  padding: 12px 14px;',
    '  border: 1px solid var(--line);',
    '  border-left-width: 4px;',
    '  border-radius: 14px;',
    '  background: var(--card);',
    '}',
    root + '.ilife-relation-tier-up {',
    '  border-left-color: ' + TONE.up + ';',
    '  background: ' + tint(TONE.up, 8) + ';',
    '}',
    root + '.ilife-relation-tier-here {',
    '  border-color: var(--blue);',
    '  border-left-color: ' + TONE.here + ';',
    '  background: var(--soft);',
    '}',
    root + '.ilife-relation-tier-down {',
    '  border-left-color: ' + TONE.down + ';',
    '  background: ' + tint(TONE.down, 5) + ';',
    '}',
    root + '.ilife-relation-tier-head {',
    '  display: flex;',
    '  align-items: center;',
    '  gap: 8px;',
    '  margin: 0;',
    '}',
    root + '.ilife-relation-tier-name {',
    '  color: var(--fg);',
    '  font-size: 13px;',
    '  font-weight: 600;',
    '}',
    root + '.ilife-relation-tier-kind {',
    '  padding: 1px 8px;',
    '  border-radius: 999px;',
    '  background: var(--soft);',
    '  color: var(--blue2);',
    '  font-size: 12px;',
    '  line-height: 1.6;',
    '}',
    root + '.ilife-relation-tier-count {',
    '  margin-left: auto;',
    '  color: var(--fg3);',
    '  font-size: 12px;',
    '}',
    root + '.ilife-relation-tier-body {',
    '  margin: 8px 0 0;',
    '}',
    /* 空层收成一条瘦条：虚线卡 ＋ 一行占位人话，不再占一整块实心卡片（空的那层白吃掉首屏一截）。 */
    root + '.ilife-relation-tier-empty {',
    '  padding: 10px 14px;',
    '  border-style: dashed;',
    '  background: var(--card);',
    '}',
    root + '.ilife-relation-tier-empty .ilife-relation-tier-body {',
    '  margin: 6px 0 0;',
    '}',
    root + '.ilife-relation-tier-empty .ilife-relation-ghost {',
    '  padding: 0;',
    '  border: 0;',
    '  background: transparent;',
    '}',
    root + '.ilife-relation-here {',
    '  display: inline-flex;',
    '  max-width: 100%;',
    '  box-sizing: border-box;',
    '  padding: 5px 14px;',
    '  border: 1px solid var(--blue);',
    '  border-radius: 999px;',
    '  background: var(--card);',
    '  color: var(--fg);',
    '  font-size: 16px;',
    '  font-weight: 600;',
    '  overflow-wrap: anywhere;',
    '}',
    root + '.ilife-relation-joint {',
    '  position: relative;',
    '  width: 2px;',
    '  height: 20px;',
    '  margin: 0 auto;',
    '  background: var(--line);',
    '}',
    root + '.ilife-relation-joint::after {',
    '  content: "";',
    '  position: absolute;',
    '  left: 50%;',
    '  bottom: 0;',
    '  width: 0;',
    '  height: 0;',
    '  border-left: 5px solid transparent;',
    '  border-right: 5px solid transparent;',
    '  border-top: 7px solid var(--blue);',
    '  transform: translateX(-50%);',
    '}',
    /* 一层里的条目行：左侧一条支线 ＋ 每行一枚本层色的圆点（图形标记，不上字），代次与菜名分槽。 */
    root + '.ilife-relation-branch {',
    '  margin: 0;',
    '  padding: 0 0 0 16px;',
    '  border-left: 2px solid var(--line);',
    '  list-style: none;',
    '}',
    root + '.ilife-relation-tier-down .ilife-relation-branch {',
    '  border-left-color: ' + TONE.down + ';',
    '}',
    root + '.ilife-relation-tier-up .ilife-relation-branch {',
    '  border-left-color: ' + TONE.up + ';',
    '}',
    root + '.ilife-relation-branch-row {',
    '  position: relative;',
    '  box-sizing: border-box;',
    '  padding: 10px 0;',
    '}',
    root + '.ilife-relation-branch-row::before {',
    '  content: "";',
    '  position: absolute;',
    '  left: -21px;',
    '  top: 14px;',
    '  box-sizing: border-box;',
    '  width: 10px;',
    '  height: 10px;',
    '  border: 2px solid var(--card);',
    '  border-radius: 999px;',
    '  background: ' + TONE.up + ';',
    '}',
    root + '.ilife-relation-tier-down .ilife-relation-branch-row::before {',
    '  background: ' + TONE.down + ';',
    '}',
    root + '.ilife-relation-tier-up .ilife-relation-branch-row::before {',
    '  background: ' + TONE.up + ';',
    '}',
    root + '.ilife-relation-branch-head {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: center;',
    '  gap: 6px 8px;',
    '}',
    root + '.ilife-relation-level {',
    '  flex: 0 0 auto;',
    '  padding: 1px 8px;',
    '  border-radius: 999px;',
    '  background: var(--soft);',
    '  color: var(--blue2);',
    '  font-size: 12px;',
    '  font-weight: 600;',
    '}',
    root + '.ilife-relation-branch-name {',
    '  min-width: 0;',
    '  color: var(--fg);',
    '  font-size: 15px;',
    '  font-weight: 600;',
    '  overflow-wrap: anywhere;',
    '}',
    root + '.ilife-relation-branch-note {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 2px 8px;',
    '  margin-top: 3px;',
    '  overflow-wrap: anywhere;',
    '}',
    /* 改动说明前的图形标记（一支笔）：给这行小字当图例，不用再写「改动」两个字。 */
    root + '.ilife-relation-branch-note-mark {',
    '  flex: 0 0 auto;',
    '  display: inline-flex;',
    '  align-items: center;',
    '  color: var(--fg3);',
    '}',
    root + '.ilife-relation-branch-note-text {',
    '  min-width: 0;',
    '  color: var(--fg2);',
    '  font-size: 12px;',
    '  line-height: 1.6;',
    '}',
    /* 宽档（≥1001px）：880 版心里三层各自竖成一条「层标 ＋ 层体」两栏，行内左右分槽把空档填掉——
       层标占左栏（图标、层名、关系类型、条数自上而下），层体占右栏，条目行左边的菜名与右边的改动说明
       各靠一边，不再是一行字悬在一张长条卡里。 */
    '@media (min-width: 1001px) {',
    root + '.ilife-relation-tier {',
    '    display: grid;',
    '    grid-template-columns: 168px minmax(0, 1fr);',
    '    column-gap: 20px;',
    '    align-items: start;',
    '  }',
    root + '.ilife-relation-tier-head {',
    '    flex-direction: column;',
    '    align-items: flex-start;',
    '    gap: 6px;',
    '  }',
    root + '.ilife-relation-tier-count {',
    '    margin-left: 0;',
    '  }',
    root + '.ilife-relation-tier-body {',
    '    margin: 0;',
    '  }',
    root + '.ilife-relation-branch-row {',
    '    display: flex;',
    '    flex-wrap: wrap;',
    '    align-items: baseline;',
    '    column-gap: 16px;',
    '    row-gap: 4px;',
    '  }',
    root + '.ilife-relation-branch-note {',
    '    margin-top: 0;',
    '  }',
    root + '.ilife-relation-ghost {',
    '    align-items: center;',
    '  }',
    root + '.ilife-relation-ornament {',
    '    display: inline-flex;',
    '  }',
    '}',
    /* 页头右侧那枝装饰树：窄档不出（首屏要留给三层树本体），宽档显出来填掉结论条右侧的空档。 */
    root + '.ilife-relation-ornament {',
    '  display: none;',
    '  flex: 0 0 auto;',
    '  align-items: center;',
    '}',
    root + '.ilife-relation-ornament svg {',
    '  display: block;',
    '}',
    /* 空层的占位件：虚线框，槽位与真条目同规格（换数据不换格子）。 */
    root + '.ilife-relation-ghost {',
    '  display: flex;',
    '  align-items: flex-start;',
    '  gap: 10px;',
    '  box-sizing: border-box;',
    '  padding: 10px 12px;',
    '  border: 1px dashed var(--line);',
    '  border-radius: 14px;',
    '  background: var(--soft);',
    '}',
    root + '.ilife-relation-ghost-mark {',
    '  flex: 0 0 auto;',
    '  width: 12px;',
    '  height: 12px;',
    '  margin-top: 3px;',
    '  border: 2px dashed var(--fg3);',
    '  border-radius: 999px;',
    '}',
    root + '.ilife-relation-ghost-body {',
    '  min-width: 0;',
    '}',
    root + '.ilife-relation-ghost-text {',
    '  margin: 0;',
    '  color: var(--fg2);',
    '  font-size: 14px;',
    '  font-weight: 600;',
    '}',
    root + '.ilife-relation-ghost-hint {',
    '  margin: 2px 0 0;',
    '  color: var(--fg3);',
    '  font-size: 12px;',
    '  line-height: 1.5;',
    '  overflow-wrap: anywhere;',
    '}',
  ].join(LF);
}
