/** #873 派生席 · 家族树那一族的页内形状（三层树／层头／条目行／宽档两栏重排）。
 *
 * 为什么与回执那两页分家：这一族讲的是「上下游三层怎么摆」，回执那两页讲的是「一组关系怎么摆」，
 * 两批改动不同批发生（改家族树时那两页一个字不用动）；合成一件会顶到本包告警线以上（拆前 427 LF）。
 *
 * 三层色基 `TONE` 与浅底 `tint()` 住本件，因为三层左缘、层头图标位、条目行圆点读的都是这三个常量，
 * 连回执页那两个节点的左缘也从 `shapes.ts` 取这里；色值只取冻结 token 与既有调色板 `CHART_PALETTE`
 * （唯一定义地＝ base-paint 的 `spec/charts.ts`），圆角只用闭集 `{8,14,20,999}`。
 */

import { CHART_PALETTE } from 'base-paint';

/** 换行（仓库口径：不写字面换行转义）。两件的产出器读同一处。 */
export const LF = String.fromCharCode(10);

/** 三层各自的强调色（上＝暖色／中＝主色／下＝成功色）。三层左缘、层头图标位、条目行圆点、
 *  以及回执页那两个节点的左缘，读的都是这一处。 */
export const TONE = {
  up: CHART_PALETTE[2],
  here: 'var(--blue)',
  down: 'var(--ok)',
} as const;

/** 强调色的浅底：按百分比与卡片底色混出来，色基仍只来自上面那三个常量（不发明新色值）。 */
export function tint(color: string, pct: number): string {
  return 'color-mix(in srgb, ' + color + ' ' + pct + '%, var(--card))';
}

/** 家族树那一族的形状样式唯一产出者。恒返回非空 CSS 文本。 */
export function relationTreeShapeCss(): string {
  const root = '.ilife-page-ui ';
  return [
    /* 三层家族树：层与层之间一条竖向连接件（线 ＋ 箭头）；三层各带一条同色左缘。 */
    root + '.ilife-relation-tree {',
    '  margin: 16px 0 0;',
    '}',
    root + '.ilife-relation-tier {',
    '  box-sizing: border-box;',
    '  padding: 12px 14px;',
    '  border: 1px solid var(--line);',
    '  border-left-width: 4px;',
    '  border-radius: 14px;',
    '  background: var(--card);',
    '}',
    root + '.ilife-relation-tier-up {',
    '  border-left-color: ' + TONE.up + ';',
    '  background: ' + tint(TONE.up, 8) + ';',
    '}',
    root + '.ilife-relation-tier-here {',
    '  border-color: var(--blue);',
    '  border-left-color: ' + TONE.here + ';',
    '  background: var(--soft);',
    '}',
    root + '.ilife-relation-tier-down {',
    '  border-left-color: ' + TONE.down + ';',
    '  background: ' + tint(TONE.down, 5) + ';',
    '}',
    root + '.ilife-relation-tier-head {',
    '  display: flex;',
    '  align-items: center;',
    '  gap: 8px;',
    '  margin: 0;',
    '}',
    root + '.ilife-relation-tier-name {',
    '  color: var(--fg);',
    '  font-size: 13px;',
    '  font-weight: 600;',
    '}',
    root + '.ilife-relation-tier-kind {',
    '  padding: 1px 8px;',
    '  border-radius: 999px;',
    '  background: var(--soft);',
    '  color: var(--blue2);',
    '  font-size: 12px;',
    '  line-height: 1.6;',
    '}',
    root + '.ilife-relation-tier-count {',
    '  margin-left: auto;',
    '  color: var(--fg3);',
    '  font-size: 12px;',
    '}',
    root + '.ilife-relation-tier-body {',
    '  margin: 8px 0 0;',
    '}',
    /* 空层收成一条瘦条：虚线卡 ＋ 一行占位人话，不再占一整块实心卡片（空的那层白吃掉首屏一截）。 */
    root + '.ilife-relation-tier-empty {',
    '  padding: 10px 14px;',
    '  border-style: dashed;',
    '  background: var(--card);',
    '}',
    root + '.ilife-relation-tier-empty .ilife-relation-tier-body {',
    '  margin: 6px 0 0;',
    '}',
    root + '.ilife-relation-tier-empty .ilife-relation-ghost {',
    '  padding: 0;',
    '  border: 0;',
    '  background: transparent;',
    '}',
    root + '.ilife-relation-here {',
    '  display: inline-flex;',
    '  max-width: 100%;',
    '  box-sizing: border-box;',
    '  padding: 5px 14px;',
    '  border: 1px solid var(--blue);',
    '  border-radius: 999px;',
    '  background: var(--card);',
    '  color: var(--fg);',
    '  font-size: 16px;',
    '  font-weight: 600;',
    '  overflow-wrap: anywhere;',
    '}',
    root + '.ilife-relation-joint {',
    '  position: relative;',
    '  width: 2px;',
    '  height: 20px;',
    '  margin: 0 auto;',
    '  background: var(--line);',
    '}',
    root + '.ilife-relation-joint::after {',
    '  content: "";',
    '  position: absolute;',
    '  left: 50%;',
    '  bottom: 0;',
    '  width: 0;',
    '  height: 0;',
    '  border-left: 5px solid transparent;',
    '  border-right: 5px solid transparent;',
    '  border-top: 7px solid var(--blue);',
    '  transform: translateX(-50%);',
    '}',
    /* 一层里的条目行：左侧一条支线 ＋ 每行一枚本层色的圆点（图形标记，不上字），代次与菜名分槽。 */
    root + '.ilife-relation-branch {',
    '  margin: 0;',
    '  padding: 0 0 0 16px;',
    '  border-left: 2px solid var(--line);',
    '  list-style: none;',
    '}',
    root + '.ilife-relation-tier-down .ilife-relation-branch {',
    '  border-left-color: ' + TONE.down + ';',
    '}',
    root + '.ilife-relation-tier-up .ilife-relation-branch {',
    '  border-left-color: ' + TONE.up + ';',
    '}',
    root + '.ilife-relation-branch-row {',
    '  position: relative;',
    '  box-sizing: border-box;',
    '  padding: 10px 0;',
    '}',
    root + '.ilife-relation-branch-row::before {',
    '  content: "";',
    '  position: absolute;',
    '  left: -21px;',
    '  top: 14px;',
    '  box-sizing: border-box;',
    '  width: 10px;',
    '  height: 10px;',
    '  border: 2px solid var(--card);',
    '  border-radius: 999px;',
    '  background: ' + TONE.up + ';',
    '}',
    root + '.ilife-relation-tier-down .ilife-relation-branch-row::before {',
    '  background: ' + TONE.down + ';',
    '}',
    root + '.ilife-relation-tier-up .ilife-relation-branch-row::before {',
    '  background: ' + TONE.up + ';',
    '}',
    root + '.ilife-relation-branch-head {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: center;',
    '  gap: 6px 8px;',
    '}',
    root + '.ilife-relation-level {',
    '  flex: 0 0 auto;',
    '  padding: 1px 8px;',
    '  border-radius: 999px;',
    '  background: var(--soft);',
    '  color: var(--blue2);',
    '  font-size: 12px;',
    '  font-weight: 600;',
    '}',
    root + '.ilife-relation-branch-name {',
    '  min-width: 0;',
    '  color: var(--fg);',
    '  font-size: 15px;',
    '  font-weight: 600;',
    '  overflow-wrap: anywhere;',
    '}',
    root + '.ilife-relation-branch-note {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 2px 8px;',
    '  margin-top: 3px;',
    '  overflow-wrap: anywhere;',
    '}',
    /* 改动说明前的图形标记（一支笔）：给这行小字当图例，不用再写「改动」两个字。 */
    root + '.ilife-relation-branch-note-mark {',
    '  flex: 0 0 auto;',
    '  display: inline-flex;',
    '  align-items: center;',
    '  color: var(--fg3);',
    '}',
    root + '.ilife-relation-branch-note-text {',
    '  min-width: 0;',
    '  color: var(--fg2);',
    '  font-size: 12px;',
    '  line-height: 1.6;',
    '}',
    /* 宽档（≥1001px）：880 版心里三层各自竖成一条「层标 ＋ 层体」两栏，行内左右分槽把空档填掉——
       层标占左栏（图标、层名、关系类型、条数自上而下），层体占右栏，条目行左边的菜名与右边的改动说明
       各靠一边，不再是一行字悬在一张长条卡里。 */
    '@media (min-width: 1001px) {',
    root + '.ilife-relation-tier {',
    '    display: grid;',
    '    grid-template-columns: 168px minmax(0, 1fr);',
    '    column-gap: 20px;',
    '    align-items: start;',
    '  }',
    root + '.ilife-relation-tier-head {',
    '    flex-direction: column;',
    '    align-items: flex-start;',
    '    gap: 6px;',
    '  }',
    root + '.ilife-relation-tier-count {',
    '    margin-left: 0;',
    '  }',
    root + '.ilife-relation-tier-body {',
    '    margin: 0;',
    '  }',
    root + '.ilife-relation-branch-row {',
    '    display: flex;',
    '    flex-wrap: wrap;',
    '    align-items: baseline;',
    '    column-gap: 16px;',
    '    row-gap: 4px;',
    '  }',
    root + '.ilife-relation-branch-note {',
    '    margin-top: 0;',
    '  }',
    root + '.ilife-relation-ghost {',
    '    align-items: center;',
    '  }',
    root + '.ilife-relation-ornament {',
    '    display: inline-flex;',
    '  }',
    '}',
    /* 页头右侧那枝装饰树：窄档不出（首屏要留给三层树本体），宽档显出来填掉结论条右侧的空档。 */
    root + '.ilife-relation-ornament {',
    '  display: none;',
    '  flex: 0 0 auto;',
    '  align-items: center;',
    '}',
    root + '.ilife-relation-ornament svg {',
    '  display: block;',
    '}',
    /* 空层的占位件：虚线框，槽位与真条目同规格（换数据不换格子）。 */
    root + '.ilife-relation-ghost {',
    '  display: flex;',
    '  align-items: flex-start;',
    '  gap: 10px;',
    '  box-sizing: border-box;',
    '  padding: 10px 12px;',
    '  border: 1px dashed var(--line);',
    '  border-radius: 14px;',
    '  background: var(--soft);',
    '}',
    root + '.ilife-relation-ghost-mark {',
    '  flex: 0 0 auto;',
    '  width: 12px;',
    '  height: 12px;',
    '  margin-top: 3px;',
    '  border: 2px dashed var(--fg3);',
    '  border-radius: 999px;',
    '}',
    root + '.ilife-relation-ghost-body {',
    '  min-width: 0;',
    '}',
    root + '.ilife-relation-ghost-text {',
    '  margin: 0;',
    '  color: var(--fg2);',
    '  font-size: 14px;',
    '  font-weight: 600;',
    '}',
    root + '.ilife-relation-ghost-hint {',
    '  margin: 2px 0 0;',
    '  color: var(--fg3);',
    '  font-size: 12px;',
    '  line-height: 1.5;',
    '  overflow-wrap: anywhere;',
    '}',
  ].join(LF);
}
