/** slider-row · **样式段**（本件唯一的样式来源）。
 *
 *  纪律（与本层其余件同一份）：只经 `skinVar()` 读皮肤／全部规则 scope 在 `.<prefix>page-ui` 之下／
 *  零 `:root`／零 `!important`／零自定义属性／宽度只由 `@container` 判（`@media` 只判设备能力）。
 *
 *  几何契约（判据钉住）：两端键与常用档 ≥`SLIDER_ROW_TOUCH_PX`（44），相邻留 `SLIDER_ROW_GAP_PX`（8）；
 *  轨道（含拇指）高 `SLIDER_ROW_TRACK_PX`（44）＝原生 `range` 的命中盒；底与已填两条线各
 *  `SLIDER_ROW_LINE_PX`（8）高——**自绘是因为三套皮肤下原生轨道的取值不受控**（换皮只换颜色，
 *  形状归本件）。原生 `range` 本身只留拇指（透明轨道），键盘与读屏器仍走原生语义。
 */
import { skinVar } from '../skin/contract.js';
import {
  SLIDER_ROW_GAP_PX,
  SLIDER_ROW_LINE_PX,
  SLIDER_ROW_THUMB_PX,
  SLIDER_ROW_TOUCH_PX,
  SLIDER_ROW_TRACK_PX,
  sliderRowSlot,
  type SliderRowSlot,
} from './attrs.js';

/** 换行（仓库口径：不写字面换行转义）。 */
const LF = String.fromCharCode(10);

/** 窄容器阈值（px）：**本件自己的宽度**。低于它时两端键与轨道分成两行（轨道独占一行更宽好拖）。 */
const NARROW_PX = 380;

/** 按下反馈的时长（ms）：≤80ms。 */
const PRESS_MS = 80;

/** 本组件的样式段。恒返回非空 CSS 文本。 */
export function sliderRowCss(input?: { readonly prefix?: string }): string {
  const p = input !== undefined && input !== null
    && typeof input.prefix === 'string' && input.prefix !== '' ? input.prefix : 'ilife-';
  const root = '.' + p + 'page-ui';
  const box = root + ' .' + p + 'block-slider-row';
  const s = (slot: SliderRowSlot): string => root + ' .' + sliderRowSlot(slot, p);
  /** 拼在 `box` **后面**的槽类（不再带 `.<prefix>page-ui`，否则会拼出嵌套的假选择器）。 */
  const inBox = (slot: SliderRowSlot): string => ' .' + sliderRowSlot(slot, p);
  const trackH = String(SLIDER_ROW_TRACK_PX) + 'px';
  const lineH = String(SLIDER_ROW_LINE_PX) + 'px';
  const thumb = String(SLIDER_ROW_THUMB_PX) + 'px';

  return [
    '/* slider-row（滑块行 · 形态 A「滑块＋常用档＋加减」）：一条轨道、两端各一枚走一档的键、',
    '   一排常用档、**右侧永远同步一个大数字**。层次靠发丝线与软底块（小票纸零阴影、大字报刊零圆角）。 */',
    box + ' {',
    /* 宽度判据的落点：本件是**自己的容器**。 */
    '  container-type: inline-size;',
    '  display: grid;',
    '  gap: 10px;',
    '  min-width: 0;',
    '  padding: 12px 14px 14px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-body') + ';',
    '  line-height: 1.5;',
    '}',
    box + ' > * {',
    '  min-width: 0;',
    '}',
    '/* 第一行：标签 ＋ 状态字 ＋ **右侧那个大数字**（`margin-left:auto` 顶到右缘，永远在右边）。 */',
    s('head') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 4px 12px;',
    '  min-width: 0;',
    '}',
    s('label') + ' {',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 600;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 状态字：一小枚带发丝线的签，**宽度锁住**（四档词长短不一，锁住就不跳版）。 */',
    s('state') + ' {',
    '  box-sizing: border-box;',
    '  min-width: 5em;',
    '  padding: 1px 6px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 700;',
    '  letter-spacing: .04em;',
    '  text-align: center;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 大数字：本形态的识别特征（右侧那一枚），等宽数字 ＋ 等宽占位（位数变了不跳版）。 */',
    s('value') + ' {',
    '  display: inline-flex;',
    '  align-items: baseline;',
    '  gap: 3px;',
    '  margin-left: auto;',
    '  min-width: 5ch;',
    '  justify-content: flex-end;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-variant-numeric: tabular-nums;',
    '  text-align: right;',
    '}',
    s('number') + ' {',
    '  color: ' + skinVar('ink') + ';',
    '  font-size: calc(' + skinVar('fs-body') + ' * 3);',
    '  font-weight: 700;',
    '  line-height: 1.05;',
    '  overflow-wrap: anywhere;',
    '}',
    s('unit') + ' {',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-h3') + ';',
    '  font-weight: 600;',
    '}',
    '/* 轨道那一排：− 键 ＋ 轨道 ＋ ＋ 键；相邻留 ' + String(SLIDER_ROW_GAP_PX) + 'px 缝（不做连体键）。 */',
    s('row') + ' {',
    '  display: flex;',
    '  flex-wrap: nowrap;',
    '  align-items: center;',
    '  gap: ' + String(SLIDER_ROW_GAP_PX) + 'px;',
    '  min-width: 0;',
    '}',
    s('dec') + ',',
    s('inc') + ' {',
    '  flex: 0 0 auto;',
    '  display: inline-flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  box-sizing: border-box;',
    '  width: ' + String(SLIDER_ROW_TOUCH_PX) + 'px;',
    '  min-width: ' + String(SLIDER_ROW_TOUCH_PX) + 'px;',
    '  height: ' + String(SLIDER_ROW_TOUCH_PX) + 'px;',
    '  padding: 0;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: inherit;',
    '  font-size: ' + skinVar('fs-h2') + ';',
    '  font-weight: 700;',
    '  line-height: 1;',
    '  cursor: pointer;',
    '  touch-action: manipulation;',
    '  transition: transform ' + String(PRESS_MS) + 'ms cubic-bezier(.22,1,.36,1);',
    '}',
    '/* 轨道：自绘「底 ＋ 已填」两条线，原生 `range` 压在上面（透明轨道 ＋ 自绘拇指）。 */',
    s('track') + ' {',
    '  position: relative;',
    '  flex: 1 1 0;',
    '  min-width: 0;',
    '  display: flex;',
    '  align-items: center;',
    '  height: ' + trackH + ';',
    '}',
    s('base') + ',',
    s('fill') + ' {',
    '  position: absolute;',
    '  top: 50%;',
    '  left: 0;',
    '  height: ' + lineH + ';',
    '  transform: translateY(-50%);',
    '  border-radius: ' + skinVar('radius-pill') + ';',
    '}',
    s('base') + ' {',
    '  right: 0;',
    '  background: ' + skinVar('line') + ';',
    '}',
    '/* 已填：强调色只做**非文本**的底（这一条是它该出现的地方）。 */',
    s('fill') + ' {',
    '  background: ' + skinVar('accent') + ';',
    '}',
    s('input') + ' {',
    '  position: relative;',
    '  box-sizing: border-box;',
    '  width: 100%;',
    '  height: ' + trackH + ';',
    '  margin: 0;',
    '  padding: 0;',
    '  border: 0;',
    '  background: transparent;',
    '  appearance: none;',
    '  -webkit-appearance: none;',
    '  cursor: pointer;',
    '  touch-action: manipulation;',
    '}',
    /* 原生轨道的线是自绘的：这里必须**透明**（否则两套线叠在一起，皮肤一换就对不齐）。 */
    s('input') + '::-webkit-slider-runnable-track {',
    '  height: ' + lineH + ';',
    '  background: transparent;',
    '}',
    s('input') + '::-webkit-slider-thumb {',
    '  appearance: none;',
    '  -webkit-appearance: none;',
    '  box-sizing: border-box;',
    '  width: ' + thumb + ';',
    '  height: ' + thumb + ';',
    '  margin-top: calc((' + lineH + ' - ' + thumb + ') / 2);',
    '  border: 3px solid ' + skinVar('accent') + ';',
    '  border-radius: 50%;',
    '  background: ' + skinVar('surface') + ';',
    '}',
    s('input') + '::-moz-range-track {',
    '  height: ' + lineH + ';',
    '  background: transparent;',
    '}',
    s('input') + '::-moz-range-thumb {',
    '  box-sizing: border-box;',
    '  width: ' + thumb + ';',
    '  height: ' + thumb + ';',
    '  border: 3px solid ' + skinVar('accent') + ';',
    '  border-radius: 50%;',
    '  background: ' + skinVar('surface') + ';',
    '}',
    '/* 常用档那一排：当前值命中哪一枚，哪一枚实心反白 ＋ 加粗（**形＋色**两样一起给）。 */',
    s('presets') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: center;',
    '  gap: ' + String(SLIDER_ROW_GAP_PX) + 'px;',
    '  min-width: 0;',
    '}',
    s('preset') + ' {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  box-sizing: border-box;',
    '  min-width: 64px;',
    '  min-height: ' + String(SLIDER_ROW_TOUCH_PX) + 'px;',
    '  padding: 0 14px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-pill') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '  font-variant-numeric: tabular-nums;',
    '  cursor: pointer;',
    '  touch-action: manipulation;',
    '  transition: transform ' + String(PRESS_MS) + 'ms cubic-bezier(.22,1,.36,1);',
    '}',
    s('preset') + '[aria-pressed="true"] {',
    '  background: ' + skinVar('accent') + ';',
    '  border-color: ' + skinVar('accent') + ';',
    '  color: ' + skinVar('accent-ink') + ';',
    '  font-weight: 700;',
    '}',
    '/* 悬停：只包在设备能力查询里（`hover:hover`），且**不是唯一通路**。 */',
    '@media (hover:hover) and (pointer:fine) {',
    '  ' + s('dec') + ':hover:not([disabled]),',
    '  ' + s('inc') + ':hover:not([disabled]) {',
    '    background: ' + skinVar('surface-2') + ';',
    '  }',
    '  ' + s('preset') + ':hover:not([disabled]) {',
    '    border-color: ' + skinVar('ink-2') + ';',
    '  }',
    '}',
    '/* 真按下：只动 `transform`（80ms 内看得见）。 */',
    s('dec') + ':active:not([disabled]),',
    s('inc') + ':active:not([disabled]),',
    s('preset') + ':active:not([disabled]) {',
    '  transform: scale(.98);',
    '}',
    '/* 可见焦点：两端键、常用档与轨道（原生 `range`）都要看得见。 */',
    box + ' :focus-visible {',
    '  outline: 2px solid ' + skinVar('accent') + ';',
    '  outline-offset: 2px;',
    '}',
    '/* 更新中：大数字与轨道保持原样（宽度锁住），状态字那一枚换成「更新中」。 */',
    box + '.is-loading [aria-disabled="true"] {',
    '  cursor: progress;',
    '}',
    '/* 禁用：说不出为什么不能拖是不许留的中间档（渲染期就要求给 `disabledReason`）。 */',
    box + ' [disabled],',
    box + '.is-disabled [aria-disabled="true"] {',
    '  background: ' + skinVar('surface-2') + ';',
    '  color: ' + skinVar('ink-3') + ';',
    '  border-color: ' + skinVar('line') + ';',
    '  cursor: not-allowed;',
    '}',
    box + '.is-disabled' + inBox('track') + ',',
    box + '.is-disabled' + inBox('value') + ' {',
    '  opacity: .55;',
    '}',
    '/* 未设置：大数字写 `—`、已填为 0（渲染期内联写死 `width: 0%`，状态字说「未设置」）——',
    '   空态是设计过的，不是漏渲染。 */',
    '/* 错误说明：写在控件旁边（控件 `aria-describedby` 指向它），**不只染色**。 */',
    s('error') + ' {',
    '  margin: 0;',
    '  padding-left: 8px;',
    '  border-left: 2px solid ' + skinVar('danger') + ';',
    '  color: ' + skinVar('danger') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    box + '.is-invalid' + inBox('input') + '::-webkit-slider-thumb {',
    '  border-color: ' + skinVar('danger') + ';',
    '}',
    '/* 口径行：区间与常用档怎么定的（**要读的正文**，走 ink-2 不走更浅的弱文字档）。 */',
    s('caliber') + ' {',
    '  margin: 0;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 窄容器（<' + String(NARROW_PX) + 'px）：两端键与轨道分成两行——轨道独占一行更好拖，',
    '   数字也不被挤。判的是**本件自己的宽度**（不用 `@media` 判宽度）。 */',
    '@container (max-width: ' + String(NARROW_PX) + 'px) {',
    '  ' + s('row') + ' {',
    '    display: grid;',
    '    grid-template-columns: auto minmax(0, 1fr) auto;',
    '    grid-template-areas: "dec track inc";',
    '  }',
    '  ' + s('dec') + ' {',
    '    grid-area: dec;',
    '  }',
    '  ' + s('inc') + ' {',
    '    grid-area: inc;',
    '  }',
    '  ' + s('track') + ' {',
    '    grid-area: track;',
    '  }',
    '}',
    '/* 减动效档：不许有东西卡在半路。 */',
    '@media (prefers-reduced-motion:reduce) {',
    '  ' + s('dec') + ',',
    '  ' + s('inc') + ',',
    '  ' + s('preset') + ' {',
    '    transition: none;',
    '  }',
    '}',
  ].join(LF);
}
