/** kanban-columns · **样式段**（本件唯一的样式来源）。
 *
 *  纪律（与本节其余件同一份）：
 *   · 只经 `skinVar()` 读皮肤 —— 组件里**不写** `var(--ilife-…)`（兜底链只许住在 `skin/contract.ts`）；
 *   · 全部规则 scope 在 `.<prefix>page-ui` 之下（不开本配方的页零命中）；不写 `:root`／`!important`、不新增 token 名；
 *   · **宽度只许容器判**：本件自己声明容器，窄档走 `@container`；媒体查询只判设备能力
 *     （悬停是不是增强、要不要减动效），**一条视口宽度查询都没有**；
 *   · 列名／计数／卡标题**永不截断**：样式段里没有 `text-overflow`／`line-clamp`／`nowrap`。
 *
 *  几何事实（判据钉住，数只写在这里一处）：
 *   · 卡／收纳键／加键／分段 ≥`KANBAN_COLUMNS_TOUCH_PX`（44）高；卡与卡之间留
 *     `KANBAN_COLUMNS_GAP_PX`（8）px 缝；空列与有卡列同高（列区 `stretch` ＋ 列身 `flex:1`）；
 *   · **形态 `grouped` 那一段在 `style-grouped.ts`**（同一份纪律、同一个前缀；每一条都钉在
 *     `.is-grouped` 上，`status` 档零命中）；**窄容器那一段在 `style-narrow.ts`**（搬家只为行数）；
 *     拿起的卡「站起来」往上挪的位移＝`KANBAN_COLUMNS_LIFT_PX`（地板口径写在 `attrs.ts` 那两枚常量上）。
 */
import { skinVar } from '../skin/contract.js';
import {
  KANBAN_COLUMNS_CARD_MIN_PX,
  KANBAN_COLUMNS_CONTAINER,
  KANBAN_COLUMNS_GAP_PX,
  KANBAN_COLUMNS_HOVER_QUERY,
  KANBAN_COLUMNS_LIFT_PX,
  KANBAN_COLUMNS_TOUCH_PX,
  kanbanColumnsSlot,
  type KanbanColumnsSlot,
} from './attrs.js';
import { kanbanColumnsGroupedCss } from './style-grouped.js';
import { kanbanColumnsNarrowCss } from './style-narrow.js';

/** 换行（仓库口径：不写字面换行转义）。 */
const LF = String.fromCharCode(10);

/** 本组件的样式段。恒返回非空 CSS 文本。 */
export function kanbanColumnsCss(input?: { readonly prefix?: string }): string {
  const p = input !== undefined && input !== null
    && typeof input.prefix === 'string' && input.prefix !== '' ? input.prefix : 'ilife-';
  const root = '.' + p + 'page-ui';
  const box = root + ' .' + p + 'block-kanban-columns';
  /** **槽类名**（不带 scope）：写「某槽下的子件」时只许用它——把带 scope 的选择器再拼一次，
   *  会拼出永不命中的死规则（见 `page-head/style.ts` 的注释）。 */
  const sc = (slot: KanbanColumnsSlot): string => '.' + kanbanColumnsSlot(slot, p);
  /** **带 scope 的完整选择器**（一条规则打头用）。 */
  const s = (slot: KanbanColumnsSlot): string => root + ' ' + sc(slot);
  const hover = '@media ' + KANBAN_COLUMNS_HOVER_QUERY;

  return [
    '/* kanban-columns（看板列 · 形态 status「按状态分列」）：列＝状态，卡在列之间挪就是改状态。',
    '   挪动不走拖拽：点卡选中、再点目标列的收纳键；空列撑到同高、列头与计数一直在。 */',
    s('host') + ' {',
    /* 宽度判据的落点：本件是**自己的容器**——嵌进侧栏／面板／卡片时照样按自己的宽度折行。 */
    '  container-type: inline-size;',
    '  container-name: ' + KANBAN_COLUMNS_CONTAINER + ';',
    '  display: grid;',
    '  gap: 8px;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-body') + ';',
    '  line-height: 1.5;',
    '}',
    '/* 窄档的分段切换：宽档整条不出（三列本来就并排，不需要第二套入口）。 */',
    s('switch') + ' {',
    '  display: none;',
    '  min-width: 0;',
    '}',
    s('seg') + ' {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  min-height: ' + String(KANBAN_COLUMNS_TOUCH_PX) + 'px;',
    '  padding: 0 8px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 600;',
    '  cursor: pointer;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 当前那一段是「有文字的选中面」那一档：软底 ＋ 主色字 ＋ 主色描边（不是实心墨块）。 */',
    s('seg') + '.is-on {',
    '  background: ' + skinVar('accent-soft') + ';',
    '  border-color: ' + skinVar('accent') + ';',
    '  color: ' + skinVar('accent-text') + ';',
    '  font-weight: 700;',
    '}',
    '/* 列区：宽档按列数并排（`is-n2／n3／n4` 照实写在标记上）；列间 12px 缝。 */',
    s('cols') + ' {',
    '  display: grid;',
    '  gap: 12px;',
    '  align-items: stretch;',
    '  min-width: 0;',
    '}',
    s('cols') + '.is-n2 { grid-template-columns: repeat(2, minmax(0, 1fr)); }',
    s('cols') + '.is-n3 { grid-template-columns: repeat(3, minmax(0, 1fr)); }',
    s('cols') + '.is-n4 { grid-template-columns: repeat(4, minmax(0, 1fr)); }',
    '/* 一列：纸面 ＋ 发丝线；纵向 flex——列身吃掉剩下的高度，空列与有卡列同高。 */',
    s('col') + ' {',
    '  display: flex;',
    '  flex-direction: column;',
    '  min-width: 0;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  overflow: hidden;',
    '}',
    '/* 列头两级字：第一级（列名 ＋ 计数）＋ 第二级（它是干什么的）＋ 加键。',
    '   列名与计数**换行、不截断**（样式段里没有省略手段，判据逐字扫）。 */',
    s('head') + ' {',
    '  display: grid;',
    '  grid-template-columns: minmax(0, 1fr) auto;',
    '  grid-template-areas: "name add" "count add" "purpose purpose";',
    '  gap: 2px 8px;',
    '  align-items: center;',
    '  padding: 8px 6px 8px 12px;',
    '  background: ' + skinVar('surface-2') + ';',
    '  border-bottom: 1px solid ' + skinVar('line') + ';',
    '  min-width: 0;',
    '}',
    s('name') + ' {',
    '  grid-area: name;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 700;',
    '  overflow-wrap: anywhere;',
    '}',
    s('count') + ' {',
    '  grid-area: count;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 700;',
    '  font-variant-numeric: tabular-nums;',
    '  overflow-wrap: anywhere;',
    '}',
    s('purpose') + ' {',
    '  grid-area: purpose;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '  line-height: 1.4;',
    '  overflow-wrap: anywhere;',
    '}',
    s('add') + ' {',
    '  grid-area: add;',
    '  align-self: center;',
    '  display: inline-flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  width: ' + String(KANBAN_COLUMNS_TOUCH_PX) + 'px;',
    '  height: ' + String(KANBAN_COLUMNS_TOUCH_PX) + 'px;',
    '  flex: none;',
    '  border: 0;',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: none;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: 18px;',
    '  line-height: 1;',
    '  cursor: pointer;',
    '}',
    '/* 列身：卡与卡之间 8px 缝（相邻触控目标的地板）；`flex:1` 把空列撑到同高。 */',
    s('body') + ' {',
    '  display: grid;',
    '  gap: ' + String(KANBAN_COLUMNS_GAP_PX) + 'px;',
    '  align-content: start;',
    '  flex: 1 1 auto;',
    '  min-height: 120px;',
    '  padding: 10px 12px 12px;',
    '  min-width: 0;',
    '}',
    '/* 一张卡：整卡就是那颗按钮（命中盒＝整卡）。卡里**没有第二颗按钮**。 */',
    s('card') + ' {',
    '  display: grid;',
    '  gap: 3px;',
    '  width: 100%;',
    '  min-height: ' + String(KANBAN_COLUMNS_CARD_MIN_PX) + 'px;',
    '  padding: 10px 12px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  text-align: start;',
    '  cursor: pointer;',
    '  transition: transform 80ms ease;',
    '  min-width: 0;',
    '  overflow-wrap: anywhere;',
    '}',
    s('title') + ' {',
    '  color: ' + skinVar('ink') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 700;',
    '  overflow-wrap: anywhere;',
    '}',
    s('meta') + ' {',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1.45;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 卡上那枚状态：记号（形）＋ 列名（字）——不只靠颜色，也不只靠列位置。 */',
    s('badge') + ' {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  gap: 5px;',
    '  margin-top: 3px;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 700;',
    '  overflow-wrap: anywhere;',
    '}',
    s('mark') + ' {',
    '  color: ' + skinVar('accent') + ';',
    '  font-style: normal;',
    '}',
    '/* 被选中的卡站起来（往上挪 `KANBAN_COLUMNS_LIFT_PX`）：软底 ＋ 主色字 ＋ 主色描边',
    '   （「有文字的选中面」那一档）。位移是这道形占的卡间缝，地板口径见 `attrs.ts` 那两枚常量。 */',
    s('card') + '.is-picked {',
    '  background: ' + skinVar('accent-soft') + ';',
    '  border-color: ' + skinVar('accent') + ';',
    '  transform: translateY(-' + String(KANBAN_COLUMNS_LIFT_PX) + 'px);',
    '}',
    s('card') + '.is-picked > ' + sc('title') + ' { color: ' + skinVar('accent-text') + '; }',
    s('card') + '.is-picked > ' + sc('badge') + ' { color: ' + skinVar('accent-text') + '; }',
    '/* 落点线：3px 实线 ＋ 写出放这里＝标记为哪一列（无文字的条走主色实底那一档）。 */',
    s('drop') + ' {',
    '  display: flex;',
    '  align-items: center;',
    '  gap: 8px;',
    '  margin: 0;',
    '  min-height: ' + String(KANBAN_COLUMNS_TOUCH_PX) + 'px;',
    '  padding-left: 8px;',
    '  border-left: 3px solid ' + skinVar('accent') + ';',
    '  color: ' + skinVar('accent-text') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 700;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 收纳键：每列一枚。选中后可用＝主动作档；没选中时按不动（`disabled`，不是藏起来）。 */',
    s('receive') + ' {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  min-height: ' + String(KANBAN_COLUMNS_TOUCH_PX) + 'px;',
    '  padding: 0 14px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-pill') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '  cursor: not-allowed;',
    '  overflow-wrap: anywhere;',
    '}',
    s('receive') + ':not(:disabled) {',
    '  background: ' + skinVar('accent-soft') + ';',
    '  border-color: ' + skinVar('accent') + ';',
    '  color: ' + skinVar('accent-text') + ';',
    '  font-weight: 700;',
    '  cursor: pointer;',
    '}',
    s('receive') + ':not(:disabled):active { transform: scale(.98); }',
    '/* 空槽：虚线框 ＋ 两句话（空列是设计过的态，不是留白）。 */',
    s('slot') + ' {',
    '  display: grid;',
    '  place-items: center;',
    '  align-self: stretch;',
    '  min-height: 72px;',
    '  margin: 0;',
    '  padding: 10px;',
    '  border: 1px dashed ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('surface-2') + ';',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '  text-align: center;',
    '  line-height: 1.5;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 状态句与脚注：弱文字档走 `ink-2`（要读的正文不走 `ink-3`，宁可深一档）。 */',
    s('status') + ' {',
    '  margin: 0;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    s('cancel') + ' {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  justify-self: start;',
    '  min-height: ' + String(KANBAN_COLUMNS_TOUCH_PX) + 'px;',
    '  padding: 0 16px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-pill') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 600;',
    '  cursor: pointer;',
    '}',
    s('cancel') + ':active { transform: scale(.98); }',
    s('hint') + ' {',
    '  margin: 0;',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    box + ' :focus-visible {',
    '  outline: 2px solid ' + skinVar('accent') + ';',
    '  outline-offset: 2px;',
    '}',
    '/* 悬停只许是增强：卡沿加深一档，不许是唯一通路（通路是点选与收纳键）。 */',
    hover + ' {',
    '  ' + s('card') + ':hover { border-color: ' + skinVar('accent') + '; }',
    '  ' + s('add') + ':hover { color: ' + skinVar('accent-text') + '; }',
    '}',
    '@media (prefers-reduced-motion: reduce) {',
    '  ' + s('card') + ', ' + s('receive') + ', ' + s('cancel') + ' { transition: none; transform: none; }',
    '}',
    '/* 形态 `grouped` 那一段（`style-grouped.ts`）：每一条都钉在 `.is-grouped` 上，`status` 档零命中；',
    '   插在窄容器段**之前**（搬走的是行数，不是取值）。 */',
    kanbanColumnsGroupedCss({ prefix: p }),
    '/* 窄容器段（`style-narrow.ts`）：同一份纪律、同一个前缀，插在这里——',
    '   搬走的是行数，不是取值；本函数的产物逐字节不变。 */',
    kanbanColumnsNarrowCss({ prefix: p }),
  ].join(LF);
}
