/** multi-checks · **样式段**（本件唯一的样式来源）。
 *
 *  纪律（与本节其余件同一份）：
 *   · 只经 `skinVar()` 读皮肤——组件里**不写**手写的 CSS 变量（兜底链只许住在 `skin/contract.ts`）；
 *   · 全部规则 scope 在 `.<prefix>page-ui` 之下；不写 `:root`／`!important`、不新增 token 名；
 *   · **宽度只许容器判**：本件自己是容器（`container-type: inline-size`，落在盒子上），
 *     窄档调整走 `@container`；`@media` 只判设备能力，不判宽度。
 *
 *  几何契约（判据钉住）：
 *   · 整行／整块是命中区 ⇒ 触控目标 ≥44×44（行 48px、全选块与组头 44px、动作按钮 44px）；
 *   · 勾选态**至少两重标记**：勾选框里的对钩（字）＋ 勾中那一行左端的 4px 竖条（形状）；
 *     底色是第三重（颜色）；皮肤「大字报刊」下强调色＝墨黑 ⇒ 前两重必须自己扛。
 */
import { skinVar } from '../skin/contract.js';
import { MULTI_CHECKS_PRIMARY_ATTR, multiChecksSlot } from './attrs.js';

/** 换行（仓库口径：不写字面换行转义）。 */
const LF = String.fromCharCode(10);

/** 触控目标的地板（px）：全宽口径，不只窄屏。 */
export const MULTI_CHECKS_MIN_TARGET_PX = 44;
/** 一行的高度下限（px）：比地板高一档（行里有两行字的情形也放得下）。 */
export const MULTI_CHECKS_ROW_MIN_HEIGHT_PX = 48;
/** 勾选框的方径（px）：装饰盒，可以小于地板（命中区由整行承担）。 */
export const MULTI_CHECKS_BOX_PX = 22;
/** 勾中时左端那道竖条的宽度（px）——**形状**那一重标记。 */
export const MULTI_CHECKS_BAR_PX = 4;
/** 窄容器阈值（px）：行右端的金额改走「另起一行、左对齐」。**判的是本件自己的宽度**。 */
export const MULTI_CHECKS_NARROW_PX = 420;

/** 本组件的样式段。恒返回非空 CSS 文本。 */
export function multiChecksCss(input?: { readonly prefix?: string }): string {
  const p = input !== undefined && input !== null
    && typeof input.prefix === 'string' && input.prefix !== '' ? input.prefix : 'ilife-';
  const root = '.' + p + 'page-ui';
  const box = root + ' .' + p + 'block-multi-checks';
  const s = (slot: Parameters<typeof multiChecksSlot>[0]): string => root + ' .' + multiChecksSlot(slot, p);
  /** **裸类名**：用在复合选择器的中段（`X > .槽`、`X ~ .槽`）。
   *  `s()` 自带作用域前缀，只许当选择器的**开头**——把它接在 `>` 后面会拼出
   *  `.ilife-page-ui X > .ilife-page-ui .槽`，那种规则永远匹配不到
   *  （2026-09 实拍：勾选框里的对钩一个都没画出来，就是这一处拼错）。 */
  const c = (slot: Parameters<typeof multiChecksSlot>[0]): string => '.' + multiChecksSlot(slot, p);
  const row = s('row');

  return [
    '/* multi-checks（多选清单 · 形态 A「顶上全选 ＋ 分组复选 ＋ 底下动作」）：批量改之前先挑。',
    '   层次不靠阴影与大圆角（小票纸零阴影、大字报刊零圆角）：靠发丝线、字重与尺度差 ⇒ 换皮只换取值。 */',
    box + ' {',
    '  display: block;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-body') + ';',
    '  line-height: 1.5;',
    '}',
    '/* 盒子自带纸面（不必外挂纸面页框）：边界清楚，否则"清单到哪儿为止"看不出来。 */',
    s('box') + ' {',
    /* 宽度判据的落点：本件是**自己的容器**——嵌进侧栏／面板／卡片时照样按自己的宽度折行。 */
    '  container-type: inline-size;',
    '  display: grid;',
    '  gap: 8px;',
    '  min-width: 0;',
    '  box-sizing: border-box;',
    '  padding: 12px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius') + ';',
    '  background: ' + skinVar('surface') + ';',
    '}',
    '/* 顶上那句「这清单是干什么的」：主字 ＋ 次段，都能换行（**不许 `…` 截断**）。 */',
    s('label') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 4px 10px;',
    '  margin: 0;',
    '  min-width: 0;',
    '}',
    s('label') + ' > b {',
    '  color: ' + skinVar('ink') + ';',
    '  font-weight: 700;',
    '  overflow-wrap: anywhere;',
    '}',
    s('hint') + ' {',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 400;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 全选头：一枚总开关 ＋ 已选数。发丝线把它与清单分开。 */',
    s('top') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: center;',
    '  gap: 4px 12px;',
    '  padding-bottom: 8px;',
    '  border-bottom: 1px solid ' + skinVar('line') + ';',
    '}',
    s('all') + ' {',
    '  position: relative;',
    '  display: inline-flex;',
    '  align-items: center;',
    '  gap: 10px;',
    '  box-sizing: border-box;',
    '  min-height: ' + String(MULTI_CHECKS_MIN_TARGET_PX) + 'px;',
    '  padding: 0 8px 0 4px;',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  color: ' + skinVar('ink') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 700;',
    '  cursor: pointer;',
    '}',
    '/* 已选数：等宽数字（数位一变宽就不跳版）。**不写 `nowrap`**：溢出比换行更难看。 */',
    s('count') + ' {',
    '  margin-left: auto;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 700;',
    '  font-variant-numeric: tabular-nums;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 勾选框：方盒（未勾）→ 方盒＋对钩（勾上）。盒与钩是**形状**，不靠色。 */',
    s('cb') + ' {',
    '  position: relative;',
    '  display: block;',
    '  flex: none;',
    '  width: ' + String(MULTI_CHECKS_BOX_PX) + 'px;',
    '  height: ' + String(MULTI_CHECKS_BOX_PX) + 'px;',
    '  box-sizing: border-box;',
    '  border: 2px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('surface') + ';',
    '}',
    '/* 真状态永远住在原生框上：勾上／半勾的显形都从 `:checked` 与 `:indeterminate` 出发。 */',
    s('all') + ' > input:checked ~ ' + c('cb') + ',',
    s('gh') + ' > input:checked ~ ' + c('cb') + ',',
    row + ' > input:checked ~ ' + c('cb') + ',',
    s('all') + ' > input:indeterminate ~ ' + c('cb') + ',',
    s('gh') + ' > input:indeterminate ~ ' + c('cb') + ' {',
    '  border-color: ' + skinVar('accent') + ';',
    '  background: ' + skinVar('accent') + ';',
    '}',
    '/* 对钩（第二重：字）；半勾用一道横杠（形状分得出「勾了一部分」与「全勾」）。 */',
    s('all') + ' > input:checked ~ ' + c('cb') + '::after,',
    s('gh') + ' > input:checked ~ ' + c('cb') + '::after,',
    row + ' > input:checked ~ ' + c('cb') + '::after {',
    '  content: "\\2713";',
    '  position: absolute;',
    '  inset: 0;',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  color: ' + skinVar('accent-ink') + ';',
    '  font-size: 13px;',
    '  font-weight: 800;',
    '  line-height: 1;',
    '}',
    s('all') + ' > input:indeterminate ~ ' + c('cb') + '::after,',
    s('gh') + ' > input:indeterminate ~ ' + c('cb') + '::after {',
    '  content: "";',
    '  position: absolute;',
    '  left: 4px;',
    '  right: 4px;',
    '  top: 50%;',
    '  height: 2px;',
    '  margin-top: -1px;',
    '  background: ' + skinVar('accent-ink') + ';',
    '}',
    '/* 原生框：视觉隐藏但**仍在无障碍树里**（1px 盒 ＋ `opacity:0`，不是 `display:none`）。 */',
    s('all') + ' > input[type="checkbox"],',
    s('gh') + ' > input[type="checkbox"],',
    row + ' > input[type="checkbox"] {',
    '  position: absolute;',
    '  width: 1px;',
    '  height: 1px;',
    '  opacity: 0;',
    '  pointer-events: none;',
    '}',
    '/* 逐条那一列：分组之间一条发丝线。 */',
    s('list') + ' {',
    '  display: grid;',
    '  min-width: 0;',
    '}',
    s('grp') + ' {',
    '  display: grid;',
    '  min-width: 0;',
    '}',
    '/* 分组头：整块是命中区（勾上＝这一组全勾）；底色与行分开，一眼看出哪几行是一组。 */',
    s('gh') + ' {',
    '  position: relative;',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: center;',
    '  gap: 2px 10px;',
    '  box-sizing: border-box;',
    '  min-height: ' + String(MULTI_CHECKS_MIN_TARGET_PX) + 'px;',
    '  padding: 6px 8px;',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('surface-2') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 700;',
    '  cursor: pointer;',
    '}',
    s('gh-title') + ' {',
    '  min-width: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  overflow-wrap: anywhere;',
    '}',
    s('gh-note') + ' {',
    '  margin-left: auto;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 700;',
    '  font-variant-numeric: tabular-nums;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 一行：勾选框 ＋ 主字（带副语）＋ 右端金额。整行是命中区（≥48px）。 */',
    row + ' {',
    '  position: relative;',
    '  display: grid;',
    '  grid-template-columns: ' + String(MULTI_CHECKS_BOX_PX) + 'px minmax(0, 1fr) auto;',
    '  gap: 2px 10px;',
    '  align-items: center;',
    '  box-sizing: border-box;',
    '  min-height: ' + String(MULTI_CHECKS_ROW_MIN_HEIGHT_PX) + 'px;',
    '  padding: 7px 8px;',
    '  cursor: pointer;',
    '}',
    s('grp') + ' > ' + c('row') + ' + ' + c('row') + ' {',
    '  border-top: 1px solid ' + skinVar('line') + ';',
    '}',
    s('nm') + ' {',
    '  min-width: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 600;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 副语与禁用原因：各占一行小字（不给就不出，不留空位）。 */',
    s('note') + ', ' + s('why') + ' {',
    '  display: block;',
    '  margin-top: 1px;',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-style: normal;',
    '  font-weight: 500;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 金额：右端等宽数字。**不写 `nowrap`**：金额长到装不下时宁可换行，也不横着溢出。 */',
    s('amt') + ' {',
    '  text-align: right;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 700;',
    '  font-variant-numeric: tabular-nums;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 勾中的行：第一重（形状）＝左端竖条；第三重（颜色）＝软底。 */',
    row + ':has(input:checked) {',
    '  background: ' + skinVar('accent-soft') + ';',
    '  box-shadow: inset ' + String(MULTI_CHECKS_BAR_PX) + 'px 0 0 ' + skinVar('accent') + ';',
    '}',
    '/* 鼠标悬停只是**提示**，不是唯一通路（勾选与焦点各有自己的标记）。 */',
    '@media (hover: hover) and (pointer: fine) {',
    '  ' + row + ':not(:has(input:checked)):not(:has(input[disabled])):hover {',
    '    background: ' + skinVar('surface-2') + ';',
    '  }',
    '  ' + s('act') + ':not([disabled]):hover {',
    '    border-color: ' + skinVar('ink-3') + ';',
    '  }',
    '}',
    '/* 焦点：原生框收到键盘焦点时，整行／整块显形（**可见焦点，≥2px**）。 */',
    row + ':has(input:focus-visible),',
    s('all') + ':has(input:focus-visible),',
    s('gh') + ':has(input:focus-visible) {',
    '  outline: 2px solid ' + skinVar('accent') + ';',
    '  outline-offset: -2px;',
    '}',
    s('act') + ':focus-visible {',
    '  outline: 2px solid ' + skinVar('accent') + ';',
    '  outline-offset: 2px;',
    '}',
    '/* 底下那一排：合计 ＋ 动作按钮（按钮在**下面**，正是本形态的样子）。 */',
    s('bar') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: center;',
    '  gap: 8px;',
    '  padding-top: 10px;',
    '  border-top: 1px solid ' + skinVar('line') + ';',
    '}',
    s('sum') + ' {',
    '  margin-right: auto;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 600;',
    '  font-variant-numeric: tabular-nums;',
    '  overflow-wrap: anywhere;',
    '}',
    s('act') + ' {',
    '  box-sizing: border-box;',
    '  min-height: ' + String(MULTI_CHECKS_MIN_TARGET_PX) + 'px;',
    '  padding: 0 14px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  color: ' + skinVar('ink') + ';',
    '  font: inherit;',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 700;',
    '  cursor: pointer;',
    '  transition: transform 80ms cubic-bezier(.22, 1, .36, 1);',
    '}',
    '/* 主按钮：强调底 ＋ 强调底上的字（`accent-ink` 是**强调底上的字色**那一档）。',
    '   挂在 `data-*` 标记上（不挂 `is-primary` 这类修饰类：短类名会与别件撞名）。 */',
    s('act') + '[' + MULTI_CHECKS_PRIMARY_ATTR + '="1"] {',
    '  border-color: ' + skinVar('accent') + ';',
    '  background: ' + skinVar('accent') + ';',
    '  color: ' + skinVar('accent-ink') + ';',
    '}',
    '/* 真按下：缩一格（≤80ms 内回弹；只动 transform，不触发布局）。 */',
    s('act') + ':active {',
    '  transform: scale(.98);',
    '}',
    '/* 按不动：`cursor: not-allowed` ＋ 把"为什么"指给底下那句读数（`aria-describedby`）。 */',
    s('act') + '[disabled] {',
    '  cursor: not-allowed;',
    '  border-color: ' + skinVar('line') + ';',
    '  background: ' + skinVar('surface-2') + ';',
    '  color: ' + skinVar('ink-3') + ';',
    '}',
    '/* 禁用与加载：行点不动（原因那句由标记渲染在行里）。判禁用走**原生** `:has(input[disabled])`；',
    '   判加载走根上的 `data-*`——状态只有一处事实，不另挂修饰类。 */',
    row + ':has(input[disabled]) {',
    '  cursor: not-allowed;',
    '}',
    row + ':has(input[disabled]) ' + c('nm') + ', ' + row + ':has(input[disabled]) ' + c('amt') + ' {',
    '  color: ' + skinVar('ink-2') + ';',
    '}',
    '/* 空态与加载态那一句：弱文字 ＋ 设计过的内距（不是留白）。 */',
    s('empty') + ', ' + s('loading') + ' {',
    '  margin: 0;',
    '  padding: 12px 14px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 错态：写在控件旁边（不是只染色），并带一枚记号字。 */',
    s('error') + ' {',
    '  display: flex;',
    '  gap: 6px;',
    '  margin: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 600;',
    '  overflow-wrap: anywhere;',
    '}',
    s('error') + '::before {',
    '  content: "\\26A0";',
    '  flex: none;',
    '  color: ' + skinVar('ink-2') + ';',
    '}',
    '/* 窄容器（<' + String(MULTI_CHECKS_NARROW_PX) + 'px）：金额另起一行、左对齐（不再与主字抢那一行）。',
    '   判的是**本件自己的宽度**：本件会被嵌进侧栏／面板／卡片，视口宽 ≠ 组件宽（所以这里不用 `@media`）。 */',
    '@container (max-width: ' + String(MULTI_CHECKS_NARROW_PX) + 'px) {',
    '  ' + row + ' {',
    '    grid-template-columns: ' + String(MULTI_CHECKS_BOX_PX) + 'px minmax(0, 1fr);',
    '  }',
    '  ' + s('amt') + ' {',
    '    grid-column: 2;',
    '    text-align: left;',
    '  }',
    '}',
    '/* 动效偏好：只关过渡，不关状态（状态不许卡在半路 ⇒ 不用 `transitionend` 驱动任何东西）。 */',
    '@media (prefers-reduced-motion: reduce) {',
    '  ' + s('act') + ' {',
    '    transition: none;',
    '  }',
    '}',
  ].join(LF);
}
