/** drag-sort · **样式段**（本件唯一的样式来源）。
 *
 *  纪律（与本层其余件同一份）：
 *   · 只经 `skinVar()` 读皮肤 —— 组件里**不写** `var(--ilife-…)`（兜底链只许住在 `skin/contract.ts`）；
 *   · 全部规则 scope 在 `.<prefix>page-ui` 之下（不开本配方的页零命中）；不写 `:root`／`!important`、不新增 token 名；
 *   · **宽度只许容器判**：根自己声明 `container`，右端读数的折行走 `@container`；媒体查询只判设备能力
 *     （悬停是不是增强、要不要减动效），**一条视口宽度查询都没有**；
 *   · 序号与名称**永不截断**：长了换行，样式段里没有 `text-overflow`／`line-clamp`／`nowrap`。
 *
 *  三样东西的画法（形 ＋ 字，不只靠颜色）：
 *   · 拿起的行：往上挪 2px ＋ 1px 强调描边 ＋ 左侧 2px 主色侧标（「整行选中」那一档的法条口径）＋
 *     次要面底；行内主字仍是墨色；
 *   · 原位空槽：虚线框 ＋ 强调软底 ＋ 强调字（淡洗底上的字走文本档，对比地板 4.5 那一档）；
 *   · 落点线：3px 实线通栏 ＋ 右端一枚胶囊写出放第几位。
 */
import { skinVar } from '../skin/contract.js';
import {
  DRAG_SORT_CONTAINER,
  DRAG_SORT_GAP_PX,
  DRAG_SORT_HOVER_QUERY,
  DRAG_SORT_NARROW_PX,
  DRAG_SORT_ROW_MIN_PX,
  DRAG_SORT_TOUCH_PX,
  dragSortSlot,
  type DragSortSlot,
} from './attrs.js';

/** 换行（仓库口径：不写字面换行转义）。 */
const LF = String.fromCharCode(10);

/** 本组件的样式段。恒返回非空 CSS 文本。 */
export function dragSortCss(input?: { readonly prefix?: string }): string {
  const p = input !== undefined && input !== null
    && typeof input.prefix === 'string' && input.prefix !== '' ? input.prefix : 'ilife-';
  const root = '.' + p + 'page-ui';
  /** 带 scope 的完整选择器（一条规则打头用）。 */
  const s = (slot: DragSortSlot): string => root + ' ' + sc(slot);
  /** **槽类名**（不带 scope）：写「某槽下的子件」时只许用它——把带 scope 的选择器再拼一次，
   *  会拼出 `.…page-ui .A > .…page-ui .B` 这种**永不命中**的死规则。 */
  function sc(slot: DragSortSlot): string {
    return '.' + dragSortSlot(slot, p);
  }
  const hover = '@media ' + DRAG_SORT_HOVER_QUERY;

  return [
    '/* drag-sort（拖拽排序清单 · 形态 lift「拖拽中」）：',
    '   卡头 ＋ 行区（把手 ＋ 序号 ＋ 名称 ＋ 读数）＋ 状态句 ＋ 取消键；拿起态三样齐。 */',
    root + ' ' + '.' + p + 'block-drag-sort {',
    '  display: grid;',
    '  gap: 10px;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-body') + ';',
    '  line-height: 1.5;',
    '  container: ' + DRAG_SORT_CONTAINER + ' / inline-size;',
    '}',
    '/* 卡头：标题 ＋ 右端那句拿法；一窄就整段折到下一行（不压字、不横滑）。 */',
    s('hd') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 6px 10px;',
    '  min-width: 0;',
    '  padding: 2px;',
    '}',
    s('title') + ' {',
    '  font-size: ' + skinVar('fs-h3') + ';',
    '  font-weight: 700;',
    '  overflow-wrap: anywhere;',
    '}',
    s('hint') + ' {',
    '  margin-left: auto;',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '  line-height: 1.5;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 行区：行与行之间那道缝（相邻触控目标的让手位，8px）。 */',
    s('list') + ' {',
    '  display: grid;',
    '  gap: ' + String(DRAG_SORT_GAP_PX) + 'px;',
    '  min-width: 0;',
    '}',
    '/* 一行：把手 ＋ 序号 ＋ 名称（吃剩余宽）＋ 右端读数 ＋ 位置读数；整段 wrap，不断字。 */',
    s('row') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: center;',
    '  gap: ' + String(DRAG_SORT_GAP_PX) + 'px 10px;',
    '  min-height: ' + String(DRAG_SORT_ROW_MIN_PX) + 'px;',
    '  min-width: 0;',
    '  padding: 6px 10px 6px 6px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  transition: transform 80ms ease;',
    '}',
    '/* 拖起把手：44×44 的真按钮；`touch-action: none` 让触屏上的拖那条路收得到 pointermove。 */',
    s('handle') + ' {',
    '  flex: none;',
    '  display: inline-flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  width: ' + String(DRAG_SORT_TOUCH_PX) + 'px;',
    '  height: ' + String(DRAG_SORT_TOUCH_PX) + 'px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('surface-2') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: 15px;',
    '  letter-spacing: 1px;',
    '  cursor: grab;',
    '  touch-action: none;',
    '  transition: transform 80ms ease;',
    '}',
    s('handle') + ':active { transform: scale(.98); }',
    '/* 序号：那一位的数（等宽数字位；**永不截断**）。 */',
    s('index') + ' {',
    '  flex: none;',
    '  min-width: 20px;',
    '  text-align: center;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 700;',
    '  font-variant-numeric: tabular-nums;',
    '}',
    s('text') + ' { min-width: 0; flex: 1 1 140px; overflow-wrap: anywhere; }',
    '/* 名称：这一行的身份（**换行，不截断**）。 */',
    s('name') + ' {',
    '  display: block;',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 700;',
    '  overflow-wrap: anywhere;',
    '}',
    s('note') + ' {',
    '  display: block;',
    '  font-style: normal;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1.45;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 锁定原因：写在名称格那一位（语义档的字走 `danger`，不借强调色）。 */',
    s('why') + ' {',
    '  display: block;',
    '  font-style: normal;',
    '  color: ' + skinVar('danger') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1.45;',
    '  overflow-wrap: anywhere;',
    '}',
    s('meta') + ' {',
    '  margin-left: auto;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '  font-variant-numeric: tabular-nums;',
    '  text-align: right;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 位置读数：每一行都写第几位（**永不截断**；拿起态走强调档）。 */',
    s('pos') + ' {',
    '  flex: none;',
    '  padding: 2px 8px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('surface-2') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 拿起的那一行：自己站起来（往上挪 2px ＋ 强调描边 ＋ 左侧 2px 主色侧标 ＋ 次要面底）。',
    '   行内主字仍是墨色；侧标 2px 是「整行选中」那一档的法条口径。 */',
    s('row') + '.is-up {',
    '  background: ' + skinVar('surface-2') + ';',
    '  border-color: ' + skinVar('accent') + ';',
    '  box-shadow: inset 2px 0 0 ' + skinVar('accent') + ';',
    '  transform: translateY(-2px);',
    '}',
    s('row') + '.is-up > ' + sc('handle') + '[aria-pressed="true"] {',
    '  background: ' + skinVar('accent-soft') + ';',
    '  border-color: ' + skinVar('accent') + ';',
    '  color: ' + skinVar('accent-text') + ';',
    '  cursor: grabbing;',
    '}',
    s('row') + '.is-up > ' + sc('pos') + ' {',
    '  background: ' + skinVar('accent-soft') + ';',
    '  border-color: ' + skinVar('accent') + ';',
    '  color: ' + skinVar('accent-text') + ';',
    '}',
    '/* 原位空槽：虚线框（形）＋ 写出哪一步空着（字）＋ 强调软底与强调字（色）。 */',
    s('slot') + ' {',
    '  display: flex;',
    '  align-items: center;',
    '  min-height: ' + String(DRAG_SORT_TOUCH_PX) + 'px;',
    '  padding: 0 10px;',
    '  border: 1.5px dashed ' + skinVar('accent') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('accent-soft') + ';',
    '  color: ' + skinVar('accent-text') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '  line-height: 1.5;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 落点粗线：3px 实线通栏（形）＋ 右端胶囊写出放第几位（字）。 */',
    s('drop') + ' {',
    '  display: flex;',
    '  align-items: center;',
    '  min-height: 36px;',
    '  padding: 2px 0;',
    '}',
    s('drop') + ' > i {',
    '  flex: 1 1 auto;',
    '  height: 3px;',
    '  min-width: 0;',
    '  border-radius: ' + skinVar('radius-pill') + ';',
    '  background: ' + skinVar('accent') + ';',
    '}',
    s('drop') + ' > b {',
    '  flex: none;',
    '  display: inline-flex;',
    '  align-items: center;',
    '  margin-left: 8px;',
    '  padding: 2px 10px;',
    '  border: 1px solid ' + skinVar('accent') + ';',
    '  border-radius: ' + skinVar('radius-pill') + ';',
    '  background: ' + skinVar('accent-soft') + ';',
    '  color: ' + skinVar('accent-text') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 700;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 状态句：现在是 plain 还是 lifted 的真读数（`role="status"`，换态时屏读器会念）。 */',
    s('status') + ' {',
    '  display: block;',
    '  margin: 0;',
    '  padding: 0 2px;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 取消键：拿起态才露出来（看得见、点得到；没拿起时 `hidden` 移出可点范围）。 */',
    s('cancel') + ' {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  justify-self: start;',
    '  min-height: ' + String(DRAG_SORT_TOUCH_PX) + 'px;',
    '  padding: 0 16px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-pill') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 600;',
    '  cursor: pointer;',
    '  transition: transform 80ms ease;',
    '}',
    s('cancel') + '[hidden] { display: none; }',
    s('cancel') + ':active { transform: scale(.98); }',
    '/* 锁定那一行：把手点不动，而且**说得清为什么**（原因在名称格那一位）。 */',
    s('row') + '.is-locked > ' + sc('handle') + ':disabled {',
    '  cursor: not-allowed;',
    '  background: none;',
    '  color: ' + skinVar('ink-3') + ';',
    '}',
    '/* 无障碍地板：真实键盘用户的焦点必须看得见（焦点是**增强**，不是通路——每一行都点得到）。 */',
    s('handle') + ':focus-visible, ' + s('cancel') + ':focus-visible {',
    '  outline: 2px solid ' + skinVar('accent') + ';',
    '  outline-offset: 2px;',
    '}',
    '/* 悬停只是增强（而且只在真有指针的设备上），点得到不靠它。 */',
    hover + ' {',
    '  ' + s('handle') + ':hover { border-color: ' + skinVar('accent') + '; }',
    '  ' + s('cancel') + ':hover { border-color: ' + skinVar('accent') + '; }',
    '}',
    '/* 减动效：拿起那一档的位移直接关掉（没有东西卡在半路——状态不靠 transitionend）。 */',
    '@media (prefers-reduced-motion: reduce) {',
    '  ' + s('row') + '.is-up { transform: none; }',
    '  ' + s('handle') + ', ' + s('cancel') + ' { transition: none; }',
    '}',
    '/* 窄档（**本件自己** < ' + String(DRAG_SORT_NARROW_PX) + 'px）：右端读数折到下一行，序号与名称不动。 */',
    '@container ' + DRAG_SORT_CONTAINER + ' (max-width: ' + String(DRAG_SORT_NARROW_PX) + 'px) {',
    '  ' + s('meta') + ' {',
    '    flex: 1 1 100%;',
    '    margin-left: 62px;',
    '    text-align: left;',
    '  }',
    '  ' + s('hint') + ' { margin-left: 0; flex: 1 1 100%; }',
    '}',
  ].join(LF);
}
