/** skill-bill · 词条表（英文列：与 `zh.ts` 同 key，缺英文先留空串并在票面记英文待译——首批 28 条与第二批 49 条（`write/receiptPaper.ts`）均即配齐英文）。
 *
 *  key 集合的权威是 `zh.ts`；拼错 key 编译期红（`SkillBillMessageId` 从 zh 派生，见 `index.ts`）。
 */
export const en = {
  /* ── 记分期场景（write/scene-installment.ts）── */
  'installment.family': 'Special income and expense',
  'installment.total.label': 'Total amount',
  'installment.total.hint': 'Total price, e.g. 1200',
  'installment.total.why': 'Missing: installments cannot be split without a total amount',
  'installment.periods.label': 'Number of installments',
  'installment.periods.hint': 'How many installments, e.g. 12',
  'installment.periods.why': 'Missing: the number of installments is up to you, no default is assumed',
  'installment.first-date.label': 'First due date',
  'installment.first-date.hint': 'Date of the first installment, e.g. 2026-10-01',
  'installment.first-date.why': 'Missing: per-installment dates cannot be computed without a first due date',
  'installment.section1': 'See what this entry is missing',
  'installment.chips.tail-diff': 'Rounding difference goes to the last installment',
  'installment.chips.total-check': 'Installments add up to the total price',
  'installment.section2': 'Installment parameters are for verification only',
  'installment.description': 'Parameters are read-only; tell me again with new values to change them.',
  'installment.section3': 'Installment preview',
  'installment.no-shares-chip': 'The split is computed once all three are given',
  'installment.fold-title': 'What is still missing, and the line to repeat once complete',
  'installment.prompt-label': 'Record each installment as stated; tap to copy',
  'installment.prompt-label-blocked': 'Once complete, repeat this line to the assistant',
  'installment.receipt.state': 'Saved to your ledger',
  'installment.receipt.next': 'This entry has been recorded; see the button below to undo.',
  'installment.receipt.rows-label': 'Entries recorded this time',
  'installment.receipt.rows-detail': 'Counted from actual ledger changes',
  'installment.receipt.periods-label': 'Installment parameters',
  'installment.receipt.feedback-detail': 'Each installment falls on the same day each month, or the last day of shorter months. To change the count, use the edit-entry command.',
  'installment.receipt.no-shares-chip': 'Installment parameters missing, not split; this entry is still recorded',
  'installment.receipt.caption': 'Saved fields and values',
  /* ── receipt paper (write/receiptPaper.ts) ── */
  'receipt-paper.expense.title': 'Expense',
  'receipt-paper.expense.eyebrow': 'Expense',
  'receipt-paper.income.title': 'Income',
  'receipt-paper.income.eyebrow': 'Income',
  'receipt-paper.photo.title': 'Bill',
  'receipt-paper.photo.eyebrow': 'Expense',
  'receipt-paper.batch.eyebrow': 'Expense',
  'receipt-paper.batch.plain-title': 'This batch is recorded',
  'receipt-paper.refund.title': 'Refund',
  'receipt-paper.refund.eyebrow': 'Refund',
  'receipt-paper.reimburse.title': 'Reimbursement',
  'receipt-paper.reimburse.eyebrow': 'Expense',
  'receipt-paper.reimburse-done.title': 'Reimbursed',
  'receipt-paper.reimburse-done.eyebrow': 'Income',
  'receipt-paper.lend.title': 'Lent out',
  'receipt-paper.lend.eyebrow': 'Expense',
  'receipt-paper.borrow.title': 'Borrowed',
  'receipt-paper.borrow.eyebrow': 'Income',
  'receipt-paper.collect.title': 'Collected',
  'receipt-paper.collect.eyebrow': 'Income',
  'receipt-paper.repay.title': 'Repaid',
  'receipt-paper.repay.eyebrow': 'Expense',
  'receipt-paper.installment.title': 'Installment',
  'receipt-paper.installment.eyebrow': 'Expense',
  'receipt-paper.plain.eyebrow': 'Expense',
  'receipt-paper.plain.plain-title': 'This entry is recorded',
  'receipt-paper.extra.tag': 'Tag',
  'receipt-paper.lend.tag-value': '#lent-out #unpaid',
  'receipt-paper.borrow.tag-value': '#borrowed #unpaid',
  'receipt-paper.ledger-fields': 'category, amount, time, account, ledger',
  'receipt-paper.note.common': 'Changed {count} entries: {fields} and more are saved',
  'receipt-paper.note.tagged': 'Changed {count} entries: {fields} and tags are saved',
  'receipt-paper.note.photo': 'Changed {count} entries: external recognition applies to the three key fields, saved',
  'receipt-paper.note.batch': 'Changed {count} entries: only one of them is recorded on this screen',
  'receipt-paper.title.done': 'Recorded: {word} {amount}',
  'receipt-paper.title.done-no-amount': 'Recorded: {word}',
  'receipt-paper.check.with-id': 'No. {id} / exceptions: none',
  'receipt-paper.check.without-id': 'No number yet / exceptions: none',
  'receipt-paper.copy.detail-with-fields': 'Changed {count} entries, saved {fields}',
  'receipt-paper.copy.detail-no-fields': 'Changed {count} entries, nothing was changed',
  'receipt-paper.sheet-note': 'Saved, nothing more to do.',
  'receipt-paper.unit': 'yuan',
  'receipt-paper.stamp': 'Valid',
  'receipt-paper.section.where': 'Where it went',
  'receipt-paper.section.check': 'Verify',
  'receipt-paper.cut-line': 'cut here',
  'receipt-paper.foot': '{brand} receipt',
  'receipt-paper.doc-title': '{word} receipt',
  'receipt-paper.missing': 'missing',
};
