/** skill-bill · 词条表（英文列：与 `zh.ts` 同 key，缺英文先留空串并在票面记英文待译——首批 28 条与第二批 49 条（`write/receiptPaper.ts`）均即配齐英文）。
 *
 *  key 集合的权威是 `zh.ts`；拼错 key 编译期红（`SkillBillMessageId` 从 zh 派生，见 `index.ts`）。
 */
/* 第三批 42 条（#1206 首切 7 件；commands 两条例句 en 与 zh 同值——示例含可运行的中文样例数据，译了就跑不通，票面记）。 */
export const en = {
  /* ── 记分期场景（write/scene-installment.ts）── */
  'installment.family': 'Special income and expense',
  'installment.total.label': 'Total amount',
  'installment.total.hint': 'Total price, e.g. 1200',
  'installment.total.why': 'Missing: installments cannot be split without a total amount',
  'installment.periods.label': 'Number of installments',
  'installment.periods.hint': 'How many installments, e.g. 12',
  'installment.periods.why': 'Missing: the number of installments is up to you, no default is assumed',
  'installment.first-date.label': 'First due date',
  'installment.first-date.hint': 'Date of the first installment, e.g. 2026-10-01',
  'installment.first-date.why': 'Missing: per-installment dates cannot be computed without a first due date',
  'installment.section1': 'See what this entry is missing',
  'installment.chips.tail-diff': 'Rounding difference goes to the last installment',
  'installment.chips.total-check': 'Installments add up to the total price',
  'installment.section2': 'Installment parameters are for verification only',
  'installment.description': 'Parameters are read-only; tell me again with new values to change them.',
  'installment.section3': 'Installment preview',
  'installment.no-shares-chip': 'The split is computed once all three are given',
  'installment.fold-title': 'What is still missing, and the line to repeat once complete',
  'installment.prompt-label': 'Record each installment as stated; tap to copy',
  'installment.prompt-label-blocked': 'Once complete, repeat this line to the assistant',
  'installment.receipt.state': 'Saved to your ledger',
  'installment.receipt.next': 'This entry has been recorded; see the button below to undo.',
  'installment.receipt.rows-label': 'Entries recorded this time',
  'installment.receipt.rows-detail': 'Counted from actual ledger changes',
  'installment.receipt.periods-label': 'Installment parameters',
  'installment.receipt.feedback-detail': 'Each installment falls on the same day each month, or the last day of shorter months. To change the count, use the edit-entry command.',
  'installment.receipt.no-shares-chip': 'Installment parameters missing, not split; this entry is still recorded',
  'installment.receipt.caption': 'Saved fields and values',
  /* ── receipt paper (write/receiptPaper.ts) ── */
  'receipt-paper.expense.title': 'Expense',
  'receipt-paper.expense.eyebrow': 'Expense',
  'receipt-paper.income.title': 'Income',
  'receipt-paper.income.eyebrow': 'Income',
  'receipt-paper.photo.title': 'Bill',
  'receipt-paper.photo.eyebrow': 'Expense',
  'receipt-paper.batch.eyebrow': 'Expense',
  'receipt-paper.batch.plain-title': 'This batch is recorded',
  'receipt-paper.refund.title': 'Refund',
  'receipt-paper.refund.eyebrow': 'Refund',
  'receipt-paper.reimburse.title': 'Reimbursement',
  'receipt-paper.reimburse.eyebrow': 'Expense',
  'receipt-paper.reimburse-done.title': 'Reimbursed',
  'receipt-paper.reimburse-done.eyebrow': 'Income',
  'receipt-paper.lend.title': 'Lent out',
  'receipt-paper.lend.eyebrow': 'Expense',
  'receipt-paper.borrow.title': 'Borrowed',
  'receipt-paper.borrow.eyebrow': 'Income',
  'receipt-paper.collect.title': 'Collected',
  'receipt-paper.collect.eyebrow': 'Income',
  'receipt-paper.repay.title': 'Repaid',
  'receipt-paper.repay.eyebrow': 'Expense',
  'receipt-paper.installment.title': 'Installment',
  'receipt-paper.installment.eyebrow': 'Expense',
  'receipt-paper.plain.eyebrow': 'Expense',
  'receipt-paper.plain.plain-title': 'This entry is recorded',
  'receipt-paper.extra.tag': 'Tag',
  'receipt-paper.lend.tag-value': '#lent-out #unpaid',
  'receipt-paper.borrow.tag-value': '#borrowed #unpaid',
  'receipt-paper.ledger-fields': 'category, amount, time, account, ledger',
  'receipt-paper.note.common': 'Changed {count} entries: {fields} and more are saved',
  'receipt-paper.note.tagged': 'Changed {count} entries: {fields} and tags are saved',
  'receipt-paper.note.photo': 'Changed {count} entries: external recognition applies to the three key fields, saved',
  'receipt-paper.note.batch': 'Changed {count} entries: only one of them is recorded on this screen',
  'receipt-paper.title.done': 'Recorded: {word} {amount}',
  'receipt-paper.title.done-no-amount': 'Recorded: {word}',
  'receipt-paper.check.with-id': 'No. {id} / exceptions: none',
  'receipt-paper.check.without-id': 'No number yet / exceptions: none',
  'receipt-paper.copy.detail-with-fields': 'Changed {count} entries, saved {fields}',
  'receipt-paper.copy.detail-no-fields': 'Changed {count} entries, nothing was changed',
  'receipt-paper.sheet-note': 'Saved, nothing more to do.',
  'receipt-paper.unit': 'yuan',
  'receipt-paper.stamp': 'Valid',
  'receipt-paper.section.where': 'Where it went',
  'receipt-paper.section.check': 'Verify',
  'receipt-paper.cut-line': 'cut here',
  'receipt-paper.foot': '{brand} receipt',
  'receipt-paper.doc-title': '{word} receipt',
  'receipt-paper.missing': 'missing',
  /* ── collection scene (write/scene-collect.ts): user data (category/tags) stays source-language, display templates take {tag} params ── */
  'scene-collect.source.label': 'Source record number',
  'scene-collect.source.why': 'Missing: collection must name which entry to clear {tag}, never default to the latest one',
  'scene-collect.candidates.why-same': 'Still carries {tag}, amount matches the collection',
  'scene-collect.candidates.why-different': 'Still carries {tag}, amount does not match the collection',
  'scene-collect.chips.positive': 'Collections are positive',
  'scene-collect.chips.category': 'Category {crumb}',
  'scene-collect.chips.swap': 'Original entry: {tagUnpaid} becomes {tagPaid}',
  'scene-collect.chips.amount-steady': 'Amount unchanged',
  'scene-collect.cards.amount.label': 'Collection amount',
  'scene-collect.cards.amount.detail': 'Record as positive income, under "{crumb}"',
  'scene-collect.cards.source.label': 'Original lent entry',
  'scene-collect.cards.source.unknown': 'Unidentified',
  'scene-collect.cards.source.no-id': 'No entry identified yet, pick one from the candidates',
  'scene-collect.cards.source.missing': '#{source} lent record not found in recent entries',
  'scene-collect.cards.source.with-row': '#{source} {category} {time}',
  'scene-collect.cards.diff.label': 'Uncollected balance',
  'scene-collect.cards.diff.pending': 'Pending',
  'scene-collect.cards.diff.pending-detail': 'The balance shows once the lent entry is identified',
  'scene-collect.cards.diff.full': 'Fully collected, nothing left',
  'scene-collect.cards.diff.partial': 'Collection differs from lent amount, the tail is recorded, no blocking',
  'scene-collect.note.msg': 'Clear by tag, never guess by amount',
  'scene-collect.note.detail': 'Candidates list only entries carrying {tagLend} and {tagUnpaid}; if none, ask back directly.',
  'scene-collect.flow.first.title': 'Lent entry',
  'scene-collect.flow.first.note': 'Candidates list only entries carrying {tagLend} and {tagUnpaid}.',
  'scene-collect.flow.first.state.known': 'Identified #{id}',
  'scene-collect.flow.first.pick.hint': 'Want the lent entry not yet returned; never auto-pick when unidentified.',
  'scene-collect.flow.second.title': 'Collection step',
  'scene-collect.flow.second.note': 'Write the collection as positive. Category is fixed to "{crumb}".',
  'scene-collect.flow.second.field.category': 'Category',
  'scene-collect.flow.second.field.category-hint': 'Fixed to {crumb}',
  'scene-collect.flow.third.title': 'Result',
  'scene-collect.flow.third.note.pending': 'Once identified: change its {tagUnpaid} to {tagPaid}, amount unchanged. Add {tagCollect} to this entry.',
  'scene-collect.flow.third.note.done': 'Original entry #{id}: change {tagUnpaid} to {tagPaid}, amount unchanged. Add {tagCollect} to this entry.',
  'scene-collect.prompt.head': 'Record this collection as stated, and move the tags on the original entry.',
  'scene-collect.prompt.body': '\nLoad the Cookie Accounting skill and record a collection.\nWake word: {wakeWord}\nLent entry: {source}\nCollection amount: {amount} (positive income)\nCategory: {category}\nAccount: {account}\nLedger: {ledger}\nTwo things to do:\n1. Record one income under "{category}" with note "{tagCollect} original entry #{sourceId}"\n2. On original entry #{sourceId}, change {tagUnpaid} to {tagPaid}, amount unchanged',
  'scene-collect.prompt.source.missing': '<source record number>',
  'scene-collect.prompt.source.no-row': '#{id} not found in recent entries',
  'scene-collect.prompt.source.with-row': '#{id} {category} {amount} {time}',
  'scene-collect.prompt.account-missing': '<which card>',
  'scene-collect.prompt.ledger-missing': '<ledger>',
  'scene-collect.prompt.label': 'Write both entries as stated, tap to copy',
  'scene-collect.receipt.rows-count': '{count} entries',
  'scene-collect.receipt.pair.label': 'Paired tags',
  'scene-collect.receipt.pair.detail': 'Only tags change on the original entry, amount unchanged',
  'scene-collect.receipt-note.msg.without-source': 'Tag this entry {tagCollect}, no original entry was given',
  'scene-collect.receipt-note.msg.with-source': 'Tag this entry {tagCollect}, change original entry #{source} to {tagPaid}',
  'scene-collect.receipt-note.detail': 'Debt queries count {tagUnpaid}; one fewer after saving. See the button below to undo.',
  /* ── #1206 首切 7 件 ── */
  'source-note.receipt': 'Accounting ledger (write)',
  'source-note.collect': 'Accounting ledger (read-only)',
  'command.record-add.title': 'Record an entry',
  'command.record-add.example': "bill-cmd-read bill.record.add --params '{\"category\":\"餐饮\",\"amount\":-12.5,\"time\":\"2026-09-14 12:00:00\",\"account\":\"支付宝\",\"ledger\":\"生活\"}'",
  'command.record-update.title': 'Edit an entry',
  'command.record-update.example': "bill-cmd-read bill.record.update --params '{\"note\":\"改过\"}'",
  'receipt-parts.status.label': 'Status',
  'receipt-parts.status.unchanged': 'No changes',
  'receipt-parts.status.changed': 'Changed',
  'receipt-parts.status.unchanged-detail': 'Same as before',
  'receipt-parts.reconcile.title': 'Reconciliation',
  'receipt-parts.reconcile.field': 'Field',
  'receipt-parts.reconcile.value': 'Value',
  'receipt-parts.reconcile.record-id': 'Record ID',
  'receipt-parts.reconcile.record-id-missing': 'Not yet',
  'receipt-parts.reconcile.action-at': 'Recorded at',
  'slots.add.category.hint': 'Pick the most specific level, e.g. "lunch"',
  'slots.add.amount.hint': 'Negative for expenses, positive for income, e.g. -12.5',
  'slots.add.time.hint': 'Defaults to today 12:00:00 when empty',
  'slots.add.account.hint': 'Defaults to the default account when empty',
  'slots.add.ledger.hint': 'Defaults to the default ledger when empty',
  'slots.add.currency.hint': 'Defaults to the default currency when empty',
  'slots.add.note.hint': 'Free text; write the item name here, #tags allowed',
  'slots.update.id.hint': 'Number of the entry to edit (also required for undo/restore)',
  'slots.update.op.hint': 'Edits fields when empty. Write undo to undo, restore to restore',
  'slots.update.category.hint': 'Leave empty to keep unchanged',
  'slots.update.amount.hint': 'Leave empty to keep unchanged',
  'slots.update.time.hint': 'Leave empty to keep unchanged',
  'slots.update.account.hint': 'Leave empty to keep unchanged',
  'slots.update.ledger.hint': 'Leave empty to keep unchanged',
  'slots.update.currency.hint': 'Leave empty to keep unchanged',
  'slots.update.note.hint': 'Leave empty to keep unchanged',
  'batch.family': 'Batch and correction',
  'batch.section1': 'See what is missing first',
  'batch.caliber': 'Only one entry is recorded per batch.',
  'batch.fold-note': 'Once complete, repeat the command above to the assistant.',
  'batch.section2': 'Verify this screen',
  'batch.total-label': 'Screen total',
  'batch.prompt-title': 'This is what to send the assistant once complete',
  'batch.section3': 'Ask the assistant to record once complete',
  'batch.receipt-caliber': 'Only one entry per batch; the receipt number is it.',
  'batch.receipt-caption': 'Written this time',
};
