/** skill-bill · 词条表（**基准语言 zh**：key 集合的权威，回退链第二站）。
 *
 *  归属：本包自己的命名空间（ADR-0004 §3「词条随包存放，命名空间＝包名」）。
 *  key 形态（第一轮＝**派生命名**，见地图 #1197 决定记录）：<件名>.<位置>.<键>——
 *  件名取场景件名，位置取该词在 InstallmentSpec 里那一格。
 *
 *  不变量：本表的中文值**逐字等于改造前写死在场景件里的字面量**——所以不启用多语言时产物逐字节不变。
 *  首批 28 条（#1204 首迁件 `write/scene-installment.ts` 的全部用户可见文案；参数名
 *  `total`／`periods`／`start_date` 是槽位标识、命令键冻结，二者都不进本表）。
 *  第二批 49 条（#1204 第二件 `write/receiptPaper.ts`：13 页回执纸共用装配的用户可见文案；
 *  行标签三格复用 `fieldLabelOf`（与摘要行同一口径），不在本表另立 key）。
  *  第三批 42 条（#1206 首切 7 件：blockedFold 复用 `installment.fold-title`、errorReceipt 复用
  *  `installment.prompt-label-blocked`、scene-batch 复用 `installment.receipt.state` 与
  *  `installment.receipt.rows-label`，同句只一处定义；commands 两条例句 en 与 zh 同值——示例含可运行的中文
  *  样例数据，译了就跑不通，en 同值并在票面记）。
  */
export const zh = {
  /* ── 记分期场景（write/scene-installment.ts）── */
  'installment.family': '特殊收支族',
  'installment.total.label': '总额',
  'installment.total.hint': '总价，如 1200',
  'installment.total.why': '没给：不分总额就摊不了期',
  'installment.periods.label': '期数',
  'installment.periods.hint': '分几期，如 12',
  'installment.periods.why': '没给：分几期由用户定，不许默认',
  'installment.first-date.label': '首期日',
  'installment.first-date.hint': '第 1 期哪一天，如 2026-10-01',
  'installment.first-date.why': '没给：首期日不定就算不出每期日期',
  'installment.section1': '先看这一笔缺什么',
  'installment.chips.tail-diff': '尾差归最后一期',
  'installment.chips.total-check': '合计等于总价',
  'installment.section2': '分期参数只供核对',
  'installment.description': '参数只供核对，改值重说。',
  'installment.section3': '分摊预览',
  'installment.no-shares-chip': '三样齐了才算得出分摊',
  'installment.fold-title': '还缺什么，以及补齐后照抄的那条',
  'installment.prompt-label': '照这个口径逐期记，点这颗复制',
  'installment.prompt-label-blocked': '补齐后照这句跟助手说一遍',
  'installment.receipt.state': '写库成功',
  'installment.receipt.next': '这一笔已记下，撤销见下方按钮。',
  'installment.receipt.rows-label': '这次记了几笔',
  'installment.receipt.rows-detail': '按库里的改动算',
  'installment.receipt.periods-label': '分期参数',
  'installment.receipt.feedback-detail': '每期日期＝每月同日，该月没有那一天就回退月末。改期数走「改记录」。',
  'installment.receipt.no-shares-chip': '缺分期参数，未分摊，这一笔仍已记下',
  'installment.receipt.caption': '写进去的项与值',
  /* ── 回执纸（write/receiptPaper.ts，#1204 第二件）：13 页共用装配 ── */
  'receipt-paper.expense.title': '支出',
  'receipt-paper.expense.eyebrow': '支出',
  'receipt-paper.income.title': '收入',
  'receipt-paper.income.eyebrow': '收入',
  'receipt-paper.photo.title': '账单',
  'receipt-paper.photo.eyebrow': '支出',
  'receipt-paper.batch.eyebrow': '支出',
  'receipt-paper.batch.plain-title': '这一批记好了',
  'receipt-paper.refund.title': '退款',
  'receipt-paper.refund.eyebrow': '退款',
  'receipt-paper.reimburse.title': '报销',
  'receipt-paper.reimburse.eyebrow': '支出',
  'receipt-paper.reimburse-done.title': '到账',
  'receipt-paper.reimburse-done.eyebrow': '收入',
  'receipt-paper.lend.title': '借出',
  'receipt-paper.lend.eyebrow': '支出',
  'receipt-paper.borrow.title': '借入',
  'receipt-paper.borrow.eyebrow': '收入',
  'receipt-paper.collect.title': '收回',
  'receipt-paper.collect.eyebrow': '收入',
  'receipt-paper.repay.title': '偿还',
  'receipt-paper.repay.eyebrow': '支出',
  'receipt-paper.installment.title': '分期',
  'receipt-paper.installment.eyebrow': '支出',
  'receipt-paper.plain.eyebrow': '支出',
  'receipt-paper.plain.plain-title': '这一笔记好了',
  'receipt-paper.extra.tag': '标签',
  'receipt-paper.lend.tag-value': '#借出 #未还',
  'receipt-paper.borrow.tag-value': '#借入 #未还',
  'receipt-paper.ledger-fields': '分类、金额、时间、账户、账本',
  'receipt-paper.note.common': '改了 {count} 笔：{fields}等项已写进账本',
  'receipt-paper.note.tagged': '改了 {count} 笔：{fields}、标签已写进账本',
  'receipt-paper.note.photo': '改了 {count} 笔：三要素以外部识别为准，已落账',
  'receipt-paper.note.batch': '改了 {count} 笔：这次只落了其中一笔',
  'receipt-paper.title.done': '记好了：{word} {amount}',
  'receipt-paper.title.done-no-amount': '记好了：{word}',
  'receipt-paper.check.with-id': '编号 {id} ／ 异常：无',
  'receipt-paper.check.without-id': '编号 还没有 ／ 异常：无',
  'receipt-paper.copy.detail-with-fields': '改了 {count} 笔，写进去 {fields}',
  'receipt-paper.copy.detail-no-fields': '改了 {count} 笔，写进去 没改到任何一项',
  'receipt-paper.sheet-note': '已经记好，不用再操作。',
  'receipt-paper.unit': '元',
  'receipt-paper.stamp': '有效',
  'receipt-paper.section.where': '记到哪里',
  'receipt-paper.section.check': '核对',
  'receipt-paper.cut-line': '✂ 裁切线',
  'receipt-paper.foot': '{brand}回执',
  'receipt-paper.doc-title': '{word} 回执',
  'receipt-paper.missing': '未给',
  /* ── 记收回场景（write/scene-collect.ts，#1204 第三件）：用户数据（分类／标签）不进表，展示模板取 {tag} 参数 ── */
  'scene-collect.source.label': '借出记录编号',
  'scene-collect.source.why': '没给：收回要指名销哪一笔的 {tag}，不拿最近一笔顶替',
  'scene-collect.candidates.why-same': '还带 {tag}，金额与收回额一致',
  'scene-collect.candidates.why-different': '还带 {tag}，金额与收回额不符',
  'scene-collect.chips.positive': '收回记正数',
  'scene-collect.chips.category': '分类 {crumb}',
  'scene-collect.chips.swap': '原记录 {tagUnpaid} 换 {tagPaid}',
  'scene-collect.chips.amount-steady': '金额不动',
  'scene-collect.cards.amount.label': '收回金额',
  'scene-collect.cards.amount.detail': '收入记正数，归在「{crumb}」下面',
  'scene-collect.cards.source.label': '借出原记录',
  'scene-collect.cards.source.unknown': '未认准',
  'scene-collect.cards.source.no-id': '还没认准是哪一笔，候选里点一行',
  'scene-collect.cards.source.missing': '#{source}近期记录里没读到借出记录',
  'scene-collect.cards.source.with-row': '#{source}　{category}　{time}',
  'scene-collect.cards.diff.label': '未收净差',
  'scene-collect.cards.diff.pending': '未算',
  'scene-collect.cards.diff.pending-detail': '认准借出记录后这里出净差',
  'scene-collect.cards.diff.full': '全额收回，未留尾',
  'scene-collect.cards.diff.partial': '收回额与借出额不等，尾差照记、不阻断',
  'scene-collect.note.msg': '按标签销账，不按金额猜',
  'scene-collect.note.detail': '候选只列带 {tagLend} 且还带 {tagUnpaid} 的记录，一条都没有就直接反问。',
  'scene-collect.flow.first.title': '借出记录',
  'scene-collect.flow.first.note': '候选只列带 {tagLend} 且还带 {tagUnpaid} 的记录。',
  'scene-collect.flow.first.state.known': '已认准 #{id}',
  'scene-collect.flow.first.pick.hint': '要的是还没还回来的那笔借出，未认准不代选。',
  'scene-collect.flow.second.title': '收回这一步',
  'scene-collect.flow.second.note': '收回额写正数。分类固定为「{crumb}」。',
  'scene-collect.flow.second.field.category': '分类',
  'scene-collect.flow.second.field.category-hint': '固定为 {crumb}',
  'scene-collect.flow.third.title': '结果',
  'scene-collect.flow.third.note.pending': '认准原记录后：把它的 {tagUnpaid} 换成 {tagPaid}，金额不动。这一笔补 {tagCollect}。',
  'scene-collect.flow.third.note.done': '原记录 #{id} 的 {tagUnpaid} 换成 {tagPaid}，金额不动。这一笔补 {tagCollect}。',
  'scene-collect.prompt.head': '照下面这个口径记这一笔收回，并把原记录的标签换过来。',
  'scene-collect.prompt.body': '\n请加载「饼干记账」技能，帮我记一笔收回。\n唤醒词：{wakeWord}\n借出记录：{source}\n收回金额：{amount}　收入记正数\n分类：{category}\n账户：{account}\n账本：{ledger}\n请办两件：\n① 记一笔收入，分类「{category}」，备注写「{tagCollect} 原记录 #{sourceId}」\n② 原记录 #{sourceId} 的备注把 {tagUnpaid} 换成 {tagPaid}，金额不动',
  'scene-collect.prompt.source.missing': '<借出记录编号>',
  'scene-collect.prompt.source.no-row': '#{id}　近期记录里没读到',
  'scene-collect.prompt.source.with-row': '#{id}　{category}　{amount}　{time}',
  'scene-collect.prompt.account-missing': '<钱回到哪张卡>',
  'scene-collect.prompt.ledger-missing': '<账本>',
  'scene-collect.prompt.label': '照这个口径写两笔，点这颗复制',
  'scene-collect.receipt.rows-count': '{count} 笔',
  'scene-collect.receipt.pair.label': '配对标签',
  'scene-collect.receipt.pair.detail': '原记录只动标签，金额不动',
  'scene-collect.receipt-note.msg.without-source': '这一笔打 {tagCollect}，原记录这次没给到',
  'scene-collect.receipt-note.msg.with-source': '这一笔打 {tagCollect}，原记录 #{source} 换成 {tagPaid}',
  'scene-collect.receipt-note.detail': '「查欠款」按 {tagUnpaid} 数，写完少一笔。撤销见下方按钮。',
  /* ── #1206 首切 7 件（write 批次 4 前锋：纯 copy 件）── */
  'source-note.receipt': '记账库（写入）',
  'source-note.collect': '记账库（只读）',
  'command.record-add.title': '记一笔',
  'command.record-add.example': "bill-cmd-read bill.record.add --params '{\"category\":\"餐饮\",\"amount\":-12.5,\"time\":\"2026-09-14 12:00:00\",\"account\":\"支付宝\",\"ledger\":\"生活\"}'",
  'command.record-update.title': '改记录',
  'command.record-update.example': "bill-cmd-read bill.record.update --params '{\"note\":\"改过\"}'",
  'receipt-parts.status.label': '状态',
  'receipt-parts.status.unchanged': '无改动',
  'receipt-parts.status.changed': '已改动',
  'receipt-parts.status.unchanged-detail': '值与改前一致',
  'receipt-parts.reconcile.title': '对账信息',
  'receipt-parts.reconcile.field': '字段',
  'receipt-parts.reconcile.value': '值',
  'receipt-parts.reconcile.record-id': '记录编号',
  'receipt-parts.reconcile.record-id-missing': '还没有',
  'receipt-parts.reconcile.action-at': '写入时间',
  'slots.add.category.hint': '要选到最细那一级，如「午餐」',
  'slots.add.amount.hint': '支出记负数、收入记正数，如 -12.5',
  'slots.add.time.hint': '不填就记成今天 12:00:00',
  'slots.add.account.hint': '不填就记到默认账户',
  'slots.add.ledger.hint': '不填就记到默认账本',
  'slots.add.currency.hint': '不填就用默认币种',
  'slots.add.note.hint': '自由文本，名目写在这里，可带 #标签',
  'slots.update.id.hint': '要改的那条记录的编号（撤销／恢复同样要它）',
  'slots.update.op.hint': '不填就改字段。撤销写 undo，恢复写 restore',
  'slots.update.category.hint': '不改就别给',
  'slots.update.amount.hint': '不改就别给',
  'slots.update.time.hint': '不改就别给',
  'slots.update.account.hint': '不改就别给',
  'slots.update.ledger.hint': '不改就别给',
  'slots.update.currency.hint': '不改就别给',
  'slots.update.note.hint': '不改就别给',
  'batch.family': '批量与修正族',
  'batch.section1': '先看缺什么',
  'batch.caliber': '本批一次只落一笔。',
  'batch.fold-note': '补齐后照上面那条口令跟助手说一遍。',
  'batch.section2': '核对这一屏',
  'batch.total-label': '这一屏合计',
  'batch.prompt-title': '这一段就是补齐后要发给助手的话',
  'batch.section3': '补齐了再请助手记',
  'batch.receipt-caliber': '本批一次只落一笔，回执里的编号就是它。',
  'batch.receipt-caption': '本次写入',
};
