/** 采集页（SAY）逐词数据表——一份版式（./saySheet.ts）＋ 16 份数据（本件）。
 *
 * 数据全部从 16 件判地原型的可见文本反推；**唤醒词一个都不写在这里**——词面一律写占位符 {word}，
 * 渲染时由调用方把投影出来的唤醒词填进去（判据 t721：一条唤醒词只准住它所属那份域声明）。
 * 键是「哪条场景」的判别位：写入域＝kind（记一笔是 plain），改记录族＝update:none／update:undo／update:restore。
 *
 * 本件由 docs/skills/skill-bill/1079-say-数据生成器.mjs 从判地原型生成（幂等）：改原型后重跑它，别手改。
 */

import type { SayWordSpec } from './saySheet.js';

export const SAY_WORDS: Readonly<Record<string, SayWordSpec>> = {
  "expense": {
    titleWait: "{word}还差 2 项",
    titleReady: "{word}已填齐",
    subWait: "补齐下面几项，就能记好这一笔。",
    subReady: "下面几项都填好了，这一句就能复制走。",
    todoWait: "还缺什么",
    todoTagWait: "TODO",
    chips: [{ key: "cat", label: "分类", small: "待补" }, { key: "amt", label: "金额", small: "待补" }],
    fills: [{ label: "方向", value: "金额取负数" }, { label: "场景", value: "{word}" }],
    fields: [{ slot: "cat", label: "分类", kind: "select", req: true, options: [{ value: "", label: "请选择分类" }, { value: "餐饮", label: "餐饮" }, { value: "出行", label: "出行" }, { value: "购物", label: "购物" }, { value: "居住", label: "居住" }, { value: "医疗", label: "医疗" }, { value: "__other", label: "其他（手填）…" }] }, { slot: "amt", label: "金额", kind: "text", req: true, placeholder: "例：12.5" }],
    optFields: [{ slot: "opt_note", label: "备注(选填)", kind: "text", req: false, placeholder: "选填，如 加班餐" }, { slot: "opt_time", label: "时间(选填)", kind: "date", req: false }, { slot: "opt_acct", label: "账户(选填)", kind: "text", req: false, placeholder: "如 支付宝、微信" }, { slot: "opt_ledger", label: "账本(选填)", kind: "text", req: false, placeholder: "如 旅行、生活" }, { slot: "opt_cur", label: "币种(选填)", kind: "text", req: false, placeholder: "空＝人民币；外币如 USD" }],
    optSummary: "备注／时间／账户／账本／币种",
    optNote: "不填就留空：复制出的那句话里这几项会落 ___，助手照默认走（时间＝现在、币种＝人民币）。",
    hint: "还差 2 项：分类、金额。",
    cfg: [{"key":"cat","label":"分类","ftype":"cat","ph":"category"},{"key":"amt","label":"金额","ftype":"amount","ph":"amount"},{"key":"opt_note","label":"备注(选填)","ftype":"text","opt":true,"ph":"note"},{"key":"opt_time","label":"时间(选填)","ftype":"date","opt":true,"ph":"record_time"},{"key":"opt_acct","label":"账户(选填)","ftype":"text","opt":true,"ph":"account"},{"key":"opt_ledger","label":"账本(选填)","ftype":"text","opt":true,"ph":"ledger"},{"key":"opt_cur","label":"币种(选填)","ftype":"text","opt":true,"ph":"currency"}],
  },
  "income": {
    titleWait: "{word}还差 2 项",
    titleReady: "{word}已填齐",
    subWait: "补齐下面几项，就能记好这一笔。",
    subReady: "下面几项都填好了，这一句就能复制走。",
    todoWait: "还缺什么",
    todoTagWait: "TODO",
    chips: [{ key: "cat", label: "分类", small: "待补" }, { key: "amt", label: "金额", small: "待补" }],
    fills: [{ label: "方向", value: "金额取正数" }, { label: "场景", value: "{word}" }],
    fields: [{ slot: "cat", label: "分类", kind: "select", req: true, options: [{ value: "", label: "请选择分类" }, { value: "工资", label: "工资" }, { value: "奖金", label: "奖金" }, { value: "副业收入", label: "副业收入" }, { value: "其他收入", label: "其他收入" }, { value: "__other", label: "其他（手填）…" }] }, { slot: "amt", label: "金额", kind: "text", req: true, placeholder: "例：8000" }],
    optFields: [{ slot: "opt_note", label: "备注(选填)", kind: "text", req: false, placeholder: "选填" }, { slot: "opt_time", label: "时间(选填)", kind: "date", req: false }, { slot: "opt_acct", label: "账户(选填)", kind: "text", req: false, placeholder: "如 银行卡、微信" }, { slot: "opt_cur", label: "币种(选填)", kind: "text", req: false, placeholder: "空＝人民币；外币如 USD" }],
    optSummary: "备注／时间／账户／币种",
    optNote: "不填就留空：复制出的那句话里这几项会落 ___，助手照默认走（时间＝现在、币种＝人民币）。",
    hint: "还差 2 项：分类、金额。",
    cfg: [{"key":"cat","label":"分类","ftype":"cat","ph":"category"},{"key":"amt","label":"金额","ftype":"amount","ph":"amount"},{"key":"opt_note","label":"备注(选填)","ftype":"text","opt":true,"ph":"note"},{"key":"opt_time","label":"时间(选填)","ftype":"date","opt":true,"ph":"record_time"},{"key":"opt_acct","label":"账户(选填)","ftype":"text","opt":true,"ph":"account"},{"key":"opt_cur","label":"币种(选填)","ftype":"text","opt":true,"ph":"currency"}],
  },
  "photo": {
    titleWait: "账单要素还没齐",
    titleReady: "账单要素已齐",
    subWait: "补齐下面几项，就能记好这一笔。",
    subReady: "下面几项都填好了，这一句就能复制走。",
    todoWait: "还缺什么",
    todoTagWait: "TODO",
    chips: [{ key: "cat", label: "分类", small: "待补" }, { key: "amt", label: "金额", small: "待补" }],
    fills: [{ label: "图片", value: "以外置识别为准" }, { label: "场景", value: "{word}" }],
    fields: [{ slot: "cat", label: "分类", kind: "select", req: true, options: [{ value: "", label: "请选择分类" }, { value: "餐饮", label: "餐饮" }, { value: "购物", label: "购物" }, { value: "出行", label: "出行" }, { value: "__other", label: "其他（手填）…" }] }, { slot: "amt", label: "金额", kind: "text", req: true, placeholder: "例：30" }],
    hint: "还差 2 项：分类、金额。",
    cfg: [{"key":"cat","label":"分类","ftype":"cat","ph":"category"},{"key":"amt","label":"金额","ftype":"amount","ph":"amount"}],
  },
  "batch": {
    titleWait: "{word}还差 2 项",
    titleReady: "{word}已填齐",
    subWait: "补齐下面几项，就能记好这一笔。",
    subReady: "下面几项都填好了，这一句就能复制走。",
    todoWait: "还缺什么",
    todoTagWait: "TODO",
    chips: [{ key: "cat", label: "分类", small: "待补" }, { key: "amt", label: "金额", small: "待补" }],
    fills: [{ label: "形态", value: "逐笔在页上确认" }, { label: "场景", value: "{word}" }],
    fields: [{ slot: "cat", label: "分类", kind: "select", req: true, options: [{ value: "", label: "请选择分类" }, { value: "餐饮", label: "餐饮" }, { value: "出行", label: "出行" }, { value: "购物", label: "购物" }, { value: "__other", label: "其他（手填）…" }] }, { slot: "amt", label: "金额", kind: "text", req: true, placeholder: "例：10" }],
    optFields: [{ slot: "opt_ledger", label: "账本(选填)", kind: "text", req: false, placeholder: "如 旅行" }],
    optSummary: "账本",
    optNote: "不填就留空：复制出的那句话里这几项会落 ___，助手照默认走（时间＝现在、币种＝人民币）。",
    hint: "还差 2 项：分类、金额。",
    cfg: [{"key":"cat","label":"分类","ftype":"cat"},{"key":"amt","label":"金额","ftype":"amount"},{"key":"opt_ledger","label":"账本(选填)","ftype":"text","opt":true,"ph":"ledger"}],
  },
  "refund": {
    titleWait: "{word}还差 3 项",
    titleReady: "{word}已填齐",
    subWait: "补齐下面几项，就能记好这一笔。",
    subReady: "下面几项都填好了，这一句就能复制走。",
    todoWait: "还缺什么",
    todoTagWait: "TODO",
    chips: [{ key: "cat", label: "分类", small: "待补" }, { key: "amt", label: "金额", small: "待补" }, { key: "orig", label: "原支出编号", small: "待补" }],
    fills: [{ label: "场景", value: "{word}" }],
    fields: [{ slot: "cat", label: "分类", kind: "select", req: true, options: [{ value: "", label: "请选择分类" }, { value: "退款/冲销", label: "退款/冲销" }, { value: "__other", label: "其他（手填）…" }] }, { slot: "amt", label: "金额", kind: "text", req: true, placeholder: "例：20" }, { slot: "orig", label: "原支出编号", kind: "text", req: true, placeholder: "例：11" }],
    optFields: [{ slot: "opt_reason", label: "退款原因(选填)", kind: "text", req: false, placeholder: "如 退货、取消订单、差价" }],
    optSummary: "退款原因",
    optNote: "不填就留空：复制出的那句话里这几项会落 ___，助手照默认走（时间＝现在、币种＝人民币）。",
    hint: "还差 3 项：分类、金额、原支出编号。",
    cfg: [{"key":"cat","label":"分类","ftype":"cat","ph":"category"},{"key":"amt","label":"金额","ftype":"amount","ph":"amount"},{"key":"orig","label":"原支出编号","ftype":"int","ph":"original"},{"key":"opt_reason","label":"退款原因(选填)","ftype":"text","opt":true,"ph":"reason"}],
  },
  "reimburse": {
    titleWait: "{word}还差 2 项",
    titleReady: "{word}已填齐",
    subWait: "补齐下面几项，就能记好这一笔。",
    subReady: "下面几项都填好了，这一句就能复制走。",
    todoWait: "还缺什么",
    todoTagWait: "TODO",
    chips: [{ key: "cat", label: "分类", small: "待补" }, { key: "amt", label: "金额", small: "待补" }],
    fills: [{ label: "场景", value: "{word}" }],
    fields: [{ slot: "cat", label: "分类", kind: "select", req: true, options: [{ value: "", label: "请选择分类" }, { value: "出行", label: "出行" }, { value: "餐饮", label: "餐饮" }, { value: "住宿", label: "住宿" }, { value: "办公", label: "办公" }, { value: "__other", label: "其他（手填）…" }] }, { slot: "amt", label: "金额", kind: "text", req: true, placeholder: "例：100" }],
    optFields: [{ slot: "opt_note", label: "备注(选填)", kind: "text", req: false, placeholder: "自动加 #待报销" }, { slot: "opt_time", label: "时间(选填)", kind: "date", req: false }],
    optSummary: "备注／时间",
    optNote: "不填就留空：复制出的那句话里这几项会落 ___，助手照默认走（时间＝现在、币种＝人民币）。",
    hint: "还差 2 项：分类、金额。",
    cfg: [{"key":"cat","label":"分类","ftype":"cat","ph":"category"},{"key":"amt","label":"金额","ftype":"amount","ph":"amount"},{"key":"opt_note","label":"备注(选填)","ftype":"text","opt":true,"ph":"note"},{"key":"opt_time","label":"时间(选填)","ftype":"date","opt":true,"ph":"record_time"}],
  },
  "reimburse-done": {
    titleWait: "{word}还差 3 项",
    titleReady: "{word}已填齐",
    subWait: "补齐下面几项，就能记好这一笔。",
    subReady: "下面几项都填好了，这一句就能复制走。",
    todoWait: "还缺什么",
    todoTagWait: "TODO",
    chips: [{ key: "cat", label: "分类", small: "待补" }, { key: "amt", label: "金额", small: "待补" }, { key: "rb", label: "待报销记录编号", small: "待补" }],
    fills: [{ label: "场景", value: "{word}" }],
    fields: [{ slot: "cat", label: "分类", kind: "select", req: true, options: [{ value: "", label: "请选择分类" }, { value: "其他收入/报销回款", label: "其他收入/报销回款" }, { value: "__other", label: "其他（手填）…" }] }, { slot: "amt", label: "金额", kind: "text", req: true, placeholder: "例：100" }, { slot: "rb", label: "待报销记录编号", kind: "text", req: true, placeholder: "例：16" }],
    hint: "还差 3 项：分类、金额、待报销记录编号。",
    cfg: [{"key":"cat","label":"分类","ftype":"cat","ph":"category"},{"key":"amt","label":"金额","ftype":"amount","ph":"amount"},{"key":"rb","label":"待报销记录编号","ftype":"int","ph":"related"}],
  },
  "lend": {
    titleWait: "{word}还差 3 项",
    titleReady: "{word}已填齐",
    subWait: "补齐下面几项，就能记好这一笔。",
    subReady: "下面几项都填好了，这一句就能复制走。",
    todoWait: "还缺什么",
    todoTagWait: "TODO",
    chips: [{ key: "cat", label: "分类", small: "待补" }, { key: "amt", label: "金额", small: "待补" }, { key: "who", label: "借给谁", small: "待补" }],
    fills: [{ label: "场景", value: "{word}" }],
    fields: [{ slot: "cat", label: "分类", kind: "select", req: true, options: [{ value: "", label: "请选择分类" }, { value: "借贷/借出", label: "借贷/借出" }, { value: "__other", label: "其他（手填）…" }] }, { slot: "amt", label: "金额", kind: "text", req: true, placeholder: "例：500" }, { slot: "who", label: "借给谁", kind: "text", req: true, placeholder: "例：小王" }],
    optFields: [{ slot: "opt_dl", label: "期限(选填)", kind: "text", req: false, placeholder: "如 月底还" }],
    optSummary: "期限",
    optNote: "不填就留空：复制出的那句话里这几项会落 ___，助手照默认走（时间＝现在、币种＝人民币）。",
    hint: "还差 3 项：分类、金额、借给谁。",
    cfg: [{"key":"cat","label":"分类","ftype":"cat","ph":"category"},{"key":"amt","label":"金额","ftype":"amount","ph":"amount"},{"key":"who","label":"借给谁","ftype":"person","ph":"person"},{"key":"opt_dl","label":"期限(选填)","ftype":"text","opt":true,"ph":"deadline"}],
  },
  "borrow": {
    titleWait: "{word}还差 3 项",
    titleReady: "{word}已填齐",
    subWait: "补齐下面几项，就能记好这一笔。",
    subReady: "下面几项都填好了，这一句就能复制走。",
    todoWait: "还缺什么",
    todoTagWait: "TODO",
    chips: [{ key: "cat", label: "分类", small: "待补" }, { key: "amt", label: "金额", small: "待补" }, { key: "who", label: "向谁借", small: "待补" }],
    fills: [{ label: "场景", value: "{word}" }],
    fields: [{ slot: "cat", label: "分类", kind: "select", req: true, options: [{ value: "", label: "请选择分类" }, { value: "借贷/借入", label: "借贷/借入" }, { value: "__other", label: "其他（手填）…" }] }, { slot: "amt", label: "金额", kind: "text", req: true, placeholder: "例：500" }, { slot: "who", label: "向谁借", kind: "text", req: true, placeholder: "例：李四" }],
    optFields: [{ slot: "opt_dl", label: "期限(选填)", kind: "text", req: false, placeholder: "选填" }],
    optSummary: "期限",
    optNote: "不填就留空：复制出的那句话里这几项会落 ___，助手照默认走（时间＝现在、币种＝人民币）。",
    hint: "还差 3 项：分类、金额、向谁借。",
    cfg: [{"key":"cat","label":"分类","ftype":"cat","ph":"category"},{"key":"amt","label":"金额","ftype":"amount","ph":"amount"},{"key":"who","label":"向谁借","ftype":"person","ph":"person"},{"key":"opt_dl","label":"期限(选填)","ftype":"text","opt":true,"ph":"deadline"}],
  },
  "collect": {
    titleWait: "{word}还差 3 项",
    titleReady: "{word}已填齐",
    subWait: "补齐下面几项，就能记好这一笔。",
    subReady: "下面几项都填好了，这一句就能复制走。",
    todoWait: "还缺什么",
    todoTagWait: "TODO",
    chips: [{ key: "cat", label: "分类", small: "待补" }, { key: "amt", label: "金额", small: "待补" }, { key: "outId", label: "借出记录编号", small: "待补" }],
    fills: [{ label: "场景", value: "{word}" }],
    fields: [{ slot: "cat", label: "分类", kind: "select", req: true, options: [{ value: "", label: "请选择分类" }, { value: "借贷/收回", label: "借贷/收回" }, { value: "__other", label: "其他（手填）…" }] }, { slot: "amt", label: "金额", kind: "text", req: true, placeholder: "例：500" }, { slot: "outId", label: "借出记录编号", kind: "text", req: true, placeholder: "例：18" }],
    hint: "还差 3 项：分类、金额、借出记录编号。",
    cfg: [{"key":"cat","label":"分类","ftype":"cat","ph":"category"},{"key":"amt","label":"金额","ftype":"amount","ph":"amount"},{"key":"outId","label":"借出记录编号","ftype":"int","ph":"which"}],
  },
  "repay": {
    titleWait: "{word}还差 3 项",
    titleReady: "{word}已填齐",
    subWait: "补齐下面几项，就能记好这一笔。",
    subReady: "下面几项都填好了，这一句就能复制走。",
    todoWait: "还缺什么",
    todoTagWait: "TODO",
    chips: [{ key: "cat", label: "分类", small: "待补" }, { key: "amt", label: "金额", small: "待补" }, { key: "inId", label: "借入记录编号", small: "待补" }],
    fills: [{ label: "场景", value: "{word}" }],
    fields: [{ slot: "cat", label: "分类", kind: "select", req: true, options: [{ value: "", label: "请选择分类" }, { value: "借贷/偿还", label: "借贷/偿还" }, { value: "__other", label: "其他（手填）…" }] }, { slot: "amt", label: "金额", kind: "text", req: true, placeholder: "例：500" }, { slot: "inId", label: "借入记录编号", kind: "text", req: true, placeholder: "例：19" }],
    hint: "还差 3 项：分类、金额、借入记录编号。",
    cfg: [{"key":"cat","label":"分类","ftype":"cat","ph":"category"},{"key":"amt","label":"金额","ftype":"amount","ph":"amount"},{"key":"inId","label":"借入记录编号","ftype":"int","ph":"which"}],
  },
  "installment": {
    titleWait: "{word}还差 5 项",
    titleReady: "{word}已填齐",
    subWait: "补齐下面几项，就能记好这一笔。",
    subReady: "下面几项都填好了，这一句就能复制走。",
    todoWait: "还缺什么",
    todoTagWait: "TODO",
    chips: [{ key: "cat", label: "分类", small: "待补" }, { key: "amt", label: "金额", small: "待补" }, { key: "total", label: "总额", small: "待补" }, { key: "n", label: "期数", small: "待补" }, { key: "d1", label: "首期日", small: "待补" }],
    fills: [{ label: "场景", value: "{word}" }],
    fields: [{ slot: "cat", label: "分类", kind: "select", req: true, options: [{ value: "", label: "请选择分类" }, { value: "分期/手机", label: "分期/手机" }, { value: "分期/电脑", label: "分期/电脑" }, { value: "分期/家电", label: "分期/家电" }, { value: "__other", label: "其他（手填）…" }] }, { slot: "amt", label: "金额", kind: "text", req: true, placeholder: "例：100" }, { slot: "total", label: "总额", kind: "text", req: true, placeholder: "例：1200" }, { slot: "n", label: "期数", kind: "text", req: true, placeholder: "例：12" }, { slot: "d1", label: "首期日", kind: "date", req: true }],
    optFields: [{ slot: "opt_acct", label: "账户(选填)", kind: "text", req: false, placeholder: "选填" }, { slot: "opt_ledger", label: "账本(选填)", kind: "text", req: false, placeholder: "选填" }],
    optSummary: "账户／账本",
    optNote: "不填就留空：复制出的那句话里这几项会落 ___，助手照默认走（时间＝现在、币种＝人民币）。",
    hint: "还差 5 项：分类、金额、总额、期数、首期日。",
    cfg: [{"key":"cat","label":"分类","ftype":"cat","ph":"item_name"},{"key":"amt","label":"金额","ftype":"amount","ph":"amount"},{"key":"total","label":"总额","ftype":"total","ph":"total"},{"key":"n","label":"期数","ftype":"period","ph":"periods"},{"key":"d1","label":"首期日","ftype":"date","ph":"first_date"},{"key":"opt_acct","label":"账户(选填)","ftype":"text","opt":true,"ph":"account"},{"key":"opt_ledger","label":"账本(选填)","ftype":"text","opt":true,"ph":"ledger"}],
  },
  "plain": {
    titleWait: "{word}还差 2 项",
    titleReady: "{word}已填齐",
    subWait: "补齐下面几项，就能记好这一笔。",
    subReady: "下面几项都填好了，这一句就能复制走。",
    todoWait: "还缺什么",
    todoTagWait: "TODO",
    chips: [{ key: "cat", label: "分类", small: "待补" }, { key: "amt", label: "金额", small: "待补" }],
    fills: [{ label: "场景", value: "通用{word}" }],
    fields: [{ slot: "cat", label: "分类", kind: "select", req: true, options: [{ value: "", label: "请选择分类" }, { value: "餐饮", label: "餐饮" }, { value: "工资", label: "工资" }, { value: "出行", label: "出行" }, { value: "其他收入", label: "其他收入" }, { value: "__other", label: "其他（手填）…" }] }, { slot: "amt", label: "金额", kind: "text", req: true, placeholder: "例：12.5" }],
    optFields: [{ slot: "opt_note", label: "备注(选填)", kind: "text", req: false, placeholder: "选填" }, { slot: "opt_time", label: "时间(选填)", kind: "date", req: false }, { slot: "opt_acct", label: "账户(选填)", kind: "text", req: false, placeholder: "如 支付宝、微信" }],
    optSummary: "备注／时间／账户",
    optNote: "不填就留空：复制出的那句话里这几项会落 ___，助手照默认走（时间＝现在、币种＝人民币）。",
    hint: "还差 2 项：分类、金额。",
    cfg: [{"key":"cat","label":"分类","ftype":"cat","ph":"category"},{"key":"amt","label":"金额","ftype":"amount","ph":"amount"},{"key":"opt_note","label":"备注(选填)","ftype":"text","opt":true,"ph":"note"},{"key":"opt_time","label":"时间(选填)","ftype":"date","opt":true,"ph":"record_time"},{"key":"opt_acct","label":"账户(选填)","ftype":"text","opt":true,"ph":"account"}],
  },
  "update:none": {
    titleWait: "{word}缺记录编号",
    titleReady: "{word}已指明哪条",
    subWait: "说清改哪一条、改什么，就可以了。",
    subReady: "说清改哪一条、改什么，就可以了。",
    todoWait: "还缺什么",
    todoTagWait: "TODO",
    chips: [{ key: "rid", label: "记录编号", small: "待补" }],
    fills: [{ label: "形态", value: "先给编号再改" }],
    fields: [{ slot: "rid", label: "记录编号", kind: "text", req: true, placeholder: "例：1" }, { slot: "chg", label: "改哪一项（可选）", kind: "select", req: false, options: [{ value: "", label: "不指定（只给编号）" }, { value: "分类", label: "分类" }, { value: "金额", label: "金额" }, { value: "备注", label: "备注" }, { value: "账户", label: "账户" }, { value: "账本", label: "账本" }, { value: "时间", label: "时间" }] }, { slot: "chgval", label: "改成什么（可选）", kind: "text", req: false, placeholder: "例：餐饮" }],
    hint: "还差 1 项：记录编号。",
    cfg: [{"key":"rid","label":"记录编号","ftype":"rid","ph":"target"},{"key":"chg","label":"改哪一项","ftype":"text","opt":true,"nochip":true},{"key":"chgval","label":"改成什么","ftype":"text","opt":true,"needs":"chg","nochip":true}],
  },
  "update:undo": {
    titleWait: "{word}缺记录编号",
    titleReady: "{word}已指明哪条",
    subWait: "指明哪一条，就可以{word}。",
    subReady: "指明哪一条，就可以{word}。",
    todoWait: "还缺什么",
    todoTagWait: "TODO",
    chips: [{ key: "rid", label: "记录编号", small: "待补" }],
    fills: [{ label: "形态", value: "软删打标，不物理删" }],
    fields: [{ slot: "rid", label: "记录编号", kind: "text", req: true, placeholder: "例：2" }],
    hint: "还差 1 项：记录编号。",
    cfg: [{"key":"rid","label":"记录编号","ftype":"rid","ph":"target"}],
  },
  "update:restore": {
    titleWait: "{word}缺记录编号",
    titleReady: "{word}已指明哪条",
    subWait: "指明哪一条，就可以{word}。",
    subReady: "指明哪一条，就可以{word}。",
    todoWait: "还缺什么",
    todoTagWait: "TODO",
    chips: [{ key: "rid", label: "记录编号", small: "待补" }],
    fills: [{ label: "形态", value: "只{word}已撤销的" }],
    fields: [{ slot: "rid", label: "记录编号", kind: "text", req: true, placeholder: "例：2" }],
    hint: "还差 1 项：记录编号。",
    cfg: [{"key":"rid","label":"记录编号","ftype":"rid","ph":"target"}],
  },
};
