/** 采集页（SAY）逐词数据表——一份实现 ＋ 16 份数据（#1079）。
 *
 * 数据全部从 16 件判地原型 docs/skills/skill-bill/proto/say-collect/*-v2.3.html 的可见文本反推：
 * 店头两态、缺项徽章、已替你填好的行、表单字段与候选项、选填组、提示行、页脚、SAY prompt 模板与槽位配置。
 * 版式一行都不在这里——版式只住 ./saySheet.ts 一处。
 */

import type { SayWordSpec } from './saySheet.js';

export const SAY_WORDS: Readonly<Record<string, SayWordSpec>> = {
  "记支出": {
    brand: "饼干记账 · 记支出",
    titleWait: "记支出还差 2 项",
    titleReady: "记支出已填齐",
    subWait: "补齐下面几项，就能记好这一笔。",
    subReady: "下面几项都填好了，这一句就能复制走。",
    todoWait: "还缺什么",
    todoTagWait: "TODO",
    chips: [{ key: "cat", label: "分类", small: "待补" }, { key: "amt", label: "金额", small: "待补" }],
    fills: [{ label: "方向", value: "金额取负数" }, { label: "场景", value: "记支出" }],
    fields: [{ slot: "cat", label: "分类", kind: "select", req: true, options: [{ value: "", label: "请选择分类" }, { value: "餐饮", label: "餐饮" }, { value: "出行", label: "出行" }, { value: "购物", label: "购物" }, { value: "居住", label: "居住" }, { value: "医疗", label: "医疗" }, { value: "__other", label: "其他（手填）…" }] }, { slot: "amt", label: "金额", kind: "text", req: true, placeholder: "例：12.5" }],
    optFields: [{ slot: "opt_note", label: "备注(选填)", kind: "text", req: false, placeholder: "选填，如 加班餐" }, { slot: "opt_time", label: "时间(选填)", kind: "date", req: false }, { slot: "opt_acct", label: "账户(选填)", kind: "text", req: false, placeholder: "如 支付宝、微信" }, { slot: "opt_ledger", label: "账本(选填)", kind: "text", req: false, placeholder: "如 旅行、生活" }, { slot: "opt_cur", label: "币种(选填)", kind: "text", req: false, placeholder: "空＝人民币；外币如 USD" }],
    optSummary: "备注／时间／账户／账本／币种",
    optNote: "不填就留空：复制出的那句话里这几项会落 ___，助手照默认走（时间＝现在、币种＝人民币）。",
    hint: "还差 2 项：分类、金额。",
    foot: "饼干记账 · 记支出",
    sayTemplate: "请你加载技能 饼干记账,执行唤醒词「记支出」。\n\n我要记一笔支出。\n\n金额:{{amount}}\n分类/名目:{{category}}\n备注(选填):{{note}}\n时间(选填):{{record_time}}\n账户(选填):{{account}}\n账本(选填):{{ledger}}\n币种(选填):{{currency}}",
    cfg: [{"key":"cat","label":"分类","ftype":"cat","ph":"category"},{"key":"amt","label":"金额","ftype":"amount","ph":"amount"},{"key":"opt_note","label":"备注(选填)","ftype":"text","opt":true,"ph":"note"},{"key":"opt_time","label":"时间(选填)","ftype":"date","opt":true,"ph":"record_time"},{"key":"opt_acct","label":"账户(选填)","ftype":"text","opt":true,"ph":"account"},{"key":"opt_ledger","label":"账本(选填)","ftype":"text","opt":true,"ph":"ledger"},{"key":"opt_cur","label":"币种(选填)","ftype":"text","opt":true,"ph":"currency"}],
  },
  "记收入": {
    brand: "饼干记账 · 记收入",
    titleWait: "记收入还差 2 项",
    titleReady: "记收入已填齐",
    subWait: "补齐下面几项，就能记好这一笔。",
    subReady: "下面几项都填好了，这一句就能复制走。",
    todoWait: "还缺什么",
    todoTagWait: "TODO",
    chips: [{ key: "cat", label: "分类", small: "待补" }, { key: "amt", label: "金额", small: "待补" }],
    fills: [{ label: "方向", value: "金额取正数" }, { label: "场景", value: "记收入" }],
    fields: [{ slot: "cat", label: "分类", kind: "select", req: true, options: [{ value: "", label: "请选择分类" }, { value: "工资", label: "工资" }, { value: "奖金", label: "奖金" }, { value: "副业收入", label: "副业收入" }, { value: "其他收入", label: "其他收入" }, { value: "__other", label: "其他（手填）…" }] }, { slot: "amt", label: "金额", kind: "text", req: true, placeholder: "例：8000" }],
    optFields: [{ slot: "opt_note", label: "备注(选填)", kind: "text", req: false, placeholder: "选填" }, { slot: "opt_time", label: "时间(选填)", kind: "date", req: false }, { slot: "opt_acct", label: "账户(选填)", kind: "text", req: false, placeholder: "如 银行卡、微信" }, { slot: "opt_cur", label: "币种(选填)", kind: "text", req: false, placeholder: "空＝人民币；外币如 USD" }],
    optSummary: "备注／时间／账户／币种",
    optNote: "不填就留空：复制出的那句话里这几项会落 ___，助手照默认走（时间＝现在、币种＝人民币）。",
    hint: "还差 2 项：分类、金额。",
    foot: "饼干记账 · 记收入",
    sayTemplate: "请你加载技能 饼干记账,执行唤醒词「记收入」。\n\n我要记一笔收入。\n\n金额:{{amount}}\n分类/名目:{{category}}\n备注(选填):{{note}}\n时间(选填):{{record_time}}\n账户(选填):{{account}}\n币种(选填):{{currency}}",
    cfg: [{"key":"cat","label":"分类","ftype":"cat","ph":"category"},{"key":"amt","label":"金额","ftype":"amount","ph":"amount"},{"key":"opt_note","label":"备注(选填)","ftype":"text","opt":true,"ph":"note"},{"key":"opt_time","label":"时间(选填)","ftype":"date","opt":true,"ph":"record_time"},{"key":"opt_acct","label":"账户(选填)","ftype":"text","opt":true,"ph":"account"},{"key":"opt_cur","label":"币种(选填)","ftype":"text","opt":true,"ph":"currency"}],
  },
  "拍账单": {
    brand: "饼干记账 · 拍账单",
    titleWait: "账单要素还没齐",
    titleReady: "账单要素已齐",
    subWait: "补齐下面几项，就能记好这一笔。",
    subReady: "下面几项都填好了，这一句就能复制走。",
    todoWait: "还缺什么",
    todoTagWait: "TODO",
    chips: [{ key: "cat", label: "分类", small: "待补" }, { key: "amt", label: "金额", small: "待补" }],
    fills: [{ label: "图片", value: "以外置识别为准" }, { label: "场景", value: "拍账单" }],
    fields: [{ slot: "cat", label: "分类", kind: "select", req: true, options: [{ value: "", label: "请选择分类" }, { value: "餐饮", label: "餐饮" }, { value: "购物", label: "购物" }, { value: "出行", label: "出行" }, { value: "__other", label: "其他（手填）…" }] }, { slot: "amt", label: "金额", kind: "text", req: true, placeholder: "例：30" }],
    hint: "还差 2 项：分类、金额。",
    foot: "饼干记账 · 拍账单",
    sayTemplate: "请你加载技能 饼干记账,执行唤醒词「拍账单」。\n\n我要拍账单照片记账，请识别图片中的金额和项目。\n\n分类:{{category}}\n金额:{{amount}}",
    cfg: [{"key":"cat","label":"分类","ftype":"cat","ph":"category"},{"key":"amt","label":"金额","ftype":"amount","ph":"amount"}],
  },
  "批量录入": {
    brand: "饼干记账 · 批量录入",
    titleWait: "批量录入还差 2 项",
    titleReady: "批量录入已填齐",
    subWait: "补齐下面几项，就能记好这一笔。",
    subReady: "下面几项都填好了，这一句就能复制走。",
    todoWait: "还缺什么",
    todoTagWait: "TODO",
    chips: [{ key: "cat", label: "分类", small: "待补" }, { key: "amt", label: "金额", small: "待补" }],
    fills: [{ label: "形态", value: "逐笔在页上确认" }, { label: "场景", value: "批量录入" }],
    fields: [{ slot: "cat", label: "分类", kind: "select", req: true, options: [{ value: "", label: "请选择分类" }, { value: "餐饮", label: "餐饮" }, { value: "出行", label: "出行" }, { value: "购物", label: "购物" }, { value: "__other", label: "其他（手填）…" }] }, { slot: "amt", label: "金额", kind: "text", req: true, placeholder: "例：10" }],
    optFields: [{ slot: "opt_ledger", label: "账本(选填)", kind: "text", req: false, placeholder: "如 旅行" }],
    optSummary: "账本",
    optNote: "不填就留空：复制出的那句话里这几项会落 ___，助手照默认走（时间＝现在、币种＝人民币）。",
    hint: "还差 2 项：分类、金额。",
    foot: "饼干记账 · 批量录入",
    sayTemplate: "请你加载技能 饼干记账,执行唤醒词「批量录入」。\n\n我要批量记几笔账。\n\n条目:{{items}}\n账本(选填):{{ledger}}",
    cfg: [{"key":"cat","label":"分类","ftype":"cat"},{"key":"amt","label":"金额","ftype":"amount"},{"key":"opt_ledger","label":"账本(选填)","ftype":"text","opt":true,"ph":"ledger"}],
  },
  "记退款": {
    brand: "饼干记账 · 记退款",
    titleWait: "记退款还差 3 项",
    titleReady: "记退款已填齐",
    subWait: "补齐下面几项，就能记好这一笔。",
    subReady: "下面几项都填好了，这一句就能复制走。",
    todoWait: "还缺什么",
    todoTagWait: "TODO",
    chips: [{ key: "cat", label: "分类", small: "待补" }, { key: "amt", label: "金额", small: "待补" }, { key: "orig", label: "原支出编号", small: "待补" }],
    fills: [{ label: "场景", value: "记退款" }],
    fields: [{ slot: "cat", label: "分类", kind: "select", req: true, options: [{ value: "", label: "请选择分类" }, { value: "退款/冲销", label: "退款/冲销" }, { value: "__other", label: "其他（手填）…" }] }, { slot: "amt", label: "金额", kind: "text", req: true, placeholder: "例：20" }, { slot: "orig", label: "原支出编号", kind: "text", req: true, placeholder: "例：11" }],
    optFields: [{ slot: "opt_reason", label: "退款原因(选填)", kind: "text", req: false, placeholder: "如 退货、取消订单、差价" }],
    optSummary: "退款原因",
    optNote: "不填就留空：复制出的那句话里这几项会落 ___，助手照默认走（时间＝现在、币种＝人民币）。",
    hint: "还差 3 项：分类、金额、原支出编号。",
    foot: "饼干记账 · 记退款",
    sayTemplate: "请你加载技能 饼干记账,执行唤醒词「记退款」。\n\n我要记一笔退款，冲销原支出。\n\n金额:{{amount}}\n原支出:{{original}}\n退款原因(选填):{{reason}}\n分类:{{category}}",
    cfg: [{"key":"cat","label":"分类","ftype":"cat","ph":"category"},{"key":"amt","label":"金额","ftype":"amount","ph":"amount"},{"key":"orig","label":"原支出编号","ftype":"int","ph":"original"},{"key":"opt_reason","label":"退款原因(选填)","ftype":"text","opt":true,"ph":"reason"}],
  },
  "记报销": {
    brand: "饼干记账 · 记报销",
    titleWait: "记报销还差 2 项",
    titleReady: "记报销已填齐",
    subWait: "补齐下面几项，就能记好这一笔。",
    subReady: "下面几项都填好了，这一句就能复制走。",
    todoWait: "还缺什么",
    todoTagWait: "TODO",
    chips: [{ key: "cat", label: "分类", small: "待补" }, { key: "amt", label: "金额", small: "待补" }],
    fills: [{ label: "场景", value: "记报销" }],
    fields: [{ slot: "cat", label: "分类", kind: "select", req: true, options: [{ value: "", label: "请选择分类" }, { value: "出行", label: "出行" }, { value: "餐饮", label: "餐饮" }, { value: "住宿", label: "住宿" }, { value: "办公", label: "办公" }, { value: "__other", label: "其他（手填）…" }] }, { slot: "amt", label: "金额", kind: "text", req: true, placeholder: "例：100" }],
    optFields: [{ slot: "opt_note", label: "备注(选填)", kind: "text", req: false, placeholder: "自动加 #待报销" }, { slot: "opt_time", label: "时间(选填)", kind: "date", req: false }],
    optSummary: "备注／时间",
    optNote: "不填就留空：复制出的那句话里这几项会落 ___，助手照默认走（时间＝现在、币种＝人民币）。",
    hint: "还差 2 项：分类、金额。",
    foot: "饼干记账 · 记报销",
    sayTemplate: "请你加载技能 饼干记账,执行唤醒词「记报销」。\n\n我要记一笔报销支出，自动加 #待报销标签。\n\n金额:{{amount}}\n分类(选填):{{category}}\n备注(选填):{{note}}\n时间(选填):{{record_time}}",
    cfg: [{"key":"cat","label":"分类","ftype":"cat","ph":"category"},{"key":"amt","label":"金额","ftype":"amount","ph":"amount"},{"key":"opt_note","label":"备注(选填)","ftype":"text","opt":true,"ph":"note"},{"key":"opt_time","label":"时间(选填)","ftype":"date","opt":true,"ph":"record_time"}],
  },
  "报销到账": {
    brand: "饼干记账 · 报销到账",
    titleWait: "报销到账还差 3 项",
    titleReady: "报销到账已填齐",
    subWait: "补齐下面几项，就能记好这一笔。",
    subReady: "下面几项都填好了，这一句就能复制走。",
    todoWait: "还缺什么",
    todoTagWait: "TODO",
    chips: [{ key: "cat", label: "分类", small: "待补" }, { key: "amt", label: "金额", small: "待补" }, { key: "rb", label: "待报销记录编号", small: "待补" }],
    fills: [{ label: "场景", value: "报销到账" }],
    fields: [{ slot: "cat", label: "分类", kind: "select", req: true, options: [{ value: "", label: "请选择分类" }, { value: "其他收入/报销回款", label: "其他收入/报销回款" }, { value: "__other", label: "其他（手填）…" }] }, { slot: "amt", label: "金额", kind: "text", req: true, placeholder: "例：100" }, { slot: "rb", label: "待报销记录编号", kind: "text", req: true, placeholder: "例：16" }],
    hint: "还差 3 项：分类、金额、待报销记录编号。",
    foot: "饼干记账 · 报销到账",
    sayTemplate: "请你加载技能 饼干记账,执行唤醒词「报销到账」。\n\n我的报销到账了，记一笔收入并流转标签。\n\n金额:{{amount}}\n关联:{{related}}\n分类:{{category}}",
    cfg: [{"key":"cat","label":"分类","ftype":"cat","ph":"category"},{"key":"amt","label":"金额","ftype":"amount","ph":"amount"},{"key":"rb","label":"待报销记录编号","ftype":"int","ph":"related"}],
  },
  "记借出": {
    brand: "饼干记账 · 记借出",
    titleWait: "记借出还差 3 项",
    titleReady: "记借出已填齐",
    subWait: "补齐下面几项，就能记好这一笔。",
    subReady: "下面几项都填好了，这一句就能复制走。",
    todoWait: "还缺什么",
    todoTagWait: "TODO",
    chips: [{ key: "cat", label: "分类", small: "待补" }, { key: "amt", label: "金额", small: "待补" }, { key: "who", label: "借给谁", small: "待补" }],
    fills: [{ label: "场景", value: "记借出" }],
    fields: [{ slot: "cat", label: "分类", kind: "select", req: true, options: [{ value: "", label: "请选择分类" }, { value: "借贷/借出", label: "借贷/借出" }, { value: "__other", label: "其他（手填）…" }] }, { slot: "amt", label: "金额", kind: "text", req: true, placeholder: "例：500" }, { slot: "who", label: "借给谁", kind: "text", req: true, placeholder: "例：小王" }],
    optFields: [{ slot: "opt_dl", label: "期限(选填)", kind: "text", req: false, placeholder: "如 月底还" }],
    optSummary: "期限",
    optNote: "不填就留空：复制出的那句话里这几项会落 ___，助手照默认走（时间＝现在、币种＝人民币）。",
    hint: "还差 3 项：分类、金额、借给谁。",
    foot: "饼干记账 · 记借出",
    sayTemplate: "请你加载技能 饼干记账,执行唤醒词「记借出」。\n\n我借给别人一笔钱。\n\n金额:{{amount}}\n对象:{{person}}\n期限(选填):{{deadline}}\n分类:{{category}}",
    cfg: [{"key":"cat","label":"分类","ftype":"cat","ph":"category"},{"key":"amt","label":"金额","ftype":"amount","ph":"amount"},{"key":"who","label":"借给谁","ftype":"person","ph":"person"},{"key":"opt_dl","label":"期限(选填)","ftype":"text","opt":true,"ph":"deadline"}],
  },
  "记借入": {
    brand: "饼干记账 · 记借入",
    titleWait: "记借入还差 3 项",
    titleReady: "记借入已填齐",
    subWait: "补齐下面几项，就能记好这一笔。",
    subReady: "下面几项都填好了，这一句就能复制走。",
    todoWait: "还缺什么",
    todoTagWait: "TODO",
    chips: [{ key: "cat", label: "分类", small: "待补" }, { key: "amt", label: "金额", small: "待补" }, { key: "who", label: "向谁借", small: "待补" }],
    fills: [{ label: "场景", value: "记借入" }],
    fields: [{ slot: "cat", label: "分类", kind: "select", req: true, options: [{ value: "", label: "请选择分类" }, { value: "借贷/借入", label: "借贷/借入" }, { value: "__other", label: "其他（手填）…" }] }, { slot: "amt", label: "金额", kind: "text", req: true, placeholder: "例：500" }, { slot: "who", label: "向谁借", kind: "text", req: true, placeholder: "例：李四" }],
    optFields: [{ slot: "opt_dl", label: "期限(选填)", kind: "text", req: false, placeholder: "选填" }],
    optSummary: "期限",
    optNote: "不填就留空：复制出的那句话里这几项会落 ___，助手照默认走（时间＝现在、币种＝人民币）。",
    hint: "还差 3 项：分类、金额、向谁借。",
    foot: "饼干记账 · 记借入",
    sayTemplate: "请你加载技能 饼干记账,执行唤醒词「记借入」。\n\n我向别人借了一笔钱。\n\n金额:{{amount}}\n对象:{{person}}\n期限(选填):{{deadline}}\n分类:{{category}}",
    cfg: [{"key":"cat","label":"分类","ftype":"cat","ph":"category"},{"key":"amt","label":"金额","ftype":"amount","ph":"amount"},{"key":"who","label":"向谁借","ftype":"person","ph":"person"},{"key":"opt_dl","label":"期限(选填)","ftype":"text","opt":true,"ph":"deadline"}],
  },
  "记收回": {
    brand: "饼干记账 · 记收回",
    titleWait: "记收回还差 3 项",
    titleReady: "记收回已填齐",
    subWait: "补齐下面几项，就能记好这一笔。",
    subReady: "下面几项都填好了，这一句就能复制走。",
    todoWait: "还缺什么",
    todoTagWait: "TODO",
    chips: [{ key: "cat", label: "分类", small: "待补" }, { key: "amt", label: "金额", small: "待补" }, { key: "outId", label: "借出记录编号", small: "待补" }],
    fills: [{ label: "场景", value: "记收回" }],
    fields: [{ slot: "cat", label: "分类", kind: "select", req: true, options: [{ value: "", label: "请选择分类" }, { value: "借贷/收回", label: "借贷/收回" }, { value: "__other", label: "其他（手填）…" }] }, { slot: "amt", label: "金额", kind: "text", req: true, placeholder: "例：500" }, { slot: "outId", label: "借出记录编号", kind: "text", req: true, placeholder: "例：18" }],
    hint: "还差 3 项：分类、金额、借出记录编号。",
    foot: "饼干记账 · 记收回",
    sayTemplate: "请你加载技能 饼干记账,执行唤醒词「记收回」。\n\n别人还我钱了，记一笔收回。\n\n哪一笔:{{which}}\n金额:{{amount}}\n分类:{{category}}",
    cfg: [{"key":"cat","label":"分类","ftype":"cat","ph":"category"},{"key":"amt","label":"金额","ftype":"amount","ph":"amount"},{"key":"outId","label":"借出记录编号","ftype":"int","ph":"which"}],
  },
  "记偿还": {
    brand: "饼干记账 · 记偿还",
    titleWait: "记偿还还差 3 项",
    titleReady: "记偿还已填齐",
    subWait: "补齐下面几项，就能记好这一笔。",
    subReady: "下面几项都填好了，这一句就能复制走。",
    todoWait: "还缺什么",
    todoTagWait: "TODO",
    chips: [{ key: "cat", label: "分类", small: "待补" }, { key: "amt", label: "金额", small: "待补" }, { key: "inId", label: "借入记录编号", small: "待补" }],
    fills: [{ label: "场景", value: "记偿还" }],
    fields: [{ slot: "cat", label: "分类", kind: "select", req: true, options: [{ value: "", label: "请选择分类" }, { value: "借贷/偿还", label: "借贷/偿还" }, { value: "__other", label: "其他（手填）…" }] }, { slot: "amt", label: "金额", kind: "text", req: true, placeholder: "例：500" }, { slot: "inId", label: "借入记录编号", kind: "text", req: true, placeholder: "例：19" }],
    hint: "还差 3 项：分类、金额、借入记录编号。",
    foot: "饼干记账 · 记偿还",
    sayTemplate: "请你加载技能 饼干记账,执行唤醒词「记偿还」。\n\n我要还一笔借入的钱。\n\n哪一笔:{{which}}\n金额:{{amount}}\n分类:{{category}}",
    cfg: [{"key":"cat","label":"分类","ftype":"cat","ph":"category"},{"key":"amt","label":"金额","ftype":"amount","ph":"amount"},{"key":"inId","label":"借入记录编号","ftype":"int","ph":"which"}],
  },
  "记分期": {
    brand: "饼干记账 · 记分期",
    titleWait: "记分期还差 5 项",
    titleReady: "记分期已填齐",
    subWait: "补齐下面几项，就能记好这一笔。",
    subReady: "下面几项都填好了，这一句就能复制走。",
    todoWait: "还缺什么",
    todoTagWait: "TODO",
    chips: [{ key: "cat", label: "分类", small: "待补" }, { key: "amt", label: "金额", small: "待补" }, { key: "total", label: "总额", small: "待补" }, { key: "n", label: "期数", small: "待补" }, { key: "d1", label: "首期日", small: "待补" }],
    fills: [{ label: "场景", value: "记分期" }],
    fields: [{ slot: "cat", label: "分类", kind: "select", req: true, options: [{ value: "", label: "请选择分类" }, { value: "分期/手机", label: "分期/手机" }, { value: "分期/电脑", label: "分期/电脑" }, { value: "分期/家电", label: "分期/家电" }, { value: "__other", label: "其他（手填）…" }] }, { slot: "amt", label: "金额", kind: "text", req: true, placeholder: "例：100" }, { slot: "total", label: "总额", kind: "text", req: true, placeholder: "例：1200" }, { slot: "n", label: "期数", kind: "text", req: true, placeholder: "例：12" }, { slot: "d1", label: "首期日", kind: "date", req: true }],
    optFields: [{ slot: "opt_acct", label: "账户(选填)", kind: "text", req: false, placeholder: "选填" }, { slot: "opt_ledger", label: "账本(选填)", kind: "text", req: false, placeholder: "选填" }],
    optSummary: "账户／账本",
    optNote: "不填就留空：复制出的那句话里这几项会落 ___，助手照默认走（时间＝现在、币种＝人民币）。",
    hint: "还差 5 项：分类、金额、总额、期数、首期日。",
    foot: "饼干记账 · 记分期",
    sayTemplate: "请你加载技能 饼干记账,执行唤醒词「记分期」。\n\n我要记一笔分期，按月平摊预写。\n\n名目:{{item_name}}\n总价:{{total}}\n期数:{{periods}}\n首期日(选填):{{first_date}}\n账户(选填):{{account}}\n账本(选填):{{ledger}}\n金额:{{amount}}",
    cfg: [{"key":"cat","label":"分类","ftype":"cat","ph":"item_name"},{"key":"amt","label":"金额","ftype":"amount","ph":"amount"},{"key":"total","label":"总额","ftype":"total","ph":"total"},{"key":"n","label":"期数","ftype":"period","ph":"periods"},{"key":"d1","label":"首期日","ftype":"date","ph":"first_date"},{"key":"opt_acct","label":"账户(选填)","ftype":"text","opt":true,"ph":"account"},{"key":"opt_ledger","label":"账本(选填)","ftype":"text","opt":true,"ph":"ledger"}],
  },
  "记一笔": {
    brand: "饼干记账 · 记一笔",
    titleWait: "记一笔还差 2 项",
    titleReady: "记一笔已填齐",
    subWait: "补齐下面几项，就能记好这一笔。",
    subReady: "下面几项都填好了，这一句就能复制走。",
    todoWait: "还缺什么",
    todoTagWait: "TODO",
    chips: [{ key: "cat", label: "分类", small: "待补" }, { key: "amt", label: "金额", small: "待补" }],
    fills: [{ label: "场景", value: "通用记一笔" }],
    fields: [{ slot: "cat", label: "分类", kind: "select", req: true, options: [{ value: "", label: "请选择分类" }, { value: "餐饮", label: "餐饮" }, { value: "工资", label: "工资" }, { value: "出行", label: "出行" }, { value: "其他收入", label: "其他收入" }, { value: "__other", label: "其他（手填）…" }] }, { slot: "amt", label: "金额", kind: "text", req: true, placeholder: "例：12.5" }],
    optFields: [{ slot: "opt_note", label: "备注(选填)", kind: "text", req: false, placeholder: "选填" }, { slot: "opt_time", label: "时间(选填)", kind: "date", req: false }, { slot: "opt_acct", label: "账户(选填)", kind: "text", req: false, placeholder: "如 支付宝、微信" }],
    optSummary: "备注／时间／账户",
    optNote: "不填就留空：复制出的那句话里这几项会落 ___，助手照默认走（时间＝现在、币种＝人民币）。",
    hint: "还差 2 项：分类、金额。",
    foot: "饼干记账 · 记一笔",
    sayTemplate: "请你加载技能 饼干记账,执行唤醒词「记一笔」。\n\n我要记一笔，支出或收入都可以。\n\n金额:{{amount}}\n分类/名目:{{category}}\n备注(选填):{{note}}\n时间(选填):{{record_time}}\n账户(选填):{{account}}",
    cfg: [{"key":"cat","label":"分类","ftype":"cat","ph":"category"},{"key":"amt","label":"金额","ftype":"amount","ph":"amount"},{"key":"opt_note","label":"备注(选填)","ftype":"text","opt":true,"ph":"note"},{"key":"opt_time","label":"时间(选填)","ftype":"date","opt":true,"ph":"record_time"},{"key":"opt_acct","label":"账户(选填)","ftype":"text","opt":true,"ph":"account"}],
  },
  "改记录": {
    brand: "饼干记账 · 改记录",
    titleWait: "改记录缺记录编号",
    titleReady: "改记录已指明哪条",
    subWait: "说清改哪一条、改什么，就可以了。",
    subReady: "说清改哪一条、改什么，就可以了。",
    todoWait: "还缺什么",
    todoTagWait: "TODO",
    chips: [{ key: "rid", label: "记录编号", small: "待补" }],
    fills: [{ label: "形态", value: "先给编号再改" }],
    fields: [{ slot: "rid", label: "记录编号", kind: "text", req: true, placeholder: "例：1" }, { slot: "chg", label: "改哪一项（可选）", kind: "select", req: false, options: [{ value: "", label: "不指定（只给编号）" }, { value: "分类", label: "分类" }, { value: "金额", label: "金额" }, { value: "备注", label: "备注" }, { value: "账户", label: "账户" }, { value: "账本", label: "账本" }, { value: "时间", label: "时间" }] }, { slot: "chgval", label: "改成什么（可选）", kind: "text", req: false, placeholder: "例：餐饮" }],
    hint: "还差 1 项：记录编号。",
    foot: "饼干记账 · 改记录",
    sayTemplate: "请你加载技能 饼干记账,执行唤醒词「改记录」。\n\n我要改一条已有记录。执行前请告诉我目标是哪条，确认后再改。\n\n目标:{{target}}\n要改的字段:{{changes}}",
    cfg: [{"key":"rid","label":"记录编号","ftype":"rid","ph":"target"},{"key":"chg","label":"改哪一项","ftype":"text","opt":true},{"key":"chgval","label":"改成什么","ftype":"text","opt":true}],
  },
  "撤销": {
    brand: "饼干记账 · 撤销",
    titleWait: "撤销缺记录编号",
    titleReady: "撤销已指明哪条",
    subWait: "指明哪一条，就可以撤销。",
    subReady: "指明哪一条，就可以撤销。",
    todoWait: "还缺什么",
    todoTagWait: "TODO",
    chips: [{ key: "rid", label: "记录编号", small: "待补" }],
    fills: [{ label: "形态", value: "软删打标，不物理删" }],
    fields: [{ slot: "rid", label: "记录编号", kind: "text", req: true, placeholder: "例：2" }],
    hint: "还差 1 项：记录编号。",
    foot: "饼干记账 · 撤销",
    sayTemplate: "请你加载技能 饼干记账,执行唤醒词「撤销」。\n\n我要撤销一条记录（软删）。执行前请告诉我目标是哪条，确认后再撤销。\n\n目标:{{target}}",
    cfg: [{"key":"rid","label":"记录编号","ftype":"rid","ph":"target"}],
  },
  "恢复": {
    brand: "饼干记账 · 恢复",
    titleWait: "恢复缺记录编号",
    titleReady: "恢复已指明哪条",
    subWait: "指明哪一条，就可以恢复。",
    subReady: "指明哪一条，就可以恢复。",
    todoWait: "还缺什么",
    todoTagWait: "TODO",
    chips: [{ key: "rid", label: "记录编号", small: "待补" }],
    fills: [{ label: "形态", value: "只恢复已撤销的" }],
    fields: [{ slot: "rid", label: "记录编号", kind: "text", req: true, placeholder: "例：2" }],
    hint: "还差 1 项：记录编号。",
    foot: "饼干记账 · 恢复",
    sayTemplate: "请你加载技能 饼干记账,执行唤醒词「恢复」。\n\n我要恢复一条已撤销的记录。执行前请告诉我目标是哪条，确认后再恢复。\n\n目标:{{target}}",
    cfg: [{"key":"rid","label":"记录编号","ftype":"rid","ph":"target"}],
  },
};
