/** radar-profile · **读数件那一块样式**（同目录第三份样式来源；由 `style.ts` 的 `radarProfileCss()` 汇总）。
 *
 *  为什么有这一件：本件一次落三个形态，样式段挤在一件里会超本包告警线 350
 *  （`packages/base-render/AGENTS.md`，先例 `scatter-fit/style-forms.ts`、`cash-walerine` 的 `style-forms.ts`）。
 *  边界按「图」与「读数」切：
 *   · `style.ts`：卡壳（卡头／标题／时间窗／尾句）＋ 图（图框／网格／辐条／两条轮廓／顶点／轴名）＋ 两处容器查询；
 *   · 本件：**图外面的那些读数件**（刻度条／读数表／圆心平均分／图例／未达标点名／脚注）；
 *   · `style-forms.ts`：两形态自己的形状（扇区／外沿弧／达标环／轴表的行与轨道）。
 *  **取值一个字节都不许改**——搬的只是「住哪个文件」，顺序即层叠顺序（各段选择器互不相交，顺序不影响结果）。
 *
 *  纪律同 `style.ts`：只经 `skinVar()` 读皮肤／全部规则 scope 在 `.<prefix>page-ui` 之下／零 `:root`／
 *  零 `!important`／零颜色字面量（淡洗走 `color-mix()`，**不拿 `ink` 系当面**）。
 */
import { skinVar } from '../skin/contract.js';
import { radarProfileSlot, type RadarProfileSlot } from './attrs.js';

/** 换行（仓库口径：不写字面换行转义）。 */
const LF = String.fromCharCode(10);

/** 一个百分比档：往卡面掺 `weight`% 的语义色（**淡洗是合法的面**，实心墨块才是禁止的那一种）。 */
const wash = (token: 'ok' | 'warn', weight: number): string =>
  'color-mix(in srgb, ' + skinVar(token) + ' ' + String(weight) + '%, ' + skinVar('surface') + ')';

/** 读数件那一块的样式。恒返回非空 CSS 文本（由 `radarProfileCss()` 插在正确的位置上）。 */
export function radarProfileReadoutsCss(input?: { readonly prefix?: string }): string {
  const p = input !== undefined && input !== null
    && typeof input.prefix === 'string' && input.prefix !== '' ? input.prefix : 'ilife-';
  const root = '.' + p + 'page-ui';
  const s = (slot: RadarProfileSlot): string => root + ' .' + radarProfileSlot(slot, p);
  /* 槽类名（**不带 scope**）：只用在**已经落进本件某条选择器内部**的位置（前缀由外层那条选择器给）。 */
  const c = (slot: RadarProfileSlot): string => '.' + radarProfileSlot(slot, p);

  return [
    '/* 印出来的刻度（三圈格子各是多少分）：它是这一张图的尺子，读者与判据都从它读。 */',
    s('scale') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  gap: 3px 12px;',
    '  margin: 0;',
    '  padding: 8px 0 0;',
    '  border-top: 1px solid ' + skinVar('line') + ';',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '}',
    s('scale-item') + ' {',
    '  min-width: 0;',
    '  font-variant-numeric: tabular-nums;',
    '  overflow-wrap: anywhere;',
    '}',
    /* 读数表：轴 ｜ 本期 ｜ 上期 ｜ 差。列宽让给数字（`auto`），轴名那一列自己收窄；
       整表有宽度上限：宽档并排时不让数字被拉到离轴名半张卡那么远。 */
    s('table') + ' {',
    '  display: grid;',
    '  align-content: start;',
    '  min-width: 0;',
    '  max-width: 30em;',
    '}',
    s('trow') + ' {',
    '  display: grid;',
    '  grid-template-columns: minmax(0, 1fr) minmax(0, auto) minmax(0, auto) minmax(0, auto);',
    '  gap: 4px 10px;',
    '  align-items: baseline;',
    '  min-height: 32px;',
    '  padding: 5px 2px;',
    '  min-width: 0;',
    '}',
    s('trow') + ' + ' + c('trow') + ' {',
    '  border-top: 1px solid ' + skinVar('line') + ';',
    '}',
    s('trow') + '.is-head {',
    '  min-height: 0;',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '}',
    s('tname') + ' {',
    '  min-width: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 600;',
    '  overflow-wrap: anywhere;',
    '}',
    s('trow') + '.is-head ' + c('tname') + ' {',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '}',
    s('tnum') + ' {',
    '  min-width: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 700;',
    '  font-variant-numeric: tabular-nums;',
    '  text-align: right;',
    /* 读数是这一行的答案：**永不换行、永不 `…` 截断**（格子跟着数字走，见上面那三列 `auto`）。 */
    '  white-space: nowrap;',
    '}',
    s('trow') + '.is-head ' + c('tnum') + ' {',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '}',
    /* 差那一格：方向由字形与正负号给（`▲ +14`／`▼ −7`／`持平`）——**不拿颜色说方向**。 */
    s('tdelta') + ' {',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '  font-variant-numeric: tabular-nums;',
    '  text-align: right;',
    '  white-space: nowrap;',
    '}',
    s('tdelta') + '.is-up, ' + s('tdelta') + '.is-down {',
    '  color: ' + skinVar('ink') + ';',
    '  font-weight: 700;',
    '}',
    /* 圆心那块：平均分（是平均，不是总分——几根轴加起来没有意义）。 */
    s('hub') + ' {',
    '  position: absolute;',
    '  left: 50%;',
    '  top: 50%;',
    '  transform: translate(-50%, -50%);',
    '  display: grid;',
    '  justify-items: center;',
    '  padding: 3px 9px;',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  text-align: center;',
    '}',
    s('hub-value') + ' {',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: ' + skinVar('fs-h2') + ';',
    '  font-weight: 700;',
    '  line-height: 1.1;',
    '  font-variant-numeric: tabular-nums;',
    '}',
    s('hub-label') + ' {',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-style: normal;',
    '  font-weight: 600;',
    '}',
    /* 图例：每一项是「形 ＋ 字」——线段说本期／上期，色块说达标／未达标。 */
    s('legend') + ' {',
    '  list-style: none;',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: center;',
    '  gap: 4px 14px;',
    '  margin: 0;',
    '  padding: 0;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '}',
    s('legend-item') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: center;',
    '  gap: 5px;',
    '  min-width: 0;',
    '  list-style: none;',
    '  overflow-wrap: anywhere;',
    '}',
    s('axline') + ' {',
    '  display: block;',
    '  flex: 0 0 auto;',
    '  width: 20px;',
    '  border-top: 2px solid ' + skinVar('accent') + ';',
    '}',
    s('axline') + '.is-past {',
    '  border-top: 1px dashed ' + skinVar('ink-2') + ';',
    '}',
    s('swatch') + ' {',
    '  display: block;',
    '  flex: 0 0 auto;',
    '  width: 12px;',
    '  height: 12px;',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '}',
    s('swatch') + '.is-ok {',
    '  background: ' + wash('ok', 30) + ';',
    '  border: 1px solid ' + skinVar('ok') + ';',
    '}',
    s('swatch') + '.is-warn {',
    '  background: ' + wash('warn', 24) + ';',
    '  border: 1px dashed ' + skinVar('warn') + ';',
    '}',
    s('goal-num') + ' {',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-weight: 700;',
    '  font-variant-numeric: tabular-nums;',
    '}',
    /* 未达标逐根点名：一行一根，差的分数写右边（`warn` 是语义档的字色，过文本地板）。 */
    s('gaps') + ' {',
    '  list-style: none;',
    '  display: flex;',
    '  flex-direction: column;',
    '  gap: 0;',
    '  margin: 0;',
    '  padding: 8px 0 0;',
    '  border-top: 1px solid ' + skinVar('line') + ';',
    '  min-width: 0;',
    '}',
    s('gap') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 2px 10px;',
    '  min-height: 32px;',
    '  padding: 5px 0;',
    '  min-width: 0;',
    '  list-style: none;',
    '}',
    s('gap') + ' + ' + c('gap') + ' {',
    '  border-top: 1px solid ' + skinVar('line') + ';',
    '}',
    s('gap-name') + ' {',
    '  min-width: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 600;',
    '  overflow-wrap: anywhere;',
    '}',
    s('gap-num') + ' {',
    '  min-width: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 700;',
    '  font-variant-numeric: tabular-nums;',
    '  white-space: nowrap;',
    '}',
    s('gap-diff') + ' {',
    '  min-width: 0;',
    '  margin-left: auto;',
    '  color: ' + skinVar('warn') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 700;',
    '  font-variant-numeric: tabular-nums;',
    '  white-space: nowrap;',
    '}',
    s('note') + ' {',
    '  margin: 0;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
  ].join(LF);
}
