/** style 区 · helpShell
 *
 *  自 `src/style.ts` 的 `SECTION_BUILDERS[helpShell]` **连它上面那段注释一起**原样切出。
 *
 *  **住址**：目录化批次⑥把 `src/style.ts` 切成「一份令牌 ＋ 一个区一件 ＋ 一个组装器」，
 *  正文原样搬来；搬迁判据＝产物逐字节相同（`buildStyleSheet()` 的 css 全文 ＋ 出口名单），
 *  见 `docs/base/base-render/组件目录架构.md`。
 */

import { LF, focusRing } from './parts.js';
import { BODY_FONT_STACK } from '../../font.js';
import { ACTION_BAR_DEFAULTS } from '../../spec/index.js';

/** helpShell —— 类名产出者 `src/help.ts:380-599`（`cls()` ＝ `ilife-help-shell-<suffix>`）
 *  ＋ `src/controls.ts` 的 `buildSharedHelpersJs`（#88 S4 运行时注入：卡级复制按钮／搜索／高亮／
 *  回到顶部——后缀同一命名空间，T11 按既有 `cls()` 实参前缀归属）。 */

export const helpShellSection: (prefix: string) => string = (p) => [
  '.' + p + 'help-shell {',
  '  display: block;',
  '  max-width: 960px;',
  '  margin: 0 auto;',
  '  padding: 32px 20px 80px;',
  '  color: var(--fg);',
  // H-06 正文栈（唯一真相源 `src/font.ts` 的 BODY_FONT_STACK，首位 "SF Pro Display"；不新增 token 名，等宽栈不动）。
  '  font-family: ' + BODY_FONT_STACK + ';',
  '  font-feature-settings: "tnum";',
  '}',
  '.' + p + 'help-shell-hero {',
  '  margin-bottom: 20px;',
  '}',
  '.' + p + 'help-shell-eyebrow {',
  '  margin: 0;',
  '  color: var(--blue);',
  '  font-size: 12px;',
  '  font-weight: 600;',
  '  letter-spacing: .08em;',
  '  text-transform: uppercase;',
  '}',
  '.' + p + 'help-shell-title {',
  '  margin: 6px 0 0;',
  '  font-size: 32px;',
  '  font-weight: 700;',
  '  letter-spacing: -.4px;',
  '  line-height: 1.2;',
  '}',
  '.' + p + 'help-shell-subtitle {',
  '  margin: 6px 0 0;',
  '  color: var(--fg2);',
  '  font-size: 15px;',
  '}',
  '.' + p + 'help-shell-lead {',
  '  margin: 4px 0 0;',
  '  color: var(--fg3);',
  '  font-size: 13px;',
  '}',
  '.' + p + 'help-shell-init {',
  '  padding: 16px;',
  '  border: 1px solid var(--line);',
  '  border-radius: 20px;',
  '  background: var(--card);',
  '}',
  '.' + p + 'help-shell-init-title {',
  '  margin: 0;',
  '  font-size: 17px;',
  '  font-weight: 600;',
  '}',
  '.' + p + 'help-shell-init-subtitle {',
  '  margin: 4px 0 0;',
  '  color: var(--fg2);',
  '  font-size: 13px;',
  '}',
  '.' + p + 'help-shell-init-prompt {',
  '  margin: 8px 0 0;',
  '  padding: 12px;',
  '  border-radius: 8px;',
  '  background: var(--soft);',
  '  color: var(--fg2);',
  '  font-family: "SF Mono", monospace;',
  '  font-size: 12px;',
  '  line-height: 1.55;',
  '  white-space: pre-wrap;',
  '  overflow-x: auto;',
  '}',
  '.' + p + 'help-shell-init-steps {',
  '  margin: 8px 0 0;',
  '  padding-left: 20px;',
  '  color: var(--fg2);',
  '  font-size: 13px;',
  '}',
  '.' + p + 'help-shell-init-step {',
  '  margin: 2px 0;',
  '}',
  '.' + p + 'help-shell-tab-bar {',
  '  display: flex;',
  '  flex-wrap: wrap;',
  '  gap: 8px;',
  '  margin: 16px 0;',
  '}',
  '.' + p + 'help-shell-tab {',
  '  display: inline-flex;',
  '  align-items: center;',
  '  gap: 6px;',
  '  padding: 6px 14px;',
  '  border: 1px solid var(--line);',
  '  border-radius: 999px;',
  '  background: var(--card);',
  '  color: var(--fg2);',
  '  font-size: 13px;',
  '  font-weight: 600;',
  '  cursor: pointer;',
  '  touch-action: manipulation;',
  '}',
  '.' + p + 'help-shell-tab-icon {',
  '  font-size: 14px;',
  '}',
  '.' + p + 'help-shell-tab-input {',
  '  position: absolute;',
  '  width: 1px;',
  '  height: 1px;',
  '  margin: -1px;',
  '  padding: 0;',
  '  border: 0;',
  '  overflow: hidden;',
  '  clip: rect(0 0 0 0);',
  '  white-space: nowrap;',
  '}',
  '.' + p + 'help-shell-pages {',
  '  display: block;',
  '}',
  '.' + p + 'help-shell-page {',
  '  display: block;',
  '}',
  '.' + p + 'help-shell-page-body {',
  '  display: none;',
  '}',
  '.' + p + 'help-shell-tab-input:checked + .' + p + 'help-shell-page-body {',
  '  display: block;',
  '}',
  '.' + p + 'help-shell-grid {',
  '  display: grid;',
  '  grid-template-columns: repeat(2, minmax(0, 1fr));',
  '  gap: 12px;',
  '}',
  '.' + p + 'help-shell-card {',
  '  display: block;',
  '  padding: 14px;',
  '  border: 1px solid var(--line);',
  '  border-radius: 14px;',
  '  background: var(--card);',
  '  box-shadow: var(--shadow);',
  '}',
  '.' + p + 'help-shell-card-top {',
  '  display: flex;',
  '  flex-wrap: wrap;',
  '  align-items: center;',
  '  gap: 8px;',
  '}',
  '.' + p + 'help-shell-card-title {',
  '  margin: 8px 0 0;',
  '  font-size: 17px;',
  '  font-weight: 600;',
  '}',
  '.' + p + 'help-shell-chip {',
  '  display: inline-flex;',
  '  align-items: center;',
  '  padding: 1px 8px;',
  '  border-radius: 999px;',
  '  background: var(--soft);',
  '  color: var(--blue2);',
  '  font-size: 11px;',
  '  font-weight: 600;',
  '}',
  '.' + p + 'help-shell-badge {',
  '  display: inline-flex;',
  '  align-items: center;',
  '  padding: 1px 8px;',
  '  border-radius: 999px;',
  '  background: var(--soft);',
  '  color: var(--fg2);',
  '  font-size: 11px;',
  '  font-weight: 600;',
  '}',
  '.' + p + 'help-shell-badge-dev {',
  '  background: rgba(255, 149, 0, .12);',
  '  color: #b25000;',
  '}',
  '.' + p + 'help-shell-cli {',
  '  display: block;',
  '  margin-top: 6px;',
  '  color: var(--fg3);',
  '  font-family: "SF Mono", monospace;',
  '  font-size: 11.5px;',
  '}',
  '.' + p + 'help-shell-fields {',
  '  margin: 8px 0 0;',
  '  padding: 0;',
  '  list-style: none;',
  '}',
  '.' + p + 'help-shell-field {',
  '  display: flex;',
  '  flex-wrap: wrap;',
  '  gap: 6px;',
  '  padding: 6px 0;',
  '  border-top: 1px solid var(--line);',
  '  font-size: 13px;',
  '}',
  '.' + p + 'help-shell-field:first-child {',
  '  border-top: 0;',
  '}',
  '.' + p + 'help-shell-field-label {',
  '  color: var(--fg2);',
  '}',
  '.' + p + 'help-shell-field-value {',
  '  color: var(--fg);',
  '  font-weight: 600;',
  '}',
  '.' + p + 'help-shell-field-hint {',
  '  color: var(--fg3);',
  '}',
  '.' + p + 'help-shell-field-required {',
  '  color: #c0392b;',
  '  font-weight: 600;',
  '}',
  '.' + p + 'help-shell-sheet {',
  '  margin-top: 10px;',
  '  border-top: 1px solid var(--line);',
  '}',
  '.' + p + 'help-shell-sheet-summary {',
  '  padding: 8px 0;',
  '  color: var(--blue);',
  '  font-size: 13px;',
  '  font-weight: 600;',
  '  cursor: pointer;',
  '  touch-action: manipulation;',
  '  list-style: none;',
  '}',
  '.' + p + 'help-shell-sheet-summary::-webkit-details-marker {',
  '  display: none;',
  '}',
  '.' + p + 'help-shell-sheet-summary::after {',
  '  content: "▾";',
  '  display: inline-block;',
  '  margin-left: 6px;',
  '  transition: transform .15s ease;',
  '}',
  '.' + p + 'help-shell-sheet[open] > .' + p + 'help-shell-sheet-summary::after {',
  '  transform: rotate(180deg);',
  '}',
  '.' + p + 'help-shell-sheet-body {',
  '  padding-bottom: 4px;',
  '}',
  '.' + p + 'help-shell-prompt {',
  '  margin: 0;',
  '  padding: 12px;',
  '  border-radius: 8px;',
  '  background: var(--soft);',
  '  color: var(--fg2);',
  '  font-family: "SF Mono", monospace;',
  '  font-size: 12px;',
  '  line-height: 1.55;',
  '  white-space: pre-wrap;',
  '  overflow-x: auto;',
  '}',
  '.' + p + 'help-shell-actions {',
  '  display: flex;',
  '  flex-wrap: wrap;',
  '  gap: 8px;',
  '  margin-top: 10px;',
  '}',
  '.' + p + 'help-shell-btn {',
  '  display: inline-flex;',
  '  align-items: center;',
  '  justify-content: center;',
  '  min-height: ' + ACTION_BAR_DEFAULTS.minHeightPx + 'px;',
  '  padding: 0 14px;',
  '  border: 1px solid transparent;',
  '  border-radius: 999px;',
  '  background: var(--blue);',
  '  color: var(--card);',
  '  font-family: inherit;',
  '  font-size: ' + ACTION_BAR_DEFAULTS.fontSizePx + 'px;',
  '  font-weight: ' + ACTION_BAR_DEFAULTS.fontWeight + ';',
  '  line-height: 1;',
  // #121：H-16「跑 450ms 弹簧动画」——弹簧口径**逐字复用** `copyButton` 基础（B1
  // `benchmark-visual-spec.md:279,645`：`transform .45s cubic-bezier(.34,1.56,.64,1)`），
  // 不新增机制、不新增关键帧；按下态同 `.ilife-copy-btn:active`（scale .96）。
  '  transition: transform .45s cubic-bezier(.34, 1.56, .64, 1), background-color .2s ease;',
  '  cursor: pointer;',
  '  -webkit-tap-highlight-color: transparent;',
  '  touch-action: manipulation;',
  '}',
  '.' + p + 'help-shell-btn:active {',
  '  transform: scale(.96);',
  '}',
  '.' + p + 'help-shell-btn-prompt,',
  '.' + p + 'help-shell-btn-wakeWord,',
  '.' + p + 'help-shell-btn-params {',
  '  background: var(--blue);',
  '  color: var(--card);',
  '}',
  // #121（H-16 双反馈的 CSS 侧补面）：HELP 速查台的复制按钮是 helpShell 命名空间（静态三目标
  // `.ilife-help-shell-btn-*` ＋ 运行时注入的 `.ilife-help-shell-card-copy`），**不含** `.ilife-copy-btn`
  // → #75 的 `.ilife-copy-btn.copied` 命中不到。此处按同一成功色 token `--ok` 补 `copied` 态，
  // 类名逐字 `copied`（运行时加，非 `ilife-` 前缀 → 不占样式区命名空间）。
  '.' + p + 'help-shell-btn.copied,',
  '.' + p + 'help-shell-card-copy.copied {',
  '  border-color: var(--ok);',
  '  background: var(--ok);',
  '  color: var(--card);',
  '}',
  focusRing('.' + p + 'help-shell-btn'),
  '.' + p + 'help-shell-subgroup {',
  '  margin-top: 12px;',
  '  border: 1px solid var(--line);',
  '  border-radius: 14px;',
  '  background: var(--card);',
  '}',
  '.' + p + 'help-shell-subgroup-summary {',
  '  display: flex;',
  '  align-items: center;',
  '  gap: 8px;',
  '  padding: 10px 14px;',
  '  font-size: 14px;',
  '  font-weight: 600;',
  '  cursor: pointer;',
  '  touch-action: manipulation;',
  '}',
  '.' + p + 'help-shell-count {',
  '  color: var(--fg3);',
  '  font-size: 12px;',
  '  font-weight: 600;',
  '}',
  '.' + p + 'help-shell-subgroup-body {',
  '  padding: 0 14px 14px;',
  '}',
  '.' + p + 'help-shell-about-sec {',
  '  margin-top: 20px;',
  '}',
  '.' + p + 'help-shell-about-head {',
  '  margin: 0 0 8px;',
  '  font-size: 17px;',
  '  font-weight: 600;',
  '}',
  '.' + p + 'help-shell-about-list {',
  '  margin: 0;',
  '  padding: 0;',
  '  list-style: none;',
  '}',
  '.' + p + 'help-shell-about-row {',
  '  display: flex;',
  '  flex-wrap: wrap;',
  '  gap: 8px;',
  '  padding: 8px 0;',
  '  border-top: 1px solid var(--line);',
  '  font-size: 13px;',
  '}',
  '.' + p + 'help-shell-about-row:first-child {',
  '  border-top: 0;',
  '}',
  '.' + p + 'help-shell-about-label {',
  '  color: var(--fg2);',
  '}',
  '.' + p + 'help-shell-about-value {',
  '  color: var(--fg);',
  '  font-weight: 600;',
  '}',
  '.' + p + 'help-shell-about-note {',
  '  margin: 8px 0 0;',
  '  color: var(--fg3);',
  '  font-size: 13px;',
  '}',
  '.' + p + 'help-shell-meta {',
  '  margin-top: 20px;',
  '}',
  '.' + p + 'help-shell-meta-block {',
  '  margin-top: 16px;',
  '}',
  '.' + p + 'help-shell-meta-title {',
  '  margin: 0 0 8px;',
  '  font-size: 17px;',
  '  font-weight: 600;',
  '}',
  '.' + p + 'help-shell-meta-html {',
  '  color: var(--fg2);',
  '  font-size: 13px;',
  '}',
  // ── #88 S4：helpers 运行时注入面（`src/controls.ts` 的 `buildSharedHelpersJs`）──────────
  // 类名后缀与 `src/help.ts` 的 `cls()` 同一命名空间（T11 归属由既有实参前缀承担）；
  // 只用 11 个冻结 token，不新增 token、不越区、不走技能侧 `extraCss`。
  '.' + p + 'help-shell-tab-search {',
  '  display: flex;',
  '  flex-wrap: wrap;',
  '  align-items: center;',
  '  gap: 8px;',
  '  margin: 0 0 16px;',
  '}',
  '.' + p + 'help-shell-tab-search-input {',
  '  flex: 1 1 200px;',
  '  min-width: 0;',
  '  min-height: 36px;',
  '  padding: 0 14px;',
  '  border: 1px solid var(--line);',
  '  border-radius: 999px;',
  '  background: var(--card);',
  '  color: var(--fg);',
  '  font-family: inherit;',
  '  font-size: 13px;',
  '}',
  focusRing('.' + p + 'help-shell-tab-search-input'),
  '.' + p + 'help-shell-tab-search-clear {',
  '  display: inline-flex;',
  '  align-items: center;',
  '  justify-content: center;',
  '  width: 28px;',
  '  height: 28px;',
  '  padding: 0;',
  '  border: 1px solid var(--line);',
  '  border-radius: 50%;',
  '  background: var(--card);',
  '  color: var(--fg2);',
  '  font-family: inherit;',
  '  font-size: 12px;',
  '  line-height: 1;',
  '  cursor: pointer;',
  '  touch-action: manipulation;',
  '}',
  focusRing('.' + p + 'help-shell-tab-search-clear'),
  '.' + p + 'help-shell-page-hitcount {',
  '  color: var(--fg2);',
  '  font-size: 13px;',
  '  font-weight: 600;',
  '}',
  '.' + p + 'help-shell-card-copy {',
  '  display: inline-flex;',
  '  align-items: center;',
  '  justify-content: center;',
  '  margin-left: auto;',
  '  min-height: 28px;',
  '  padding: 0 12px;',
  '  border: 1px solid var(--line);',
  '  border-radius: 999px;',
  '  background: var(--card);',
  '  color: var(--blue);',
  '  font-family: inherit;',
  '  font-size: 12px;',
  '  font-weight: 600;',
  '  line-height: 1;',
  // #121：弹簧口径同 `copyButton` 基础（H-16「450ms 弹簧」），成功态 `.copied` 见上方 helpShell 区。
  '  transition: transform .45s cubic-bezier(.34, 1.56, .64, 1), background-color .2s ease;',
  '  cursor: pointer;',
  '  -webkit-tap-highlight-color: transparent;',
  '  touch-action: manipulation;',
  '}',
  '.' + p + 'help-shell-card-copy:active {',
  '  transform: scale(.96);',
  '}',
  focusRing('.' + p + 'help-shell-card-copy'),
  '.' + p + 'help-shell-card-mark {',
  '  padding: 0 2px;',
  // H-10：`4px` ∉ {8,14,20,999px,50%} → 取集合内最近的 `8px`（D-5：CSS 常量直写，不新增 token 名）。
  '  border-radius: 8px;',
  '  background: var(--soft);',
  '  color: var(--blue2);',
  '  font-weight: 600;',
  '}',
  // 搜索态：未命中卡片／子功能组整块隐藏（`hidden` 属性会被本区 `display:block` 覆盖，
  // 故用类名而非属性；类名同样由 helpers 以 `className` 字符串增删，不依赖 `classList`）。
  '.' + p + 'help-shell-card-hidden {',
  '  display: none;',
  '}',
  '.' + p + 'help-shell-subgroup-hidden {',
  '  display: none;',
  '}',
  '.' + p + 'help-shell-field-input {',
  '  flex: 1 1 120px;',
  '  min-width: 0;',
  '  min-height: 32px;',
  '  padding: 0 10px;',
  '  border: 1px solid var(--line);',
  '  border-radius: 8px;',
  '  background: var(--card);',
  '  color: var(--fg);',
  '  font-family: inherit;',
  '  font-size: 13px;',
  '}',
  focusRing('.' + p + 'help-shell-field-input'),
  // 回到顶部（视觉尺 H-19：42px 圆形、fixed bottom/right 24px、初始 opacity:0 ＋
  // pointer-events:none，scrollY>400 加 `-show`；点击平滑回顶由 helpers 承担）。
  '.' + p + 'help-shell-btn-backtop {',
  '  position: fixed;',
  '  right: 24px;',
  '  bottom: 24px;',
  '  display: inline-flex;',
  '  align-items: center;',
  '  justify-content: center;',
  '  width: 42px;',
  '  height: 42px;',
  '  padding: 0;',
  '  border: 1px solid var(--line);',
  '  border-radius: 50%;',
  '  background: var(--card);',
  '  color: var(--fg);',
  '  font-family: inherit;',
  '  font-size: 18px;',
  '  font-weight: 600;',
  '  line-height: 1;',
  '  box-shadow: var(--shadow);',
  '  opacity: 0;',
  '  pointer-events: none;',
  '  transition: opacity .2s ease;',
  '  z-index: 9998;',
  '  cursor: pointer;',
  '  touch-action: manipulation;',
  '}',
  '.' + p + 'help-shell-btn-backtop-show {',
  '  opacity: 1;',
  '  pointer-events: auto;',
  '}',
  focusRing('.' + p + 'help-shell-btn-backtop'),
  '@media (max-width: 640px) {',
  '  .' + p + 'help-shell {',
  '    padding: 20px 16px 60px;',
  '  }',
  '  .' + p + 'help-shell-title {',
  '    font-size: 26px;',
  '  }',
  '  .' + p + 'help-shell-grid {',
  '    grid-template-columns: minmax(0, 1fr);',
  '  }',
  '}',
  '@media (max-width: 400px) {',
  '  .' + p + 'help-shell-tab-bar {',
  '    gap: 6px;',
  '  }',
  '}',
  '@media (prefers-reduced-motion: reduce) {',
  '  .' + p + 'copy-btn {',
  '    transition: none;',
  '  }',
  '  .' + p + 'copy-btn:active {',
  '    transform: none;',
  '  }',
  // W4：入场动效在 reduced-motion 下**归零**（含动画本身，不只是时长）。
  '  .' + p + 'toast {',
  '    animation: none;',
  '  }',
  // #88 S4：回到顶部按钮的透明度过渡同样归零（H-20 覆盖全部可交互控件）。
  '  .' + p + 'help-shell-btn-backtop {',
  '    transition: none;',
  '  }',
  // #121：helpShell 复制按钮新增的弹簧过渡同样归零（口径同上一行）。
  '  .' + p + 'help-shell-btn,',
  '  .' + p + 'help-shell-card-copy {',
  '    transition: none;',
  '  }',
  '  .' + p + 'help-shell-btn:active,',
  '  .' + p + 'help-shell-card-copy:active {',
  '    transform: none;',
  '  }',
  '}',
].join(LF)
