/** 票据纸族样式（**#1124 从 skill 侧 docPage.ts 上移**；按 #1082 §23 归属到 base 组件）。
 *
 *  本件是**搬家件**：逐条规则按它的选择器主人归属（见每条前的 `owner:` 注），但**拼接顺序保持搬家前逐字不变**
 *  （`assembleSheetPage` 的注释写明：族样式与皮肤在前、本页家具在后——家具那几条是页面级几何覆盖，靠「后出现」取胜）。
 *  所以：`ticketFamilyCss()` 的返回值与搬家前 `docPage.ts` 的 `TICKET_CSS` **逐字节相同**；
 *  `ticketFurnitureCss()` 与 `TICKET_FURNITURE_CSS` **逐字节相同**。
 *
 *  归属（§23 的 12 目录清单里与本段相关的 8 个）：
 *    sheet-frame（页与纸的几何／窄档）／summary-head（主数字块）／ledger-rows（账目行）／
 *    entry-card（明细卡与行）／copy-button（复制区两枚钮）／ticket-button（主按钮那一族）／
 *    ticket-section（段标题）／check-row（对账卡）／sheet-head（店头内距）／punch-strip（页尾锯齿，随 sheet-frame）。
 */

/** 换行（仓库口径：不写字面换行转义）。 */
const LF = String.fromCharCode(10);

/** 票据纸族样式段·**core**（＝搬家前 docPage.ts 的 `TICKET_CSS` 里非页面族那部分；#1124 第三步拆块）。 */
const TICKET_CSS_CORE = [
  '/* #993 桌：暖奶油底＋居中一列（原型 `body` 那一层；底色的两处浅深用 token 混出，不抄字面色）。 */',
  '.ilife-bill-sheet-page {',
  '  box-sizing: border-box;',
  '  width: 100%;',
  '  min-height: 100vh;',
  '  padding: 28px 14px 48px;',
  '  display: flex;',
  '  flex-direction: column;',
  '  align-items: center;',
  '  background: radial-gradient(1200px 600px at 50% -10%,',
  '    color-mix(in srgb, var(--ilife-surface) 70%, var(--ilife-ground)) 0%,',
  '    var(--ilife-ground) 55%,',
  '    color-mix(in srgb, var(--ilife-ground) 96%, var(--ilife-accent)) 100%);',
  '  color: var(--ilife-ink);',
  '  font-family: var(--ilife-font);',
  '  line-height: normal;',
  '  -webkit-font-smoothing: antialiased;',
  '}',
  '/* 纸宽（原型 `.page` 的 440px 版心；桌的内距由上面那条给）。 */',
  '.ilife-bill-sheet-page > section { width: 100%; max-width: 440px; }',
  '/* 原型 `*{box-sizing:border-box}` 的作用域版：只在本族根类之下（其余 29 页零命中）。 */',
  '.ilife-bill-sheet-page *,',
  '.ilife-bill-sheet-page *::before,',
  '.ilife-bill-sheet-page *::after { box-sizing: border-box; }',
  '/* 店头（原型 `.shop-head`）：品牌行＋结论标题，居中；改动值那一段走危险档（原型 `.hl`）。 */',
  '.ilife-sheet-head { text-align: center; padding: 2px 0 0; }',
  '.ilife-sheet-eyebrow { margin: 0; font-size: 11.5px; letter-spacing: 2px; color: var(--ilife-ink-2); font-weight: 700; }',
  '.ilife-sheet-title { margin: 8px 0 0; font-size: 19px; line-height: 1.4; letter-spacing: .2px; font-weight: 800; color: var(--ilife-ink); }',
  '.ilife-sheet-title .hl { color: var(--ilife-danger); }',
  '/* 店头副题（原型 `.shop-sub`）：只查询域详情页出（`sheetHead` 第三参），回执两页零命中。 */',
  '.ilife-sheet-sub { margin: 8px 0 0; font-size: 12.5px; line-height: 1.6; color: var(--ilife-ink-2); text-align: center; }',
  '/* 虚线分隔（原型 `hr.dashed`）：2px 虚线、左右各探出 8px。 */',
  '.ilife-ticket-rule { border: 0; border-top: 2px dashed var(--ilife-line); margin: 14px -8px; }',
  '/* 段（原型 `.sec`）＋ 段标题（4px 主色条 ＋ 右对齐英文标）。 */',
  '.ilife-ticket-sec { padding: 2px 0 6px; }',
  '.ilife-ticket-sec-heading { display: flex; align-items: center; gap: 8px; margin: 4px 0 10px; font-size: 13px; font-weight: 800; letter-spacing: 1.5px; color: var(--ilife-ink-2); }',
  '.ilife-ticket-sec-heading::before { content: ""; width: 4px; height: 14px; border-radius: 4px; background: var(--ilife-accent); }',
  '.ilife-ticket-sec-no { margin-left: auto; font-weight: 700; color: var(--ilife-ink-3); letter-spacing: 0; }',
  '/* 危险档段标题（原型 `.sec-heading.danger`）：只换主色条那一枚色。 */',
  '.ilife-ticket-sec-heading.is-danger::before { background: var(--ilife-danger); }',
  '/* 主数字块（原型 `.summary-head`）：整块居中，下留 16px；印章钉右上角并微斜（公共层票据纸版式给形，',
  '   这里补齐原型的三处几何：内距 6px、脚行不占位（印章是绝对定位的，脚行只剩一枚空槽）、',
  '   下面那两行小字居中）。 */',
  '.ilife-ticket-summary { padding: 0 0 16px; text-align: center; }',
  '.ilife-ticket-summary .ilife-block-summary-head.is-ticket { padding: 6px 0 0; }',
  '/* 脚行距：公共层列向 flex 的 4px gap 之外补 9px ⇒ 与原型 note 距主数字 10px 同距（实测三档视口一致）。 */',
  /* #1133：那 9px 是**说明句**距主数字的那段白（与原型 note 的 10px 同距）——只给「脚行里有说明句」的行。
     脚行里只有印章时（印章是绝对定位的）不留这段白：`:not(.has-note)` 显式压 0，压过公共层那条 10px。
     判别子由 summary-head 渲染器挂（`has-note`），页面件一字不动。 */
  '.ilife-ticket-summary .ilife-block-summary-head.is-ticket .ilife-block-summary-head-foot.has-note { margin-top: 9px; }',
  '.ilife-ticket-summary .ilife-block-summary-head.is-ticket .ilife-block-summary-head-foot:not(.has-note) { margin-top: 0; }',
  '/* 没有脚行小字时，那一枚空槽不占版面（印章是绝对定位的，仍钉在右上角）。 */',
  '.ilife-ticket-summary .ilife-block-summary-head.is-ticket .ilife-block-summary-head-foot > span:empty { display: none; }',
  '.ilife-ticket-summary .ilife-block-summary-head.is-ticket .ilife-block-summary-head-stamp { font-weight: 900; opacity: .92; }',
  '/* 眉标药丸：字距照原型 2px（公共层票据纸版式取的是 .12em，12px 下 1.44px）。 */',
  '.ilife-ticket-summary .ilife-block-summary-head.is-ticket .ilife-block-summary-head-eyebrow { letter-spacing: 2px; }',
  '.ilife-ticket-summary-note { margin: 10px 0 0; font-size: 13.5px; line-height: 1.6; color: var(--ilife-ink-2); }',
  '.ilife-ticket-summary-note b { color: var(--ilife-ink); }',
  '/* 时刻行在原型里是 `.summary-head` 的最后一个子块（6px 距）；本仓把它放在头块之外，故补足同一距离。 */',
  '.ilife-ticket-summary-time { margin: 10px 0 0; font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 13.5px; color: var(--ilife-ink-2); }',
  '/* 账目行：详情页那几行照原型抬到 44px 触摸档（回执页 4 行是 9px 行距、不抬）；',
  '   两页的值列行高在原型里也不同：详情 1.55（可折行）、回执 1.4（单行紧排）。 */',
  '.ilife-ticket-detail .ilife-block-ledger-rows.is-ticket .ilife-block-ledger-row, .ilife-ticket-receipt .ilife-block-ledger-rows.is-ticket .ilife-block-ledger-row { min-height: 44px; }',
  '.ilife-ticket-receipt .ilife-block-ledger-rows.is-ticket .ilife-block-ledger-row-value { line-height: 1.4; font-variant-numeric: normal; }',
  '/* 回执行间那条**看不见的** 1px 上边线：原型写的就是 `1px dotted transparent`（不画线，只占 1px 行高），',
  '   不补它整块矮 3px、下面的段落跟着上移。 */',
  '.ilife-ticket-receipt .ilife-block-ledger-rows.is-ticket .ilife-block-ledger-row + .ilife-block-ledger-row { border-top: 1px dotted transparent; }',
  '/* 落点状态行（w17 v2.1）：原型即纯文本、无胶囊，详情页不再发出 `.is-status` 行，',
  '   下面两条状态胶囊样式随之删除（回执两页从未用过，删后零命中、不留死代码）。 */',
  '/* 对账卡（w17 v2.1 CHECK 行）：浅绿卡＋圆点＋一行字；已撤销走危险档。只详情页发出。 */',
  '.ilife-ticket-check { display: flex; align-items: flex-start; gap: 8px; margin-top: 10px; padding: 10px 12px; border: 1px solid #cfe6d6; border-radius: var(--ilife-radius-sm); background: #f4fbf6; color: #3e5a4a; font-size: 12.8px; line-height: 1.6; overflow-wrap: anywhere; }',
  '.ilife-ticket-check-dot { flex: none; width: 8px; height: 8px; margin-top: 6px; border-radius: 999px; background: #2f9e5f; }',
  '.ilife-ticket-check.is-danger { border-color: #ecc9c2; background: var(--ilife-danger-soft); color: #6d2118; }',
  '.ilife-ticket-check.is-danger .ilife-ticket-check-dot { background: var(--ilife-danger); }',
  '/* 纸外脚注（w17 v2.1 foot-note）：纸外、页内居中一行小字；只详情页发出。 */',
  /* #1132：按判地 `.foot-note` 对齐（11.5px／行高 1.7／字距 .4／内距 10 0 2／无上距）——族级取值，全票据页共用。 */
  '.ilife-bill-sheet-page .ilife-ticket-foot { margin: 0; padding: 10px 0 2px; font-size: 11.5px; line-height: 1.7; letter-spacing: .4px; color: var(--ilife-ink-3); text-align: center; }',
  '/* 明细卡（原型 `.entry-card`／`.entry-rows`）：米黄卡 ＋ 编号胶囊 ＋ 实付行高亮。 */',
  '.ilife-ticket-card { background: var(--ilife-surface-2); border: 1px solid var(--ilife-line); border-radius: var(--ilife-radius-card, var(--ilife-radius-sm)); padding: 12px 13px 11px; }',
  '.ilife-ticket-entries { list-style: none; margin: 0; padding: 0; counter-reset: ilife-ticket-row; }',
  '.ilife-ticket-entries > li { display: flex; gap: 12px; align-items: flex-start; padding: 10px 0; border-bottom: 1px dotted var(--ilife-line); font-size: 14px; min-height: 44px; line-height: 1.55; }',
  '.ilife-ticket-entries > li:last-child { border-bottom: 0; }',
  '.ilife-ticket-entries > li::before { counter-increment: ilife-ticket-row; content: counter(ilife-ticket-row); flex: 0 0 22px; height: 22px; margin-top: 1px; border: 1px solid var(--ilife-line); border-radius: var(--ilife-radius-tag, var(--ilife-radius-sm)); background: var(--ilife-surface-2); color: var(--ilife-ink-3); font-size: 12px; font-weight: 700; display: inline-flex; align-items: center; justify-content: center; }',
  // #1126：明细行文本不收缩＝flex 子项 min-width:auto 的自动最小尺寸在撑，长「备注 · …」被右缘裁掉。
  // 照判地原型同位置那份写法定死（`proto/query/w03-查某天-v2.1.html` 的 `.entry-text{flex:1 1 auto;min-width:0;overflow-wrap:anywhere}`）：
  // 补 `min-width: 0`（告警线口径：一处规则一处改，别自创别的招）。
  '.ilife-ticket-entry-text { flex: 1 1 auto; min-width: 0; overflow-wrap: anywhere; word-break: break-all; }',
  '.ilife-ticket-entries > li.is-pay { margin: 8px 0; padding: 10px 12px; border: 1px solid var(--ilife-line); border-radius: var(--ilife-radius-sm); background: var(--ilife-surface); }',
  '.ilife-ticket-entries > li.is-pay .ilife-ticket-entry-text { font-size: 15px; font-weight: 800; }',
  '.ilife-ticket-entries > li.is-pay::before { background: var(--ilife-ink); border-color: var(--ilife-ink); color: var(--ilife-surface); }',
  '/* 次按钮那一族是公共层复制区的产物（`.ilife-copy-btn`），这里按原型 `.btn-secondary` 改形状：',
  '   整行宽、13px 圆角、白底暖边。高度钉 47px＝原型那一颗的**实测盒高**（它的标签里带着一个 `▾` 字符，',
  '   那一枚字形把行盒抬到 23px ⇒ 12+23+12）；本仓的三角由 CSS 画、行盒只有 21px ⇒ 不钉就矮 2px，',
  '   连带下面的裁切线与页脚各上移 2px。只在本族根类之下生效。 */',
  '.ilife-ticket-actions { padding: 14px 0 4px; }',
  '/* 复制区宽度：票据纸的复制钮一律收 340 居中（原型 overlay 的同一取值）。**一处定义**：' + 
  '   setup 与 query 两域的票据纸都读这条，页面侧不再各写一条。 */',
  '.ilife-bill-sheet-page .ilife-ticket-actions { max-width: 340px; margin-inline: auto; }',
  '/* 退出口那一行口径（原型 `.caliber`：12px、行高 1.7、居中、左右各 2px）。 */',
  '.ilife-ticket-actions .ilife-block-caliber { margin: 10px 2px 0; line-height: 1.7; text-align: center; color: var(--ilife-ink-2); }',
  '.ilife-ticket-btn { display: flex; align-items: center; justify-content: center; width: 100%; min-height: 48px; padding: 12px 14px; border: 0; border-radius: var(--ilife-radius-sm); font-family: inherit; font-size: 16px; font-weight: 800; letter-spacing: .5px; line-height: normal; cursor: pointer; -webkit-tap-highlight-color: transparent; touch-action: manipulation; }',
  '.ilife-ticket-btn.is-primary { background: linear-gradient(180deg, color-mix(in srgb, var(--ilife-danger) 82%, var(--ilife-surface)) 0%, var(--ilife-danger) 100%); color: var(--ilife-surface); box-shadow: 0 8px 20px color-mix(in srgb, var(--ilife-danger) 28%, transparent), inset 0 1px 0 color-mix(in srgb, var(--ilife-surface) 25%, transparent); }',
  '.ilife-bill-sheet-page .ilife-block-copy-block { margin: 0; }',
  '.ilife-bill-sheet-page .ilife-action-bar { margin: 0; max-width: none; gap: 0; }',
  '.ilife-bill-sheet-page .ilife-action-row-ghost { display: flex; flex-direction: column; gap: 0; }',
  '.ilife-bill-sheet-page .ilife-copy-menu-wrap { width: 100%; margin-top: 10px; }',
  '.ilife-bill-sheet-page .ilife-copy-menu-wrap + .ilife-copy-btn { margin-top: 10px; }',
  '.ilife-bill-sheet-page .ilife-copy-btn { width: 100%; min-height: 44px; padding: 12px 14px; border: 1.5px solid #ddd0b6; border-radius: var(--ilife-radius-sm); background: #fff; color: #4a4236; font-size: 14.5px; font-weight: 800; letter-spacing: .5px; line-height: normal; }',
  '.ilife-bill-sheet-page .ilife-copy-btn.copied { border-color: var(--ilife-ok); background: var(--ilife-ok); color: var(--ilife-surface); }',
  '.ilife-bill-sheet-page .ilife-copy-menu { left: 0; right: 0; min-width: 0; max-width: none; padding: 6px; border: 1.5px solid #ddd0b6; border-radius: var(--ilife-radius-sm); background: #fff; box-shadow: var(--ilife-shadow-pop); }',
  '.ilife-bill-sheet-page .ilife-copy-menu-item { min-height: 44px; padding: 10px 12px; border-radius: var(--ilife-radius-sm); font-size: 13.5px; font-weight: 700; color: var(--ilife-ink); }',
  '.ilife-bill-sheet-page .ilife-copy-menu-item > .ilife-copy-menu-label { font-size: 13.5px; font-weight: 700; color: var(--ilife-ink); }',
  '.ilife-bill-sheet-page .ilife-copy-menu-item > .ilife-copy-menu-hint { font-size: 11.5px; font-weight: 600; color: var(--ilife-ink-2); }',
  '/* 窄档（原型 390 档；仓内既有断点取 400）：桌内距与纸内距收一档、主数字收一档。 */',
  '@media (max-width: 400px) {',
  '  .ilife-bill-sheet-page { padding: 18px 10px 36px; }',
  '  .ilife-bill-sheet-page .ilife-block-sheet.is-ticket { padding: 18px 22px 8px; }',
  '  .ilife-bill-sheet-page .ilife-ticket-summary .ilife-block-summary-head.is-ticket .ilife-block-summary-head-value { font-size: 50px; }',
  '  .ilife-sheet-title { font-size: 18px; }',
  '  .ilife-bill-sheet-page .ilife-block-ledger-row-value { max-width: 58%; }',
  '}',
].join(LF);

/** 票据纸族样式段·**页面族块**（#1124 §20／§21／§22 从各页面逐字节搬来的整页 CSS）。
 *
 *  这些选择器全被各自页面族的作用域锁着（`.ilife-ticket-detail .ilife-today-*`／`.ilife-week-*`／
 *  `.ilife-debt-*`… 与 `section[data-key="account.*"]`），**只有那一族的页会用上**；
 *  不属于那些族的页（HELP／速查表）经 `ticketFamilyCss({ pageCss: false })` 不注入本段。#1124 第三步。 */
const TICKET_PAGE_CSS = [
  /* #1124 §22：账户域复制区 guards 从页面搬来（逐字节，作用域原样保留）——页面侧不再自出这一段。 */
  /* #1132：账户／目标两族的判地把复制钮标签包在 `.btn-in` 里（行高 1.4 ⇒ 盒高 47），查询／分析族不带那一层（46.3）
    ——按族给盒高，别一把梭到全族。 */
 '.ilife-skin-ticket section[data-key="account.write"] .ilife-copy-btn, .ilife-skin-ticket section[data-key="account.query"] .ilife-copy-btn, .ilife-skin-ticket section[data-key="goal.write"] .ilife-copy-btn, .ilife-skin-ticket section[data-key="goal.query"] .ilife-copy-btn { min-height: 47px; }',
 'section[data-key="account.write"] .ilife-block-copy-block, section[data-key="account.query"] .ilife-block-copy-block { max-width: 340px; margin-inline: auto; text-align: center; }',
  'section[data-key="account.write"] .ilife-action-row-ghost, section[data-key="account.query"] .ilife-action-row-ghost { display: flex; flex-direction: column; align-items: center; gap: 0; }',
  'section[data-key="account.write"] .ilife-copy-menu-wrap, section[data-key="account.query"] .ilife-copy-menu-wrap { width: 100%; max-width: 340px; margin-inline: auto; justify-content: center; }',
  'section[data-key="account.write"] .ilife-copy-btn, section[data-key="account.query"] .ilife-copy-btn { width: 100%; max-width: 340px; justify-content: center; text-align: center; }',
  'section[data-key="account.write"] .ilife-copy-menu-wrap > .ilife-copy-btn::after, section[data-key="account.query"] .ilife-copy-menu-wrap > .ilife-copy-btn::after { content: " \\25BE"; border: none !important; width: auto; height: auto; margin-left: 6px; transform: none !important; }',
  'section[data-key="account.write"] .copy-menu-open.ilife-copy-menu-wrap > .ilife-copy-btn::after, section[data-key="account.query"] .copy-menu-open.ilife-copy-menu-wrap > .ilife-copy-btn::after { transform: none !important; }',
  'section[data-key="account.write"] [data-action-id="ilife-copy-log"]::after, section[data-key="account.query"] [data-action-id="ilife-copy-log"]::after { content: " \\25BE"; visibility: hidden; margin-left: 6px; }',
  'section[data-key="account.write"] .ilife-copy-btn.copied::after, section[data-key="account.query"] .ilife-copy-btn.copied::after { content: none !important; }',
  'section[data-key="account.write"] .ilife-block-param-form-input, section[data-key="account.query"] .ilife-block-param-form-input { min-width: 0; max-width: 100%; width: 100%; box-sizing: border-box; }',
  'section[data-key="account.write"] .ilife-block-param-form-field, section[data-key="account.query"] .ilife-block-param-form-field { min-width: 0; max-width: 100%; }',
  'section[data-key="account.write"] select.ilife-block-param-form-input, section[data-key="account.query"] select.ilife-block-param-form-input { min-height: 44px; }',
  /* #1124 §22：目标域复制区 guards 从页面搬来（逐字节，作用域原样保留）——页面侧不再自出这一段。 */
  'section[data-key="goal.write"] .ilife-block-copy-block, section[data-key="goal.query"] .ilife-block-copy-block { max-width: 340px; margin-inline: auto; text-align: center; }',
  'section[data-key="goal.write"] .ilife-action-row-ghost, section[data-key="goal.query"] .ilife-action-row-ghost { display: flex; flex-direction: column; align-items: center; gap: 0; }',
  'section[data-key="goal.write"] .ilife-copy-menu-wrap, section[data-key="goal.query"] .ilife-copy-menu-wrap { width: 100%; max-width: 340px; margin-inline: auto; justify-content: center; }',
  'section[data-key="goal.write"] .ilife-copy-btn, section[data-key="goal.query"] .ilife-copy-btn { width: 100%; max-width: 340px; justify-content: center; text-align: center; }',
  'section[data-key="goal.write"] .ilife-copy-menu-wrap > .ilife-copy-btn::after, section[data-key="goal.query"] .ilife-copy-menu-wrap > .ilife-copy-btn::after { content: " \\25BE"; border: none !important; width: auto; height: auto; margin-left: 6px; transform: none !important; }',
  'section[data-key="goal.write"] .copy-menu-open.ilife-copy-menu-wrap > .ilife-copy-btn::after, section[data-key="goal.query"] .copy-menu-open.ilife-copy-menu-wrap > .ilife-copy-btn::after { transform: none !important; }',
  'section[data-key="goal.write"] [data-action-id="ilife-copy-log"]::after, section[data-key="goal.query"] [data-action-id="ilife-copy-log"]::after { content: " \\25BE"; visibility: hidden; margin-left: 6px; }',
  'section[data-key="goal.write"] .ilife-copy-btn.copied::after, section[data-key="goal.query"] .ilife-copy-btn.copied::after { content: none !important; }',
  'section[data-key="goal.write"] .ilife-block-param-form-input, section[data-key="goal.query"] .ilife-block-param-form-input { min-width: 0; max-width: 100%; width: 100%; box-sizing: border-box; min-height: 44px; }',
  'section[data-key="goal.write"] .ilife-block-param-form-field, section[data-key="goal.query"] .ilife-block-param-form-field { min-width: 0; max-width: 100%; }',
  /* #1124 §20：SAY 采集页整页 CSS 从 write/saySheet.ts 搬来（逐字节，选择器一字不动）——页面侧不再自出这一段。 */
  "/* 桌（判地 body）：底色两处浅深是字面值，皮肤 token 只是同值代名 */",
  ".ilife-bill-sheet-page:has(.say-page) { background: radial-gradient(1200px 600px at 50% -10%, #f7f2e6 0%, var(--ilife-ground) 55%, #e6dcc8 100%); color: var(--ilife-ink); font-family: var(--ilife-font); -webkit-font-smoothing: antialiased; min-height: 100vh; display: flex; flex-direction: column; align-items: center; padding: 28px 14px 48px; }",
  "/* 纸宽（判地 .page） */",
  ".say-page { width: 100%; max-width: 440px; }",
  "/* 纸（判地 .sheet-wrap／.sheet-frame／.sheet-inner）：投影走 drop-shadow，两列齿边挖的是桌面色 */",
  ".say-page .sheet-wrap { position: relative; filter: drop-shadow(var(--ilife-shadow)); }",
  ".say-page .sheet-frame { position: relative; background: var(--ilife-surface); border-radius: var(--ilife-radius); overflow: hidden; }",
  ".say-page .sheet-frame::before, .say-page .sheet-frame::after { content: \"\"; position: absolute; top: 0; bottom: 0; width: 14px; background-image: radial-gradient(circle at 7px 10px, var(--ilife-ground) 5.5px, transparent 6px); background-size: 14px 20px; background-repeat: repeat-y; pointer-events: none; }",
  ".say-page .sheet-frame::before { left: 0; }",
  ".say-page .sheet-frame::after { right: 0; transform: scaleX(-1); }",
  ".say-page .sheet-inner { padding: 22px 28px 10px; position: relative; }",
  ".say-page .zigzag { height: 12px; margin: 0 6px; transform: rotate(180deg); background: linear-gradient(-45deg, transparent 8px, var(--ilife-surface) 0) 0 0/16px 16px repeat-x, linear-gradient(45deg, transparent 8px, var(--ilife-surface) 0) 8px 0/16px 16px repeat-x; }",
  "/* 店头（判地 .shop-head） */",
  ".say-page .shop-head { text-align: center; padding: 2px 0 0; }",
  ".say-page .shop-brand { font-size: 11.5px; letter-spacing: 2px; color: var(--ilife-ink-2); font-weight: 700; }",
  ".say-page .shop-head h2 { margin: 8px 0 0; font-size: 19px; line-height: 1.4; font-weight: 800; }",
  ".say-page .shop-sub { margin: 8px 0 0; font-size: 12.5px; line-height: 1.6; color: var(--ilife-ink-2); }",
  "/* 虚线分隔与段（判地 hr.dashed／.sec／.sec-heading） */",
  ".say-page .dashed { border: 0; border-top: 2px dashed var(--ilife-line); margin: 14px -8px; }",
  ".say-page .sec { padding: 2px 0 6px; }",
  ".say-page .sec-heading { display: flex; align-items: center; gap: 8px; margin: 4px 0 10px; font-size: 13px; font-weight: 800; letter-spacing: 1.5px; color: #6b6152; }",
  ".say-page .sec-heading::before { content: \"\"; width: 4px; height: 14px; border-radius: 4px; background: var(--ilife-accent); }",
  ".say-page .sec-heading .no { margin-left: auto; font-weight: 700; color: var(--ilife-ink-3); letter-spacing: 0; }",
  "/* 缺项徽章列（判地 .slot-row／.slot） */",
  ".say-page .slot-row { display: flex; flex-wrap: wrap; gap: 8px; margin: 2px 0 4px; }",
  ".say-page .slot { display: inline-flex; align-items: center; gap: 6px; min-height: 44px; padding: 8px 14px; border-radius: 999px; font-size: 13.5px; font-weight: 800; background: var(--ilife-accent-soft); border: 1px solid #f0d7c2; color: var(--ilife-accent); }",
  ".say-page .slot.miss { background: #f9e8e4; border-color: #e5b8b0; color: var(--ilife-danger); }",
  ".say-page .slot.ok { background: var(--ilife-ok-soft); border-color: #bfe3cc; color: var(--ilife-ok); }",
  ".say-page .slot small { font-weight: 600; font-size: 11.5px; opacity: .85; }",
  "/* 已替你填好的行（判地 .fill-line） */",
  ".say-page .fill-line { display: flex; align-items: flex-end; gap: 8px; padding: 9px 0; font-size: 14px; line-height: 1.4; min-height: 44px; }",
  ".say-page .fill-line .k { flex: none; color: var(--ilife-ink-2); white-space: nowrap; }",
  ".say-page .fill-line .dots { flex: 1 1 auto; min-width: 14px; border-bottom: 2px dotted #d9cdb4; transform: translateY(-5px); }",
  ".say-page .fill-line .v { flex: none; max-width: 62%; text-align: right; font-weight: 700; overflow-wrap: anywhere; }",
  "/* 表单（判地 .say-form／.say-field） */",
  ".say-page .say-form { display: flex; flex-direction: column; gap: 10px; margin: 0 0 10px; }",
  ".say-page .say-field { display: flex; flex-wrap: wrap; align-items: center; gap: 10px; min-height: 44px; background: #fbf7ec; border: 1px solid var(--ilife-line); border-radius: 12px; padding: 8px 12px; font-size: 14px; }",
  ".say-page .say-field > span:first-child { flex: none; min-width: 76px; color: var(--ilife-ink-2); font-weight: 700; white-space: nowrap; }",
  ".say-page .say-field .req { color: var(--ilife-danger); font-style: normal; font-weight: 900; }",
  ".say-page .say-field input, .say-page .say-field select { flex: 1 1 0; min-width: 0; min-height: 44px; border: 1.5px solid #ddd0b6; border-radius: 10px; background: #fff; color: var(--ilife-ink); font-size: 15px; font-weight: 700; padding: 8px 10px; font-family: var(--ilife-font); }",
  ".say-page .say-field input:focus, .say-page .say-field select:focus { outline: 2px solid var(--ilife-accent); outline-offset: 1px; border-color: var(--ilife-accent); }",
  ".say-page .say-field input:disabled { background: #f4efe2; color: #a39c8e; }",
  "/* 选填组（判地 .say-opt） */",
  ".say-page .say-opt { margin: 10px 0 0; border: 1px dashed #ddd0b6; border-radius: 12px; background: #fdfaf3; overflow: hidden; }",
  ".say-page .say-opt > summary { list-style: none; cursor: pointer; display: flex; align-items: center; gap: 8px; min-height: 44px; padding: 10px 13px; font-size: 13px; font-weight: 700; color: var(--ilife-ink-2); }",
  ".say-page .say-opt > summary::-webkit-details-marker { display: none; }",
  ".say-page .say-opt > summary .lbl { flex: none; white-space: nowrap; }",
  ".say-page .say-opt > summary .plus { flex: none; color: var(--ilife-accent); font-weight: 900; font-size: 15px; line-height: 1; }",
  ".say-page .say-opt > summary .sub { flex: 1 1 auto; min-width: 0; font-weight: 400; color: var(--ilife-ink-3); font-size: 12px; overflow-wrap: anywhere; }",
  ".say-page .say-opt > summary .cnt { flex: none; font-size: 12px; color: var(--ilife-accent); font-weight: 800; white-space: nowrap; }",
  ".say-page .say-opt[open] > summary { border-bottom: 1px dashed #ddd0b6; background: #fbf7ec; }",
  ".say-page .say-opt .say-form { margin: 10px 13px 0; }",
  ".say-page .say-opt-note { margin: 6px 13px 12px; font-size: 12px; line-height: 1.6; color: var(--ilife-ink-3); }",
  "/* 提示行（判地 .say-hint） */",
  ".say-page .say-hint { margin: 8px 2px 0; font-size: 12.5px; line-height: 1.7; color: var(--ilife-danger); font-weight: 700; }",
  ".say-page .say-hint.ready { color: var(--ilife-ok); }",
  "/* 按钮区（判地 .actions／.btn） */",
  ".say-page .actions { display: flex; flex-wrap: wrap; gap: 8px; justify-content: center; align-items: center; padding: 14px 0 4px; text-align: center; }",
  ".say-page .actions .btn-primary { flex: 1 1 100%; width: 100%; }",
  ".say-page .btn { display: flex; align-items: center; justify-content: center; text-align: center; min-height: 48px; border-radius: 13px; font-size: 16px; font-weight: 800; letter-spacing: .5px; border: 0; padding: 12px 14px; }",
  ".say-page .btn-primary { background: linear-gradient(180deg, #d34a35, #b93222); color: #fff; box-shadow: 0 8px 20px rgba(185,50,34,.28), inset 0 1px 0 rgba(255,255,255,.25); }",
  ".say-page .btn-secondary { background: #fff; color: #4a4236; border: 1.5px solid #ddd0b6; min-height: 44px; font-size: 14.5px; }",
  ".say-page .actions .btn-secondary { flex: 1 1 100%; width: 100%; margin-top: 0; }",
  ".say-page .copy-wrap { position: relative; flex: 1 1 100%; width: 100%; margin-top: 0; display: flex; justify-content: center; text-align: center; }",
  ".say-page .actions #say-btn { flex: 1 1 100%; width: 100%; margin: 2px auto 0; }",
  ".say-page .actions #say-data-btn { flex: 1 1 100%; width: 100%; margin: 2px auto 0; }",
  ".say-page .actions #say-log-btn { flex: 1 1 100%; width: 100%; margin: 2px auto 0; }",
  ".say-page .actions #say-data-btn .btn-in, .say-page .actions #say-log-btn .btn-in { display: inline-block; min-width: 0; text-align: left; font: inherit; letter-spacing: inherit; }",
  ".say-page .actions .tri { font: inherit; }",
  ".say-page .actions .tri.ghost { visibility: hidden; }",
  ".say-page .btn-primary:disabled { background: #c9c2b4; color: #fff; box-shadow: none; opacity: .9; cursor: not-allowed; }",
  ".say-page .copy-menu { position: absolute; left: 0; right: 0; bottom: calc(100% + 8px); min-width: 200px; text-align: center; background: #fff; border: 1.5px solid #ddd0b6; border-radius: 12px; box-shadow: var(--ilife-shadow-pop); padding: 6px; display: none; z-index: 5; }",
  ".say-page .copy-wrap.open .copy-menu { display: block; }",
  ".say-page .copy-item { display: flex; justify-content: center; text-align: center; align-items: center; gap: 10px; width: 100%; min-height: 44px; padding: 10px 12px; border: 0; border-radius: 8px; background: none; font-size: 13.5px; font-weight: 700; color: var(--ilife-ink); }",
  ".say-page .copy-item small { font-weight: 600; color: var(--ilife-ink-2); font-size: 11.5px; }",
  "/* 裁切线（判地 .cut-line） */",
  ".say-page .cut-line { display: flex; align-items: center; gap: 10px; padding: 14px 0 8px; color: var(--ilife-ink-3); font-size: 12px; }",
  ".say-page .cut-line::before, .say-page .cut-line::after { content: \"\"; flex: 1; border-top: 2px dashed #d9cdb4; }",
  "/* 纸外脚注（判地 .foot-note） */",
  ".say-page .foot-note { text-align: center; color: var(--ilife-ink-3); font-size: 11.5px; padding: 10px 0 2px; letter-spacing: .4px; line-height: 1.7; }",
  "/* 窄档（判地 390 档；同值照抄，含桌、纸内距与标题字号三处） */",
  "@media (max-width: 390px) { .ilife-bill-sheet-page:has(.say-page) { padding: 18px 10px 36px; } .say-page .sheet-inner { padding: 18px 22px 8px; } .say-page .shop-head h2 { font-size: 18px; } }",
  /* #1124 §21：YESTERDAY_TICKET_CSS 从 src/query/ticketYesterday.ts 逐字节搬来（选择器一字不动）——页面侧不再自出这一段。 */
  '.ilife-ticket-detail .ilife-yesterday-shop-sub { margin: 8px 0 0; font-size: 12.5px; line-height: 1.6; color: var(--ilife-ink-2); text-align: center; overflow-wrap: anywhere; }',
  '.ilife-ticket-detail .ilife-yesterday-sub { display: block; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; font-size: 12.5px; font-weight: 400; color: var(--ilife-ink-2); margin-top: 2px; }',
  '.ilife-ticket-detail .ilife-yesterday-mono { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 12px; }',
  '.ilife-ticket-detail .ilife-yesterday-amt { flex: 0 0 auto; font-variant-numeric: tabular-nums; font-weight: 800; white-space: nowrap; }',
  '.ilife-ticket-detail .ilife-yesterday-check { display: flex; align-items: center; gap: 8px; background: var(--ilife-ok-soft); border-radius: var(--ilife-radius-sm); padding: 10px 12px; font-size: 13px; line-height: 1.6; overflow-wrap: anywhere; }',
  '.ilife-ticket-detail .ilife-yesterday-check-dot { flex: 0 0 auto; width: 8px; height: 8px; border-radius: 999px; background: var(--ilife-ok); }',
  '.ilife-yesterday-foot { text-align: center; color: var(--ilife-ink-3); font-size: 11.5px; padding: 10px 0 2px; letter-spacing: .4px; line-height: 1.7; }',
  /* #1124 §21：WEEK_TICKET_CSS 从 src/query/ticketWeek.ts 逐字节搬来（选择器一字不动）——页面侧不再自出这一段。 */
  '.ilife-ticket-detail .ilife-week-shop-sub { margin: 8px 0 0; font-size: 12.5px; line-height: 1.6; color: var(--ilife-ink-2); text-align: center; overflow-wrap: anywhere; }',
  '.ilife-ticket-detail .ilife-week-sub { display: block; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; font-size: 12.5px; font-weight: 400; color: var(--ilife-ink-2); margin-top: 2px; }',
  '.ilife-ticket-detail .ilife-week-mono { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 12px; }',
  '.ilife-ticket-detail .ilife-week-amt { flex: 0 0 auto; font-variant-numeric: tabular-nums; font-weight: 800; white-space: nowrap; }',
  '.ilife-ticket-detail .ilife-week-check { display: flex; align-items: center; gap: 8px; background: var(--ilife-ok-soft); border-radius: var(--ilife-radius-sm); padding: 10px 12px; font-size: 13px; line-height: 1.6; overflow-wrap: anywhere; }',
  '.ilife-ticket-detail .ilife-week-check-dot { flex: 0 0 auto; width: 8px; height: 8px; border-radius: 999px; background: var(--ilife-ok); }',
  '.ilife-week-foot { text-align: center; color: var(--ilife-ink-3); font-size: 11.5px; padding: 10px 0 2px; letter-spacing: .4px; line-height: 1.7; }',
  /* #1124 §21：EMPTY_TICKET_CSS 从 src/query/ticket-empty.ts 逐字节搬来（选择器一字不动）——页面侧不再自出这一段。 */
  '.ilife-ticket-detail .ilife-empty-shop-sub { margin: 8px 0 0; font-size: 12.5px; line-height: 1.6; color: var(--ilife-ink-2); text-align: center; overflow-wrap: anywhere; }',
  '.ilife-ticket-detail .ilife-empty-check { display: flex; align-items: center; gap: 8px; background: var(--ilife-ok-soft); border-radius: var(--ilife-radius-sm); padding: 10px 12px; font-size: 13px; line-height: 1.6; overflow-wrap: anywhere; }',
  '.ilife-ticket-detail .ilife-empty-check-dot { flex: 0 0 auto; width: 8px; height: 8px; border-radius: 999px; background: var(--ilife-ok); }',
  '.ilife-empty-foot { text-align: center; color: var(--ilife-ink-3); font-size: 11.5px; padding: 10px 0 2px; letter-spacing: .4px; line-height: 1.7; }',
  /* #1124 §21：TODAY_TICKET_CSS 从 src/query/ticketToday.ts 逐字节搬来（选择器一字不动）——页面侧不再自出这一段。 */
  '.ilife-ticket-detail .ilife-today-shop-sub { margin: 8px 0 0; font-size: 12.5px; line-height: 1.6; color: var(--ilife-ink-2); text-align: center; overflow-wrap: anywhere; }',
  '.ilife-ticket-detail .ilife-today-alias { margin: 6px 0 0; font-size: 12px; line-height: 1.6; color: var(--ilife-ink-3); text-align: center; overflow-wrap: anywhere; }',
  '.ilife-ticket-detail .ilife-today-sub { display: block; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; font-size: 12.5px; font-weight: 400; color: var(--ilife-ink-2); margin-top: 2px; }',
  '.ilife-ticket-detail .ilife-today-mono { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 12px; }',
  '.ilife-ticket-detail .ilife-today-amt { flex: 0 0 auto; font-variant-numeric: tabular-nums; font-weight: 800; white-space: nowrap; }',
  '.ilife-ticket-detail .ilife-today-check { display: flex; align-items: center; gap: 8px; background: var(--ilife-ok-soft); border-radius: var(--ilife-radius-sm); padding: 10px 12px; font-size: 13px; line-height: 1.6; overflow-wrap: anywhere; }',
  '.ilife-ticket-detail .ilife-today-check-dot { flex: 0 0 auto; width: 8px; height: 8px; border-radius: 999px; background: var(--ilife-ok); }',
  '.ilife-today-foot { text-align: center; color: var(--ilife-ink-3); font-size: 11.5px; padding: 10px 0 2px; letter-spacing: .4px; line-height: 1.7; }',
  /* #1124 §21：LEDGER_TICKET_CSS 从 src/query/ticketLedger.ts 逐字节搬来（选择器一字不动）——页面侧不再自出这一段。 */
  '.ilife-ticket-detail .ilife-ledger-shop-sub { margin: 8px 0 0; font-size: 12.5px; line-height: 1.6; color: var(--ilife-ink-2); text-align: center; overflow-wrap: anywhere; }',
  '.ilife-ticket-detail .ilife-ledger-sub { display: block; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; font-size: 12.5px; font-weight: 400; color: var(--ilife-ink-2); margin-top: 2px; }',
  '.ilife-ticket-detail .ilife-ledger-mono { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 12px; }',
  '.ilife-ticket-detail .ilife-ledger-amt { flex: 0 0 auto; font-variant-numeric: tabular-nums; font-weight: 800; white-space: nowrap; }',
  '.ilife-ticket-detail .ilife-ledger-check { display: flex; align-items: center; gap: 8px; background: var(--ilife-ok-soft); border-radius: var(--ilife-radius-sm); padding: 10px 12px; font-size: 13px; line-height: 1.6; overflow-wrap: anywhere; }',
  '.ilife-ticket-detail .ilife-ledger-check-dot { flex: 0 0 auto; width: 8px; height: 8px; border-radius: 999px; background: var(--ilife-ok); }',
  '.ilife-ledger-foot { text-align: center; color: var(--ilife-ink-3); font-size: 11.5px; padding: 10px 0 2px; letter-spacing: .4px; line-height: 1.7; }',
  /* #1124 §21：CATEGORY_TICKET_CSS 从 src/query/ticketCategory.ts 逐字节搬来（选择器一字不动）——页面侧不再自出这一段。 */
  '.ilife-ticket-detail .ilife-category-bar { display: block; height: 6px; margin-top: 6px; border-radius: var(--ilife-radius-pill); background: var(--ilife-line); overflow: hidden; }',
  /* #1113：占比条填充读皮肤号 `bar-fill`（票据纸＝判地 `.entry-text .bar i{background:#3f7fbf}`；
     兜底到 `--blue` ⇒ 没挂皮肤／别的皮肤与改动前逐字节同）。 */
  '.ilife-ticket-detail .ilife-category-bar > i { display: block; height: 100%; border-radius: var(--ilife-radius-pill); background: var(--ilife-bar-fill, var(--blue)); }',
  '.ilife-ticket-detail .ilife-category-check { display: flex; align-items: center; gap: 8px; background: var(--ilife-ok-soft); border-radius: var(--ilife-radius-sm); padding: 10px 12px; font-size: 13px; line-height: 1.6; overflow-wrap: anywhere; }',
  '.ilife-ticket-detail .ilife-category-check-dot { flex: 0 0 auto; width: 8px; height: 8px; border-radius: 999px; background: var(--ilife-ok); }',
  '.ilife-category-foot { text-align: center; color: var(--ilife-ink-3); font-size: 11.5px; padding: 10px 0 2px; letter-spacing: .4px; line-height: 1.7; }',
  /* #1124 §21：REIMBURSE_TICKET_CSS 从 src/query/ticketReimburse.ts 逐字节搬来（选择器一字不动）——页面侧不再自出这一段。 */
  '.ilife-ticket-detail .ilife-reimburse-shop-sub { margin: 8px 0 0; font-size: 12.5px; line-height: 1.6; color: var(--ilife-ink-2); text-align: center; }',
  '.ilife-ticket-detail .ilife-reimburse-sub { display: block; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; font-size: 12.5px; font-weight: 400; color: var(--ilife-ink-2); margin-top: 2px; }',
  '.ilife-ticket-detail .ilife-reimburse-mono { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 12px; }',
  '.ilife-ticket-detail .ilife-reimburse-amt { flex: 0 0 auto; font-variant-numeric: tabular-nums; font-weight: 800; }',
  '.ilife-ticket-detail .ilife-reimburse-check { display: flex; align-items: center; gap: 8px; background: var(--ilife-ok-soft); border-radius: var(--ilife-radius-sm); padding: 10px 12px; font-size: 13px; line-height: 1.6; }',
  '.ilife-ticket-detail .ilife-reimburse-check-dot { flex: 0 0 auto; width: 8px; height: 8px; border-radius: 999px; background: var(--ilife-ok); }',
  '.ilife-ticket-detail .ilife-reimburse-foot { text-align: center; color: var(--ilife-ink-3); font-size: 11.5px; padding: 10px 0 2px; letter-spacing: .4px; line-height: 1.7; }',
  /* #1124 §21：SOMEDAY_TICKET_CSS 从 src/query/ticket-day.ts 逐字节搬来（选择器一字不动）——页面侧不再自出这一段。 */
  '.ilife-ticket-detail .ilife-someday-shop-sub { margin: 8px 0 0; font-size: 12.5px; line-height: 1.6; color: var(--ilife-ink-2); text-align: center; overflow-wrap: anywhere; }',
  '.ilife-ticket-detail .ilife-someday-sub { display: block; min-width: 0; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; font-size: 12.5px; font-weight: 400; color: var(--ilife-ink-2); margin-top: 2px; }',
  '.ilife-ticket-detail .ilife-someday-mono { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 12px; }',
  '.ilife-ticket-detail .ilife-someday-amt { flex: 0 0 auto; font-variant-numeric: tabular-nums; font-weight: 800; white-space: nowrap; }',
  '.ilife-ticket-detail .ilife-someday-check { display: flex; align-items: center; gap: 8px; background: var(--ilife-ok-soft); border-radius: var(--ilife-radius-sm); padding: 10px 12px; font-size: 13px; line-height: 1.6; overflow-wrap: anywhere; }',
  '.ilife-ticket-detail .ilife-someday-check-dot { flex: 0 0 auto; width: 8px; height: 8px; border-radius: 999px; background: var(--ilife-ok); }',
  '.ilife-someday-foot { text-align: center; color: var(--ilife-ink-3); font-size: 11.5px; padding: 10px 0 2px; letter-spacing: .4px; line-height: 1.7; }',
  /* #1124 §21：ACCOUNT_TICKET_CSS 从 src/query/ticketAccount.ts 逐字节搬来（选择器一字不动）——页面侧不再自出这一段。 */
  '.ilife-ticket-detail .ilife-account-shop-sub { margin: 8px 0 0; font-size: 12.5px; line-height: 1.6; color: var(--ilife-ink-2); text-align: center; overflow-wrap: anywhere; }',
  '.ilife-ticket-detail .ilife-account-sub { display: block; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; font-size: 12.5px; font-weight: 400; color: var(--ilife-ink-2); margin-top: 2px; }',
  '.ilife-ticket-detail .ilife-account-mono { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 12px; }',
  '.ilife-ticket-detail .ilife-account-amt { flex: 0 0 auto; font-variant-numeric: tabular-nums; font-weight: 800; white-space: nowrap; }',
  '.ilife-ticket-detail .ilife-account-check { display: flex; align-items: center; gap: 8px; background: var(--ilife-ok-soft); border-radius: var(--ilife-radius-sm); padding: 10px 12px; font-size: 13px; line-height: 1.6; overflow-wrap: anywhere; }',
  '.ilife-ticket-detail .ilife-account-check-dot { flex: 0 0 auto; width: 8px; height: 8px; border-radius: 999px; background: var(--ilife-ok); }',
  '.ilife-account-foot { text-align: center; color: var(--ilife-ink-3); font-size: 11.5px; padding: 10px 0 2px; letter-spacing: .4px; line-height: 1.7; }',
  /* #1124 §21：DEBT_TICKET_CSS 从 src/query/ticketDebt.ts 逐字节搬来（选择器一字不动）——页面侧不再自出这一段。 */
  '.ilife-ticket-detail .ilife-debt-shop-sub { margin: 8px 0 0; font-size: 12.5px; line-height: 1.6; color: var(--ilife-ink-2); text-align: center; }',
  '.ilife-ticket-detail .ilife-debt-sub { display: block; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; font-size: 12.5px; font-weight: 400; color: var(--ilife-ink-2); margin-top: 2px; }',
  '.ilife-ticket-detail .ilife-debt-mono { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 12px; }',
  '.ilife-ticket-detail .ilife-debt-amt { flex: 0 0 auto; font-variant-numeric: tabular-nums; font-weight: 800; }',
  '.ilife-ticket-detail .ilife-debt-check { display: flex; align-items: center; gap: 8px; background: var(--ilife-ok-soft); border-radius: var(--ilife-radius-sm); padding: 10px 12px; font-size: 13px; line-height: 1.6; }',
  '.ilife-ticket-detail .ilife-debt-check-dot { flex: 0 0 auto; width: 8px; height: 8px; border-radius: 999px; background: var(--ilife-ok); }',
  '.ilife-debt-foot { text-align: center; color: var(--ilife-ink-3); font-size: 11.5px; padding: 10px 0 2px; letter-spacing: .4px; line-height: 1.7; }',
  /* #1124 §21：INSTALLMENT_TICKET_CSS 从 src/query/ticketInstallment.ts 逐字节搬来（选择器一字不动）——页面侧不再自出这一段。 */
  '.ilife-ticket-detail .ilife-installment-shop-sub { margin: 8px 0 0; font-size: 12.5px; line-height: 1.6; color: var(--ilife-ink-2); text-align: center; }',
  '.ilife-ticket-detail .ilife-installment-sub { display: block; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; font-size: 12.5px; font-weight: 400; color: var(--ilife-ink-2); margin-top: 2px; }',
  '.ilife-ticket-detail .ilife-installment-mono { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 12px; }',
  '.ilife-ticket-detail .ilife-installment-amt { flex: 0 0 auto; font-variant-numeric: tabular-nums; font-weight: 800; }',
  '.ilife-ticket-detail .ilife-installment-check { display: flex; align-items: center; gap: 8px; background: var(--ilife-ok-soft); border-radius: var(--ilife-radius-sm); padding: 10px 12px; font-size: 13px; line-height: 1.6; }',
  '.ilife-ticket-detail .ilife-installment-check-dot { flex: 0 0 auto; width: 8px; height: 8px; border-radius: 999px; background: var(--ilife-ok); }',
  '.ilife-ticket-detail .ilife-installment-foot { text-align: center; color: var(--ilife-ink-3); font-size: 11.5px; padding: 10px 0 2px; letter-spacing: .4px; line-height: 1.7; }',
  /* #1124 §21：INTERVAL_TICKET_CSS 从 src/query/ticketInterval.ts 逐字节搬来（选择器一字不动）——页面侧不再自出这一段。 */
  '.ilife-ticket-detail .ilife-interval-shop-sub { margin: 8px 0 0; font-size: 12.5px; line-height: 1.6; color: var(--ilife-ink-2); text-align: center; overflow-wrap: anywhere; }',
  '.ilife-ticket-detail .ilife-interval-sub { display: block; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; font-size: 12px; font-weight: 400; color: var(--ilife-ink-2); margin-top: 2px; }',
  '.ilife-ticket-detail .ilife-interval-mono { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 12px; }',
  '.ilife-ticket-detail .ilife-interval-amt { flex: none; font-weight: 800; white-space: nowrap; font-variant-numeric: tabular-nums; }',
  '.ilife-ticket-detail .ilife-interval-check { display: flex; align-items: flex-start; gap: 8px; background: var(--ilife-ok-soft); border-radius: var(--ilife-radius-sm); padding: 10px 12px; font-size: 13px; line-height: 1.6; overflow-wrap: anywhere; }',
  '.ilife-ticket-detail .ilife-interval-check-dot { flex: none; width: 8px; height: 8px; border-radius: 999px; background: var(--ilife-ok); margin-top: 6px; }',
  '.ilife-interval-foot { text-align: center; color: var(--ilife-ink-3); font-size: 11.5px; padding: 10px 0 2px; letter-spacing: .4px; line-height: 1.7; }',
  /* #1124 §21：RECENT_TICKET_CSS 从 src/query/ticketRecent.ts 逐字节搬来（选择器一字不动）——页面侧不再自出这一段。 */
  '.ilife-ticket-detail .ilife-recent-shop-sub { margin: 8px 0 0; font-size: 12.5px; line-height: 1.6; color: var(--ilife-ink-2); text-align: center; }',
  '.ilife-ticket-detail .ilife-recent-sub { display: block; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; font-size: 12.5px; font-weight: 400; color: var(--ilife-ink-2); margin-top: 2px; }',
  '.ilife-ticket-detail .ilife-recent-mono { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 12px; }',
  '.ilife-ticket-detail .ilife-recent-amt { flex: 0 0 auto; font-variant-numeric: tabular-nums; font-weight: 800; }',
  '.ilife-ticket-detail .ilife-recent-check { display: flex; align-items: center; gap: 8px; background: var(--ilife-ok-soft); border-radius: var(--ilife-radius-sm); padding: 10px 12px; font-size: 13px; line-height: 1.6; }',
  '.ilife-ticket-detail .ilife-recent-check-dot { flex: 0 0 auto; width: 8px; height: 8px; border-radius: 999px; background: var(--ilife-ok); }',
  '.ilife-recent-foot { text-align: center; color: var(--ilife-ink-3); font-size: 11.5px; padding: 10px 0 2px; letter-spacing: .4px; line-height: 1.7; }',
  /* #1124 §21：TAG_CSS 从 src/query/list-tag.ts 逐字节搬来（选择器一字不动）——页面侧不再自出这一段。 */
  '.ilife-taglist .shop-sub{margin:8px 0 0;font-size:12.5px;line-height:1.6;color:var(--ilife-ink-2);text-align:center;overflow-wrap:anywhere}',
  '.ilife-taglist .check-mini{display:flex;gap:8px;align-items:flex-start;background:#f4fbf6;border:1px solid #cfe6d6;border-radius:10px;padding:10px 12px;font-size:12.8px;line-height:1.6;color:#3e5a4a;margin-top:10px;overflow-wrap:anywhere}',
  '.ilife-taglist .check-mini .dot{flex:none;width:8px;height:8px;border-radius:50%;background:#2f9e5f;margin-top:6px}',
  '.ilife-taglist .ilife-ticket-entry-sub{display:block;font-size:12px;color:var(--ilife-ink-2);margin-top:2px}',
  '.ilife-taglist .ilife-ticket-entry-amt{flex:none;font-weight:800;white-space:nowrap;font-variant-numeric:tabular-nums}',
  '.ilife-taglist .mono{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}',
  /* #1124 §21：MONTH_TICKET_CSS 从 src/query/ticketMonth.ts 逐字节搬来（选择器一字不动）——页面侧不再自出这一段。 */
  '.ilife-ticket-detail .ilife-month-shop-sub { margin: 8px 0 0; font-size: 12.5px; line-height: 1.6; color: var(--ilife-ink-2); text-align: center; overflow-wrap: anywhere; }',
  '.ilife-ticket-detail .ilife-month-sub { display: block; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; font-size: 12.5px; font-weight: 400; color: var(--ilife-ink-2); margin-top: 2px; }',
  '.ilife-ticket-detail .ilife-month-mono { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 12px; }',
  '.ilife-ticket-detail .ilife-month-amt { flex: 0 0 auto; font-variant-numeric: tabular-nums; font-weight: 800; white-space: nowrap; }',
  '.ilife-ticket-detail .ilife-month-check { display: flex; align-items: center; gap: 8px; background: var(--ilife-ok-soft); border-radius: var(--ilife-radius-sm); padding: 10px 12px; font-size: 13px; line-height: 1.6; overflow-wrap: anywhere; }',
  '.ilife-ticket-detail .ilife-month-check-dot { flex: 0 0 auto; width: 8px; height: 8px; border-radius: 999px; background: var(--ilife-ok); }',
  '.ilife-month-foot { text-align: center; color: var(--ilife-ink-3); font-size: 11.5px; padding: 10px 0 2px; letter-spacing: .4px; line-height: 1.7; }',
].join(LF);

/** 票据纸族·**复制区形状**（规格 §6）：从 `components/style/copy-button.ts` 的通用段**搬来**（#1114 H-10 返修）。
 *
 *  为什么搬：那次按钮圆角（13px）与菜单圆角（12px）是**票据纸族的一次性授权字面**，住在通用件段里会被
 *  HELP 区的 radius 全集判据（H-10，`help-visual-lock-89.test.mjs`）算进 HELP 区——而它们只在
 *  `.ilife-page-ui .ilife-skin-ticket` 之下生效、HELP 壳页（`.ilife-help-shell`）根本命中不到。
 *  搬家后票据页经 `ticketFamilyCss()` 照旧拿得到（票据页恒注入本段），通用段回到干净集合。
 *  选择器与声明逐字照搬，只把前缀拼接写成字面类名（本件全篇是字面类名口径）。 */
const TICKET_CSS_COPY = [
  '/* 规格 §6 授权照抄：次按钮形状（票据纸族；只在 .ilife-page-ui .ilife-skin-ticket 之下生效）。 */',
  '.ilife-page-ui .ilife-skin-ticket .ilife-copy-btn {',
  '  width: 100%;',
  '  min-height: 44px;',
  '  padding: 12px 14px;',
  '  border: 1.5px solid #ddd0b6; /* 规格 §6 授权照抄：次按钮 1.5px 暖边 #ddd0b6 */',
  '  border-radius: 13px; /* 规格 §6 授权照抄：radius 13px（主/次按钮同档） */',
  '  background: #fff; /* 规格 §6 授权照抄：次按钮白底 #fff */',
  '  color: #4a4236; /* 判地字面 · 授权照抄：#4a4236（次按钮字色） */',
  '  font-size: 14.5px; /* 规格 §6 授权照抄：14.5px／w800 */',
  '  font-weight: 800;',
  '  letter-spacing: .5px;',
  '  /* 判地 .btn 不写行高：46.3px ＝ 12+12 内距 ＋ 1.5+1.5 边 ＋ 19.3（14.5px 的 normal 行盒）。',
  '     通用档写死 line-height:1（其余皮肤沿用）⇒ 这一档必须显式收回。 */',
  '  line-height: 1.4; /* 判地字面 · 授权照抄：行高 1.4（判地按钮标签住 .btn-in，行盒 20.3px） */',
  '}',
  '.ilife-page-ui .ilife-skin-ticket .ilife-copy-menu {',
  '  left: 0;',
  '  right: 0;',
  '  min-width: 0;',
  '  max-width: none;',
  '  padding: 6px;',
  '  border: 1.5px solid #ddd0b6; /* 规格 §6 授权照抄：菜单 1.5px 暖边 #ddd0b6 */',
  '  border-radius: 12px; /* 规格 §6 授权照抄：复制菜单圆角 12px */',
  '  background: #fff; /* 规格 §6 授权照抄：浮层白底 #fff */',
  '  box-shadow: var(--ilife-shadow-pop); /* 规格 §2 授权照抄：浮层投影 shadow-pop */',
  '}',
  '.ilife-page-ui .ilife-skin-ticket .ilife-copy-menu-item {',
  '  min-height: 44px;',
  '  padding: 10px 12px;',
  '  border-radius: 8px;',
  '  font-size: 13.5px; /* 规格 §6 授权照抄：菜项 13.5px／w700 */',
  '  font-weight: 700;',
  '}',
  '.ilife-page-ui .ilife-skin-ticket .ilife-copy-menu-item:hover {',
  '  background: #faf5e9; /* 判地字面 · 授权照抄：#faf5e9（菜项悬停底） */',
  '}',
  '.ilife-page-ui .ilife-skin-ticket .ilife-copy-menu-item > .ilife-copy-menu-label {',
  '  font-size: 13.5px;',
  '  font-weight: 700;',
  '  color: var(--ilife-ink);',
  '}',
  '.ilife-page-ui .ilife-skin-ticket .ilife-copy-menu-item > .ilife-copy-menu-hint {',
  '  font-size: 11.5px; /* 规格 §6 授权照抄：右注 11.5px／w600 */',
  '  font-weight: 600;',
  '  color: var(--ilife-ink-2);',
  '}',
].join(LF);

/** 票据纸族样式段全量（＝搬家前 docPage.ts 的 `TICKET_CSS` ＋ #1114 搬来的复制区形状段）。 */
const TICKET_CSS = [TICKET_CSS_CORE, TICKET_PAGE_CSS, TICKET_CSS_COPY].join(LF);

/** 票据纸页内家具样式段（＝搬家前 docPage.ts 的 `TICKET_FURNITURE_CSS`，逐字节相同）。 */
export const TICKET_FURNITURE_CSS = [
  '.ilife-ticket-receipt .ilife-block-ledger-rows.is-mono-first .ilife-block-ledger-row:first-child .ilife-block-ledger-row-value, .ilife-ticket-detail .ilife-block-ledger-rows.is-mono-first .ilife-block-ledger-row:first-child .ilife-block-ledger-row-value { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 12.5px; font-weight: 700; }',
  '.ilife-ticket-receipt .ilife-block-summary-head.is-warn-head .ilife-block-summary-head-eyebrow, .ilife-ticket-detail .ilife-block-summary-head.is-warn-head .ilife-block-summary-head-eyebrow { background: var(--ilife-warn-soft); border-color: #e8d3a8; color: var(--ilife-warn); }',
  '.ilife-ticket-receipt .ilife-block-summary-head.is-warn-head .ilife-block-summary-head-eyebrow::before, .ilife-ticket-detail .ilife-block-summary-head.is-warn-head .ilife-block-summary-head-eyebrow::before { background: #b97a1a; }',
  '.ilife-ticket-receipt .ilife-ticket-entries > li.is-star::before, .ilife-ticket-detail .ilife-ticket-entries > li.is-star::before { content: "★"; background: var(--ilife-ink); border-color: var(--ilife-ink); color: var(--ilife-surface); }',
  '.ilife-ticket-receipt .ilife-ticket-entry-sub, .ilife-ticket-detail .ilife-ticket-entry-sub { display: block; color: var(--ilife-ink-2); font-size: 12px; font-weight: 400; }',
  '.ilife-ticket-receipt .ilife-ticket-entries > li.is-done::before, .ilife-ticket-detail .ilife-ticket-entries > li.is-done::before, .ilife-ticket-receipt .ilife-ticket-entries > li.is-ok::before, .ilife-ticket-detail .ilife-ticket-entries > li.is-ok::before { background: var(--ilife-ok); border-color: var(--ilife-ok); color: var(--ilife-surface); }',
  '.ilife-ticket-receipt .ilife-ticket-entries > li.is-now::before, .ilife-ticket-detail .ilife-ticket-entries > li.is-now::before { background: var(--ilife-warn); border-color: var(--ilife-warn); color: var(--ilife-surface); }',
  '.ilife-ticket-receipt .ilife-ticket-entries > li.is-bad::before, .ilife-ticket-detail .ilife-ticket-entries > li.is-bad::before { background: var(--ilife-danger); border-color: var(--ilife-danger); color: var(--ilife-surface); }',
  '.ilife-ticket-receipt .ilife-ticket-check.is-warn, .ilife-ticket-detail .ilife-ticket-check.is-warn { background: var(--ilife-warn-soft); border-color: #e8d3a8; color: #5f4413; }',
  '.ilife-ticket-receipt .ilife-ticket-check.is-warn .ilife-ticket-check-dot, .ilife-ticket-detail .ilife-ticket-check.is-warn .ilife-ticket-check-dot { background: #b97a1a; }',
  '.ilife-ticket-receipt .ilife-ticket-prompt, .ilife-ticket-detail .ilife-ticket-prompt { margin-top: 10px; padding: 10px 12px; border: 1px solid #f0d9bd; border-radius: var(--ilife-radius-sm); background: #fff8ee; color: #4a4236; font-size: 13px; line-height: 1.7; }',
  '.ilife-ticket-receipt .ilife-ticket-prompt .ilife-ticket-prompt-mono, .ilife-ticket-detail .ilife-ticket-prompt .ilife-ticket-prompt-mono { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 12.5px; }',
].join('\n');

/** 族样式段（调用方显式拼；`assembleSheetPage` 用它替掉原来的 `TICKET_CSS` 槽位）。
 *
 *  `pageCss: false` ⇒ **只出 core 段**（#1124 第三步，HELP／速查表这类页面族之外的页用）：
 *  页面族块的选择器都被各自的页面族作用域锁着，这类页一个都用不上；不注入它们，页体积才回得到预算内。
 *  缺省（不给参数）＝全量，与搬家前逐字节相同——票据页调用点行为不变。 */
export function ticketFamilyCss(opts: { readonly pageCss?: boolean } = {}): string {
  return opts.pageCss === false ? TICKET_CSS_CORE : TICKET_CSS;
}

/** 页内家具样式段（`ticketFurnitureStyleTag()` 的正文来源）。 */
export function ticketFurnitureCss(): string {
  return TICKET_FURNITURE_CSS;
}
