/** style 区 · toast
 *
 *  自 `src/style.ts` 的 `SECTION_BUILDERS[toast]` **连它上面那段注释一起**原样切出。
 *
 *  **住址**：目录化批次⑥把 `src/style.ts` 切成「一份令牌 ＋ 一个区一件 ＋ 一个组装器」，
 *  正文原样搬来；搬迁判据＝产物逐字节相同（`buildStyleSheet()` 的 css 全文 ＋ 出口名单），
 *  见 `docs/base/base-render/组件目录架构.md`。
 */

import { LF, focusRing } from './parts.js';
import { TOAST_DEFAULTS } from '../../spec/index.js';

export const toastSection: (prefix: string) => string = (p) => [
  '.' + p + 'toast-stack {',
  '  position: fixed;',
  '  left: 50%;',
  '  bottom: calc(24px + env(safe-area-inset-bottom, 0px));',
  '  transform: translateX(-50%);',
  '  z-index: 9999;',
  '  display: flex;',
  '  flex-direction: column;',
  '  align-items: center;',
  '  gap: ' + TOAST_DEFAULTS.gapPx + 'px;',
  '  max-width: calc(100vw - 32px);',
  '  pointer-events: none;',
  '}',
  // W1（返修第二轮）：此处原有 `flex-wrap: wrap` 是**权宜补丁**（helpers 运行时 DOM 缺 body 包裹
  // 时靠换行分层，代价是把关闭按钮挤到第三行）。根因已由 `controls.ts` 的结构对齐修掉
  // （helpers 与静态产出器／旧层同构：`icon? + .toast-body(> .toast-title-row + detail) + .toast-close`），
  // 补丁一并删除 → 关闭按钮与标题恒同行。
  // 卡面色（2026-09-12 用户裁定改用**老技能**版）：深色毛玻璃，逐值取自
  // 老仓 `公共组件/assets/base.js:75` 的 `.hm-toast` 串——底色 rgba(28,28,30,.94)、
  // 毛玻璃 blur(20px) saturate(180%)、主字 #f0f0f0、投影 0 10px 32px rgba(0,0,0,.32)
  // ＋ 0 0 0 .5px rgba(255,255,255,.08) inset（原样的「无描边、靠内影收边」）。
  // 几何（圆角 14px／内距 13-14-16／min 300／max 480／gap 12）与老仓逐值相同，本次不动。
  // 取字面量而非 token：本卡是**深色面**，不随浅色 token 变——这是本次的唯一例外，记账见
  // `docs/visual-spec-blocks.md` §B-12 的 2026-09-12 裁定行。
  '.' + p + 'toast {',
  '  display: flex;',
  '  align-items: flex-start;',
  '  gap: 12px;',
  '  box-sizing: border-box;',
  '  min-width: 300px;',
  '  max-width: 480px;',
  '  padding: 13px 14px 13px 16px;',
  '  border-radius: 14px;',
  '  background: rgba(28, 28, 30, .94);',
  '  -webkit-backdrop-filter: blur(20px) saturate(180%);',
  '  backdrop-filter: blur(20px) saturate(180%);',
  '  color: #f0f0f0;',
  '  box-shadow: 0 10px 32px rgba(0, 0, 0, .32), 0 0 0 .5px rgba(255, 255, 255, .08) inset;',
  // #567 J4（§5.2 正文 13 吸收 13／12.5）。
  '  font-size: 13px;',
  '  line-height: 1.4;',
  '  font-feature-settings: "tnum";',
  '  pointer-events: auto;',
  '  animation: ' + p + 'toast-in .22s cubic-bezier(.34, 1.56, .64, 1) both;',
  '}',
  // 入场动效（W4）：旧层 `.hm-toast{opacity:0;transform:scale(.9)}` ＋ `.hm-toast.show{…}`
  // （`base.js:75`）依赖 JS 加类，新控制器**不加 `.show`**（`ToastController.show` 是方法名，非类）
  // → 改为 **CSS-only** `@keyframes` ＋ `animation`，**不依赖任何 JS 加类**，且默认可见。
  '@keyframes ' + p + 'toast-in {',
  '  from {',
  '    opacity: 0;',
  '    transform: scale(.9) translateY(4px);',
  '  }',
  '  to {',
  '    opacity: 1;',
  '    transform: none;',
  '  }',
  '}',
  // 失败态：老仓没有卡面描边，失败由「❌ 图标 ＋ danger 徽章」承担；深色面上改由
  // **内影那条 0.5px 细线换成功色系的红**来点一句（不新增描边、不改底色）。
  '.' + p + 'toast-danger {',
  '  box-shadow: 0 10px 32px rgba(0, 0, 0, .32), 0 0 0 .5px rgba(255, 59, 48, .45) inset;',
  '}',
  '.' + p + 'toast-icon {',
  '  flex: 0 0 auto;',
  '  padding-top: 1px;',
  // #567 J4（§5.2 标题 18 吸收 17／18／20／22）：装饰字形 20→18。
  '  font-size: 18px;',
  '  line-height: 1;',
  '}',
  // body 是 toast 的**唯一**内容列（静态产出器与 helpers 运行时同构，见 `controls.ts`
  // `TOAST_BODY_CLASS`）：`flex: 1 1 auto` 让它吃掉剩余宽度并内部换行，
  // 关闭按钮因此恒与标题同行（W1 判据 `rt_close_top === rt_title_top`）。
  '.' + p + 'toast-body {',
  '  flex: 1 1 auto;',
  '  min-width: 0;',
  '}',
  '.' + p + 'toast-title-row {',
  '  display: flex;',
  '  flex-wrap: wrap;',
  '  align-items: center;',
  '  gap: 8px;',
  '}',
  '.' + p + 'toast-title {',
  '  margin-bottom: 2px;',
  '  color: #fff;',
  // #567 J4（§5.2 正文 13 吸收 13／12.5）。
  '  font-size: 13px;',
  '  font-weight: 600;',
  '  line-height: 1.4;',
  '}',
  // 运行时详情（helpers 产出 `.ilife-toast-title-detail`，在 `.ilife-toast-body` 内）：
  // 与静态侧 `.ilife-toast-detail` **同排版**；此前的 `flex: 1 1 100%` 权宜补丁已随结构对齐删除。
  '.' + p + 'toast-title-detail {',
  '  color: #c8c8cc;',
  '  font-size: 11px;',
  '  font-weight: 400;',
  '  line-height: 1.5;',
  '}',
  '.' + p + 'toast-chip {',
  '  flex-shrink: 0;',
  '  padding: 2px 8px;',
  '  border-radius: 999px;',
  '  background: rgba(255, 255, 255, .12);',
  '  color: #c8c8cc;',
  // #567 J4（§5.2 下限 11：10／10.5／11 一律抬到 11）。
  '  font-size: 11px;',
  '  font-weight: 700;',
  '  letter-spacing: .02em;',
  '  line-height: 1.6;',
  '}',
  '.' + p + 'toast-chip-ok {',
  '  background: rgba(52, 199, 89, .18);',
  '  color: #4dd96b;',
  '}',
  '.' + p + 'toast-chip-warn {',
  '  background: rgba(255, 149, 0, .18);',
  '  color: #ffb340;',
  '}',
  '.' + p + 'toast-chip-danger {',
  '  background: rgba(255, 59, 48, .18);',
  '  color: #ff6961;',
  '}',
  '.' + p + 'toast-count {',
  '  flex-shrink: 0;',
  '  padding: 2px 8px;',
  '  border-radius: 8px;',
  '  background: rgba(255, 255, 255, .08);',
  '  color: #c8c8cc;',
  // #567 J4（§5.2 下限 11）。
  '  font-size: 11px;',
  '  font-weight: 700;',
  '  font-variant-numeric: tabular-nums;',
  '}',
  '.' + p + 'toast-detail {',
  '  color: #c8c8cc;',
  '  font-size: 11px;',
  '  line-height: 1.5;',
  '}',
  '.' + p + 'toast-lines {',
  '  color: #c8c8cc;',
  '  font-size: 11px;',
  '  line-height: 1.55;',
  '  white-space: pre-wrap;',
  '}',
  '.' + p + 'toast-code {',
  '  margin: 6px 0 0;',
  '  padding: 8px 10px;',
  '  border-radius: 8px;',
  '  background: rgba(0, 0, 0, .32);',
  '  color: #aeb0b8;',
  '  font-family: "SF Mono", monospace;',
  // #567 J4（§5.2 下限 11）。
  '  font-size: 11px;',
  '  line-height: 1.5;',
  '  white-space: pre-wrap;',
  '  max-height: 140px;',
  '  overflow: auto;',
  '}',
  '.' + p + 'toast-act {',
  '  margin: 0;',
  '  padding: 2px 4px;',
  '  border: 0;',
  '  background: none;',
  '  color: #4dd96b;',
  '  font-family: inherit;',
  '  font-size: 11px;',
  '  font-weight: 600;',
  '  cursor: pointer;',
  '  -webkit-tap-highlight-color: transparent;',
  '  touch-action: manipulation;',
  '}',
  '.' + p + 'toast-act:active {',
  '  opacity: .7;',
  '}',
  '.' + p + 'toast-close {',
  '  flex-shrink: 0;',
  '  margin: 0 0 0 6px;',
  '  padding: 5px 9px;',
  '  border: 0;',
  '  border-radius: 8px;',
  '  background: rgba(255, 255, 255, .10);',
  '  color: #34c759;',
  '  font-family: inherit;',
  // #567 J4（§5.2 下限 11）。
  '  font-size: 11px;',
  '  font-weight: 500;',
  '  white-space: nowrap;',
  '  cursor: pointer;',
  '  -webkit-tap-highlight-color: transparent;',
  '  touch-action: manipulation;',
  '}',
  focusRing('.' + p + 'toast-act'),
  focusRing('.' + p + 'toast-close'),
  '@media (max-width: ' + TOAST_DEFAULTS.mobileMaxPx + 'px) {',
  '  .' + p + 'toast-stack {',
  '    left: 12px;',
  '    right: 12px;',
  '    transform: none;',
  '    align-items: stretch;',
  '  }',
  '  .' + p + 'toast {',
  '    min-width: 0;',
  '    max-width: none;',
  '  }',
  '}',
].join(LF)
