/** pageBarsCss · #950：本族样式的**唯一产出者**（自产出器那件整段搬来，选择器与值一字未改）。
 *
 *  **住址**：目录化批次①把它从 `src/pageBarsCss.ts` 搬到 `src/components/page-bars/style.ts`
 *  （同批产出器 → `./index.ts`）；判据＝产物逐字节相同（`docs/base/base-render/组件目录架构.md`）。
 *
 *  为什么分开住：产出器那件带上这一整段就越过本包 350 行告警线；
 *  照仓内先例（`src/render/reviewDocsCss.ts`：样式另立姊妹件、出口经件薄转出），本族样式单独一件，
 *  产出器那件只留形状与类型，两边都落回线内。由 `pageShapeCss()` 汇总进页。
 */

/** 换行（仓库口径：不写字面换行转义，与 `blocks.ts`／`pageShapes.ts` 同）。 */
const LF = String.fromCharCode(10);

/* ══════════════════════════════════════════════════════════════
 * 样式（本族）：与产出器**分住两件**（本件）——照仓内 `reviewDocsCss.ts` 的先例，产出器那件只留形状与类型。
 * ══════════════════════════════════════════════════════════════ */

/** 三件的样式唯一产出者。恒返回非空 CSS 文本（由 `pageShapeCss()` 汇总进页）。 */
export function pageBarsCss(input?: { readonly prefix?: string }): string {
  const p = input !== undefined && input !== null
    && typeof input.prefix === 'string' && input.prefix !== '' ? input.prefix : 'ilife-';
  const root = '.' + p + 'page-ui';
  return [
    '/* ① 时间格带：7 格（或 N 格）等宽，一格一天；缺数格留空槽、不补零。 */',
    root + ' .' + p + 'block-day-strip {',
    '  background: var(--card);',
    '  border: 1px solid var(--line);',
    '  border-radius: ' + 14 + 'px;',
    '  overflow: hidden;',
    '}',
    root + ' .' + p + 'block-day-strip-cells {',
    '  display: grid;',
    '  grid-template-columns: repeat(auto-fit, minmax(0, 1fr));',
    '}',
    root + ' .' + p + 'block-day-strip-cell {',
    '  display: flex;',
    '  flex-direction: column;',
    '  align-items: center;',
    '  gap: 7px;',
    '  padding: 11px 8px 13px;',
    '  border-right: 1px solid var(--line);',
    '}',
    root + ' .' + p + 'block-day-strip-cell:last-child {',
    '  border-right: 0;',
    '}',
    root + ' .' + p + 'block-day-strip-date {',
    '  color: var(--fg3);',
    '  font-size: 12px;',
    '  font-variant-numeric: tabular-nums;',
    '  white-space: nowrap;',
    '}',
    root + ' .' + p + 'block-day-strip-dot {',
    '  width: 9px;',
    '  height: 9px;',
    '  border-radius: 50%;',
    '  background: var(--line);',
    '}',
    root + ' .' + p + 'block-day-strip-val {',
    '  color: var(--fg3);',
    '  font-size: 13px;',
    '  font-weight: 600;',
    '  font-variant-numeric: tabular-nums;',
    '}',
    root + ' .' + p + 'block-day-strip-cell.is-has {',
    '  background: rgba(0, 122, 255, .05);',
    '}',
    root + ' .' + p + 'block-day-strip-cell.is-has .' + p + 'block-day-strip-dot {',
    '  background: var(--blue);',
    '}',
    root + ' .' + p + 'block-day-strip-cell.is-has .' + p + 'block-day-strip-val {',
    '  color: var(--fg);',
    '  font-weight: 700;',
    '}',
    root + ' .' + p + 'block-day-strip-cell.is-today {',
    '  background: rgba(0, 122, 255, .12);',
    '}',
    root + ' .' + p + 'block-day-strip-cell.is-today .' + p + 'block-day-strip-date {',
    '  color: var(--blue2);',
    '  font-weight: 700;',
    '}',
    root + ' .' + p + 'block-day-strip.is-compact .' + p + 'block-day-strip-val {',
    '  font-size: 12px;',
    '}',
    root + ' .' + p + 'block-day-strip-cap {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: center;',
    '  gap: 10px 16px;',
    '  padding: 10px 13px;',
    '  border-top: 1px solid var(--line);',
    '  background: var(--soft);',
    '  color: var(--fg2);',
    '  font-size: 13px;',
    '}',
    root + ' .' + p + 'block-day-strip-cap-item-ok {',
    '  padding: 2px 9px;',
    '  border-radius: 999px;',
    '  background: rgba(52, 199, 89, .14);',
    '  color: #1a7f4b;',
    '  font-weight: 600;',
    '}',
    root + ' .' + p + 'block-day-strip-cap-item-warn {',
    '  color: #a15a06;',
    '  font-weight: 600;',
    '}',
    root + ' .' + p + 'block-day-strip-cap-item-danger {',
    '  color: #8f2f24;',
    '  font-weight: 600;',
    '}',
    '/* ② 等式条：两段轨道 ＋ 端点读数。 */',
    root + ' .' + p + 'block-equation-bar {',
    '  background: var(--card);',
    '  border: 1px solid var(--line);',
    '  border-radius: ' + 14 + 'px;',
    '  padding: 14px 16px;',
    '}',
    root + ' .' + p + 'block-equation-bar-top {',
    '  display: flex;',
    '  align-items: baseline;',
    '  justify-content: space-between;',
    '  gap: 10px;',
    '  margin-bottom: 10px;',
    '}',
    root + ' .' + p + 'block-equation-bar-label {',
    '  color: var(--fg2);',
    '  font-size: 13px;',
    '  font-weight: 600;',
    '}',
    root + ' .' + p + 'block-equation-bar-value {',
    '  font-size: 19px;',
    '  font-weight: 700;',
    '  font-variant-numeric: tabular-nums;',
    '}',
    root + ' .' + p + 'block-equation-bar-track {',
    '  display: flex;',
    '  height: 14px;',
    '  border-radius: 999px;',
    '  overflow: hidden;',
    '  background: var(--line);',
    '}',
    root + ' .' + p + 'block-equation-bar-seg {',
    '  display: block;',
    '  height: 100%;',
    '}',
    root + ' .' + p + 'block-equation-bar-seg.is-a {',
    '  background: var(--blue);',
    '}',
    root + ' .' + p + 'block-equation-bar-seg.is-b {',
    '  background: #ff9f0a;',
    '}',
    root + ' .' + p + 'block-equation-bar-cap {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  justify-content: space-between;',
    '  gap: 6px 12px;',
    '  margin-top: 8px;',
    '  color: var(--fg2);',
    '  font-size: 12.5px;',
    '  font-variant-numeric: tabular-nums;',
    '}',
    '/* ③ 态声明条：徽标 ＋ 说明（＋ 动作）。语气色与状态徽章同一套语义色。 */',
    root + ' .' + p + 'block-state-banner {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: center;',
    '  gap: 10px;',
    '  padding: 11px 14px;',
    '  border: 1px solid var(--line);',
    '  border-radius: ' + 14 + 'px;',
    '  background: var(--card);',
    '  font-size: 14.5px;',
    '}',
    root + ' .' + p + 'block-state-banner-badge {',
    '  padding: 3px 9px;',
    '  border-radius: 999px;',
    '  font-size: 12px;',
    '  font-weight: 700;',
    '}',
    root + ' .' + p + 'block-state-banner.is-info {',
    '  border-color: rgba(0, 122, 255, .28);',
    '  background: rgba(0, 122, 255, .06);',
    '}',
    root + ' .' + p + 'block-state-banner.is-info .' + p + 'block-state-banner-badge {',
    '  background: rgba(0, 122, 255, .14);',
    '  color: var(--blue2);',
    '}',
    root + ' .' + p + 'block-state-banner.is-warn {',
    '  border-color: rgba(255, 159, 10, .34);',
    '  background: rgba(255, 159, 10, .12);',
    '}',
    root + ' .' + p + 'block-state-banner.is-warn .' + p + 'block-state-banner-badge {',
    '  background: rgba(255, 159, 10, .22);',
    '  color: #a15a06;',
    '}',
    root + ' .' + p + 'block-state-banner.is-danger {',
    '  border-color: rgba(255, 59, 48, .3);',
    '  background: rgba(255, 59, 48, .1);',
    '}',
    root + ' .' + p + 'block-state-banner.is-danger .' + p + 'block-state-banner-badge {',
    '  background: rgba(255, 59, 48, .18);',
    '  color: #8f2f24;',
    '}',
    root + ' .' + p + 'block-state-banner-action {',
    '  margin-left: auto;',
    '  box-sizing: border-box;',
    '  min-height: 44px;',
    '  padding: 0 14px;',
    '  border: 1px solid var(--line);',
    '  border-radius: 999px;',
    '  background: var(--card);',
    '  color: var(--fg);',
    '  font-family: inherit;',
    '  font-size: 13px;',
    '  font-weight: 600;',
    '  cursor: pointer;',
    '}',
    '@media (max-width: 640px) {',
    '  ' + root + ' .' + p + 'block-day-strip-cell {',
    '    padding: 9px 3px 11px;',
    '  }',
    '  ' + root + ' .' + p + 'block-day-strip-date {',
    '    font-size: 12px;',
    // #950 实拍修（真组件验收抓到）：窄档「09-23 今天」这类**调用方给的长日期串**会被格带的
    // `overflow: hidden`（圆角需要它）裁掉半截。这里放开折行：标签在自身格内换行，格子仍等宽等高。
    '    white-space: normal;',
    '    text-align: center;',
    '    line-height: 1.25;',
    '  }',
    '  ' + root + ' .' + p + 'block-day-strip-val {',
    '    font-size: 12px;',
    '  }',
    '}',
  ].join(LF);
}
