/** progress-list · **样式段**（本件唯一的样式来源）。
 *
 *  纪律（与本族其余件同一份）：
 *   · 只经 `skinVar()` 读皮肤 —— 组件里**不写** `var(--ilife-…)`（兜底链只许住在 `skin/contract.ts`）；
 *   · 全部规则 scope 在 `.<prefix>page-ui` 之下（不开本配方的页零命中）；不写 `:root`／`!important`、不新增 token 名；
 *   · **宽度只许容器判**：布局靠 `@container` ＋ 内在尺寸 ＋ `flex-wrap`；媒体查询只判设备能力（本件没用到）。
 *
 *  几何契约（判据钉住）：条高 ＝ `PROGRESS_LIST_TRACK_HEIGHT_PX`；窄容器阈值 ＝ `PROGRESS_LIST_NARROW_PX`。
 *  层次不靠阴影、不靠圆角：行与行之间靠**发丝线**，条靠**轨的底色**与**填充的实色** ⇒ 零阴影皮肤下照样读得出。
 */
import { skinVar } from '../skin/contract.js';
import { progressListSlot, type ProgressListSlot } from './attrs.js';

/** 换行（仓库口径：不写字面换行转义）。 */
const LF = String.fromCharCode(10);

/** 条高（px）：一个数，样式里只写它一处——判据从源码读这个数来对账。 */
export const PROGRESS_LIST_TRACK_HEIGHT_PX = 8;

/** 窄容器阈值（px）：目标名与状态字改走「上下两行」，长目标名不再被状态字挤窄。
 *  **这是本件自己的宽度**（`@container` 判的），不是视口宽度。 */
export const PROGRESS_LIST_NARROW_PX = 360;

/** 本组件的样式段。恒返回非空 CSS 文本。 */
export function progressListCss(input?: { readonly prefix?: string }): string {
  const p = input !== undefined && input !== null
    && typeof input.prefix === 'string' && input.prefix !== '' ? input.prefix : 'ilife-';
  const root = '.' + p + 'page-ui';
  const box = root + ' .' + p + 'block-progress-list';
  /* 两种拼法：`s()` 带 scope（顶层规则用），`slotSel()` 不带（拼接 `.is-ok .…-fill` 这类后代选择器用，
     拼两遍 scope 会得到一个永不匹配的选择器）。 */
  const slotSel = (slot: ProgressListSlot): string => '.' + progressListSlot(slot, p);
  const s = (slot: ProgressListSlot): string => root + ' ' + slotSel(slot);

  return [
    '/* progress-list（多目标进度 · 形态 A「四行清单」）：每行＝目标名＋状态字／当前 / 目标／条／还差多少。',
    '   层次不靠阴影与大圆角（小票纸零阴影、大字报刊零圆角）：靠发丝线、条轨底色与字重 ⇒ 换皮只换取值。 */',
    box + ' {',
    /* 宽度判据的落点：本件是**自己的容器**——嵌进侧栏／面板／卡片时照样按自己的宽度折行。 */
    '  container-type: inline-size;',
    '  display: grid;',
    '  gap: 10px;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-body') + ';',
    '  line-height: 1.5;',
    '}',
    s('heading') + ' {',
    '  margin: 0;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 700;',
    '  letter-spacing: .02em;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 清单：一行一个目标，行间一条发丝线（零阴影下靠它分家）。 */',
    s('list') + ' {',
    '  display: grid;',
    '  gap: 0;',
    '  margin: 0;',
    '  padding: 0;',
    '  min-width: 0;',
    '  list-style: none;',
    '}',
    s('row') + ' {',
    '  display: grid;',
    '  gap: 6px;',
    '  min-width: 0;',
    '  padding: 12px 0;',
    '  border-top: 1px solid ' + skinVar('line') + ';',
    '}',
    s('row') + ':first-child {',
    '  border-top: 0;',
    '  padding-top: 0;',
    '}',
    '/* 行首：目标名 ＋ 状态字（**色不是唯一信息**：这一枚状态字就是第二样）。 */',
    s('top') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 4px 10px;',
    '  margin: 0;',
    '  min-width: 0;',
    '}',
    s('label') + ' {',
    '  flex: 1 1 auto;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-size: ' + skinVar('fs-body') + ';',
    '  font-weight: 700;',
    '  overflow-wrap: anywhere;',
    '}',
    s('state') + ' {',
    '  flex: none;',
    '  margin-left: auto;',
    '  padding: 1px 6px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('surface-2') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 700;',
    '  letter-spacing: .02em;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 当前 / 目标 ＋ 单位：值走大字档（**等宽数字**，多行读数上下对齐）。 */',
    s('meta') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 4px 8px;',
    '  margin: 0;',
    '  min-width: 0;',
    '}',
    s('value') + ' {',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: calc(' + skinVar('fs-body') + ' * 1.35);',
    '  font-weight: 700;',
    '  line-height: 1.15;',
    '  font-variant-numeric: tabular-nums;',
    '  overflow-wrap: anywhere;',
    '}',
    s('goal') + ' {',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-variant-numeric: tabular-nums;',
    '  overflow-wrap: anywhere;',
    '}',
    s('unit') + ' {',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 600;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 条：轨走软底 ＋ 一圈发丝线（**零阴影下的边界**），填充走实色。',
    '   未记录那行宽度是 0，读者看到的是空轨——这就是"还没记"的形状。 */',
    s('track') + ' {',
    '  display: block;',
    '  min-width: 0;',
    '  height: ' + String(PROGRESS_LIST_TRACK_HEIGHT_PX) + 'px;',
    '  box-sizing: border-box;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-pill') + ';',
    '  background: ' + skinVar('surface-2') + ';',
    '  overflow: hidden;',
    '}',
    s('fill') + ' {',
    '  display: block;',
    '  height: 100%;',
    '  border-radius: ' + skinVar('radius-pill') + ';',
    '  background: ' + skinVar('accent') + ';',
    '}',
    '/* 语气只改**取值**：达标走 ok、超了走 warn、危险档走 danger（状态字与条的形状都不变）。 */',
    s('row') + '.is-ok ' + slotSel('fill') + ' { background: ' + skinVar('ok') + '; }',
    s('row') + '.is-warn ' + slotSel('fill') + ' { background: ' + skinVar('warn') + '; }',
    s('row') + '.is-danger ' + slotSel('fill') + ' { background: ' + skinVar('danger') + '; }',
    s('row') + '.is-ok ' + slotSel('state') + ' { color: ' + skinVar('ok') + '; border-color: ' + skinVar('ok') + '; }',
    s('row') + '.is-warn ' + slotSel('state') + ' { color: ' + skinVar('warn') + '; border-color: ' + skinVar('warn') + '; }',
    s('row') + '.is-danger ' + slotSel('state') + ' { color: ' + skinVar('danger') + '; border-color: ' + skinVar('danger') + '; }',
    s('row') + '.is-blank ' + slotSel('value') + ' { color: ' + skinVar('ink-2') + '; }',
    '/* 「还差多少」那一句：本形态的第四段，永远整行独占，不跟条抢宽度。 */',
    s('remain') + ' {',
    '  margin: 0;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 600;',
    '  font-variant-numeric: tabular-nums;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 口径行：这批目标怎么算的（弱文字档，可很长、必须能换行；段间一条发丝线，标记里不写分隔符）。 */',
    s('note') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 4px 8px;',
    '  margin: 0;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1.7;',
    '  overflow-wrap: anywhere;',
    '}',
    s('note') + ' > span {',
    '  padding-left: 8px;',
    '  border-left: 1px solid ' + skinVar('line') + ';',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 本件自身不带可点元素。这一条是**地板**：调用方若把行包成链接或按钮，焦点必须看得见。 */',
    box + ' :focus-visible {',
    '  outline: 2px solid ' + skinVar('accent') + ';',
    '  outline-offset: 2px;',
    '}',
    '/* 窄容器（<' + String(PROGRESS_LIST_NARROW_PX) + 'px）：目标名与状态字改走上下两行，',
    '   长目标名不再被那枚状态字挤成一列孤字。判的是**本件自己的宽度**（本件会被嵌进侧栏／面板／卡片，',
    '   视口宽 ≠ 组件宽，所以这里不写 `@media`）。 */',
    '@container (max-width: ' + String(PROGRESS_LIST_NARROW_PX) + 'px) {',
    '  ' + s('top') + ' {',
    '    display: grid;',
    '    gap: 2px;',
    '  }',
    '  ' + s('state') + ' {',
    '    margin-left: 0;',
    '    justify-self: start;',
    '  }',
    '}',
  ].join(LF);
}
