/** bulk-bar · **条目那一列的样式**（由 `style.ts` 的 `bulkBarCss()` 汇总；搬走的是行数，不是取值）。
 *
 *  为什么在这里：本件的样式段本来一件事——「上面一列可勾的条目 ＋ 底下一条浮出来的操作条」——
 *  写到一起会顶破本包的告警线（350 行）。按**改动的批次**分家：条目列（怎么排一行、勾选框长什么样、
 *  读数怎么摆）与操作条／确认面（浮出、状态矩阵、会改哪几条）是两批会各自改动的东西。
 *
 *  四条纪律与 `style.ts` 同一份：只经 `skinVar()` 读皮肤；全部规则 scope 在 `.<prefix>page-ui` 之下；
 *  不写 `:root`／`!important`／不新增 token 名；**宽度只许容器判**（窄档走 `@container`，本文件不写宽度媒体查询）。
 */
import { skinVar } from '../skin/contract.js';
import { bulkBarSlot, type BulkBarSlot } from './attrs.js';
import { BULK_BAR_BOX_PX, BULK_BAR_MIN_TARGET_PX, BULK_BAR_ROW_MIN_HEIGHT_PX } from './style-sizes.js';

/** 换行（仓库口径：不写字面换行转义）。 */
const LF = String.fromCharCode(10);

/** 条目列那一段样式。恒返回非空 CSS 文本。 */
export function bulkBarColumnCss(input?: { readonly prefix?: string }): string {
  const p = input !== undefined && input !== null
    && typeof input.prefix === 'string' && input.prefix !== '' ? input.prefix : 'ilife-';
  const root = '.' + p + 'page-ui';
  const box = root + ' .' + p + 'block-bulk-bar';
  /** **槽类名**（不带 scope）：只用在已经落进本件某条选择器内部的位置。 */
  const c = (slot: BulkBarSlot): string => '.' + bulkBarSlot(slot, p);
  /** **带 scope 的完整选择器**：点只许由 `c()` 出（漏点＝「找一个叫 `<件>-<槽>` 的元素」的死规则）。 */
  const s = (slot: BulkBarSlot): string => root + ' ' + c(slot);

  return [
    '/* bulk-bar（批量操作条 · 形态 A「选中后浮出来的操作条（底部）」）：条目列 ＋ 选中 ≥1 条时浮出的操作条。',
    '   层次不靠阴影与大圆角：靠发丝线、底色块与字重差 ⇒ 换皮只换取值。 */',
    box + ' {',
    /* 宽度判据的落点：本件是**自己的容器**——嵌进侧栏／面板／卡片时照样按自己的宽度排。 */
    '  container-type: inline-size;',
    '  box-sizing: border-box;',
    '  display: grid;',
    /* 单列 grid **一律写死 `minmax(0, 1fr)`**：不写的话隐式 `auto` 轨会被最长的一段文字顶宽，
       整个件被自己的内容撑出容器（真机上就是横向溢出）。 */
    '  grid-template-columns: minmax(0, 1fr);',
    '  gap: 0;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-body') + ';',
    '  line-height: 1.5;',
    '}',
    /* 宿主页不保证是 `border-box`（真页面默认 content-box）：在本件**自己的子树里**钉死，
       否则「输入框 `width:100%` ＋ 1px 边框」这类组合会比容器宽出边框那两像素。 */
    box + ' * {',
    '  box-sizing: inherit;',
    '}',
    s('host') + ' {',
    /* **不写 `overflow:hidden`**：写了的那个盒子会成为 `sticky` 的滚动容器，条就再也粘不到视口底部。 */
    '  display: grid;',
    '  grid-template-columns: minmax(0, 1fr);',
    '  gap: 0;',
    '  min-width: 0;',
    '}',
    '/* 条目那一列：纸面 ＋ 发丝线（圆角靠这一层裁一次，行的高亮才不出角）。 */',
    s('list') + ' {',
    '  display: grid;',
    '  grid-template-columns: minmax(0, 1fr);',
    '  min-width: 0;',
    '  background: ' + skinVar('surface') + ';',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius') + ';',
    '  overflow: hidden;',
    '}',
    '/* 一行：勾选框（命中盒 44×44）‖ 主字与副语 ‖ 右端读数。**整行是 `<label>`＝命中区**。',
    '   三块走 flex ＋ `flex-wrap`：读数按内容宽排（`flex:0 1 auto`），但**最多占 45%**',
    '   （`max-width`）——不设这个上限的话，一串超长读数会把主字挤成一列孤字；',
    '   反过来主字也不设上限，位置不够时两块各让一步、各自折行（永不 `…` 截断）。 */',
    s('row') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: center;',
    '  gap: 4px 10px;',
    '  min-height: ' + String(BULK_BAR_ROW_MIN_HEIGHT_PX) + 'px;',
    '  min-width: 0;',
    '  padding: 4px 12px 4px 2px;',
    '  border-top: 1px solid ' + skinVar('line') + ';',
    '  cursor: pointer;',
    '}',
    s('row') + ':first-child {',
    '  border-top: 0;',
    '}',
    '/* 整行选中（四档口径里的「整行／整块选中」）：底 `surface-2` ＋ 左端 2px 强调侧标；行内主字仍 `ink`。 */',
    s('row') + '.is-on {',
    '  background: ' + skinVar('surface-2') + ';',
    '  box-shadow: inset 2px 0 0 ' + skinVar('accent') + ';',
    '}',
    '/* 勾不动的那一行：光标给出来，原因由 `-why` 那行字写着（不只染色）。 */',
    s('row') + '.is-off {',
    '  cursor: not-allowed;',
    '  color: ' + skinVar('ink-3') + ';',
    '}',
    s('check') + ' {',
    '  position: relative;',
    '  flex: none;',
    '  display: grid;',
    '  place-items: center;',
    '  width: ' + String(BULK_BAR_MIN_TARGET_PX) + 'px;',
    '  height: ' + String(BULK_BAR_MIN_TARGET_PX) + 'px;',
    '}',
    '/* 原生框铺满 44×44 命中盒：视觉隐藏走 `opacity:0`，**不是** `display:none`',
    '   （那会把键盘可达性一并干掉；`:focus-visible` 的环改画在旁边那枚视觉盒上）。 */',
    s('check') + ' input {',
    '  position: absolute;',
    '  inset: 0;',
    '  width: 100%;',
    '  height: 100%;',
    '  margin: 0;',
    '  opacity: 0;',
    '  cursor: pointer;',
    '}',
    s('check') + ' input:disabled {',
    '  cursor: not-allowed;',
    '}',
    s('box') + ' {',
    '  display: grid;',
    '  place-items: center;',
    '  width: ' + String(BULK_BAR_BOX_PX) + 'px;',
    '  height: ' + String(BULK_BAR_BOX_PX) + 'px;',
    '  border: 2px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('surface') + ';',
    '}',
    '/* 勾上（无文字的格那一档）：`accent` 实底 ＋ 一枚对钩（勾＝图形，才许放实底上）。 */',
    s('check') + ' input:checked + ' + c('box') + ' {',
    '  background: ' + skinVar('accent') + ';',
    '  border-color: ' + skinVar('accent') + ';',
    '}',
    s('check') + ' input:checked + ' + c('box') + '::after {',
    '  content: "✓";',
    '  color: ' + skinVar('accent-ink') + ';',
    '  font-size: 15px;',
    '  font-weight: 700;',
    '  line-height: 1;',
    '}',
    s('check') + ' input:focus-visible + ' + c('box') + ' {',
    '  outline: 2px solid ' + skinVar('accent') + ';',
    '  outline-offset: 2px;',
    '}',
    s('text') + ' {',
    /* 主字那一块**可以长到把整行占满**（可缩）：读数被挤时它会先让位。 */
    '  flex: 1 1 auto;',
    '  display: block;',
    '  min-width: 0;',
    '}',
    s('name') + ' {',
    '  display: block;',
    '  color: inherit;',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 600;',
    '  overflow-wrap: anywhere;',
    '}',
    s('note') + ' {',
    '  display: block;',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-style: normal;',
    '  overflow-wrap: anywhere;',
    '}',
    s('why') + ' {',
    '  display: block;',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-style: normal;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 行右端的读数（金额／条数）：等宽数字、**永不 `…` 截断**（位置不够就折行）。',
    '   宽到最多 45% —— 上限不是为了省地方，是为了**别把主字挤成一列孤字**。 */',
    s('reading') + ' {',
    '  flex: 0 1 auto;',
    '  min-width: 0;',
    '  max-width: 45%;',
    '  margin-left: auto;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-variant-numeric: tabular-nums;',
    '  font-weight: 700;',
    '  text-align: right;',
    '  overflow-wrap: anywhere;',
    '}',
    s('empty') + ' {',
    '  margin: 0;',
    '  padding: 18px 14px;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  text-align: center;',
    '  overflow-wrap: anywhere;',
    '}',
  ].join(LF);
}
