/** bulk-bar · **就地确认面那一段样式**（由 `style.ts` 的 `bulkBarCss()` 汇总；搬走的是行数，不是取值）。
 *
 *  为什么在这里：B 档「抽屉式批量编辑」不落，但**「改之前能看见会改哪几条」这一层信息必须留住**——
 *  它落在 A 档的**条内就地确认面**上（原型的 `.c-bulk-edit` 那张卡的配方：头 ／ 改成什么 ／ 逐条预演 ／ 页脚）。
 *  它不是浮层、不是抽屉：跟着操作条一起在流内粘在底部，窄档铺满、逐条折行。
 *
 *  三条硬口径（判据断）：
 *   · **形 ＋ 字 ＋ 色**三样都在：「会改」＝`✓`（形）＋ 右端那两个字（字）＋ 底色；跳过的同理（`⊘`／`跳过`）；
 *   · **触控地板**：输入框与胶囊 ≥44px 高，相邻间距 8px，预演一行 ≥44px；
 *   · **不截断**：长值／长说明一律 `overflow-wrap:anywhere` 折行，任何一处都没有省略号。
 *
 *  窄档阈值**只读 `style-sizes.ts`**（铁律二：概念只有一处；本文件先前自己又写了一份 `560`，
 *  两边各改一次必然走散）。
 */
import { skinVar } from '../skin/contract.js';
import { bulkBarSlot, type BulkBarSlot } from './attrs.js';
import { BULK_BAR_NARROW_PX } from './style-sizes.js';

/** 换行（仓库口径：不写字面换行转义）。 */
const LF = String.fromCharCode(10);
/** 预演行左端那枚记号的列宽（px）。 */
const MARK_COL_PX = 20;

/** 确认面那一段样式。恒返回非空 CSS 文本。 */
export function bulkBarConfirmCss(input?: { readonly prefix?: string }): string {
  const p = input !== undefined && input !== null
    && typeof input.prefix === 'string' && input.prefix !== '' ? input.prefix : 'ilife-';
  const root = '.' + p + 'page-ui';
  const c = (slot: BulkBarSlot): string => '.' + bulkBarSlot(slot, p);
  /** 带 scope 的完整选择器（点只许由 `c()` 出：漏点会拼成「找一个叫 `<件>-<槽>` 的元素」的死规则）。 */
  const s = (slot: BulkBarSlot): string => root + ' ' + c(slot);

  return [
    '/* ── 就地确认面（改之前先看见会改哪几条）───────────────────────────── */',
    s('confirm') + ' {',
    '  display: grid;',
    '  grid-template-columns: minmax(0, 1fr);',
    '  min-width: 0;',
    '  margin-top: 8px;',
    '  background: ' + skinVar('surface') + ';',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  overflow: hidden;',
    '}',
    '/* 同上：`display:grid` 会压过 UA 的 `[hidden]{display:none}` ⇒ 显式重写。 */',
    s('confirm') + '[hidden] {',
    '  display: none;',
    '}',
    s('chead') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 4px 10px;',
    '  min-width: 0;',
    '  padding: 10px 12px;',
    '  background: ' + skinVar('surface-2') + ';',
    '  border-bottom: 1px solid ' + skinVar('line') + ';',
    '}',
    s('ctitle') + ' {',
    '  color: ' + skinVar('ink') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 700;',
    '  overflow-wrap: anywhere;',
    '}',
    s('ccap') + ' {',
    '  margin-left: auto;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '  overflow-wrap: anywhere;',
    '}',
    s('cbody') + ' {',
    '  display: grid;',
    '  grid-template-columns: minmax(0, 1fr);',
    '  gap: 10px;',
    '  min-width: 0;',
    '  padding: 12px;',
    '}',
    '/* 「改成」那一格：标签 ＋ 输入框并成一块命中区（点标签也能把光标送进框里）。 */',
    s('value') + ' {',
    '  display: grid;',
    '  grid-template-columns: minmax(0, 1fr);',
    '  gap: 4px;',
    '  min-width: 0;',
    '}',
    s('vlabel') + ' {',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 600;',
    '}',
    s('input') + ' {',
    '  width: 100%;',
    '  min-height: 44px;',
    '  min-width: 0;',
    '  padding: 0 12px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('ground') + ';',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '}',
    s('recent') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: center;',
    '  gap: 8px;',
    '  min-width: 0;',
    '}',
    s('rlabel') + ' {',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '}',
    '/* 「最近用过」那几枚胶囊：点它＝把它的字填进输入框（比让人重新敲一遍快）。 */',
    s('chip') + ' {',
    '  min-width: 44px;',
    '  min-height: 44px;',
    '  max-width: 100%;',
    '  padding: 6px 14px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-pill') + ';',
    '  background: ' + skinVar('surface-2') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '  cursor: pointer;',
    '  transition: transform 80ms linear;',
    '  overflow-wrap: anywhere;',
    '}',
    '@media (hover:hover) and (pointer:fine) {',
    '  ' + s('chip') + ':hover {',
    '    border-color: ' + skinVar('accent') + ';',
    '    color: ' + skinVar('accent-text') + ';',
    '  }',
    '}',
    s('chip') + ':active {',
    '  transform: scale(.98);',
    '}',
    '/* ── 逐条预演：`✓ 会改` / `⊘ 跳过` ＋ 旧值删除线 ＋ 右端那两个字 ─────── */',
    s('preview') + ' {',
    '  display: grid;',
    '  grid-template-columns: minmax(0, 1fr);',
    '  min-width: 0;',
    '  border-top: 1px solid ' + skinVar('line') + ';',
    '}',
    s('prow') + ' {',
    '  display: grid;',
    '  grid-template-columns: ' + String(MARK_COL_PX) + 'px minmax(0, 1fr) auto;',
    '  align-items: center;',
    '  gap: 4px 10px;',
    '  min-height: 44px;',
    '  min-width: 0;',
    '  margin: 0;',
    '  padding: 6px 12px;',
    '  border-top: 1px solid ' + skinVar('line') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '}',
    s('prow') + ':first-child {',
    '  border-top: 0;',
    '}',
    '/* 会改那一行：`ok` 是「达标／正常」那一档；跳过那一行整体压到弱字（它不是错误，**不借 danger**）。 */',
    s('mark') + ' {',
    '  color: ' + skinVar('ok') + ';',
    '  font-weight: 700;',
    '  text-align: center;',
    '}',
    s('prow') + '.is-skip {',
    '  color: ' + skinVar('ink-2') + ';',
    '}',
    s('prow') + '.is-skip ' + c('mark') + ' {',
    '  color: ' + skinVar('ink-2') + ';',
    '}',
    s('old') + ' {',
    '  color: ' + skinVar('ink-3') + ';',
    '  text-decoration: line-through;',
    '  overflow-wrap: anywhere;',
    '}',
    s('arrow') + ' {',
    '  padding: 0 4px;',
    '  color: ' + skinVar('ink-3') + ';',
    '}',
    s('next') + ' {',
    '  font-weight: 700;',
    '  overflow-wrap: anywhere;',
    '}',
    s('pnote') + ' {',
    '  padding-left: 6px;',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 右端那两个字是状态的**字**那一重（色只是第三重：换皮不靠色也读得出）。 */',
    s('pstate') + ' {',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-style: normal;',
    '  font-weight: 600;',
    '}',
    '/* ── 页脚：结论句 ＋ 取消 ＋ 改这 N 条 ─────────────────────────────── */',
    s('cfoot') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: center;',
    '  gap: 8px;',
    '  min-width: 0;',
    '  padding: 10px 12px;',
    '  background: ' + skinVar('surface-2') + ';',
    '  border-top: 1px solid ' + skinVar('line') + ';',
    '}',
    s('sum') + ' {',
    '  flex: 1 1 auto;',
    '  min-width: 0;',
    '  margin-right: auto;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '  overflow-wrap: anywhere;',
    '}',
    '@container (max-width: ' + String(BULK_BAR_NARROW_PX) + 'px) {',
    '  /* 窄档：标题右端那句另起一行（挤在标题右边会把标题压成两三个字一列）。 */',
    '  ' + s('ccap') + ' {',
    '    margin-left: 0;',
    '    flex: 1 1 100%;',
    '  }',
    '  /* 页脚两枚按钮铺满整行、等分（手指好按）。 */',
    '  ' + s('cfoot') + ' > ' + c('act') + ' {',
    '    flex: 1 1 auto;',
    '  }',
    '}',
    '@media (prefers-reduced-motion: reduce) {',
    '  ' + s('chip') + ' {',
    '    transition: none;',
    '  }',
    '}',
  ].join(LF);
}
