/** photo-compare · **样式段**（本件唯一的样式来源）。**重做件**：拖动之外还要给得出「变了多少」。
 *
 *  四条重做口径（`重做设计口径.md` §0）逐条落在这一段里：
 *   ① **占位物读得出它是什么**：定形框（`aspect-ratio`）＋ 四角取景角标 ＋ 中央相机记号 ＋ 题注条；
 *   ② **状态除色之外还有第二样**：差值行有**方向记号（↓／↑／＝）**与**正负号**，颜色只是第三样；
 *   ③ **层次不靠投影与圆角**：台面靠一圈发丝线，题注条靠软底色，差值行靠**发丝线 ＋ 缩进**；
 *   ④ **骨架对得上这类数据**：`<figure>` 装照片、`<ul>` 装差值行（一件就是「两张图 ＋ N 行差值」）。
 *
 *  两档是**同一份标记**：宽档两张叠着（`grid-area: 1/1` ＋ 裁切），窄档同一对 `<figure>` 左右并排，
 *  拖动条收起、差值条上屏。判的是**本件自己的宽度**（`@container`），不是视口宽度。
 *
 *  纪律：只经 `skinVar()` 读皮肤；scope 在 `.<prefix>page-ui` 之下；零 `:root`／`!important`；
 *  媒体查询只判设备能力（`hover`／`prefers-reduced-motion`）。
 */
import { skinVar } from '../skin/contract.js';
import {
  PHOTO_COMPARE_MIN_HIT_PX,
  PHOTO_COMPARE_SPLIT_VAR,
  photoCompareSlot,
  type PhotoCompareSlot,
} from './attrs.js';

/** 换行（仓库口径：不写字面换行转义）。 */
const LF = String.fromCharCode(10);

/** 取景角标的臂长／线宽／内距（px，与 `photo-grid` 同一套做法：占位要读得出是相片）。 */
export const PHOTO_COMPARE_MARK_ARM_PX = 12;
export const PHOTO_COMPARE_MARK_THICK_PX = 2;
export const PHOTO_COMPARE_MARK_INSET_PX = 6;

/** 窄容器阈值（px）：宽于它两张叠着拖，窄于它退成左右并排 ＋ 差值条。 */
export const PHOTO_COMPARE_NARROW_PX = 520;

/** 台面比例与高度上限（宽档用：盒先定形，图到位不跳版；高度封顶免得一张竖版照片占满屏）。 */
export const PHOTO_COMPARE_STAGE_RATIO = '4 / 3';
export const PHOTO_COMPARE_STAGE_MAX_PX = 460;

/** 四角取景角标：8 层背景（每角一横一竖），不加元素、不用伪元素。 */
function marksCss(): string[] {
  const color = skinVar('line');
  const bar = 'linear-gradient(' + color + ', ' + color + ')';
  const arm = String(PHOTO_COMPARE_MARK_ARM_PX) + 'px';
  const thick = String(PHOTO_COMPARE_MARK_THICK_PX) + 'px';
  const inset = String(PHOTO_COMPARE_MARK_INSET_PX) + 'px';
  const right = 'calc(100% - ' + inset + ')';
  const bottom = 'calc(100% - ' + inset + ')';
  const pos: string[] = [];
  for (const [y, x] of [[inset, inset], [inset, right], [bottom, inset], [bottom, right]]) {
    pos.push(x + ' ' + y, x + ' ' + y);
  }
  const size = [arm + ' ' + thick, thick + ' ' + arm].join(', ');
  return [
    '  background-image: ' + new Array(8).fill(bar).join(', ') + ';',
    '  background-size: ' + new Array(4).fill(size).join(', ') + ';',
    '  background-position: ' + pos.join(', ') + ';',
    '  background-repeat: no-repeat;',
  ];
}

/** 本组件的样式段。恒返回非空 CSS 文本。 */
export function photoCompareCss(input?: { readonly prefix?: string }): string {
  const p = input !== undefined && input !== null
    && typeof input.prefix === 'string' && input.prefix !== '' ? input.prefix : 'ilife-';
  const root = '.' + p + 'page-ui';
  const box = root + ' .' + p + 'block-photo-compare';
  const slotSel = (s: PhotoCompareSlot): string => '.' + photoCompareSlot(s, p);
  const s = (slot: PhotoCompareSlot): string => root + ' ' + slotSel(slot);
  const split = 'var(' + PHOTO_COMPARE_SPLIT_VAR + ', 50%)';

  const out: string[] = [
    '/* photo-compare（前后对比 · 形态 A「拖动对照」）：两张叠着拖 ＋ 两张的日期标签 ＋ 数值差值行。',
    '   **重做件**：原型只给拖动，读者读不出「变了多少」——差值行就是补上的那个读数。',
    '   零阴影、零圆角下层次靠发丝线、软底色与裁切边 ⇒ 三套皮肤都成立。 */',
    box + ' {',
    '  container-type: inline-size;',
    '  display: grid;',
    '  gap: 12px;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-body') + ';',
    '  line-height: 1.5;',
    '}',
    '/* 台面：盒先定形（`aspect-ratio` ＋ 高度上限），图到位不跳版；两张 `<figure>` 落在同一格里叠着。 */',
    s('stage') + ' {',
    '  position: relative;',
    '  display: grid;',
    '  grid-template-columns: minmax(0, 1fr);',
    '  gap: 0;',
    '  aspect-ratio: ' + PHOTO_COMPARE_STAGE_RATIO + ';',
    '  max-height: ' + String(PHOTO_COMPARE_STAGE_MAX_PX) + 'px;',
    '  min-width: 0;',
    '  box-sizing: border-box;',
    '  border: 1px solid ' + skinVar('edge') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('surface-2') + ';',
    '  overflow: hidden;',
    '}',
    '/* 两张：宽档**同一格**（后一张压在先一张上面，从左边裁开）；窄档改并排（见文末那段）。 */',
    s('layer') + ' {',
    '  position: relative;',
    '  grid-area: 1 / 1;',
    '  display: grid;',
    '  grid-template-rows: minmax(0, 1fr) auto;',
    '  gap: 0;',
    '  min-width: 0;',
    '  height: 100%;',
    '  margin: 0;',
    '}',
    s('layer') + '.is-after {',
    '  clip-path: inset(0 0 0 ' + split + ');',
    '}',
    '/* 定形框：宽档铺满台面那一格（图 `object-fit: cover`），窄档由自己的比例定形。',
    '   注意这一档要把比例**让开**（`aspect-ratio: auto`）：台面的盒已经定过形了，',
    '   框再按 4/5 撑一遍会把整层顶到 613×766，题注条被台面的 `overflow: hidden` 裁掉（重做时踩过）。 */',
    s('frame') + ' {',
    '  position: relative;',
    '  display: grid;',
    '  place-items: center;',
    '  width: 100%;',
    '  height: 100%;',
    '  min-width: 0;',
    '  min-height: 0;',
    '  box-sizing: border-box;',
    '  overflow: hidden;',
    '  background: ' + skinVar('surface') + ';',
    '}',
    root + ' .' + photoCompareSlot('frame', p) + '-4-5 { aspect-ratio: 4 / 5; }',
    root + ' .' + photoCompareSlot('layer', p) + ' > .' + photoCompareSlot('frame', p) + ' { aspect-ratio: auto; }',
    '/* ④ 四角取景角标 ＋ 相机记号：没真图时一眼看出「这里放一张照片」。 */',
    s('marks') + ' {',
    '  position: absolute;',
    '  inset: 0;',
    '  pointer-events: none;',
    ...marksCss(),
    '}',
    s('lens') + ' {',
    '  position: relative;',
    '  grid-area: 1 / 1;',
    '  align-self: end;',
    '  margin-bottom: 6px;',
    '  width: 34px;',
    '  height: 26px;',
    '  box-sizing: border-box;',
    '  border: ' + String(PHOTO_COMPARE_MARK_THICK_PX) + 'px solid ' + skinVar('ink-2') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '}',
    s('lens') + '::before {',
    '  content: "";',
    '  position: absolute;',
    '  left: 50%;',
    '  top: 50%;',
    '  width: 10px;',
    '  height: 10px;',
    '  margin: -6px 0 0 -6px;',
    '  box-sizing: border-box;',
    '  border: ' + String(PHOTO_COMPARE_MARK_THICK_PX) + 'px solid ' + skinVar('ink-2') + ';',
    '  border-radius: 50%;',
    '}',
    s('alt') + ' {',
    '  grid-area: 2 / 1;',
    '  align-self: start;',
    '  justify-self: center;',
    '  max-width: 100%;',
    '  padding: 0 10px;',
    '  box-sizing: border-box;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 700;',
    '  text-align: center;',
    '  overflow-wrap: anywhere;',
    '}',
    s('img') + ' {',
    '  display: block;',
    '  grid-area: 1 / 1;',
    '  width: 100%;',
    '  height: 100%;',
    '  max-width: 100%;',
    '  object-fit: cover;',
    '}',
    '/* **日期标签**（左／右角）：各自贴在自己那张上——这是「哪天比哪天」的第一处落点。 */',
    s('tag') + ' {',
    '  position: absolute;',
    '  top: ' + String(PHOTO_COMPARE_MARK_INSET_PX) + 'px;',
    '  z-index: 3;',
    '  padding: 2px 9px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 700;',
    '  font-variant-numeric: tabular-nums;',
    '}',
    s('layer') + '.is-before ' + slotSel('tag') + ' { left: ' + String(PHOTO_COMPARE_MARK_INSET_PX) + 'px; }',
    s('layer') + '.is-after ' + slotSel('tag') + ' { right: ' + String(PHOTO_COMPARE_MARK_INSET_PX) + 'px; }',
    '/* 占位格上那枚相机记号与那句「放什么」：**各自贴着自己那张的可见半边**——',
    '   宽档两张叠着，居中的话两个记号会在裁切线上撞成一团（后一张只露右半边）。 */',
    s('layer') + '.is-before ' + slotSel('lens') + ', ' + s('layer') + '.is-before ' + slotSel('alt') + ' { justify-self: start; }',
    s('layer') + '.is-after ' + slotSel('lens') + ', ' + s('layer') + '.is-after ' + slotSel('alt') + ' { justify-self: end; }',
    s('layer') + '.is-after ' + slotSel('alt') + ' { text-align: right; }',
    '/* 题注条：框下那一行（位置／朝向 ＋ 读数）。后一张靠右对齐——它被从左边裁开，',
    '   靠左的字会落在裁掉的那半边里（正是重做时最容易漏的一处）。 */',
    s('caption') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 2px 8px;',
    '  min-width: 0;',
    '  padding: 5px 9px;',
    '  box-sizing: border-box;',
    '  border-top: 1px solid ' + skinVar('line') + ';',
    '  background: ' + skinVar('surface-2') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '}',
    s('layer') + '.is-after ' + slotSel('caption') + ' { justify-content: flex-end; }',
    s('text') + ' { overflow-wrap: anywhere; }',
    s('size') + ' {',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-variant-numeric: tabular-nums;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 中间那根竖线：位置只从 `--photo-compare-split` 算（一个事实一处存）。 */',
    s('divider') + ' {',
    '  position: absolute;',
    '  top: 0;',
    '  bottom: 0;',
    '  left: ' + split + ';',
    '  width: 2px;',
    '  margin-left: -1px;',
    '  background: ' + skinVar('accent') + ';',
    '  pointer-events: none;',
    '}',
    '/* 拖动条：**原生 `range`**（键盘 ←／→ 各一档、指针与触摸都交给原生）；',
    '   命中盒铺满台面（≫44×44），把手本体 44×44 透明圆、里面画一枚 22px 的可见把手。 */',
    s('range') + ' {',
    '  position: absolute;',
    '  inset: 0;',
    '  z-index: 4;',
    '  width: 100%;',
    '  height: 100%;',
    '  min-height: ' + String(PHOTO_COMPARE_MIN_HIT_PX) + 'px;',
    '  margin: 0;',
    '  padding: 0;',
    '  border: 0;',
    '  background: none;',
    '  cursor: ew-resize;',
    '  -webkit-appearance: none;',
    '  appearance: none;',
    '}',
    s('range') + '::-webkit-slider-runnable-track {',
    '  height: 3px;',
    '  border-radius: ' + skinVar('radius-pill') + ';',
    '  background: ' + skinVar('line') + ';',
    '}',
    s('range') + '::-webkit-slider-thumb {',
    '  -webkit-appearance: none;',
    '  appearance: none;',
    '  width: ' + String(PHOTO_COMPARE_MIN_HIT_PX) + 'px;',
    '  height: ' + String(PHOTO_COMPARE_MIN_HIT_PX) + 'px;',
    '  margin-top: -' + String(Math.round(PHOTO_COMPARE_MIN_HIT_PX / 2)) + 'px;',
    '  border: 0;',
    '  border-radius: 50%;',
    '  background-color: transparent;',
    '  background-image: radial-gradient(circle at 50% 50%, '
      + skinVar('surface') + ' 0 9px, ' + skinVar('accent') + ' 9px 12px, transparent 12px);',
    '}',
    s('range') + '::-moz-range-track {',
    '  height: 3px;',
    '  border-radius: ' + skinVar('radius-pill') + ';',
    '  background: ' + skinVar('line') + ';',
    '}',
    s('range') + '::-moz-range-thumb {',
    '  width: ' + String(PHOTO_COMPARE_MIN_HIT_PX) + 'px;',
    '  height: ' + String(PHOTO_COMPARE_MIN_HIT_PX) + 'px;',
    '  border: 0;',
    '  border-radius: 50%;',
    '  background-color: transparent;',
    '  background-image: radial-gradient(circle at 50% 50%, '
      + skinVar('surface') + ' 0 9px, ' + skinVar('accent') + ' 9px 12px, transparent 12px);',
    '}',
    s('range') + ':focus-visible {',
    '  outline: 2px solid ' + skinVar('accent') + ';',
    '  outline-offset: 2px;',
    '}',
    '/* **数值差值行**：这一件重做补上的那个读数（拖动读不出「变了多少」）。 */',
    s('deltas') + ' {',
    '  display: grid;',
    '  gap: 0;',
    '  margin: 0;',
    '  padding: 0;',
    '  min-width: 0;',
    '  list-style: none;',
    '}',
    s('delta') + ' {',
    '  display: grid;',
    '  grid-template-columns: auto minmax(0, 1fr) auto;',
    '  gap: 2px 10px;',
    '  min-width: 0;',
    '  padding: 8px 0;',
    '  border-top: 1px solid ' + skinVar('line') + ';',
    '  align-items: baseline;',
    '}',
    s('delta-mark') + ' {',
    '  grid-column: 1;',
    '  grid-row: 1;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-weight: 700;',
    '}',
    s('delta-label') + ' {',
    '  grid-column: 2;',
    '  grid-row: 1;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  overflow-wrap: anywhere;',
    '}',
    s('delta-value') + ' {',
    '  grid-column: 3;',
    '  grid-row: 1;',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 0 6px;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 700;',
    '  font-variant-numeric: tabular-nums;',
    '}',
    s('delta-arrow') + ' {',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-weight: 600;',
    '}',
    '/* 「变了多少」：**正负号 ＋ 方向记号 ＋ 色**三样齐全（色只是第三样）。 */',
    s('delta-change') + ' {',
    '  grid-column: 2 / 4;',
    '  grid-row: 2;',
    '  min-width: 0;',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 700;',
    '  font-variant-numeric: tabular-nums;',
    '  overflow-wrap: anywhere;',
    '}',
    s('delta') + '.is-down ' + slotSel('delta-change') + ' { color: ' + skinVar('ok') + '; }',
    s('delta') + '.is-up ' + slotSel('delta-change') + ' { color: ' + skinVar('danger') + '; }',
    s('delta') + '.is-same ' + slotSel('delta-change') + ' { color: ' + skinVar('ink-2') + '; }',
    '/* 差值条：**窄档才上屏**（宽档已有差值行，同一件事不说两遍）。 */',
    s('verdict') + ' {',
    '  display: none;',
    '  margin: 0;',
    '  padding: 8px 10px;',
    '  box-sizing: border-box;',
    '  border-left: 3px solid ' + skinVar('accent') + ';',
    '  background: ' + skinVar('surface-2') + ';',
    '  color: ' + skinVar('ink') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 700;',
    '  overflow-wrap: anywhere;',
    '}',
    s('note') + ' {',
    '  margin: 0;',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1.7;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 窄容器（<' + String(PHOTO_COMPARE_NARROW_PX) + 'px）：拖动退成**左右并排两张 ＋ 差值条**',
    '   （不许变成没法用的小滑块）：同一对 `<figure>` 改并排、裁切撤掉、拖动条收起。 */',
    '@container (max-width: ' + String(PHOTO_COMPARE_NARROW_PX) + 'px) {',
    '  ' + s('stage') + ' {',
    '    grid-template-columns: repeat(2, minmax(0, 1fr));',
    '    gap: 10px;',
    '    aspect-ratio: auto;',
    '    max-height: none;',
    '    padding: 10px;',
    '    align-items: start;',
    '  }',
    '  ' + s('layer') + ' {',
    '    grid-area: auto;',
    '    grid-template-rows: auto auto;',
    '    clip-path: none;',
    '    height: auto;',
    '    gap: 6px;',
    '  }',
    '  /* 窄档两张并排：比例回到框自己身上（台面这一档不再给形状）。 */',
    '  ' + s('layer') + ' > ' + slotSel('frame') + ', ' + s('frame') + ' { aspect-ratio: 4 / 5; }',
    '  ' + s('layer') + '.is-after ' + slotSel('caption') + ' { justify-content: flex-start; }',
    '  /* 窄档两张各占一格：记号与那句「放什么」回到各自那格的正中（不再让位给裁切线）。 */',
    '  ' + s('lens') + ', ' + s('alt') + ' {',
    '    justify-self: center;',
    '    text-align: center;',
    '  }',
    '  ' + s('frame') + ' { height: auto; border: 1px solid ' + skinVar('edge') + '; }',
    '  ' + s('divider') + ', ' + s('range') + ' { display: none; }',
    '  ' + s('verdict') + ' { display: block; }',
    '}',
    '/* 这一段里**没有任何 `transition`／`animation`／`@keyframes`**：拖动是直接操作，不做补间，',
    '   所以「减动效」这档下也没有东西会卡在半路（判据直接断这一段里零动效）。 */',
  ];
  return out.join(LF);
}
