/** sync-status · **样式段**（本件唯一的样式来源）。
 *
 *  纪律（与本层其余件同一份）：
 *   · 只经 `skinVar()` 读皮肤 —— 组件里**不写** `var(--ilife-…)`（兜底链只许住在 `skin/contract.ts`）；
 *   · 全部规则 scope 在 `.<prefix>page-ui` 之下；不写 `:root`／`!important`、不新增 token 名；
 *   · **宽度只许容器判**：`@container` ＋ 内在尺寸 ＋ `flex-wrap`；媒体查询只判设备能力
 *     （`@media (hover:hover) and (pointer:fine)` 与 `(prefers-reduced-motion:reduce)`）。
 *
 *  交互状态矩阵（判据逐条断；按钮本体见文末那一段）：
 *   rest／`:hover`（包在 hover 能力查询里，且**不是唯一通路**：静止态也写清了「按下去会怎样」）／
 *   `:active`（`scale(.98)`，80ms）／`:focus-visible`（2px 可见焦点）／`:disabled`（`not-allowed` ＋ 字换「同步中…」）／
 *   `running`（原地换字、**宽度锁住**：两枚字占同一格）／`error`（写在控件旁边 ＋ 描述关系）／`empty`（空态）。
 *
 *  零阴影下层次：行间发丝线、失败行靠**左竖条 ＋ 软底**、按钮靠**一圈发丝线** ⇒ 三套皮肤都成立。
 */
import { skinVar } from '../skin/contract.js';
import { syncStatusSlot, type SyncStatusSlot } from './attrs.js';

/** 换行（仓库口径：不写字面换行转义）。 */
const LF = String.fromCharCode(10);

/** 触控目标下限（px）：按钮的**命中盒**不得小于它（视觉盒可以小，命中盒必须够）。 */
export const SYNC_STATUS_TOUCH_PX = 44;

/** 窄容器阈值（px）：名字／时间／徽标由「一行三列」改走「上下两行」。
 *  **这是本件自己的宽度**（`@container` 判的），不是视口宽度。 */
export const SYNC_STATUS_NARROW_PX = 520;

/** 本组件的样式段。恒返回非空 CSS 文本。 */
export function syncStatusCss(input?: { readonly prefix?: string }): string {
  const p = input !== undefined && input !== null
    && typeof input.prefix === 'string' && input.prefix !== '' ? input.prefix : 'ilife-';
  const root = '.' + p + 'page-ui';
  const box = root + ' .' + p + 'block-sync-status';
  const slotSel = (s: SyncStatusSlot): string => '.' + syncStatusSlot(s, p);
  const s = (slot: SyncStatusSlot): string => root + ' ' + slotSel(slot);
  const running = box + '[data-ilife-sync-state="running"] ';

  return [
    '/* sync-status（同步状态 · 形态 B「带『同步一次』动作」）：汇总行／逐目标一行（名字 · 时间 · 徽标）／',
    '   失败行的原因与怎么修／按钮那一排。零阴影下靠发丝线、左竖条与字重分家 ⇒ 换皮只换取值。 */',
    box + ' {',
    '  container-type: inline-size;',
    '  display: grid;',
    '  gap: 10px;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-body') + ';',
    '  line-height: 1.5;',
    '}',
    '/* 焦点地板：本件里可点的只有那枚按钮；这一条先立好，按钮自己的那条在下面覆盖它。 */',
    box + ' :focus-visible {',
    '  outline: 2px solid ' + skinVar('accent') + ';',
    '  outline-offset: 2px;',
    '}',
    '/* 汇总行：逐段一枚 span、段间只靠列距（标记里不写分隔符）。 */',
    s('meta') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 4px 12px;',
    '  margin: 0;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    s('list') + ' {',
    '  display: grid;',
    '  gap: 0;',
    '  margin: 0;',
    '  padding: 0;',
    '  min-width: 0;',
    '  list-style: none;',
    '  border-top: 1px solid ' + skinVar('line') + ';',
    '}',
    '/* 一行一个目标：**缺省＝宽档一行三列**（名字／时间／徽标）；窄档那一条在文末把它覆盖成两行。 */',
    s('target') + ' {',
    '  display: grid;',
    '  grid-template-columns: minmax(0, 9em) minmax(0, 1fr) auto;',
    '  gap: 3px 12px;',
    '  min-width: 0;',
    '  padding: 12px 0;',
    '  border-bottom: 1px solid ' + skinVar('line') + ';',
    '  align-items: center;',
    '}',
    s('name') + ' {',
    '  grid-column: 1;',
    '  grid-row: 1;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-size: ' + skinVar('fs-body') + ';',
    '  font-weight: 700;',
    '  overflow-wrap: anywhere;',
    '}',
    s('detail') + ' {',
    '  grid-column: 2;',
    '  grid-row: 1;',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 3px 10px;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-variant-numeric: tabular-nums;',
    '  overflow-wrap: anywhere;',
    '}',
    s('detail') + ' > span { overflow-wrap: anywhere; }',
    '/* 徽标：**记号 ＋ 字**（✓ 已同步 ／ ✗ 失败 ／ ○ 待运行）；色只是第三样。 */',
    s('badge') + ' {',
    '  grid-column: 3;',
    '  grid-row: 1;',
    '  justify-self: end;',
    '  align-self: baseline;',
    '  padding: 1px 8px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('surface-2') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 700;',
    '  overflow-wrap: anywhere;',
    '}',
    s('badge') + '.is-ok { color: ' + skinVar('ok') + '; border-color: ' + skinVar('ok') + '; }',
    s('badge') + '.is-failed { color: ' + skinVar('danger') + '; border-color: ' + skinVar('danger') + '; }',
    s('badge') + '.is-pending { color: ' + skinVar('ink-2') + '; }',
    '/* 失败行那两句：**左竖条 ＋ 软底**（零阴影、零圆角下也立得住）。 */',
    s('why') + ' {',
    '  grid-column: 1 / 4;',
    '  grid-row: 2;',
    '  margin: 6px 0 0;',
    '  padding: 9px 11px;',
    '  border-left: 3px solid ' + skinVar('warn') + ';',
    '  background: ' + skinVar('warn-soft') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  line-height: 1.7;',
    '  overflow-wrap: anywhere;',
    '}',
    s('why') + ' > b { color: ' + skinVar('ink') + '; }',
    s('why') + ' > span { display: block; margin-top: 3px; }',
    s('why') + ' > span > b { color: ' + skinVar('ink') + '; }',
    '/* 按钮那一排：说明占满剩下一行，按钮永远是最右边那枚（窄档自己折到下一行）。 */',
    s('tool') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  gap: 10px;',
    '  align-items: center;',
    '  justify-content: space-between;',
    '  padding-top: 12px;',
    '  border-top: 1px solid ' + skinVar('line') + ';',
    '}',
    s('hint') + ' {',
    '  flex: 1 1 190px;',
    '  min-width: 0;',
    '  margin: 0;',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 按钮：两枚字（静止／跑起来）**占同一格**，宽度取宽者 ⇒ 换字不跳版。 */',
    s('button') + ' {',
    '  flex: none;',
    '  display: grid;',
    '  min-height: ' + String(SYNC_STATUS_TOUCH_PX) + 'px;',
    '  padding: 10px 18px;',
    '  box-sizing: border-box;',
    '  border: 1px solid ' + skinVar('accent') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('accent') + ';',
    '  color: ' + skinVar('accent-ink') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 700;',
    '  letter-spacing: .02em;',
    '  cursor: pointer;',
    '  transition: transform .08s ease, opacity .08s ease;',
    '}',
    s('btn-rest') + ', ' + s('btn-busy') + ' {',
    '  grid-area: 1 / 1;',
    '  white-space: nowrap;',
    '}',
    s('btn-busy') + ' { visibility: hidden; }',
    '/* running：字换成「同步中…」（原地、宽度锁住）；`:disabled` 一并给出——没有第二个色是必须的。',
    '   后半截只用**裸槽类**：`running` 里已经带了 scope，再拼一次 `s()` 会得到',
    '   「件内还要再套一层 page-ui」那种永远匹配不到的死规则。 */',
    running + slotSel('btn-busy') + ' { visibility: visible; }',
    running + slotSel('btn-rest') + ' { visibility: hidden; }',
    s('button') + ':disabled {',
    '  cursor: not-allowed;',
    '  opacity: .72;',
    '}',
    '/* hover：只判设备能力（谁的页面被嵌进侧栏／面板都一样不吃亏），且**不是唯一通路**：',
    '   静止态已经写清按下去会怎样（`-hint`），色与位移都只是加强。 */',
    '@media (hover:hover) and (pointer:fine) {',
    '  ' + s('button') + ':not(:disabled):hover {',
    '    opacity: .92;',
    '  }',
    '}',
    s('button') + ':not(:disabled):active {',
    '  transform: scale(.98);',
    '}',
    s('button') + ':focus-visible {',
    '  outline: 2px solid ' + skinVar('ink') + ';',
    '  outline-offset: 2px;',
    '}',
    '/* 错误行：**写在控件旁边**（不是页角），左竖条 ＋ 危险软底；`hidden` 必须真的收起来',
    '   （作者样式里的 display 会盖掉 UA 的 `[hidden]{display:none}`，所以这一条得自己写）。 */',
    s('error') + ' {',
    '  margin: 0;',
    '  padding: 9px 11px;',
    '  border-left: 3px solid ' + skinVar('danger') + ';',
    '  background: ' + skinVar('danger-soft') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  color: ' + skinVar('ink') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  line-height: 1.7;',
    '  overflow-wrap: anywhere;',
    '}',
    s('error') + '[hidden] { display: none; }',
    '/* 空态：说清这里本来会写什么（一个目标都没接过不是错误，是还没开始）。 */',
    s('empty') + ' {',
    '  margin: 0;',
    '  padding: 18px 14px;',
    '  box-sizing: border-box;',
    '  border: 1px dashed ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  text-align: center;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 窄容器（≤' + String(SYNC_STATUS_NARROW_PX) + 'px）：一行三列**覆盖**成两行',
    '   （名字＋徽标／时间；失败行再落到第三行）——判的是**本件自己的宽度**，不是视口宽度。 */',
    '@container (max-width: ' + String(SYNC_STATUS_NARROW_PX) + 'px) {',
    '  ' + s('target') + ' {',
    '    grid-template-columns: minmax(0, 1fr) auto;',
    '    align-items: baseline;',
    '  }',
    '  ' + s('detail') + ' {',
    '    grid-column: 1 / 3;',
    '    grid-row: 2;',
    '  }',
    '  ' + s('badge') + ' {',
    '    grid-column: 2;',
    '    grid-row: 1;',
    '  }',
    '  ' + s('why') + ' { grid-column: 1 / 3; grid-row: 3; }',
    '}',
    '/* 动效只有那 80ms 的按下位移与 hover 透明度；这档下连它都不做——没有东西会卡在半路。 */',
    '@media (prefers-reduced-motion:reduce) {',
    '  ' + s('button') + ' { transition: none; }',
    '  ' + s('button') + ':not(:disabled):active { transform: none; }',
    '}',
  ].join(LF);
}
