/** 组件层**件清单**（自动派生，**勿手改**）。
 *
 *  谁产的：`node packages/base-render/scripts/gen-components.mjs`（写）／`--check`（守漂移：非零退出并点名）。
 *  唯一事实在磁盘：本文件是 `src/components/` 的派生，**不许手写、不许反过来当输入**——找件读这里，改件改磁盘再重跑。
 *
 *  口径三条（与 `docs/base/base-render/公共组件契约.md` §四 同一条）：
 *   ① 件＝`src/components/<件名>/` 里同时有 `index.ts`／`render.ts`／`style.ts` 的目录（契约 §三 的形状）；
 *      `shared/`／`skin/` 不是件；缺文件的目录按**不是「一件一目录」的形状**跳过（照实记在 `COMPONENT_SKIPPED`）。
 *   ② `--check` 与磁盘不一致 ⇒ 非零退出并点名（哪一件、哪个字段）；
 *   ③ 抽不出的字段照实写 `—（…）`，不静默填默认值。
 *
 *  本盘读数：件 49（跳过 12 个目录）；中文名抽不出 0；形态闭集抽不出 2（entry-rows、punch-strip）；示例入参抽不出 5（filter-chips、result-row、search-field、sort-toggle、window-picker）；层出口还没加行的 0（—）。
 *
 *  **名册对账**（层出口 ＝ 名册）：点名目录 50 ＝ 件 49 ＋ 非件 1 ＋ **缺目录 0**（—）——名册里有、盘上没有的，照实记在这儿，不许静默跳过。
 *
 *  **跨件重名 0 个**（—）：同一个名字被 ≥2 件出口 ⇒ 层出口 `export *` 下会撞（`isIsoDate` 那类就是这个坑）。**这里只记事实**；要不要判红由判据那边定（`ILIFE_COMPONENT_EXPORTS_UNIQUE=1` 可开成硬红）。
 *
 *  「族」＝层出口（`src/components/index.ts`）上这件所在注记块的族名；`—`＝那一行没有族注记（独立成件）。
 *  「层出口」＝层出口加没加这件那一行（`无`＝件已在磁盘上、`base-paint/blocks` 还取不到它）。
 *  「示例入参」＝README 入参表里**必填**字段按声明类型各给一个确定值（皮肤矩阵判据拿它渲染每一件）。
 */

/** 跳过的目录（名字 ＋ 原因：不是件，或不是「一件一目录」的形状）。 */
export interface SkippedEntry {
  readonly name: string;
  readonly why: string;
  /** 层出口（名册）里点了名没有。 */
  readonly inLayer: boolean;
}

/** 名册里有、盘上没有的目录（照实记，不许静默跳过）。 */
export interface MissingDirEntry {
  readonly name: string;
  readonly why: string;
}

/** 跨件公开名（同一个名字被 ≥2 件出口 ⇒ 层出口 `export *` 下会撞）。 */
export interface SharedExportEntry {
  readonly name: string;
  readonly pieces: readonly string[];
}

/** 一件的机器读数（全部由 `src/components/<件名>/` 现算）。 */
export interface ComponentRow {
  readonly name: string;
  readonly cn: string;
  readonly family: string;
  readonly layerLine: string;
  readonly exports: readonly string[];
  readonly variants: readonly string[];
  readonly render: string;
  readonly style: string;
  readonly familyCss: string;
  readonly runtime: string;
  readonly readme: string;
  readonly sample: Readonly<Record<string, unknown>> | null;
}

/** 清单从哪一层派生（唯一事实所在）。 */
export const COMPONENT_LAYER: string = "src/components";

/** 派生器路径（重跑就是它）。 */
export const COMPONENT_GENERATOR: string = "packages/base-render/scripts/gen-components.mjs";

/** 跳过的目录（族目录 ＋ 层内共用）。 */
export const COMPONENT_SKIPPED: readonly SkippedEntry[] = [
  {"name":"charts","why":"不是「一件一目录」的形状（缺 render.ts）：族目录，或还在落地中的件","inLayer":false},
  {"name":"controls","why":"不是「一件一目录」的形状（缺 render.ts／style.ts）：族目录，或还在落地中的件","inLayer":false},
  {"name":"help","why":"不是「一件一目录」的形状（缺 style.ts）：族目录，或还在落地中的件","inLayer":false},
  {"name":"page","why":"不是「一件一目录」的形状（缺 render.ts）：族目录，或还在落地中的件","inLayer":false},
  {"name":"page-bars","why":"不是「一件一目录」的形状（缺 render.ts）：族目录，或还在落地中的件","inLayer":false},
  {"name":"page-nav","why":"不是「一件一目录」的形状（缺 render.ts）：族目录，或还在落地中的件","inLayer":false},
  {"name":"page-ui","why":"不是「一件一目录」的形状（缺 render.ts／style.ts）：族目录，或还在落地中的件","inLayer":false},
  {"name":"shared","why":"层内共用小件（跨族小件，不放组件本身），不是件","inLayer":false},
  {"name":"skin","why":"皮肤层（三套语言的取值表），不是件","inLayer":true},
  {"name":"style","why":"不是「一件一目录」的形状（缺 render.ts／style.ts）：族目录，或还在落地中的件","inLayer":false},
  {"name":"template","why":"不是「一件一目录」的形状（缺 render.ts／style.ts）：族目录，或还在落地中的件","inLayer":false},
  {"name":"text","why":"不是「一件一目录」的形状（缺 render.ts／style.ts）：族目录，或还在落地中的件","inLayer":false},
];

/** **名册里有、盘上没有**的目录（`缺目录`）——层出口点了名，目录还没落地。 */
export const COMPONENT_MISSING_DIRS: readonly MissingDirEntry[] = [
];

/** **跨件公开名**：同一个名字被 ≥2 件出口（层出口 `export *` 下会撞）。 */
export const COMPONENT_SHARED_EXPORTS: readonly SharedExportEntry[] = [
];

/** 件清单（顺序＝目录名字节序，稳定）。 */
export const COMPONENTS: readonly ComponentRow[] = [
  {"name":"calendar-month","cn":"月历格","family":"—","layerLine":"有","exports":["CALENDAR_MONTH_CLASS","CALENDAR_MONTH_FORMS","CALENDAR_MONTH_LEVELS","CALENDAR_MONTH_MAX_WEEKS","CALENDAR_MONTH_MISSING","CALENDAR_MONTH_SLOTS","CALENDAR_MONTH_TODAY_MARK","CALENDAR_MONTH_WEEKDAYS","CALENDAR_MONTH_WEEK_LENGTH","calendarMonthSlot","renderCalendarMonth","CALENDAR_MONTH_BAR_HEIGHT_PX","CALENDAR_MONTH_CELL_MIN_HEIGHT_PX","CALENDAR_MONTH_LEVEL_HEIGHTS_PX","CALENDAR_MONTH_NARROW_PX","calendarMonthCss"],"variants":["CALENDAR_MONTH_FORMS=('grid')"],"render":"renderCalendarMonth","style":"calendarMonthCss","familyCss":"","runtime":"无","readme":"有","sample":{"title":"示例","cells":[{"day":"示例","value":"示例"}]}},
  {"name":"compare-columns","cn":"双列对照","family":"—","layerLine":"有","exports":["COMPARE_COLUMNS_CALIBER_LABEL","COMPARE_COLUMNS_CLASS","COMPARE_COLUMNS_DIFF_LABEL","COMPARE_COLUMNS_DIRECTIONS","COMPARE_COLUMNS_DOWN","COMPARE_COLUMNS_FLAT","COMPARE_COLUMNS_FORMS","COMPARE_COLUMNS_MINUS","COMPARE_COLUMNS_PLUS","COMPARE_COLUMNS_SENSES","COMPARE_COLUMNS_SLOTS","COMPARE_COLUMNS_UP","compareColumnsDirectionClass","compareColumnsSideClass","compareColumnsSlot","compareColumnsToneClass","renderCompareColumns","COMPARE_COLUMNS_BAR_MIN_PX","COMPARE_COLUMNS_BAR_THICKNESS_PX","COMPARE_COLUMNS_LABEL_BAND_EM","COMPARE_COLUMNS_NARROW_PX","compareColumnsCss"],"variants":["COMPARE_COLUMNS_FORMS=('back-to-back')","COMPARE_COLUMNS_DIRECTIONS=('up','down','flat')","COMPARE_COLUMNS_SENSES=('neutral','up-good','down-good')"],"render":"renderCompareColumns","style":"compareColumnsCss","familyCss":"","runtime":"无","readme":"有","sample":{"leftLabel":"示例","rightLabel":"示例","rows":[{"label":"示例","left":1,"right":1}]}},
  {"name":"confirm-strip","cn":"二次确认条","family":"—","layerLine":"有","exports":["CONFIRM_STRIP_ACTS","CONFIRM_STRIP_BARE_WORDS","CONFIRM_STRIP_BACKUP_ATTR","CONFIRM_STRIP_BACKUP_DEFAULT","CONFIRM_STRIP_BOUND_ATTR","CONFIRM_STRIP_CLASS","CONFIRM_STRIP_COUNT_ATTR","CONFIRM_STRIP_EVENT_CANCEL","CONFIRM_STRIP_EVENT_COMMIT","CONFIRM_STRIP_FORM_ATTR","CONFIRM_STRIP_FORMS","CONFIRM_STRIP_IRREVERSIBLE_ATTR","CONFIRM_STRIP_KEEP_DEFAULT","CONFIRM_STRIP_LOSS_DEFAULT","CONFIRM_STRIP_SLOTS","CONFIRM_STRIP_STATES","CONFIRM_STRIP_STATE_ATTR","CONFIRM_STRIP_UNIT_ATTR","CONFIRM_STRIP_UNIT_DEFAULT","confirmStripSlot","renderConfirmStrip","CONFIRM_STRIP_ACTIVE_SCALE","CONFIRM_STRIP_NARROW_PX","CONFIRM_STRIP_TOUCH_MIN_PX","CONFIRM_STRIP_TRANSITION_MS","confirmStripCss","buildConfirmStripJs"],"variants":["CONFIRM_STRIP_FORMS=('list')","CONFIRM_STRIP_STATES=('rest','busy','disabled')","CONFIRM_STRIP_ACTS=('keep','danger')","CONFIRM_STRIP_BARE_WORDS=('确定','确认','好','好的','是','是的','行','可以','提交','继续','下一步','OK','ok','yes','no')"],"render":"renderConfirmStrip","style":"confirmStripCss","familyCss":"","runtime":"有（runtime.ts：buildConfirmStripJs）","readme":"有","sample":{"dangerVerb":"示例","count":1,"undoable":false,"items":[{"name":"示例"}]}},
  {"name":"date-range","cn":"日期范围","family":"—","layerLine":"有","exports":["DATE_RANGE_CELLS","DATE_RANGE_CLASS","DATE_RANGE_COLUMNS","DATE_RANGE_CUSTOM","DATE_RANGE_DAYS_ATTR","DATE_RANGE_EVENT_CHANGE","DATE_RANGE_FORMS","DATE_RANGE_FROM_ATTR","DATE_RANGE_GAP_PX","DATE_RANGE_HIT_ATTR","DATE_RANGE_MISSING","DATE_RANGE_NAME_ATTR","DATE_RANGE_PRESET_ATTR","DATE_RANGE_TO_ATTR","DATE_RANGE_TOUCH_PX","DATE_RANGE_UNSET","DATE_RANGE_WEEK_LABELS","isIsoDate","monthCells","rangeDays","shiftMonth","renderDateRange","sentenceOf","dateRangeCss","buildDateRangeJs"],"variants":["DATE_RANGE_FORMS=('calendar')","DATE_RANGE_ACTIONS=('preset','day','prev','next')","DATE_RANGE_WEEK_LABELS=('一','二','三','四','五','六','日')"],"render":"renderDateRange","style":"dateRangeCss","familyCss":"","runtime":"有（runtime.ts：buildDateRangeJs）","readme":"有","sample":{"name":"示例"}},
  {"name":"dialog","cn":"对话框（形态 A 确认型）","family":"—","layerLine":"有","exports":["DIALOG_ACT_ATTR","DIALOG_ATTR","DIALOG_BOUND_ATTR","DIALOG_CLASS","DIALOG_CLOSE_REASONS","DIALOG_EDGE_PX","DIALOG_EVENT_CLOSE","DIALOG_EVENT_OPEN","DIALOG_FORMS","DIALOG_MAX_WIDTH_PX","DIALOG_MIN_HEIGHT_PX","DIALOG_OPEN_ATTR","DIALOG_OPENER_CLASS","DIALOG_SLOTS","DIALOG_STATUS_ATTR","DIALOG_STATUS_KINDS","DIALOG_TONES","dialogClass","dialogOpenerClass","dialogSlot","renderDialog","renderDialogOpener","dialogCss","dialogEdgeMix","dialogHaloMix","dialogScrimMix","buildDialogJs"],"variants":["DIALOG_FORMS=('confirm')","DIALOG_TONES=('plain','warn','danger')","DIALOG_STATUS_KINDS=('error','busy')","DIALOG_CLOSE_REASONS=('action','esc','backdrop','programmatic')"],"render":"renderDialog","style":"dialogCss","familyCss":"","runtime":"有（runtime.ts：buildDialogJs）","readme":"有","sample":{"id":"示例","title":"示例","body":[{}],"actions":[{"label":"示例","value":"示例"}]}},
  {"name":"drawer-sheet","cn":"底部弹层（形态 C 多选 ＋ 完成 N 项）","family":"—","layerLine":"有","exports":["DRAWER_ATTR","DRAWER_BOUND_ATTR","DRAWER_CLASS","DRAWER_CLOSE_ATTR","DRAWER_CLOSE_REASONS","DRAWER_COUNT_ATTR","DRAWER_COUNT_LEAD","DRAWER_COUNT_UNIT","DRAWER_DONE_ATTR","DRAWER_DONE_TEMPLATE","DRAWER_EDGE_PX","DRAWER_EDGES","DRAWER_EVENT_CHANGE","DRAWER_EVENT_CLOSE","DRAWER_EVENT_DONE","DRAWER_FORMS","DRAWER_GAP_PX","DRAWER_MAX_WIDTH_PX","DRAWER_MIN_HEIGHT_PX","DRAWER_MISSING","DRAWER_NOTE_ATTR","DRAWER_OPEN_ATTR","DRAWER_OPT_ATTR","DRAWER_OPTION_MIN_HEIGHT_PX","DRAWER_SIDE_WIDTH_PX","DRAWER_SLOTS","DRAWER_TEMPLATE_ATTR","DRAWER_ZERO_ATTR","DRAWER_ZERO_NOTE","drawerClass","drawerOpenerClass","drawerSlot","renderDrawerOpener","renderDrawerSheet","drawerSheetCss","buildDrawerSheetJs"],"variants":["DRAWER_FORMS=('multi')","DRAWER_EDGES=('bottom','side')","DRAWER_CLOSE_REASONS=('done','dismiss','esc','backdrop','programmatic')"],"render":"renderDrawerSheet","style":"drawerSheetCss","familyCss":"","runtime":"有（runtime.ts：buildDrawerSheetJs）","readme":"有","sample":{"id":"示例","title":"示例","options":[{"value":"示例","label":"示例"}]}},
  {"name":"due-row","cn":"到期行","family":"—","layerLine":"有","exports":["DUE_ACT_ATTR","DUE_ACT_LABEL_ATTR","DUE_BOUND_ATTR","DUE_DISABLED_ATTR","DUE_EVENT_ACTION","DUE_KEY_ATTR","DUE_LABEL_ATTR","DUE_LOADING_ATTR","DUE_LOADING_LABEL","DUE_ROW_CLASS","DUE_ROW_FORMS","DUE_ROW_MISSING","DUE_ROW_SLOTS","DUE_ROW_TONES","DUE_TONE_ATTR","dueRowClass","dueRowSlot","renderDueRows","DUE_ROW_BUTTON_MIN_HEIGHT_PX","DUE_ROW_BUTTON_MIN_WIDTH_PX","DUE_ROW_CONTAINER","DUE_ROW_COUNT_PX","DUE_ROW_NARROW_MAX_PX","dueRowCss","buildDueRowJs"],"variants":["DUE_ROW_SLOTS=('head','heading','count','list','item','body','line1','tag','dot','name','meta','note','side','countdown','countdown-label','count-value','count-unit','due','act','button','act-note','err','foot','absent')","DUE_ROW_FORMS=('countdown')","DUE_ROW_TONES=('ok','warn','danger')"],"render":"renderDueRows","style":"dueRowCss","familyCss":"","runtime":"有（runtime.ts：buildDueRowJs）","readme":"有","sample":{"rows":[{"key":"示例","name":"示例","tone":"ok","tag":"示例","countdown":"示例"}]}},
  {"name":"editable-value","cn":"就地可编辑值（\"值即入口\"）","family":"—","layerLine":"有","exports":["EDIT_AFFORDANCE_ATTR","EDIT_AFFORDANCES","EDIT_BOUND_ATTR","EDIT_DISABLED_ATTR","EDIT_DISPLAY_ATTR","EDIT_EVENT_CANCEL","EDIT_EVENT_COMMIT","EDIT_HIT_ATTR","EDIT_KINDS","EDIT_KIND_ATTR","EDIT_LABEL_ATTR","EDIT_MAX_ATTR","EDIT_MIN_ATTR","EDIT_NAME_ATTR","EDIT_OPTIONS_ATTR","EDIT_PLACEHOLDER_ATTR","EDIT_REQUIRED_ATTR","EDIT_STEP_ATTR","EDIT_UNIT_ATTR","EDIT_VALUE_ATTR","EDIT_VALUE_CLASS","renderEditableValue","editableValueCss","EDIT_VALUE_EDITOR_MAX_WIDTH_PX","EDIT_VALUE_MIN_HEIGHT_PX","buildEditableValueJs"],"variants":["EDIT_KINDS=('text','number','select','date')","EDIT_AFFORDANCES=('always','hover','none')"],"render":"renderEditableValue","style":"editableValueCss","familyCss":"","runtime":"有（runtime.ts：buildEditableValueJs）","readme":"有","sample":{"name":"示例","value":"示例"}},
  {"name":"entry-rows","cn":"明细行","family":"单据族","layerLine":"有","exports":["renderEntryRows","ENTRY_ROW_NOTE_INDENT_PX","ENTRY_ROW_TIME_MIN_WIDTH_PX","entryRowsCss"],"variants":[],"render":"renderEntryRows","style":"entryRowsCss","familyCss":"sheetCss","runtime":"无","readme":"有","sample":{"rows":[{"name":"示例","value":"示例"}]}},
  {"name":"filter-chips","cn":"筛选条（形态 A）","family":"—","layerLine":"有","exports":["CHIPS_BOUND_ATTR","CHIPS_CLEAR_ATTR","CHIPS_DEFAULTS","CHIPS_DISABLED_ATTR","CHIPS_EMPTY_ATTR","CHIPS_ERROR_ATTR","CHIPS_EVENT_CHANGE","CHIPS_EVENT_LOADING","CHIPS_FORM_ATTR","CHIPS_FORMS","CHIPS_INVALID_ATTR","CHIPS_LOADING_ATTR","CHIPS_MORE_ATTR","CHIPS_NAME_ATTR","CHIPS_PICKED_ATTR","CHIPS_REGION_ATTR","CHIPS_ROOT_CLASS","CHIPS_ROWS_ATTR","CHIPS_ROW_ATTR","CHIPS_RUNTIME_ATTR","CHIPS_STATUS_ATTR","CHIPS_TARGET_ATTR","CHIPS_TOTAL_ATTR","CHIP_ATTR","CHIP_ITEM_ATTR","CHIP_ITEM_TAGS_ATTR","CHIP_ITEM_VALUE_ATTR","CHIP_N_ATTR","chipsErrorId","renderFilterChips","filterChipsCss","CHIPS_MAX_WIDTH_PX","CHIPS_STATUS_MIN_CH","CHIPS_TOUCH_MIN_PX","buildFilterChipsJs"],"variants":["CHIPS_FORMS=('A')"],"render":"renderFilterChips","style":"filterChipsCss","familyCss":"","runtime":"有（runtime.ts：buildFilterChipsJs）","readme":"有","sample":null},
  {"name":"heat-grid","cn":"热力格","family":"—","layerLine":"有","exports":["renderHeatGrid","HEAT_GRID_CLASS","HEAT_GRID_COLUMNS","HEAT_GRID_FORMS","HEAT_GRID_LEVEL_COUNT","HEAT_GRID_LEVEL_STOPS","HEAT_GRID_MISSING","HEAT_GRID_PEAK_MARK","HEAT_GRID_SLOTS","HEAT_GRID_WEEKDAYS","heatGridSlot","HEAT_GRID_ROW_PX","heatGridCss","heatGridLevel"],"variants":["HEAT_GRID_FORMS=('matrix')","HEAT_GRID_WEEKDAYS=('周一','周二','周三','周四','周五','周六','周日')"],"render":"renderHeatGrid","style":"heatGridCss","familyCss":"","runtime":"无","readme":"有","sample":{"title":"示例","rows":[{"label":"示例","values":[]}]}},
  {"name":"hour-band","cn":"时段带","family":"—","layerLine":"有","exports":["HOUR_BAND_CLASS","HOUR_BAND_DEFAULT_TONE","HOUR_BAND_FORMS","HOUR_BAND_HOURS","HOUR_BAND_MINUTES_PER_DAY","HOUR_BAND_MISSING","HOUR_BAND_RULER_NARROW_PX","HOUR_BAND_SLOTS","HOUR_BAND_TEXT_MIN_FRACTION","HOUR_BAND_TONES","HOUR_BAND_UNRECORDED_LABEL","hourBandSlot","renderHourBand","HOUR_BAND_HEIGHT_PX","HOUR_BAND_RULER_FONT_PX","hourBandCss","hourBandClock","hourBandDuration","hourBandPercent"],"variants":["HOUR_BAND_FORMS=('band')"],"render":"renderHourBand","style":"hourBandCss","familyCss":"","runtime":"无","readme":"有","sample":{"title":"示例","intervals":[{"from / .to":1,"label":"示例"}]}},
  {"name":"invoice-lines","cn":"金额分解","family":"—","layerLine":"有","exports":["INVOICE_LINES_CLASS","INVOICE_LINES_DECIMALS","INVOICE_LINES_FORMS","INVOICE_LINES_KIND_MARKS","INVOICE_LINES_SEGMENT_MIN_PCT","INVOICE_LINES_SHARE_WORD","INVOICE_LINES_SYMBOL","INVOICE_LINES_TOTAL_LABEL","INVOICE_LINES_TOTAL_SCALE","INVOICE_LINES_WHY_ADD","INVOICE_LINES_WHY_CUT","INVOICE_LINE_KINDS","formatInvoiceAmount","renderInvoiceLines","INVOICE_LINES_INDENT_PX","INVOICE_LINES_RULE_PX","invoiceLinesCss"],"variants":["INVOICE_LINES_FORMS=('chain','waterfall')","INVOICE_LINE_KINDS=('base','cut','add')"],"render":"renderInvoiceLines","style":"invoiceLinesCss","familyCss":"","runtime":"无","readme":"有","sample":{"lines":[{"label":"示例","amount":1,"kind":"base","why":"示例"}]}},
  {"name":"key-value-list","cn":"档案行","family":"—","layerLine":"有","exports":["KEY_VALUE_CLASS","KEY_VALUE_FORMS","KEY_VALUE_MIN_ROW_PX","KEY_VALUE_MISSING","keyValueSlot","normalizeKeyValueList","renderKeyValueList","keyValueListCss"],"variants":["KEY_VALUE_FORMS=('rows')"],"render":"renderKeyValueList","style":"keyValueListCss","familyCss":"","runtime":"无","readme":"有","sample":{"rows":[{"label":"示例","value":"示例"}]}},
  {"name":"ledger-rows","cn":"账目行","family":"单据族","layerLine":"有","exports":["LEDGER_LEADERS","LEDGER_ROW_KINDS","renderLedgerRows","ledgerRowsCss"],"variants":["LEDGER_ROW_KINDS=('item','total')","LEDGER_LEADERS=('dots','none')"],"render":"renderLedgerRows","style":"ledgerRowsCss","familyCss":"sheetCss","runtime":"无","readme":"有","sample":{"rows":[{"label":"示例","value":"示例"}]}},
  {"name":"multi-checks","cn":"多选清单","family":"—","layerLine":"有","exports":["MULTI_CHECKS_ACTION_ATTR","MULTI_CHECKS_ALL_ATTR","MULTI_CHECKS_ALL_TEXT","MULTI_CHECKS_AMOUNT_ATTR","MULTI_CHECKS_BOUND_ATTR","MULTI_CHECKS_CLASS","MULTI_CHECKS_EMPTY_TEXT","MULTI_CHECKS_EVENT_ACTION","MULTI_CHECKS_EVENT_CHANGE","MULTI_CHECKS_FORMS","MULTI_CHECKS_FORM_ATTR","MULTI_CHECKS_GROUP_ATTR","MULTI_CHECKS_ITEM_ATTR","MULTI_CHECKS_LOADING_ATTR","MULTI_CHECKS_LOADING_TEXT","MULTI_CHECKS_MONEY_ATTR","MULTI_CHECKS_NAME_ATTR","MULTI_CHECKS_NONE_TEXT","MULTI_CHECKS_PARTIAL_ATTR","MULTI_CHECKS_PRIMARY_ATTR","MULTI_CHECKS_SLOTS","MULTI_CHECKS_UNIT_ATTR","multiChecksSlot","renderMultiChecks","MULTI_CHECKS_BAR_PX","MULTI_CHECKS_BOX_PX","MULTI_CHECKS_MIN_TARGET_PX","MULTI_CHECKS_NARROW_PX","MULTI_CHECKS_ROW_MIN_HEIGHT_PX","multiChecksCss","buildMultiChecksJs"],"variants":["MULTI_CHECKS_FORMS=('grouped')"],"render":"renderMultiChecks","style":"multiChecksCss","familyCss":"","runtime":"有（runtime.ts：buildMultiChecksJs）","readme":"有","sample":{"name":"示例","label":"示例","rows":[{"id":"示例","title":"示例"}]}},
  {"name":"note-block","cn":"备注块","family":"—","layerLine":"有","exports":["NOTE_BLOCK_ATT_PREFIX","NOTE_BLOCK_CLASS","NOTE_BLOCK_COLLAPSE_CHARS","NOTE_BLOCK_ELLIPSIS","NOTE_BLOCK_FORMS","NOTE_BLOCK_LEN_SUFFIX","NOTE_BLOCK_PEEK_CHARS","NOTE_BLOCK_TONES","renderNoteBlock","NOTE_BLOCK_INDENT_PX","NOTE_BLOCK_RULE_PX","NOTE_BLOCK_TOUCH_PX","noteBlockCss"],"variants":["NOTE_BLOCK_FORMS=('note')","NOTE_BLOCK_TONES=('quiet','warn','danger')"],"render":"renderNoteBlock","style":"noteBlockCss","familyCss":"","runtime":"无","readme":"有","sample":{"text":"示例","toneLabel":"示例"}},
  {"name":"number-stepper","cn":"数量步进","family":"—","layerLine":"有","exports":["NUMBER_STEPPER_AT_MAX","NUMBER_STEPPER_AT_MIN","NUMBER_STEPPER_CLASS","NUMBER_STEPPER_EVENT_CHANGE","NUMBER_STEPPER_FORMS","NUMBER_STEPPER_GAP_PX","NUMBER_STEPPER_HIT_ATTR","NUMBER_STEPPER_MISSING","NUMBER_STEPPER_NAME_ATTR","NUMBER_STEPPER_TOUCH_PX","NUMBER_STEPPER_UNSET","NUMBER_STEPPER_VALUE_ATTR","NUMBER_STEPPER_VALUE_MIN_PX","formatStepperValue","renderNumberStepper","numberStepperCss","buildNumberStepperJs"],"variants":["NUMBER_STEPPER_FORMS=('standard')","NUMBER_STEPPER_ACTIONS=('dec','inc','quick','edit')"],"render":"renderNumberStepper","style":"numberStepperCss","familyCss":"","runtime":"有（runtime.ts：buildNumberStepperJs）","readme":"有","sample":{"name":"示例","value":1,"min":1,"max":1,"step":1}},
  {"name":"page-head","cn":"页头","family":"—","layerLine":"有","exports":["PAGE_HEAD_CLASS","PAGE_HEAD_FORMS","renderPageHead","PAGE_HEAD_READING_SCALE","pageHeadCss"],"variants":["PAGE_HEAD_FORMS=('hero')"],"render":"renderPageHead","style":"pageHeadCss","familyCss":"","runtime":"无","readme":"有","sample":{"skill":"示例","title":"示例","reading":{"value":"示例"}}},
  {"name":"photo-compare","cn":"前后对比","family":"—","layerLine":"有","exports":["PHOTO_COMPARE_CLASS","PHOTO_COMPARE_FORMS","PHOTO_COMPARE_MIN_HIT_PX","PHOTO_COMPARE_MISSING","PHOTO_COMPARE_SPLIT_VAR","PHOTO_COMPARE_STEP","PHOTO_COMPARE_TONES","PHOTO_COMPARE_TONE_MARKS","renderPhotoCompare","buildPhotoCompareJs","PHOTO_COMPARE_MARK_ARM_PX","PHOTO_COMPARE_NARROW_PX","PHOTO_COMPARE_STAGE_MAX_PX","photoCompareCss"],"variants":["PHOTO_COMPARE_FORMS=('drag')","PHOTO_COMPARE_TONES=('down','up','same')"],"render":"renderPhotoCompare","style":"photoCompareCss","familyCss":"","runtime":"有（runtime.ts：buildPhotoCompareJs）","readme":"有","sample":{"before":"示例","after":"示例","deltas":[{"label":"示例","before":"示例","after":"示例","change":"示例"}]}},
  {"name":"photo-grid","cn":"照片网格","family":"—","layerLine":"有","exports":["PHOTO_GRID_ADD_LABEL","PHOTO_GRID_ADD_MARK","PHOTO_GRID_CLASS","PHOTO_GRID_EMPTY_TEXT","PHOTO_GRID_FORMS","PHOTO_GRID_MIN_STACK","PHOTO_GRID_MISSING","PHOTO_GRID_RATIOS","renderPhotoGrid","PHOTO_GRID_MARK_ARM_PX","PHOTO_GRID_MARK_INSET_PX","PHOTO_GRID_MARK_THICK_PX","PHOTO_GRID_THREE_COL_PX","PHOTO_GRID_TOUCH_PX","photoGridCss"],"variants":["PHOTO_GRID_FORMS=('grid')","PHOTO_GRID_RATIOS=('4-5','1-1','3-4','4-3')"],"render":"renderPhotoGrid","style":"photoGridCss","familyCss":"","runtime":"无","readme":"有","sample":{"photos":[{"alt":"示例"}],"groups":[{"month":"示例"}]}},
  {"name":"popover-menu","cn":"浮出菜单（形态 A 贴着按钮）","family":"—","layerLine":"有","exports":["MENU_ALIGNS","MENU_ANCHOR_PREFIX","MENU_ANCHOR_QUERY","MENU_AREA_QUERY","MENU_ATTR","MENU_BOUND_ATTR","MENU_CARET","MENU_CLASS","MENU_EDGE_PX","MENU_EVENT_SELECT","MENU_EVENT_TOGGLE","MENU_FORMS","MENU_GAP_PX","MENU_ITEM_ATTR","MENU_KINDS","MENU_MAX_HEIGHT_PX","MENU_MIN_HEIGHT_PX","MENU_OFFSET_PX","MENU_PANEL_ATTR","MENU_SLOTS","MENU_TICK","MENU_TRIGGER_ATTR","MENU_WIDTH_PX","menuClass","menuSlot","renderPopoverMenu","popoverMenuCss","buildPopoverMenuJs"],"variants":["MENU_FORMS=('hug')","MENU_ALIGNS=('start','end')","MENU_KINDS=('action','check','danger')"],"render":"renderPopoverMenu","style":"popoverMenuCss","familyCss":"","runtime":"有（runtime.ts：buildPopoverMenuJs）","readme":"有","sample":{"id":"示例","trigger":"示例","items":[{"value":"示例","label":"示例"}]}},
  {"name":"progress-list","cn":"多目标进度","family":"—","layerLine":"有","exports":["PROGRESS_LIST_CLASS","PROGRESS_LIST_FORMS","PROGRESS_LIST_MISSING","PROGRESS_LIST_STATES","PROGRESS_LIST_STATE_WORDS","PROGRESS_LIST_TONES","formatProgressNumber","renderProgressList","PROGRESS_LIST_NARROW_PX","PROGRESS_LIST_TRACK_HEIGHT_PX","progressListCss"],"variants":["PROGRESS_LIST_FORMS=('rows')","PROGRESS_LIST_STATES=('blank','on-track','done','over')","PROGRESS_LIST_TONES=('none','ok','warn','danger')"],"render":"renderProgressList","style":"progressListCss","familyCss":"","runtime":"无","readme":"有","sample":{"rows":[{"label":"示例","current":1,"goal":1}]}},
  {"name":"progress-ring","cn":"进度环","family":"—","layerLine":"有","exports":["renderProgressRing","PROGRESS_RING_ARC_LEN","PROGRESS_RING_CLASS","PROGRESS_RING_FORMS","PROGRESS_RING_MISSING","PROGRESS_RING_RADIUS_PX","PROGRESS_RING_SLOTS","PROGRESS_RING_STROKE_PX","progressRingSlot","PROGRESS_RING_MAX_DIAMETER_PX","PROGRESS_RING_VALUE_PX","progressRingCss"],"variants":["PROGRESS_RING_FORMS=('arc')"],"render":"renderProgressRing","style":"progressRingCss","familyCss":"","runtime":"无","readme":"有","sample":{"title":"示例","value":1,"goal":1}},
  {"name":"punch-strip","cn":"打孔格带","family":"单据族","layerLine":"有","exports":["PUNCH_STRIP_EMPTY_MARK","PUNCH_STRIP_MAX_CELLS","renderPunchStrip","PUNCH_STRIP_BOX_HEIGHT_PX","PUNCH_STRIP_BOX_RADIUS_PX","punchStripCss"],"variants":[],"render":"renderPunchStrip","style":"punchStripCss","familyCss":"sheetCss","runtime":"无","readme":"有","sample":{"days":[{"label":"示例","value":"示例"}]}},
  {"name":"radio-cards","cn":"单选卡组","family":"—","layerLine":"有","exports":["RADIO_CARDS_BOUND_ATTR","RADIO_CARDS_CLASS","RADIO_CARDS_EMPTY_TEXT","RADIO_CARDS_EVENT_CHANGE","RADIO_CARDS_FORMS","RADIO_CARDS_FORM_ATTR","RADIO_CARDS_LEAD_MAX","RADIO_CARDS_LOADING_ATTR","RADIO_CARDS_LOADING_TEXT","RADIO_CARDS_NAME_ATTR","RADIO_CARDS_OPTION_ATTR","RADIO_CARDS_REQUIRED_ATTR","RADIO_CARDS_SLOTS","RADIO_CARDS_VALUE_ATTR","radioCardsSlot","renderRadioCards","RADIO_CARDS_BAR_PX","RADIO_CARDS_CARD_MIN_HEIGHT_PX","RADIO_CARDS_MIN_TARGET_PX","RADIO_CARDS_NARROW_PX","radioCardsCss","buildRadioCardsJs"],"variants":["RADIO_CARDS_FORMS=('cards')"],"render":"renderRadioCards","style":"radioCardsCss","familyCss":"","runtime":"有（runtime.ts：buildRadioCardsJs）","readme":"有","sample":{"name":"示例","label":"示例","options":[{"value":"示例","title":"示例"}]}},
  {"name":"range-bar","cn":"区间条","family":"—","layerLine":"有","exports":["RANGE_BAR_CLASS","RANGE_BAR_DEFAULT_TONE","RANGE_BAR_FORMS","RANGE_BAR_NARROW_PX","RANGE_BAR_SLOTS","RANGE_BAR_TEXT_HIDE_BELOW_PX","RANGE_BAR_TEXT_MIN_FRACTION","RANGE_BAR_TONES","rangeBarSlot","renderRangeBar","RANGE_BAR_KEY_COLUMN_NARROW_PX","RANGE_BAR_KEY_COLUMN_PX","RANGE_BAR_RAIL_HEIGHT_PX","RANGE_BAR_TICK_GAP_PX","RANGE_BAR_TOTAL_COLUMN_NARROW_PX","RANGE_BAR_TOTAL_COLUMN_PX","rangeBarCss"],"variants":["RANGE_BAR_FORMS=('lanes')"],"render":"renderRangeBar","style":"rangeBarCss","familyCss":"","runtime":"无","readme":"有","sample":{"title":"示例","domain":{},"lanes":[{"label":"示例","intervals":[]}],"intervals":[{"from / .to":1}]}},
  {"name":"rank-list","cn":"榜单","family":"—","layerLine":"有","exports":["RANK_LIST_CALIBER_LABEL","RANK_LIST_CLASS","RANK_LIST_FORMS","RANK_LIST_PODIUM_SIZE","RANK_LIST_SLOTS","rankListPlaceClass","rankListSlot","renderRankList","RANK_LIST_BAR_MIN_PX","RANK_LIST_BAR_THICKNESS_PX","RANK_LIST_CARD_MIN_EM","RANK_LIST_FIRST_VALUE_SCALE","RANK_LIST_NARROW_PX","rankListCss"],"variants":["RANK_LIST_FORMS=('podium')"],"render":"renderRankList","style":"rankListCss","familyCss":"","runtime":"无","readme":"有","sample":{"rows":[{"name":"示例","value":1,"share":1}]}},
  {"name":"rating-row","cn":"评分行","family":"—","layerLine":"有","exports":["RATING_ROW_BOUND_ATTR","RATING_ROW_CLASS","RATING_ROW_DEFAULT_MAX","RATING_ROW_DISABLED_ATTR","RATING_ROW_EVENT_CHANGE","RATING_ROW_FORMS","RATING_ROW_FORM_ATTR","RATING_ROW_HALF_ATTR","RATING_ROW_LOADING_ATTR","RATING_ROW_LOADING_TEXT","RATING_ROW_MAX_ATTR","RATING_ROW_MAX_MAX","RATING_ROW_MISSING","RATING_ROW_NAME_ATTR","RATING_ROW_SLOTS","RATING_ROW_STAR_ATTR","RATING_ROW_STAR_LABEL_SUFFIX","RATING_ROW_VALUE_ATTR","ratingRowSlot","renderRatingRow","RATING_ROW_NARROW_PX","RATING_ROW_NUM_SCALE","RATING_ROW_STAR_FONT_PX","RATING_ROW_STAR_PX","ratingRowCss","buildRatingRowJs"],"variants":["RATING_ROW_FORMS=('stars')"],"render":"renderRatingRow","style":"ratingRowCss","familyCss":"","runtime":"有（runtime.ts：buildRatingRowJs）","readme":"有","sample":{"name":"示例","label":"示例"}},
  {"name":"result-row","cn":"结果行（形态 A）","family":"—","layerLine":"有","exports":["RESULT_DEFAULTS","RESULT_EMPTY_ATTR","RESULT_FORM_ATTR","RESULT_FORMS","RESULT_ITEM_ATTR","RESULT_NAME_ATTR","RESULT_ROOT_CLASS","RESULT_SEARCH_HIT_ATTR","RESULT_SEARCH_ITEM_ATTR","RESULT_SEARCH_REGION_ATTR","RESULT_SEARCH_TAGS_ATTR","markTerms","renderResultRow","resultRowCss","RESULT_MAX_WIDTH_PX","RESULT_ROW_MIN_PX","RESULT_THUMB_PX","RESULT_TOUCH_MIN_PX"],"variants":["RESULT_FORMS=('A')"],"render":"renderResultRow","style":"resultRowCss","familyCss":"","runtime":"无","readme":"有","sample":null},
  {"name":"scale-bar","cn":"刻度条","family":"单据族","layerLine":"有","exports":["SCALE_BAR_DEFAULT_CELLS","SCALE_BAR_VARIANTS","renderScaleBar","SCALE_BAR_CELL_HEIGHT_PX","SCALE_BAR_LINE_HEIGHT_PX","scaleBarCss"],"variants":["SCALE_BAR_VARIANTS=('cells','line')"],"render":"renderScaleBar","style":"scaleBarCss","familyCss":"sheetCss","runtime":"无","readme":"有","sample":{"value":1,"goal":1}},
  {"name":"search-field","cn":"搜索框（形态 B）","family":"—","layerLine":"有","exports":["SEARCH_AT_ATTR","SEARCH_BOUND_ATTR","SEARCH_CLEAR_ATTR","SEARCH_COUNT_ATTR","SEARCH_CURRENT_ATTR","SEARCH_DEFAULTS","SEARCH_DISABLED_ATTR","SEARCH_EMPTY_ATTR","SEARCH_ERROR_ATTR","SEARCH_EVENT_JUMP","SEARCH_EVENT_LOADING","SEARCH_EVENT_QUERY","SEARCH_FORM_ATTR","SEARCH_FORMS","SEARCH_HIT_ATTR","SEARCH_INPUT_ATTR","SEARCH_INVALID_ATTR","SEARCH_ITEM_ATTR","SEARCH_LOADING_ATTR","SEARCH_LOADING_TEXT_ATTR","SEARCH_NAME_ATTR","SEARCH_NEXT_ATTR","SEARCH_N_ATTR","SEARCH_POS_ATTR","SEARCH_PREV_ATTR","SEARCH_READOUT_ATTR","SEARCH_REGION_ATTR","SEARCH_ROOT_CLASS","SEARCH_RUNTIME_ATTR","SEARCH_SCOPE_ATTR","SEARCH_SCOPE_NAME_ATTR","SEARCH_STATUS_ATTR","SEARCH_TAGS_ATTR","SEARCH_TARGET_ATTR","searchErrorId","renderSearchField","searchFieldCss","SEARCH_MAX_WIDTH_PX","SEARCH_STATUS_MIN_CH","SEARCH_TOUCH_MIN_PX","buildSearchFieldJs"],"variants":["SEARCH_FORMS=('B')"],"render":"renderSearchField","style":"searchFieldCss","familyCss":"","runtime":"有（runtime.ts：buildSearchFieldJs）","readme":"有","sample":null},
  {"name":"section-head","cn":"小节头","family":"—","layerLine":"有","exports":["SECTION_HEAD_CLASS","SECTION_HEAD_FORMS","SECTION_HEAD_MORE_TEXTS","SECTION_HEAD_SEQ_MAX","SECTION_HEAD_SEQ_MIN","sectionHeadSlot","normalizeSectionHead","renderSectionHead","sectionHeadOrdinalText","SECTION_HEAD_SUM_MIN_PX","sectionHeadCss"],"variants":["SECTION_HEAD_FORMS=('fd')"],"render":"renderSectionHead","style":"sectionHeadCss","familyCss":"","runtime":"无","readme":"有","sample":{"title":"示例","body":"示例"}},
  {"name":"sheet-frame","cn":"纸面页框","family":"单据族","layerLine":"有","exports":["SHEET_VARIANTS","renderSheetFrame","sheetCss","sheetFrameCss"],"variants":["SHEET_VARIANTS=('plain','receipt')"],"render":"renderSheetFrame","style":"sheetFrameCss","familyCss":"sheetCss","runtime":"无","readme":"有","sample":{"content":"示例"}},
  {"name":"skeleton","cn":"加载骨架","family":"—","layerLine":"有","exports":["SKELETON_CLASS","SKELETON_FORM_ATTR","SKELETON_FORMS","SKELETON_MAX_ROWS","SKELETON_ROWS_ATTR","SKELETON_SLOTS","skeletonSlot","renderSkeleton","SKELETON_NARROW_PX","SKELETON_PLACEHOLDER_MIX_PERCENT","SKELETON_PULSE_DURATION_MS","SKELETON_PULSE_MIN_OPACITY","SKELETON_PULSE_NAME","SKELETON_READING_SCALE","SKELETON_ROW_HEIGHT_PX","SKELETON_ROW_SEPARATOR_PX","SKELETON_STILL_OPACITY","SKELETON_VALUE_SLOT_PX","skeletonCss"],"variants":["SKELETON_FORMS=('reading-list')"],"render":"renderSkeleton","style":"skeletonCss","familyCss":"","runtime":"无","readme":"有","sample":{"label":"示例","rows":1}},
  {"name":"slider-row","cn":"滑块行","family":"—","layerLine":"有","exports":["SLIDER_ROW_AT_MAX","SLIDER_ROW_AT_MIN","SLIDER_ROW_CLASS","SLIDER_ROW_EVENT_CHANGE","SLIDER_ROW_FORMS","SLIDER_ROW_GAP_PX","SLIDER_ROW_HIT_ATTR","SLIDER_ROW_LINE_PX","SLIDER_ROW_MISSING","SLIDER_ROW_NAME_ATTR","SLIDER_ROW_THUMB_PX","SLIDER_ROW_TOUCH_PX","SLIDER_ROW_TRACK_PX","SLIDER_ROW_UNSET","SLIDER_ROW_VALUE_ATTR","fillPercent","formatSliderValue","renderSliderRow","sliderRowCss","buildSliderRowJs"],"variants":["SLIDER_ROW_FORMS=('track')","SLIDER_ROW_ACTIONS=('dec','inc','preset')"],"render":"renderSliderRow","style":"sliderRowCss","familyCss":"","runtime":"有（runtime.ts：buildSliderRowJs）","readme":"有","sample":{"name":"示例","value":1,"min":1,"max":1,"step":1}},
  {"name":"sort-toggle","cn":"排序切换（形态 C）","family":"—","layerLine":"有","exports":["SORT_BOUND_ATTR","SORT_CALIBER_ATTR","SORT_CALIBER_LINE_ATTR","SORT_CALIBER_TEXT_ATTR","SORT_DEFAULTS","SORT_DIRECTIONS","SORT_DIR_ATTR","SORT_DISABLED_ATTR","SORT_EMPTY_ATTR","SORT_ERROR_ATTR","SORT_EVENT_CHANGE","SORT_EVENT_LOADING","SORT_FIELD_ATTR","SORT_FLIP_ATTR","SORT_FLIP_LABEL_ATTR","SORT_FORM_ATTR","SORT_FORMS","SORT_INK_ATTR","SORT_INVALID_ATTR","SORT_ITEM_ATTR","SORT_ITEM_TAGS_ATTR","SORT_LOADING_ATTR","SORT_NAME_ATTR","SORT_N_ATTR","SORT_REGION_ATTR","SORT_ROOT_CLASS","SORT_RUNTIME_ATTR","SORT_SHOWN_ATTR","SORT_STATUS_ATTR","SORT_TARGET_ATTR","SORT_VIEW_ATTR","SORT_VIEW_LABEL_ATTR","sortErrorId","renderSortToggle","sortToggleCss","SORT_MAX_WIDTH_PX","SORT_STATUS_MIN_CH","SORT_TOUCH_MIN_PX","buildSortToggleJs"],"variants":["SORT_FORMS=('C')","SORT_DIRECTIONS=('desc','asc')"],"render":"renderSortToggle","style":"sortToggleCss","familyCss":"","runtime":"有（runtime.ts：buildSortToggleJs）","readme":"有","sample":null},
  {"name":"stacked-bar","cn":"构成条","family":"—","layerLine":"有","exports":["renderStackedBar","STACKED_BAR_CLASS","STACKED_BAR_FORMS","STACKED_BAR_MAX_SEGMENTS","STACKED_BAR_MISSING","STACKED_BAR_NAME_MIN_PCT","STACKED_BAR_SERIES","STACKED_BAR_SLOTS","STACKED_BAR_VALUE_MIN_PCT","stackedBarSlot","STACKED_BAR_HEIGHT_PX","stackedBarCss"],"variants":["STACKED_BAR_FORMS=('stack')"],"render":"renderStackedBar","style":"stackedBarCss","familyCss":"","runtime":"无","readme":"有","sample":{"title":"示例","segments":[{"name":"示例","value":1}]}},
  {"name":"stat-inline","cn":"行内读数","family":"—","layerLine":"有","exports":["STAT_INLINE_CLASS","STAT_INLINE_FORMS","STAT_INLINE_MISSING","STAT_INLINE_SEP","statInlineSlot","normalizeStatInline","renderStatInline","statInlineCss"],"variants":["STAT_INLINE_FORMS=('dots')"],"render":"renderStatInline","style":"statInlineCss","familyCss":"","runtime":"无","readme":"有","sample":{"items":[{"value":"示例"}]}},
  {"name":"status-row","cn":"状态台账行","family":"—","layerLine":"有","exports":["STATUS_ROW_CLASS","STATUS_ROW_FORMS","STATUS_ROW_MISSING","STATUS_ROW_SLOTS","STATUS_ROW_TONES","statusRowClass","statusRowSlot","renderStatusRows","STATUS_ROW_CONTAINER","STATUS_ROW_ITEM_MIN_HEIGHT_PX","STATUS_ROW_NARROW_MAX_PX","STATUS_ROW_NODE_SIZE_PX","STATUS_ROW_RAIL_WIDTH_PX","statusRowCss"],"variants":["STATUS_ROW_FORMS=('ledger')","STATUS_ROW_TONES=('neutral','active','ok','warn','danger')"],"render":"renderStatusRows","style":"statusRowCss","familyCss":"","runtime":"无","readme":"有","sample":{"rows":[{"name":"示例","phase":"示例"}]}},
  {"name":"step-flow","cn":"步骤条","family":"—","layerLine":"有","exports":["STEP_FLOW_CLASS","STEP_FLOW_FORMS","STEP_FLOW_MARK_DONE","STEP_FLOW_MISSING","STEP_FLOW_SLOTS","STEP_STATES","STEP_STATE_WORDS","stepFlowClass","stepFlowSlot","renderStepFlow","STEP_FLOW_CONTAINER","STEP_FLOW_NARROW_MAX_PX","STEP_FLOW_NODE_COLUMN_PX","STEP_FLOW_NODE_SIZE_PX","stepFlowCss"],"variants":["STEP_FLOW_SLOTS=('head','title','count','list','step','node','body','title-row','name','state','time','estimate','actual','desc','note','foot','absent')","STEP_FLOW_FORMS=('vertical')","STEP_STATES=('done','now','todo')"],"render":"renderStepFlow","style":"stepFlowCss","familyCss":"","runtime":"无","readme":"有","sample":{"steps":[{"title":"示例","state":"done"}]}},
  {"name":"streak-badge","cn":"连记徽标","family":"—","layerLine":"有","exports":["STREAK_BADGE_CLASS","STREAK_BADGE_FORMS","STREAK_BADGE_MISSING","STREAK_BADGE_SLOTS","STREAK_STRENGTHS","streakBadgeClass","streakBadgeSlot","renderStreakBadges","STREAK_BADGE_CONTAINER","STREAK_BADGE_MIN_HEIGHT_PX","STREAK_BADGE_NARROW_MAX_PX","STREAK_BADGE_VALUE_PX","streakBadgeCss"],"variants":["STREAK_BADGE_SLOTS=('head','heading','list','badge','label','value','unit','absent')","STREAK_BADGE_FORMS=('row')","STREAK_STRENGTHS=('strong','mid','weak')"],"render":"renderStreakBadges","style":"streakBadgeCss","familyCss":"","runtime":"无","readme":"有","sample":{"badges":[{"strength":"strong","label":"示例","value":"示例"}]}},
  {"name":"sub-list","cn":"分组清单","family":"—","layerLine":"有","exports":["SUB_LIST_CLASS","SUB_LIST_COUNT_UNIT","SUB_LIST_DONE_LABEL","SUB_LIST_FORMS","SUB_LIST_SLOTS","subListSlot","renderSubList","SUB_LIST_HEAD_MIN_HEIGHT_PX","SUB_LIST_NARROW_PX","SUB_LIST_PRESS_MS","subListCss"],"variants":["SUB_LIST_FORMS=('fold')"],"render":"renderSubList","style":"subListCss","familyCss":"","runtime":"无","readme":"有","sample":{"groups":[{"label":"示例","items":[]}],"items":[{"label":"示例"}]}},
  {"name":"summary-head","cn":"主数字头","family":"单据族","layerLine":"有","exports":["SUMMARY_HEAD_FACES","SUMMARY_HEAD_SIZES","SUMMARY_HEAD_STAMP_TONES","renderSummaryHead","SUMMARY_HEAD_VALUE_PX","summaryHeadCss"],"variants":["SUMMARY_HEAD_SIZES=('m','l','xl')","SUMMARY_HEAD_FACES=('sans','serif')","SUMMARY_HEAD_STAMP_TONES=('ok','warn','danger')"],"render":"renderSummaryHead","style":"summaryHeadCss","familyCss":"sheetCss","runtime":"无","readme":"有","sample":{"value":"示例"}},
  {"name":"sync-status","cn":"同步状态","family":"—","layerLine":"有","exports":["SYNC_STATUS_ACTION_ATTR","SYNC_STATUS_ACTIONS","SYNC_STATUS_ATTR","SYNC_STATUS_BOUND_ATTR","SYNC_STATUS_CLASS","SYNC_STATUS_ERROR_ATTR","SYNC_STATUS_EVENT_DONE","SYNC_STATUS_EVENT_RUN","SYNC_STATUS_FAILED_TEXT","SYNC_STATUS_FORMS","SYNC_STATUS_RESULTS","SYNC_STATUS_RESULT_WORDS","SYNC_STATUS_RUNNING_LABEL","SYNC_STATUS_RUN_TIMEOUT_MS","SYNC_STATUS_STATES","SYNC_STATUS_STATE_ATTR","SYNC_STATUS_TIMEOUT_TEXT","renderSyncStatus","buildSyncStatusJs","SYNC_STATUS_NARROW_PX","SYNC_STATUS_TOUCH_PX","syncStatusCss"],"variants":["SYNC_STATUS_FORMS=('run')","SYNC_STATUS_RESULTS=('ok','failed','pending')","SYNC_STATUS_ACTIONS=('run')","SYNC_STATUS_STATES=('idle','running','failed')"],"render":"renderSyncStatus","style":"syncStatusCss","familyCss":"","runtime":"有（runtime.ts：buildSyncStatusJs）","readme":"有","sample":{"targets":[{"name":"示例","result":"ok","reason":"示例","fix":"示例"}]}},
  {"name":"task-list","cn":"勾选清单","family":"—","layerLine":"有","exports":["TASK_BAR_ATTR","TASK_BOUND_ATTR","TASK_BUSY_ATTR","TASK_CHECK_CLASS","TASK_COUNTS_ATTR","TASK_COUNTS_SEPARATOR","TASK_DONE_ATTR","TASK_EVENT_TOGGLE","TASK_GROUP_ATTR","TASK_HIT_CLASS","TASK_KEY_ATTR","TASK_LABEL_ATTR","TASK_LABEL_CLASS","TASK_LIST_ATTR","TASK_LIST_CLASS","TASK_LIST_DEFAULT_KEY","TASK_LIST_FORMS","TASK_LIST_SLOTS","TASK_OF_ATTR","TASK_ROW_CLASS","TASK_ROW_DONE_CLASS","taskListClass","taskListSlot","renderTaskList","TASK_LIST_BAR_HEIGHT_PX","TASK_LIST_CHECK_SIZE_PX","TASK_LIST_CONTAINER","TASK_LIST_HIT_MIN_HEIGHT_PX","TASK_LIST_NARROW_MAX_PX","taskListCss","buildTaskListJs"],"variants":["TASK_LIST_FORMS=('checklist')"],"render":"renderTaskList","style":"taskListCss","familyCss":"","runtime":"有（runtime.ts：buildTaskListJs）","readme":"有","sample":{"rows":[{"key":"示例","label":"示例"}]}},
  {"name":"timer-card","cn":"计时卡","family":"—","layerLine":"有","exports":["TIMER_ACT_ATTR","TIMER_ACTS","TIMER_BOUND_ATTR","TIMER_BUSY_ATTR","TIMER_CARD_CLASS","TIMER_CARD_EMPTY_LINE","TIMER_CARD_FORMS","TIMER_CARD_MISSING","TIMER_CARD_SLOTS","TIMER_CARD_TICK_MS","TIMER_DISABLED_ATTR","TIMER_DISPLAY_ATTR","TIMER_ELAPSED_ATTR","TIMER_EVENT_DONE","TIMER_EVENT_STATE","TIMER_KEY_ATTR","TIMER_LOADING_LABEL","TIMER_PRIMARY_LABELS","TIMER_REMAIN_ATTR","TIMER_RESET_LABEL","TIMER_REST_ATTR","TIMER_STATES","TIMER_STATE_ATTR","TIMER_STATE_WORDS","TIMER_TAG_ATTR","TIMER_TOTAL_ATTR","timerCardClass","timerCardSlot","renderTimerCard","timerClockText","TIMER_CARD_BUTTON_MIN_HEIGHT_PX","TIMER_CARD_BUTTON_MIN_WIDTH_PX","TIMER_CARD_CONTAINER","TIMER_CARD_NARROW_MAX_PX","TIMER_CARD_VALUE_PX","timerCardCss","buildTimerCardJs"],"variants":["TIMER_CARD_SLOTS=('head','title','tag','display','display-value','display-unit','bar','bar-fill','readouts','hint','acts','button','error','absent')","TIMER_CARD_FORMS=('card')","TIMER_STATES=('idle','running','paused','done')","TIMER_ACTS=('toggle','reset')"],"render":"renderTimerCard","style":"timerCardCss","familyCss":"","runtime":"有（runtime.ts：buildTimerCardJs）","readme":"有","sample":{"key":"示例","title":"示例","totalSeconds":1}},
  {"name":"tooltip","cn":"气泡说明（形态 B 宽气泡 · 带「为什么重要」）","family":"—","layerLine":"有","exports":["TOOLTIP_ANCHOR_PREFIX","TOOLTIP_ANCHOR_QUERY","TOOLTIP_ATTR","TOOLTIP_BADGES","TOOLTIP_BADGE_TEXT","TOOLTIP_BOUND_ATTR","TOOLTIP_BUBBLE_ATTR","TOOLTIP_CLASS","TOOLTIP_EDGE_PX","TOOLTIP_FORMS","TOOLTIP_HINT","TOOLTIP_HIT_INSET_Y_PX","TOOLTIP_HIT_PX","TOOLTIP_MARK","TOOLTIP_OFFSET_PX","TOOLTIP_SLOTS","TOOLTIP_WHY_LABEL","TOOLTIP_WIDTH_PX","TOOLTIP_WORD_ATTR","tooltipClass","tooltipSlot","renderTooltip","tooltipCss","buildTooltipJs"],"variants":["TOOLTIP_FORMS=('wide')","TOOLTIP_BADGES=('caliber','field')"],"render":"renderTooltip","style":"tooltipCss","familyCss":"","runtime":"有（runtime.ts：buildTooltipJs）","readme":"有","sample":{"id":"示例","word":"示例","title":"示例","text":"示例","why":"示例"}},
  {"name":"window-picker","cn":"窗口选择器（形态 A）","family":"—","layerLine":"有","exports":["WINDOW_BOUND_ATTR","WINDOW_CUSTOM","WINDOW_DAYS_ATTR","WINDOW_DEFAULTS","WINDOW_DISABLED_ATTR","WINDOW_EMPTY_ATTR","WINDOW_ERROR_ATTR","WINDOW_EVENT_CHANGE","WINDOW_EVENT_LOADING","WINDOW_FORM_ATTR","WINDOW_FORMS","WINDOW_FROM_ATTR","WINDOW_INVALID_ATTR","WINDOW_LAST_ATTR","WINDOW_LOADING_ATTR","WINDOW_NAME_ATTR","WINDOW_PRESET_ATTR","WINDOW_PRESET_DAYS_ATTR","WINDOW_ROOT_CLASS","WINDOW_RUNTIME_ATTR","WINDOW_STATUS_ATTR","WINDOW_TODAY_ATTR","WINDOW_TO_ATTR","DAY_TEMPLATE","renderWindowPicker","windowErrorId","isoDayCount","normalizeWindowPicker","shiftIso","windowPickerCss","WINDOW_DATE_BASIS_PX","WINDOW_DATE_MAX_PX","WINDOW_MAX_WIDTH_PX","WINDOW_TOUCH_MIN_PX","buildWindowPickerJs"],"variants":["WINDOW_FORMS=('A')"],"render":"renderWindowPicker","style":"windowPickerCss","familyCss":"","runtime":"有（runtime.ts：buildWindowPickerJs）","readme":"有","sample":null},
];

/** 同一份数据的人读表（表头 ＋ 每件一行）。 */
export const COMPONENTS_TABLE: string = [
  "件名 | 中文名 | 族 | 层出口 | 出口给的名字 | 形态闭集 | 样式函数名 | 运行时段 | 说明书 | 示例入参",
  "calendar-month | 月历格 | — | 有 | CALENDAR_MONTH_CLASS、CALENDAR_MONTH_FORMS、CALENDAR_MONTH_LEVELS、CALENDAR_MONTH_MAX_WEEKS、CALENDAR_MONTH_MISSING、CALENDAR_MONTH_SLOTS、CALENDAR_MONTH_TODAY_MARK、CALENDAR_MONTH_WEEKDAYS、CALENDAR_MONTH_WEEK_LENGTH、calendarMonthSlot、renderCalendarMonth、CALENDAR_MONTH_BAR_HEIGHT_PX、CALENDAR_MONTH_CELL_MIN_HEIGHT_PX、CALENDAR_MONTH_LEVEL_HEIGHTS_PX、CALENDAR_MONTH_NARROW_PX、calendarMonthCss | CALENDAR_MONTH_FORMS=('grid') | calendarMonthCss | 无 | 有 | {\"title\":\"示例\",\"cells\":[{\"day\":\"示例\",\"value\":\"示例\"}]}",
  "compare-columns | 双列对照 | — | 有 | COMPARE_COLUMNS_CALIBER_LABEL、COMPARE_COLUMNS_CLASS、COMPARE_COLUMNS_DIFF_LABEL、COMPARE_COLUMNS_DIRECTIONS、COMPARE_COLUMNS_DOWN、COMPARE_COLUMNS_FLAT、COMPARE_COLUMNS_FORMS、COMPARE_COLUMNS_MINUS、COMPARE_COLUMNS_PLUS、COMPARE_COLUMNS_SENSES、COMPARE_COLUMNS_SLOTS、COMPARE_COLUMNS_UP、compareColumnsDirectionClass、compareColumnsSideClass、compareColumnsSlot、compareColumnsToneClass、renderCompareColumns、COMPARE_COLUMNS_BAR_MIN_PX、COMPARE_COLUMNS_BAR_THICKNESS_PX、COMPARE_COLUMNS_LABEL_BAND_EM、COMPARE_COLUMNS_NARROW_PX、compareColumnsCss | COMPARE_COLUMNS_FORMS=('back-to-back')、COMPARE_COLUMNS_DIRECTIONS=('up','down','flat')、COMPARE_COLUMNS_SENSES=('neutral','up-good','down-good') | compareColumnsCss | 无 | 有 | {\"leftLabel\":\"示例\",\"rightLabel\":\"示例\",\"rows\":[{\"label\":\"示例\",\"left\":1,\"right\":1}]}",
  "confirm-strip | 二次确认条 | — | 有 | CONFIRM_STRIP_ACTS、CONFIRM_STRIP_BARE_WORDS、CONFIRM_STRIP_BACKUP_ATTR、CONFIRM_STRIP_BACKUP_DEFAULT、CONFIRM_STRIP_BOUND_ATTR、CONFIRM_STRIP_CLASS、CONFIRM_STRIP_COUNT_ATTR、CONFIRM_STRIP_EVENT_CANCEL、CONFIRM_STRIP_EVENT_COMMIT、CONFIRM_STRIP_FORM_ATTR、CONFIRM_STRIP_FORMS、CONFIRM_STRIP_IRREVERSIBLE_ATTR、CONFIRM_STRIP_KEEP_DEFAULT、CONFIRM_STRIP_LOSS_DEFAULT、CONFIRM_STRIP_SLOTS、CONFIRM_STRIP_STATES、CONFIRM_STRIP_STATE_ATTR、CONFIRM_STRIP_UNIT_ATTR、CONFIRM_STRIP_UNIT_DEFAULT、confirmStripSlot、renderConfirmStrip、CONFIRM_STRIP_ACTIVE_SCALE、CONFIRM_STRIP_NARROW_PX、CONFIRM_STRIP_TOUCH_MIN_PX、CONFIRM_STRIP_TRANSITION_MS、confirmStripCss、buildConfirmStripJs | CONFIRM_STRIP_FORMS=('list')、CONFIRM_STRIP_STATES=('rest','busy','disabled')、CONFIRM_STRIP_ACTS=('keep','danger')、CONFIRM_STRIP_BARE_WORDS=('确定','确认','好','好的','是','是的','行','可以','提交','继续','下一步','OK','ok','yes','no') | confirmStripCss | 有（runtime.ts：buildConfirmStripJs） | 有 | {\"dangerVerb\":\"示例\",\"count\":1,\"undoable\":false,\"items\":[{\"name\":\"示例\"}]}",
  "date-range | 日期范围 | — | 有 | DATE_RANGE_CELLS、DATE_RANGE_CLASS、DATE_RANGE_COLUMNS、DATE_RANGE_CUSTOM、DATE_RANGE_DAYS_ATTR、DATE_RANGE_EVENT_CHANGE、DATE_RANGE_FORMS、DATE_RANGE_FROM_ATTR、DATE_RANGE_GAP_PX、DATE_RANGE_HIT_ATTR、DATE_RANGE_MISSING、DATE_RANGE_NAME_ATTR、DATE_RANGE_PRESET_ATTR、DATE_RANGE_TO_ATTR、DATE_RANGE_TOUCH_PX、DATE_RANGE_UNSET、DATE_RANGE_WEEK_LABELS、isIsoDate、monthCells、rangeDays、shiftMonth、renderDateRange、sentenceOf、dateRangeCss、buildDateRangeJs | DATE_RANGE_FORMS=('calendar')、DATE_RANGE_ACTIONS=('preset','day','prev','next')、DATE_RANGE_WEEK_LABELS=('一','二','三','四','五','六','日') | dateRangeCss | 有（runtime.ts：buildDateRangeJs） | 有 | {\"name\":\"示例\"}",
  "dialog | 对话框（形态 A 确认型） | — | 有 | DIALOG_ACT_ATTR、DIALOG_ATTR、DIALOG_BOUND_ATTR、DIALOG_CLASS、DIALOG_CLOSE_REASONS、DIALOG_EDGE_PX、DIALOG_EVENT_CLOSE、DIALOG_EVENT_OPEN、DIALOG_FORMS、DIALOG_MAX_WIDTH_PX、DIALOG_MIN_HEIGHT_PX、DIALOG_OPEN_ATTR、DIALOG_OPENER_CLASS、DIALOG_SLOTS、DIALOG_STATUS_ATTR、DIALOG_STATUS_KINDS、DIALOG_TONES、dialogClass、dialogOpenerClass、dialogSlot、renderDialog、renderDialogOpener、dialogCss、dialogEdgeMix、dialogHaloMix、dialogScrimMix、buildDialogJs | DIALOG_FORMS=('confirm')、DIALOG_TONES=('plain','warn','danger')、DIALOG_STATUS_KINDS=('error','busy')、DIALOG_CLOSE_REASONS=('action','esc','backdrop','programmatic') | dialogCss | 有（runtime.ts：buildDialogJs） | 有 | {\"id\":\"示例\",\"title\":\"示例\",\"body\":[{}],\"actions\":[{\"label\":\"示例\",\"value\":\"示例\"}]}",
  "drawer-sheet | 底部弹层（形态 C 多选 ＋ 完成 N 项） | — | 有 | DRAWER_ATTR、DRAWER_BOUND_ATTR、DRAWER_CLASS、DRAWER_CLOSE_ATTR、DRAWER_CLOSE_REASONS、DRAWER_COUNT_ATTR、DRAWER_COUNT_LEAD、DRAWER_COUNT_UNIT、DRAWER_DONE_ATTR、DRAWER_DONE_TEMPLATE、DRAWER_EDGE_PX、DRAWER_EDGES、DRAWER_EVENT_CHANGE、DRAWER_EVENT_CLOSE、DRAWER_EVENT_DONE、DRAWER_FORMS、DRAWER_GAP_PX、DRAWER_MAX_WIDTH_PX、DRAWER_MIN_HEIGHT_PX、DRAWER_MISSING、DRAWER_NOTE_ATTR、DRAWER_OPEN_ATTR、DRAWER_OPT_ATTR、DRAWER_OPTION_MIN_HEIGHT_PX、DRAWER_SIDE_WIDTH_PX、DRAWER_SLOTS、DRAWER_TEMPLATE_ATTR、DRAWER_ZERO_ATTR、DRAWER_ZERO_NOTE、drawerClass、drawerOpenerClass、drawerSlot、renderDrawerOpener、renderDrawerSheet、drawerSheetCss、buildDrawerSheetJs | DRAWER_FORMS=('multi')、DRAWER_EDGES=('bottom','side')、DRAWER_CLOSE_REASONS=('done','dismiss','esc','backdrop','programmatic') | drawerSheetCss | 有（runtime.ts：buildDrawerSheetJs） | 有 | {\"id\":\"示例\",\"title\":\"示例\",\"options\":[{\"value\":\"示例\",\"label\":\"示例\"}]}",
  "due-row | 到期行 | — | 有 | DUE_ACT_ATTR、DUE_ACT_LABEL_ATTR、DUE_BOUND_ATTR、DUE_DISABLED_ATTR、DUE_EVENT_ACTION、DUE_KEY_ATTR、DUE_LABEL_ATTR、DUE_LOADING_ATTR、DUE_LOADING_LABEL、DUE_ROW_CLASS、DUE_ROW_FORMS、DUE_ROW_MISSING、DUE_ROW_SLOTS、DUE_ROW_TONES、DUE_TONE_ATTR、dueRowClass、dueRowSlot、renderDueRows、DUE_ROW_BUTTON_MIN_HEIGHT_PX、DUE_ROW_BUTTON_MIN_WIDTH_PX、DUE_ROW_CONTAINER、DUE_ROW_COUNT_PX、DUE_ROW_NARROW_MAX_PX、dueRowCss、buildDueRowJs | DUE_ROW_SLOTS=('head','heading','count','list','item','body','line1','tag','dot','name','meta','note','side','countdown','countdown-label','count-value','count-unit','due','act','button','act-note','err','foot','absent')、DUE_ROW_FORMS=('countdown')、DUE_ROW_TONES=('ok','warn','danger') | dueRowCss | 有（runtime.ts：buildDueRowJs） | 有 | {\"rows\":[{\"key\":\"示例\",\"name\":\"示例\",\"tone\":\"ok\",\"tag\":\"示例\",\"countdown\":\"示例\"}]}",
  "editable-value | 就地可编辑值（\"值即入口\"） | — | 有 | EDIT_AFFORDANCE_ATTR、EDIT_AFFORDANCES、EDIT_BOUND_ATTR、EDIT_DISABLED_ATTR、EDIT_DISPLAY_ATTR、EDIT_EVENT_CANCEL、EDIT_EVENT_COMMIT、EDIT_HIT_ATTR、EDIT_KINDS、EDIT_KIND_ATTR、EDIT_LABEL_ATTR、EDIT_MAX_ATTR、EDIT_MIN_ATTR、EDIT_NAME_ATTR、EDIT_OPTIONS_ATTR、EDIT_PLACEHOLDER_ATTR、EDIT_REQUIRED_ATTR、EDIT_STEP_ATTR、EDIT_UNIT_ATTR、EDIT_VALUE_ATTR、EDIT_VALUE_CLASS、renderEditableValue、editableValueCss、EDIT_VALUE_EDITOR_MAX_WIDTH_PX、EDIT_VALUE_MIN_HEIGHT_PX、buildEditableValueJs | EDIT_KINDS=('text','number','select','date')、EDIT_AFFORDANCES=('always','hover','none') | editableValueCss | 有（runtime.ts：buildEditableValueJs） | 有 | {\"name\":\"示例\",\"value\":\"示例\"}",
  "entry-rows | 明细行 | 单据族 | 有 | renderEntryRows、ENTRY_ROW_NOTE_INDENT_PX、ENTRY_ROW_TIME_MIN_WIDTH_PX、entryRowsCss | —（attrs.ts／render.ts 里抽不出 as const 字符串数组） | entryRowsCss（族汇总：sheetCss） | 无 | 有 | {\"rows\":[{\"name\":\"示例\",\"value\":\"示例\"}]}",
  "filter-chips | 筛选条（形态 A） | — | 有 | CHIPS_BOUND_ATTR、CHIPS_CLEAR_ATTR、CHIPS_DEFAULTS、CHIPS_DISABLED_ATTR、CHIPS_EMPTY_ATTR、CHIPS_ERROR_ATTR、CHIPS_EVENT_CHANGE、CHIPS_EVENT_LOADING、CHIPS_FORM_ATTR、CHIPS_FORMS、CHIPS_INVALID_ATTR、CHIPS_LOADING_ATTR、CHIPS_MORE_ATTR、CHIPS_NAME_ATTR、CHIPS_PICKED_ATTR、CHIPS_REGION_ATTR、CHIPS_ROOT_CLASS、CHIPS_ROWS_ATTR、CHIPS_ROW_ATTR、CHIPS_RUNTIME_ATTR、CHIPS_STATUS_ATTR、CHIPS_TARGET_ATTR、CHIPS_TOTAL_ATTR、CHIP_ATTR、CHIP_ITEM_ATTR、CHIP_ITEM_TAGS_ATTR、CHIP_ITEM_VALUE_ATTR、CHIP_N_ATTR、chipsErrorId、renderFilterChips、filterChipsCss、CHIPS_MAX_WIDTH_PX、CHIPS_STATUS_MIN_CH、CHIPS_TOUCH_MIN_PX、buildFilterChipsJs | CHIPS_FORMS=('A') | filterChipsCss | 有（runtime.ts：buildFilterChipsJs） | 有 | —（README 入参表抽不出）",
  "heat-grid | 热力格 | — | 有 | renderHeatGrid、HEAT_GRID_CLASS、HEAT_GRID_COLUMNS、HEAT_GRID_FORMS、HEAT_GRID_LEVEL_COUNT、HEAT_GRID_LEVEL_STOPS、HEAT_GRID_MISSING、HEAT_GRID_PEAK_MARK、HEAT_GRID_SLOTS、HEAT_GRID_WEEKDAYS、heatGridSlot、HEAT_GRID_ROW_PX、heatGridCss、heatGridLevel | HEAT_GRID_FORMS=('matrix')、HEAT_GRID_WEEKDAYS=('周一','周二','周三','周四','周五','周六','周日') | heatGridCss | 无 | 有 | {\"title\":\"示例\",\"rows\":[{\"label\":\"示例\",\"values\":[]}]}",
  "hour-band | 时段带 | — | 有 | HOUR_BAND_CLASS、HOUR_BAND_DEFAULT_TONE、HOUR_BAND_FORMS、HOUR_BAND_HOURS、HOUR_BAND_MINUTES_PER_DAY、HOUR_BAND_MISSING、HOUR_BAND_RULER_NARROW_PX、HOUR_BAND_SLOTS、HOUR_BAND_TEXT_MIN_FRACTION、HOUR_BAND_TONES、HOUR_BAND_UNRECORDED_LABEL、hourBandSlot、renderHourBand、HOUR_BAND_HEIGHT_PX、HOUR_BAND_RULER_FONT_PX、hourBandCss、hourBandClock、hourBandDuration、hourBandPercent | HOUR_BAND_FORMS=('band') | hourBandCss | 无 | 有 | {\"title\":\"示例\",\"intervals\":[{\"from / .to\":1,\"label\":\"示例\"}]}",
  "invoice-lines | 金额分解 | — | 有 | INVOICE_LINES_CLASS、INVOICE_LINES_DECIMALS、INVOICE_LINES_FORMS、INVOICE_LINES_KIND_MARKS、INVOICE_LINES_SEGMENT_MIN_PCT、INVOICE_LINES_SHARE_WORD、INVOICE_LINES_SYMBOL、INVOICE_LINES_TOTAL_LABEL、INVOICE_LINES_TOTAL_SCALE、INVOICE_LINES_WHY_ADD、INVOICE_LINES_WHY_CUT、INVOICE_LINE_KINDS、formatInvoiceAmount、renderInvoiceLines、INVOICE_LINES_INDENT_PX、INVOICE_LINES_RULE_PX、invoiceLinesCss | INVOICE_LINES_FORMS=('chain','waterfall')、INVOICE_LINE_KINDS=('base','cut','add') | invoiceLinesCss | 无 | 有 | {\"lines\":[{\"label\":\"示例\",\"amount\":1,\"kind\":\"base\",\"why\":\"示例\"}]}",
  "key-value-list | 档案行 | — | 有 | KEY_VALUE_CLASS、KEY_VALUE_FORMS、KEY_VALUE_MIN_ROW_PX、KEY_VALUE_MISSING、keyValueSlot、normalizeKeyValueList、renderKeyValueList、keyValueListCss | KEY_VALUE_FORMS=('rows') | keyValueListCss | 无 | 有 | {\"rows\":[{\"label\":\"示例\",\"value\":\"示例\"}]}",
  "ledger-rows | 账目行 | 单据族 | 有 | LEDGER_LEADERS、LEDGER_ROW_KINDS、renderLedgerRows、ledgerRowsCss | LEDGER_ROW_KINDS=('item','total')、LEDGER_LEADERS=('dots','none') | ledgerRowsCss（族汇总：sheetCss） | 无 | 有 | {\"rows\":[{\"label\":\"示例\",\"value\":\"示例\"}]}",
  "multi-checks | 多选清单 | — | 有 | MULTI_CHECKS_ACTION_ATTR、MULTI_CHECKS_ALL_ATTR、MULTI_CHECKS_ALL_TEXT、MULTI_CHECKS_AMOUNT_ATTR、MULTI_CHECKS_BOUND_ATTR、MULTI_CHECKS_CLASS、MULTI_CHECKS_EMPTY_TEXT、MULTI_CHECKS_EVENT_ACTION、MULTI_CHECKS_EVENT_CHANGE、MULTI_CHECKS_FORMS、MULTI_CHECKS_FORM_ATTR、MULTI_CHECKS_GROUP_ATTR、MULTI_CHECKS_ITEM_ATTR、MULTI_CHECKS_LOADING_ATTR、MULTI_CHECKS_LOADING_TEXT、MULTI_CHECKS_MONEY_ATTR、MULTI_CHECKS_NAME_ATTR、MULTI_CHECKS_NONE_TEXT、MULTI_CHECKS_PARTIAL_ATTR、MULTI_CHECKS_PRIMARY_ATTR、MULTI_CHECKS_SLOTS、MULTI_CHECKS_UNIT_ATTR、multiChecksSlot、renderMultiChecks、MULTI_CHECKS_BAR_PX、MULTI_CHECKS_BOX_PX、MULTI_CHECKS_MIN_TARGET_PX、MULTI_CHECKS_NARROW_PX、MULTI_CHECKS_ROW_MIN_HEIGHT_PX、multiChecksCss、buildMultiChecksJs | MULTI_CHECKS_FORMS=('grouped') | multiChecksCss | 有（runtime.ts：buildMultiChecksJs） | 有 | {\"name\":\"示例\",\"label\":\"示例\",\"rows\":[{\"id\":\"示例\",\"title\":\"示例\"}]}",
  "note-block | 备注块 | — | 有 | NOTE_BLOCK_ATT_PREFIX、NOTE_BLOCK_CLASS、NOTE_BLOCK_COLLAPSE_CHARS、NOTE_BLOCK_ELLIPSIS、NOTE_BLOCK_FORMS、NOTE_BLOCK_LEN_SUFFIX、NOTE_BLOCK_PEEK_CHARS、NOTE_BLOCK_TONES、renderNoteBlock、NOTE_BLOCK_INDENT_PX、NOTE_BLOCK_RULE_PX、NOTE_BLOCK_TOUCH_PX、noteBlockCss | NOTE_BLOCK_FORMS=('note')、NOTE_BLOCK_TONES=('quiet','warn','danger') | noteBlockCss | 无 | 有 | {\"text\":\"示例\",\"toneLabel\":\"示例\"}",
  "number-stepper | 数量步进 | — | 有 | NUMBER_STEPPER_AT_MAX、NUMBER_STEPPER_AT_MIN、NUMBER_STEPPER_CLASS、NUMBER_STEPPER_EVENT_CHANGE、NUMBER_STEPPER_FORMS、NUMBER_STEPPER_GAP_PX、NUMBER_STEPPER_HIT_ATTR、NUMBER_STEPPER_MISSING、NUMBER_STEPPER_NAME_ATTR、NUMBER_STEPPER_TOUCH_PX、NUMBER_STEPPER_UNSET、NUMBER_STEPPER_VALUE_ATTR、NUMBER_STEPPER_VALUE_MIN_PX、formatStepperValue、renderNumberStepper、numberStepperCss、buildNumberStepperJs | NUMBER_STEPPER_FORMS=('standard')、NUMBER_STEPPER_ACTIONS=('dec','inc','quick','edit') | numberStepperCss | 有（runtime.ts：buildNumberStepperJs） | 有 | {\"name\":\"示例\",\"value\":1,\"min\":1,\"max\":1,\"step\":1}",
  "page-head | 页头 | — | 有 | PAGE_HEAD_CLASS、PAGE_HEAD_FORMS、renderPageHead、PAGE_HEAD_READING_SCALE、pageHeadCss | PAGE_HEAD_FORMS=('hero') | pageHeadCss | 无 | 有 | {\"skill\":\"示例\",\"title\":\"示例\",\"reading\":{\"value\":\"示例\"}}",
  "photo-compare | 前后对比 | — | 有 | PHOTO_COMPARE_CLASS、PHOTO_COMPARE_FORMS、PHOTO_COMPARE_MIN_HIT_PX、PHOTO_COMPARE_MISSING、PHOTO_COMPARE_SPLIT_VAR、PHOTO_COMPARE_STEP、PHOTO_COMPARE_TONES、PHOTO_COMPARE_TONE_MARKS、renderPhotoCompare、buildPhotoCompareJs、PHOTO_COMPARE_MARK_ARM_PX、PHOTO_COMPARE_NARROW_PX、PHOTO_COMPARE_STAGE_MAX_PX、photoCompareCss | PHOTO_COMPARE_FORMS=('drag')、PHOTO_COMPARE_TONES=('down','up','same') | photoCompareCss | 有（runtime.ts：buildPhotoCompareJs） | 有 | {\"before\":\"示例\",\"after\":\"示例\",\"deltas\":[{\"label\":\"示例\",\"before\":\"示例\",\"after\":\"示例\",\"change\":\"示例\"}]}",
  "photo-grid | 照片网格 | — | 有 | PHOTO_GRID_ADD_LABEL、PHOTO_GRID_ADD_MARK、PHOTO_GRID_CLASS、PHOTO_GRID_EMPTY_TEXT、PHOTO_GRID_FORMS、PHOTO_GRID_MIN_STACK、PHOTO_GRID_MISSING、PHOTO_GRID_RATIOS、renderPhotoGrid、PHOTO_GRID_MARK_ARM_PX、PHOTO_GRID_MARK_INSET_PX、PHOTO_GRID_MARK_THICK_PX、PHOTO_GRID_THREE_COL_PX、PHOTO_GRID_TOUCH_PX、photoGridCss | PHOTO_GRID_FORMS=('grid')、PHOTO_GRID_RATIOS=('4-5','1-1','3-4','4-3') | photoGridCss | 无 | 有 | {\"photos\":[{\"alt\":\"示例\"}],\"groups\":[{\"month\":\"示例\"}]}",
  "popover-menu | 浮出菜单（形态 A 贴着按钮） | — | 有 | MENU_ALIGNS、MENU_ANCHOR_PREFIX、MENU_ANCHOR_QUERY、MENU_AREA_QUERY、MENU_ATTR、MENU_BOUND_ATTR、MENU_CARET、MENU_CLASS、MENU_EDGE_PX、MENU_EVENT_SELECT、MENU_EVENT_TOGGLE、MENU_FORMS、MENU_GAP_PX、MENU_ITEM_ATTR、MENU_KINDS、MENU_MAX_HEIGHT_PX、MENU_MIN_HEIGHT_PX、MENU_OFFSET_PX、MENU_PANEL_ATTR、MENU_SLOTS、MENU_TICK、MENU_TRIGGER_ATTR、MENU_WIDTH_PX、menuClass、menuSlot、renderPopoverMenu、popoverMenuCss、buildPopoverMenuJs | MENU_FORMS=('hug')、MENU_ALIGNS=('start','end')、MENU_KINDS=('action','check','danger') | popoverMenuCss | 有（runtime.ts：buildPopoverMenuJs） | 有 | {\"id\":\"示例\",\"trigger\":\"示例\",\"items\":[{\"value\":\"示例\",\"label\":\"示例\"}]}",
  "progress-list | 多目标进度 | — | 有 | PROGRESS_LIST_CLASS、PROGRESS_LIST_FORMS、PROGRESS_LIST_MISSING、PROGRESS_LIST_STATES、PROGRESS_LIST_STATE_WORDS、PROGRESS_LIST_TONES、formatProgressNumber、renderProgressList、PROGRESS_LIST_NARROW_PX、PROGRESS_LIST_TRACK_HEIGHT_PX、progressListCss | PROGRESS_LIST_FORMS=('rows')、PROGRESS_LIST_STATES=('blank','on-track','done','over')、PROGRESS_LIST_TONES=('none','ok','warn','danger') | progressListCss | 无 | 有 | {\"rows\":[{\"label\":\"示例\",\"current\":1,\"goal\":1}]}",
  "progress-ring | 进度环 | — | 有 | renderProgressRing、PROGRESS_RING_ARC_LEN、PROGRESS_RING_CLASS、PROGRESS_RING_FORMS、PROGRESS_RING_MISSING、PROGRESS_RING_RADIUS_PX、PROGRESS_RING_SLOTS、PROGRESS_RING_STROKE_PX、progressRingSlot、PROGRESS_RING_MAX_DIAMETER_PX、PROGRESS_RING_VALUE_PX、progressRingCss | PROGRESS_RING_FORMS=('arc') | progressRingCss | 无 | 有 | {\"title\":\"示例\",\"value\":1,\"goal\":1}",
  "punch-strip | 打孔格带 | 单据族 | 有 | PUNCH_STRIP_EMPTY_MARK、PUNCH_STRIP_MAX_CELLS、renderPunchStrip、PUNCH_STRIP_BOX_HEIGHT_PX、PUNCH_STRIP_BOX_RADIUS_PX、punchStripCss | —（attrs.ts／render.ts 里抽不出 as const 字符串数组） | punchStripCss（族汇总：sheetCss） | 无 | 有 | {\"days\":[{\"label\":\"示例\",\"value\":\"示例\"}]}",
  "radio-cards | 单选卡组 | — | 有 | RADIO_CARDS_BOUND_ATTR、RADIO_CARDS_CLASS、RADIO_CARDS_EMPTY_TEXT、RADIO_CARDS_EVENT_CHANGE、RADIO_CARDS_FORMS、RADIO_CARDS_FORM_ATTR、RADIO_CARDS_LEAD_MAX、RADIO_CARDS_LOADING_ATTR、RADIO_CARDS_LOADING_TEXT、RADIO_CARDS_NAME_ATTR、RADIO_CARDS_OPTION_ATTR、RADIO_CARDS_REQUIRED_ATTR、RADIO_CARDS_SLOTS、RADIO_CARDS_VALUE_ATTR、radioCardsSlot、renderRadioCards、RADIO_CARDS_BAR_PX、RADIO_CARDS_CARD_MIN_HEIGHT_PX、RADIO_CARDS_MIN_TARGET_PX、RADIO_CARDS_NARROW_PX、radioCardsCss、buildRadioCardsJs | RADIO_CARDS_FORMS=('cards') | radioCardsCss | 有（runtime.ts：buildRadioCardsJs） | 有 | {\"name\":\"示例\",\"label\":\"示例\",\"options\":[{\"value\":\"示例\",\"title\":\"示例\"}]}",
  "range-bar | 区间条 | — | 有 | RANGE_BAR_CLASS、RANGE_BAR_DEFAULT_TONE、RANGE_BAR_FORMS、RANGE_BAR_NARROW_PX、RANGE_BAR_SLOTS、RANGE_BAR_TEXT_HIDE_BELOW_PX、RANGE_BAR_TEXT_MIN_FRACTION、RANGE_BAR_TONES、rangeBarSlot、renderRangeBar、RANGE_BAR_KEY_COLUMN_NARROW_PX、RANGE_BAR_KEY_COLUMN_PX、RANGE_BAR_RAIL_HEIGHT_PX、RANGE_BAR_TICK_GAP_PX、RANGE_BAR_TOTAL_COLUMN_NARROW_PX、RANGE_BAR_TOTAL_COLUMN_PX、rangeBarCss | RANGE_BAR_FORMS=('lanes') | rangeBarCss | 无 | 有 | {\"title\":\"示例\",\"domain\":{},\"lanes\":[{\"label\":\"示例\",\"intervals\":[]}],\"intervals\":[{\"from / .to\":1}]}",
  "rank-list | 榜单 | — | 有 | RANK_LIST_CALIBER_LABEL、RANK_LIST_CLASS、RANK_LIST_FORMS、RANK_LIST_PODIUM_SIZE、RANK_LIST_SLOTS、rankListPlaceClass、rankListSlot、renderRankList、RANK_LIST_BAR_MIN_PX、RANK_LIST_BAR_THICKNESS_PX、RANK_LIST_CARD_MIN_EM、RANK_LIST_FIRST_VALUE_SCALE、RANK_LIST_NARROW_PX、rankListCss | RANK_LIST_FORMS=('podium') | rankListCss | 无 | 有 | {\"rows\":[{\"name\":\"示例\",\"value\":1,\"share\":1}]}",
  "rating-row | 评分行 | — | 有 | RATING_ROW_BOUND_ATTR、RATING_ROW_CLASS、RATING_ROW_DEFAULT_MAX、RATING_ROW_DISABLED_ATTR、RATING_ROW_EVENT_CHANGE、RATING_ROW_FORMS、RATING_ROW_FORM_ATTR、RATING_ROW_HALF_ATTR、RATING_ROW_LOADING_ATTR、RATING_ROW_LOADING_TEXT、RATING_ROW_MAX_ATTR、RATING_ROW_MAX_MAX、RATING_ROW_MISSING、RATING_ROW_NAME_ATTR、RATING_ROW_SLOTS、RATING_ROW_STAR_ATTR、RATING_ROW_STAR_LABEL_SUFFIX、RATING_ROW_VALUE_ATTR、ratingRowSlot、renderRatingRow、RATING_ROW_NARROW_PX、RATING_ROW_NUM_SCALE、RATING_ROW_STAR_FONT_PX、RATING_ROW_STAR_PX、ratingRowCss、buildRatingRowJs | RATING_ROW_FORMS=('stars') | ratingRowCss | 有（runtime.ts：buildRatingRowJs） | 有 | {\"name\":\"示例\",\"label\":\"示例\"}",
  "result-row | 结果行（形态 A） | — | 有 | RESULT_DEFAULTS、RESULT_EMPTY_ATTR、RESULT_FORM_ATTR、RESULT_FORMS、RESULT_ITEM_ATTR、RESULT_NAME_ATTR、RESULT_ROOT_CLASS、RESULT_SEARCH_HIT_ATTR、RESULT_SEARCH_ITEM_ATTR、RESULT_SEARCH_REGION_ATTR、RESULT_SEARCH_TAGS_ATTR、markTerms、renderResultRow、resultRowCss、RESULT_MAX_WIDTH_PX、RESULT_ROW_MIN_PX、RESULT_THUMB_PX、RESULT_TOUCH_MIN_PX | RESULT_FORMS=('A') | resultRowCss | 无 | 有 | —（README 入参表抽不出）",
  "scale-bar | 刻度条 | 单据族 | 有 | SCALE_BAR_DEFAULT_CELLS、SCALE_BAR_VARIANTS、renderScaleBar、SCALE_BAR_CELL_HEIGHT_PX、SCALE_BAR_LINE_HEIGHT_PX、scaleBarCss | SCALE_BAR_VARIANTS=('cells','line') | scaleBarCss（族汇总：sheetCss） | 无 | 有 | {\"value\":1,\"goal\":1}",
  "search-field | 搜索框（形态 B） | — | 有 | SEARCH_AT_ATTR、SEARCH_BOUND_ATTR、SEARCH_CLEAR_ATTR、SEARCH_COUNT_ATTR、SEARCH_CURRENT_ATTR、SEARCH_DEFAULTS、SEARCH_DISABLED_ATTR、SEARCH_EMPTY_ATTR、SEARCH_ERROR_ATTR、SEARCH_EVENT_JUMP、SEARCH_EVENT_LOADING、SEARCH_EVENT_QUERY、SEARCH_FORM_ATTR、SEARCH_FORMS、SEARCH_HIT_ATTR、SEARCH_INPUT_ATTR、SEARCH_INVALID_ATTR、SEARCH_ITEM_ATTR、SEARCH_LOADING_ATTR、SEARCH_LOADING_TEXT_ATTR、SEARCH_NAME_ATTR、SEARCH_NEXT_ATTR、SEARCH_N_ATTR、SEARCH_POS_ATTR、SEARCH_PREV_ATTR、SEARCH_READOUT_ATTR、SEARCH_REGION_ATTR、SEARCH_ROOT_CLASS、SEARCH_RUNTIME_ATTR、SEARCH_SCOPE_ATTR、SEARCH_SCOPE_NAME_ATTR、SEARCH_STATUS_ATTR、SEARCH_TAGS_ATTR、SEARCH_TARGET_ATTR、searchErrorId、renderSearchField、searchFieldCss、SEARCH_MAX_WIDTH_PX、SEARCH_STATUS_MIN_CH、SEARCH_TOUCH_MIN_PX、buildSearchFieldJs | SEARCH_FORMS=('B') | searchFieldCss | 有（runtime.ts：buildSearchFieldJs） | 有 | —（README 入参表抽不出）",
  "section-head | 小节头 | — | 有 | SECTION_HEAD_CLASS、SECTION_HEAD_FORMS、SECTION_HEAD_MORE_TEXTS、SECTION_HEAD_SEQ_MAX、SECTION_HEAD_SEQ_MIN、sectionHeadSlot、normalizeSectionHead、renderSectionHead、sectionHeadOrdinalText、SECTION_HEAD_SUM_MIN_PX、sectionHeadCss | SECTION_HEAD_FORMS=('fd') | sectionHeadCss | 无 | 有 | {\"title\":\"示例\",\"body\":\"示例\"}",
  "sheet-frame | 纸面页框 | 单据族 | 有 | SHEET_VARIANTS、renderSheetFrame、sheetCss、sheetFrameCss | SHEET_VARIANTS=('plain','receipt') | sheetFrameCss（族汇总：sheetCss） | 无 | 有 | {\"content\":\"示例\"}",
  "skeleton | 加载骨架 | — | 有 | SKELETON_CLASS、SKELETON_FORM_ATTR、SKELETON_FORMS、SKELETON_MAX_ROWS、SKELETON_ROWS_ATTR、SKELETON_SLOTS、skeletonSlot、renderSkeleton、SKELETON_NARROW_PX、SKELETON_PLACEHOLDER_MIX_PERCENT、SKELETON_PULSE_DURATION_MS、SKELETON_PULSE_MIN_OPACITY、SKELETON_PULSE_NAME、SKELETON_READING_SCALE、SKELETON_ROW_HEIGHT_PX、SKELETON_ROW_SEPARATOR_PX、SKELETON_STILL_OPACITY、SKELETON_VALUE_SLOT_PX、skeletonCss | SKELETON_FORMS=('reading-list') | skeletonCss | 无 | 有 | {\"label\":\"示例\",\"rows\":1}",
  "slider-row | 滑块行 | — | 有 | SLIDER_ROW_AT_MAX、SLIDER_ROW_AT_MIN、SLIDER_ROW_CLASS、SLIDER_ROW_EVENT_CHANGE、SLIDER_ROW_FORMS、SLIDER_ROW_GAP_PX、SLIDER_ROW_HIT_ATTR、SLIDER_ROW_LINE_PX、SLIDER_ROW_MISSING、SLIDER_ROW_NAME_ATTR、SLIDER_ROW_THUMB_PX、SLIDER_ROW_TOUCH_PX、SLIDER_ROW_TRACK_PX、SLIDER_ROW_UNSET、SLIDER_ROW_VALUE_ATTR、fillPercent、formatSliderValue、renderSliderRow、sliderRowCss、buildSliderRowJs | SLIDER_ROW_FORMS=('track')、SLIDER_ROW_ACTIONS=('dec','inc','preset') | sliderRowCss | 有（runtime.ts：buildSliderRowJs） | 有 | {\"name\":\"示例\",\"value\":1,\"min\":1,\"max\":1,\"step\":1}",
  "sort-toggle | 排序切换（形态 C） | — | 有 | SORT_BOUND_ATTR、SORT_CALIBER_ATTR、SORT_CALIBER_LINE_ATTR、SORT_CALIBER_TEXT_ATTR、SORT_DEFAULTS、SORT_DIRECTIONS、SORT_DIR_ATTR、SORT_DISABLED_ATTR、SORT_EMPTY_ATTR、SORT_ERROR_ATTR、SORT_EVENT_CHANGE、SORT_EVENT_LOADING、SORT_FIELD_ATTR、SORT_FLIP_ATTR、SORT_FLIP_LABEL_ATTR、SORT_FORM_ATTR、SORT_FORMS、SORT_INK_ATTR、SORT_INVALID_ATTR、SORT_ITEM_ATTR、SORT_ITEM_TAGS_ATTR、SORT_LOADING_ATTR、SORT_NAME_ATTR、SORT_N_ATTR、SORT_REGION_ATTR、SORT_ROOT_CLASS、SORT_RUNTIME_ATTR、SORT_SHOWN_ATTR、SORT_STATUS_ATTR、SORT_TARGET_ATTR、SORT_VIEW_ATTR、SORT_VIEW_LABEL_ATTR、sortErrorId、renderSortToggle、sortToggleCss、SORT_MAX_WIDTH_PX、SORT_STATUS_MIN_CH、SORT_TOUCH_MIN_PX、buildSortToggleJs | SORT_FORMS=('C')、SORT_DIRECTIONS=('desc','asc') | sortToggleCss | 有（runtime.ts：buildSortToggleJs） | 有 | —（README 入参表抽不出）",
  "stacked-bar | 构成条 | — | 有 | renderStackedBar、STACKED_BAR_CLASS、STACKED_BAR_FORMS、STACKED_BAR_MAX_SEGMENTS、STACKED_BAR_MISSING、STACKED_BAR_NAME_MIN_PCT、STACKED_BAR_SERIES、STACKED_BAR_SLOTS、STACKED_BAR_VALUE_MIN_PCT、stackedBarSlot、STACKED_BAR_HEIGHT_PX、stackedBarCss | STACKED_BAR_FORMS=('stack') | stackedBarCss | 无 | 有 | {\"title\":\"示例\",\"segments\":[{\"name\":\"示例\",\"value\":1}]}",
  "stat-inline | 行内读数 | — | 有 | STAT_INLINE_CLASS、STAT_INLINE_FORMS、STAT_INLINE_MISSING、STAT_INLINE_SEP、statInlineSlot、normalizeStatInline、renderStatInline、statInlineCss | STAT_INLINE_FORMS=('dots') | statInlineCss | 无 | 有 | {\"items\":[{\"value\":\"示例\"}]}",
  "status-row | 状态台账行 | — | 有 | STATUS_ROW_CLASS、STATUS_ROW_FORMS、STATUS_ROW_MISSING、STATUS_ROW_SLOTS、STATUS_ROW_TONES、statusRowClass、statusRowSlot、renderStatusRows、STATUS_ROW_CONTAINER、STATUS_ROW_ITEM_MIN_HEIGHT_PX、STATUS_ROW_NARROW_MAX_PX、STATUS_ROW_NODE_SIZE_PX、STATUS_ROW_RAIL_WIDTH_PX、statusRowCss | STATUS_ROW_FORMS=('ledger')、STATUS_ROW_TONES=('neutral','active','ok','warn','danger') | statusRowCss | 无 | 有 | {\"rows\":[{\"name\":\"示例\",\"phase\":\"示例\"}]}",
  "step-flow | 步骤条 | — | 有 | STEP_FLOW_CLASS、STEP_FLOW_FORMS、STEP_FLOW_MARK_DONE、STEP_FLOW_MISSING、STEP_FLOW_SLOTS、STEP_STATES、STEP_STATE_WORDS、stepFlowClass、stepFlowSlot、renderStepFlow、STEP_FLOW_CONTAINER、STEP_FLOW_NARROW_MAX_PX、STEP_FLOW_NODE_COLUMN_PX、STEP_FLOW_NODE_SIZE_PX、stepFlowCss | STEP_FLOW_SLOTS=('head','title','count','list','step','node','body','title-row','name','state','time','estimate','actual','desc','note','foot','absent')、STEP_FLOW_FORMS=('vertical')、STEP_STATES=('done','now','todo') | stepFlowCss | 无 | 有 | {\"steps\":[{\"title\":\"示例\",\"state\":\"done\"}]}",
  "streak-badge | 连记徽标 | — | 有 | STREAK_BADGE_CLASS、STREAK_BADGE_FORMS、STREAK_BADGE_MISSING、STREAK_BADGE_SLOTS、STREAK_STRENGTHS、streakBadgeClass、streakBadgeSlot、renderStreakBadges、STREAK_BADGE_CONTAINER、STREAK_BADGE_MIN_HEIGHT_PX、STREAK_BADGE_NARROW_MAX_PX、STREAK_BADGE_VALUE_PX、streakBadgeCss | STREAK_BADGE_SLOTS=('head','heading','list','badge','label','value','unit','absent')、STREAK_BADGE_FORMS=('row')、STREAK_STRENGTHS=('strong','mid','weak') | streakBadgeCss | 无 | 有 | {\"badges\":[{\"strength\":\"strong\",\"label\":\"示例\",\"value\":\"示例\"}]}",
  "sub-list | 分组清单 | — | 有 | SUB_LIST_CLASS、SUB_LIST_COUNT_UNIT、SUB_LIST_DONE_LABEL、SUB_LIST_FORMS、SUB_LIST_SLOTS、subListSlot、renderSubList、SUB_LIST_HEAD_MIN_HEIGHT_PX、SUB_LIST_NARROW_PX、SUB_LIST_PRESS_MS、subListCss | SUB_LIST_FORMS=('fold') | subListCss | 无 | 有 | {\"groups\":[{\"label\":\"示例\",\"items\":[]}],\"items\":[{\"label\":\"示例\"}]}",
  "summary-head | 主数字头 | 单据族 | 有 | SUMMARY_HEAD_FACES、SUMMARY_HEAD_SIZES、SUMMARY_HEAD_STAMP_TONES、renderSummaryHead、SUMMARY_HEAD_VALUE_PX、summaryHeadCss | SUMMARY_HEAD_SIZES=('m','l','xl')、SUMMARY_HEAD_FACES=('sans','serif')、SUMMARY_HEAD_STAMP_TONES=('ok','warn','danger') | summaryHeadCss（族汇总：sheetCss） | 无 | 有 | {\"value\":\"示例\"}",
  "sync-status | 同步状态 | — | 有 | SYNC_STATUS_ACTION_ATTR、SYNC_STATUS_ACTIONS、SYNC_STATUS_ATTR、SYNC_STATUS_BOUND_ATTR、SYNC_STATUS_CLASS、SYNC_STATUS_ERROR_ATTR、SYNC_STATUS_EVENT_DONE、SYNC_STATUS_EVENT_RUN、SYNC_STATUS_FAILED_TEXT、SYNC_STATUS_FORMS、SYNC_STATUS_RESULTS、SYNC_STATUS_RESULT_WORDS、SYNC_STATUS_RUNNING_LABEL、SYNC_STATUS_RUN_TIMEOUT_MS、SYNC_STATUS_STATES、SYNC_STATUS_STATE_ATTR、SYNC_STATUS_TIMEOUT_TEXT、renderSyncStatus、buildSyncStatusJs、SYNC_STATUS_NARROW_PX、SYNC_STATUS_TOUCH_PX、syncStatusCss | SYNC_STATUS_FORMS=('run')、SYNC_STATUS_RESULTS=('ok','failed','pending')、SYNC_STATUS_ACTIONS=('run')、SYNC_STATUS_STATES=('idle','running','failed') | syncStatusCss | 有（runtime.ts：buildSyncStatusJs） | 有 | {\"targets\":[{\"name\":\"示例\",\"result\":\"ok\",\"reason\":\"示例\",\"fix\":\"示例\"}]}",
  "task-list | 勾选清单 | — | 有 | TASK_BAR_ATTR、TASK_BOUND_ATTR、TASK_BUSY_ATTR、TASK_CHECK_CLASS、TASK_COUNTS_ATTR、TASK_COUNTS_SEPARATOR、TASK_DONE_ATTR、TASK_EVENT_TOGGLE、TASK_GROUP_ATTR、TASK_HIT_CLASS、TASK_KEY_ATTR、TASK_LABEL_ATTR、TASK_LABEL_CLASS、TASK_LIST_ATTR、TASK_LIST_CLASS、TASK_LIST_DEFAULT_KEY、TASK_LIST_FORMS、TASK_LIST_SLOTS、TASK_OF_ATTR、TASK_ROW_CLASS、TASK_ROW_DONE_CLASS、taskListClass、taskListSlot、renderTaskList、TASK_LIST_BAR_HEIGHT_PX、TASK_LIST_CHECK_SIZE_PX、TASK_LIST_CONTAINER、TASK_LIST_HIT_MIN_HEIGHT_PX、TASK_LIST_NARROW_MAX_PX、taskListCss、buildTaskListJs | TASK_LIST_FORMS=('checklist') | taskListCss | 有（runtime.ts：buildTaskListJs） | 有 | {\"rows\":[{\"key\":\"示例\",\"label\":\"示例\"}]}",
  "timer-card | 计时卡 | — | 有 | TIMER_ACT_ATTR、TIMER_ACTS、TIMER_BOUND_ATTR、TIMER_BUSY_ATTR、TIMER_CARD_CLASS、TIMER_CARD_EMPTY_LINE、TIMER_CARD_FORMS、TIMER_CARD_MISSING、TIMER_CARD_SLOTS、TIMER_CARD_TICK_MS、TIMER_DISABLED_ATTR、TIMER_DISPLAY_ATTR、TIMER_ELAPSED_ATTR、TIMER_EVENT_DONE、TIMER_EVENT_STATE、TIMER_KEY_ATTR、TIMER_LOADING_LABEL、TIMER_PRIMARY_LABELS、TIMER_REMAIN_ATTR、TIMER_RESET_LABEL、TIMER_REST_ATTR、TIMER_STATES、TIMER_STATE_ATTR、TIMER_STATE_WORDS、TIMER_TAG_ATTR、TIMER_TOTAL_ATTR、timerCardClass、timerCardSlot、renderTimerCard、timerClockText、TIMER_CARD_BUTTON_MIN_HEIGHT_PX、TIMER_CARD_BUTTON_MIN_WIDTH_PX、TIMER_CARD_CONTAINER、TIMER_CARD_NARROW_MAX_PX、TIMER_CARD_VALUE_PX、timerCardCss、buildTimerCardJs | TIMER_CARD_SLOTS=('head','title','tag','display','display-value','display-unit','bar','bar-fill','readouts','hint','acts','button','error','absent')、TIMER_CARD_FORMS=('card')、TIMER_STATES=('idle','running','paused','done')、TIMER_ACTS=('toggle','reset') | timerCardCss | 有（runtime.ts：buildTimerCardJs） | 有 | {\"key\":\"示例\",\"title\":\"示例\",\"totalSeconds\":1}",
  "tooltip | 气泡说明（形态 B 宽气泡 · 带「为什么重要」） | — | 有 | TOOLTIP_ANCHOR_PREFIX、TOOLTIP_ANCHOR_QUERY、TOOLTIP_ATTR、TOOLTIP_BADGES、TOOLTIP_BADGE_TEXT、TOOLTIP_BOUND_ATTR、TOOLTIP_BUBBLE_ATTR、TOOLTIP_CLASS、TOOLTIP_EDGE_PX、TOOLTIP_FORMS、TOOLTIP_HINT、TOOLTIP_HIT_INSET_Y_PX、TOOLTIP_HIT_PX、TOOLTIP_MARK、TOOLTIP_OFFSET_PX、TOOLTIP_SLOTS、TOOLTIP_WHY_LABEL、TOOLTIP_WIDTH_PX、TOOLTIP_WORD_ATTR、tooltipClass、tooltipSlot、renderTooltip、tooltipCss、buildTooltipJs | TOOLTIP_FORMS=('wide')、TOOLTIP_BADGES=('caliber','field') | tooltipCss | 有（runtime.ts：buildTooltipJs） | 有 | {\"id\":\"示例\",\"word\":\"示例\",\"title\":\"示例\",\"text\":\"示例\",\"why\":\"示例\"}",
  "window-picker | 窗口选择器（形态 A） | — | 有 | WINDOW_BOUND_ATTR、WINDOW_CUSTOM、WINDOW_DAYS_ATTR、WINDOW_DEFAULTS、WINDOW_DISABLED_ATTR、WINDOW_EMPTY_ATTR、WINDOW_ERROR_ATTR、WINDOW_EVENT_CHANGE、WINDOW_EVENT_LOADING、WINDOW_FORM_ATTR、WINDOW_FORMS、WINDOW_FROM_ATTR、WINDOW_INVALID_ATTR、WINDOW_LAST_ATTR、WINDOW_LOADING_ATTR、WINDOW_NAME_ATTR、WINDOW_PRESET_ATTR、WINDOW_PRESET_DAYS_ATTR、WINDOW_ROOT_CLASS、WINDOW_RUNTIME_ATTR、WINDOW_STATUS_ATTR、WINDOW_TODAY_ATTR、WINDOW_TO_ATTR、DAY_TEMPLATE、renderWindowPicker、windowErrorId、isoDayCount、normalizeWindowPicker、shiftIso、windowPickerCss、WINDOW_DATE_BASIS_PX、WINDOW_DATE_MAX_PX、WINDOW_MAX_WIDTH_PX、WINDOW_TOUCH_MIN_PX、buildWindowPickerJs | WINDOW_FORMS=('A') | windowPickerCss | 有（runtime.ts：buildWindowPickerJs） | 有 | —（README 入参表抽不出）",
].join("\n");
