/** timer-card · **样式段**（本件唯一的样式来源）。
 *
 *  三条纪律（与组件层其余件同一份）：
 *   1. 颜色／圆角／字面／字号一律经 `skinVar()` 读；本件源码里不出现手写的 `var(--ilife-…)`；
 *   2. 全部规则 scope 在 `.<prefix>page-ui` 之下；
 *   3. **状态靠「字 ＋ 形 ＋ 色」**：状态字（待开始／计时中／已暂停／到点了）＋ 标签形状
 *      （底线／实底块／描边空心／双线框）＋ 色 ⇒「大字报刊」皮肤下强调色＝墨黑也分得出。
 *
 *  交互件的地板（判据逐条断）：
 *   · 按钮命中盒 **≥44 高**、`min-width` 锁住（`TIMER_CARD_BUTTON_MIN_WIDTH_PX`）⇒
 *     「开始／暂停／继续／重新开始／开始中…」五种字换来换去**不跳版**；
 *   · 进度条只动 `transform: scaleX()`（不动宽度）；`:hover` 包在设备能力查询里且不是唯一通路；
 *   · `:active` 只动 `transform`（≤80ms）；`:focus-visible` 有 2px 可见焦点环；
 *   · `disabled` 有 `cursor:not-allowed`；`prefers-reduced-motion` 下过渡关掉、读数照走（不卡半路）；
 *   · 状态不依赖 `transitionend`（读数由运行时按时间写，不靠动画收尾）。
 *
 *  几何契约：大数字 `white-space:nowrap`（时间**永不截断**）；窄宽由**容器**决定。
 */
import { skinVar } from '../skin/contract.js';
import { timerCardClass, timerCardSlot, type TimerCardSlot } from './attrs.js';

/** 换行（仓库口径：不写字面换行转义）。 */
const LF = String.fromCharCode(10);

/** 本件的内容容器名（`@container` 按它命中）。 */
export const TIMER_CARD_CONTAINER = 'ilife-timer-card';
/** 窄档断点（px）：容器窄于它就让按钮各占一整行（**不是**视口断点）。 */
export const TIMER_CARD_NARROW_MAX_PX = 420;
/** 按钮的高度下限（px）：44 是全仓的触控地板。 */
export const TIMER_CARD_BUTTON_MIN_HEIGHT_PX = 44;
/** 按钮的宽度下限（px）：主按钮换字（开始／暂停／继续／重新开始／开始中…）时不跳版。 */
export const TIMER_CARD_BUTTON_MIN_WIDTH_PX = 112;
/** 大数字的字号（px）：一个显示级读数（与正文字号的比例 ≫2×）。 */
export const TIMER_CARD_VALUE_PX = 44;

/** 本组件的样式段。恒返回非空 CSS 文本。 */
export function timerCardCss(input?: { readonly prefix?: string }): string {
  const p = input !== undefined && input !== null
    && typeof input.prefix === 'string' && input.prefix !== '' ? input.prefix : 'ilife-';
  const root = '.' + p + 'page-ui';
  const sc = (name: TimerCardSlot): string => root + ' .' + timerCardSlot(name, p);
  const s = root + ' .' + timerCardClass(p);
  const v = skinVar;
  return [
    '/* timer-card（计时卡）：剩余时间当主读数（大数字 ＋ 进度条 ＋ 已过／还剩），底下开始／暂停／重置。 */',
    s + ' {',
    '  display: flex;',
    '  flex-direction: column;',
    '  gap: 8px;',
    '  box-sizing: border-box;',
    '  min-width: 0;',
    '  padding: 14px ' + v('pad-x') + ';',
    '  border: 1px solid ' + v('edge') + ';',
    '  border-radius: ' + v('radius') + ';',
    '  background: ' + v('surface') + ';',
    '  box-shadow: ' + v('shadow') + ';',
    '  container: ' + TIMER_CARD_CONTAINER + ' / inline-size;',
    '}',
    sc('head') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 4px 10px;',
    '  min-width: 0;',
    '}',
    sc('title') + ' {',
    '  min-width: 0;',
    '  color: ' + v('ink') + ';',
    '  font-size: ' + v('fs-sm') + ';',
    '  font-weight: 700;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 状态字四档形状：底线／实底块／描边空心／双线框。 */',
    sc('tag') + ' {',
    '  flex: 0 0 auto;',
    '  box-sizing: border-box;',
    '  margin-left: auto;',
    '  padding: 1px 8px;',
    '  border: 1px solid transparent;',
    '  border-radius: ' + v('radius-pill') + ';',
    '  color: ' + v('ink-2') + ';',
    '  font-size: ' + v('fs-xs') + ';',
    '  font-weight: 700;',
    '  line-height: 1.5;',
    '  white-space: nowrap;',
    '}',
    sc('tag') + '.is-idle {',
    '  padding: 0 0 1px;',
    '  border: 0;',
    '  border-bottom: 2px solid ' + v('line') + ';',
    '  border-radius: 0;',
    '}',
    sc('tag') + '.is-running {',
    '  border: 0;',
    '  background: ' + v('accent') + ';',
    '  color: ' + v('accent-ink') + ';',
    '}',
    sc('tag') + '.is-paused {',
    '  border: 1px solid ' + v('warn') + ';',
    '  background: ' + v('warn-soft') + ';',
    '  color: ' + v('warn') + ';',
    '}',
    sc('tag') + '.is-done {',
    '  border: 3px double ' + v('ok') + ';',
    '  border-radius: 0;',
    '  color: ' + v('ok') + ';',
    '}',
    '/* 主读数：大数字 ＋ 单位。 */',
    sc('display') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 6px;',
    '  min-width: 0;',
    '}',
    sc('display-value') + ' {',
    '  color: ' + v('ink') + ';',
    '  font-family: ' + v('font-display') + ';',
    '  font-size: ' + TIMER_CARD_VALUE_PX + 'px;',
    '  font-variant-numeric: tabular-nums;',
    '  font-weight: 800;',
    '  line-height: 1.02;',
    '  letter-spacing: -.02em;',
    '  white-space: nowrap;',
    '}',
    sc('display-unit') + ' {',
    '  color: ' + v('ink-2') + ';',
    '  font-size: ' + v('fs-xs') + ';',
    '  font-weight: 700;',
    '}',
    '/* 进度条：只动 transform（宽度不变 ⇒ 不重排）。 */',
    sc('bar') + ' {',
    '  height: 8px;',
    '  border-radius: ' + v('radius-pill') + ';',
    '  background: ' + v('surface-2') + ';',
    '  overflow: hidden;',
    '}',
    sc('bar-fill') + ' {',
    '  display: block;',
    '  height: 100%;',
    '  transform-origin: left center;',
    '  transform: scaleX(0);',
    '  background: ' + v('accent') + ';',
    '  transition: transform 180ms linear;',
    '}',
    sc('readouts') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 4px 14px;',
    '  color: ' + v('ink-3') + ';',
    '  font-size: ' + v('fs-xs') + ';',
    '}',
    sc('readouts') + ' b {',
    '  color: ' + v('ink-2') + ';',
    '  font-family: ' + v('font-num') + ';',
    '  font-variant-numeric: tabular-nums;',
    '  font-weight: 700;',
    '}',
    sc('hint') + ' {',
    '  margin: 2px 0 0;',
    '  padding: 9px 11px;',
    '  border-left: 3px solid ' + v('accent') + ';',
    '  border-radius: ' + v('radius-sm') + ';',
    '  background: ' + v('surface-2') + ';',
    '  color: ' + v('ink-2') + ';',
    '  font-size: ' + v('fs-xs') + ';',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    sc('acts') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: center;',
    '  gap: 8px;',
    '  margin-top: 2px;',
    '  min-width: 0;',
    '}',
    '/* 按钮：真按钮。命中盒 44 高、宽度锁住（换字不跳版）。 */',
    sc('button') + ' {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  box-sizing: border-box;',
    '  flex: 0 1 auto;',
    '  min-height: ' + TIMER_CARD_BUTTON_MIN_HEIGHT_PX + 'px;',
    '  min-width: ' + TIMER_CARD_BUTTON_MIN_WIDTH_PX + 'px;',
    '  padding: 0 14px;',
    '  border: 1px solid ' + v('accent') + ';',
    '  border-radius: ' + v('radius-sm') + ';',
    '  background: ' + v('accent') + ';',
    '  color: ' + v('accent-ink') + ';',
    '  font: inherit;',
    '  font-size: ' + v('fs-sm') + ';',
    '  font-weight: 700;',
    '  white-space: nowrap;',
    '  cursor: pointer;',
    '  transition: transform 60ms linear;',
    '}',
    sc('button') + '.is-quiet {',
    '  border-color: ' + v('line') + ';',
    '  background: none;',
    '  color: ' + v('ink-2') + ';',
    '}',
    sc('button') + '[disabled] {',
    '  border-color: ' + v('line') + ';',
    '  background: ' + v('surface-2') + ';',
    '  color: ' + v('ink-3') + ';',
    '  cursor: not-allowed;',
    '}',
    sc('button') + ':active { transform: scale(.98); }',
    sc('button') + ':focus-visible {',
    '  outline: 2px solid ' + v('accent') + ';',
    '  outline-offset: 2px;',
    '}',
    sc('error') + ' {',
    '  flex: 1 1 140px;',
    '  padding-left: 8px;',
    '  border-left: 3px solid ' + v('danger') + ';',
    '  color: ' + v('danger') + ';',
    '  font-size: ' + v('fs-xs') + ';',
    '  line-height: 1.55;',
    '  overflow-wrap: anywhere;',
    '}',
    sc('absent') + ' {',
    '  margin: 0;',
    '  color: ' + v('ink-3') + ';',
    '  font-size: ' + v('fs-sm') + ';',
    '}',
    '/* 悬停：包在设备能力查询里（不是唯一通路——按钮本来就是按下去的）。 */',
    '@media (hover:hover) and (pointer:fine) {',
    '  ' + sc('button') + ':hover:not([disabled]) { background: ' + v('accent-text') + '; border-color: ' + v('accent-text') + '; }',
    '  ' + sc('button') + '.is-quiet:hover:not([disabled]) { background: ' + v('surface-2') + '; }',
    '}',
    '/* 减动效：过渡关掉，读数照走（读数由运行时按时间写，不靠动画收尾）。 */',
    '@media (prefers-reduced-motion:reduce) {',
    '  ' + sc('bar-fill') + ' { transition: none; }',
    '  ' + sc('button') + ' { transition: none; }',
    '}',
    '/* 窄档：按钮各占一整行（大数字照旧不截断）。 */',
    '@container ' + TIMER_CARD_CONTAINER + ' (max-width: ' + TIMER_CARD_NARROW_MAX_PX + 'px) {',
    '  ' + sc('button') + ' { flex: 1 1 100%; }',
    '  ' + sc('tag') + ' { margin-left: 0; }',
    '}',
  ].join(LF);
}
