// 本文件由 `scripts/gen-cli.mjs` 生成，勿手改（`pnpm gen` 重生成，`pnpm gen:check` 验真）。
export const SCHEDULE_ROUTES = [
  { phrase: '作息管家 HELP', key: 'schedule.help.lookup', order: 0 },
  { phrase: '作息管家帮助', key: 'schedule.help.lookup', order: 1 },
  { phrase: '作息管家能做什么', key: 'schedule.help.lookup', order: 2 },
  { phrase: '作息管家使用说明', key: 'schedule.help.lookup', order: 3 },
  { phrase: '今天总结', key: 'schedule.record.today', order: 4 },
  { phrase: '今日作息', key: 'schedule.record.today', order: 5 },
  { phrase: '今日总结', key: 'schedule.record.today', order: 6 },
  { phrase: '今天作息', key: 'schedule.record.today', order: 7 },
  { phrase: '查作息时间轴', key: 'schedule.record.today', order: 8 },
  { phrase: '查作息状态', key: 'schedule.record.today', order: 9 },
  { phrase: '初始化数据库', key: 'schedule.record.today', order: 10 },
  { phrase: '查作息', key: 'schedule.record.today', order: 11 },
  { phrase: '汇总作息', key: 'schedule.record.range', needs: ['start', 'end'], order: 12 },
  { phrase: '查作息范围', key: 'schedule.record.range', needs: ['start', 'end'], order: 13 },
  { phrase: '查作息游标', key: 'schedule.record.range', needs: ['start', 'end'], order: 14 },
  { phrase: '查作息详情', key: 'schedule.record.detail', order: 15 },
  { phrase: '按ID查记录', key: 'schedule.record.detail', needs: ['id'], order: 16 },
  { phrase: '补一条作息', key: 'schedule.record.write', preset: {"op":"add"}, order: 17 },
  { phrase: '录作息', key: 'schedule.record.write', preset: {"op":"add"}, order: 18 },
  { phrase: '修正作息', key: 'schedule.record.write', needs: ['id'], preset: {"op":"amend"}, order: 19 },
  { phrase: '改作息', key: 'schedule.record.write', needs: ['id'], preset: {"op":"amend"}, order: 20 },
  { phrase: '这条记错了', key: 'schedule.record.write', needs: ['id'], preset: {"op":"amend"}, order: 21 },
  { phrase: '写作息摘要', key: 'schedule.record.write', preset: {"op":"summary"}, order: 22 },
  { phrase: '记作息', key: 'schedule.record.write', preset: {"op":"add"}, order: 23 },
  { phrase: '对比两个月', key: 'schedule.record.compare', preset: {"kind":"months"}, order: 24 },
  { phrase: '月份对比', key: 'schedule.record.compare', preset: {"kind":"months"}, order: 25 },
  { phrase: '跨月对比', key: 'schedule.record.compare', preset: {"kind":"months"}, order: 26 },
  { phrase: '类别深挖', key: 'schedule.record.compare', preset: {"kind":"category"}, order: 27 },
  { phrase: '异常检测', key: 'schedule.record.compare', preset: {"kind":"anomaly"}, order: 28 },
  { phrase: '查多日计划', key: 'schedule.plan.today', needs: ['dates'], preset: {"view":"aggregate"}, order: 29 },
  { phrase: '24h 概览', key: 'schedule.plan.today', preset: {"view":"aggregate"}, order: 30 },
  { phrase: '查日程', key: 'schedule.plan.today', order: 31 },
  { phrase: '看日程', key: 'schedule.plan.today', order: 32 },
  { phrase: '商量计划', key: 'schedule.plan.write', preset: {"op":"preview"}, order: 33 },
  { phrase: '一起规划', key: 'schedule.plan.write', preset: {"op":"preview"}, order: 34 },
  { phrase: '规划明天', key: 'schedule.plan.write', preset: {"op":"preview"}, order: 35 },
  { phrase: '规划一天', key: 'schedule.plan.write', preset: {"op":"preview"}, order: 36 },
  { phrase: '讨论计划', key: 'schedule.plan.write', preset: {"op":"preview"}, order: 37 },
  { phrase: '补计划', key: 'schedule.plan.write', needs: ['date', 'time_start', 'time_end', 'title'], preset: {"op":"ensure"}, order: 38 },
  { phrase: '改计划', key: 'schedule.plan.write', needs: ['id'], preset: {"op":"update"}, order: 39 },
  { phrase: '删计划', key: 'schedule.plan.write', needs: ['id'], preset: {"op":"deactivate"}, order: 40 },
  { phrase: '复盘今日', key: 'schedule.plan.write', preset: {"op":"review","granularity":"day"}, order: 41 },
  { phrase: '复盘本周', key: 'schedule.plan.write', preset: {"op":"review","granularity":"week"}, order: 42 },
  { phrase: '复盘本月', key: 'schedule.plan.write', preset: {"op":"review","granularity":"month"}, order: 43 },
  { phrase: '复盘区间', key: 'schedule.plan.write', preset: {"op":"review","granularity":"range"}, order: 44 },
  { phrase: '日程管家同步', key: 'schedule.plan.write', preset: {"op":"sync"}, order: 45 },
  { phrase: '飞书探测', key: 'schedule.plan.write', preset: {"op":"sync","dryRun":true}, order: 46 },
  { phrase: '复盘', key: 'schedule.plan.write', preset: {"op":"review"}, order: 47 },
  { phrase: '周视图', key: 'schedule.record.range', preset: {"view":"week"}, order: 48 },
  { phrase: '按 ID 查记录', key: 'schedule.record.detail', needs: ['id'], order: 49 },
] as const;
