/** gantt-timeline · **段与图例那几档的样式**（搬出去的是行数，不是取值：本包告警线 350 行）。
 *
 *  为什么有这一件：形态 C 要画的东西太多（段四档状态 ＋ 关键路径 ＋ 空档块 ＋ 里程碑 ＋ 图例六档），
 *  一段装不下本包的告警线（`packages/base-render/AGENTS.md`）。切口按「骨架面／读数面」分：
 *   · `style.ts`：卡壳、刻度行、「现在」游标、行与轨迹的骨架，并汇总本件全部样式；
 *   · 本件：**落在轨迹里的那些读数**（段／字形／短字／空档块／里程碑／图例／图例那几枚形）。
 *  纪律与 `style.ts` 同一份：只经 `skinVar()` 读皮肤、全部规则 scope 在 `.<prefix>page-ui` 之下、
 *  零 `:root`／`!important`／零新 token／零 `@media`；本件不写 `overflow:hidden`（不靠截断）。
 */
import { skinVar } from '../skin/contract.js';
import { ganttTimelineSlot, type GanttTimelineSlot } from './attrs.js';
import { GANTT_TIMELINE_BAR_PX } from './style.js';

/** 换行（仓库口径：不写字面换行转义）。 */
const LF = String.fromCharCode(10);

/** 轨迹里那几档读数的样式段（由 `style.ts` 汇总进本件的样式段，前缀与 scope 一起透传）。 */
export function ganttTimelineMarksCss(input?: { readonly prefix?: string }): string {
  const p = input !== undefined && input !== null
    && typeof input.prefix === 'string' && input.prefix !== '' ? input.prefix : 'ilife-';
  const root = '.' + p + 'page-ui';
  /** **槽类名**（不带 scope）：嵌套时只许用它（拼第二遍 scope ＝ 永不命中的死规则）。 */
  const c = (slot: GanttTimelineSlot): string => '.' + ganttTimelineSlot(slot, p);
  const s = (slot: GanttTimelineSlot): string => root + ' ' + c(slot);

  return [
    '/* 一条段：字形居中；有短字时字跟着走（长了在条内换行，不截断）。 */',
    s('bar') + ' {',
    '  grid-row: 1;',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  gap: 4px;',
    '  min-height: ' + String(GANTT_TIMELINE_BAR_PX) + 'px;',
    '  min-width: 0;',
    '  padding: 0 2px;',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('accent') + ';',
    '  color: ' + skinVar('accent-ink') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 700;',
    '  line-height: 1;',
    '  overflow-wrap: anywhere;',
    '}',
    s('mark') + ' {',
    '  flex: none;',
    '  font-style: normal;',
    '  line-height: 1;',
    '}',
    s('text') + ' {',
    '  min-width: 0;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 已完成：次要面 ＋ 发丝边（弱一档）。 */',
    s('bar') + '.is-done {',
    '  background: ' + skinVar('surface-2') + ';',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '}',
    '/* 等待前置：次要面 ＋ 虚线边 ＋ `⋯`（**形不同**，不只靠色）。 */',
    s('bar') + '.is-wait {',
    '  background: ' + skinVar('surface-2') + ';',
    '  border: 1px dashed ' + skinVar('line') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '}',
    '/* 未开始：纸面 ＋ 虚线边 ＋ `▷`（空心三角与进行中的实心三角成对）。 */',
    s('bar') + '.is-plan {',
    '  background: ' + skinVar('surface') + ';',
    '  border: 1px dashed ' + skinVar('line') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '}',
    '/* 关键路径：段里那枚**顺序号是正文级的字** ⇒ 法则表里归"有文字的选中面"：软底 ＋ 主色字 ＋ 主色描边',
    '   （实底那一档在 neutral 皮肤下过不了 4.5 的文本地板）。 */',
    s('bar') + '.is-crit {',
    '  background: ' + skinVar('accent-soft') + ';',
    '  border: 1px solid ' + skinVar('accent') + ';',
    '  color: ' + skinVar('accent-text') + ';',
    '}',
    '/* 带短字的段（`is-labelled`）：**这块面上有正文级的字** ⇒ 与关键路径段同一档（软底 ＋ 主色字 ＋ 描边）。',
    '   进行中那根条只有**不带短字**时才是实底（那条上只有 `▶` 这类图形，走"无文字的选中面"）；',
    '   一旦带了短字，实底上的 `accent-ink` 在 neutral 皮肤下只有 4.02，正文过不了 4.5。 */',
    s('bar') + '.is-labelled {',
    '  background: ' + skinVar('accent-soft') + ';',
    '  border: 1px solid ' + skinVar('accent') + ';',
    '  color: ' + skinVar('accent-text') + ';',
    '}',
    '/* 空档段：点线块 ＋ 块里那枚分钟数（**不装作占用**：不是实底、不是状态色）。 */',
    s('idle') + ' {',
    '  grid-row: 1;',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  gap: 4px;',
    '  min-height: ' + String(GANTT_TIMELINE_BAR_PX) + 'px;',
    '  min-width: 0;',
    '  padding: 0 2px;',
    '  border: 1px dotted ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '  line-height: 1;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 里程碑：元素铺到一侧，那枚 `◆` 压在格线上；名字写在旁边（长了换行）。 */',
    s('milestone') + ' {',
    '  grid-row: 1;',
    '  display: flex;',
    '  align-items: center;',
    '  gap: 4px;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '}',
    '/* 落点在右半区：名字长在点的**左边**（从第 1 格铺到落点前那一格，内容右对齐）。 */',
    s('milestone') + '.is-end {',
    '  flex-direction: row-reverse;',
    '  justify-content: flex-start;',
    '  text-align: right;',
    '}',
    s('ms-mark') + ' {',
    '  flex: none;',
    '  color: ' + skinVar('accent') + ';',
    '  font-style: normal;',
    '  line-height: 1;',
    '}',
    s('ms-text') + ' {',
    '  min-width: 0;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 图例：逐枚「形 ＋ 字」（**只列这一段里出现过的档**）。 */',
    s('legend') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  gap: 4px 14px;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '  line-height: 1.5;',
    '}',
    s('legend-item') + ' {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  gap: 6px;',
    '  min-width: 0;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 图例那枚形：宽度是**下限**不是定值（`1-4` 这类三字符自己撑开），所以它不会被压扁成省略号。 */',
    s('swatch') + ' {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  flex: none;',
    '  min-width: 22px;',
    '  height: 20px;',
    '  padding: 0 3px;',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  font-style: normal;',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1;',
    '}',
    s('swatch') + '.is-crit {',
    '  background: ' + skinVar('accent-soft') + ';',
    '  border: 1px solid ' + skinVar('accent') + ';',
    '  color: ' + skinVar('accent-text') + ';',
    '}',
    s('swatch') + '.is-done {',
    '  background: ' + skinVar('surface-2') + ';',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '}',
    s('swatch') + '.is-doing {',
    '  background: ' + skinVar('accent') + ';',
    '  color: ' + skinVar('accent-ink') + ';',
    '}',
    s('swatch') + '.is-wait {',
    '  background: ' + skinVar('surface-2') + ';',
    '  border: 1px dashed ' + skinVar('line') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '}',
    s('swatch') + '.is-plan {',
    '  background: ' + skinVar('surface') + ';',
    '  border: 1px dashed ' + skinVar('line') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '}',
    s('swatch') + '.is-idle {',
    '  border: 1px dotted ' + skinVar('line') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '}',
    '/* 里程碑那枚 `◆` 在轨迹里是**主色的裸字形**（不铺底）⇒ 图例里也照这个形给：发丝边 ＋ 主色字。 */',
    s('swatch') + '.is-milestone {',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  color: ' + skinVar('accent') + ';',
    '}',
    s('legend-word') + ' {',
    '  min-width: 0;',
    '  overflow-wrap: anywhere;',
    '}',
  ].join(LF);
}
