/** confirm-strip · **样式段**（本件唯一的样式来源）。
 *
 *  纪律（与本层其余件同一份）：
 *   · 只经 `skinVar()` 读皮肤 —— 组件里**不写** `var(--ilife-…)`（兜底链只许住在 `skin/contract.ts`）；
 *   · 全部规则 scope 在 `.<prefix>page-ui` 之下（不开本配方的页零命中）；不写 `:root`／`!important`、不新增 token 名；
 *   · **宽度只许容器判**：本件设 `container-type: inline-size`（它自己就是容器），折行靠内在尺寸 ＋ `flex-wrap`；
 *     窄档调整走 `@container`。媒体查询只判设备能力（`hover`／`pointer`／`prefers-reduced-motion`）。
 *
 *  **危险档的三样手段**（本件的要害：色不许是唯一通路，大字报刊皮肤下强调色是墨黑）：
 *   ① 左边一道 `4px` 危险色粗条 ＋ 危险软底；
 *   ② **不可撤销**时整条改走 `3px double` 双线框（`double` 画出两条平行线），危险按钮字重提到 800；
 *   ③ 徽标与后果话前半句**用字说出**「可撤销／不可撤销」（字，不是色）。
 *  色（`danger`／`danger-soft`）只排在第三位；三套皮肤下前两样都在。
 *
 *  几何契约（判据钉住）：两个按钮的命中盒 ≥`CONFIRM_STRIP_TOUCH_MIN_PX`（44×44）；状态行**恒占位**
 *  （`min-height:1.5em`）⇒ `rest`／`busy`／`disabled` 三态互切**不跳版**。
 */
import { skinVar } from '../skin/contract.js';
import { CONFIRM_STRIP_IRREVERSIBLE_ATTR, confirmStripSlot, type ConfirmStripSlot } from './attrs.js';

/** 换行（仓库口径：不写字面换行转义）。 */
const LF = String.fromCharCode(10);

/** 触控目标下限（px）：两个按钮的命中盒（用户裁定：全宽口径，不只窄屏）。 */
export const CONFIRM_STRIP_TOUCH_MIN_PX = 44;

/** 窄容器阈值（px，`@container` 判的是**本件自己的宽度**，不是视口宽度）：动作排改一列。 */
export const CONFIRM_STRIP_NARROW_PX = 420;

/** 按下时的缩放（真按下 ≤80ms）。 */
export const CONFIRM_STRIP_ACTIVE_SCALE = 0.98;

/** 按下反馈时长（ms，≤80ms）。 */
export const CONFIRM_STRIP_TRANSITION_MS = 80;

/** 本组件的样式段。恒返回非空 CSS 文本。 */
export function confirmStripCss(input?: { readonly prefix?: string }): string {
  const p = input !== undefined && input !== null
    && typeof input.prefix === 'string' && input.prefix !== '' ? input.prefix : 'ilife-';
  const root = '.' + p + 'page-ui';
  const box = root + ' .' + p + 'block-confirm-strip';
  /** 槽位的**裸类名**：跟在组合子（`>`／`+`／后代）后面时用它 —— 带 `.ilife-page-ui` 前缀的复合选择器
   *  拼成 `A > .ilife-page-ui .x` 时，要求中间还有一个内层 `.ilife-page-ui`，规则会**静默不匹配**
   *  （2026-09 真机判据抓到过这一处：不可撤销的字重规则整条没生效）。 */
  const cls = (slot: ConfirmStripSlot): string => '.' + confirmStripSlot(slot, p);
  const s = (slot: ConfirmStripSlot): string => root + ' ' + cls(slot);
  const touch = CONFIRM_STRIP_TOUCH_MIN_PX + 'px';

  return [
    '/* confirm-strip（二次确认条 · 形态 A「清单式」）：点名要删什么、删几条、能不能撤销。',
    '   危险档不靠单色：左粗条 ＋ 不可撤销时双线框与字重 ＋ 徽标与后果话用字说出。 */',
    box + ' {',
    '  container-type: inline-size;',
    '  display: grid;',
    '  gap: 10px;',
    '  min-width: 0;',
    '  padding: 14px 16px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-inline-start: 4px solid ' + skinVar('danger') + ';',
    '  border-radius: ' + skinVar('radius') + ';',
    '  background: ' + skinVar('danger-soft') + ';',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-body') + ';',
    '  line-height: 1.5;',
    '}',
    '/* 不可撤销：整条换成双线框（`double` ＝ 两条平行线），危险按钮再提字重 ——',
    '   这是「危险档必须另有手段」的那一手：把色抽掉，它仍然读得出「重」。 */',
    box + '[' + CONFIRM_STRIP_IRREVERSIBLE_ATTR + '="1"] {',
    '  border: 3px double ' + skinVar('danger') + ';',
    '  border-inline-start: 4px solid ' + skinVar('danger') + ';',
    '}',
    s('head') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: center;',
    '  gap: 8px;',
    '  min-width: 0;',
    '}',
    '/* 徽标用字说出「可撤销／不可撤销」——色之外的第一样证据（描边字，不铺满）。 */',
    s('badge') + ' {',
    '  flex: none;',
    '  padding: 1px 7px;',
    '  border: 1px solid ' + skinVar('danger') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  color: ' + skinVar('danger') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 800;',
    '  letter-spacing: .04em;',
    '}',
    s('title') + ' {',
    '  min-width: 0;',
    '  font-family: ' + skinVar('font-display') + ';',
    '  font-size: ' + skinVar('fs-h3') + ';',
    '  font-weight: 700;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 点名的清单：名称占主位、旁证与值依次跟上；行间一条发丝线（与「明细行」的点线分得开）。 */',
    s('items') + ' {',
    '  display: grid;',
    '  gap: 0;',
    '  margin: 0;',
    '  padding: 0;',
    '  list-style: none;',
    '  min-width: 0;',
    '  border-top: 1px solid ' + skinVar('line') + ';',
    '  border-bottom: 1px solid ' + skinVar('line') + ';',
    '}',
    s('item') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 2px 10px;',
    '  padding: 7px 0;',
    '  min-width: 0;',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '}',
    s('item') + ' + ' + cls('item') + ' {',
    '  border-top: 1px solid ' + skinVar('line') + ';',
    '}',
    s('name') + ' {',
    '  flex: 1 1 60%;',
    '  min-width: 0;',
    '  font-weight: 700;',
    '  overflow-wrap: anywhere;',
    '}',
    s('meta') + ' {',
    '  flex: 0 1 auto;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-variant-numeric: tabular-nums;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 值（金额／热量）：右对齐等宽数字，`nowrap` —— 关键语义不许 `…` 截断（要折行就整块折）。 */',
    s('value') + ' {',
    '  flex: none;',
    '  margin-left: auto;',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-variant-numeric: tabular-nums;',
    '  font-weight: 700;',
    '  white-space: nowrap;',
    '}',
    '/* 可选备份项：整行是 `<label>`（触区 ≥44px），控件本体留在可聚焦位置、视觉画在盒子上。 */',
    s('opt') + ' {',
    '  display: flex;',
    '  align-items: center;',
    '  gap: 10px;',
    '  min-height: ' + touch + ';',
    '  cursor: pointer;',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 600;',
    '}',
    s('opt') + ' input[type="checkbox"] {',
    '  position: absolute;',
    '  width: 1px;',
    '  height: 1px;',
    '  opacity: 0;',
    '  pointer-events: none;',
    '}',
    s('optbox') + ' {',
    '  position: relative;',
    '  flex: none;',
    '  box-sizing: border-box;',
    '  width: 22px;',
    '  height: 22px;',
    '  border: 2px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('surface') + ';',
    '}',
    s('opt') + ' input:checked ~ ' + cls('optbox') + ' {',
    '  border-color: ' + skinVar('accent') + ';',
    '  background: ' + skinVar('accent') + ';',
    '}',
    s('opt') + ' input:checked ~ ' + cls('optbox') + '::after {',
    '  content: "";',
    '  position: absolute;',
    '  left: 6px;',
    '  top: 2px;',
    '  width: 5px;',
    '  height: 10px;',
    '  border: solid ' + skinVar('accent-ink') + ';',
    '  border-width: 0 2px 2px 0;',
    '  transform: rotate(45deg);',
    '}',
    s('opt') + ' input:focus-visible ~ ' + cls('optbox') + ' {',
    '  outline: 2px solid ' + skinVar('accent') + ';',
    '  outline-offset: 2px;',
    '}',
    '/* 后果话：前半句（可以／不能撤销）加粗上色，后半句是撤销入口或后果 —— 两半都是字。 */',
    s('note') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 2px 4px;',
    '  margin: 0;',
    '  max-width: 64ch;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    s('note') + ' > b {',
    '  flex: none;',
    '  color: ' + skinVar('danger') + ';',
    '  font-weight: 800;',
    '}',
    s('note') + ' > span {',
    '  min-width: 0;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 状态行**恒占位**（`rest` 时是空元素）：三态互切因此不跳版（判据量这一条）。 */',
    s('status') + ' {',
    '  margin: 0;',
    '  min-height: 1.5em;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 动作排：安全动作在前、危险动作靠 `margin-left:auto` 顶到右缘（标记顺序 ＝ 读屏顺序）。 */',
    s('acts') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: center;',
    '  gap: 8px;',
    '  min-width: 0;',
    '}',
    s('acts') + ' > button {',
    '  box-sizing: border-box;',
    '  min-height: ' + touch + ';',
    '  min-width: ' + touch + ';',
    '  padding: 0 16px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: inherit;',
    '  font-size: ' + skinVar('fs-body') + ';',
    '  font-weight: 600;',
    '  cursor: pointer;',
    '  transition: transform ' + String(CONFIRM_STRIP_TRANSITION_MS) + 'ms ease-out;',
    '}',
    s('acts') + ' > ' + cls('danger') + ' {',
    '  margin-left: auto;',
    '  border-color: ' + skinVar('danger') + ';',
    '  background: ' + skinVar('danger') + ';',
    '  color: ' + skinVar('accent-ink') + ';',
    '  font-weight: 700;',
    '}',
    '/* 不可撤销：双线框之外，危险按钮再提一档字重 —— 「危险档必须另有手段」的第二样（字重）。 */',
    box + '[' + CONFIRM_STRIP_IRREVERSIBLE_ATTR + '="1"] ' + cls('danger') + ' {',
    '  font-weight: 800;',
    '}',
    s('acts') + ' > button:focus-visible {',
    '  outline: 2px solid ' + skinVar('accent') + ';',
    '  outline-offset: 2px;',
    '}',
    s('acts') + ' > button:active {',
    '  transform: scale(' + String(CONFIRM_STRIP_ACTIVE_SCALE) + ');',
    '}',
    '/* 禁用（`busy`／`disabled`）：光标说明「点不动」，为什么由状态行回答（写在控件旁边）。 */',
    s('acts') + ' > button[disabled] {',
    '  cursor: not-allowed;',
    '  border-color: ' + skinVar('line') + ';',
    '  background: ' + skinVar('surface-2') + ';',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-weight: 600;',
    '}',
    '/* 禁用档落回普通字重（比「不可撤销」那条更具体，免得禁用的危险按钮还挂着 800）。 */',
    s('acts') + ' > ' + cls('danger') + '[disabled] {',
    '  font-weight: 600;',
    '}',
    '/* 悬停只是**加**一条通路（不是唯一通路：焦点与按下都各有一条），故只包在能悬停的设备里。 */',
    '@media (hover:hover) and (pointer:fine) {',
    '  ' + s('keep') + ':not([disabled]):hover {',
    '    background: ' + skinVar('surface-2') + ';',
    '  }',
    '  ' + s('danger') + ':not([disabled]):hover {',
    '    filter: brightness(1.08);',
    '  }',
    '  ' + s('opt') + ':hover > ' + cls('optbox') + ' {',
    '    border-color: ' + skinVar('ink-2') + ';',
    '  }',
    '}',
    '@media (prefers-reduced-motion:reduce) {',
    '  ' + s('acts') + ' > button {',
    '    transition: none;',
    '  }',
    '  ' + s('acts') + ' > button:active {',
    '    transform: none;',
    '  }',
    '}',
    '/* 窄容器（<' + String(CONFIRM_STRIP_NARROW_PX) + 'px）：每条的名称独占一行（旁证与值另起一行不挤名），',
    '   动作排改一列 —— 安全动作仍在上、危险动作仍在下，读屏顺序与视觉顺序一致。 */',
    '@container (max-width: ' + String(CONFIRM_STRIP_NARROW_PX) + 'px) {',
    '  ' + s('name') + ' {',
    '    flex: 1 1 100%;',
    '  }',
    '  ' + s('acts') + ' {',
    '    display: grid;',
    '    grid-template-columns: minmax(0, 1fr);',
    '  }',
    '  ' + s('acts') + ' > ' + cls('danger') + ' {',
    '    margin-left: 0;',
    '  }',
    '}',
  ].join(LF);}
