/** searchField · **运行时**（产出 JS 文本；DOM 只允许出现在这段文本里）。
 *
 *  与 `controls.buildSharedHelpersJs()`／`charts.buildChartsHelpersJs()` 同一处分工：
 *  模块代码零 DOM；DOM 只出现在本文件产出的**字符串**里。
 *
 *  行为契约（逐条对应判据）：
 *   · **委派 ＋ 幂等**：`document` 上四枚委派（`input`／`click`／`keydown` ＋ `ilife:search-loading`）；
 *     `<html>` 上打一枚挂载标记，重复注入只绑一次，事件只派发一条。
 *   · **命中计数是真数**：命中数＝结果区里**真实被标出来的词**（`<mark data-ilife-search-hit>`）的个数；
 *     渲染期写 `—`，运行时算完才写真数——计数不是文案。
 *   · **过滤靠 `hidden`**：不匹配的条目落 `hidden`；清空时**逐字还原**（`<mark>` 拆回文本，
 *     `parent.normalize()` 合并文本节点，不留空壳）。
 *   · **范围分段**：`aria-pressed="true"` 的那一档生效；档计数＝该档条目里的命中数（按 `data-ilife-search-tags` 对号）。
 *   · **跳转**：Enter／下一处 → 第 i 处循环前进，`scrollIntoView({block:'nearest'})`，
 *     当前处落 `data-ilife-search-current`；位置读数与当前处**同一次**写完（不许两处对不上）。
 *   · **IME**：组字中的回车不跳。
 *   · **载入态**：`ilife:search-loading`（`detail={name,on}`）→ 读数行原地换字 ＋ 收起跳转键；
 *     `on:false` 时重算一次真读数（载入期间**不写**假的数）。
 *   · **错态**：结果区不在／里面一条都没有 → 控件旁边写「没接上结果区」并落 `aria-invalid`（不只染色）。
 *   · **无脚本降级**：这段不跑时，条目照常可读、搜索框照常可打字，只是不计数不过滤。
 */
import {
  SEARCH_AT_ATTR, SEARCH_BOUND_ATTR, SEARCH_CLEAR_ATTR, SEARCH_COUNT_ATTR, SEARCH_CURRENT_ATTR,
  SEARCH_DEFAULTS, SEARCH_DISABLED_ATTR, SEARCH_EMPTY_ATTR, SEARCH_ERROR_ATTR, SEARCH_EVENT_JUMP,
  SEARCH_EVENT_LOADING, SEARCH_EVENT_QUERY, SEARCH_HIT_ATTR, SEARCH_INPUT_ATTR, SEARCH_INVALID_ATTR,
  SEARCH_ITEM_ATTR, SEARCH_LOADING_ATTR, SEARCH_NAME_ATTR, SEARCH_NEXT_ATTR, SEARCH_N_ATTR,
  SEARCH_PREV_ATTR, SEARCH_REGION_ATTR, SEARCH_ROOT_CLASS, SEARCH_RUNTIME_ATTR, SEARCH_SCOPE_ATTR,
  SEARCH_SCOPE_NAME_ATTR, SEARCH_STATUS_ATTR, SEARCH_TAGS_ATTR, SEARCH_TARGET_ATTR,
} from './attrs.js';

/** 产出运行时的 JS 文本（经典 script 作用域可跑的 IIFE；由页面拼进自己的脚本槽）。 */
export function buildSearchFieldJs(): string {
  const q = (s: string): string => JSON.stringify(s);
  const C = q(SEARCH_ROOT_CLASS);
  return '(function(){' + '\n'
    /* ── 常量 ─────────────────────────────────────────────────────── */
    + '  var A_ROOT=' + q(SEARCH_NAME_ATTR) + ', A_TARGET=' + q(SEARCH_TARGET_ATTR) + ', A_REGION=' + q(SEARCH_REGION_ATTR) + ';' + '\n'
    + '  var A_ITEM=' + q(SEARCH_ITEM_ATTR) + ', A_TAGS=' + q(SEARCH_TAGS_ATTR) + ', A_INPUT=' + q(SEARCH_INPUT_ATTR) + ';' + '\n'
    + '  var A_CLEAR=' + q(SEARCH_CLEAR_ATTR) + ', A_SCOPE=' + q(SEARCH_SCOPE_ATTR) + ', A_N=' + q(SEARCH_N_ATTR) + ';' + '\n'
    + '  var A_SCOPE_NAME=' + q(SEARCH_SCOPE_NAME_ATTR) + ', A_STATUS=' + q(SEARCH_STATUS_ATTR) + ', A_COUNT=' + q(SEARCH_COUNT_ATTR) + ';' + '\n'
    + '  var A_AT=' + q(SEARCH_AT_ATTR) + ', A_PREV=' + q(SEARCH_PREV_ATTR) + ', A_NEXT=' + q(SEARCH_NEXT_ATTR) + ';' + '\n'
    + '  var A_HIT=' + q(SEARCH_HIT_ATTR) + ', A_CURRENT=' + q(SEARCH_CURRENT_ATTR) + ', A_EMPTY=' + q(SEARCH_EMPTY_ATTR) + ';' + '\n'
    + '  var A_ERR=' + q(SEARCH_ERROR_ATTR) + ', A_INVALID=' + q(SEARCH_INVALID_ATTR) + ', A_LOADING=' + q(SEARCH_LOADING_ATTR) + ';' + '\n'
    + '  var A_DISABLED=' + q(SEARCH_DISABLED_ATTR) + ', A_BOUND=' + q(SEARCH_BOUND_ATTR) + ', A_RUNTIME=' + q(SEARCH_RUNTIME_ATTR) + ';' + '\n'
    + '  var EV_QUERY=' + q(SEARCH_EVENT_QUERY) + ', EV_JUMP=' + q(SEARCH_EVENT_JUMP) + ', EV_LOADING=' + q(SEARCH_EVENT_LOADING) + ';' + '\n'
    + '  var D={unset:' + q(SEARCH_DEFAULTS.unset) + ', scopeAll:' + q(SEARCH_DEFAULTS.scopeAll)
    + ', unwiredText:' + q(SEARCH_DEFAULTS.unwiredText) + '};' + '\n'
    + '  var C_LAB=' + q(SEARCH_ROOT_CLASS + '-scope-lab') + ';' + '\n'
    + '  var SEL_ROOT="["+A_ROOT+"]", SKIP={SCRIPT:1,STYLE:1,TEXTAREA:1,INPUT:1,SELECT:1,BUTTON:1};' + '\n'
    + '  var TAGS_RE=/\\s+/;' + '\n'
    + '  var doc=document;' + '\n'
    + '  if (doc.documentElement.getAttribute(A_RUNTIME)==="1") return;' + '\n'
    + '  doc.documentElement.setAttribute(A_RUNTIME,"1");' + '\n'
    /* ── 定位小件 ─────────────────────────────────────────────────── */
    + '  function quoted(value){ return String(value).replace(/["\\\\]/g, "\\\\$&"); }' + '\n'
    + '  function pick(attr,value){ return "["+attr+"=\\""+quoted(value)+"\\"]"; }' + '\n'
    + '  function one(root,attr){ return root.querySelector("["+attr+"]"); }' + '\n'
    + '  function many(root,attr){ return root.querySelectorAll("["+attr+"]"); }' + '\n'
    + '  function rootOf(el){ return el && el.closest ? el.closest(SEL_ROOT) : null; }' + '\n'
    + '  function inputOf(root){ return one(root,A_INPUT); }' + '\n'
    + '  function itemsOf(root){' + '\n'
    + '    var key=root.getAttribute(A_TARGET);' + '\n'
    + '    var box=null;' + '\n'
    + '    if (key){ box=doc.querySelector(pick(A_REGION,key)); if (!box) return null; }' + '\n'
    + '    /* 只认**最外层**的条目：卡片里再嵌一行结果（两个元素都挂 A_ITEM）是常见写法，' + '\n'
    + '       两层都算就会把同一条文本数两遍（实测：命中数翻倍、还会标出嵌套的 <mark>）。 */' + '\n'
    + '    var all=(box||doc).querySelectorAll("["+A_ITEM+"]"), out=[];' + '\n'
    + '    for (var i=0;i<all.length;i+=1){' + '\n'
    + '      var nested=false;' + '\n'
    + '      for (var j=0;j<all.length && !nested;j+=1){' + '\n'
    + '        if (i!==j && all[j].contains && all[j].contains(all[i])) nested=true;' + '\n'
    + '      }' + '\n'
    + '      if (!nested) out.push(all[i]);' + '\n'
    + '    }' + '\n'
    + '    return out;' + '\n'
    + '  }' + '\n'
    /* ── 文本与标记 ───────────────────────────────────────────────── */
    + '  function textOf(node){' + '\n'
    + '    var out="", kids=node.childNodes;' + '\n'
    + '    for (var i=0;i<kids.length;i+=1){' + '\n'
    + '      var c=kids[i];' + '\n'
    + '      if (c.nodeType===3){ out+=c.nodeValue; continue; }' + '\n'
    + '      if (c.nodeType!==1 || SKIP[c.tagName]) continue;' + '\n'
    + '      out+=textOf(c);' + '\n'
    + '    }' + '\n'
    + '    return out;' + '\n'
    + '  }' + '\n'
    + '  function collect(node,out){' + '\n'
    + '    var kids=node.childNodes;' + '\n'
    + '    for (var i=0;i<kids.length;i+=1){' + '\n'
    + '      var c=kids[i];' + '\n'
    + '      if (c.nodeType===3){ if (c.nodeValue) out.push(c); continue; }' + '\n'
    + '      if (c.nodeType!==1 || SKIP[c.tagName]) continue;' + '\n'
    + '      /* 已经标过的词不再进：否则会在 <mark> 里再套一层 <mark>（嵌套高亮＝读屏器念两遍）。 */' + '\n'
    + '      if (c.hasAttribute(A_HIT)) continue;' + '\n'
    + '      collect(c,out);' + '\n'
    + '    }' + '\n'
    + '  }' + '\n'
    + '  function wrap(node,term,marks){' + '\n'
    + '    var text=node.nodeValue||"", rest=text, low=text.toLowerCase(), at=low.indexOf(term);' + '\n'
    + '    if (at<0) return;' + '\n'
    + '    var frag=doc.createDocumentFragment();' + '\n'
    + '    while (at>-1){' + '\n'
    + '      if (at>0) frag.appendChild(doc.createTextNode(rest.slice(0,at)));' + '\n'
    + '      var m=doc.createElement("mark");' + '\n'
    + '      m.setAttribute(A_HIT,"");' + '\n'
    + '      m.textContent=rest.slice(at,at+term.length);' + '\n'
    + '      frag.appendChild(m); marks.push(m);' + '\n'
    + '      rest=rest.slice(at+term.length); low=low.slice(at+term.length);' + '\n'
    + '      at=low.indexOf(term);' + '\n'
    + '    }' + '\n'
    + '    if (rest!=="") frag.appendChild(doc.createTextNode(rest));' + '\n'
    + '    var parent=node.parentNode;' + '\n'
    + '    if (parent) parent.replaceChild(frag,node);' + '\n'
    + '  }' + '\n'
    + '  function unmark(item){' + '\n'
    + '    var marks=item.querySelectorAll("["+A_HIT+"]");' + '\n'
    + '    for (var i=0;i<marks.length;i+=1){' + '\n'
    + '      var m=marks[i], p=m.parentNode;' + '\n'
    + '      if (!p) continue;' + '\n'
    + '      p.replaceChild(doc.createTextNode(m.textContent),m);' + '\n'
    + '      if (p.normalize) p.normalize();' + '\n'
    + '    }' + '\n'
    + '  }' + '\n'
    + '  function marksOf(root){' + '\n'
    + '    var out=[], items=itemsOf(root);' + '\n'
    + '    if (!items) return out;' + '\n'
    + '    for (var i=0;i<items.length;i+=1){' + '\n'
    + '      var m=items[i].querySelectorAll("["+A_HIT+"]");' + '\n'
    + '      for (var j=0;j<m.length;j+=1) out.push(m[j]);' + '\n'
    + '    }' + '\n'
    + '    return out;' + '\n'
    + '  }' + '\n'
    /* ── 范围 ─────────────────────────────────────────────────────── */
    + '  function tagsOf(item){' + '\n'
    + '    var raw=String(item.getAttribute(A_TAGS)||"").replace(TAGS_RE," ").replace(/^\\s+|\\s+$/g,"");' + '\n'
    + '    return raw==="" ? " " : " "+raw+" ";' + '\n'
    + '  }' + '\n'
    + '  function inScope(item,scope){' + '\n'
    + '    if (scope==="" || scope===D.scopeAll) return true;' + '\n'
    + '    return tagsOf(item).indexOf(" "+scope+" ")>=0;' + '\n'
    + '  }' + '\n'
    + '  function scopeOf(root){' + '\n'
    + '    var btn=root.querySelector("["+A_SCOPE+"][aria-pressed=\\"true\\"]");' + '\n'
    + '    return btn ? btn.getAttribute(A_SCOPE)||"" : "";' + '\n'
    + '  }' + '\n'
    /* ── 读数读写（DOM 即状态：判据读得到，重入也不丢） ───────────── */
    + '  function readNum(el){ var v=el ? parseInt(el.textContent,10) : NaN; return isFinite(v)&&v>0 ? v : 0; }' + '\n'
    + '  function countOf(root){ return readNum(one(root,A_COUNT)); }' + '\n'
    + '  function atOf(root){ return readNum(one(root,A_AT)); }' + '\n'
    + '  function writeCount(root,text){ var els=many(root,A_COUNT);' + '\n'
    + '    for (var i=0;i<els.length;i+=1) els[i].textContent=text; }' + '\n'
    + '  function writeAt(root,text){ var el=one(root,A_AT); if (el) el.textContent=text; }' + '\n'
    + '  function setNav(root,off){' + '\n'
    + '    var p=one(root,A_PREV), n=one(root,A_NEXT);' + '\n'
    + '    if (p) p.disabled=off;' + '\n'
    + '    if (n) n.disabled=off;' + '\n'
    + '  }' + '\n'
    + '  function setCurrent(marks,idx){' + '\n'
    + '    for (var i=0;i<marks.length;i+=1){' + '\n'
    + '      if (i===idx) marks[i].setAttribute(A_CURRENT,"");' + '\n'
    + '      else marks[i].removeAttribute(A_CURRENT);' + '\n'
    + '    }' + '\n'
    + '  }' + '\n'
    + '  function setError(root,msg){' + '\n'
    + '    var el=one(root,A_ERR), input=inputOf(root);' + '\n'
    + '    if (msg){' + '\n'
    + '      if (el){ el.textContent=msg; el.removeAttribute("hidden"); }' + '\n'
    + '      root.setAttribute(A_INVALID,"1");' + '\n'
    + '      if (input) input.setAttribute("aria-invalid","true");' + '\n'
    + '    } else {' + '\n'
    + '      if (el){ el.textContent=""; el.setAttribute("hidden",""); }' + '\n'
    + '      root.removeAttribute(A_INVALID);' + '\n'
    + '      if (input) input.removeAttribute("aria-invalid");' + '\n'
    + '    }' + '\n'
    + '  }' + '\n'
    + '  function readout(root,count,at,total,scopeLabel){' + '\n'
    + '    writeCount(root,count);' + '\n'
    + '    writeAt(root,at);' + '\n'
    + '    setNav(root,total===0);' + '\n'
    + '    var slot=one(root,A_SCOPE_NAME);' + '\n'
    + '    if (slot) slot.textContent=scopeLabel;' + '\n'
    + '  }' + '\n'
    + '  function fire(root,name,detail){ root.dispatchEvent(new CustomEvent(name,{bubbles:true,detail:detail})); }' + '\n'
    /* ── 重算（唯一入口） ─────────────────────────────────────────── */
    + '  function run(root){' + '\n'
    + '    var input=inputOf(root);' + '\n'
    + '    if (!input) return;' + '\n'
    + '    var items=itemsOf(root);' + '\n'
    + '    if (!items || items.length===0){' + '\n'
    + '      setError(root,D.unwiredText);' + '\n'
    + '      readout(root,D.unset,D.unset,0,"");' + '\n'
    + '      var none=one(root,A_EMPTY); if (none) none.setAttribute("hidden","");' + '\n'
    + '      return;' + '\n'
    + '    }' + '\n'
    + '    setError(root,"");' + '\n'
    + '    var i,j;' + '\n'
    + '    for (i=0;i<items.length;i+=1){ items[i].removeAttribute("hidden"); unmark(items[i]); }' + '\n'
    + '    var term=input.value.replace(/^\\s+|\\s+$/g,"").toLowerCase();' + '\n'
    + '    var scope=scopeOf(root);' + '\n'
    + '    var btn=root.querySelector("["+A_SCOPE+"][aria-pressed=\\"true\\"]");' + '\n'
    + '    var label=btn ? btn.querySelector("."+C_LAB) : null;' + '\n'
    + '    var scopeLabel=label ? label.textContent : "";' + '\n'
    + '    var hits=[], perScope={}, shown=0;' + '\n'
    + '    if (term!==""){' + '\n'
    + '      for (i=0;i<items.length;i+=1){' + '\n'
    + '        var item=items[i], mine=[];' + '\n'
    + '        if (inScope(item,scope) && textOf(item).toLowerCase().indexOf(term)>=0){' + '\n'
    + '          var nodes=[]; collect(item,nodes);' + '\n'
    + '          for (j=0;j<nodes.length;j+=1) wrap(nodes[j],term,mine);' + '\n'
    + '          shown+=1;' + '\n'
    + '        } else { item.setAttribute("hidden",""); }' + '\n'
    + '        for (j=0;j<mine.length;j+=1) hits.push(mine[j]);' + '\n'
    + '        if (mine.length>0){' + '\n'
    + '          var btns=root.querySelectorAll("["+A_SCOPE+"]");' + '\n'
    + '          for (j=0;j<btns.length;j+=1){' + '\n'
    + '            var v=btns[j].getAttribute(A_SCOPE)||"";' + '\n'
    + '            if (inScope(item,v)) perScope[v]=(perScope[v]||0)+mine.length;' + '\n'
    + '          }' + '\n'
    + '        }' + '\n'
    + '      }' + '\n'
    + '    }' + '\n'
    + '    var sbtns=root.querySelectorAll("["+A_SCOPE+"]");' + '\n'
    + '    for (i=0;i<sbtns.length;i+=1){' + '\n'
    + '      var slot=sbtns[i].querySelector("["+A_N+"]");' + '\n'
    + '      if (!slot) continue;' + '\n'
    + '      slot.textContent = term==="" ? D.unset : String(perScope[sbtns[i].getAttribute(A_SCOPE)||""]||0);' + '\n'
    + '    }' + '\n'
    + '    var total=hits.length;' + '\n'
    + '    var empty=one(root,A_EMPTY);' + '\n'
    + '    if (empty){ if (term!=="" && total===0) empty.removeAttribute("hidden"); else empty.setAttribute("hidden",""); }' + '\n'
    + '    if (root.getAttribute(A_LOADING)==="1"){' + '\n'
    + '      setNav(root,true);' + '\n'
    + '      fire(root,EV_QUERY,{name:root.getAttribute(A_ROOT),query:input.value,scope:scope===""?D.scopeAll:scope,hits:total,items:shown,loading:true});' + '\n'
    + '      return;' + '\n'
    + '    }' + '\n'
    + '    readout(root, term==="" ? D.unset : String(total), total===0 ? D.unset : "1", total, scopeLabel);' + '\n'
    + '    setCurrent(hits, total===0 ? -1 : 0);' + '\n'
    + '    fire(root,EV_QUERY,{name:root.getAttribute(A_ROOT),query:input.value,scope:scope===""?D.scopeAll:scope,hits:total,items:shown});' + '\n'
    + '  }' + '\n'
    /* ── 跳转 ─────────────────────────────────────────────────────── */
    + '  function jump(root,dir){' + '\n'
    + '    var marks=marksOf(root), n=marks.length;' + '\n'
    + '    if (n===0) return;' + '\n'
    + '    var at=atOf(root); if (at<1) at=1;' + '\n'
    + '    var next = dir>0 ? (at%n)+1 : ((at-2+n)%n)+1;' + '\n'
    + '    writeAt(root,String(next));' + '\n'
    + '    setCurrent(marks,next-1);' + '\n'
    + '    var t=marks[next-1];' + '\n'
    + '    if (t && t.scrollIntoView){ try { t.scrollIntoView({block:"nearest",inline:"nearest"}); } catch(e){ } }' + '\n'
    + '    fire(root,EV_JUMP,{name:root.getAttribute(A_ROOT),index:next,total:n});' + '\n'
    + '  }' + '\n'
    /* ── 载入态 ───────────────────────────────────────────────────── */
    + '  function setBusy(root,on){' + '\n'
    + '    var clear=one(root,A_CLEAR);' + '\n'
    + '    if (on){' + '\n'
    + '      root.setAttribute(A_LOADING,"1");' + '\n'
    + '      if (clear) clear.disabled=true;' + '\n'
    + '      setNav(root,true);' + '\n'
    + '    } else {' + '\n'
    + '      root.removeAttribute(A_LOADING);' + '\n'
    + '      if (clear) clear.disabled=root.hasAttribute(A_DISABLED);' + '\n'
    + '      run(root);' + '\n'
    + '    }' + '\n'
    + '  }' + '\n'
    /* ── 委派 ─────────────────────────────────────────────────────── */
    + '  doc.addEventListener("input",function(e){' + '\n'
    + '    var t=e.target;' + '\n'
    + '    if (!t || !t.hasAttribute || !t.hasAttribute(A_INPUT)) return;' + '\n'
    + '    var root=rootOf(t); if (!root || t.disabled) return;' + '\n'
    + '    run(root);' + '\n'
    + '  });' + '\n'
    + '  doc.addEventListener("click",function(e){' + '\n'
    + '    var t=e.target;' + '\n'
    + '    if (!t || !t.closest) return;' + '\n'
    + '    var root=rootOf(t); if (!root) return;' + '\n'
    + '    var clear=t.closest("["+A_CLEAR+"]");' + '\n'
    + '    if (clear){ if (clear.disabled) return; var input=inputOf(root);' + '\n'
    + '      if (input){ input.value=""; run(root); input.focus(); } return; }' + '\n'
    + '    var sbtn=t.closest("["+A_SCOPE+"]");' + '\n'
    + '    if (sbtn){ if (sbtn.disabled) return;' + '\n'
    + '      var all=root.querySelectorAll("["+A_SCOPE+"]");' + '\n'
    + '      for (var i=0;i<all.length;i+=1) all[i].setAttribute("aria-pressed", all[i]===sbtn?"true":"false");' + '\n'
    + '      run(root); return; }' + '\n'
    + '    var prev=t.closest("["+A_PREV+"]"); if (prev){ if (!prev.disabled) jump(root,-1); return; }' + '\n'
    + '    var next=t.closest("["+A_NEXT+"]"); if (next){ if (!next.disabled) jump(root,1); }' + '\n'
    + '  });' + '\n'
    + '  doc.addEventListener("keydown",function(e){' + '\n'
    + '    var t=e.target;' + '\n'
    + '    if (!t || !t.hasAttribute || !t.hasAttribute(A_INPUT)) return;' + '\n'
    + '    if (e.isComposing || e.keyCode===229) return;' + '\n'
    + '    var root=rootOf(t); if (!root) return;' + '\n'
    + '    if (e.key==="Enter"){ e.preventDefault(); jump(root, e.shiftKey ? -1 : 1); return; }' + '\n'
    + '    if (e.key==="Escape"){ var input=inputOf(root); if (input){ input.value=""; run(root); } }' + '\n'
    + '  });' + '\n'
    + '  doc.addEventListener(EV_LOADING,function(e){' + '\n'
    + '    var d=e.detail||{};' + '\n'
    + '    var root=(e.target && e.target.closest) ? e.target.closest(SEL_ROOT) : null;' + '\n'
    + '    if (!root && d.name) root=doc.querySelector(pick(A_ROOT,d.name));' + '\n'
    + '    if (!root) return;' + '\n'
    + '    setBusy(root, d.on!==false);' + '\n'
    + '  });' + '\n'
    /* ── 首次挂载：把渲染期的 `—` 换成本页真数 ─────────────────────── */
    + '  var roots=doc.querySelectorAll(SEL_ROOT);' + '\n'
    + '  for (var k=0;k<roots.length;k+=1){ roots[k].setAttribute(A_BOUND,"1"); run(roots[k]); }' + '\n'
    + '}());';
}
