export { CalorieRenderError } from './errors.js';
export type { CalorieRenderErrorCode } from './errors.js';
export { buildHomeData } from './home.js';
export type { HomeData } from './home.js';
export { MEAL_BUCKETS, buildMealDistribution, buildDietOverview } from './diet.js';
export type { MealBucket, MealSlice, MealDistribution, DietOverview } from './diet.js';
export { buildExerciseView } from './exercise.js';
export type { ExerciseView } from './exercise.js';
export { buildGoalView } from './goal.js';
export type { GoalView } from './goal.js';
export { renderHomeHtml, renderDietHtml, renderExerciseHtml, renderGoalHtml } from './html.js';
export { VIEW_KEYS, VIEW_SHAPES, viewShapeFor, assertStatMetrics } from './envelope.js';
export type { ViewName } from './envelope.js';
