/** radio-cards · **样式段**（本件唯一的样式来源）。
 *
 *  纪律（与本节其余件同一份）：
 *   · 只经 `skinVar()` 读皮肤——组件里**不写**手写的 CSS 变量（兜底链只许住在 `skin/contract.ts`）；
 *   · 全部规则 scope 在 `.<prefix>page-ui` 之下（不开本配方的页零命中）；不写 `:root`／`!important`、不新增 token 名；
 *   · **宽度只许容器判**：本件自己是容器（`container-type: inline-size`），折行靠内在尺寸 ＋ `flex-wrap`，
 *     窄档调整走 `@container`；`@media` 只判设备能力（`hover`／`pointer`／`prefers-reduced-motion`），不判宽度。
 *
 *  几何契约（判据钉住）：
 *   · 整卡是命中区 ⇒ 触控目标 ≥44×44（`RADIO_CARDS_CARD_MIN_HEIGHT_PX` ＝ 64 > 44）；
 *   · 选中态**至少两重标记**：左端 4px 竖条（形状）＋ 标记位里的对钩（字）；边框与底色是第三重（颜色）。
 *     皮肤「大字报刊」下强调色＝墨黑 ⇒ 只染色会塌，故形状与字必须自己扛。
 */
import { skinVar } from '../skin/contract.js';
import { RADIO_CARDS_LOADING_ATTR, radioCardsSlot } from './attrs.js';

/** 换行（仓库口径：不写字面换行转义）。 */
const LF = String.fromCharCode(10);

/** 触控目标的地板（px）：全宽口径，不只窄屏——低于它的命中区就是不许留的中间档。 */
export const RADIO_CARDS_MIN_TARGET_PX = 44;
/** 一张卡的最小高度（px）：大于地板（卡里有说明行，本来就比 44 高）。 */
export const RADIO_CARDS_CARD_MIN_HEIGHT_PX = 64;
/** 标记位方径（px）：装饰盒，可以小于地板（命中区由整卡承担）。 */
export const RADIO_CARDS_MARK_PX = 20;
/** 图标位方径（px）。 */
export const RADIO_CARDS_LEAD_PX = 34;
/** 选中时左端那道竖条的宽度（px）——**形状**那一重标记。 */
export const RADIO_CARDS_BAR_PX = 4;
/** 窄容器阈值（px）：标题与读数改走「读数另起一行」。**判的是本件自己的宽度**，不是视口。 */
export const RADIO_CARDS_NARROW_PX = 420;

/** 本组件的样式段。恒返回非空 CSS 文本。 */
export function radioCardsCss(input?: { readonly prefix?: string }): string {
  const p = input !== undefined && input !== null
    && typeof input.prefix === 'string' && input.prefix !== '' ? input.prefix : 'ilife-';
  const root = '.' + p + 'page-ui';
  const box = root + ' .' + p + 'block-radio-cards';
  const s = (slot: Parameters<typeof radioCardsSlot>[0]): string => root + ' .' + radioCardsSlot(slot, p);
  /** **裸类名**：用在复合选择器的中段（`X > .槽`、`X:has(…) > .槽`）。
   *  `s()` 自带作用域前缀，只许当选择器的**开头**——把它接在 `>` 后面会拼出
   *  `.ilife-page-ui X > .ilife-page-ui .槽`，那种规则永远匹配不到
   *  （2026-09 实拍：选中态的对钩一个都没画出来，就是这一处拼错）。 */
  const c = (slot: Parameters<typeof radioCardsSlot>[0]): string => '.' + radioCardsSlot(slot, p);
  const card = s('card');

  return [
    '/* radio-cards（单选卡组 · 形态 A「竖排卡」）：一列卡，每张里是标记 ＋ 图标位 ＋ 标题 ＋ 读数 ＋ 一行说明。',
    '   层次不靠阴影与大圆角（小票纸零阴影、大字报刊零圆角）：靠发丝线、字重与尺度差 ⇒ 换皮只换取值。 */',
    box + ' {',
    /* 宽度判据的落点：本件是**自己的容器**——嵌进侧栏／面板／卡片时照样按自己的宽度折行。 */
    '  container-type: inline-size;',
    '  display: grid;',
    '  gap: 8px;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-body') + ';',
    '  line-height: 1.5;',
    '}',
    '/* 组名行：主段（在选什么）＋ 次段（补充说明）。两段都能换行——**不许 `…` 截断**。 */',
    s('legend') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 4px 10px;',
    '  margin: 0;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 600;',
    '}',
    s('legend-title') + ' {',
    '  color: ' + skinVar('ink') + ';',
    '  font-weight: 700;',
    '  overflow-wrap: anywhere;',
    '}',
    s('legend-hint') + ' {',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 400;',
    '  overflow-wrap: anywhere;',
    '}',
    s('list') + ' {',
    '  display: grid;',
    '  gap: 8px;',
    '  min-width: 0;',
    '}',
    '/* 一张卡：整张是 `<label>`（命中区）。列宽写死两枚记号位，余下全给文字（`minmax(0,1fr)` 防压字）。 */',
    card + ' {',
    '  position: relative;',
    '  display: grid;',
    '  grid-template-columns: ' + String(RADIO_CARDS_MARK_PX) + 'px ' + String(RADIO_CARDS_LEAD_PX) + 'px minmax(0, 1fr);',
    '  grid-template-areas: "mk lead line" "mk lead desc";',
    '  gap: 3px 10px;',
    '  align-items: center;',
    '  box-sizing: border-box;',
    '  min-height: ' + String(RADIO_CARDS_CARD_MIN_HEIGHT_PX) + 'px;',
    '  padding: 11px 12px;',
    '  border: 2px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  cursor: pointer;',
    '  transition: transform 80ms cubic-bezier(.22, 1, .36, 1);',
    '}',
    '/* 标记位：空圆环（未选）→ 实心圆＋对钩（选中）。环／圆是**形状**，不靠色。 */',
    card + ' > ' + c('mk') + ' {',
    '  grid-area: mk;',
    '  position: relative;',
    '  display: block;',
    '  width: ' + String(RADIO_CARDS_MARK_PX) + 'px;',
    '  height: ' + String(RADIO_CARDS_MARK_PX) + 'px;',
    '  border: 2px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-pill') + ';',
    '  background: ' + skinVar('surface') + ';',
    '}',
    s('lead') + ' {',
    '  grid-area: lead;',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  width: ' + String(RADIO_CARDS_LEAD_PX) + 'px;',
    '  height: ' + String(RADIO_CARDS_LEAD_PX) + 'px;',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('surface-2') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 700;',
    '  line-height: 1;',
    '}',
    s('line') + ' {',
    '  grid-area: line;',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 2px 10px;',
    '  min-width: 0;',
    '}',
    s('title') + ' {',
    '  min-width: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-weight: 700;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 读数：右端等宽数字。**不写 `nowrap`**：金额换行难看，但溢出更难看（零横向溢出的判据在这儿收口）。 */',
    s('reading') + ' {',
    '  margin-left: auto;',
    '  text-align: right;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 700;',
    '  font-variant-numeric: tabular-nums;',
    '  overflow-wrap: anywhere;',
    '}',
    s('reading-label') + ' {',
    '  margin-right: 4px;',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '}',
    s('desc') + ' {',
    '  grid-area: desc;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1.55;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 禁用原因：跟说明同槽位（读屏也读得到"为什么不能选"）。 */',
    s('why') + ' {',
    '  display: block;',
    '  margin-top: 2px;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-style: normal;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 鼠标悬停只是**提示**，不是唯一通路（焦点态与选中态各有自己的标记）。 */',
    '@media (hover: hover) and (pointer: fine) {',
    '  ' + card + ':not(:has(input:checked)):not(:has(input[disabled])):hover {',
    '    border-color: ' + skinVar('ink-3') + ';',
    '  }',
    '}',
    '/* 真按下：缩一格（≤80ms 内回弹；只动 transform，不触发布局）。 */',
    card + ':active {',
    '  transform: scale(.98);',
    '}',
    '/* 选中态第一重（形状）：左端一道竖条。`inset` 光影不占盒、不推字。',
    '   判选中走**原生** `:has(input:checked)`：状态只有一处事实（`<input checked>`），不另挂修饰类。 */',
    card + ':has(input:checked) {',
    '  border-color: ' + skinVar('accent') + ';',
    '  background: ' + skinVar('accent-soft') + ';',
    '  box-shadow: inset ' + String(RADIO_CARDS_BAR_PX) + 'px 0 0 ' + skinVar('accent') + ';',
    '}',
    '/* 选中态第二重（字）：标记位变实心圆 ＋ 对钩。 */',
    card + ':has(input:checked) > ' + c('mk') + ' {',
    '  border-color: ' + skinVar('accent') + ';',
    '  background: ' + skinVar('accent') + ';',
    '}',
    card + ':has(input:checked) > ' + c('mk') + '::after {',
    '  content: "\\2713";',
    '  position: absolute;',
    '  inset: 0;',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  color: ' + skinVar('accent-ink') + ';',
    '  font-size: 12px;',
    '  font-weight: 800;',
    '  line-height: 1;',
    '}',
    '/* 焦点：原生 `input` 收到键盘焦点时，整卡与标记位一起显形（**可见焦点，≥2px**）。 */',
    card + ':has(input:focus-visible) {',
    '  outline: 2px solid ' + skinVar('accent') + ';',
    '  outline-offset: 2px;',
    '}',
    card + ' > input:focus-visible ~ ' + c('mk') + ' {',
    '  outline: 2px solid ' + skinVar('accent') + ';',
    '  outline-offset: 2px;',
    '}',
    '/* 原生单选：视觉隐藏但**仍在无障碍树里**（1px 盒 ＋ `opacity:0`，不是 `display:none`）。 */',
    card + ' > input[type="radio"] {',
    '  position: absolute;',
    '  width: 1px;',
    '  height: 1px;',
    '  opacity: 0;',
    '  pointer-events: none;',
    '}',
    '/* 禁用：`cursor: not-allowed` ＋ 说明为什么（原因那句由标记渲染在卡里）。 */',
    card + ':has(input[disabled]) {',
    '  cursor: not-allowed;',
    '}',
    card + ':has(input[disabled]) > ' + c('title') + ', ' + card + ':has(input[disabled]) > ' + c('desc') + ',',
    card + ':has(input[disabled]) > ' + c('line') + ' {',
    '  color: ' + skinVar('ink-2') + ';',
    '}',
    '/* 加载态：读数在原地换成那句话（盒模型不动 ⇒ 不跳版）。加载是**整组**的事，故读根上的标记。 */',
    box + '[' + RADIO_CARDS_LOADING_ATTR + '="1"] ' + card + ' > ' + c('line') + ' > ' + c('reading') + ' {',
    '  color: ' + skinVar('ink-3') + ';',
    '}',
    '/* 空态与加载态那一句：弱文字 ＋ 设计过的内距（不是留白）。 */',
    s('empty') + ', ' + s('loading') + ' {',
    '  margin: 0;',
    '  padding: 12px 14px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 错态：写在控件旁边（不是只染色），并带一枚记号字。 */',
    s('error') + ' {',
    '  display: flex;',
    '  gap: 6px;',
    '  margin: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 600;',
    '  overflow-wrap: anywhere;',
    '}',
    s('error') + '::before {',
    '  content: "\\26A0";',
    '  flex: none;',
    '  color: ' + skinVar('ink-2') + ';',
    '}',
    '/* 窄容器（<' + String(RADIO_CARDS_NARROW_PX) + 'px）：标题与读数不再挤同一行（读数另起一行、左对齐）。',
    '   判的是**本件自己的宽度**：本件会被嵌进侧栏／面板／卡片，视口宽 ≠ 组件宽（所以这里不用 `@media`）。 */',
    '@container (max-width: ' + String(RADIO_CARDS_NARROW_PX) + 'px) {',
    '  ' + s('line') + ' {',
    '    display: grid;',
    '    gap: 2px;',
    '  }',
    '  ' + s('reading') + ' {',
    '    margin-left: 0;',
    '    text-align: left;',
    '  }',
    '}',
    '/* 动效偏好：只关过渡，不关状态（状态不许卡在半路 ⇒ 不用 `transitionend` 驱动任何东西）。 */',
    '@media (prefers-reduced-motion: reduce) {',
    '  ' + card + ' {',
    '    transition: none;',
    '  }',
    '}',
  ].join(LF);
}
