/** cash-waterline · **三个形态各自的形状**（同目录第二份样式来源；由 `style.ts` 的 `cashWaterlineCss()` 汇总）。
 *
 *  为什么有这一件：本件一次落三个形态（逐日水位柱／每周子弹图／进出水三栏），样式段一度到 482 行
 *  （本包告警线 350，`packages/base-render/AGENTS.md`）。三个形态各自是一段边界干净的形状——形态 A 是
 *  画布上的柱与底线，形态 B 是每行一条轨道，形态 C 是三栏纸卡——独立成件；**取值一个字节都不许改**，
 *  搬的只是「住哪个文件」。
 *
 *  边界与另一半的分工：卡头（标题／印）、三形态共用的图例与点名那块与脚注、焦点环，以及窄容器的两处覆盖
 *  仍住 `style.ts`——那几段在汇总数组的头与尾，而一份文件只能插在一个位置上，**连续的一段**才搬得动，
 *  这样产物逐字节不变（先例 `scatter-fit/style-forms.ts`、`date-range/style-calendar.ts`）。
 *  纪律同 `style.ts`：只经 `skinVar()` 读皮肤／全部规则 scope 在 `.<prefix>page-ui` 之下／
 *  零 `:root`／零 `!important`／零颜色字面量（色一律走 `skinVar()` 的兜底链）。
 */
import { skinVar } from '../skin/contract.js';
import {
  CASH_WATERLINE_HEIGHT_VAR,
  CASH_WATERLINE_THRESHOLD_VAR,
  CASH_WATERLINE_USED_THRESHOLD_VAR,
  CASH_WATERLINE_WIDTH_VAR,
  cashWaterlineSlot,
  type CashWaterlineSlot,
} from './attrs.js';

/** 换行（仓库口径：不写字面换行转义）。 */
const LF = String.fromCharCode(10);

/** 水位画布的高度（px）：宽容器一档、窄容器一档（窄档覆盖住 `style.ts` 的窄容器那一段）。 */
export const CASH_WATERLINE_PLOT_HEIGHT_PX = 190;

/** 三个形态各自的形状。恒返回非空 CSS 文本（由 `cashWaterlineCss()` 插在正确的位置上）。 */
export function cashWaterlineFormsCss(input?: { readonly prefix?: string }): string {
  const p = input !== undefined && input !== null
    && typeof input.prefix === 'string' && input.prefix !== '' ? input.prefix : 'ilife-';
  const root = '.' + p + 'page-ui';
  const s = (slot: CashWaterlineSlot): string => root + ' .' + cashWaterlineSlot(slot, p);
  /* 槽类名（**不带 scope**）：只用在已经落进本件某条选择器内部的位置（前缀由外层那条选择器给）。 */
  const c = (slot: CashWaterlineSlot): string => '.' + cashWaterlineSlot(slot, p);

  return [
    /* ── 形态 A：逐日水位柱 ───────────────────────────────────────── */
    s('plot') + ' {',
    '  position: relative;',
    '  display: flex;',
    '  align-items: flex-end;',
    '  gap: 5px;',
    '  height: ' + String(CASH_WATERLINE_PLOT_HEIGHT_PX) + 'px;',
    '  min-width: 0;',
    '  border-bottom: 1px solid ' + skinVar('line') + ';',
    '}',
    /* 底线：一条虚线 ＋ 一枚带字的标签（**字在**，不是只靠线）。 */
    s('thr') + ' {',
    '  position: absolute;',
    '  left: 0;',
    '  right: 0;',
    '  bottom: var(' + CASH_WATERLINE_THRESHOLD_VAR + ', 30%);',
    '  z-index: 2;',
    '  border-top: 2px dashed ' + skinVar('danger') + ';',
    '  pointer-events: none;',
    '}',
    s('thr-text') + ' {',
    '  position: absolute;',
    '  left: 0;',
    '  bottom: 3px;',
    '  padding: 1px 6px;',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('danger-soft') + ';',
    '  color: ' + skinVar('danger') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 700;',
    '  white-space: nowrap;',
    '}',
    /* 一格 ＝ 一天；柱子贴着底沿往上长（柱高由行内 `--cash-waterline-h` 给）。 */
    s('col') + ' {',
    '  position: relative;',
    '  display: flex;',
    '  flex-direction: column;',
    '  justify-content: flex-end;',
    '  flex: 1 1 0;',
    '  height: 100%;',
    '  min-width: 0;',
    '}',
    s('fill') + ' {',
    '  position: relative;',
    '  z-index: 1;',
    '  display: block;',
    '  width: 100%;',
    '  height: var(' + CASH_WATERLINE_HEIGHT_VAR + ', 0%);',
    '  min-height: 4px;',
    '  border-radius: ' + skinVar('radius-sm') + ' ' + skinVar('radius-sm') + ' 0 0;',
    '  background: ' + skinVar('accent') + ';',
    '}',
    /* 跌破底线那一格：柱色换 `danger`（**色**只是三通路里的一条，日期与金额在点名那块）。 */
    s('col') + '.is-low ' + c('fill') + ' {',
    '  background: ' + skinVar('danger') + ';',
    '}',
    /* 今天那一格：一根**贯穿画布的竖游标**（形）＋ 轴上的「今天」（字）＋ 强调色系（色）。
       为什么不是"整列软底"：软底与柱同宽、又占满画布高度，一眼读起来就是"那天的余量很高"——
       与"标出今天"是两件事（2026-09-25 自看样张时抓到）。游标由柱子盖住下半段（`z-index`），
       只从柱顶往上露出来 ⇒ 不会盖在读数上，也不会被误读成柱子。 */
    s('col') + '.is-today::before {',
    '  content: "";',
    '  position: absolute;',
    '  top: 0;',
    '  bottom: 0;',
    '  left: 50%;',
    '  width: 2px;',
    '  margin-left: -1px;',
    '  background: ' + skinVar('accent') + ';',
    '}',
    /* 横轴：只出算好的那几枚刻度字（`space-between` 摊开，`flex-wrap` 兜底换行——**不压字、不截断**）。 */
    s('xax') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  justify-content: space-between;',
    '  gap: 2px 12px;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '  font-variant-numeric: tabular-nums;',
    '}',
    s('xax-cell') + ' {',
    '  white-space: nowrap;',
    '}',
    s('xax-cell') + '.is-today {',
    '  color: ' + skinVar('accent-text') + ';',
    '  font-weight: 700;',
    '}',
    /* ── 形态 B：每周子弹图 ───────────────────────────────────────── */
    s('bullet') + ' {',
    '  display: grid;',
    '  gap: 0;',
    '  min-width: 0;',
    '}',
    s('brow') + ' {',
    '  display: grid;',
    '  grid-template-columns: minmax(0, 1fr);',
    '  gap: 5px;',
    '  min-width: 0;',
    '  padding: 8px 0;',
    '}',
    s('brow') + ' + ' + c('brow') + ' {',
    '  border-top: 1px solid ' + skinVar('line') + ';',
    '}',
    /* 越过底线那一周：左侧 2px 侧标（**形**）＋ 读数里点名（**字**）＋ `danger`（**色**）。 */
    s('brow') + '.is-low {',
    '  padding-left: 10px;',
    '  border-left: 2px solid ' + skinVar('danger') + ';',
    '}',
    s('bhd') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 4px 10px;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '}',
    s('bhd-name') + ' {',
    '  color: ' + skinVar('ink') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 700;',
    '}',
    s('bhd-num') + ' {',
    '  font-variant-numeric: tabular-nums;',
    '  white-space: nowrap;',
    '}',
    s('net') + ' {',
    '  margin-left: auto;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-variant-numeric: tabular-nums;',
    '  font-weight: 700;',
    '  white-space: nowrap;',
    '}',
    s('over') + ' {',
    '  color: ' + skinVar('danger') + ';',
    '  font-weight: 700;',
    '  white-space: nowrap;',
    '}',
    /* 轨道：满宽＝整段预算；填充＝累计已用（封顶 100%，超出部分靠读数点名）。 */
    s('rail') + ' {',
    '  position: relative;',
    '  display: block;',
    '  height: 20px;',
    '  min-width: 0;',
    '  overflow: hidden;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('surface') + ';',
    '}',
    s('rail-fill') + ' {',
    '  position: absolute;',
    '  inset: 0 auto 0 0;',
    '  width: var(' + CASH_WATERLINE_WIDTH_VAR + ', 0%);',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('accent') + ';',
    '}',
    s('brow') + '.is-low ' + c('rail-fill') + ' {',
    '  background: ' + skinVar('danger') + ';',
    '}',
    /* 底线刻度：**落在“余量跌破底线”的那个已用位置上**（＝ `100 − 底线`，值由 `render.ts` 给）。 */
    s('rail-thr') + ' {',
    '  position: absolute;',
    '  top: 0;',
    '  bottom: 0;',
    '  left: var(' + CASH_WATERLINE_USED_THRESHOLD_VAR + ', 70%);',
    '  width: 0;',
    '  border-left: 2px solid ' + skinVar('danger') + ';',
    '}',
    /* ── 形态 C：进出水三栏 ───────────────────────────────────────── */
    s('three') + ' {',
    '  display: grid;',
    '  grid-template-columns: repeat(3, minmax(0, 1fr));',
    '  gap: 10px;',
    '  min-width: 0;',
    '}',
    s('card') + ' {',
    '  display: grid;',
    '  gap: 6px;',
    '  min-width: 0;',
    '  padding: 8px 10px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('surface') + ';',
    '}',
    s('card-hd') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 6px;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '}',
    s('card-name') + ' {',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-weight: 700;',
    '}',
    s('card-count') + ' {',
    '  font-variant-numeric: tabular-nums;',
    '  white-space: nowrap;',
    '}',
    s('card-total') + ' {',
    '  margin-left: auto;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: ' + skinVar('fs-h3') + ';',
    '  font-variant-numeric: tabular-nums;',
    '  font-weight: 700;',
    '}',
    s('line') + ' {',
    '  display: grid;',
    '  grid-template-columns: minmax(0, 1fr) auto;',
    '  gap: 8px;',
    '  align-items: center;',
    '  min-width: 0;',
    '  padding: 2px 0;',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '}',
    s('line-bar') + ' {',
    '  position: relative;',
    '  display: block;',
    '  height: 10px;',
    '  min-width: 0;',
    '  border-radius: ' + skinVar('radius-pill') + ';',
    '  background: ' + skinVar('surface-2') + ';',
    '}',
    s('line-fill') + ' {',
    '  position: absolute;',
    '  inset: 0 auto 0 0;',
    '  width: var(' + CASH_WATERLINE_WIDTH_VAR + ', 0%);',
    '  border-radius: ' + skinVar('radius-pill') + ';',
    '  background: ' + skinVar('accent') + ';',
    '}',
    /* 出／余两条口径换强调色的**深档**（`accent-text`），进那条走 `accent`：
       色只用来分开两条口径——每行都带名字与钱数、栏头写着「进」「出」「余」，色不是唯一信息。 */
    s('line-bar') + '.is-out ' + c('line-fill') + ' {',
    '  background: ' + skinVar('accent-text') + ';',
    '}',
    s('line-bar') + '.is-left ' + c('line-fill') + ' {',
    '  background: ' + skinVar('accent-text') + ';',
    '}',
    s('line-text') + ' {',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-variant-numeric: tabular-nums;',
    '  font-weight: 700;',
    '  white-space: nowrap;',
    '}',
    /* 判定那块：**结论写成字**（撑得住／撑不住 ＋ 差多少），色只是第三次提醒。 */
    s('verdict') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 6px 10px;',
    '  margin: 0;',
    '  padding-top: 8px;',
    '  border-top: 1px solid ' + skinVar('line') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  overflow-wrap: anywhere;',
    '}',
    s('verdict-word') + ' {',
    '  flex: none;',
    '  color: ' + skinVar('ok') + ';',
    '  font-weight: 700;',
    '  white-space: nowrap;',
    '}',
    s('verdict') + '.is-danger ' + c('verdict-word') + ' {',
    '  color: ' + skinVar('danger') + ';',
    '}',
  ].join(LF);
}
