/** status-row · **样式段**（本件唯一的样式来源）。
 *
 *  三条纪律（与组件层其余件同一份）：
 *   1. 颜色／圆角／阴影／字面／字号**一律经 `skinVar()` 读**（产出带兜底链的 `var()` 串，
 *      老页面没挂皮肤时落到那 11 个冻结 token）——本件源码里**不出现**手写的 `var(--ilife-…)`；
 *   2. 全部规则 scope 在 `.<prefix>page-ui` 之下（不开 pageUi 的页零命中 ⇒ 加法式）；
 *   3. **状态靠「字 ＋ 形 ＋ 色」三样一起**给：徽标与轨道点的形状差异逐档写在下面
 *      （空心圆／双环实心／实心圆／空心方／双线菱；无框底线／空心框／实底色块／框＋底块／双线框），
 *      所以「大字报刊」（强调色＝墨黑）那档也分得开。
 *
 *  几何契约（钉在判据里）：
 *   · 行高 ≥ `STATUS_ROW_ITEM_MIN_HEIGHT_PX`（44）：本件没有可点元素，但行高先钉在这个地板上，
 *     页面把整行接成入口时不会掉到 44 以下；
 *   · 金额与到期日**永不 `…` 截断**（`white-space:nowrap`，不写 `overflow:hidden`）；
 *   · 窄宽由**容器**决定（`container-type:inline-size` ＋ `@container`），不看视口：
 *     本件会被嵌进侧栏／面板／卡片，视口宽 ≠ 组件宽。本件**零动效**（没有可卡住的中间态）。
 */
import { skinVar } from '../skin/contract.js';
import { statusRowClass, statusRowSlot, type StatusRowSlot } from './attrs.js';

/** 换行（仓库口径：不写字面换行转义）。 */
const LF = String.fromCharCode(10);

/** 本件的内容容器名（`@container` 按它命中，不会跟别件的容器串味）。 */
export const STATUS_ROW_CONTAINER = 'ilife-status-row';
/** 窄档断点（px）：容器窄于它就换排法（**不是**视口断点）。 */
export const STATUS_ROW_NARROW_MAX_PX = 460;
/** 轨道点直径（px）。 */
export const STATUS_ROW_NODE_SIZE_PX = 13;
/** 左轨列宽（px）：点居中在它里面，连线走它的中线。 */
export const STATUS_ROW_RAIL_WIDTH_PX = 24;
/** 行高下限（px）：44 是全仓的触控地板；本件没有可点元素，行高先钉在这里。 */
export const STATUS_ROW_ITEM_MIN_HEIGHT_PX = 44;
/** 行内上下内距（px）：换算连线与点的位置时用它（别处不许再写这个数）。 */
const ROW_PAD_Y = 9;

/** 本组件的样式段。恒返回非空 CSS 文本。 */
export function statusRowCss(input?: { readonly prefix?: string }): string {
  const p = input !== undefined && input !== null
    && typeof input.prefix === 'string' && input.prefix !== '' ? input.prefix : 'ilife-';
  const root = '.' + p + 'page-ui';
  /** 槽类的**裸**选择器（不带 `.page-ui` 前缀）：只用在"祖先已经由 `sc()` 给过"的嵌套选择器里——
   *  否则会拼成 `.page-ui .a .page-ui .b`（那要求 `.page-ui` 出现在件内部），永远匹配不上（实拍踩过）。 */
  const n = (slot: StatusRowSlot): string => '.' + statusRowSlot(slot, p);
  /** 槽类的完整选择器（唯一的拼法：槽名只来自 `attrs.ts` 的闭集）。 */
  const sc = (slot: StatusRowSlot): string => root + ' ' + n(slot);
  const v = skinVar;
  return [
    '/* status-row（状态台账行）：一笔一行 —— 轨道点（形）＋ 阶段徽标（字）＋ 金额；第二行补充与到期日。 */',
    root + ' .' + statusRowClass(p) + ' {',
    '  display: flex;',
    '  flex-direction: column;',
    '  min-width: 0;',
    '  container: ' + STATUS_ROW_CONTAINER + ' / inline-size;',
    '}',
    sc('head') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 4px 10px;',
    '  padding-bottom: 6px;',
    '  border-bottom: 1px solid ' + v('line') + ';',
    '}',
    sc('heading') + ' {',
    '  color: ' + v('ink-3') + ';',
    '  font-size: 11.5px;',
    '  font-weight: 700;',
    '  letter-spacing: .22em;',
    '}',
    sc('count') + ' {',
    '  margin-left: auto;',
    '  color: ' + v('ink-2') + ';',
    '  font-family: ' + v('font-num') + ';',
    '  font-size: ' + v('fs-xs') + ';',
    '  font-variant-numeric: tabular-nums;',
    '  white-space: nowrap;',
    '}',
    sc('list') + ' {',
    '  display: flex;',
    '  flex-direction: column;',
    '  min-width: 0;',
    '}',
    sc('item') + ' {',
    '  position: relative;',
    '  display: grid;',
    '  grid-template-columns: auto minmax(0, 1fr);',
    '  gap: 0 10px;',
    '  box-sizing: border-box;',
    '  min-width: 0;',
    '  min-height: ' + STATUS_ROW_ITEM_MIN_HEIGHT_PX + 'px;',
    '  padding: ' + ROW_PAD_Y + 'px 0;',
    '}',
    '/* 从左轨中点往下连到下一行（最后一行不画）："走到哪了"的位置感由这条线承担。 */',
    sc('item') + ':not(:last-child)::after {',
    '  content: "";',
    '  position: absolute;',
    '  left: ' + (STATUS_ROW_RAIL_WIDTH_PX / 2 - 0.5) + 'px;',
    '  top: ' + (ROW_PAD_Y + 3 + STATUS_ROW_NODE_SIZE_PX + 3) + 'px;',
    '  bottom: -2px;',
    '  width: 1px;',
    '  background: ' + v('line') + ';',
    '}',
    '/* 走完的那一段连线变实（不是靠变色：线型之分自己就是第二样信息）。色走**主色实底**——它是"无文字的条"，',
    '   `docs/base/base-render/选中态与皮肤语言.md` 第三节法则表把"已完成连接线"逐字点在这一档；',
    '   旧写法 `background: ink` 是拿正文墨色当面，纸面语言里没有对应语汇，`ink` 皮肤下只读成一道近黑印痕。 */',
    sc('item') + '.is-ok + ' + n('item') + '::after { background: ' + v('accent') + '; }',
    sc('rail') + ' {',
    '  display: flex;',
    '  justify-content: center;',
    '  flex: 0 0 auto;',
    '  width: ' + STATUS_ROW_RAIL_WIDTH_PX + 'px;',
    '}',
    sc('node') + ' {',
    '  position: relative;',
    '  display: block;',
    '  box-sizing: border-box;',
    '  width: ' + STATUS_ROW_NODE_SIZE_PX + 'px;',
    '  height: ' + STATUS_ROW_NODE_SIZE_PX + 'px;',
    '  margin-top: 3px;',
    '  border: 1.5px solid ' + v('line') + ';',
    '  border-radius: 50%;',
    '  background: ' + v('surface') + ';',
    '}',
    '/* 五档形状（色只是第三样）：空心圆／双环实心／实心圆／空心方／双线菱。 */',
    sc('item') + '.is-active ' + n('node') + ' { border-color: ' + v('accent') + '; }',
    sc('item') + '.is-active ' + n('node') + '::after {',
    '  content: "";',
    '  position: absolute;',
    '  inset: 2.5px;',
    '  border-radius: 50%;',
    '  background: ' + v('accent') + ';',
    '}',
    '/* 「走完了」那一档：实心圆＝**无文字的点** ⇒ 主色实底（法则表第三节：无文字的点／格／条走 `accent`）；',
    '   旧写法 `border-color: ink; background: ink` 是拿正文墨色当面，属第四节禁止项 1／4。 */',
    sc('item') + '.is-ok ' + n('node') + ' {',
    '  border-color: ' + v('accent') + ';',
    '  background: ' + v('accent') + ';',
    '}',
    sc('item') + '.is-warn ' + n('node') + ' {',
    '  border-color: ' + v('warn') + ';',
    '  border-radius: 2px;',
    '  background: ' + v('warn-soft') + ';',
    '}',
    sc('item') + '.is-danger ' + n('node') + ' {',
    '  border: 3px double ' + v('danger') + ';',
    '  border-radius: 0;',
    '  background: ' + v('danger-soft') + ';',
    '  transform: rotate(45deg);',
    '}',
    sc('body') + ' {',
    '  display: flex;',
    '  flex-direction: column;',
    '  min-width: 0;',
    '}',
    sc('line1') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 4px 10px;',
    '  min-width: 0;',
    '}',
    sc('name') + ' {',
    '  min-width: 0;',
    '  color: ' + v('ink') + ';',
    '  font-size: ' + v('fs-sm') + ';',
    '  font-weight: 700;',
    '  overflow-wrap: anywhere;',
    '}',
    sc('badge') + ' {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  box-sizing: border-box;',
    '  flex: 0 0 auto;',
    '  padding: 1px 8px;',
    '  border: 1px solid transparent;',
    '  border-radius: ' + v('radius-pill') + ';',
    '  background: none;',
    '  color: ' + v('ink-2') + ';',
    '  font-size: ' + v('fs-xs') + ';',
    '  font-weight: 700;',
    '  line-height: 1.5;',
    '  white-space: nowrap;',
    '}',
    '/* 徽标五档形状：无框底线／空心框／实底色块／框＋底块／双线框。 */',
    sc('badge') + '.is-neutral {',
    '  padding: 0 0 1px;',
    '  border: 0;',
    '  border-bottom: 2px solid ' + v('line') + ';',
    '  border-radius: 0;',
    '}',
    sc('badge') + '.is-active {',
    '  border: 1px solid ' + v('accent') + ';',
    '  background: ' + v('accent-soft') + ';',
    '  color: ' + v('accent-text') + ';',
    '}',
    sc('badge') + '.is-ok {',
    '  border: 0;',
    '  background: ' + v('ok-soft') + ';',
    '  color: ' + v('ok') + ';',
    '}',
    sc('badge') + '.is-warn {',
    '  border: 1px solid ' + v('warn') + ';',
    '  background: ' + v('warn-soft') + ';',
    '  color: ' + v('warn') + ';',
    '}',
    sc('badge') + '.is-danger {',
    '  border: 3px double ' + v('danger') + ';',
    '  border-radius: 0;',
    '  background: none;',
    '  color: ' + v('danger') + ';',
    '}',
    sc('amount') + ' {',
    '  margin-left: auto;',
    '  flex: 0 0 auto;',
    '  color: ' + v('ink') + ';',
    '  font-family: ' + v('font-num') + ';',
    '  font-size: ' + v('fs-sm') + ';',
    '  font-variant-numeric: tabular-nums;',
    '  font-weight: 700;',
    '  text-align: right;',
    '  white-space: nowrap;',
    '}',
    sc('amount') + ' small {',
    '  margin-left: 2px;',
    '  color: ' + v('ink-2') + ';',
    '  font-size: ' + v('fs-xs') + ';',
    '  font-weight: 600;',
    '}',
    sc('line2') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 2px 10px;',
    '  min-width: 0;',
    '  margin-top: 3px;',
    '  color: ' + v('ink-3') + ';',
    '  font-size: ' + v('fs-xs') + ';',
    '}',
    sc('meta') + ' {',
    '  min-width: 0;',
    '  overflow-wrap: anywhere;',
    '}',
    sc('due') + ' {',
    '  display: inline-flex;',
    '  align-items: baseline;',
    '  gap: 4px;',
    '  margin-left: auto;',
    '  padding-bottom: 1px;',
    '  border-bottom: 2px solid transparent;',
    '  color: ' + v('ink-2') + ';',
    '  font-family: ' + v('font-num') + ';',
    '  font-size: ' + v('fs-xs') + ';',
    '  font-variant-numeric: tabular-nums;',
    '  white-space: nowrap;',
    '}',
    '/* 到期日五档形状：无线／双线／细实线／点线／粗实线＋加粗。 */',
    sc('due') + '.is-active { border-bottom: 3px double ' + v('accent') + '; color: ' + v('accent-text') + '; }',
    sc('due') + '.is-ok { border-bottom: 2px solid ' + v('ok') + '; }',
    sc('due') + '.is-warn { border-bottom: 2px dotted ' + v('warn') + '; color: ' + v('warn') + '; }',
    sc('due') + '.is-danger {',
    '  border-bottom: 2px solid ' + v('danger') + ';',
    '  color: ' + v('danger') + ';',
    '  font-weight: 700;',
    '}',
    sc('due') + ' em {',
    '  color: ' + v('ink-3') + ';',
    '  font-family: ' + v('font') + ';',
    '  font-style: normal;',
    '}',
    sc('absent') + ' {',
    '  padding: 10px 0 2px;',
    '  color: ' + v('ink-3') + ';',
    '  font-size: ' + v('fs-sm') + ';',
    '}',
    sc('foot') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 4px 12px;',
    '  margin-top: 8px;',
    '  padding-top: 8px;',
    '  border-top: 1px solid ' + v('line') + ';',
    '  color: ' + v('ink-2') + ';',
    '  font-size: ' + v('fs-xs') + ';',
    '}',
    '/* 窄档：金额与到期日不再往右顶，各占一整行（右对齐）——听容器，不听视口。 */',
    '@container ' + STATUS_ROW_CONTAINER + ' (max-width: ' + STATUS_ROW_NARROW_MAX_PX + 'px) {',
    '  ' + sc('amount') + ' { margin-left: 0; flex: 1 1 100%; }',
    '  ' + sc('due') + ' { margin-left: 0; }',
    '}',
  ].join(LF);
}
