/** date-range · **样式段**（本件唯一的样式来源）。
 *
 *  纪律（与本层其余件同一份）：只经 `skinVar()` 读皮肤／全部规则 scope 在 `.<prefix>page-ui` 之下／
 *  零 `:root`／零 `!important`／零自定义属性／宽度只由 `@container` 判（`@media` 只判设备能力）。
 *
 *  几何契约（判据钉住）：翻月键、快捷档、起止两格、**每一格天**都不小于 `DATE_RANGE_TOUCH_PX`（44）——
 *  判据量的是**有效命中区**（基准盒 ±26px、2px 步长扫描、逐点归属回同一控件的包围盒），不是元素盒。
 *  两条**有意偏离原型**的间距口径，写在这里备查：
 *   · 独立的相邻控件（翻月键之间、快捷档之间、起止两格之间）一律留 `DATE_RANGE_GAP_PX`（8px）；
 *   · **日历格之间 0 缝**（**矩阵缝并进格子**）：7 列 × 44px ＝ 308px 已是硬约束，缝留在格子之间会把
 *     每格的有效命中区再削一份（2026-09-25 实测：320 档每格只剩 34.8px、有效命中 34–36px）。
 *     缝并进格子之后，窄档再由**满幅**兜底（见 `style-calendar.ts` 那条 `@container`）。
 *
 *  零阴影下立层次：日历块走软底（`surface-2`），区间内的格走纸面（`surface`），两端走**强调面**
 *  （软底 `accent-soft` ＋ 主色字 `accent-text` ＋ 主色描边 `accent`：那一格里有数字＝有文字），
 *  「今天」靠一圈发丝线（`border-color`，盒内 1px，不推版）。
 */
import { skinVar } from '../skin/contract.js';
import {
  DATE_RANGE_BOX_PAD_X_PX,
  DATE_RANGE_GAP_PX,
  DATE_RANGE_TOUCH_PX,
  dateRangeSlot,
  type DateRangeSlot,
} from './attrs.js';
import { dateRangeCalendarCss } from './style-calendar.js';

/** 换行（仓库口径：不写字面换行转义）。 */
const LF = String.fromCharCode(10);

/** 窄容器阈值（px）：**本件自己的宽度**。低于它时起止两格竖排（一格一行，日期串读得全）。 */
const NARROW_PX = 420;

/** 按下反馈的时长（ms）：≤80ms（与 `style-calendar.ts` 里那一条同一个口径，两段各写一份不互相 import）。 */
const PRESS_MS = 80;

/** 本组件的样式段（＝这一份 ＋ `style-calendar.ts` 那一份，**一次调用拿全部**）。恒返回非空 CSS 文本。 */
export function dateRangeCss(input?: { readonly prefix?: string }): string {
  const p = input !== undefined && input !== null
    && typeof input.prefix === 'string' && input.prefix !== '' ? input.prefix : 'ilife-';
  const root = '.' + p + 'page-ui';
  const box = root + ' .' + p + 'block-date-range';
  const s = (slot: DateRangeSlot): string => root + ' .' + dateRangeSlot(slot, p);
  /** 拼在 `box` **后面**的槽类（不再带 `.<prefix>page-ui`，否则会拼出嵌套的假选择器）。 */
  const inBox = (slot: DateRangeSlot): string => ' .' + dateRangeSlot(slot, p);
  const touch = String(DATE_RANGE_TOUCH_PX) + 'px';

  return [
    '/* date-range（日期范围 · 形态 B「日历缩略」）：起止两格 ＋ 一排快捷档（命中的带 ✓）＋ 一个月的格子，',
    '   底下那句口径点名「当前按 哪一档、从哪天到哪天、共几天」。零阴影下层次靠发丝线与底色块。 */',
    box + ' {',
    '  container-type: inline-size;',
    '  display: grid;',
    '  gap: 10px;',
    '  min-width: 0;',
    '  padding: 12px ' + String(DATE_RANGE_BOX_PAD_X_PX) + 'px 14px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-body') + ';',
    '  line-height: 1.5;',
    '}',
    box + ' > * {',
    '  min-width: 0;',
    '}',
    '/* 第一行：名字 ＋ 状态字（`当前按 本周`／`自定义区间`／`还未选`／`更新中`）。 */',
    s('head') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: center;',
    '  justify-content: space-between;',
    '  gap: 4px 12px;',
    '  min-width: 0;',
    '}',
    s('label') + ' {',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 600;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 状态字：一枚带发丝线的签（**字**这一档：换皮换不掉"按的是哪一档"）。 */',
    s('state') + ' {',
    '  box-sizing: border-box;',
    '  max-width: 100%;',
    '  padding: 1px 8px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 700;',
    '  letter-spacing: .02em;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 起止两格：两列（窄容器竖排），与快捷档／日历之间各留 ' + String(DATE_RANGE_GAP_PX) + 'px。 */',
    s('ends') + ' {',
    '  display: grid;',
    '  grid-template-columns: repeat(2, minmax(0, 1fr));',
    '  gap: ' + String(DATE_RANGE_GAP_PX) + 'px;',
    '  min-width: 0;',
    '}',
    s('from') + ',',
    s('to') + ' {',
    '  display: flex;',
    '  align-items: center;',
    '  gap: 6px;',
    '  min-width: 0;',
    '}',
    s('endLabel') + ' {',
    '  flex: none;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '}',
    s('input') + ' {',
    '  box-sizing: border-box;',
    '  flex: 1 1 0;',
    '  min-width: 0;',
    '  height: ' + touch + ';',
    '  padding: 0 10px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-variant-numeric: tabular-nums;',
    '  cursor: pointer;',
    '}',
    '/* 快捷档那一排：命中的一枚带 ✓ ＋ 走**强调面**（软底 `accent-soft` ＋ 主色字 `accent-text`',
    '   ＋ 主色描边 `accent`）＋ 加粗（**形 ＋ 字 ＋ 色**三样一起给）。口径住',
    '   `docs/base/base-render/选中态与皮肤语言.md` 第三节：有文字的选中面不许写成"实心反白"。 */',
    s('quick') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: center;',
    '  gap: ' + String(DATE_RANGE_GAP_PX) + 'px;',
    '  min-width: 0;',
    '}',
    s('preset') + ' {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  gap: 5px;',
    '  box-sizing: border-box;',
    '  min-width: 72px;',
    '  min-height: ' + touch + ';',
    '  padding: 0 14px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-pill') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-family: inherit;',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '  cursor: pointer;',
    '  touch-action: manipulation;',
    '  transition: transform ' + String(PRESS_MS) + 'ms cubic-bezier(.22,1,.36,1);',
    '}',
    '/* ✓ 一直在标记里，只有按下的那一枚看得见——运行时段只管翻 `aria-pressed`，不用动标记。 */',
    s('mark') + ' {',
    '  display: none;',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1;',
    '}',
    s('preset') + '[aria-pressed="true"] {',
    '  background: ' + skinVar('accent-soft') + ';',
    '  border-color: ' + skinVar('accent') + ';',
    '  color: ' + skinVar('accent-text') + ';',
    '  font-weight: 700;',
    '}',
    s('preset') + '[aria-pressed="true"]' + inBox('mark') + ' {',
    '  display: inline;',
    '}',
    /* 日历那一块（软底块 ＋ 翻月头 ＋ 星期表头 ＋ 42 格的四档形状）住同目录 `style-calendar.ts`：
       一段一段分开长大，汇总在这一次调用里（照 `sheetCss()` 的先例：调用方一行拿全部样式）。
       插在这一行的位置上，是为了**产物逐字节不变**——拆的只是"住哪个文件"。 */
    dateRangeCalendarCss({ prefix: p }),
    '/* 悬停：只包在设备能力查询里（`hover:hover`），且**不是唯一通路**。',
    '   提示只给**不是两端**的格子：那两格是选中面（软底 ＋ 主色字 ＋ 主色描边），',
    '   若悬停时把底换成 `surface`、描边换成 `ink-2`，选中态在悬停那一刻就散了。 */',
    '@media (hover:hover) and (pointer:fine) {',
    '  ' + s('nav') + ':hover:not([disabled]),',
    '  ' + s('day') + ':not(.is-end):hover:not([disabled]) {',
    '    background: ' + skinVar('surface') + ';',
    '    border-color: ' + skinVar('ink-2') + ';',
    '  }',
    '  ' + s('preset') + ':not([aria-pressed="true"]):hover:not([disabled]),',
    '  ' + s('input') + ':hover:not([disabled]) {',
    '    border-color: ' + skinVar('ink-2') + ';',
    '  }',
    '}',
    '/* 真按下：只动 `transform`（80ms 内看得见）。 */',
    s('nav') + ':active:not([disabled]),',
    s('preset') + ':active:not([disabled]),',
    s('day') + ':active:not([disabled]) {',
    '  transform: scale(.98);',
    '}',
    '/* 可见焦点：翻月键、快捷档、日格、起止两格都 ≥2px 描边。 */',
    box + ' :focus-visible {',
    '  outline: 2px solid ' + skinVar('accent') + ';',
    '  outline-offset: 2px;',
    '}',
    '/* 更新中：读数与格子保持原样（宽度锁住），状态字换成「更新中」；光标给 `progress`。 */',
    box + '.is-loading [aria-disabled="true"] {',
    '  cursor: progress;',
    '}',
    '/* 禁用：说不出为什么不能改是不许留的中间档（渲染期就要求给 `disabledReason`）。 */',
    box + ' [disabled],',
    box + '.is-disabled [aria-disabled="true"] {',
    '  background: ' + skinVar('surface-2') + ';',
    '  color: ' + skinVar('ink-3') + ';',
    '  border-color: ' + skinVar('line') + ';',
    '  cursor: not-allowed;',
    '}',
    box + '.is-disabled' + inBox('calendar') + ' {',
    '  opacity: .55;',
    '}',
    '/* 错误说明：写在控件旁边（控件 `aria-describedby` 指向它），**不只染色**。 */',
    s('error') + ' {',
    '  margin: 0;',
    '  padding-left: 8px;',
    '  border-left: 2px solid ' + skinVar('danger') + ';',
    '  color: ' + skinVar('danger') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    box + '.is-invalid' + inBox('input') + ' {',
    '  border-color: ' + skinVar('danger') + ';',
    '}',
    '/* 一句口径：`本周：09-19 到 09-25，共 7 天（含首尾）`（**要读的正文**，走 ink-2）。',
    '   调用方补的那句挂在后头，段间一条发丝线。 */',
    s('caliber') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 4px 8px;',
    '  margin: 0;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    s('sentence') + ' {',
    '  overflow-wrap: anywhere;',
    '}',
    s('extra') + ' {',
    '  padding-left: 8px;',
    '  border-left: 1px solid ' + skinVar('line') + ';',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 窄容器（<' + String(NARROW_PX) + 'px）：起止两格竖排——一格一行，日期串读得全（不压字）。',
    '   判的是**本件自己的宽度**（不用 `@media` 判宽度）。 */',
    '@container (max-width: ' + String(NARROW_PX) + 'px) {',
    '  ' + s('ends') + ' {',
    '    grid-template-columns: minmax(0, 1fr);',
    '  }',
    '}',
    '/* 减动效档：不许有东西卡在半路。 */',
    '@media (prefers-reduced-motion:reduce) {',
    '  ' + s('nav') + ',',
    '  ' + s('preset') + ',',
    '  ' + s('day') + ' {',
    '    transition: none;',
    '  }',
    '}',
  ].join(LF);
}