/** date-range · **样式段**（本件唯一的样式来源）。
 *
 *  纪律（与本层其余件同一份）：只经 `skinVar()` 读皮肤／全部规则 scope 在 `.<prefix>page-ui` 之下／
 *  零 `:root`／零 `!important`／零自定义属性／宽度只由 `@container` 判（`@media` 只判设备能力）。
 *
 *  几何契约（判据钉住）：翻月键、快捷档、起止两格、**每一格天**都不小于 `DATE_RANGE_TOUCH_PX`（44）。
 *  两条**有意偏离原型**的间距口径，写在这里备查：
 *   · 独立的相邻控件（翻月键之间、快捷档之间、起止两格之间）一律留 `DATE_RANGE_GAP_PX`（8px）；
 *   · **日历格之间只留 4px**：7 列 × 44px 是硬约束（44×7 ＋ 6×8 ＋ 内距 ＝ 356px > 390 容器装得下的
 *     日历宽），格与格之间的缝是**矩阵缝**、不是两个独立动作之间的间隔——44 的命中盒优先。
 *
 *  零阴影下立层次：日历块走软底（`surface-2`），区间内的格走纸面（`surface`），两端走实心强调块，
 *  「今天」靠一圈发丝线（`border-color`，盒内 1px，不推版）。
 */
import { skinVar } from '../skin/contract.js';
import {
  DATE_RANGE_GAP_PX,
  DATE_RANGE_TOUCH_PX,
  dateRangeSlot,
  type DateRangeSlot,
} from './attrs.js';

/** 换行（仓库口径：不写字面换行转义）。 */
const LF = String.fromCharCode(10);

/** 窄容器阈值（px）：**本件自己的宽度**。低于它时起止两格竖排（一格一行，日期串读得全）。 */
const NARROW_PX = 420;

/** 日历格之间的矩阵缝（px）：见文件头「有意偏离」那一段。 */
const CELL_GAP_PX = 4;

/** 日历块的宽度上限（px）：一个月有自己的自然宽度（原型给的是 430px）。
 *  不设它，1280 档下一格天会铺成 170px、数字孤零零吊在中间——真机截图里亲眼看到的。 */
const CALENDAR_MAX_PX = 430;
/** 格宽的期望量级（px）：写在这里是为了让"格宽稳在多少"有一个可对账的读数（判据断 ≥44）。 */
const CELL_MIN_W_PX = 44;

/** 按下反馈的时长（ms）：≤80ms。 */
const PRESS_MS = 80;

/** 本组件的样式段。恒返回非空 CSS 文本。 */
export function dateRangeCss(input?: { readonly prefix?: string }): string {
  const p = input !== undefined && input !== null
    && typeof input.prefix === 'string' && input.prefix !== '' ? input.prefix : 'ilife-';
  const root = '.' + p + 'page-ui';
  const box = root + ' .' + p + 'block-date-range';
  const s = (slot: DateRangeSlot): string => root + ' .' + dateRangeSlot(slot, p);
  /** 拼在 `box` **后面**的槽类（不再带 `.<prefix>page-ui`，否则会拼出嵌套的假选择器）。 */
  const inBox = (slot: DateRangeSlot): string => ' .' + dateRangeSlot(slot, p);
  const touch = String(DATE_RANGE_TOUCH_PX) + 'px';

  return [
    '/* date-range（日期范围 · 形态 B「日历缩略」）：起止两格 ＋ 一排快捷档（命中的带 ✓）＋ 一个月的格子，',
    '   底下那句口径点名「当前按 哪一档、从哪天到哪天、共几天」。零阴影下层次靠发丝线与底色块。 */',
    box + ' {',
    '  container-type: inline-size;',
    '  display: grid;',
    '  gap: 10px;',
    '  min-width: 0;',
    '  padding: 12px 14px 14px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-body') + ';',
    '  line-height: 1.5;',
    '}',
    box + ' > * {',
    '  min-width: 0;',
    '}',
    '/* 第一行：名字 ＋ 状态字（`当前按 本周`／`自定义区间`／`还未选`／`更新中`）。 */',
    s('head') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: center;',
    '  justify-content: space-between;',
    '  gap: 4px 12px;',
    '  min-width: 0;',
    '}',
    s('label') + ' {',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 600;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 状态字：一枚带发丝线的签（**字**这一档：换皮换不掉"按的是哪一档"）。 */',
    s('state') + ' {',
    '  box-sizing: border-box;',
    '  max-width: 100%;',
    '  padding: 1px 8px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 700;',
    '  letter-spacing: .02em;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 起止两格：两列（窄容器竖排），与快捷档／日历之间各留 ' + String(DATE_RANGE_GAP_PX) + 'px。 */',
    s('ends') + ' {',
    '  display: grid;',
    '  grid-template-columns: repeat(2, minmax(0, 1fr));',
    '  gap: ' + String(DATE_RANGE_GAP_PX) + 'px;',
    '  min-width: 0;',
    '}',
    s('from') + ',',
    s('to') + ' {',
    '  display: flex;',
    '  align-items: center;',
    '  gap: 6px;',
    '  min-width: 0;',
    '}',
    s('endLabel') + ' {',
    '  flex: none;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '}',
    s('input') + ' {',
    '  box-sizing: border-box;',
    '  flex: 1 1 0;',
    '  min-width: 0;',
    '  height: ' + touch + ';',
    '  padding: 0 10px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-variant-numeric: tabular-nums;',
    '  cursor: pointer;',
    '}',
    '/* 快捷档那一排：命中的一枚带 ✓ ＋ 实心反白 ＋ 加粗（**形 ＋ 字 ＋ 色**三样一起给）。 */',
    s('quick') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: center;',
    '  gap: ' + String(DATE_RANGE_GAP_PX) + 'px;',
    '  min-width: 0;',
    '}',
    s('preset') + ' {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  gap: 5px;',
    '  box-sizing: border-box;',
    '  min-width: 72px;',
    '  min-height: ' + touch + ';',
    '  padding: 0 14px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-pill') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-family: inherit;',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '  cursor: pointer;',
    '  touch-action: manipulation;',
    '  transition: transform ' + String(PRESS_MS) + 'ms cubic-bezier(.22,1,.36,1);',
    '}',
    '/* ✓ 一直在标记里，只有按下的那一枚看得见——运行时段只管翻 `aria-pressed`，不用动标记。 */',
    s('mark') + ' {',
    '  display: none;',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1;',
    '}',
    s('preset') + '[aria-pressed="true"] {',
    '  background: ' + skinVar('accent') + ';',
    '  border-color: ' + skinVar('accent') + ';',
    '  color: ' + skinVar('accent-ink') + ';',
    '  font-weight: 700;',
    '}',
    s('preset') + '[aria-pressed="true"]' + inBox('mark') + ' {',
    '  display: inline;',
    '}',
    '/* 日历块：软底块 ＋ 发丝线（零阴影下用它立边界）。',
    '   **宽度上限 ' + String(CALENDAR_MAX_PX) + 'px**：一个月有自己的自然宽度——1000px 宽的格子里',
    '   一格天铺成 170px、数字孤零零吊在中间，读起来不像日历（真机 1280 档亲眼看过才发现）。',
    '   超过上限的宽度留在块外（其余几行照常占满），格宽稳在 ' + String(CELL_MIN_W_PX) + 'px 上下。 */',
    s('calendar') + ' {',
    '  display: grid;',
    '  gap: ' + String(DATE_RANGE_GAP_PX) + 'px;',
    '  min-width: 0;',
    '  max-width: ' + String(CALENDAR_MAX_PX) + 'px;',
    '  padding: 10px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('surface-2') + ';',
    '}',
    s('calHead') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: center;',
    '  gap: ' + String(DATE_RANGE_GAP_PX) + 'px;',
    '  min-width: 0;',
    '}',
    s('nav') + ' {',
    '  flex: none;',
    '  display: inline-flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  box-sizing: border-box;',
    '  width: ' + touch + ';',
    '  min-width: ' + touch + ';',
    '  height: ' + touch + ';',
    '  padding: 0;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: inherit;',
    '  font-size: ' + skinVar('fs-h3') + ';',
    '  font-weight: 700;',
    '  line-height: 1;',
    '  cursor: pointer;',
    '  touch-action: manipulation;',
    '  transition: transform ' + String(PRESS_MS) + 'ms cubic-bezier(.22,1,.36,1);',
    '}',
    s('month') + ' {',
    '  flex: 1 1 auto;',
    '  min-width: 0;',
    '  margin-left: 2px;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: ' + skinVar('fs-h3') + ';',
    '  font-weight: 700;',
    '  font-variant-numeric: tabular-nums;',
    '  overflow-wrap: anywhere;',
    '}',
    s('week') + ',',
    s('days') + ' {',
    '  display: grid;',
    '  grid-template-columns: repeat(7, minmax(0, 1fr));',
    '  gap: ' + String(CELL_GAP_PX) + 'px;',
    '  min-width: 0;',
    '}',
    s('week') + ' span {',
    '  padding: 2px 0;',
    '  text-align: center;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '}',
    '/* 每一格天：命中盒 ≥44×44（矩阵缝 4px，见文件头）。',
    '   四档形状：区间内＝纸面块，两端＝实心强调块，相邻月＝弱字，今天＝一圈发丝线。 */',
    s('day') + ' {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  box-sizing: border-box;',
    '  min-width: 0;',
    '  min-height: ' + touch + ';',
    '  padding: 0;',
    '  border: 1px solid transparent;',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: transparent;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-variant-numeric: tabular-nums;',
    '  cursor: pointer;',
    '  touch-action: manipulation;',
    '  transition: transform ' + String(PRESS_MS) + 'ms cubic-bezier(.22,1,.36,1);',
    '}',
    s('day') + '.is-in {',
    '  background: ' + skinVar('surface') + ';',
    '}',
    s('day') + '.is-end {',
    '  background: ' + skinVar('accent') + ';',
    '  border-color: ' + skinVar('accent') + ';',
    '  color: ' + skinVar('accent-ink') + ';',
    '  font-weight: 700;',
    '}',
    s('day') + '.is-adj {',
    '  color: ' + skinVar('ink-3') + ';',
    '}',
    s('day') + '.is-today {',
    '  border-color: ' + skinVar('ink-2') + ';',
    '}',
    '/* 悬停：只包在设备能力查询里（`hover:hover`），且**不是唯一通路**。 */',
    '@media (hover:hover) and (pointer:fine) {',
    '  ' + s('nav') + ':hover:not([disabled]),',
    '  ' + s('day') + ':hover:not([disabled]) {',
    '    background: ' + skinVar('surface') + ';',
    '    border-color: ' + skinVar('ink-2') + ';',
    '  }',
    '  ' + s('preset') + ':hover:not([disabled]),',
    '  ' + s('input') + ':hover:not([disabled]) {',
    '    border-color: ' + skinVar('ink-2') + ';',
    '  }',
    '}',
    '/* 真按下：只动 `transform`（80ms 内看得见）。 */',
    s('nav') + ':active:not([disabled]),',
    s('preset') + ':active:not([disabled]),',
    s('day') + ':active:not([disabled]) {',
    '  transform: scale(.98);',
    '}',
    '/* 可见焦点：翻月键、快捷档、日格、起止两格都 ≥2px 描边。 */',
    box + ' :focus-visible {',
    '  outline: 2px solid ' + skinVar('accent') + ';',
    '  outline-offset: 2px;',
    '}',
    '/* 更新中：读数与格子保持原样（宽度锁住），状态字换成「更新中」；光标给 `progress`。 */',
    box + '.is-loading [aria-disabled="true"] {',
    '  cursor: progress;',
    '}',
    '/* 禁用：说不出为什么不能改是不许留的中间档（渲染期就要求给 `disabledReason`）。 */',
    box + ' [disabled],',
    box + '.is-disabled [aria-disabled="true"] {',
    '  background: ' + skinVar('surface-2') + ';',
    '  color: ' + skinVar('ink-3') + ';',
    '  border-color: ' + skinVar('line') + ';',
    '  cursor: not-allowed;',
    '}',
    box + '.is-disabled' + inBox('calendar') + ' {',
    '  opacity: .55;',
    '}',
    '/* 错误说明：写在控件旁边（控件 `aria-describedby` 指向它），**不只染色**。 */',
    s('error') + ' {',
    '  margin: 0;',
    '  padding-left: 8px;',
    '  border-left: 2px solid ' + skinVar('danger') + ';',
    '  color: ' + skinVar('danger') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    box + '.is-invalid' + inBox('input') + ' {',
    '  border-color: ' + skinVar('danger') + ';',
    '}',
    '/* 一句口径：`本周：09-19 到 09-25，共 7 天（含首尾）`（**要读的正文**，走 ink-2）。',
    '   调用方补的那句挂在后头，段间一条发丝线。 */',
    s('caliber') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 4px 8px;',
    '  margin: 0;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    s('sentence') + ' {',
    '  overflow-wrap: anywhere;',
    '}',
    s('extra') + ' {',
    '  padding-left: 8px;',
    '  border-left: 1px solid ' + skinVar('line') + ';',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 窄容器（<' + String(NARROW_PX) + 'px）：起止两格竖排——一格一行，日期串读得全（不压字）。',
    '   判的是**本件自己的宽度**（不用 `@media` 判宽度）。 */',
    '@container (max-width: ' + String(NARROW_PX) + 'px) {',
    '  ' + s('ends') + ' {',
    '    grid-template-columns: minmax(0, 1fr);',
    '  }',
    '}',
    '/* 减动效档：不许有东西卡在半路。 */',
    '@media (prefers-reduced-motion:reduce) {',
    '  ' + s('nav') + ',',
    '  ' + s('preset') + ',',
    '  ' + s('day') + ' {',
    '    transition: none;',
    '  }',
    '}',
  ].join(LF);
}