/** sub-list · **样式段**（本件唯一的样式来源）。
 *
 *  纪律（与本层其余件同一份）：
 *   · 只经 `skinVar()` 读皮肤 —— 组件里**不写** `var(--ilife-…)`（兜底链只许住在 `skin/contract.ts`）；
 *   · 全部规则 scope 在 `.<prefix>page-ui` 之下（不开本配方的页零命中）；不写 `:root`／`!important`、不新增 token 名；
 *   · 宽度判**容器**：布局靠内在尺寸 ＋ `minmax(0,1fr)`；媒体查询只判设备能力（`hover`／`prefers-reduced-motion`）。
 *
 *  交互件的那几档（本件唯一的可点元素是折页头 `<summary>`，开合是**浏览器原生**行为）：
 *   · `rest` ／ `:hover`（包在 `@media (hover:hover) and (pointer:fine)` 里，且**不是唯一通路**：
 *     方向标 ＋ `cursor:pointer` ＋ 原生 `<details>` 的键盘行为都在）／`:active`（色阶，60ms）
 *     ／`:focus-visible`（可见焦点；画在框内，因为折页盒 `overflow:hidden` 会裁掉外溢）
 *     ／`empty`（设计过的空态：虚线卡）；
 *   · 折页头**命中区 ≥44px**（`RANGE` 取 48px，判据真机量得出）；
 *   · 语义不只靠色：子项"备好"＝勾（形）＋ 名字转弱（色）＋ 折页头的「N/M 已备」（字）。
 */
import { skinVar } from '../skin/contract.js';
import { subListSlot, type SubListSlot } from './attrs.js';

/** 换行（仓库口径：不写字面换行转义）。 */
const LF = String.fromCharCode(10);

/** 折页头的最小高度（px）：本件唯一的可点元素，命中区不许小于 44（触摸地板）。 */
export const SUB_LIST_HEAD_MIN_HEIGHT_PX = 48;

/** 窄容器阈值（px）：折页头与子项区的内距各收一档，把宽度让给名字与读数。
 *  **这是本件自己的宽度**（`@container` 判的），不是视口宽度。 */
export const SUB_LIST_NARROW_PX = 420;

/** 按下时的色阶过渡（ms）：≤80ms（"按下要立刻有回应"）。 */
export const SUB_LIST_PRESS_MS = 60;

/** 本组件的样式段。恒返回非空 CSS 文本。 */
export function subListCss(input?: { readonly prefix?: string }): string {
  const p = input !== undefined && input !== null
    && typeof input.prefix === 'string' && input.prefix !== '' ? input.prefix : 'ilife-';
  const root = '.' + p + 'page-ui';
  /* 槽位类的**唯一拼法**：scope（`.ilife-page-ui`）＋ 本件类名 —— 一条独立规则的完整选择器。
     要把两个槽拼成**后代选择器**时，后半截用 `c()`（`c()` 不带 scope）：两个 `s()` 拼一起会写出
     `.ilife-page-ui … .ilife-page-ui …`，那条规则永远命中不到。判据断的是"scope 恰好出现一次"。 */
  const s = (slot: SubListSlot): string => root + ' .' + subListSlot(slot, p);
  const c = (slot: SubListSlot): string => '.' + subListSlot(slot, p);

  return [
    '/* sub-list（分组清单 · 形态 A「折叠组＋组级小计＋备货进度」）：一组一枚原生 `<details>`；',
    '   折页头＝方向标／组名＋计数／小计／进度条＋「N/M 已备」。**零脚本**：开合是浏览器原生行为。',
    '   层次不靠阴影与大圆角（小票纸零阴影、大字报刊零圆角）：靠发丝线、字重与深浅阶梯 ⇒ 换皮只换取值。 */',
    root + ' .' + p + 'block-sub-list {',
    '  display: grid;',
    '  gap: 8px;',
    '  min-width: 0;',
    /* 本件是**自己的容器**：下面那条 `@container (max-width: SUB_LIST_NARROW_PX)` 判的是
       **本件宽度**（件会被嵌进侧栏／面板，视口宽 ≠ 件宽）。少了这一行，那条查询会去找**祖先**里
       最近的容器——件里没有、页上也可能没有，于是「窄档收内距」这条规则**永远不生效**（死规则）。 */
    '  container-type: inline-size;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-body') + ';',
    '  line-height: 1.5;',
    '}',
    '/* 头部：标题 ＋ 用途 ＋ 合计（合计顶右缘；容器一窄，三件自己折行，谁也不压谁）。 */',
    s('hd') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 4px 10px;',
    '  min-width: 0;',
    '}',
    s('title') + ' {',
    '  min-width: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font-display') + ';',
    '  font-size: ' + skinVar('fs-h2') + ';',
    '  font-weight: 700;',
    '  line-height: 1.25;',
    '  overflow-wrap: anywhere;',
    '}',
    s('use') + ' {',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '  overflow-wrap: anywhere;',
    '}',
    s('sum') + ' {',
    '  display: flex;',
    '  align-items: baseline;',
    '  gap: 6px;',
    '  margin-left: auto;',
    '  min-width: 0;',
    '}',
    s('sum-label') + ' {',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '}',
    s('sum-value') + ' {',
    '  min-width: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: ' + skinVar('fs-h3') + ';',
    '  font-weight: 700;',
    '  font-variant-numeric: tabular-nums;',
    '  overflow-wrap: anywhere;',
    '}',
    s('list') + ' {',
    '  display: grid;',
    '  gap: 6px;',
    '  min-width: 0;',
    '}',
    '/* 一个分组：卡内的一张折页（发丝边 ＋ 皮肤圆角）；`overflow:hidden` 让折页头的底色不越出圆角。 */',
    s('g') + ' {',
    '  min-width: 0;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  overflow: hidden;',
    '}',
    '/* 折页头（`<summary>`）：**本件唯一的可点元素** —— 命中区 ≥44px，光标是手，键盘原生可开合。',
    '   两行网格：第一行＝组名＋计数／小计，第二行＝进度条／进度读数。 */',
    s('head') + ' {',
    '  box-sizing: border-box;',
    '  display: grid;',
    '  grid-template-columns: 16px minmax(0, 1fr) auto;',
    '  grid-template-rows: auto auto;',
    '  gap: 3px 8px;',
    '  align-items: center;',
    '  min-height: ' + String(SUB_LIST_HEAD_MIN_HEIGHT_PX) + 'px;',
    '  padding: 8px 14px;',
    '  cursor: pointer;',
    '  list-style: none;',
    '  transition: background-color ' + String(SUB_LIST_PRESS_MS) + 'ms linear;',
    '}',
    '/* 原生三角标（Safari／Chrome 各一枚）由样式关掉，方向标改画在左端那一枚上。 */',
    s('head') + '::-webkit-details-marker {',
    '  display: none;',
    '}',
    s('ar') + ' {',
    '  grid-row: 1 / 3;',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: 11px;',
    '  font-style: normal;',
    '  line-height: 1;',
    '}',
    '/* 方向标：收起 `▸`／展开 `▾`（**形状通路**：不看颜色也知道这一组开着还是关着）。 */',
    s('ar') + '::before {',
    '  content: "\\25B8";',
    '}',
    s('g') + '[open] ' + c('ar') + '::before {',
    '  content: "\\25BE";',
    '}',
    s('h') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 6px;',
    '  min-width: 0;',
    '}',
    s('label') + ' {',
    '  min-width: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font-display') + ';',
    '  font-size: ' + skinVar('fs-h3') + ';',
    '  font-weight: 700;',
    '  line-height: 1.3;',
    '  overflow-wrap: anywhere;',
    '}',
    s('count') + ' {',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '  font-variant-numeric: tabular-nums;',
    '  text-decoration: none;',
    '  white-space: nowrap;',
    '}',
    s('sub') + ' {',
    '  justify-self: end;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 700;',
    '  font-variant-numeric: tabular-nums;',
    '  white-space: nowrap;',
    '}',
    '/* 进度条：一条轨 ＋ 一段填充（长度＝已备占比）；它是**非文本**形状，读数另有「N/M 已备」。 */',
    s('pg') + ' {',
    '  grid-column: 2;',
    '  display: block;',
    '  min-width: 0;',
    '  height: 5px;',
    '  border-radius: ' + skinVar('radius-pill') + ';',
    '  background: ' + skinVar('line') + ';',
    '  overflow: hidden;',
    '}',
    s('pg-fill') + ' {',
    '  display: block;',
    '  height: 100%;',
    '  background: ' + skinVar('accent') + ';',
    '}',
    s('st') + ' {',
    '  justify-self: end;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: 10.5px;',
    '  font-weight: 600;',
    '  font-variant-numeric: tabular-nums;',
    '  white-space: nowrap;',
    '}',
    '/* 子项区：勾／名／数量／值四栏；名字长了自己折行，数量与值 `nowrap`（不许截断）。 */',
    s('body') + ' {',
    '  display: grid;',
    '  gap: 0;',
    '  padding: 0 14px 12px;',
    '  min-width: 0;',
    '}',
    s('r') + ' {',
    '  display: grid;',
    '  grid-template-columns: 16px minmax(0, 1fr) auto auto;',
    '  gap: 8px;',
    '  align-items: center;',
    '  min-width: 0;',
    '  padding: 6px 0;',
    '  border-top: 1px solid ' + skinVar('line') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '}',
    '/* 勾：**形状通路**（有没有备好不只靠颜色）；空的那一枚留同样大的框，行高不跳。 */',
    s('ck') + ' {',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  box-sizing: border-box;',
    '  width: 16px;',
    '  height: 16px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  color: ' + skinVar('ok') + ';',
    '  font-size: 11px;',
    '  font-style: normal;',
    '  line-height: 1;',
    '}',
    s('r') + '.is-done ' + c('ck') + ' {',
    '  border-color: ' + skinVar('ok') + ';',
    '  background: ' + skinVar('ok-soft') + ';',
    '}',
    s('n') + ' {',
    '  min-width: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 备好的那一项：名字转弱（色）——与勾（形）、折页头的读数（字）一起，三路说同一件事。 */',
    s('r') + '.is-done ' + c('n') + ' {',
    '  color: ' + skinVar('ink-2') + ';',
    '}',
    s('q') + ' {',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-variant-numeric: tabular-nums;',
    '  white-space: nowrap;',
    '}',
    s('v') + ' {',
    '  min-width: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 600;',
    '  font-variant-numeric: tabular-nums;',
    '  white-space: nowrap;',
    '}',
    '/* 设计过的空态：虚线卡 ＋ 一句人话（不是"页面裂开一角"）。 */',
    s('empty') + ' {',
    '  margin: 0;',
    '  min-width: 0;',
    '  padding: 14px;',
    '  border: 1px dashed ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    s('note') + ' {',
    '  margin: 0;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 焦点：画在框内（折页盒 `overflow:hidden`，外溢的环会被裁掉）。',
    '   本件只有折页头可聚焦，这条同时也是其余可聚焦元素的地板（调用方塞了链接也看得见焦点）。 */',
    root + ' .' + p + 'block-sub-list :focus-visible {',
    '  outline: 2px solid ' + skinVar('accent') + ';',
    '  outline-offset: -2px;',
    '}',
    '/* 悬停与按下：**只在真有指针的机器上**给悬停底色（触屏上"悬停"是个假状态）；',
    '   按下给一档更实的色——两者都不是唯一通路（方向标与原生开合一直在）。 */',
    '@media (hover: hover) and (pointer: fine) {',
    '  ' + s('head') + ':hover {',
    '    background: ' + skinVar('surface-2') + ';',
    '  }',
    '}',
    s('head') + ':active {',
    '  background: ' + skinVar('accent-soft') + ';',
    '}',
    '/* 减动效：过渡关掉（按下仍是立刻变色，不会有东西卡在半路）。 */',
    '@media (prefers-reduced-motion: reduce) {',
    '  ' + s('head') + ' {',
    '    transition: none;',
    '  }',
    '}',
    '/* 窄容器（<' + String(SUB_LIST_NARROW_PX) + 'px）：折页头与子项区各收一档内距',
    '   （判的是**本件自己的宽度**：本件会被嵌进侧栏／面板／卡片，视口宽 ≠ 组件宽）。 */',
    '@container (max-width: ' + String(SUB_LIST_NARROW_PX) + 'px) {',
    '  ' + s('head') + ' {',
    '    padding: 8px 10px;',
    '    gap: 3px 6px;',
    '  }',
    '  ' + s('body') + ' {',
    '    padding: 0 10px 10px;',
    '  }',
    '  ' + s('r') + ' {',
    '    gap: 6px;',
    '  }',
    '}',
  ].join(LF);
}
