/** invoice-lines · **样式段**（本件唯一的样式来源）。**重做件**：要从「像普通账目行」里走出来。
 *
 *  四条重做口径（`重做设计口径.md` §0）逐条落在这一段里：
 *   ① 该件没有"占位物"；
 *   ② **状态除色之外还有第二样**：减项行带 **`−` 号 ＋ 缩进 ＋ 左竖线**，加项行带 **`＋` 号 ＋ 左竖线**，
 *      实付行带 **重线 ＋ 加粗放大** —— 换皮换到墨黑强调，三类行照样分得开；
 *   ③ **层次不靠投影与圆角**：链靠**逐级缩进 ＋ 发丝线**，收口靠**一条重线**，条靠实色块；
 *   ④ **骨架对得上这类数据**：这是一笔钱的**减法链**（不是平铺读数），所以走有序表 ＋ 收口行。
 *
 *  纪律：只经 `skinVar()` 读皮肤；scope 在 `.<prefix>page-ui` 之下；零 `:root`／`!important`；
 *  宽度只许容器判（`@container`），媒体查询只判设备能力（本件没用到）。
 */
import { skinVar } from '../skin/contract.js';
import {
  INVOICE_LINES_SEGMENT_MIN_PCT,
  INVOICE_LINES_TOTAL_SCALE,
  invoiceLinesSlot,
  type InvoiceLinesSlot,
} from './attrs.js';

/** 换行（仓库口径：不写字面换行转义）。 */
const LF = String.fromCharCode(10);

/** 减项／加项那一级的缩进（px）：**链**就靠这个逐级退让读出来。 */
export const INVOICE_LINES_INDENT_PX = 14;
/** 收口那条重线的宽度（px）。 */
export const INVOICE_LINES_RULE_PX = 2;
/** 图例换列的容器阈值（px）：**容器宽 ≤ 它一列，> 它两列**。
 *  判的是**本件自己的宽度**（`@container`），不是视口宽度；这一档写成**窄档的上界**（`max-width`）、
 *  两列当缺省——窄档才是要**覆盖**的那一档。 */
export const INVOICE_LINES_LEGEND_MAX_PX = 620;

/** 本组件的样式段。恒返回非空 CSS 文本。 */
export function invoiceLinesCss(input?: { readonly prefix?: string }): string {
  const p = input !== undefined && input !== null
    && typeof input.prefix === 'string' && input.prefix !== '' ? input.prefix : 'ilife-';
  const root = '.' + p + 'page-ui';
  const box = root + ' .' + p + 'block-invoice-lines';
  const slotSel = (s: InvoiceLinesSlot): string => '.' + invoiceLinesSlot(s, p);
  const s = (slot: InvoiceLinesSlot): string => root + ' ' + slotSel(slot);
  const seg = (kind: string): string => s('seg') + '.is-' + kind;

  return [
    '/* invoice-lines（金额分解 · 形态 A「逐行分解 ＋ 收口」／形态 D「瀑布条」）：',
    '   每行读得出「为什么」，从原价到实付读成一条链，末尾实付加粗放大、均摊写进副语。',
    '   **重做件**：原型读起来像一摞普通账目行；零阴影、零圆角下靠缩进、发丝线与重线分家。 */',
    box + ' {',
    '  container-type: inline-size;',
    '  display: grid;',
    '  gap: 10px;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-body') + ';',
    '  line-height: 1.5;',
    '}',
    '/* 链：行与行一条发丝线；**减项／加项逐级缩进**，读者一眼看出这一笔从哪儿减下去。 */',
    s('list') + ' {',
    '  display: grid;',
    '  gap: 0;',
    '  margin: 0;',
    '  padding: 0;',
    '  min-width: 0;',
    '  list-style: none;',
    '}',
    s('line') + ' {',
    '  display: grid;',
    '  grid-template-columns: minmax(0, 1fr) auto;',
    '  gap: 2px 12px;',
    '  min-width: 0;',
    '  padding: 8px 0;',
    '  border-top: 1px solid ' + skinVar('line') + ';',
    '  align-items: baseline;',
    '}',
    s('line') + ':first-child {',
    '  border-top: 0;',
    '}',
    '/* 减项与加项：缩进 ＋ 一道左竖线（**缩进本身**就是「这一笔挂在上面那一行下面」的形状）。 */',
    s('line') + '.is-cut, ' + s('line') + '.is-add {',
    '  padding-left: ' + String(INVOICE_LINES_INDENT_PX) + 'px;',
    '  border-left: 1px solid ' + skinVar('line') + ';',
    '}',
    '/* 实付：一条**重线**收口（不是投影、不是圆角），字号加倍 —— 收口那一行是全件的读数。 */',
    s('line') + '.is-total {',
    '  margin-top: 6px;',
    '  padding-top: 12px;',
    '  border-top: ' + String(INVOICE_LINES_RULE_PX) + 'px solid ' + skinVar('ink') + ';',
    '  align-items: end;',
    '}',
    s('label') + ' {',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  overflow-wrap: anywhere;',
    '}',
    s('line') + '.is-base ' + slotSel('label') + ' { color: ' + skinVar('ink') + '; }',
    s('line') + '.is-total ' + slotSel('label') + ' {',
    '  color: ' + skinVar('ink') + ';',
    '  font-size: ' + skinVar('fs-h3') + ';',
    '  font-weight: 700;',
    '}',
    '/* 金额：等宽数字（同一条链上下对齐）；实付那一行加粗放大。 */',
    s('amount') + ' {',
    '  justify-self: end;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 700;',
    '  font-variant-numeric: tabular-nums;',
    '  overflow-wrap: anywhere;',
    '}',
    s('line') + '.is-total ' + slotSel('amount') + ' {',
    '  font-size: calc(' + skinVar('fs-h3') + ' * ' + String(INVOICE_LINES_TOTAL_SCALE) + ');',
    '  line-height: 1.1;',
    '}',
    '/* 减项走 ok 档（省下来了）；加项走 warn 档（多花出去了）——**色只是第二样**：',
    '   记号（−／＋）、缩进与那两枚「为什么」标签都在。 */',
    s('line') + '.is-cut ' + slotSel('amount') + ' { color: ' + skinVar('ok') + '; }',
    s('line') + '.is-add ' + slotSel('amount') + ' { color: ' + skinVar('warn') + '; }',
    '/* 「为什么」：满行独占，左端一枚标签把原因点出来。 */',
    s('why') + ' {',
    '  grid-column: 1 / 3;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    s('why') + ' > b {',
    '  margin-right: 6px;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-weight: 700;',
    '}',
    s('why') + ' > span { margin-right: 10px; }',
    '/* 均摊那句补充（除不尽时的那几分钱去哪了）：缩进 ＋ 一道更细的竖线，不跟正文抢层次。 */',
    s('share') + ' {',
    '  grid-column: 1 / 3;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 瀑布条：段宽与金额等比（宽度落内联 style，比例由本件算）。 */',
    s('bar') + ' {',
    '  display: flex;',
    '  min-width: 0;',
    '  height: 40px;',
    '  box-sizing: border-box;',
    '  border: 1px solid ' + skinVar('edge') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('surface-2') + ';',
    '  overflow: hidden;',
    '}',
    s('seg') + ' {',
    '  display: flex;',
    '  flex-direction: column;',
    '  align-items: center;',
    '  justify-content: center;',
    '  min-width: 0;',
    '  overflow: hidden;',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 700;',
    '  font-variant-numeric: tabular-nums;',
    '  box-sizing: border-box;',
    '}',
    seg('total') + ' {',
    '  background: ' + skinVar('accent') + ';',
    '  color: ' + skinVar('accent-ink') + ';',
    '}',
    '/* 减项段：底色从 token **算出来**（`ok` 掺进 `surface`）——`ok-soft` 在报刊／中性两套下接近白，',
    '   段与条底分不开，「省了多少」在形状上就看不见了。 */',
    seg('cut') + ' {',
    '  background: color-mix(in srgb, ' + skinVar('ok') + ' 32%, ' + skinVar('surface') + ');',
    '  color: ' + skinVar('ok') + ';',
    '  border-left: 2px solid ' + skinVar('surface') + ';',
    '}',
    s('seg') + ' > b { font-weight: 700; }',
    s('seg') + ' > i {',
    '  font-style: normal;',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '}',
    '/* 条下面那行口径：说清条长的满分是什么（**判据断言这一句在**）。 */',
    s('foot') + ' {',
    '  margin: 0;',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 图例：条上写不下的金额，在这里**逐行全出**（关键语义不许被段的宽度截掉）。',
    '   缺省（宽档）两列；窄档那一条在文末把它**覆盖**成一列。 */',
    s('legend') + ' {',
    '  display: grid;',
    '  grid-template-columns: repeat(2, minmax(0, 1fr));',
    '  gap: 0 20px;',
    '  margin: 0;',
    '  padding: 0;',
    '  min-width: 0;',
    '  list-style: none;',
    '}',
    s('legend-row') + ' {',
    '  display: grid;',
    '  grid-template-columns: auto minmax(0, 1fr) auto;',
    '  gap: 2px 10px;',
    '  min-width: 0;',
    '  padding: 7px 0;',
    '  border-top: 1px solid ' + skinVar('line') + ';',
    '  align-items: baseline;',
    '}',
    s('legend-swatch') + ' {',
    '  align-self: center;',
    '  display: block;',
    '  width: 11px;',
    '  height: 11px;',
    '  box-sizing: border-box;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: 2px;',
    '}',
    s('legend-swatch') + '.is-base { background: ' + skinVar('surface-2') + '; }',
    s('legend-swatch') + '.is-cut { background: color-mix(in srgb, ' + skinVar('ok') + ' 32%, ' + skinVar('surface') + '); }',
    s('legend-swatch') + '.is-add { background: ' + skinVar('warn-soft') + '; }',
    s('legend-swatch') + '.is-total { background: ' + skinVar('accent') + '; }',
    s('legend-label') + ' {',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  overflow-wrap: anywhere;',
    '}',
    s('legend-amount') + ' {',
    '  justify-self: end;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 700;',
    '  font-variant-numeric: tabular-nums;',
    '  overflow-wrap: anywhere;',
    '}',
    s('legend-row') + '.is-total ' + slotSel('legend-amount') + ' {',
    '  font-size: calc(' + skinVar('fs-sm') + ' * ' + String(INVOICE_LINES_TOTAL_SCALE) + ');',
    '}',
    s('legend-row') + '.is-cut ' + slotSel('legend-amount') + ' { color: ' + skinVar('ok') + '; }',
    s('legend-row') + '.is-add ' + slotSel('legend-amount') + ' { color: ' + skinVar('warn') + '; }',
    '/* 口径行：这一笔怎么拆的（逐段一枚 span，段间一条发丝线）。 */',
    s('note') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 4px 8px;',
    '  margin: 0;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1.7;',
    '  overflow-wrap: anywhere;',
    '}',
    s('note') + ' > span {',
    '  padding-left: 8px;',
    '  border-left: 1px solid ' + skinVar('line') + ';',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 焦点地板：本件不带可点元素；调用方若把某一行包成链接，焦点必须看得见。 */',
    box + ' :focus-visible {',
    '  outline: 2px solid ' + skinVar('accent') + ';',
    '  outline-offset: 2px;',
    '}',
    '/* 窄容器（≤' + String(INVOICE_LINES_LEGEND_MAX_PX) + 'px）：图例两列**覆盖**成一列',
    '   （判的是本件自己的宽度，不是视口宽度）。 */',
    '@container (max-width: ' + String(INVOICE_LINES_LEGEND_MAX_PX) + 'px) {',
    '  ' + s('legend') + ' {',
    '    grid-template-columns: minmax(0, 1fr);',
    '  }',
    '}',
    '/* 段宽下限常量（判据从源码读它）：窄于 ' + String(INVOICE_LINES_SEGMENT_MIN_PCT)
      + '% 的段不写字，金额改在图例里逐行出。 */',
  ].join(LF);
}
