/** wizard-shell · **样式段**（本件唯一的样式来源；答题面那两块在 `style-answer.ts`，由这里汇总）。
 *
 *  纪律（与本节其余件同一份）：
 *   · 只经 `skinVar()` 读皮肤——组件里**不写**手写的 CSS 变量（兜底链只许住在 `skin/contract.ts`）；
 *   · 全部规则 scope 在 `.<prefix>page-ui` 之下（不开本配方的页零命中）；不写 `:root`／`!important`、不新增 token 名；
 *   · **宽度只许容器判**：本件自己是容器（`container-type: inline-size`），折行靠内在尺寸 ＋ `flex-wrap`，
 *     窄档调整走 `@container`；`@media` 只判设备能力（`hover`／`pointer`／`prefers-reduced-motion`），不判宽度。
 *
 *  几何契约（判据钉住）：
 *   · 三枚键 ≥ `WIZARD_SHELL_MIN_TARGET_PX`、相邻触控目标之间恒留 `WIZARD_SHELL_TARGET_GAP_PX`
 *     ——**这是手指的地板，不是桌面福利**；答法那两块的地板写在 `style-answer.ts`；
 *   · 进度那一条是无文字的条 ⇒ 皮肤语汇里只有 `accent` 一档实底：**走过**与**正走**用「形」分辨
 *     （当前那格高一档 ＋ `aria-current="step"`），不偷偷借 `ink` 当第二档颜色（那是"拿字色当面"）；
 *   · 尺寸事实（宽高阈值）只有一处定义，住 `attrs.ts`，两份样式段都从那儿读。
 */
import { skinVar } from '../skin/contract.js';
import {
  WIZARD_SHELL_BT_PRIMARY,
  WIZARD_SHELL_LABEL_LOADING,
  WIZARD_SHELL_LOADING_ATTR,
  WIZARD_SHELL_MIN_TARGET_PX,
  WIZARD_SHELL_NARROW_PX,
  WIZARD_SHELL_PAD_PX,
  WIZARD_SHELL_SEG_DONE,
  WIZARD_SHELL_SEG_NOW,
  WIZARD_SHELL_SEG_NOW_PX,
  WIZARD_SHELL_SEG_PX,
  WIZARD_SHELL_TARGET_GAP_PX,
  wizardShellSlot,
  type WizardShellSlot,
} from './attrs.js';
import { wizardShellAnswersCss } from './style-answer.js';

/** 换行（仓库口径：不写字面换行转义）。 */
const LF = String.fromCharCode(10);

/** 本组件的样式段。恒返回非空 CSS 文本。 */
export function wizardShellCss(input?: { readonly prefix?: string }): string {
  const p = input !== undefined && input !== null
    && typeof input.prefix === 'string' && input.prefix !== '' ? input.prefix : 'ilife-';
  const root = '.' + p + 'page-ui';
  const box = root + ' .' + p + 'block-wizard-shell';
  const s = (slot: WizardShellSlot): string => root + ' .' + wizardShellSlot(slot, p);
  /** **裸类名**：只用在复合选择器的中段（`X > .槽`、`X:has(…) > .槽`）。
   *  `s()` 自带作用域前缀，只许当选择器的**开头**——把它接在 `>` 后面会拼出
   *  `.… > .ilife-page-ui .槽` 这种**永远不命中**的死规则（语法合法、编译不报错，只有放大看才发现没生效）。 */
  const c = (slot: WizardShellSlot): string => '.' + wizardShellSlot(slot, p);
  const bt = s('bt');
  const busy = box + '[' + WIZARD_SHELL_LOADING_ATTR + '="1"]';

  return [
    '/* wizard-shell（分步录入壳 · 形态 B「一问一屏」）：一条细进度 → 第 n / N 问 → 大字问题 → 这一问的答法 → 脚行三枚键。',
    '   层次不靠阴影与大圆角（小票纸零阴影、大字报刊零直角）：靠发丝线、字重与尺度差 ⇒ 换皮只换取值。 */',
    box + ' {',
    /* 宽度判据的落点：本件是**自己的容器**——嵌进侧栏／面板／卡片时照样按自己的宽度折行。 */
    '  container-type: inline-size;',
    '  display: block;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-body') + ';',
    '  line-height: 1.5;',
    '}',
    '/* 这一屏 = 一张纸：发丝线 ＋ 主圆角 ＋ 纸面（零投影档下也立得住）。 */',
    s('now') + ' {',
    '  display: grid;',
    '  min-width: 0;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius') + ';',
    '  background: ' + skinVar('surface') + ';',
    '}',
    '/* 细进度：N 格等分，格间恒留一道缝（缝是形的一部分，不靠底色差）。 */',
    s('prog') + ' {',
    '  display: flex;',
    '  gap: 4px;',
    '  min-width: 0;',
    '  padding: 14px ' + String(WIZARD_SHELL_PAD_PX) + 'px 0;',
    '}',
    s('seg') + ' {',
    '  flex: 1 1 0;',
    '  min-width: 0;',
    '  height: ' + String(WIZARD_SHELL_SEG_PX) + 'px;',
    '  border-radius: ' + skinVar('radius-pill') + ';',
    '  background: ' + skinVar('line') + ';',
    '}',
    '/* 走过的那几格：`accent` 实底（无文字的条只有这一档）。 */',
    s('seg') + '.' + WIZARD_SHELL_SEG_DONE + ' {',
    '  background: ' + skinVar('accent') + ';',
    '}',
    '/* 正走那一格：同样是 `accent` 实底，靠**高一档的形**分辨（外加读数行那枚「第 n / N 问」这个字）。 */',
    s('seg') + '.' + WIZARD_SHELL_SEG_NOW + ' {',
    '  height: ' + String(WIZARD_SHELL_SEG_NOW_PX) + 'px;',
    '  background: ' + skinVar('accent') + ';',
    '}',
    '/* 读数行：「第 n / N 问」＋次段。次段是**按不动的"上一问"为什么按不动**那句话的落点（按钮 `aria-describedby` 指它）。 */',
    s('step') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 4px 10px;',
    '  margin: 0;',
    '  min-width: 0;',
    '  padding: 12px ' + String(WIZARD_SHELL_PAD_PX) + 'px 0;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 700;',
    '  letter-spacing: .04em;',
    '  overflow-wrap: anywhere;',
    '}',
    s('step') + ' > b {',
    '  flex: none;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-variant-numeric: tabular-nums;',
    '}',
    s('aside') + ' {',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-weight: 400;',
    '  letter-spacing: 0;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 大字问题：这一屏唯一的大字（`fs-h1`；四套皮肤下都 ≥ 正文的 1.8 倍）。',
    '   **不许 `…` 截断**：长了换行（它是"一问一屏"的识别特征，压字等于把这一档的骨架丢了）。 */',
    s('q') + ' {',
    '  margin: 0;',
    '  min-width: 0;',
    '  padding: 8px ' + String(WIZARD_SHELL_PAD_PX) + 'px 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font-display') + ';',
    '  font-size: ' + skinVar('fs-h1') + ';',
    '  font-weight: 700;',
    '  line-height: 1.28;',
    '  letter-spacing: -.01em;',
    '  overflow-wrap: anywhere;',
    '}',
    s('why') + ' {',
    '  margin: 0;',
    '  min-width: 0;',
    '  padding: 8px ' + String(WIZARD_SHELL_PAD_PX) + 'px 0;',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1.65;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 答题区：三种答法（选项／填空／确认）各占同一块地，互不叠——三块自己的规则在 `style-answer.ts`。 */',
    s('answer') + ' {',
    '  display: grid;',
    '  gap: 10px;',
    '  min-width: 0;',
    '  padding: 14px ' + String(WIZARD_SHELL_PAD_PX) + 'px 0;',
    '}',
    wizardShellAnswersCss({ prefix: p }),
    '/* 错态／禁用原因：写在控件旁边（不是只染色），并带一枚记号字。 */',
    s('error') + ' {',
    '  display: flex;',
    '  gap: 6px;',
    '  margin: 0;',
    '  min-width: 0;',
    '  padding: 10px ' + String(WIZARD_SHELL_PAD_PX) + 'px 0;',
    '  color: ' + skinVar('danger') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 600;',
    '  overflow-wrap: anywhere;',
    '}',
    s('error') + '::before {',
    '  content: "\\26A0";',
    '  flex: none;',
    '}',
    '/* 脚行：提示句（左）＋ 三枚键（右）。整幅铺底，圆角由它自己收（不靠 `overflow: hidden`）。 */',
    s('foot') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: center;',
    '  gap: ' + String(WIZARD_SHELL_TARGET_GAP_PX) + 'px;',
    '  margin-top: 14px;',
    '  padding: 14px ' + String(WIZARD_SHELL_PAD_PX) + 'px;',
    '  border-top: 1px solid ' + skinVar('line') + ';',
    '  border-radius: 0 0 ' + skinVar('radius') + ' ' + skinVar('radius') + ';',
    '  background: ' + skinVar('surface-2') + ';',
    '}',
    s('hint') + ' {',
    '  flex: 1 1 180px;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '  line-height: 1.5;',
    '  overflow-wrap: anywhere;',
    '}',
    s('acts') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  gap: ' + String(WIZARD_SHELL_TARGET_GAP_PX) + 'px;',
    '  margin-left: auto;',
    '  min-width: 0;',
    '}',
    '/* 一枚键：命中盒 ≥44×44。**不写 `white-space: nowrap`**——长了要换行（宽了顶出屏比换行难看）。 */',
    bt + ' {',
    '  display: inline-grid;',
    '  grid-template-columns: auto;',
    '  place-items: center;',
    '  box-sizing: border-box;',
    '  min-height: ' + String(WIZARD_SHELL_MIN_TARGET_PX) + 'px;',
    '  min-width: ' + String(WIZARD_SHELL_MIN_TARGET_PX) + 'px;',
    '  padding: 10px 16px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-pill') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 600;',
    '  line-height: 1.2;',
    '  cursor: pointer;',
    '  transition: transform 80ms cubic-bezier(.22, 1, .36, 1);',
    '}',
    '/* 键上那枚字：**两枚（常态那枚 ＋ 加载态那枚）叠在同一个格里** ⇒ 主键的宽度由两枚字里更宽的那枚',
    '   说了算，换字时盒模型一动不动（不跳版）；该藏的那枚走 `visibility: hidden`（仍占位）。 */',
    s('bt-label') + ' {',
    '  grid-area: 1 / 1;',
    '  min-width: 0;',
    '  text-align: center;',
    '  overflow-wrap: anywhere;',
    '}',
    s('bt-label') + '.' + WIZARD_SHELL_LABEL_LOADING + ' {',
    '  visibility: hidden;',
    '}',
    busy + ' ' + c('bt-label') + ' {',
    '  visibility: hidden;',
    '}',
    busy + ' ' + c('bt-label') + '.' + WIZARD_SHELL_LABEL_LOADING + ' {',
    '  visibility: visible;',
    '}',
    '/* 主键（实底）：底取 `accent-text` 而不是 `accent`——小字压强调底走仓内既有口径',
    '   （`accent` 在 `neutral` 那套上只有 4.02:1，过不了文本地板；`accent-text` 起才够）。 */',
    bt + '.' + WIZARD_SHELL_BT_PRIMARY + ' {',
    '  border-color: ' + skinVar('accent-text') + ';',
    '  background: ' + skinVar('accent-text') + ';',
    '  color: ' + skinVar('accent-ink') + ';',
    '  font-weight: 700;',
    '}',
    '/* 按不动：原生 `disabled` ＋ `cursor: not-allowed`（"看着能点、点了没反应"是不许留的中间档）。',
    '   三层都要给：**字**（弱文字档）＋**形**（虚线框：实线与虚线的区别换皮不塌）＋**底**（透明，露出脚行底色），',
    '   只染一层颜色在纸面语言里读不出来（原型是"软底压软底"＝按不动的那枚与脚行同色，等于没画）。 */',
    bt + '[disabled] {',
    '  border-style: dashed;',
    '  border-color: ' + skinVar('line') + ';',
    '  background: transparent;',
    '  color: ' + skinVar('ink-3') + ';',
    '  cursor: not-allowed;',
    '}',
    '/* 推进中的主键：**保住实心底**（字已换成「保存中」，就地告诉读者"它在干活"）——',
    '   这一条要压在通用禁用规则**之后**，否则一按下去红底就变虚框、读者会以为取消了。',
    '   中段一律用**裸槽类** `c(...)`：`bt` 自带 `.ilife-page-ui ` 前缀，再把两个带前缀的选择器拼起来',
    '   会拼出「件里再套一层 page-ui」的要求 ⇒ 那条规则永远不命中（这条自己踩过，判据里钉着）。 */',
    busy + ' ' + c('bt') + '.' + WIZARD_SHELL_BT_PRIMARY + ' {',
    '  border-style: solid;',
    '  border-color: ' + skinVar('accent-text') + ';',
    '  background: ' + skinVar('accent-text') + ';',
    '  color: ' + skinVar('accent-ink') + ';',
    '}',
    bt + ':focus-visible {',
    '  outline: 2px solid ' + skinVar('accent') + ';',
    '  outline-offset: 2px;',
    '}',
    bt + ':not([disabled]):active {',
    '  transform: scale(.98);',
    '}',
    '@media (hover: hover) and (pointer: fine) {',
    '  ' + bt + ':not([disabled]):hover {',
    '    border-color: ' + skinVar('ink-3') + ';',
    '  }',
    '}',
    '/* 窄容器（<' + String(WIZARD_SHELL_NARROW_PX) + 'px）：提示句独占一行、三枚键均分剩下那一行——',
    '   手指够得到（每个键都吃满一份宽度），也不会有哪一枚被挤到卡片外。',
    '   判的是**本件自己的宽度**：本件会被嵌进侧栏／面板／卡片，视口宽 ≠ 组件宽（所以这里不用 `@media`）。 */',
    '@container (max-width: ' + String(WIZARD_SHELL_NARROW_PX) + 'px) {',
    '  ' + s('hint') + ' {',
    '    flex: 1 1 100%;',
    '  }',
    '  ' + s('acts') + ' {',
    '    flex: 1 1 100%;',
    '    margin-left: 0;',
    '  }',
    '  ' + bt + ' {',
    '    flex: 1 1 auto;',
    '  }',
    '}',
    '/* 动效偏好：只关过渡，不关状态（状态不许卡在半路 ⇒ 不用 `transitionend` 驱动任何东西）。',
    '   选择器一行里两个槽各带一次作用域：`bt` 与选项那一条不在同一个文件，故这里用裸类名拼出来。 */',
    '@media (prefers-reduced-motion: reduce) {',
    '  ' + bt + ',',
    '  ' + root + ' .' + wizardShellSlot('opt', p) + ' {',
    '    transition: none;',
    '  }',
    '}',
  ].join(LF);
}
