/** wizard-shell · **答题面那两块样式**（同目录第二份样式来源；由 `style.ts` 的 `wizardShellCss()` 汇总）。
 *
 *  为什么有这一份：本件一次落「一问一屏」的三种答法（选项／填空／确认屏）＋ 错态行，样式段一度到 479 行
 *  （本包告警线 350，见 `packages/base-render/AGENTS.md`）。三块之间的边界干净：
 *   · **选项段**（`opts`／`opt`／`mk`／`tx`／标题与说明）＝ 一条一条的卡；
 *   · **填空段**（`fields`／`fld`／标签／输入框／提示）＝ 一格一格的输入；
 *   · **空态与错态**（`confirm`／`error`）＝ 没有答法、或答得不对时的那两句话。
 *  拆的是「住哪个文件」，**取值一个字节都没改**（先例 `scatter-fit/style-forms.ts`、`date-range/style-calendar.ts`）。
 *
 *  纪律同 `style.ts`：只经 `skinVar()` 读皮肤／全部规则 scope 在 `.<prefix>page-ui` 之下／
 *  零 `:root`、零 `!important`、零颜色字面量／**不拿 `ink` 系当面**（选中面走 `accent-soft` ＋ `accent-text` ＋ `accent` 描边）。
 */
import { skinVar } from '../skin/contract.js';
import {
  WIZARD_SHELL_BAR_PX,
  WIZARD_SHELL_MIN_TARGET_PX,
  WIZARD_SHELL_NARROW_PX,
  WIZARD_SHELL_OPTION_MIN_HEIGHT_PX,
  WIZARD_SHELL_TARGET_GAP_PX,
  wizardShellSlot,
  type WizardShellSlot,
} from './attrs.js';

/** 换行（仓库口径：不写字面换行转义）。 */
const LF = String.fromCharCode(10);

/** 答题面那几块的样式。恒返回非空 CSS 文本（由 `wizardShellCss()` 插在壳段与脚行段之间）。 */
export function wizardShellAnswersCss(input?: { readonly prefix?: string }): string {
  const p = input !== undefined && input !== null
    && typeof input.prefix === 'string' && input.prefix !== '' ? input.prefix : 'ilife-';
  const root = '.' + p + 'page-ui';
  const s = (slot: WizardShellSlot): string => root + ' .' + wizardShellSlot(slot, p);
  /** **裸类名**：只用在复合选择器的中段（`X > .槽`、`X:has(…) > .槽`）；`s()` 自带 scope，只许当选择器开头。 */
  const c = (slot: WizardShellSlot): string => '.' + wizardShellSlot(slot, p);
  const opt = s('opt');

  return [
    '/* ── 选项段：一条选项整条是 `<label>`（命中区）⇒ 触控目标 = 这一条，恒 ≥56px 高。 ── */',
    s('opts') + ' {',
    '  display: grid;',
    '  gap: ' + String(WIZARD_SHELL_TARGET_GAP_PX) + 'px;',
    '  min-width: 0;',
    '}',
    opt + ' {',
    '  position: relative;',
    '  display: grid;',
    '  grid-template-columns: 24px minmax(0, 1fr);',
    '  align-items: center;',
    '  gap: 12px;',
    '  box-sizing: border-box;',
    '  min-height: ' + String(WIZARD_SHELL_OPTION_MIN_HEIGHT_PX) + 'px;',
    '  padding: 10px 14px;',
    '  border: 2px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  cursor: pointer;',
    '  transition: transform 80ms cubic-bezier(.22, 1, .36, 1);',
    '}',
    '/* 标记位：空圆环（未选）→ 实心圆 ＋ 对钩（选中）。环／圆是**形状**，不靠色。 */',
    s('mk') + ' {',
    '  box-sizing: border-box;',
    '  display: block;',
    '  width: 24px;',
    '  height: 24px;',
    '  border: 2px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-pill') + ';',
    '  background: ' + skinVar('surface') + ';',
    '}',
    s('tx') + ' {',
    '  display: grid;',
    '  gap: 3px;',
    '  min-width: 0;',
    '}',
    s('opt-title') + ' {',
    '  min-width: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 700;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 选项说明：**不许 `；` 与「三连顿号」**（那是拿符号顶替版式的设计债）——分行写，不写分隔符。 */',
    s('opt-desc') + ' {',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-style: normal;',
    '  font-weight: 400;',
    '  line-height: 1.5;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 鼠标悬停只是**提示**，不是唯一通路（选中态与焦点态各有自己的标记）。 */',
    '@media (hover: hover) and (pointer: fine) {',
    '  ' + opt + ':not(:has(input:checked)):not(:has(input[disabled])):hover {',
    '    border-color: ' + skinVar('ink-3') + ';',
    '  }',
    '}',
    '/* 真按下：缩一格（≤80ms 内回弹；只动 transform，不触发布局）。 */',
    opt + ':not(:has(input[disabled])):active {',
    '  transform: scale(.98);',
    '}',
    '/* 选中那一条（**有文字的选中面**）：软底 ＋ 主色描边；左端一道竖条是**形状**那一重。',
    '   判选中走**原生** `:has(input:checked)`：状态只有一处事实（`<input checked>`），不另挂修饰类。 */',
    opt + ':has(input:checked) {',
    '  border-color: ' + skinVar('accent') + ';',
    '  background: ' + skinVar('accent-soft') + ';',
    '  box-shadow: inset ' + String(WIZARD_SHELL_BAR_PX) + 'px 0 0 ' + skinVar('accent') + ';',
    '}',
    opt + ':has(input:checked) > ' + c('opt-title') + ' {',
    '  color: ' + skinVar('accent-text') + ';',
    '}',
    '/* 选中态第二重（字）：标记位变实心圆 ＋ 对钩（勾是图形，实底上只放它）。 */',
    opt + ':has(input:checked) > ' + c('mk') + ' {',
    '  border-color: ' + skinVar('accent') + ';',
    '  background: ' + skinVar('accent') + ';',
    '}',
    opt + ':has(input:checked) > ' + c('mk') + '::after {',
    '  content: "\\2713";',
    '  display: flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  width: 100%;',
    '  height: 100%;',
    '  color: ' + skinVar('accent-ink') + ';',
    '  font-size: 12px;',
    '  font-weight: 800;',
    '  line-height: 1;',
    '}',
    '/* 焦点：原生框收到焦点时整条显形（**可见焦点 ≥2px**，不许 `outline:none` 无替代）。 */',
    opt + ':has(input:focus-visible) {',
    '  outline: 2px solid ' + skinVar('accent') + ';',
    '  outline-offset: 2px;',
    '}',
    '/* 原生单选：视觉隐藏但**仍在无障碍树里**（1px 盒 ＋ `opacity: 0`，不是 `display: none`）。 */',
    opt + ' > input[type="radio"] {',
    '  position: absolute;',
    '  width: 1px;',
    '  height: 1px;',
    '  opacity: 0;',
    '  pointer-events: none;',
    '}',
    '/* 按不动：`cursor: not-allowed`（为什么不能动由"整壳禁用"那一行写清）。 */',
    opt + ':has(input[disabled]) {',
    '  cursor: not-allowed;',
    '}',
    '/* ── 填空段：标签 ＋ 输入框 ＋ 提示，一列往下走（窄档不折列——折了反倒要横滑）。 ── */',
    s('fields') + ' {',
    '  display: grid;',
    '  gap: 12px;',
    '  min-width: 0;',
    '}',
    s('fld') + ' {',
    '  display: grid;',
    '  gap: 6px;',
    '  min-width: 0;',
    '}',
    s('fld-label') + ' {',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 600;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 输入框：命中盒 ≥44 高；`border-box` ＋ `width: 100%`（窄档不得把输入框顶出去）。 */',
    s('fld-input') + ' {',
    '  box-sizing: border-box;',
    '  width: 100%;',
    '  max-width: 100%;',
    '  min-width: 0;',
    '  min-height: ' + String(WIZARD_SHELL_MIN_TARGET_PX) + 'px;',
    '  padding: 0 12px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('ground') + ';',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '}',
    s('fld-input') + ':focus-visible {',
    '  outline: 2px solid ' + skinVar('accent') + ';',
    '  outline-offset: 1px;',
    '}',
    s('fld-input') + '[disabled] {',
    '  background: ' + skinVar('surface-2') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '  cursor: not-allowed;',
    '}',
    s('fld-hint') + ' {',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1.55;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* ── 空态：没有答法那一问写清"不用填"（**设计过的空态**，不是留白）。 ── */',
    s('confirm') + ' {',
    '  margin: 0;',
    '  min-width: 0;',
    '  padding: 10px 12px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('surface-2') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 窄容器：选项的内距收一档（文字多一行也放得下）——判的是**本件自己的宽度**，不是视口。 */',
    '@container (max-width: ' + String(WIZARD_SHELL_NARROW_PX) + 'px) {',
    '  ' + opt + ' {',
    '    gap: 10px;',
    '    padding: 10px 12px;',
    '  }',
    '}',
  ].join(LF);
}
