/** relation-picker · **组件出口**（本组件对外的唯一名字面）。
 *
 *  五件运行名：`renderRelationPicker(input)`（产标记，零 DOM）／`relationPickerCss()`（样式段）／
 *  `buildRelationPickerJs()`（运行时段：输入即筛 ＋ 整行可点 ＋ 命中词重画 ＋ 就地新建 ＋ 「换」重选）。
 *  标记契约（别的件／页面要按名字找元素时读它）：`RELATION_PICKER_CLASS`／`RELATION_PICKER_SLOTS`／
 *  `relationPickerSlot()`／`RELATION_PICKER_PANEL_ATTR`／`RELATION_PICKER_ITEM_ATTR`／
 *  `RELATION_PICKER_QUERY_ATTR`／`RELATION_PICKER_VALUE_ATTR`。
 *  闭集与几何：`RELATION_PICKER_FORMS`（`overlay` 浮层选一个／`inline` 行内展开选一个）／
 *  `RELATION_PICKER_TOUCH_PX`／`RELATION_PICKER_ROW_MIN_PX`／`RELATION_PICKER_GAP_PX`。
 *  三条事件：`RELATION_PICKER_EVENT_SELECT`（选中一行）／`RELATION_PICKER_EVENT_CREATE`（点了新建）／
 *  `RELATION_PICKER_EVENT_QUERY`（筛完的真读数）。
 *
 *  用法与参数表见同目录 `README.md`。消费方走 `base-paint/blocks`（组件层出口），不走根出口。
 */
export {
  RELATION_PICKER_ATTR,
  RELATION_PICKER_BOUND_ATTR,
  RELATION_PICKER_CHANGE_ATTR,
  RELATION_PICKER_CHOSEN_ATTR,
  RELATION_PICKER_CLASS,
  RELATION_PICKER_CLEAR_ATTR,
  RELATION_PICKER_CONTAINER,
  RELATION_PICKER_CREATE_ATTR,
  RELATION_PICKER_EDGE_PX,
  RELATION_PICKER_EMPTY_ATTR,
  RELATION_PICKER_EVENT_CREATE,
  RELATION_PICKER_EVENT_QUERY,
  RELATION_PICKER_EVENT_SELECT,
  RELATION_PICKER_FOOT_ATTR,
  RELATION_PICKER_FORMS,
  RELATION_PICKER_FORM_ATTR,
  RELATION_PICKER_GAP_PX,
  RELATION_PICKER_GROUP_ATTR,
  RELATION_PICKER_HIT_ATTR,
  RELATION_PICKER_HOVER_QUERY,
  RELATION_PICKER_INLINE_ATTR,
  RELATION_PICKER_ITEM_ATTR,
  RELATION_PICKER_NAME_ATTR,
  RELATION_PICKER_NARROW_PX,
  RELATION_PICKER_OPEN_ATTR,
  RELATION_PICKER_PANEL_ATTR,
  RELATION_PICKER_PANEL_MAX_PX,
  RELATION_PICKER_QUERY_ATTR,
  RELATION_PICKER_RECENT_ATTR,
  RELATION_PICKER_ROW_MIN_PX,
  RELATION_PICKER_RUNTIME_ATTR,
  RELATION_PICKER_SEARCH_ATTR,
  RELATION_PICKER_SLOTS,
  RELATION_PICKER_TEXT,
  RELATION_PICKER_TOUCH_PX,
  RELATION_PICKER_VALUE_ATTR,
  relationPickerSlot,
} from './attrs.js';
export type {
  RelationPickerForm,
  RelationPickerInput,
  RelationPickerOption,
  RelationPickerSlot,
} from './attrs.js';
export { renderRelationPicker } from './render.js';
export { relationPickerCss } from './style.js';
export { buildRelationPickerJs } from './runtime.js';
