/** relation-picker · **样式段**（本件唯一的样式来源）。
 *
 *  纪律（与本层其余件同一份）：
 *   · 只经 `skinVar()` 读皮肤 —— 组件里**不写** `var(--ilife-…)`（兜底链只许住在 `skin/contract.ts`）；
 *   · 全部规则 scope 在 `.<prefix>page-ui` 之下（不开本配方的页零命中）；不写 `:root`／`!important`、不新增 token 名；
 *   · **宽度只许容器判**：根自己声明 `container`，行内的收紧走 `@container`；媒体查询只判设备能力
 *     （悬停是不是增强、要不要减动效），**一条视口宽度查询都没有**；
 *   · 名字与数量**永不 `…` 截断**：一律 `overflow-wrap: anywhere`，不写 `text-overflow`／`line-clamp`／`nowrap`。
 *
 *  选中语汇（照 `docs/base/base-render/选中态与皮肤语言.md` 第三节法则表）：
 *   · **整行选中**＝次要面底 ＋ 左侧 2px 主色侧标；行内主字仍主墨色；另有 ✓ 记号与行尾「已选」二字
 *     （色之外还有形与字——原型写 3px 侧标，落地按法条收成 2px）；
 *   · **触发键读当前值**＝强调软底 ＋ 主色描边（有文字的选中面那一档的字色地板由描边与字重承担，
 *     键里的主字仍走主墨色，不断对比）；
 *   · 实心 ✓ 块（`mk` 选中态／`tick`）是**无文字的点**＝主色实底。
 */
import { skinVar } from '../skin/contract.js';
import {
  RELATION_PICKER_CONTAINER,
  RELATION_PICKER_EDGE_PX,
  RELATION_PICKER_GAP_PX,
  RELATION_PICKER_HOVER_QUERY,
  RELATION_PICKER_NARROW_PX,
  RELATION_PICKER_PANEL_MAX_PX,
  RELATION_PICKER_ROW_MIN_PX,
  RELATION_PICKER_TOUCH_PX,
  relationPickerSlot,
  type RelationPickerSlot,
} from './attrs.js';
import { relationPickerFormsCss } from './style-forms.js';
import { relationPickerListCss } from './style-list.js';

/** 换行（仓库口径：不写字面换行转义）。 */
const LF = String.fromCharCode(10);

/** 本组件的样式段。恒返回非空 CSS 文本。 */
export function relationPickerCss(input?: { readonly prefix?: string }): string {
  const p = input !== undefined && input !== null
    && typeof input.prefix === 'string' && input.prefix !== '' ? input.prefix : 'ilife-';
  const root = '.' + p + 'page-ui';
  /** 带 scope 的完整选择器（一条规则打头用）。 */
  const s = (slot: RelationPickerSlot): string => root + ' ' + sc(slot);
  /** **槽类名**（不带 scope）：写「某槽下的子件」时只许用它——把带 scope 的选择器再拼一次，
   *  会拼出 `.…page-ui .A > .…page-ui .B` 这种**永不命中**的死规则。 */
  function sc(slot: RelationPickerSlot): string {
    return '.' + relationPickerSlot(slot, p);
  }
  const hover = '@media ' + RELATION_PICKER_HOVER_QUERY;
  /** 行这一格的子件（`.…-row > .…-name` 这种）。**结构层级必须与 `render.ts` 的标记逐层对齐**。 */
  const rowChild = (slot: RelationPickerSlot): string => s('row') + ' > ' + sc(slot);
  /** 文字格里的子件（名字／副语住在 `-tx` 这一格里）。 */
  const txChild = (slot: RelationPickerSlot): string => s('tx') + ' > ' + sc(slot);

  return [
    '/* relation-picker（关系选择器 · overlay 浮层选一个／inline 行内展开选一个）：',
    '   字段行读当前值，列表里那一行是选中态；搜不到就地新建，不用退出去先建。 */',
    root + ' ' + '.' + p + 'block-relation-picker {',
    '  display: grid;',
    '  gap: 6px;',
    '  min-width: 0;',
    '  max-width: ' + String(RELATION_PICKER_PANEL_MAX_PX) + 'px;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-body') + ';',
    '  line-height: 1.5;',
    '  container: ' + RELATION_PICKER_CONTAINER + ' / inline-size;',
    '}',
    '/* 字段行：标签 ＋ 触发键（触发键里读的是当前值）。 */',
    s('field') + ' {',
    '  display: grid;',
    '  gap: 5px;',
    '  min-width: 0;',
    '}',
    s('label') + ' {',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 600;',
    '  overflow-wrap: anywhere;',
    '}',
    s('state') + ' { font-style: normal; font-weight: 400; }',
    s('box') + ' {',
    '  display: flex;',
    '  align-items: center;',
    '  gap: 10px;',
    '  min-height: ' + String(RELATION_PICKER_TOUCH_PX) + 'px;',
    '  padding: 0 12px;',
    '  border: 1px solid ' + skinVar('accent') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('accent-soft') + ';',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 600;',
    '  line-height: 1.4;',
    '  text-align: left;',
    '  cursor: pointer;',
    '  transition: transform 80ms ease;',
    '  overflow-wrap: anywhere;',
    '}',
    s('box') + ':active { transform: scale(.98); }',
    s('value') + ' { flex: 1 1 auto; min-width: 0; overflow-wrap: anywhere; }',
    s('caret') + ' { flex: none; color: ' + skinVar('ink-3') + '; font-size: 12px; }',
    '/* 浮面：顶层浮面。宽＝min(上限, 视口 let 开两边边距)，内容长了内部滚。',
    '   行内那一块：字段行下面推开的那一块（单列，窄档不并排）。 */',
    s('panel') + ' {',
    '  width: min(' + String(RELATION_PICKER_PANEL_MAX_PX) + 'px, calc(100% - '
      + String(RELATION_PICKER_EDGE_PX * 2) + 'px));',
    '  max-height: min(78dvh, ' + String(RELATION_PICKER_PANEL_MAX_PX) + 'px);',
    '  overflow-y: auto;',
    '  overscroll-behavior: contain;',
    '  margin-top: 8px;',
    '  padding: 0 0 10px;',
    '  border: 1px solid color-mix(in srgb, ' + skinVar('ink') + ' 30%, ' + skinVar('line') + ');',
    '  border-radius: ' + skinVar('radius') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  color: ' + skinVar('ink') + ';',
    '  box-shadow: 0 0 0 3px color-mix(in srgb, ' + skinVar('ink') + ' 9%, transparent);',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-body') + ';',
    '}',
    s('panel') + '::backdrop { background: color-mix(in srgb, ' + skinVar('ink') + ' 42%, transparent); }',
    '/* 行内那一块与选完那一行（`style-forms.ts`）：同一份纪律、同一个前缀，插在这里——',
    '   顺序即层叠顺序，改动前后产物逐字节相同。 */',
    relationPickerFormsCss({ prefix: p }),
    '/* 输入行：输入框通栏，清空键固定 44×44。 */',
    s('in') + ' {',
    '  display: flex;',
    '  align-items: center;',
    '  gap: 10px;',
    '  padding: 2px 10px 2px 14px;',
    '  border-bottom: 1px solid ' + skinVar('line') + ';',
    '}',
    s('q') + ' {',
    '  flex: 1 1 auto;',
    '  min-width: 0;',
    '  min-height: 50px;',
    '  border: 0;',
    '  background: none;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-body') + ';',
    '  line-height: 1.4;',
    '}',
    s('q') + '::placeholder { color: ' + skinVar('ink-3') + '; }',
    s('q') + ':focus-visible {',
    '  outline: 2px solid ' + skinVar('accent') + ';',
    '  outline-offset: -3px;',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '}',
    s('clear') + ' {',
    '  flex: none;',
    '  display: inline-flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  width: ' + String(RELATION_PICKER_TOUCH_PX) + 'px;',
    '  height: ' + String(RELATION_PICKER_TOUCH_PX) + 'px;',
    '  border: 0;',
    '  background: none;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-body') + ';',
    '  cursor: pointer;',
    '  transition: transform 80ms ease;',
    '}',
    s('clear') + ':active { transform: scale(.98); }',
    '/* 错态写在输入框旁边（不只染色）：`aria-describedby` 指的就是它。 */',
    s('err') + ' {',
    '  margin: 0;',
    '  padding: 0 14px 8px;',
    '  color: ' + skinVar('danger') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 列头行：sources 名归左、读数名归右，与下面每行同一条内边距（读数长短挤不到名字）。 */',
    s('colh') + ' {',
    '  display: flex;',
    '  align-items: baseline;',
    '  justify-content: space-between;',
    '  gap: 10px;',
    '  padding: 6px 14px;',
    '  background: ' + skinVar('surface-2') + ';',
    '  border-bottom: 1px solid ' + skinVar('line') + ';',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 700;',
    '  letter-spacing: .05em;',
    '}',
    '/* 列头两段：长了也在自己那一段里换行（读数再长也挤不到名字那一段）。 */',
    s('col') + ', ' + s('colr') + ' { min-width: 0; overflow-wrap: anywhere; }',
    '/* 分组标题：只有字号／字重／字距与颜色，无底色无线（组与组靠行间 8px 缝分级）。 */',
    s('grp') + ' {',
    '  display: block;',
    '  margin: 0;',
    '  padding: 9px 14px 3px;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 700;',
    '  letter-spacing: .05em;',
    '  overflow-wrap: anywhere;',
    '}',
    s('grp') + '[hidden] { display: none; }',
    '/* 行容器、一行选项与命中词（`style-list.ts`）：同一份纪律、同一个前缀，插在这里——',
    '   顺序即层叠顺序，改动前后产物逐字节相同。 */',
    relationPickerListCss({ prefix: p }),
    '/* 无障碍地板：真实键盘用户的焦点必须看得见（焦点是**增强**，不是通路——每一行都点得到）。 */',
    s('box') + ':focus-visible, '
      + s('create') + ':focus-visible, ' + s('clear') + ':focus-visible {',
    '  outline: 2px solid ' + skinVar('accent') + ';',
    '  outline-offset: 2px;',
    '}',
    s('q') + ':focus-visible {',
    '  outline: 2px solid ' + skinVar('accent') + ';',
    '  outline-offset: -3px;',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '}',
    '/* 末行「新建」：前面一句 ＋ 把当前搜索词直接建成新的那一枚键（44 高，不断行）。 */',
    s('new') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: center;',
    '  gap: 8px 10px;',
    '  padding: 10px 14px;',
    '  border-top: 1px solid ' + skinVar('line') + ';',
    '  background: ' + skinVar('surface-2') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '  overflow-wrap: anywhere;',
    '}',
    s('newlabel') + ' { overflow-wrap: anywhere; }',
    s('create') + ' {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  gap: 6px;',
    '  min-height: ' + String(RELATION_PICKER_TOUCH_PX) + 'px;',
    '  min-width: ' + String(RELATION_PICKER_TOUCH_PX) + 'px;',
    '  padding: 0 14px;',
    '  border: 1px solid ' + skinVar('accent') + ';',
    '  border-radius: ' + skinVar('radius-pill') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '  line-height: 1.2;',
    '  cursor: pointer;',
    '  transition: transform 80ms ease;',
    '  overflow-wrap: anywhere;',
    '}',
    s('create') + ':active { transform: scale(.98); }',
    '/* 空态：一条都没命中时出来（脚注同时换成「换个短一点的词试试」）。 */',
    s('empty') + ' {',
    '  display: block;',
    '  margin: 0;',
    '  padding: 12px 14px;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    s('empty') + '[hidden] { display: none; }',
    '/* 脚注：这一屏现在是什么状态（常用去处／命中几条／换个词）——原地换字，不跳版。 */',
    s('foot') + ' {',
    '  display: block;',
    '  margin: 0;',
    '  padding: 10px 14px;',
    '  border-top: 1px solid ' + skinVar('line') + ';',
    '  background: ' + skinVar('surface-2') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 卡底那句提示。 */',
    s('hint') + ' {',
    '  margin: 0;',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 悬停只是增强（而且只在真有指针的设备上），点得到不靠它。 */',
    hover + ' {',
    '  ' + s('box') + ':hover { border-color: ' + skinVar('accent') + '; }',
    '  ' + s('clear') + ':hover { color: ' + skinVar('ink') + '; }',
    '  ' + s('row') + ':hover { background: ' + skinVar('surface-2') + '; }',
    '}',
    '/* 减动效：按下那一档的缩放直接关掉（没有东西卡在半路——状态不靠 transitionend）。 */',
    '@media (prefers-reduced-motion: reduce) {',
    '  ' + s('box') + ', ' + s('clear') + ', ' + s('create')
      + ' { transition: none; }',
    '}',
    '/* 窄档（**本件自己** < ' + String(RELATION_PICKER_NARROW_PX) + 'px）：**列一道也不折**。',
    '   列表本来就是单列，窄档真正要收的是行内左右内边距与那两道缝：缝 10px→8px、内边距各收 2px，',
    '   把这点宽度让给名字那一列（行内那一块的内边距住 `style-forms.ts`，同一道查询）。 */',
    '@container ' + RELATION_PICKER_CONTAINER + ' (max-width: ' + String(RELATION_PICKER_NARROW_PX) + 'px) {',
    '  ' + s('row') + ' {',
    '    column-gap: ' + String(RELATION_PICKER_GAP_PX) + 'px;',
    '    padding: 7px 12px;',
    '  }',
    '  ' + s('rows') + ' { padding: 0 12px 8px; }',
    '}',
  ].join(LF);
}
