/** relation-picker · **形态段样式**（`inline` 行内展开 ＋ 选完那一行；由 `style.ts` 汇总）。
 *
 *  拆分只为行数（本包告警线 350；与 `scatter-fit/style-forms.ts` 同一处手法）：
 *  同一份纪律、同一个前缀，搬走的是行数，不是取值；`relationPickerCss()` 的产物逐字节不变。
 */
import { skinVar } from '../skin/contract.js';
import {
  RELATION_PICKER_CONTAINER,
  RELATION_PICKER_GAP_PX,
  RELATION_PICKER_HOVER_QUERY,
  RELATION_PICKER_NARROW_PX,
  RELATION_PICKER_TOUCH_PX,
  relationPickerSlot,
  type RelationPickerSlot,
} from './attrs.js';

/** 换行（仓库口径：不写字面换行转义）。 */
const LF = String.fromCharCode(10);

/** 形态段：行内那一块、最近一排、「全部」组头、选完那一行。由 `style.ts` 按前缀汇总。 */
export function relationPickerFormsCss(input?: { readonly prefix?: string }): string {
  const p = input !== undefined && input !== null
    && typeof input.prefix === 'string' && input.prefix !== '' ? input.prefix : 'ilife-';
  const root = '.' + p + 'page-ui';
  /** 带 scope 的完整选择器（一条规则打头用）。 */
  const s = (slot: RelationPickerSlot): string => root + ' ' + sc(slot);
  /** **槽类名**（不带 scope）：只许用它写子件，不许把带 scope 的选择器再拼一次。 */
  function sc(slot: RelationPickerSlot): string {
    return '.' + relationPickerSlot(slot, p);
  }
  const hover = '@media ' + RELATION_PICKER_HOVER_QUERY;

  return [
    '/* relation-picker 形态段（`style-forms.ts`）：行内那一块、最近一排、「全部」组头、选完那一行。 */',
    '/* 行内展开那一块：字段行下面推开的那一块（单列，窄档不并排）；选完收起时 `hidden`。 */',
    s('inline') + ' {',
    '  display: grid;',
    '  gap: 0;',
    '  min-width: 0;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  padding: 10px 12px 12px;',
    '}',
    s('inline') + '[hidden] { display: none; }',
    s('inline') + ' > ' + sc('new') + ' { padding-left: 0; padding-right: 0; }',
    '/* 最近一排：横排换行的那一排（窄档自动折成两行）；一枚一点就选中那一项。 */',
    s('quick') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  gap: ' + String(RELATION_PICKER_GAP_PX) + 'px;',
    '  padding: 10px 0;',
    '  min-width: 0;',
    '}',
    s('quick') + ':empty { display: none; }',
    /* 一枚都不露时，运行时与渲染期都把这条带子收起来（同组头那条口径）。 */
    s('quick') + '[hidden] { display: none; }',
    s('chip') + '[hidden] { display: none; }',
    s('chip') + ' {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  gap: 6px;',
    '  min-height: ' + String(RELATION_PICKER_TOUCH_PX) + 'px;',
    '  padding: 0 13px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-pill') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '  line-height: 1;',
    '  cursor: pointer;',
    '  transition: transform 80ms ease;',
    '  overflow-wrap: anywhere;',
    '}',
    s('chip') + ':active { transform: scale(.98); }',
    s('chip') + '.is-on {',
    '  background: ' + skinVar('accent-soft') + ';',
    '  border-color: ' + skinVar('accent') + ';',
    '  color: ' + skinVar('accent-text') + ';',
    '}',
    s('tag') + ' {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('surface-2') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '  padding: 1px 5px;',
    '}',
    '/* 「全部」组头：组名（一档字）＋ 几个（一档灰读数，等宽数字）。 */',
    s('gh') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 4px 8px;',
    '  margin: 0;',
    '  padding: 12px 0 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 700;',
    '  overflow-wrap: anywhere;',
    '}',
    s('count') + ' {',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '  line-height: 1;',
    '  font-variant-numeric: tabular-nums;',
    '  overflow-wrap: anywhere;',
    '}',
    s('list') + ' { display: grid; gap: ' + String(RELATION_PICKER_GAP_PX) + 'px; margin-top: 2px; min-width: 0; }',
    s('list') + ' > ' + sc('row') + ' { padding-left: 0; padding-right: 0; }',
    '/* 选完收成的那一行：✓ ＋ 选了什么 ＋ 一枚真按钮「换」（**看得见、点得到**，不是一行带下划线的字）。 */',
    s('chosen') + ' {',
    '  display: grid;',
    '  grid-template-columns: auto minmax(0, 1fr) auto;',
    '  gap: 10px;',
    '  align-items: center;',
    '  margin-top: 10px;',
    '  padding: 8px 8px 8px 12px;',
    '  border: 1px solid ' + skinVar('accent') + ';',
    '  border-radius: ' + skinVar('radius') + ';',
    '  background: ' + skinVar('accent-soft') + ';',
    '  min-width: 0;',
    '}',
    s('chosen') + '[hidden] { display: none; }',
    s('tick') + ' {',
    '  display: grid;',
    '  place-items: center;',
    '  width: 24px;',
    '  height: 24px;',
    '  flex: none;',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('accent') + ';',
    '  color: ' + skinVar('accent-ink') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: 14px;',
    '  font-weight: 700;',
    '  line-height: 1;',
    '}',
    s('chosen') + ' > ' + sc('tx') + ' { min-width: 0; overflow-wrap: anywhere; }',
    s('result') + ' {',
    '  display: block;',
    '  color: ' + skinVar('accent-text') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 700;',
    '  overflow-wrap: anywhere;',
    '}',
    s('why') + ' {',
    '  display: block;',
    '  font-style: normal;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1.45;',
    '  overflow-wrap: anywhere;',
    '}',
    s('change') + ' {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  min-height: ' + String(RELATION_PICKER_TOUCH_PX) + 'px;',
    '  min-width: ' + String(RELATION_PICKER_TOUCH_PX) + 'px;',
    '  padding: 0 16px;',
    '  border: 1px solid ' + skinVar('accent') + ';',
    '  border-radius: ' + skinVar('radius-pill') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  color: ' + skinVar('accent-text') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 700;',
    '  line-height: 1;',
    '  cursor: pointer;',
    '  transition: transform 80ms ease;',
    '}',
    s('change') + ':active { transform: scale(.98); }',
    '/* 无障碍地板（形态段这两枚）：焦点是**增强**，不是通路。 */',
    s('chip') + ':focus-visible, ' + s('change') + ':focus-visible {',
    '  outline: 2px solid ' + skinVar('accent') + ';',
    '  outline-offset: 2px;',
    '}',
    '/* 悬停只是增强（而且只在真有指针的设备上），点得到不靠它。 */',
    hover + ' {',
    '  ' + s('chip') + ':hover { border-color: ' + skinVar('accent') + '; }',
    '}',
    '/* 减动效：按下那一档的缩放直接关掉。 */',
    '@media (prefers-reduced-motion: reduce) {',
    '  ' + s('chip') + ', ' + s('change') + ' { transition: none; }',
    '}',
    '/* 窄档（**本件自己** < ' + String(RELATION_PICKER_NARROW_PX) + 'px）：行内那一块的左右内边距各收 2px',
    '   （行那两道缝住 `style.ts`，同一道查询）。 */',
    '@container ' + RELATION_PICKER_CONTAINER + ' (max-width: ' + String(RELATION_PICKER_NARROW_PX) + 'px) {',
    '  ' + s('inline') + ' { padding: 8px 10px 10px; }',
    '}',
  ].join(LF);
}
