/** due-row · **样式段**（本件唯一的样式来源）。
 *
 *  三条纪律（与组件层其余件同一份）：
 *   1. 颜色／圆角／字面／字号一律经 `skinVar()` 读；本件源码里不出现手写的 `var(--ilife-…)`；
 *   2. 全部规则 scope 在 `.<prefix>page-ui` 之下；
 *   3. **三档靠「字 ＋ 形 ＋ 色」**：左竖条实线／点线／双线，档位字带底线／描边实底／双线框，
 *      点圆／方／菱 ⇒「大字报刊」皮肤下强调色＝墨黑也分得出紧急度。
 *
 *  交互件的地板（判据逐条断）：
 *   · 动作是真 `<button>`，命中盒 **≥44 高**、`min-width` 锁住（`DUE_ROW_BUTTON_MIN_WIDTH_PX`）
 *     ⇒ 开始／处理中／禁用三档换字**不跳版**；
 *   · `:hover` 包在 `@media (hover:hover) and (pointer:fine)` 里、且**不是唯一通路**；
 *   · `:active` 只动 `transform`（≤80ms）；`:focus-visible` 有 2px 可见焦点环；
 *   · `disabled` 有 `cursor:not-allowed`（为什么不能按写在按钮旁的 `note` 上）；
 *   · `prefers-reduced-motion` 下过渡关掉、状态照落（不许有东西卡在半路）；状态不依赖 `transitionend`。
 *
 *  几何契约：倒计时（放大的数）与到期日 `white-space:nowrap`、**永不截断**；
 *  窄宽由**容器**决定（`container-type:inline-size` ＋ `@container`），不看视口。
 */
import { skinVar } from '../skin/contract.js';
import { dueRowClass, dueRowSlot, type DueRowSlot } from './attrs.js';

/** 换行（仓库口径：不写字面换行转义）。 */
const LF = String.fromCharCode(10);

/** 本件的内容容器名（`@container` 按它命中）。 */
export const DUE_ROW_CONTAINER = 'ilife-due-row';
/** 窄档断点（px）：容器窄于它就把右侧那一块（倒计时 ＋ 动作）放到下一行（**不是**视口断点）。 */
export const DUE_ROW_NARROW_MAX_PX = 460;
/** 动作按钮的高度下限（px）：44 是全仓的触控地板。 */
export const DUE_ROW_BUTTON_MIN_HEIGHT_PX = 44;
/** 动作按钮的宽度下限（px）：换字（开始／处理中）时不跳版。 */
export const DUE_ROW_BUTTON_MIN_WIDTH_PX = 104;
/** 倒计时读数的字号（px）：一个显示级读数（与正文字号的比例 ≥4×）。 */
export const DUE_ROW_COUNT_PX = 34;

/** 本组件的样式段。恒返回非空 CSS 文本。 */
export function dueRowCss(input?: { readonly prefix?: string }): string {
  const p = input !== undefined && input !== null
    && typeof input.prefix === 'string' && input.prefix !== '' ? input.prefix : 'ilife-';
  const root = '.' + p + 'page-ui';
  /** 槽类的**裸**选择器（不带 `.page-ui` 前缀）：只用在"祖先已经由 `sc()` 给过"的嵌套选择器里——
   *  否则会拼成 `.page-ui .a .page-ui .b`（那要求 `.page-ui` 出现在件内部），永远匹配不上（实拍踩过）。 */
  const n = (name: DueRowSlot): string => '.' + dueRowSlot(name, p);
  const sc = (name: DueRowSlot): string => root + ' ' + n(name);
  const s = root + ' .' + dueRowClass(p);
  const item = sc('item');
  const v = skinVar;
  return [
    '/* due-row（到期行）：还剩多少天放大成读数，每行一个动作。 */',
    s + ' {',
    '  display: flex;',
    '  flex-direction: column;',
    '  min-width: 0;',
    '  container: ' + DUE_ROW_CONTAINER + ' / inline-size;',
    '}',
    sc('head') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 4px 10px;',
    '  padding-bottom: 6px;',
    '  border-bottom: 1px solid ' + v('line') + ';',
    '}',
    sc('heading') + ' {',
    '  color: ' + v('ink') + ';',
    '  font-size: ' + v('fs-sm') + ';',
    '  font-weight: 700;',
    '}',
    sc('count') + ' {',
    '  margin-left: auto;',
    '  color: ' + v('ink-3') + ';',
    '  font-size: ' + v('fs-xs') + ';',
    '  font-variant-numeric: tabular-nums;',
    '  white-space: nowrap;',
    '}',
    sc('list') + ' {',
    '  display: flex;',
    '  flex-direction: column;',
    '  min-width: 0;',
    '}',
    '/* 行：左竖条给档位（实线／点线／双线），右边是倒计时与动作。 */',
    item + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: flex-start;',
    '  gap: 4px 16px;',
    '  box-sizing: border-box;',
    '  min-width: 0;',
    '  padding: 12px 0 12px 12px;',
    '  border-top: 1px solid ' + v('line') + ';',
    '  border-left: 3px solid transparent;',
    '}',
    item + '.is-ok { border-left: 3px solid ' + v('ok') + '; }',
    item + '.is-warn { border-left: 3px dotted ' + v('warn') + '; }',
    item + '.is-danger { border-left: 3px double ' + v('danger') + '; }',
    sc('body') + ' {',
    '  display: flex;',
    '  flex-direction: column;',
    '  flex: 1 1 220px;',
    '  min-width: 0;',
    '}',
    sc('line1') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 4px 10px;',
    '  min-width: 0;',
    '}',
    '/* 档位字三档形状：底线／描边实底／双线框。 */',
    sc('tag') + ' {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  gap: 6px;',
    '  box-sizing: border-box;',
    '  flex: 0 0 auto;',
    '  padding: 1px 8px;',
    '  border: 1px solid transparent;',
    '  border-radius: ' + v('radius-pill') + ';',
    '  color: ' + v('ink-2') + ';',
    '  font-size: ' + v('fs-xs') + ';',
    '  font-weight: 700;',
    '  line-height: 1.5;',
    '  white-space: nowrap;',
    '}',
    sc('tag') + '.is-ok {',
    '  padding: 0 0 1px;',
    '  border: 0;',
    '  border-bottom: 2px solid ' + v('ok') + ';',
    '  border-radius: 0;',
    '  color: ' + v('ok') + ';',
    '}',
    sc('tag') + '.is-warn {',
    '  border: 1px solid ' + v('warn') + ';',
    '  background: ' + v('warn-soft') + ';',
    '  color: ' + v('warn') + ';',
    '}',
    sc('tag') + '.is-danger {',
    '  border: 3px double ' + v('danger') + ';',
    '  border-radius: 0;',
    '  color: ' + v('danger') + ';',
    '}',
    '/* 点三档形状：空心圆／实心方／实心菱。 */',
    sc('dot') + ' {',
    '  flex: 0 0 auto;',
    '  width: 8px;',
    '  height: 8px;',
    '  border: 1.5px solid currentColor;',
    '  border-radius: 50%;',
    '  background: none;',
    '}',
    sc('tag') + '.is-warn ' + n('dot') + ' {',
    '  border-radius: 1px;',
    '  background: currentColor;',
    '}',
    sc('tag') + '.is-danger ' + n('dot') + ' {',
    '  border-radius: 0;',
    '  background: currentColor;',
    '  transform: rotate(45deg);',
    '}',
    sc('name') + ' {',
    '  min-width: 0;',
    '  color: ' + v('ink') + ';',
    '  font-size: ' + v('fs-sm') + ';',
    '  font-weight: 700;',
    '  overflow-wrap: anywhere;',
    '}',
    sc('meta') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  gap: 2px 10px;',
    '  margin-top: 3px;',
    '  min-width: 0;',
    '  color: ' + v('ink-3') + ';',
    '  font-size: ' + v('fs-xs') + ';',
    '  font-variant-numeric: tabular-nums;',
    '  overflow-wrap: anywhere;',
    '}',
    sc('note') + ' {',
    '  margin-top: 4px;',
    '  color: ' + v('ink-2') + ';',
    '  font-size: ' + v('fs-xs') + ';',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    sc('side') + ' {',
    '  display: flex;',
    '  flex-direction: column;',
    '  align-items: flex-end;',
    '  gap: 4px;',
    '  flex: 0 1 auto;',
    '  margin-left: auto;',
    '  min-width: 0;',
    '}',
    '/* 倒计时：这一件的主读数（放大 ＋ 等宽数字 ＋ 永不截断）。 */',
    sc('countdown') + ' {',
    '  display: inline-flex;',
    '  align-items: baseline;',
    '  gap: 5px;',
    '  white-space: nowrap;',
    '}',
    sc('countdown-label') + ' {',
    '  color: ' + v('ink-2') + ';',
    '  font-size: ' + v('fs-xs') + ';',
    '  font-weight: 700;',
    '}',
    sc('count-value') + ' {',
    '  color: ' + v('ink') + ';',
    '  font-family: ' + v('font-display') + ';',
    '  font-size: ' + DUE_ROW_COUNT_PX + 'px;',
    '  font-variant-numeric: tabular-nums;',
    '  font-weight: 800;',
    '  line-height: 1.05;',
    '  letter-spacing: -.01em;',
    '}',
    item + '.is-warn ' + n('count-value') + ' { color: ' + v('warn') + '; }',
    item + '.is-danger ' + n('count-value') + ' { color: ' + v('danger') + '; }',
    sc('count-unit') + ' {',
    '  color: ' + v('ink-2') + ';',
    '  font-size: ' + v('fs-xs') + ';',
    '  font-weight: 700;',
    '}',
    sc('due') + ' {',
    '  color: ' + v('ink-3') + ';',
    '  font-family: ' + v('font-num') + ';',
    '  font-size: ' + v('fs-xs') + ';',
    '  font-variant-numeric: tabular-nums;',
    '  white-space: nowrap;',
    '}',
    sc('act') + ' {',
    '  display: flex;',
    '  flex-direction: column;',
    '  align-items: flex-end;',
    '  gap: 4px;',
    '  margin-top: 4px;',
    '  min-width: 0;',
    '}',
    '/* 动作：真按钮。命中盒 44 高、宽度锁住（换字不跳版）。 */',
    sc('button') + ' {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  box-sizing: border-box;',
    '  min-height: ' + DUE_ROW_BUTTON_MIN_HEIGHT_PX + 'px;',
    '  min-width: ' + DUE_ROW_BUTTON_MIN_WIDTH_PX + 'px;',
    '  padding: 0 14px;',
    '  border: 1px solid ' + v('accent') + ';',
    '  border-radius: ' + v('radius-sm') + ';',
    '  background: ' + v('accent') + ';',
    '  color: ' + v('accent-ink') + ';',
    '  font: inherit;',
    '  font-size: ' + v('fs-sm') + ';',
    '  font-weight: 700;',
    '  white-space: nowrap;',
    '  cursor: pointer;',
    '  transition: transform 60ms linear;',
    '}',
    sc('button') + '[disabled] {',
    '  border-color: ' + v('line') + ';',
    '  background: ' + v('surface-2') + ';',
    '  color: ' + v('ink-3') + ';',
    '  cursor: not-allowed;',
    '}',
    sc('button') + ':active { transform: scale(.98); }',
    sc('button') + ':focus-visible {',
    '  outline: 2px solid ' + v('accent') + ';',
    '  outline-offset: 2px;',
    '}',
    sc('act-note') + ' {',
    '  color: ' + v('ink-3') + ';',
    '  font-size: ' + v('fs-xs') + ';',
    '  text-align: right;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 错态：写在按钮旁边（不只染色）。 */',
    sc('err') + ' {',
    '  padding-left: 8px;',
    '  border-left: 3px solid ' + v('danger') + ';',
    '  color: ' + v('danger') + ';',
    '  font-size: ' + v('fs-xs') + ';',
    '  line-height: 1.55;',
    '  text-align: right;',
    '  overflow-wrap: anywhere;',
    '}',
    sc('foot') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 4px 12px;',
    '  margin-top: 10px;',
    '  padding-top: 8px;',
    '  border-top: 1px solid ' + v('line') + ';',
    '  color: ' + v('ink-2') + ';',
    '  font-size: ' + v('fs-xs') + ';',
    '}',
    sc('absent') + ' {',
    '  margin: 0;',
    '  padding: 12px 0 2px;',
    '  color: ' + v('ink-3') + ';',
    '  font-size: ' + v('fs-sm') + ';',
    '}',
    '/* 悬停：包在设备能力查询里（不是唯一通路——按钮本来就是按下去的）。 */',
    '@media (hover:hover) and (pointer:fine) {',
    '  ' + sc('button') + ':hover:not([disabled]) {',
    '    background: ' + v('accent-text') + ';',
    '    border-color: ' + v('accent-text') + ';',
    '  }',
    '}',
    '/* 减动效：过渡关掉，状态照落。 */',
    '@media (prefers-reduced-motion:reduce) {',
    '  ' + sc('button') + ' { transition: none; }',
    '}',
    '/* 窄档：右侧那一块（倒计时 ＋ 动作）挪到下一行、左对齐。 */',
    '@container ' + DUE_ROW_CONTAINER + ' (max-width: ' + DUE_ROW_NARROW_MAX_PX + 'px) {',
    '  ' + sc('side') + ' {',
    '    align-items: flex-start;',
    '    flex: 1 1 100%;',
    '    margin-left: 0;',
    '  }',
    '  ' + sc('act') + ' { align-items: flex-start; }',
    '  ' + sc('act-note') + ' { text-align: left; }',
    '  ' + sc('err') + ' { text-align: left; }',
    '}',
  ].join(LF);
}
