/** command-palette · **样式段**（本件唯一的样式来源）。
 *
 *  纪律（与本节其余件同一份）：
 *   · 只经 `skinVar()` 读皮肤 —— 组件里**不写** `var(--ilife-…)`（兜底链只许住在 `skin/contract.ts`）；
 *   · 全部规则 scope 在 `.<prefix>page-ui` 之下（不开本配方的页零命中）；不写 `:root`／`!important`、不新增 token 名；
 *   · **宽度只许容器判**：面板自己声明 `container`，行内的折行走 `@container`；媒体查询只判设备能力
 *     （悬停是不是增强、要不要减动效），**一条视口宽度查询都没有**。
 *
 *  两条几何事实（判据钉住，数只写在这里一处）：
 *   · 入口键与行右那一格都 ≥`COMMAND_PALETTE_TOUCH_PX`（44）高；行的命中盒＝**整行**（≥48 高、通栏）；
 *   · 相邻两行之间留 `COMMAND_PALETTE_GAP_PX`（8）px 缝——同一组里的行是连续项，
 *     缝就是相邻触控目标之间那道让手的地方（原型里是 1px 发丝线，落地按要求改成 8px 缝）。
 *
 *  浮面语言（与 `dialog`／`drawer-sheet`／`popover-menu` 同一套）：**硬边 ＋ 零模糊外圈**，
 *  不拿 `shadow`／`shadow-pop` 表达「浮起来」——`paper`／`broadsheet` 两套皮肤里投影本就是 none，
 *  拿它撑层次会让那两套里的浮面塌掉。面板外面那层遮罩走 `::backdrop`（浏览器给），色是皮肤主色的淡洗。
 */
import { skinVar } from '../skin/contract.js';
import {
  COMMAND_PALETTE_CONTAINER,
  COMMAND_PALETTE_EDGE_PX,
  COMMAND_PALETTE_GAP_PX,
  COMMAND_PALETTE_HOVER_QUERY,
  COMMAND_PALETTE_NARROW_PX,
  COMMAND_PALETTE_PANEL_MAX_PX,
  COMMAND_PALETTE_ROW_MIN_PX,
  COMMAND_PALETTE_TOUCH_PX,
  commandPaletteSlot,
  type CommandPaletteSlot,
} from './attrs.js';

/** 换行（仓库口径：不写字面换行转义）。 */
const LF = String.fromCharCode(10);

/** 面板高上限：屏幕的 78%（手机横屏也留得出关掉键与脚注）或宽档上限，取小的那个。 */
const COMMAND_PALETTE_PANEL_MAX_H = 'min(78dvh, ' + String(COMMAND_PALETTE_PANEL_MAX_PX) + 'px)';

/** 本组件的样式段。恒返回非空 CSS 文本。 */
export function commandPaletteCss(input?: { readonly prefix?: string }): string {
  const p = input !== undefined && input !== null
    && typeof input.prefix === 'string' && input.prefix !== '' ? input.prefix : 'ilife-';
  const root = '.' + p + 'page-ui';
  /** 带 scope 的完整选择器（一条规则打头用）。 */
  const s = (slot: CommandPaletteSlot): string => root + ' ' + sc(slot);
  /** **槽类名**（不带 scope）：写「某槽下的子件」时只许用它——把带 scope 的选择器再拼一次，
   *  会拼出 `.…page-ui .A > .…page-ui .B` 这种**永不命中**的死规则。 */
  function sc(slot: CommandPaletteSlot): string {
    return '.' + commandPaletteSlot(slot, p);
  }
  const hover = '@media ' + COMMAND_PALETTE_HOVER_QUERY;
  /** 行这一格的子件（`.…-row > .…-sk` 这种）。**结构层级必须与 `render.ts` 的标记逐层对齐**：
   *  少写一层就是永不命中的死规则（本件真踩过——主文字与副文字住在 `-tx` 里，写成 `-row > …` 之后
   *  两行挤成一行，只有把截图放大才看得出来；判据那边另加了一条「每条选择器都要命中至少一个真节点」）。 */
  const rowChild = (slot: CommandPaletteSlot): string => s('row') + ' > ' + sc(slot);
  /** 文字格里的子件（主文字／副文字住在 `-tx` 这一格里）。 */
  const txChild = (slot: CommandPaletteSlot): string => s('tx') + ' > ' + sc(slot);

  return [
    '/* command-palette（命令面板 · 形态 A「单栏分组结果（动作在前／页面在后）」）：',
    '   入口＝一页顶部一枚看得见的按钮；面板＝顶层浮面（原生 `popover`），✕ 与点面板外都在界面上。 */',
    root + ' ' + '.' + p + 'block-command-palette {',
    '  display: grid;',
    '  gap: 6px;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-body') + ';',
    '  line-height: 1.5;',
    '}',
    '/* 入口那一排：**看得见、点得到**是这一件的底线（隐式入口在手机上等于不存在）。',
    '   键与提示各占一段，容器一窄就整段折到下一行（不压字、不横滑）。 */',
    s('entry') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: center;',
    '  gap: ' + String(COMMAND_PALETTE_GAP_PX) + 'px 10px;',
    '  min-width: 0;',
    '}',
    s('open') + ' {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  gap: 8px;',
    '  min-height: ' + String(COMMAND_PALETTE_TOUCH_PX) + 'px;',
    '  padding: 0 16px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-pill') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 600;',
    '  line-height: 1;',
    '  cursor: pointer;',
    '  transition: transform 80ms ease;',
    '  overflow-wrap: anywhere;',
    '}',
    s('mark') + ' { display: inline-flex; align-items: center; }',
    s('mark') + ' > svg { display: block; color: ' + skinVar('accent') + '; }',
    '/* 面板开着的时候，入口键自己就是「当前这一档」（强调软底 ＋ 主色字 ＋ 主色描边）。 */',
    s('open') + '[aria-expanded="true"] {',
    '  background: ' + skinVar('accent-soft') + ';',
    '  border-color: ' + skinVar('accent') + ';',
    '  color: ' + skinVar('accent-text') + ';',
    '}',
    s('open') + ':active { transform: scale(.98); }',
    s('hint') + ' {',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1.5;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 面板：顶层浮面。宽＝min(上限, 视口 let 开两边边距)，高＝min(屏高 78%, 上限)，内容长了内部滚。',
    '   面板**自己就是容器**：行内的折行按面板的宽度判（@container），不按视口。 */',
    s('panel') + ' {',
    '  position: fixed;',
    '  inset: 0;',
    '  margin: auto;',
    '  width: min(' + String(COMMAND_PALETTE_PANEL_MAX_PX) + 'px, calc(100% - '
      + String(COMMAND_PALETTE_EDGE_PX * 2) + 'px));',
    '  max-height: ' + COMMAND_PALETTE_PANEL_MAX_H + ';',
    '  overflow-y: auto;',
    '  overscroll-behavior: contain;',
    '  padding: 0;',
    '  border: 1px solid color-mix(in srgb, ' + skinVar('ink') + ' 30%, ' + skinVar('line') + ');',
    '  border-radius: ' + skinVar('radius') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  color: ' + skinVar('ink') + ';',
    '  box-shadow: 0 0 0 3px color-mix(in srgb, ' + skinVar('ink') + ' 9%, transparent);',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-body') + ';',
    '  container: ' + COMMAND_PALETTE_CONTAINER + ' / inline-size;',
    '}',
    '/* 面板外那层：浏览器给的遮罩（点它那一下就是「点面板外」，关的动作归浏览器）。 */',
    s('panel') + '::backdrop { background: color-mix(in srgb, ' + skinVar('ink') + ' 42%, transparent); }',
    '/* 输入行：输入框通栏，关掉键固定 44×44。 */',
    s('in') + ' {',
    '  display: flex;',
    '  align-items: center;',
    '  gap: 10px;',
    '  padding: 2px 10px 2px 14px;',
    '  border-bottom: 1px solid ' + skinVar('line') + ';',
    '}',
    s('q') + ' {',
    '  flex: 1 1 auto;',
    '  min-width: 0;',
    '  min-height: 50px;',
    '  border: 0;',
    '  background: none;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-body') + ';',
    '  line-height: 1.4;',
    '}',
    s('q') + '::placeholder { color: ' + skinVar('ink-3') + '; }',
    s('q') + ':focus-visible {',
    '  outline: 2px solid ' + skinVar('accent') + ';',
    '  outline-offset: -3px;',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '}',
    s('x') + ' {',
    '  flex: none;',
    '  display: inline-flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  width: ' + String(COMMAND_PALETTE_TOUCH_PX) + 'px;',
    '  height: ' + String(COMMAND_PALETTE_TOUCH_PX) + 'px;',
    '  border: 0;',
    '  background: none;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-body') + ';',
    '  cursor: pointer;',
    '  transition: transform 80ms ease;',
    '}',
    s('x') + ':active { transform: scale(.98); }',
    '/* 错态写在输入框旁边（不只染色）：句子由 `render` 落进这一行，`aria-describedby` 指的就是它。 */',
    s('err') + ' {',
    '  margin: 0;',
    '  padding: 0 14px 8px;',
    '  color: ' + skinVar('danger') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 分组标题：标题 ＋ 括号里那句说明（这一组是就地做还是跳走）。 */',
    s('grp') + ' {',
    '  display: block;',
    '  margin: 0;',
    '  padding: 10px 14px 6px;',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 700;',
    '  letter-spacing: .05em;',
    '  overflow-wrap: anywhere;',
    '}',
    s('grp') + ' > b { font-weight: 500; }',
    '/* 行与行之间那道缝：相邻触控目标的让手位（8px）。 */',
    s('rows') + ' {',
    '  display: grid;',
    '  gap: ' + String(COMMAND_PALETTE_GAP_PX) + 'px;',
    '  padding: 0 14px 10px;',
    '  min-width: 0;',
    '}',
    '/* 一行＝一颗按钮（整行都是命中区）；`hidden` 是运行时段筛出来的「这一行现在不露」。 */',
    s('row') + ' {',
    '  display: grid;',
    '  grid-template-columns: auto minmax(0, 1fr) auto;',
    '  gap: 10px;',
    '  align-items: center;',
    '  min-height: ' + String(COMMAND_PALETTE_ROW_MIN_PX) + 'px;',
    '  padding: 6px 12px;',
    '  border: 0;',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: none;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-body') + ';',
    '  text-align: left;',
    '  cursor: pointer;',
    '}',
    s('row') + '[hidden] { display: none; }',
    rowChild('sk') + ' {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  min-height: 26px;',
    '  padding: 0 8px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('surface-2') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '  overflow-wrap: anywhere;',
    '}',
    rowChild('tx') + ' { min-width: 0; overflow-wrap: anywhere; }',
    txChild('lb') + ' {',
    '  display: block;',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 600;',
    '  overflow-wrap: anywhere;',
    '}',
    txChild('nt') + ' {',
    '  display: block;',
    '  font-style: normal;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1.45;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 行右那一格：这一行要干什么（执行／打开）。它是整行那颗按钮的写法，不是第二颗按钮。 */',
    rowChild('act') + ' {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  min-height: ' + String(COMMAND_PALETTE_TOUCH_PX) + 'px;',
    '  padding: 0 12px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-pill') + ';',
    '  background: ' + skinVar('surface-2') + ';',
    '  color: ' + skinVar('ink') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 700;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 命中词：底是主色的淡洗、形是下划线、字加粗——形与字重两样，不只靠颜色。 */',
    s('hit') + ' {',
    '  background: color-mix(in srgb, ' + skinVar('accent') + ' 24%, transparent);',
    '  border-bottom: 2px solid ' + skinVar('accent') + ';',
    '  color: inherit;',
    '  font-weight: 700;',
    '}',
    '/* 手指落下那一档：整行换次要面 ＋ 左侧一道主色标；行右那格抬到强调软底。',
    '   强调实底上不写正文级小字（对比地板），所以那一格走的是软底那一档。 */',
    s('row') + ':active {',
    '  background: ' + skinVar('surface-2') + ';',
    '  box-shadow: inset 4px 0 0 ' + skinVar('accent') + ';',
    '}',
    s('row') + ':active > ' + sc('act') + ', ' + s('row') + '.is-primary > ' + sc('act') + ' {',
    '  background: ' + skinVar('accent-soft') + ';',
    '  border-color: ' + skinVar('accent') + ';',
    '  color: ' + skinVar('accent-text') + ';',
    '}',
    '/* 无障碍地板：真实键盘用户的焦点必须看得见（焦点是**增强**，不是通路——每一行都点得到）。 */',
    s('row') + ':focus-visible {',
    '  outline: 2px solid ' + skinVar('accent') + ';',
    '  outline-offset: -2px;',
    '}',
    s('open') + ':focus-visible, ' + s('x') + ':focus-visible {',
    '  outline: 2px solid ' + skinVar('accent') + ';',
    '  outline-offset: 2px;',
    '}',
    '/* 停用档：点不动，而且**说得清为什么**（原因写在那一行的副文字那一位）。 */',
    s('row') + '.is-off { cursor: not-allowed; color: ' + skinVar('ink-2') + '; }',
    s('row') + '.is-off > ' + sc('act') + ' {',
    '  background: none;',
    '  color: ' + skinVar('ink-2') + ';',
    '}',
    '/* 空态：一条都没命中时出来（脚注同时换成「换个短一点的词试试」）。 */',
    s('empty') + ' {',
    '  display: block;',
    '  margin: 0;',
    '  padding: 12px 14px;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    s('empty') + '[hidden], ' + s('grp') + '[hidden] { display: none; }',
    '/* 脚注：这一屏现在是什么状态（常用去处／命中几条／换个词／正在找）——原地换字，不跳版。 */',
    s('foot') + ' {',
    '  display: block;',
    '  margin: 0;',
    '  padding: 10px 14px;',
    '  border-top: 1px solid ' + skinVar('line') + ';',
    '  background: ' + skinVar('surface-2') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 悬停只是增强（而且只在真有指针的设备上），点得到不靠它。 */',
    hover + ' {',
    '  ' + s('open') + ':hover { border-color: ' + skinVar('accent') + '; }',
    '  ' + s('x') + ':hover { color: ' + skinVar('ink') + '; }',
    '  ' + s('row') + ':hover { background: ' + skinVar('surface-2') + '; }',
    '}',
    '/* 减动效：按下那一档的缩放直接关掉（没有东西卡在半路——状态不靠 transitionend）。 */',
    '@media (prefers-reduced-motion: reduce) {',
    '  ' + s('open') + ', ' + s('x') + ' { transition: none; }',
    '}',
    '/* 窄档（**面板自己的宽度** < ' + String(COMMAND_PALETTE_NARROW_PX) + 'px）：来源技能片独占一行，',
    '   主文字与右边那格并到下一行——手机上名字短、片长，挤一行会把名字压成两三个字一列。 */',
    '@container ' + COMMAND_PALETTE_CONTAINER + ' (max-width: ' + String(COMMAND_PALETTE_NARROW_PX) + 'px) {',
    '  ' + s('row') + ' {',
    '    grid-template-columns: minmax(0, 1fr) auto;',
    '    row-gap: 2px;',
    '  }',
    '  ' + rowChild('sk') + ' { grid-column: 1 / -1; justify-self: start; }',
    '}',
  ].join(LF);
}
