/** switch-row · **样式段**（本件唯一的样式来源）。**重做件**。
 *
 *  纪律（与本层其余件同一份）：只经 `skinVar()` 读皮肤／全部规则 scope 在 `.<prefix>page-ui` 之下／
 *  零 `:root`／零 `!important`／零自定义属性／宽度只由 `@container` 判（`@media` 只判设备能力）。
 *
 *  重做的四条要点，全都落在这段样式里（判据逐条断）：
 *   1. **形**：轨道**关＝空心**（`background: transparent` ＋ 一圈发丝线）、**开＝实心**（填充 ＋ 同色边）；
 *      滑块关时贴左内距 `SWITCH_ROW_THUMB_INSET_PX`、开时贴右（`translateX(SWITCH_ROW_THUMB_TRAVEL_PX)`）
 *      ——**把颜色全拿掉，光看滑块位置也分得出开合**；
 *   2. **字**：状态字那一枚由标记给出（本段只管它的排版与"宽度锁住"，**不用 CSS 生成内容**）；
 *   3. **色**：`ok` 只是第三样；**零阴影**下轨道的边界靠 `line` 那一圈发丝线（不是投影）；
 *   4. 触控：命中盒 `.sw`（56×44）≥44×44，整行也是命中区；`:focus-visible` 给 ≥2px 可见描边；
 *      禁用只改视觉、不给"看着能点"的中间档（原生 `disabled` ＋ `cursor: not-allowed`）。
 *
 *  动效只碰 `transform`／`opacity`（滑块滑动是 `transform`，加载态是 `opacity`），`prefers-reduced-motion` 下关掉。
 */
import { skinVar } from '../skin/contract.js';
import {
  SWITCH_ROW_THUMB_INSET_PX,
  SWITCH_ROW_THUMB_PX,
  SWITCH_ROW_THUMB_TRAVEL_PX,
  SWITCH_ROW_TOUCH_PX,
  SWITCH_ROW_TRACK_H_PX,
  SWITCH_ROW_TRACK_W_PX,
  switchRowSlot,
  type SwitchRowSlot,
} from './attrs.js';

/** 换行（仓库口径：不写字面换行转义）。 */
const LF = String.fromCharCode(10);

/** 窄容器阈值（px）：**本件自己的宽度**。低于它时文字独占一行、状态字与开关落到第二行。 */
const NARROW_PX = 380;

/** 滑块滑动时长（ms）。 */
const SLIDE_MS = 120;

/** 本组件的样式段。恒返回非空 CSS 文本。 */
export function switchRowCss(input?: { readonly prefix?: string }): string {
  const p = input !== undefined && input !== null
    && typeof input.prefix === 'string' && input.prefix !== '' ? input.prefix : 'ilife-';
  const root = '.' + p + 'page-ui';
  const box = root + ' .' + p + 'block-switch-row';
  const s = (slot: SwitchRowSlot): string => root + ' .' + switchRowSlot(slot, p);
  /** 拼在 `box` **后面**的槽类（不再带 `.<prefix>page-ui`，否则会拼出嵌套的假选择器）。 */
  const inBox = (slot: SwitchRowSlot): string => ' .' + switchRowSlot(slot, p);
  /** 裸槽类（**给 `+`／`~` 这类兄弟组合器用**：右侧不能再带 `.page-ui` 前缀，否则永远不命中）。 */
  const cls = (slot: SwitchRowSlot): string => '.' + switchRowSlot(slot, p);
  const trackW = String(SWITCH_ROW_TRACK_W_PX) + 'px';
  const trackH = String(SWITCH_ROW_TRACK_H_PX) + 'px';
  const thumb = String(SWITCH_ROW_THUMB_PX) + 'px';
  const inset = String(SWITCH_ROW_THUMB_INSET_PX) + 'px';
  /* 命中盒高（≥44）与轨道在其中的垂直居中：轨道高 32 ⇒ 上下各 6px。 */
  const swH = String(SWITCH_ROW_TOUCH_PX) + 'px';
  const trackTop = String((SWITCH_ROW_TOUCH_PX - SWITCH_ROW_TRACK_H_PX) / 2) + 'px';

  return [
    '/* switch-row（开关行 · 重做件）：标签 ＋ 说明句（写清打开会怎样）／固定状态字／开关本体。',
    '   开与关同时给**形**（实心／空心轨道 ＋ 滑块贴左／贴右）、**字**（已开／已关）、**色**（ok 只是第三样）；',
    '   零阴影皮肤下边界靠那一圈发丝线，不靠投影。 */',
    box + ' {',
    '  container-type: inline-size;',
    '  display: grid;',
    '  gap: 8px;',
    '  min-width: 0;',
    '  padding: 12px 14px 14px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-body') + ';',
    '  line-height: 1.5;',
    '}',
    box + ' > * {',
    '  min-width: 0;',
    '}',
    '/* 整行是一枚 `<label>`：点名字、点说明、点开关都能翻 —— 命中区比 44×44 还大。 */',
    s('row') + ' {',
    '  display: grid;',
    '  grid-template-columns: minmax(0, 1fr) auto auto;',
    '  align-items: center;',
    '  gap: 4px 12px;',
    '  min-height: ' + String(SWITCH_ROW_TOUCH_PX + 12) + 'px;',
    '  cursor: pointer;',
    '}',
    s('text') + ' {',
    '  display: grid;',
    '  gap: 2px;',
    '  min-width: 0;',
    '}',
    s('label') + ' {',
    '  min-width: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 600;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 说明句是**要读的正文**（写清打开会怎样）：走 ink-2，不走更浅的弱文字档。 */',
    s('note') + ' {',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-style: normal;',
    '  font-weight: 400;',
    '  line-height: 1.5;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 状态字：**字**这一档。宽度锁住（已开／已关／更新中长短不一，锁住就不跳版）。 */',
    s('state') + ' {',
    '  box-sizing: border-box;',
    '  min-width: 4em;',
    '  padding: 1px 6px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 700;',
    '  letter-spacing: .04em;',
    '  text-align: center;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 开关本体：**命中盒 56×44**（视觉盒是里面那条轨道 56×32）。 */',
    s('sw') + ' {',
    '  position: relative;',
    '  display: inline-flex;',
    '  align-items: center;',
    '  flex: none;',
    '  box-sizing: border-box;',
    '  width: ' + trackW + ';',
    '  min-width: ' + trackW + ';',
    '  height: ' + swH + ';',
    '}',
    '/* 轨道（关）：**空心** —— 透明底 ＋ 一圈发丝线（零阴影皮肤下边界就靠它）。 */',
    s('track') + ' {',
    '  position: absolute;',
    '  left: 0;',
    '  right: 0;',
    '  top: ' + trackTop + ';',
    '  box-sizing: border-box;',
    '  height: ' + trackH + ';',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-pill') + ';',
    '  background: transparent;',
    '}',
    '/* 滑块（关）：贴**左**内距 —— 位置本身就是形状读数。 */',
    s('thumb') + ' {',
    '  position: absolute;',
    '  top: ' + inset + ';',
    '  left: ' + inset + ';',
    '  box-sizing: border-box;',
    '  width: ' + thumb + ';',
    '  height: ' + thumb + ';',
    '  border: 2px solid ' + skinVar('ink-3') + ';',
    '  border-radius: 50%;',
    '  background: ' + skinVar('surface') + ';',
    '  transition: transform ' + String(SLIDE_MS) + 'ms cubic-bezier(.22,1,.36,1);',
    '}',
    '/* 开：轨道**实心** ＋ 滑块贴**右**内距（离边的距离把开合读出来，颜色只是第三样）。 */',
    s('input') + ':checked + ' + cls('track') + ' {',
    '  background: ' + skinVar('ok') + ';',
    '  border-color: ' + skinVar('ok') + ';',
    '}',
    s('input') + ':checked + ' + cls('track') + inBox('thumb') + ' {',
    '  transform: translateX(' + String(SWITCH_ROW_THUMB_TRAVEL_PX) + 'px);',
    '  border-color: ' + skinVar('accent-ink') + ';',
    '  background: ' + skinVar('accent-ink') + ';',
    '}',
    '/* 视觉盒可以小、命中盒必须够：原生 `checkbox` 摊平在整块 `.sw` 上（真语义、真键盘）。 */',
    s('input') + ' {',
    '  position: absolute;',
    '  inset: 0;',
    '  box-sizing: border-box;',
    '  width: 100%;',
    '  height: 100%;',
    '  margin: 0;',
    '  opacity: 0;',
    '  cursor: pointer;',
    '}',
    '/* 悬停：只包在设备能力查询里（`hover:hover`），且**不是唯一通路**（键盘走原生 checkbox）。 */',
    '@media (hover:hover) and (pointer:fine) {',
    '  ' + s('row') + ':hover' + inBox('track') + ' {',
    '    border-color: ' + skinVar('ink-2') + ';',
    '  }',
    '}',
    '/* 真按下：只动 `transform`（80ms 内看得见）。 */',
    s('row') + ':active' + inBox('track') + ' {',
    '  transform: scale(.98);',
    '}',
    '/* 可见焦点：焦点落在原生 `checkbox` 上，描边画在轨道那一圈（≥2px，不许只有 `outline:none`）。 */',
    s('input') + ':focus-visible + ' + cls('track') + ' {',
    '  outline: 2px solid ' + skinVar('accent') + ';',
    '  outline-offset: 2px;',
    '}',
    '/* 更新中：位置与轨道保持原样（形状读数不变），滑块淡一档；光标给 `progress`。 */',
    box + '.is-loading' + inBox('thumb') + ' {',
    '  opacity: .6;',
    '}',
    box + '.is-loading' + inBox('sw') + ',',
    box + '.is-loading' + inBox('input') + ' {',
    '  cursor: progress;',
    '}',
    '/* 禁用：原生 `disabled` ＋ `cursor: not-allowed`；**为什么不能开**由下面那行说明句写清。 */',
    box + '.is-disabled' + inBox('row') + ' {',
    '  cursor: not-allowed;',
    '}',
    box + '.is-disabled' + inBox('input') + ' {',
    '  cursor: not-allowed;',
    '}',
    box + '.is-disabled' + inBox('track') + ' {',
    '  background: ' + skinVar('surface-2') + ';',
    '  border-color: ' + skinVar('line') + ';',
    '}',
    /* 禁用态的滑块：选择器要压过 `:checked + .track .thumb` 那一条（同特异度、靠后即胜）。 */
    box + '.is-disabled' + inBox('track') + inBox('thumb') + ' {',
    '  border-color: ' + skinVar('line') + ';',
    '  background: ' + skinVar('surface-2') + ';',
    '}',
    box + '.is-disabled' + inBox('label') + ' {',
    '  color: ' + skinVar('ink-3') + ';',
    '}',
    '/* 错误说明（写在控件旁边、被 `aria-describedby` 指到）：**不只染色**。 */',
    s('error') + ' {',
    '  margin: 0;',
    '  padding-left: 8px;',
    '  border-left: 2px solid ' + skinVar('danger') + ';',
    '  color: ' + skinVar('danger') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    box + '.is-invalid' + inBox('track') + ' {',
    '  border-color: ' + skinVar('danger') + ';',
    '}',
    '/* 口径行（可选）：这一行影响什么、什么时候生效。 */',
    s('caliber') + ' {',
    '  margin: 0;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 窄容器（<' + String(NARROW_PX) + 'px）：文字独占一行，状态字与开关落到第二行两端。',
    '   判的是**本件自己的宽度**（不用 `@media` 判宽度）。 */',
    '@container (max-width: ' + String(NARROW_PX) + 'px) {',
    '  ' + s('row') + ' {',
    '    grid-template-columns: minmax(0, 1fr) auto;',
    '    grid-template-areas: "text text" "state sw";',
    '  }',
    '  ' + s('text') + ' {',
    '    grid-area: text;',
    '  }',
    '  ' + s('state') + ' {',
    '    grid-area: state;',
    '    justify-self: start;',
    '  }',
    '  ' + s('sw') + ' {',
    '    grid-area: sw;',
    '    justify-self: end;',
    '  }',
    '}',
    '/* 减动效档：不许有东西卡在半路（滑块直接落位，不留过渡）。 */',
    '@media (prefers-reduced-motion:reduce) {',
    '  ' + s('thumb') + ' {',
    '    transition: none;',
    '  }',
    '  ' + s('row') + ':active' + inBox('track') + ' {',
    '    transform: none;',
    '  }',
    '}',
  ].join(LF);
}
