/** number-stepper · **样式段**（本件唯一的样式来源）。
 *
 *  纪律（与本层其余件同一份）：
 *   · 只经 `skinVar()` 读皮肤 —— 组件里**不写** `var(--ilife-…)`（兜底链只许住在 `skin/contract.ts`）；
 *   · 全部规则 scope 在 `.<prefix>page-ui` 之下（不开本配方的页零命中）；不写 `:root`／`!important`、
 *     不新增 token 名、不定义任何自定义属性；
 *   · **宽度只许容器判**：布局靠 `@container` ＋ 内在尺寸 ＋ `flex-wrap`；本件只有两条 `@media`，
 *     判的都是设备能力（`hover:hover`／`prefers-reduced-motion`），不判宽度。
 *
 *  几何契约（判据钉住）：三枚可点区与常用值一律 ≥44×44（`NUMBER_STEPPER_TOUCH_PX`），
 *  相邻触控目标留 `NUMBER_STEPPER_GAP_PX` 的缝（**不做连体键**：连体键在手机上最容易被误点）；
 *  值位最小宽度 `NUMBER_STEPPER_VALUE_MIN_PX` 把整排钉住，数字位数变了也不跳版。
 */
import { skinVar } from '../skin/contract.js';
import {
  NUMBER_STEPPER_GAP_PX,
  NUMBER_STEPPER_TOUCH_PX,
  NUMBER_STEPPER_VALUE_MIN_PX,
  numberStepperSlot,
  type NumberStepperSlot,
} from './attrs.js';

/** 换行（仓库口径：不写字面换行转义）。 */
const LF = String.fromCharCode(10);

/** 窄容器阈值（px）：**本件自己的宽度**（`@container` 判的，不是视口宽）。
 *  低于它时值位独占一行——两枚 ± 与值位挤一排会把数字压窄（数字是关键语义，不许被挤）。 */
const NARROW_PX = 340;

/** 按下反馈的时长（ms）：≤80ms（真按下要立刻看得见，慢过它就不像"按到了"）。 */
const PRESS_MS = 80;

/** 值位的宽度上限（px）：宽档下不跟着容器一路拉宽（否则 1000px 的空槽里数字吊在中间）。 */
const NUMBER_STEPPER_VALUE_MAX_PX = 240;

/** 本组件的样式段。恒返回非空 CSS 文本。 */
export function numberStepperCss(input?: { readonly prefix?: string }): string {
  const p = input !== undefined && input !== null
    && typeof input.prefix === 'string' && input.prefix !== '' ? input.prefix : 'ilife-';
  const root = '.' + p + 'page-ui';
  const box = root + ' .' + p + 'block-number-stepper';
  const s = (slot: NumberStepperSlot): string => root + ' .' + numberStepperSlot(slot, p);
  /** 拼在 `box` **后面**的槽类：不再带 `.<prefix>page-ui`（否则会拼出嵌套的假选择器，永远不命中）。 */
  const inBox = (slot: NumberStepperSlot): string => ' .' + numberStepperSlot(slot, p);

  return [
    '/* number-stepper（数量步进 · 形态 A「标准：加减＋常用值排」）：− n ＋ 三个可点区 ＋ 一排常用值。',
    '   层次不靠阴影与大圆角（小票纸零阴影、大字报刊零圆角）：靠发丝线、软底块与字重 ⇒ 换皮只换取值。 */',
    box + ' {',
    /* 宽度判据的落点：本件是**自己的容器**（嵌进侧栏／面板／卡片时照样按自己的宽度折行）。 */
    '  container-type: inline-size;',
    '  display: grid;',
    '  gap: 10px;',
    '  min-width: 0;',
    '  padding: 12px 14px 14px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-body') + ';',
    '  line-height: 1.5;',
    '}',
    box + ' > * {',
    '  min-width: 0;',
    '}',
    '/* 第一行：标签（左）＋ 状态字（右）。状态字是**字**这一档：小票纸与大字报刊两套皮肤里',
    '   `accent` 已接近墨色，只靠底色深浅读不出"还能不能再按"。 */',
    s('head') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: center;',
    '  justify-content: space-between;',
    '  gap: 4px 12px;',
    '  min-width: 0;',
    '}',
    s('label') + ' {',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 600;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 状态字做成一小枚带发丝线的签：**宽度锁住**（四档词长短不一，锁住就不跳版）。 */',
    s('state') + ' {',
    '  box-sizing: border-box;',
    '  min-width: 5em;',
    '  padding: 1px 6px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 700;',
    '  letter-spacing: .04em;',
    '  text-align: center;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 「− n ＋」三个可点区：**不做连体**，相邻留 ' + String(NUMBER_STEPPER_GAP_PX) + 'px 缝（防误点）。',
    '   宽档下这是一簇**靠右的紧凑控件**（值位不跟着容器一路拉宽：1000px 的空值框里数字吊在中间，',
    '   读起来不像一个控件——真机 1280 档亲眼看过才发现）；窄档改成一格一行（见下面 @container）。 */',
    s('controls') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: stretch;',
    '  justify-content: flex-end;',
    '  gap: ' + String(NUMBER_STEPPER_GAP_PX) + 'px;',
    '  min-width: 0;',
    '}',
    s('dec') + ',',
    s('inc') + ' {',
    '  flex: 0 0 auto;',
    '  display: inline-flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  box-sizing: border-box;',
    '  width: ' + String(NUMBER_STEPPER_TOUCH_PX) + 'px;',
    '  min-width: ' + String(NUMBER_STEPPER_TOUCH_PX) + 'px;',
    '  height: ' + String(NUMBER_STEPPER_TOUCH_PX) + 'px;',
    '  padding: 0;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: inherit;',
    '  font-size: ' + skinVar('fs-h2') + ';',
    '  font-weight: 700;',
    '  line-height: 1;',
    '  cursor: pointer;',
    '  touch-action: manipulation;',
    '  transition: transform ' + String(PRESS_MS) + 'ms cubic-bezier(.22,1,.36,1);',
    '}',
    '/* 值位（第三个可点区）：软底块 ＋ 等宽数字；最小宽度把整排钉住，**宽度上限**防止它在宽档里',
    '   拉成一条空槽。`flex-basis: 0` 与行内编辑器**同一条**：两者都只按剩余空间分配 ⇒ 进出编辑同宽。 */',
    s('value') + ' {',
    '  flex: 1 1 0;',
    '  max-width: ' + String(NUMBER_STEPPER_VALUE_MAX_PX) + 'px;',
    '  display: inline-flex;',
    '  align-items: baseline;',
    '  justify-content: center;',
    '  gap: 2px;',
    '  box-sizing: border-box;',
    '  min-width: ' + String(NUMBER_STEPPER_VALUE_MIN_PX) + 'px;',
    '  height: ' + String(NUMBER_STEPPER_TOUCH_PX) + 'px;',
    '  padding: 0 12px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('surface-2') + ';',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: inherit;',
    '  cursor: pointer;',
    '  touch-action: manipulation;',
    '  transition: transform ' + String(PRESS_MS) + 'ms cubic-bezier(.22,1,.36,1);',
    '}',
    s('number') + ' {',
    '  min-width: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: ' + skinVar('fs-h2') + ';',
    '  font-weight: 700;',
    '  font-variant-numeric: tabular-nums;',
    '  line-height: 1.2;',
    '  overflow-wrap: anywhere;',
    '}',
    s('unit') + ' {',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '}',
    '/* 行内编辑器（值位点开后在同一格里换上）：与值位**同盒模型**（同 flex-basis／同 min-width／同高），',
    '   进出编辑不跳版。 */',
    s('editor') + ' {',
    '  flex: 1 1 0;',
    '  box-sizing: border-box;',
    '  min-width: ' + String(NUMBER_STEPPER_VALUE_MIN_PX) + 'px;',
    '  height: ' + String(NUMBER_STEPPER_TOUCH_PX) + 'px;',
    '  padding: 0 10px;',
    '  border: 1px solid ' + skinVar('accent') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: ' + skinVar('fs-h2') + ';',
    '  font-variant-numeric: tabular-nums;',
    '  text-align: center;',
    '}',
    box + '[data-ilife-stepper-editing="1"]' + inBox('value') + ' {',
    '  display: none;',
    '}',
    '/* 常用值那一排：当前值命中哪一枚，哪一枚实心反白 ＋ 加粗（**形＋色**两样一起给）。 */',
    s('quick') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: center;',
    '  gap: ' + String(NUMBER_STEPPER_GAP_PX) + 'px;',
    '  min-width: 0;',
    '}',
    s('quickLabel') + ' {',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '}',
    s('preset') + ' {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  box-sizing: border-box;',
    '  min-width: 56px;',
    '  min-height: ' + String(NUMBER_STEPPER_TOUCH_PX) + 'px;',
    '  padding: 0 14px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-pill') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '  font-variant-numeric: tabular-nums;',
    '  cursor: pointer;',
    '  touch-action: manipulation;',
    '  transition: transform ' + String(PRESS_MS) + 'ms cubic-bezier(.22,1,.36,1);',
    '}',
    s('preset') + '[aria-pressed="true"] {',
    '  background: ' + skinVar('accent') + ';',
    '  border-color: ' + skinVar('accent') + ';',
    '  color: ' + skinVar('accent-ink') + ';',
    '  font-weight: 700;',
    '}',
    '/* 悬停：只包在设备能力查询里（`hover:hover`），且**不是唯一通路**（键盘与触屏各走各的）。 */',
    '@media (hover:hover) and (pointer:fine) {',
    '  ' + s('dec') + ':hover:not([disabled]),',
    '  ' + s('inc') + ':hover:not([disabled]) {',
    '    background: ' + skinVar('surface-2') + ';',
    '  }',
    '  ' + s('value') + ':hover:not([disabled]) {',
    '    border-color: ' + skinVar('ink-2') + ';',
    '  }',
    '  ' + s('preset') + ':hover:not([disabled]) {',
    '    border-color: ' + skinVar('ink-2') + ';',
    '  }',
    '}',
    '/* 真按下：只动 `transform`（80ms 内看得见）。 */',
    s('dec') + ':active:not([disabled]),',
    s('inc') + ':active:not([disabled]),',
    s('value') + ':active:not([disabled]),',
    s('preset') + ':active:not([disabled]) {',
    '  transform: scale(.98);',
    '}',
    '/* 可见焦点：三枚可点区与常用值都 ≥2px 描边（不许只写 `outline:none`）。 */',
    box + ' :focus-visible {',
    '  outline: 2px solid ' + skinVar('accent') + ';',
    '  outline-offset: 2px;',
    '}',
    '/* 更新中：值位与键保持原样（宽度锁住），状态字那一枚换成「更新中」；光标给 `progress`。 */',
    box + '.is-loading [aria-disabled="true"] {',
    '  cursor: progress;',
    '}',
    '/* 禁用：**说不出为什么不能动**是不许留的中间档（渲染期就要求给 `disabledReason`，写在下面那行）。 */',
    box + ' [disabled],',
    box + '.is-disabled [aria-disabled="true"] {',
    '  background: ' + skinVar('surface-2') + ';',
    '  color: ' + skinVar('ink-3') + ';',
    '  border-color: ' + skinVar('line') + ';',
    '  cursor: not-allowed;',
    '}',
    '/* 错误说明：写在控件旁边（控件 `aria-describedby` 指向它），**不只染色**。 */',
    s('error') + ' {',
    '  margin: 0;',
    '  padding-left: 8px;',
    '  border-left: 2px solid ' + skinVar('danger') + ';',
    '  color: ' + skinVar('danger') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    box + '.is-invalid' + inBox('value') + ' {',
    '  border-color: ' + skinVar('danger') + ';',
    '}',
    '/* 口径行：这一件的加减步长与取值范围怎么定的（**要读的正文**，走 ink-2 不走更浅的弱文字档）。 */',
    s('caliber') + ' {',
    '  margin: 0;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 窄容器（<' + String(NARROW_PX) + 'px）：值位独占一行——两枚 ± 与值位挤一排会把数字压窄，',
    '   而数字是关键语义（判据断它不许被挤／截）。判的是**本件自己的宽度**（不用 `@media` 判宽度）。 */',
    '@container (max-width: ' + String(NARROW_PX) + 'px) {',
    '  ' + s('controls') + ' {',
    '    display: grid;',
    '    grid-template-columns: auto minmax(0, 1fr) auto;',
    '  }',
    '  ' + s('dec') + ' {',
    '    grid-area: 1 / 1;',
    '  }',
    '  ' + s('inc') + ' {',
    '    grid-area: 1 / 3;',
    '  }',
    '  ' + s('value') + ' {',
    '    grid-area: 2 / 1 / 3 / -1;',
    '  }',
    '  ' + s('editor') + ' {',
    '    grid-area: 2 / 1 / 3 / -1;',
    '  }',
    '}',
    '/* 减动效档：不许有东西卡在半路（按下反馈走 `transition`，这里只去掉过渡本身）。 */',
    '@media (prefers-reduced-motion:reduce) {',
    '  ' + s('dec') + ',',
    '  ' + s('inc') + ',',
    '  ' + s('value') + ',',
    '  ' + s('preset') + ' {',
    '    transition: none;',
    '  }',
    '}',
  ].join(LF);
}
