/** step-flow · **样式段**（本件唯一的样式来源）。
 *
 *  三条纪律（与组件层其余件同一份）：
 *   1. 颜色／圆角／字面／字号一律经 `skinVar()` 读；本件源码里不出现手写的 `var(--ilife-…)`；
 *   2. 全部规则 scope 在 `.<prefix>page-ui` 之下；
 *   3. **三态靠「字 ＋ 形 ＋ 色」**：节点＝实心圆带 ✓／双环带内点／虚线空圈带序号；
 *      状态字＝底线／实底块／虚线框；连线＝实线（走过的）／虚线（还没走的）。
 *
 *  几何契约（钉在判据里）：节点列定宽（`STEP_FLOW_NODE_COLUMN_PX`）⇒ 逐行节点竖排在同一列；
 *  名称、状态字、估时实耗三槽各自独立、窄容器里换行不挤压；关键语义（名称／状态字／估时）不截断。
 *  本件**零动效、零可点元素**（静态件：没有可卡住的中间态，也不装作能点）。
 */
import { skinVar } from '../skin/contract.js';
import { stepFlowClass, stepFlowSlot, type StepFlowSlot } from './attrs.js';

/** 换行（仓库口径：不写字面换行转义）。 */
const LF = String.fromCharCode(10);

/** 本件的内容容器名（`@container` 按它命中）。 */
export const STEP_FLOW_CONTAINER = 'ilife-step-flow';
/** 窄档断点（px）：容器窄于它就让估时实耗掉到下一行（**不是**视口断点）。 */
export const STEP_FLOW_NARROW_MAX_PX = 440;
/** 节点直径（px）。 */
export const STEP_FLOW_NODE_SIZE_PX = 24;
/** 左列宽度（px）：节点居中在它里面，连线走它的中线。 */
export const STEP_FLOW_NODE_COLUMN_PX = 34;

/** 本组件的样式段。恒返回非空 CSS 文本。 */
export function stepFlowCss(input?: { readonly prefix?: string }): string {
  const p = input !== undefined && input !== null
    && typeof input.prefix === 'string' && input.prefix !== '' ? input.prefix : 'ilife-';
  const root = '.' + p + 'page-ui';
  /** 槽类的**裸**选择器（不带 `.page-ui` 前缀）：只用在"祖先已经由 `sc()` 给过"的嵌套选择器里——
   *  否则会拼成 `.page-ui .a .page-ui .b`（那要求 `.page-ui` 出现在件内部），永远匹配不上（实拍踩过）。 */
  const n = (name: StepFlowSlot): string => '.' + stepFlowSlot(name, p);
  const sc = (name: StepFlowSlot): string => root + ' ' + n(name);
  const s = root + ' .' + stepFlowClass(p);
  const step = sc('step');
  const v = skinVar;
  return [
    '/* step-flow（步骤条）：竖排带说明 —— 节点形状给三态，状态字带上，连线给"走到了哪"。 */',
    s + ' {',
    '  display: flex;',
    '  flex-direction: column;',
    '  min-width: 0;',
    '  container: ' + STEP_FLOW_CONTAINER + ' / inline-size;',
    '}',
    sc('head') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 4px 10px;',
    '  padding-bottom: 8px;',
    '  border-bottom: 1px solid ' + v('line') + ';',
    '}',
    sc('title') + ' {',
    '  color: ' + v('ink') + ';',
    '  font-size: ' + v('fs-sm') + ';',
    '  font-weight: 700;',
    '  overflow-wrap: anywhere;',
    '}',
    sc('count') + ' {',
    '  margin-left: auto;',
    '  color: ' + v('ink-2') + ';',
    '  font-size: ' + v('fs-xs') + ';',
    '  font-variant-numeric: tabular-nums;',
    '  white-space: nowrap;',
    '}',
    sc('list') + ' {',
    '  display: flex;',
    '  flex-direction: column;',
    '  min-width: 0;',
    '}',
    step + ' {',
    '  position: relative;',
    '  display: grid;',
    '  grid-template-columns: auto minmax(0, 1fr);',
    '  gap: 0 10px;',
    '  box-sizing: border-box;',
    '  min-width: 0;',
    '  padding: 10px 0;',
    '}',
    '/* 连线：从左列中线往下连到下一步；走过的实线、没走的虚线（线型自己就是第二样信息）。 */',
    step + ':not(:last-child)::after {',
    '  content: "";',
    '  position: absolute;',
    '  left: ' + (STEP_FLOW_NODE_COLUMN_PX / 2 - 0.5) + 'px;',
    '  top: ' + (10 + STEP_FLOW_NODE_SIZE_PX + 3) + 'px;',
    '  bottom: -2px;',
    '  width: 1px;',
    '  background: ' + v('line') + ';',
    '}',
    /* 走过的连线是**无文字的线**：走 `accent` 实底，不借正文墨色
       （口径：`docs/base/base-render/选中态与皮肤语言.md`「无文字的点／格／条」。） */
    step + '.is-done:not(:last-child)::after { background: ' + v('accent') + '; }',
    step + '.is-todo:not(:last-child)::after {',
    '  background: none;',
    '  border-left: 1px dashed ' + v('line') + ';',
    '  width: 0;',
    '}',
    sc('node') + ' {',
    '  position: relative;',
    '  display: inline-flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  box-sizing: border-box;',
    '  flex: 0 0 auto;',
    '  width: ' + STEP_FLOW_NODE_SIZE_PX + 'px;',
    '  height: ' + STEP_FLOW_NODE_SIZE_PX + 'px;',
    '  border: 1.5px dashed ' + v('line') + ';',
    '  border-radius: 50%;',
    '  background: ' + v('surface') + ';',
    '  color: ' + v('ink-3') + ';',
    '  font-family: ' + v('font-num') + ';',
    '  font-size: ' + v('fs-xs') + ';',
    '  font-weight: 700;',
    '  line-height: 1;',
    '  font-variant-numeric: tabular-nums;',
    '}',
    '/* 已完成：实心圆 ＋ ✓（**无文字的点**走主色实底；✓ 是主色底上的字色，见口径文件那四档）。 */',
    step + '.is-done ' + n('node') + ' {',
    '  border: 1.5px solid ' + v('accent') + ';',
    '  background: ' + v('accent') + ';',
    '  color: ' + v('accent-ink') + ';',
    '}',
    '/* 当前：双环 ＋ 内点（形）＋ 强一圈的边。 */',
    step + '.is-now ' + n('node') + ' {',
    '  border: 1.5px solid ' + v('accent') + ';',
    '  background: ' + v('surface') + ';',
    '  color: ' + v('accent-text') + ';',
    '}',
    step + '.is-now ' + n('node') + '::after {',
    '  content: "";',
    '  position: absolute;',
    '  inset: 4px;',
    '  border-radius: 50%;',
    '  background: ' + v('accent') + ';',
    '}',
    step + '.is-now ' + n('node') + ' { color: transparent; }',
    sc('body') + ' {',
    '  display: flex;',
    '  flex-direction: column;',
    '  min-width: 0;',
    '}',
    sc('title-row') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 4px 10px;',
    '  min-width: 0;',
    '}',
    sc('name') + ' {',
    '  min-width: 0;',
    '  color: ' + v('ink') + ';',
    '  font-size: ' + v('fs-sm') + ';',
    '  font-weight: 700;',
    '  overflow-wrap: anywhere;',
    '}',
    step + '.is-todo ' + n('name') + ' { color: ' + v('ink-2') + '; font-weight: 600; }',
    '/* 状态字三档形状：底线／实底块／虚线框。 */',
    sc('state') + ' {',
    '  flex: 0 0 auto;',
    '  box-sizing: border-box;',
    '  padding: 1px 8px;',
    '  border: 1px dashed ' + v('line') + ';',
    '  border-radius: ' + v('radius-pill') + ';',
    '  color: ' + v('ink-3') + ';',
    '  font-size: ' + v('fs-xs') + ';',
    '  font-weight: 700;',
    '  line-height: 1.5;',
    '  white-space: nowrap;',
    '}',
    sc('state') + '.is-done {',
    '  padding: 0 0 1px;',
    '  border: 0;',
    '  border-bottom: 2px solid ' + v('ok') + ';',
    '  border-radius: 0;',
    '  color: ' + v('ok') + ';',
    '}',
    sc('state') + '.is-now {',
    '  border: 0;',
    '  border-radius: ' + v('radius-pill') + ';',
    '  background: ' + v('accent') + ';',
    '  color: ' + v('accent-ink') + ';',
    '}',
    sc('time') + ' {',
    '  display: inline-flex;',
    '  flex: 0 0 auto;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 2px 10px;',
    '  margin-left: auto;',
    '  color: ' + v('ink-3') + ';',
    '  font-family: ' + v('font-num') + ';',
    '  font-size: ' + v('fs-xs') + ';',
    '  font-variant-numeric: tabular-nums;',
    '  white-space: nowrap;',
    '}',
    sc('actual') + ' { color: ' + v('ink-2') + '; font-weight: 700; }',
    sc('desc') + ' {',
    '  margin-top: 3px;',
    '  color: ' + v('ink-2') + ';',
    '  font-size: ' + v('fs-xs') + ';',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    sc('note') + ' {',
    '  margin-top: 2px;',
    '  color: ' + v('ink-3') + ';',
    '  font-size: ' + v('fs-xs') + ';',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    sc('note') + '.is-warn {',
    '  padding-left: 8px;',
    '  border-left: 3px solid ' + v('warn') + ';',
    '  color: ' + v('warn') + ';',
    '  font-weight: 700;',
    '}',
    sc('absent') + ' {',
    '  margin: 0;',
    '  padding: 10px 0 2px;',
    '  color: ' + v('ink-3') + ';',
    '  font-size: ' + v('fs-sm') + ';',
    '}',
    sc('foot') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 4px 12px;',
    '  margin-top: 10px;',
    '  padding-top: 9px;',
    '  border-top: 1px solid ' + v('line') + ';',
    '  color: ' + v('ink-2') + ';',
    '  font-size: ' + v('fs-xs') + ';',
    '}',
    '/* 窄档：估时实耗另起一行（不挤压名称与状态字）。 */',
    '@container ' + STEP_FLOW_CONTAINER + ' (max-width: ' + STEP_FLOW_NARROW_MAX_PX + 'px) {',
    '  ' + sc('time') + ' { margin-left: 0; flex: 1 1 100%; }',
    '  ' + sc('count') + ' { margin-left: 0; }',
    '}',
  ].join(LF);
}
