/** page-head · **样式段**（本件唯一的样式来源）。
 *
 *  纪律（与本节其余件同一份）：
 *   · 只经 `skinVar()` 读皮肤 —— 组件里**不写** `var(--ilife-…)`（兜底链只许住在 `skin/contract.ts`）；
 *   · 全部规则 scope 在 `.<prefix>page-ui` 之下（不开本配方的页零命中）；不写 `:root`／`!important`、不新增 token 名；
 *   · **宽度只许容器判**：布局靠 `@container` ＋ 内在尺寸 ＋ `flex-wrap`；本件不写任何 `@media`（视口宽 ≠ 组件宽）。
 *
 *  几何契约（判据钉住）：主读数 ＝ 页标题 × `PAGE_HEAD_READING_SCALE`，皮肤只给 `fs-h1` 一档 ⇒
 *  读数跟着皮肤缩放，而「读数 > 标题」「读数 ≥ 正文字号 2 倍」两条不变量在三套皮肤下都成立。
 */
import { skinVar } from '../skin/contract.js';
import { pageHeadSlot, type PageHeadSlot } from './attrs.js';

/** 换行（仓库口径：不写字面换行转义）。 */
const LF = String.fromCharCode(10);

/** **主读数相对页标题的倍数**：本形态的尺寸事实只有这一个数（样式里也只写它一处）。
 *  它同时满足两条不变量：读数 > 页标题（`2.2 > 1`）；读数 ≥ 正文的 2 倍
 *  （三套皮肤下 `2.2 × fs-h1 ÷ fs-body` ＝ 4.11／4.68／4.11，最小值仍 > 2）。 */
export const PAGE_HEAD_READING_SCALE = 2.2;

/** 窄容器阈值（px）：主读数后的附属位（单位／分母／说明）改走「另起一行」。
 *  **这是本件自己的宽度**（`@container` 判的），不是视口宽度。 */
const NARROW_PX = 420;

/** 本组件的样式段。恒返回非空 CSS 文本。 */
export function pageHeadCss(input?: { readonly prefix?: string }): string {
  const p = input !== undefined && input !== null
    && typeof input.prefix === 'string' && input.prefix !== '' ? input.prefix : 'ilife-';
  const root = '.' + p + 'page-ui';
  const box = root + ' .' + p + 'block-page-head';
  /** **槽类名**（不带 scope）：写「某槽下的子件」时只许用它。
   *  坑（本件真踩过，判据已钉住）：把带 scope 的完整选择器再拼一次，会拼出
   *  `.…-reading > .ilife-page-ui .…-value` 这种**永远不命中**的死规则——语法合法、编译不报错、
   *  屏幕上「看起来也还行」，只有把图放大看才会发现那一条根本没生效。 */
  const sc = (slot: PageHeadSlot): string => '.' + pageHeadSlot(slot, p);
  /** **带 scope 的完整选择器**（一条规则打头用）。 */
  const s = (slot: PageHeadSlot): string => root + ' ' + sc(slot);

  return [
    '/* page-head（页头 · 形态 B「读数当第二行」）：眉标（技能 · 域）／页标题／主读数大字／副题／口径行。',
    '   层次不靠阴影与大圆角（小票纸零阴影、大字报刊零圆角）：靠发丝线、字重与尺度差 ⇒ 换皮只换取值。 */',
    box + ' {',
    /* 宽度判据的落点：本件是**自己的容器**——嵌进侧栏／面板／卡片时照样按自己的宽度折行。 */
    '  container-type: inline-size;',
    '  display: grid;',
    '  gap: 8px;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-body') + ';',
    '  line-height: 1.5;',
    '}',
    '/* 第一行：眉标与页标题**同一排**（读的是「这一页叫什么」）。标题的内在宽度撑到 18ch：',
    '   容器一窄，眉标与工具位自己折到上一行——标题不被挤成一列孤字，也不掉字（不用 `…`）。 */',
    s('top') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 4px 12px;',
    '  min-width: 0;',
    '}',
    s('top') + ' > ' + sc('eyebrow') + ' {',
    '  flex: 0 1 auto;',
    '  min-width: 0;',
    '}',
    s('top') + ' > ' + sc('title') + ' {',
    '  flex: 1 1 max-content;',
    '  min-width: min(100%, 18ch);',
    '}',
    '/* 眉标：品牌位（技能名）＋ 范围位（域），两枚都能换行——**中间那条细竖线是样式画的，不是字。 */',
    s('eyebrow') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: center;',
    '  gap: 4px 8px;',
    '  margin: 0;',
    '  min-width: 0;',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 700;',
    '  line-height: 1.4;',
    '  overflow-wrap: anywhere;',
    '}',
    s('mark') + ' {',
    '  flex: none;',
    '  display: block;',
    '  width: 8px;',
    '  height: 8px;',
    '  background: ' + skinVar('accent') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '}',
    '/* 技能名走 `accent-text`（强调色的**文本**档）——`accent` 是非文本档，只许做条／边／底与大字。 */',
    s('skill') + ' {',
    '  color: ' + skinVar('accent-text') + ';',
    '  letter-spacing: .06em;',
    '  overflow-wrap: anywhere;',
    '}',
    s('domain') + ' {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  gap: 8px;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-weight: 600;',
    '  letter-spacing: .02em;',
    '  overflow-wrap: anywhere;',
    '}',
    s('domain') + '::before {',
    '  content: "";',
    '  flex: none;',
    '  display: block;',
    '  width: 1px;',
    '  height: 11px;',
    '  background: ' + skinVar('line') + ';',
    '}',
    s('title') + ' {',
    '  margin: 0;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font-display') + ';',
    '  font-size: ' + skinVar('fs-h1') + ';',
    '  font-weight: 700;',
    '  line-height: 1.15;',
    '  letter-spacing: -.01em;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 右上工具位：**只放一句读数或一枚状态字**（不放按钮——按钮归 `action-bar`）。',
    '   `margin-left:auto` 把它顶到右缘；容器窄到放不下时它自己折到下一行，不压标题。 */',
    s('tool') + ' {',
    '  flex: none;',
    '  margin-left: auto;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '  font-variant-numeric: tabular-nums;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 主读数行：本形态就靠这一行认出来——它是**页标题下面**那一行大字。 */',
    s('reading') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 4px 10px;',
    '  margin: 4px 0 0;',
    '  min-width: 0;',
    '}',
    '/* 尺寸事实只有这一个数（读数 ＝ 页标题 × ' + String(PAGE_HEAD_READING_SCALE) + '）：',
    '   皮肤只给 h1 一档 ⇒ 读数跟着皮肤一起缩放，「读数 > 标题」与「读数 ≥ 正文 2 倍」两条同时成立。 */',
    s('value') + ' {',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: calc(' + skinVar('fs-h1') + ' * ' + String(PAGE_HEAD_READING_SCALE) + ');',
    '  font-weight: 700;',
    '  line-height: 1;',
    '  letter-spacing: -.02em;',
    '  font-variant-numeric: tabular-nums;',
    '  overflow-wrap: anywhere;',
    '}',
    s('unit') + ' {',
    '  margin-left: 4px;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 600;',
    '  letter-spacing: 0;',
    '}',
    s('denominator') + ' {',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-variant-numeric: tabular-nums;',
    '  overflow-wrap: anywhere;',
    '}',
    s('note') + ' {',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 600;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 副题（时间窗／范围／条数）：逐段一枚 `span`、段间只靠列距——**标记里不写分隔符**。 */',
    s('sub') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 4px 12px;',
    '  margin: 0;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    s('sub') + ' > span {',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 口径行：这一页的数字怎么算的（一句话，可以很长）。走 `ink-2` 不走 `ink-3`：',
    '   本行是**要读的正文**，弱文字档在三套皮肤下更浅，宁可深一档。段间一条发丝线。 */',
    s('caliber') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 4px 8px;',
    '  margin: 0;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1.7;',
    '  overflow-wrap: anywhere;',
    '}',
    s('caliber') + ' > b {',
    '  flex: none;',
    '  color: ' + skinVar('ink') + ';',
    '  font-weight: 700;',
    '  letter-spacing: .06em;',
    '}',
    s('caliber') + ' > span {',
    '  padding-left: 8px;',
    '  border-left: 1px solid ' + skinVar('line') + ';',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 本件自身不带可点元素（工具位只放一句读数或一枚状态字）。这一条是**地板**：',
    '   调用方若把标题或工具位包成链接，焦点必须看得见——不许只写 `outline:none` 而不给替代。 */',
    box + ' :focus-visible {',
    '  outline: 2px solid ' + skinVar('accent') + ';',
    '  outline-offset: 2px;',
    '}',
    '/* 窄容器（<' + String(NARROW_PX) + 'px）：附属位（分母／说明）与值挤在一行会把值压窄',
    '   （分母一长最明显）⇒ **值独占一行**，分母与说明并成下一行（比「逐枚一行」省一行高度）。',
    '   判的是**本件自己的宽度**：本件会被嵌进侧栏／面板／卡片，视口宽 ≠ 组件宽（所以这里不用 `@media`）。 */',
    '@container (max-width: ' + String(NARROW_PX) + 'px) {',
    '  /* 窄容器：右上工具位排到**眉标那一排**的右端（与宽档同一个「右上角」）。',
    '     不让它插进标题与主读数之间——一插，主读数就掉到第四行，本形态的识别特征当场没了',
    '     （看图抓出来的：标题的 18ch 下限先把标题挤下去，再让工具位掉到自己那一行）。 */',
    '  ' + s('eyebrow') + ' {',
    '    order: -2;',
    '  }',
    '  ' + s('tool') + ' {',
    '    order: -1;',
    '  }',
    '  ' + s('reading') + ' {',
    '    display: grid;',
    '    grid-template-columns: auto auto;',
    '    justify-content: start;',
    '    gap: 4px 10px;',
    '  }',
    '  ' + s('reading') + ' > ' + sc('value') + ' {',
    '    grid-column: 1 / -1;',
    '  }',
    '}',
  ].join(LF);
}
