// 物品能力的路由声明（**权威源**，#800 新立）。
//
// 顺序权威只住声明里的出现序（生成器照此顺序组装 `routes.generated.ts`）。
// 变体行只收 `scenarios.yaml` 里标 `route: true` 的变体（无槽位唯一命中才进确定性路由，
// 见唤醒词层规格；`route: false` 的只由 AI 识别，不进表）。

import type { HomeRouteSpec } from '../shared/commandSpec.js';

export const ITEM_ROUTES: readonly HomeRouteSpec[] = [
  { phrase: '查物品(HTML)', key: 'home.item.search' },
  { phrase: '查物品', key: 'home.item.search' },
  { phrase: '紧急定位', key: 'home.item.search', preset: { locate: true } },
  { phrase: '筛选浏览', key: 'home.item.search', preset: { browse: true } },
  { phrase: '拍照找物品', key: 'home.item.search', preset: { photo: true } },
  { phrase: '查重复', key: 'home.item.search', preset: { dupes: true } },
  { phrase: '照片墙', key: 'home.item.search', preset: { wall: true } },
  { phrase: '搜索物品', key: 'home.item.search' },
  { phrase: '找一下物品', key: 'home.item.search' },
  { phrase: '帮我找找', key: 'home.item.search' },
  { phrase: '看看家里有啥', key: 'home.item.search' },
  { phrase: '看物品(HTML)', key: 'home.item.detail', needs: ['id'] },
  { phrase: '看物品', key: 'home.item.detail', needs: ['id'] },
  { phrase: '查看照片', key: 'home.item.detail', needs: ['id'], preset: { view: 'photos' } },
  { phrase: '历史', key: 'home.item.detail', needs: ['id'], preset: { view: 'history' } },
  { phrase: '查看物品', key: 'home.item.detail', needs: ['id'] },
  { phrase: '物品详情', key: 'home.item.detail', needs: ['id'] },
  { phrase: '录物品', key: 'home.item.add' },
  { phrase: '拍物品', key: 'home.item.add', preset: { photo: '1' } },
  { phrase: '批量录入', key: 'home.item.add', preset: { op: 'batch' } },
  { phrase: '补录', key: 'home.item.add', preset: { op: 'backfill' } },
  { phrase: '登记物品', key: 'home.item.add' },
  { phrase: '添加物品', key: 'home.item.add' },
  { phrase: '帮我记一下', key: 'home.item.add' },
  { phrase: '家里又多了个东西', key: 'home.item.add' },
  { phrase: '新到货了', key: 'home.item.add' },
  { phrase: '改物品', key: 'home.item.update', needs: ['id'] },
  { phrase: '移物品', key: 'home.item.update', needs: ['id'], preset: { op: 'move' } },
  { phrase: '补物品', key: 'home.item.update', needs: ['id'], preset: { op: 'qty' } },
  { phrase: '减物品', key: 'home.item.update', needs: ['id'], preset: { op: 'qty' } },
  { phrase: '标物品', key: 'home.item.update', needs: ['id'], preset: { op: 'tags' } },
  { phrase: '废物品', key: 'home.item.update', needs: ['id'], preset: { op: 'status' } },
  { phrase: '借物品', key: 'home.item.update', needs: ['id'], preset: { op: 'status' } },
  { phrase: '修物品', key: 'home.item.update', needs: ['id'], preset: { op: 'status' } },
  { phrase: '合并物品', key: 'home.item.update', needs: ['id'], preset: { op: 'merge' } },
  { phrase: '撤销操作', key: 'home.item.update', preset: { op: 'undo' } },
  { phrase: '物品关联', key: 'home.item.update', needs: ['id'], preset: { op: 'relate' } },
  { phrase: '管照片', key: 'home.item.update', needs: ['id'], preset: { op: 'photo' } },
  { phrase: '数量变更', key: 'home.item.update', needs: ['id'], preset: { op: 'qty' } },
  { phrase: '状态变更', key: 'home.item.update', needs: ['id'], preset: { op: 'status' } },
  { phrase: '看标签', key: 'home.tag.query' },
  { phrase: '管标签', key: 'home.tag.write', preset: { op: 'overview' } },
  { phrase: '管分类', key: 'home.tag.write', preset: { op: 'category' } },
  { phrase: '整理建议', key: 'home.tag.write', preset: { op: 'tidy' } },
  { phrase: '合标签', key: 'home.tag.write', preset: { op: 'merge' } },
  { phrase: '盘物品', key: 'home.inventory.round', preset: { op: 'round' } },
  { phrase: '盘全部', key: 'home.inventory.round', preset: { op: 'round', scope: 'all' } },
  { phrase: '盘点', key: 'home.inventory.round', preset: { op: 'round' } },
  { phrase: '差异处理', key: 'home.inventory.round', preset: { op: 'resolve' } },
  { phrase: '搬家盘点', key: 'home.inventory.round', preset: { op: 'move' } },
  { phrase: '清点物品', key: 'home.inventory.round', preset: { op: 'round' } },
  { phrase: '核对库存', key: 'home.inventory.round', preset: { op: 'round' } },
  { phrase: '数数这里', key: 'home.inventory.round', preset: { op: 'round' } },
  { phrase: '盘点记录', key: 'home.inventory.records' },
];
