/** @generated —— 由 scripts/gen-present.mjs 从 combos.yaml 生成，手改无效（构建覆盖）。
 * present 层红线：只许 string 字面量引 registry key，禁 import render。 */
export const PRESENT_KEYS: string[] = [
  'calorie.today',
  'calorie.view.home',
  'calorie.view.diet',
  'calorie.view.exercise',
  'calorie.view.goal',
  'calorie.view.goal-config',
  'calorie.view.goal-recommend',
  'calorie.view.goal-weight',
  'calorie.view.goal-progress',
  'calorie.view.goal-status',
  'calorie.view.combined',
  'calorie.view.deficit',
  'calorie.view.diet-review',
  'calorie.view.health',
  'calorie.view.ranking',
  'calorie.view.library',
  'calorie.view.search',
  'calorie.photo.list',
  'calorie.photo.detail',
  'calorie.photo.compare',
  'calorie.photo.gif',
  'calorie.help.center',
  'calorie.help.lookup',
  'calorie.history',
  'memo.search',
  'memo.detail',
  'memo.create',
  'memo.update',
  'memo.remove',
  'memo.remind',
  'memo.wish',
  'memo.sync',
  'memo.batch',
  'memo.stats',
];
