/** 本文件由 `scripts/gen-routes.mjs` 生成，勿手改（`pnpm gen` 重生成，`pnpm gen:check` 验真）。
 *
 * 权威是声明层：`src/cli/legacy/routes/scene-NN.ts`（未搬迁清单，一场景一件）与各能力
 * `src/<能力>/routes.ts`（已搬迁键，一能力一件）。本件只做「按 `list` 分组、按 `order` 升序」的
 * 排序与拼接，不含任何顺序知识——顺序事实只住声明的 `order` 字段，换文件搬动不会打乱顺序。
 * 本次生成：WAKE_ROUTES 436 条 ＋ NEW_KEY_ROUTES 69 条 ＋ COVERAGE_REPAIR_ROUTES 1 条，合计 506 条（与声明逐条自洽：`pnpm gen:check` 验真）。
 */
import type { ExecWakeRoute, WakeRoute } from './routeSpec.js';

/** 436 条 SoT 唤醒词路由（exec ／ non-exec 两种记录；顺序与 SoT 逐位对齐） */
export const WAKE_ROUTES: readonly WakeRoute[] = [
  { wakeWord: '看今日主页', scene: '01', kind: 'exec', key: 'calorie.view.home', cli: 'calorie-cmd-read calorie.view.home --params \'{"date":"今日","section":"overview"}\'' },
  { wakeWord: '看今日饮食概览', scene: '01', kind: 'exec', key: 'calorie.view.diet', cli: 'calorie-cmd-read calorie.view.diet --params \'{"window":"今日"}\'' },
  { wakeWord: '看今日运动概览', scene: '01', kind: 'exec', key: 'calorie.view.exercise', cli: 'calorie-cmd-read calorie.view.exercise --params \'{"window":"今日"}\'' },
  { wakeWord: '看今日体重概览', scene: '01', kind: 'exec', key: 'calorie.view.weight', cli: 'calorie-cmd-read calorie.view.weight' },
  { wakeWord: '看今日目标进度', scene: '01', kind: 'exec', key: 'calorie.view.goal-progress', cli: 'calorie-cmd-read calorie.view.goal-progress --params \'{"window":"今日"}\'' },
  { wakeWord: '看本周主页', scene: '01', kind: 'exec', key: 'calorie.view.home', cli: 'calorie-cmd-read calorie.view.home --params \'{"windowDays":7,"date":"今日","section":"week"}\'' },
  { wakeWord: '看本月主页', scene: '01', kind: 'exec', key: 'calorie.view.home', cli: 'calorie-cmd-read calorie.view.home --params \'{"windowDays":30,"date":"今日","section":"month"}\'' },
  { wakeWord: '看连续记录天数', scene: '01', kind: 'exec', key: 'calorie.view.home', cli: 'calorie-cmd-read calorie.view.home --params \'{"date":"今日","section":"streak"}\'' },
  { wakeWord: '看今日热量预算', scene: '01', kind: 'exec', key: 'calorie.view.home', cli: 'calorie-cmd-read calorie.view.home --params \'{"date":"今日","section":"budget"}\'' },
  { wakeWord: '记一餐', scene: '02', kind: 'exec', key: 'calorie.diet.add', cli: 'calorie-cmd-read calorie.diet.add --params \'{"foodName":"鸡胸","calories":200,"protein":35}\'' },
  { wakeWord: '记一餐（含备注）', scene: '02', kind: 'exec', key: 'calorie.diet.add', cli: 'calorie-cmd-read calorie.diet.add --params \'{"foodName":"鸡胸","calories":200,"protein":35,"note":"加了辣酱"}\'' },
  { wakeWord: '补记饮食', scene: '02', kind: 'exec', key: 'calorie.diet.add', cli: 'calorie-cmd-read calorie.diet.add --params \'{"foodName":"米饭","calories":500,"protein":10,"time":"12:30:00","date":"<日期>"}\'' },
  { wakeWord: '批量补记饮食', scene: '02', kind: 'exec', key: 'calorie.diet.batch', cli: 'calorie-cmd-read calorie.diet.batch --params \'{"items":[{"foodName":"粥","calories":150,"protein":3,"date":"<日期>"}]}\'' },
  { wakeWord: '拍营养表记一餐', scene: '02', kind: 'exec', key: 'calorie.diet.add', cli: 'calorie-cmd-read calorie.diet.add --params \'{"foodName":"鸡胸","calories":200,"protein":35,"note":"营养表识别","source":"photo"}\'' },
  { wakeWord: '拍营养表补记一餐', scene: '02', kind: 'exec', key: 'calorie.diet.add', cli: 'calorie-cmd-read calorie.diet.add --params \'{"foodName":"米饭","calories":500,"protein":10,"date":"<日期>","time":"12:30:00","note":"营养表补记","source":"photo"}\'' },
  { wakeWord: '记喝水', scene: '02', kind: 'exec', key: 'calorie.water.log', cli: 'calorie-cmd-read calorie.water.log --params \'{"ml":300}\'' },
  { wakeWord: '复制昨日饮食', scene: '02', kind: 'exec', key: 'calorie.diet.copy', cli: 'calorie-cmd-read calorie.diet.copy --params \'{"from":"<日期>"}\'' },
  { wakeWord: '改饮食记录', scene: '02', kind: 'exec', key: 'calorie.diet.update', cli: 'calorie-cmd-read calorie.diet.update --params \'{"id":1,"grams":150}\'' },
  { wakeWord: '改某日饮食', scene: '02', kind: 'exec', key: 'calorie.diet.update-by-date', cli: 'calorie-cmd-read calorie.diet.update-by-date --params \'{"note":"食堂","date":"<日期>"}\'' },
  { wakeWord: '删饮食记录', scene: '02', kind: 'exec', key: 'calorie.diet.remove', cli: 'calorie-cmd-read calorie.diet.remove --params \'{"id":1}\'' },
  { wakeWord: '删一餐', scene: '02', kind: 'exec', key: 'calorie.diet.remove-by-type', cli: 'calorie-cmd-read calorie.diet.remove-by-type --params \'{"mealType":"早餐","date":"<日期>"}\'' },
  { wakeWord: '删某日饮食', scene: '02', kind: 'exec', key: 'calorie.diet.remove-by-date', cli: 'calorie-cmd-read calorie.diet.remove-by-date --params \'{"date":"<日期>"}\'' },
  { wakeWord: '批量删饮食', scene: '02', kind: 'exec', key: 'calorie.diet.remove-by-range', cli: 'calorie-cmd-read calorie.diet.remove-by-range --params \'{"start":"<日期>","end":"<日期>"}\'' },
  { wakeWord: '看今日饮食', scene: '02', kind: 'exec', key: 'calorie.today', cli: 'calorie-cmd-read calorie.today --params \'{"date":"今日"}\'' },
  { wakeWord: '看昨日饮食', scene: '02', kind: 'exec', key: 'calorie.view.diet', cli: 'calorie-cmd-read calorie.view.diet --params \'{"window":"昨日"}\'' },
  { wakeWord: '看本周饮食', scene: '02', kind: 'exec', key: 'calorie.view.diet', cli: 'calorie-cmd-read calorie.view.diet --params \'{"window":"本周"}\'' },
  { wakeWord: '看上周饮食', scene: '02', kind: 'exec', key: 'calorie.view.diet', cli: 'calorie-cmd-read calorie.view.diet --params \'{"window":"上周"}\'' },
  { wakeWord: '看本月饮食', scene: '02', kind: 'exec', key: 'calorie.view.diet', cli: 'calorie-cmd-read calorie.view.diet --params \'{"window":"本月"}\'' },
  { wakeWord: '看上月饮食', scene: '02', kind: 'exec', key: 'calorie.view.diet', cli: 'calorie-cmd-read calorie.view.diet --params \'{"window":"上月"}\'' },
  { wakeWord: '看最近 7 天饮食', scene: '02', kind: 'exec', key: 'calorie.view.diet', cli: 'calorie-cmd-read calorie.view.diet --params \'{"window":"7d"}\'' },
  { wakeWord: '看最近 30 天饮食', scene: '02', kind: 'exec', key: 'calorie.view.diet', cli: 'calorie-cmd-read calorie.view.diet --params \'{"window":"30d"}\'' },
  { wakeWord: '看某段时间饮食', scene: '02', kind: 'exec', key: 'calorie.view.diet', cli: 'calorie-cmd-read calorie.view.diet --params \'{"window":"custom","start":"<开始日期>","end":"<结束日期>"}\'' },
  { wakeWord: '看今日喝水', scene: '02', kind: 'exec', key: 'calorie.view.today-water', cli: 'calorie-cmd-read calorie.view.today-water --params \'{"date":"今日","entry":"drink"}\'' },
  { wakeWord: '看有备注的饮食记录', scene: '02', kind: 'exec', key: 'calorie.today', cli: 'calorie-cmd-read calorie.today --params \'{"date":"今日","hasNote":true}\'' },
  { wakeWord: '查食品', scene: '02', kind: 'exec', key: 'calorie.view.search', cli: 'calorie-cmd-read calorie.view.search --params \'{"keyword":"鸡胸"}\'' },
  { wakeWord: '查食品（按分类）', scene: '02', kind: 'exec', key: 'calorie.view.library', cli: 'calorie-cmd-read calorie.view.library --params \'{"category":"蛋白类"}\'' },
  { wakeWord: '存食品', scene: '02', kind: 'exec', key: 'calorie.product.add', cli: 'calorie-cmd-read calorie.product.add --params \'{"productName":"鸡胸肉","calories":165,"protein":31,"fat":3.6,"carbohydrates":0,"sodium":70}\'' },
  { wakeWord: '改食品', scene: '02', kind: 'exec', key: 'calorie.product.update', cli: 'calorie-cmd-read calorie.product.update --params \'{"id":1,"note":"新版"}\'' },
  { wakeWord: '下架食品', scene: '02', kind: 'exec', key: 'calorie.product.deprecate', cli: 'calorie-cmd-read calorie.product.deprecate --params \'{"id":1}\'' },
  { wakeWord: '看食品库（去重）', scene: '02', kind: 'exec', key: 'calorie.view.dedupe', cli: 'calorie-cmd-read calorie.view.dedupe' },
  { wakeWord: '批量导入食品', scene: '02', kind: 'exec', key: 'calorie.product.import', cli: 'calorie-cmd-read calorie.product.import --params \'{"items":[{"productName":"测试导入燕麦","calories":389,"protein":13,"fat":7,"carbohydrates":66,"sodium":5}]}\'' },
  { wakeWord: '校验批量导入', scene: '02', kind: 'exec', key: 'calorie.view.batch-import-preview', cli: 'calorie-cmd-read calorie.view.batch-import-preview --params \'{"items":[{"foodName":"粥","calories":150,"protein":3}]}\'' },
  { wakeWord: '看食品来源统计', scene: '02', kind: 'exec', key: 'calorie.view.source-stats', cli: 'calorie-cmd-read calorie.view.source-stats' },
  { wakeWord: '看营养结构', scene: '02', kind: 'exec', key: 'calorie.view.diet-review', cli: 'calorie-cmd-read calorie.view.diet-review --params \'{"window":"7d"}\'' },
  { wakeWord: '看今日营养', scene: '02', kind: 'exec', key: 'calorie.view.diet-review', cli: 'calorie-cmd-read calorie.view.diet-review --params \'{"window":"今日"}\'' },
  { wakeWord: '看饮食总览', scene: '02', kind: 'exec', key: 'calorie.view.diet', cli: 'calorie-cmd-read calorie.view.diet --params \'{"window":"7d"}\'' },
  { wakeWord: '看营养素深度', scene: '02', kind: 'exec', key: 'calorie.view.nutrition-detail', cli: 'calorie-cmd-read calorie.view.nutrition-detail --params \'{"window":"7d"}\'' },
  { wakeWord: '看高热量榜', scene: '02', kind: 'exec', key: 'calorie.view.ranking', cli: 'calorie-cmd-read calorie.view.ranking --params \'{"category":"high_calorie","topN":10,"window":"7d"}\'' },
  { wakeWord: '看低热量榜', scene: '02', kind: 'exec', key: 'calorie.view.ranking', cli: 'calorie-cmd-read calorie.view.ranking --params \'{"category":"low_calorie","topN":10,"window":"7d"}\'' },
  { wakeWord: '看频繁吃榜', scene: '02', kind: 'exec', key: 'calorie.view.ranking', cli: 'calorie-cmd-read calorie.view.ranking --params \'{"category":"frequent","topN":10,"window":"7d"}\'' },
  { wakeWord: '看高碳水榜', scene: '02', kind: 'exec', key: 'calorie.view.ranking', cli: 'calorie-cmd-read calorie.view.ranking --params \'{"category":"high_carb","topN":10,"window":"7d"}\'' },
  { wakeWord: '看高蛋白榜', scene: '02', kind: 'exec', key: 'calorie.view.ranking', cli: 'calorie-cmd-read calorie.view.ranking --params \'{"category":"high_protein","topN":10,"window":"7d"}\'' },
  { wakeWord: '看全部排行榜', scene: '02', kind: 'exec', key: 'calorie.view.ranking', cli: 'calorie-cmd-read calorie.view.ranking --params \'{"topN":10,"window":"7d"}\'' },
  { wakeWord: '看高热量榜（最近 30 天）', scene: '02', kind: 'exec', key: 'calorie.view.ranking', cli: 'calorie-cmd-read calorie.view.ranking --params \'{"category":"high_calorie","topN":10,"window":"30d"}\'' },
  { wakeWord: '看高热量榜（本月）', scene: '02', kind: 'exec', key: 'calorie.view.ranking', cli: 'calorie-cmd-read calorie.view.ranking --params \'{"category":"high_calorie","topN":10,"window":"本月"}\'' },
  { wakeWord: '看高热量榜（自定义）', scene: '02', kind: 'exec', key: 'calorie.view.ranking', cli: 'calorie-cmd-read calorie.view.ranking --params \'{"category":"high_calorie","topN":10,"window":"custom","start":"<开始日期>","end":"<结束日期>"}\'' },
  { wakeWord: '看低热量榜（最近 30 天）', scene: '02', kind: 'exec', key: 'calorie.view.ranking', cli: 'calorie-cmd-read calorie.view.ranking --params \'{"category":"low_calorie","topN":10,"window":"30d"}\'' },
  { wakeWord: '看低热量榜（本月）', scene: '02', kind: 'exec', key: 'calorie.view.ranking', cli: 'calorie-cmd-read calorie.view.ranking --params \'{"category":"low_calorie","topN":10,"window":"本月"}\'' },
  { wakeWord: '看低热量榜（自定义）', scene: '02', kind: 'exec', key: 'calorie.view.ranking', cli: 'calorie-cmd-read calorie.view.ranking --params \'{"category":"low_calorie","topN":10,"window":"custom","start":"<开始日期>","end":"<结束日期>"}\'' },
  { wakeWord: '看频繁吃榜（最近 30 天）', scene: '02', kind: 'exec', key: 'calorie.view.ranking', cli: 'calorie-cmd-read calorie.view.ranking --params \'{"category":"frequent","topN":10,"window":"30d"}\'' },
  { wakeWord: '看频繁吃榜（本月）', scene: '02', kind: 'exec', key: 'calorie.view.ranking', cli: 'calorie-cmd-read calorie.view.ranking --params \'{"category":"frequent","topN":10,"window":"本月"}\'' },
  { wakeWord: '看频繁吃榜（自定义）', scene: '02', kind: 'exec', key: 'calorie.view.ranking', cli: 'calorie-cmd-read calorie.view.ranking --params \'{"category":"frequent","topN":10,"window":"custom","start":"<开始日期>","end":"<结束日期>"}\'' },
  { wakeWord: '看高碳水榜（最近 30 天）', scene: '02', kind: 'exec', key: 'calorie.view.ranking', cli: 'calorie-cmd-read calorie.view.ranking --params \'{"category":"high_carb","topN":10,"window":"30d"}\'' },
  { wakeWord: '看高碳水榜（本月）', scene: '02', kind: 'exec', key: 'calorie.view.ranking', cli: 'calorie-cmd-read calorie.view.ranking --params \'{"category":"high_carb","topN":10,"window":"本月"}\'' },
  { wakeWord: '看高碳水榜（自定义）', scene: '02', kind: 'exec', key: 'calorie.view.ranking', cli: 'calorie-cmd-read calorie.view.ranking --params \'{"category":"high_carb","topN":10,"window":"custom","start":"<开始日期>","end":"<结束日期>"}\'' },
  { wakeWord: '看高蛋白榜（最近 30 天）', scene: '02', kind: 'exec', key: 'calorie.view.ranking', cli: 'calorie-cmd-read calorie.view.ranking --params \'{"category":"high_protein","topN":10,"window":"30d"}\'' },
  { wakeWord: '看高蛋白榜（本月）', scene: '02', kind: 'exec', key: 'calorie.view.ranking', cli: 'calorie-cmd-read calorie.view.ranking --params \'{"category":"high_protein","topN":10,"window":"本月"}\'' },
  { wakeWord: '看高蛋白榜（自定义）', scene: '02', kind: 'exec', key: 'calorie.view.ranking', cli: 'calorie-cmd-read calorie.view.ranking --params \'{"category":"high_protein","topN":10,"window":"custom","start":"<开始日期>","end":"<结束日期>"}\'' },
  { wakeWord: '饮食复盘（本周）', scene: '02', kind: 'exec', key: 'calorie.view.diet-review', cli: 'calorie-cmd-read calorie.view.diet-review --params \'{"window":"本周"}\'' },
  { wakeWord: '饮食复盘（本月）', scene: '02', kind: 'exec', key: 'calorie.view.diet-review', cli: 'calorie-cmd-read calorie.view.diet-review --params \'{"window":"本月"}\'' },
  { wakeWord: '饮食复盘（最近 90 天）', scene: '02', kind: 'exec', key: 'calorie.view.diet-review', cli: 'calorie-cmd-read calorie.view.diet-review --params \'{"window":"90d"}\'' },
  { wakeWord: '饮食复盘（今年）', scene: '02', kind: 'exec', key: 'calorie.view.diet-review', cli: 'calorie-cmd-read calorie.view.diet-review --params \'{"window":"今年"}\'' },
  { wakeWord: '饮食复盘（自定义时间）', scene: '02', kind: 'exec', key: 'calorie.view.diet-review', cli: 'calorie-cmd-read calorie.view.diet-review --params \'{"window":"custom","start":"<开始日期>","end":"<结束日期>"}\'' },
  { wakeWord: '看早餐（最近 7 天）', scene: '02', kind: 'exec', key: 'calorie.view.diet', cli: 'calorie-cmd-read calorie.view.diet --params \'{"window":"7d"}\'' },
  { wakeWord: '看午餐（最近 7 天）', scene: '02', kind: 'exec', key: 'calorie.view.diet', cli: 'calorie-cmd-read calorie.view.diet --params \'{"window":"7d"}\'' },
  { wakeWord: '看晚餐（最近 7 天）', scene: '02', kind: 'exec', key: 'calorie.view.diet', cli: 'calorie-cmd-read calorie.view.diet --params \'{"window":"7d"}\'' },
  { wakeWord: '看加餐（最近 7 天）', scene: '02', kind: 'exec', key: 'calorie.view.diet', cli: 'calorie-cmd-read calorie.view.diet --params \'{"window":"7d"}\'' },
  { wakeWord: '看全部餐别分布（最近 7 天）', scene: '02', kind: 'exec', key: 'calorie.view.diet', cli: 'calorie-cmd-read calorie.view.diet --params \'{"window":"7d"}\'' },
  { wakeWord: '看「有备注」的饮食记录', scene: '02', kind: 'exec', key: 'calorie.today', cli: 'calorie-cmd-read calorie.today --params \'{"date":"今日","hasNote":true}\'' },
  { wakeWord: '记体重', scene: '03', kind: 'exec', key: 'calorie.weight.log', cli: 'calorie-cmd-read calorie.weight.log --params \'{"kg":70.5}\'' },
  { wakeWord: '记体重（含备注）', scene: '03', kind: 'exec', key: 'calorie.weight.log', cli: 'calorie-cmd-read calorie.weight.log --params \'{"kg":70.5,"note":"晨起空腹"}\'' },
  { wakeWord: '补录体重', scene: '03', kind: 'exec', key: 'calorie.weight.log', cli: 'calorie-cmd-read calorie.weight.log --params \'{"kg":70.5,"date":"<日期>"}\'' },
  { wakeWord: '批量补录体重', scene: '03', kind: 'exec', key: 'calorie.weight.batch', cli: 'calorie-cmd-read calorie.weight.batch --params \'{"items":[{"date":"<日期>","kg":70.5}]}\'' },
  { wakeWord: '看今日体重', scene: '03', kind: 'exec', key: 'calorie.view.weight', cli: 'calorie-cmd-read calorie.view.weight --params \'{"window":"今日"}\'' },
  { wakeWord: '改体重记录', scene: '03', kind: 'exec', key: 'calorie.weight.update', cli: 'calorie-cmd-read calorie.weight.update --params \'{"id":1,"kg":70.2}\'' },
  { wakeWord: '改某日体重', scene: '03', kind: 'exec', key: 'calorie.weight.update', cli: 'calorie-cmd-read calorie.weight.update --params \'{"kg":70.2,"date":"<日期>"}\'' },
  { wakeWord: '删体重记录', scene: '03', kind: 'exec', key: 'calorie.weight.remove', cli: 'calorie-cmd-read calorie.weight.remove --params \'{"id":1}\'' },
  { wakeWord: '删某日体重', scene: '03', kind: 'exec', key: 'calorie.weight.remove', cli: 'calorie-cmd-read calorie.weight.remove --params \'{"date":"<日期>"}\'' },
  { wakeWord: '批量删体重', scene: '03', kind: 'exec', key: 'calorie.weight.remove', cli: 'calorie-cmd-read calorie.weight.remove --params \'{"start":"<日期>","end":"<日期>"}\'' },
  { wakeWord: '看本周体重', scene: '03', kind: 'exec', key: 'calorie.view.weight-history', cli: 'calorie-cmd-read calorie.view.weight-history --params \'{"window":"本周"}\'' },
  { wakeWord: '看上周体重', scene: '03', kind: 'exec', key: 'calorie.view.weight-history', cli: 'calorie-cmd-read calorie.view.weight-history --params \'{"window":"上周"}\'' },
  { wakeWord: '看本月体重', scene: '03', kind: 'exec', key: 'calorie.view.weight-history', cli: 'calorie-cmd-read calorie.view.weight-history --params \'{"window":"本月"}\'' },
  { wakeWord: '看上月体重', scene: '03', kind: 'exec', key: 'calorie.view.weight-history', cli: 'calorie-cmd-read calorie.view.weight-history --params \'{"window":"上月"}\'' },
  { wakeWord: '看最近 7 天体重', scene: '03', kind: 'exec', key: 'calorie.view.weight-history', cli: 'calorie-cmd-read calorie.view.weight-history --params \'{"window":"7d"}\'' },
  { wakeWord: '看最近 90 天体重', scene: '03', kind: 'exec', key: 'calorie.view.weight-history', cli: 'calorie-cmd-read calorie.view.weight-history --params \'{"window":"90d"}\'' },
  { wakeWord: '看某段时间体重', scene: '03', kind: 'exec', key: 'calorie.view.weight-history', cli: 'calorie-cmd-read calorie.view.weight-history --params \'{"window":"custom","start":"<开始日期>","end":"<结束日期>"}\'' },
  { wakeWord: '看体重曲线', scene: '03', kind: 'exec', key: 'calorie.view.weight-history', cli: 'calorie-cmd-read calorie.view.weight-history --params \'{"window":"30d"}\'' },
  { wakeWord: '看体重曲线（带目标）', scene: '03', kind: 'exec', key: 'calorie.view.weight-history', cli: 'calorie-cmd-read calorie.view.weight-history --params \'{"window":"30d","overlay":"target"}\'' },
  { wakeWord: '看体重曲线（带里程碑）', scene: '03', kind: 'exec', key: 'calorie.view.weight-history', cli: 'calorie-cmd-read calorie.view.weight-history --params \'{"window":"30d","overlay":"milestone"}\'' },
  { wakeWord: '看体重曲线（带异常点）', scene: '03', kind: 'exec', key: 'calorie.view.weight-history', cli: 'calorie-cmd-read calorie.view.weight-history --params \'{"window":"30d","overlay":"anomaly"}\'' },
  { wakeWord: '看本月体重曲线', scene: '03', kind: 'exec', key: 'calorie.view.weight-history', cli: 'calorie-cmd-read calorie.view.weight-history --params \'{"window":"本月"}\'' },
  { wakeWord: '看上月体重曲线', scene: '03', kind: 'exec', key: 'calorie.view.weight-history', cli: 'calorie-cmd-read calorie.view.weight-history --params \'{"window":"上月"}\'' },
  { wakeWord: '看最近 90 天体重曲线', scene: '03', kind: 'exec', key: 'calorie.view.weight-history', cli: 'calorie-cmd-read calorie.view.weight-history --params \'{"window":"90d"}\'' },
  { wakeWord: '看最近 180 天体重曲线', scene: '03', kind: 'exec', key: 'calorie.view.weight-history', cli: 'calorie-cmd-read calorie.view.weight-history --params \'{"window":"180d"}\'' },
  { wakeWord: '看最近 365 天体重曲线', scene: '03', kind: 'exec', key: 'calorie.view.weight-history', cli: 'calorie-cmd-read calorie.view.weight-history --params \'{"window":"365d"}\'' },
  { wakeWord: '看某段时间体重曲线', scene: '03', kind: 'exec', key: 'calorie.view.weight-history', cli: 'calorie-cmd-read calorie.view.weight-history --params \'{"window":"custom","start":"<开始日期>","end":"<结束日期>"}\'' },
  { wakeWord: '看体重稳不稳（增强版）', scene: '03', kind: 'exec', key: 'calorie.view.volatility', cli: 'calorie-cmd-read calorie.view.volatility --params \'{"window":"7d"}\'' },
  { wakeWord: '看本月波动', scene: '03', kind: 'exec', key: 'calorie.view.volatility', cli: 'calorie-cmd-read calorie.view.volatility --params \'{"window":"本月"}\'' },
  { wakeWord: '看最近 90 天波动', scene: '03', kind: 'exec', key: 'calorie.view.volatility', cli: 'calorie-cmd-read calorie.view.volatility --params \'{"window":"90d"}\'' },
  { wakeWord: '看最近 180 天波动', scene: '03', kind: 'exec', key: 'calorie.view.volatility', cli: 'calorie-cmd-read calorie.view.volatility --params \'{"window":"180d"}\'' },
  { wakeWord: '看波动异常点', scene: '03', kind: 'exec', key: 'calorie.view.volatility', cli: 'calorie-cmd-read calorie.view.volatility --params \'{"window":"7d"}\'' },
  { wakeWord: '看「有备注」的体重记录', scene: '03', kind: 'exec', key: 'calorie.view.weight-history', cli: 'calorie-cmd-read calorie.view.weight-history --params \'{"window":"30d","noteOnly":true}\'' },
  { wakeWord: '对比体重：最近 30 天 vs 之前 30 天', scene: '03', kind: 'exec', key: 'calorie.view.weight-compare', cli: 'calorie-cmd-read calorie.view.weight-compare --params \'{"window":"30d","compareWindow":"prev"}\'' },
  { wakeWord: '对比体重：自定义两段时间', scene: '03', kind: 'exec', key: 'calorie.view.weight-compare', cli: 'calorie-cmd-read calorie.view.weight-compare --params \'{"window":"custom","start":"<开始日期>","end":"<结束日期>","compareWindow":"custom","compareStart":"<对比开始日期>","compareEnd":"<对比结束日期>"}\'' },
  { wakeWord: '对比体重：本周 vs 上周', scene: '03', kind: 'exec', key: 'calorie.view.weight-compare', cli: 'calorie-cmd-read calorie.view.weight-compare --params \'{"window":"本周","compareWindow":"上周"}\'' },
  { wakeWord: '对比体重：本月 vs 上月', scene: '03', kind: 'exec', key: 'calorie.view.weight-compare', cli: 'calorie-cmd-read calorie.view.weight-compare --params \'{"window":"本月","compareWindow":"上月"}\'' },
  { wakeWord: '对比体重：近 N 天 vs 上一个 N 天', scene: '03', kind: 'exec', key: 'calorie.view.weight-compare', cli: 'calorie-cmd-read calorie.view.weight-compare --params \'{"window":"7d","compareWindow":"prev"}\'' },
  { wakeWord: '对比体重：今天 vs 一年前今天', scene: '03', kind: 'exec', key: 'calorie.view.weight-compare', cli: 'calorie-cmd-read calorie.view.weight-compare --params \'{"window":"今日","compareWindow":"今日","compareOffset":"-1y"}\'' },
  { wakeWord: '对比体重：今天 vs 半年前今天', scene: '03', kind: 'exec', key: 'calorie.view.weight-compare', cli: 'calorie-cmd-read calorie.view.weight-compare --params \'{"window":"今日","compareWindow":"今日","compareOffset":"-6m"}\'' },
  { wakeWord: '对比体重：今天 vs 三月前今天', scene: '03', kind: 'exec', key: 'calorie.view.weight-compare', cli: 'calorie-cmd-read calorie.view.weight-compare --params \'{"window":"今日","compareWindow":"今日","compareOffset":"-3m"}\'' },
  { wakeWord: '对比体重：当前 vs 目标体重', scene: '03', kind: 'exec', key: 'calorie.view.goal-weight', cli: 'calorie-cmd-read calorie.view.goal-weight --params \'{"window":"30d"}\'' },
  { wakeWord: '对比体重：当前 vs 平台期首日', scene: '03', kind: 'exec', key: 'calorie.view.weight-compare', cli: 'calorie-cmd-read calorie.view.weight-compare --params \'{"scenario":"b8"}\'' },
  { wakeWord: '对比体重：当前 vs 历史最低', scene: '03', kind: 'exec', key: 'calorie.view.weight-compare', cli: 'calorie-cmd-read calorie.view.weight-compare --params \'{"scenario":"e1"}\'' },
  { wakeWord: '对比体重：当前 vs 历史最高', scene: '03', kind: 'exec', key: 'calorie.view.weight-compare', cli: 'calorie-cmd-read calorie.view.weight-compare --params \'{"scenario":"e2"}\'' },
  { wakeWord: '对比体重：减重 5kg 那天 vs 今天', scene: '03', kind: 'exec', key: 'calorie.view.weight-compare', cli: 'calorie-cmd-read calorie.view.weight-compare --params \'{"scenario":"e3","delta":5}\'' },
  { wakeWord: '对比体重：减重 10kg 那天 vs 今天', scene: '03', kind: 'exec', key: 'calorie.view.weight-compare', cli: 'calorie-cmd-read calorie.view.weight-compare --params \'{"scenario":"e3","delta":10}\'' },
  { wakeWord: '对比体重：当前 vs 入夏最低', scene: '03', kind: 'exec', key: 'calorie.view.weight-compare', cli: 'calorie-cmd-read calorie.view.weight-compare --params \'{"scenario":"e5"}\'' },
  { wakeWord: '对比体重：当前 vs 入冬最低', scene: '03', kind: 'exec', key: 'calorie.view.weight-compare', cli: 'calorie-cmd-read calorie.view.weight-compare --params \'{"scenario":"e6"}\'' },
  { wakeWord: '对比体重：运动多 vs 运动少的两个月', scene: '03', kind: 'exec', key: 'calorie.view.weight-compare', cli: 'calorie-cmd-read calorie.view.weight-compare --params \'{"scenario":"c5"}\'' },
  { wakeWord: '对比体重：工作日 vs 周末', scene: '03', kind: 'exec', key: 'calorie.view.weight-compare', cli: 'calorie-cmd-read calorie.view.weight-compare --params \'{"window":"工作日","compareWindow":"周末"}\'' },
  { wakeWord: '看体重总览', scene: '03', kind: 'exec', key: 'calorie.view.weight', cli: 'calorie-cmd-read calorie.view.weight --params \'{"window":"30d"}\'' },
  { wakeWord: '体重复盘（本周）', scene: '03', kind: 'exec', key: 'calorie.view.weight-review', cli: 'calorie-cmd-read calorie.view.weight-review --params \'{"window":"本周"}\'' },
  { wakeWord: '体重复盘（本月）', scene: '03', kind: 'exec', key: 'calorie.view.weight-review', cli: 'calorie-cmd-read calorie.view.weight-review --params \'{"window":"本月"}\'' },
  { wakeWord: '体重复盘（最近 90 天）', scene: '03', kind: 'exec', key: 'calorie.view.weight-review', cli: 'calorie-cmd-read calorie.view.weight-review --params \'{"window":"90d"}\'' },
  { wakeWord: '体重复盘（今年）', scene: '03', kind: 'exec', key: 'calorie.view.weight-review', cli: 'calorie-cmd-read calorie.view.weight-review --params \'{"window":"今年"}\'' },
  { wakeWord: '体重复盘（自定义时间）', scene: '03', kind: 'exec', key: 'calorie.view.weight-review', cli: 'calorie-cmd-read calorie.view.weight-review --params \'{"window":"custom","start":"<开始日期>","end":"<结束日期>"}\'' },
  { wakeWord: '看里程碑回溯', scene: '03', kind: 'exec', key: 'calorie.view.weight-review', cli: 'calorie-cmd-read calorie.view.weight-review --params \'{"mode":"milestones"}\'' },
  { wakeWord: '记运动', scene: '04', kind: 'exec', key: 'calorie.exercise.add', cli: 'calorie-cmd-read calorie.exercise.add --params \'{"type":"慢跑","calories":320,"minutes":30}\'' },
  { wakeWord: '记运动（含备注）', scene: '04', kind: 'exec', key: 'calorie.exercise.add', cli: 'calorie-cmd-read calorie.exercise.add --params \'{"type":"慢跑","calories":320,"minutes":30,"note":"夜跑"}\'' },
  { wakeWord: '记力量训练', scene: '04', kind: 'exec', key: 'calorie.exercise.add', cli: 'calorie-cmd-read calorie.exercise.add --params \'{"type":"卧推","calories":150,"category":"力量","loadKg":60,"reps":10}\'' },
  { wakeWord: '记有氧运动', scene: '04', kind: 'exec', key: 'calorie.exercise.add', cli: 'calorie-cmd-read calorie.exercise.add --params \'{"type":"户外跑","calories":300,"minutes":30,"category":"有氧","distance":5}\'' },
  { wakeWord: '记日常活动', scene: '04', kind: 'exec', key: 'calorie.exercise.add', cli: 'calorie-cmd-read calorie.exercise.add --params \'{"type":"步行","calories":80,"minutes":20,"category":"日常","steps":3000}\'' },
  { wakeWord: '补记运动', scene: '04', kind: 'exec', key: 'calorie.exercise.add', cli: 'calorie-cmd-read calorie.exercise.add --params \'{"type":"慢跑","calories":320,"minutes":30,"date":"<日期>"}\'' },
  { wakeWord: '批量补记运动', scene: '04', kind: 'exec', key: 'calorie.exercise.add', cli: 'calorie-cmd-read calorie.exercise.add --params \'{"items":[{"type":"慢跑","calories":320,"minutes":30,"date":"<日期>"}]}\'' },
  { wakeWord: '复制昨日运动', scene: '04', kind: 'exec', key: 'calorie.exercise.add', cli: 'calorie-cmd-read calorie.exercise.add --params \'{"copyFrom":"yesterday"}\'' },
  { wakeWord: '改运动记录', scene: '04', kind: 'exec', key: 'calorie.exercise.update', cli: 'calorie-cmd-read calorie.exercise.update --params \'{"id":1,"minutes":40}\'' },
  { wakeWord: '改某日运动', scene: '04', kind: 'exec', key: 'calorie.exercise.update', cli: 'calorie-cmd-read calorie.exercise.update --params \'{"note":"补记","date":"<日期>"}\'' },
  { wakeWord: '删运动记录', scene: '04', kind: 'exec', key: 'calorie.exercise.remove', cli: 'calorie-cmd-read calorie.exercise.remove --params \'{"id":1}\'' },
  { wakeWord: '删某日运动', scene: '04', kind: 'exec', key: 'calorie.exercise.remove', cli: 'calorie-cmd-read calorie.exercise.remove --params \'{"date":"<日期>"}\'' },
  { wakeWord: '批量删运动', scene: '04', kind: 'exec', key: 'calorie.exercise.remove', cli: 'calorie-cmd-read calorie.exercise.remove --params \'{"from":"<日期>","to":"<日期>"}\'' },
  { wakeWord: '看今日运动', scene: '04', kind: 'exec', key: 'calorie.view.exercise-records', cli: 'calorie-cmd-read calorie.view.exercise-records --params \'{"window":"今日"}\'' },
  { wakeWord: '看昨日运动', scene: '04', kind: 'exec', key: 'calorie.view.exercise-records', cli: 'calorie-cmd-read calorie.view.exercise-records --params \'{"window":"昨日"}\'' },
  { wakeWord: '看本周运动', scene: '04', kind: 'exec', key: 'calorie.view.exercise', cli: 'calorie-cmd-read calorie.view.exercise --params \'{"window":"本周"}\'' },
  { wakeWord: '看上周运动', scene: '04', kind: 'exec', key: 'calorie.view.exercise', cli: 'calorie-cmd-read calorie.view.exercise --params \'{"window":"上周"}\'' },
  { wakeWord: '看本月运动', scene: '04', kind: 'exec', key: 'calorie.view.exercise', cli: 'calorie-cmd-read calorie.view.exercise --params \'{"window":"本月"}\'' },
  { wakeWord: '看上月运动', scene: '04', kind: 'exec', key: 'calorie.view.exercise', cli: 'calorie-cmd-read calorie.view.exercise --params \'{"window":"上月"}\'' },
  { wakeWord: '看最近 7 天运动', scene: '04', kind: 'exec', key: 'calorie.view.exercise', cli: 'calorie-cmd-read calorie.view.exercise --params \'{"window":"7d"}\'' },
  { wakeWord: '看最近 30 天运动', scene: '04', kind: 'exec', key: 'calorie.view.exercise', cli: 'calorie-cmd-read calorie.view.exercise --params \'{"window":"30d"}\'' },
  { wakeWord: '看某段时间运动', scene: '04', kind: 'exec', key: 'calorie.view.exercise', cli: 'calorie-cmd-read calorie.view.exercise --params \'{"window":"custom","start":"<开始日期>","end":"<结束日期>"}\'' },
  { wakeWord: '看今日运动（vs 目标）', scene: '04', kind: 'exec', key: 'calorie.view.exercise-goal', cli: 'calorie-cmd-read calorie.view.exercise-goal --params \'{"window":"今日"}\'' },
  { wakeWord: '看本周运动（vs 目标）', scene: '04', kind: 'exec', key: 'calorie.view.exercise-goal', cli: 'calorie-cmd-read calorie.view.exercise-goal --params \'{"window":"本周"}\'' },
  { wakeWord: '看运动记录（有备注）', scene: '04', kind: 'exec', key: 'calorie.view.exercise-records', cli: 'calorie-cmd-read calorie.view.exercise-records --params \'{"window":"7d","hasNote":true}\'' },
  { wakeWord: '看运动记录（按力量筛选）', scene: '04', kind: 'exec', key: 'calorie.view.exercise-records', cli: 'calorie-cmd-read calorie.view.exercise-records --params \'{"window":"7d","category":"力量"}\'' },
  { wakeWord: '看运动记录（按有氧筛选）', scene: '04', kind: 'exec', key: 'calorie.view.exercise-records', cli: 'calorie-cmd-read calorie.view.exercise-records --params \'{"window":"7d","category":"有氧"}\'' },
  { wakeWord: '看最近 60 天运动', scene: '04', kind: 'exec', key: 'calorie.view.exercise', cli: 'calorie-cmd-read calorie.view.exercise --params \'{"window":"60d"}\'' },
  { wakeWord: '看最近 180 天运动', scene: '04', kind: 'exec', key: 'calorie.view.exercise', cli: 'calorie-cmd-read calorie.view.exercise --params \'{"window":"180d"}\'' },
  { wakeWord: '看最近 365 天运动', scene: '04', kind: 'exec', key: 'calorie.view.exercise', cli: 'calorie-cmd-read calorie.view.exercise --params \'{"window":"365d"}\'' },
  { wakeWord: '看运动类型分布', scene: '04', kind: 'exec', key: 'calorie.view.exercise-distribution', cli: 'calorie-cmd-read calorie.view.exercise-distribution --params \'{"window":"7d"}\'' },
  { wakeWord: '看力量训练总览', scene: '04', kind: 'exec', key: 'calorie.view.exercise-strength', cli: 'calorie-cmd-read calorie.view.exercise-strength --params \'{"window":"7d"}\'' },
  { wakeWord: '看有氧训练总览', scene: '04', kind: 'exec', key: 'calorie.view.exercise-cardio', cli: 'calorie-cmd-read calorie.view.exercise-cardio --params \'{"window":"7d"}\'' },
  { wakeWord: '看运动趋势', scene: '04', kind: 'exec', key: 'calorie.view.exercise-trend', cli: 'calorie-cmd-read calorie.view.exercise-trend --params \'{"window":"30d"}\'' },
  { wakeWord: '运动复盘（本周）', scene: '04', kind: 'exec', key: 'calorie.view.exercise-recap', cli: 'calorie-cmd-read calorie.view.exercise-recap --params \'{"window":"本周"}\'' },
  { wakeWord: '运动复盘（本月）', scene: '04', kind: 'exec', key: 'calorie.view.exercise-recap', cli: 'calorie-cmd-read calorie.view.exercise-recap --params \'{"window":"本月"}\'' },
  { wakeWord: '运动复盘（最近 90 天）', scene: '04', kind: 'exec', key: 'calorie.view.exercise-recap', cli: 'calorie-cmd-read calorie.view.exercise-recap --params \'{"window":"90d"}\'' },
  { wakeWord: '运动复盘（今年）', scene: '04', kind: 'exec', key: 'calorie.view.exercise-recap', cli: 'calorie-cmd-read calorie.view.exercise-recap --params \'{"window":"今年"}\'' },
  { wakeWord: '运动复盘（自定义时间）', scene: '04', kind: 'exec', key: 'calorie.view.exercise-recap', cli: 'calorie-cmd-read calorie.view.exercise-recap --params \'{"window":"custom","start":"<开始日期>","end":"<结束日期>"}\'' },
  { wakeWord: '看本周计划', scene: '05', kind: 'exec', key: 'calorie.view.plan', cli: 'calorie-cmd-read calorie.view.plan --params \'{"weekOffset":0}\'' },
  { wakeWord: '看下周计划', scene: '05', kind: 'exec', key: 'calorie.view.plan', cli: 'calorie-cmd-read calorie.view.plan --params \'{"weekOffset":1}\'' },
  { wakeWord: '看上周计划', scene: '05', kind: 'exec', key: 'calorie.view.plan', cli: 'calorie-cmd-read calorie.view.plan --params \'{"weekOffset":-1}\'' },
  { wakeWord: '看指定周计划', scene: '05', kind: 'exec', key: 'calorie.view.plan', cli: 'calorie-cmd-read calorie.view.plan --params \'{"week":1}\'' },
  { wakeWord: '看今天练什么', scene: '05', kind: 'exec', key: 'calorie.view.plan', cli: 'calorie-cmd-read calorie.view.plan --params \'{"date":"今日"}\'' },
  { wakeWord: '看某动作安排', scene: '05', kind: 'exec', key: 'calorie.view.plan', cli: 'calorie-cmd-read calorie.view.plan --params \'{"movement":"硬拉"}\'' },
  { wakeWord: '看某天练什么', scene: '05', kind: 'exec', key: 'calorie.view.plan', cli: 'calorie-cmd-read calorie.view.plan --params \'{"date":"今日"}\'' },
  { wakeWord: '看计划概览', scene: '05', kind: 'exec', key: 'calorie.view.plan', cli: 'calorie-cmd-read calorie.view.plan' },
  { wakeWord: '看完整计划', scene: '05', kind: 'exec', key: 'calorie.view.plan', cli: 'calorie-cmd-read calorie.view.plan' },
  { wakeWord: '看计划 vs 实际', scene: '05', kind: 'exec', key: 'calorie.view.plan-vs-actual', cli: 'calorie-cmd-read calorie.view.plan-vs-actual --params \'{"window":"本周"}\'' },
  { wakeWord: '定训练计划', scene: '05', kind: 'exec', key: 'calorie.view.plan-wizard', cli: 'calorie-cmd-read calorie.view.plan-wizard --params \'{"plan":{"config":{"title":"减脂4周","start_date":"<开始日期>","user_level":"中手","available_equipment":["瑜伽垫"]},"weeks":[{"week_number":1,"days":[{"day_of_week":1,"sessions":[{"session_label":"上肢","movements":[{"name":"俯卧撑","part":"胸","type":"力量","sets":[]}]}]}]}]}}\'' },
  { wakeWord: '复制训练计划', scene: '05', kind: 'exec', key: 'calorie.view.plan-write-preview', cli: 'calorie-cmd-read calorie.view.plan-write-preview --params \'{"op":"copy"}\'' },
  { wakeWord: '定休息日', scene: '05', kind: 'exec', key: 'calorie.view.plan-write-preview', cli: 'calorie-cmd-read calorie.view.plan-write-preview --params \'{"op":"set-rest","week":1,"dayOfWeek":3}\'' },
  { wakeWord: '加训练动作', scene: '05', kind: 'exec', key: 'calorie.view.plan-write-preview', cli: 'calorie-cmd-read calorie.view.plan-write-preview --params \'{"op":"add-movement","week":1,"dayOfWeek":1,"movement":{"name":"硬拉"}}\'' },
  { wakeWord: '定一周计划', scene: '05', kind: 'exec', key: 'calorie.view.plan-write-preview', cli: 'calorie-cmd-read calorie.view.plan-write-preview --params \'{"op":"set-week","week":1}\'' },
  { wakeWord: '改训练计划', scene: '05', kind: 'exec', key: 'calorie.view.plan-write-preview', cli: 'calorie-cmd-read calorie.view.plan-write-preview --params \'{"op":"update","title":"示例改名"}\'' },
  { wakeWord: '改某天训练', scene: '05', kind: 'exec', key: 'calorie.view.plan-write-preview', cli: 'calorie-cmd-read calorie.view.plan-write-preview --params \'{"op":"update-day","week":1,"dayOfWeek":3,"newLabel":"下肢＋核心"}\'' },
  { wakeWord: '删某天训练', scene: '05', kind: 'exec', key: 'calorie.view.plan-write-preview', cli: 'calorie-cmd-read calorie.view.plan-write-preview --params \'{"op":"delete-day","week":1,"dayOfWeek":3}\'' },
  { wakeWord: '改动作', scene: '05', kind: 'exec', key: 'calorie.view.plan-write-preview', cli: 'calorie-cmd-read calorie.view.plan-write-preview --params \'{"op":"update-movement","oldMovement":"硬拉","newMovement":{"name":"杠铃划船"}}\'' },
  { wakeWord: '撤销训练计划', scene: '05', kind: 'exec', key: 'calorie.view.plan-write-preview', cli: 'calorie-cmd-read calorie.view.plan-write-preview --params \'{"op":"delete"}\'' },
  { wakeWord: '落地训练', scene: '05', kind: 'non-exec', bucket: 'out-of-scope', reason: '明确不做（架构规格 docs/calorie-architecture.md:60：落地）；词只保证命中与文案，执行层不承接（t71 属 M8 需移植项、非 O1–O4，差异见 T71_DIFFS）。' },
  { wakeWord: '落地到本周末', scene: '05', kind: 'non-exec', bucket: 'out-of-scope', reason: '明确不做（架构规格 docs/calorie-architecture.md:60：落地）；词只保证命中与文案，执行层不承接（t71 属 M8 需移植项、非 O1–O4，差异见 T71_DIFFS）。' },
  { wakeWord: '落地到本月底', scene: '05', kind: 'non-exec', bucket: 'out-of-scope', reason: '明确不做（架构规格 docs/calorie-architecture.md:60：落地）；词只保证命中与文案，执行层不承接（t71 属 M8 需移植项、非 O1–O4，差异见 T71_DIFFS）。' },
  { wakeWord: '同步到训记', scene: '05', kind: 'non-exec', bucket: 'out-of-scope', reason: '明确不做（架构规格 docs/calorie-architecture.md:60：训记）；词只保证命中与文案，执行层不承接（t71 O3 同项）。' },
  { wakeWord: '拉训记实绩', scene: '05', kind: 'non-exec', bucket: 'out-of-scope', reason: '明确不做（架构规格 docs/calorie-architecture.md:60：训记）；词只保证命中与文案，执行层不承接（t71 O3 同项）。' },
  { wakeWord: '计划复盘（本周）', scene: '05', kind: 'exec', key: 'calorie.view.exercise-review', cli: 'calorie-cmd-read calorie.view.exercise-review --params \'{"window":"本周"}\'' },
  { wakeWord: '计划复盘（本月）', scene: '05', kind: 'exec', key: 'calorie.view.exercise-review', cli: 'calorie-cmd-read calorie.view.exercise-review --params \'{"window":"本月"}\'' },
  { wakeWord: '计划复盘（全部）', scene: '05', kind: 'exec', key: 'calorie.view.exercise-review', cli: 'calorie-cmd-read calorie.view.exercise-review --params \'{"window":"custom","start":"<开始日期>","end":"<结束日期>"}\'' },
  { wakeWord: '看计划完成率', scene: '05', kind: 'exec', key: 'calorie.view.exercise-review', cli: 'calorie-cmd-read calorie.view.exercise-review --params \'{"window":"7d"}\'' },
  { wakeWord: '看未完成训练', scene: '05', kind: 'exec', key: 'calorie.view.exercise-review', cli: 'calorie-cmd-read calorie.view.exercise-review --params \'{"window":"7d"}\'' },
  { wakeWord: '看动作完成率', scene: '05', kind: 'exec', key: 'calorie.view.exercise-review', cli: 'calorie-cmd-read calorie.view.exercise-review --params \'{"window":"7d"}\'' },
  { wakeWord: '扫禁忌', scene: '05', kind: 'exec', key: 'calorie.view.contraindication', cli: 'calorie-cmd-read calorie.view.contraindication' },
  { wakeWord: '定营养目标', scene: '06', kind: 'exec', key: 'calorie.goal.set', cli: 'calorie-cmd-read calorie.goal.set --params \'{"calorie":1800,"protein":150,"carbs":200,"fat":50,"water":2000}\'' },
  { wakeWord: '定营养目标(自动算)', scene: '06', kind: 'exec', key: 'calorie.view.goal-wizard', cli: 'calorie-cmd-read calorie.view.goal-wizard --params \'{"profile":"cut","wake":"定营养目标(自动算)"}\'' },
  { wakeWord: '定体重目标', scene: '06', kind: 'exec', key: 'calorie.goal.weight', cli: 'calorie-cmd-read calorie.goal.weight --params \'{"kg":68}\'' },
  { wakeWord: '定体重目标(自动算截止)', scene: '06', kind: 'exec', key: 'calorie.goal.weight', cli: 'calorie-cmd-read calorie.goal.weight --params \'{"kg":68,"deadline":"<日期>"}\'' },
  { wakeWord: '定体重目标(含起始日)', scene: '06', kind: 'exec', key: 'calorie.goal.weight', cli: 'calorie-cmd-read calorie.goal.weight --params \'{"kg":68,"startKg":72,"deadline":"<日期>","startDate":"<日期>"}\'' },
  { wakeWord: '定饮水目标', scene: '06', kind: 'exec', key: 'calorie.goal.water', cli: 'calorie-cmd-read calorie.goal.water --params \'{"water":2000}\'' },
  { wakeWord: '定饮水目标(自动算)', scene: '06', kind: 'exec', key: 'calorie.view.goal-wizard', cli: 'calorie-cmd-read calorie.view.goal-wizard --params \'{"profile":"cut","wake":"定饮水目标(自动算)"}\'' },
  { wakeWord: '一键定全套目标', scene: '06', kind: 'exec', key: 'calorie.view.goal-wizard', cli: 'calorie-cmd-read calorie.view.goal-wizard --params \'{"profile":"cut","wake":"一键定全套目标"}\'' },
  { wakeWord: '看今日目标', scene: '06', kind: 'exec', key: 'calorie.view.goal-progress', cli: 'calorie-cmd-read calorie.view.goal-progress --params \'{"window":"今日"}\'' },
  { wakeWord: '看本周目标', scene: '06', kind: 'exec', key: 'calorie.view.goal-progress', cli: 'calorie-cmd-read calorie.view.goal-progress --params \'{"window":"本周"}\'' },
  { wakeWord: '看营养目标进度', scene: '06', kind: 'exec', key: 'calorie.view.goal-progress', cli: 'calorie-cmd-read calorie.view.goal-progress --params \'{"window":"7d"}\'' },
  { wakeWord: '看体重目标进度', scene: '06', kind: 'exec', key: 'calorie.view.goal-weight', cli: 'calorie-cmd-read calorie.view.goal-weight --params \'{"window":"7d"}\'' },
  { wakeWord: '看饮水目标进度', scene: '06', kind: 'exec', key: 'calorie.view.goal-progress', cli: 'calorie-cmd-read calorie.view.goal-progress --params \'{"window":"今日"}\'' },
  { wakeWord: '看目标对比实际', scene: '06', kind: 'exec', key: 'calorie.view.goal-vs-actual', cli: 'calorie-cmd-read calorie.view.goal-vs-actual --params \'{"window":"30d"}\'' },
  { wakeWord: '看目标完成度', scene: '06', kind: 'exec', key: 'calorie.view.goal', cli: 'calorie-cmd-read calorie.view.goal --params \'{"window":"7d"}\'' },
  { wakeWord: '看即将到期的目标', scene: '06', kind: 'exec', key: 'calorie.view.goal-expiring', cli: 'calorie-cmd-read calorie.view.goal-expiring' },
  { wakeWord: '看目标完成率(按周)', scene: '06', kind: 'exec', key: 'calorie.view.goal-progress', cli: 'calorie-cmd-read calorie.view.goal-progress --params \'{"window":"7d"}\'' },
  { wakeWord: '看目标完成率(按月)', scene: '06', kind: 'exec', key: 'calorie.view.goal-progress', cli: 'calorie-cmd-read calorie.view.goal-progress --params \'{"window":"7d"}\'' },
  { wakeWord: '改营养目标', scene: '06', kind: 'exec', key: 'calorie.goal.set', cli: 'calorie-cmd-read calorie.goal.set --params \'{"calorie":1800,"protein":150,"carbs":200,"fat":50}\'' },
  { wakeWord: '改体重目标', scene: '06', kind: 'exec', key: 'calorie.goal.weight', cli: 'calorie-cmd-read calorie.goal.weight --params \'{"kg":67.5}\'' },
  { wakeWord: '改饮水目标', scene: '06', kind: 'exec', key: 'calorie.goal.water', cli: 'calorie-cmd-read calorie.goal.water --params \'{"water":2200}\'' },
  { wakeWord: '暂停所有目标', scene: '06', kind: 'exec', key: 'calorie.goal.pause', cli: 'calorie-cmd-read calorie.goal.pause' },
  { wakeWord: '重启所有目标', scene: '06', kind: 'exec', key: 'calorie.goal.resume', cli: 'calorie-cmd-read calorie.goal.resume' },
  { wakeWord: '看目标历史完成', scene: '06', kind: 'exec', key: 'calorie.view.goal', cli: 'calorie-cmd-read calorie.view.goal --params \'{"window":"30d"}\'' },
  { wakeWord: '看目标预测达成', scene: '06', kind: 'exec', key: 'calorie.view.goal-predict', cli: 'calorie-cmd-read calorie.view.goal-predict --params \'{"window":"14d"}\'' },
  { wakeWord: '设置档案', scene: '07', kind: 'exec', key: 'calorie.profile.set', cli: 'calorie-cmd-read calorie.profile.set --params \'{"heightCm":175,"age":30,"gender":"male","activityLevel":"moderate"}\'' },
  { wakeWord: '设活动量', scene: '07', kind: 'exec', key: 'calorie.profile.activity', cli: 'calorie-cmd-read calorie.profile.activity --params \'{"activityLevel":"active"}\'' },
  { wakeWord: '改档案', scene: '07', kind: 'exec', key: 'calorie.profile.update', cli: 'calorie-cmd-read calorie.profile.update --params \'{"field":"heightCm","value":176}\'' },
  { wakeWord: '查档案', scene: '07', kind: 'exec', key: 'calorie.view.profile', cli: 'calorie-cmd-read calorie.view.profile' },
  { wakeWord: '记体脂（皮褶钳）', scene: '08', kind: 'exec', key: 'calorie.body.composition-add', cli: 'calorie-cmd-read calorie.body.composition-add --params \'{"source":"home_caliper","sex":"male","age":30,"caliper_chest_mm":10,"caliper_abdominal_mm":12,"caliper_thigh_mm":14,"caliper_tricep_mm":11,"caliper_subscapular_mm":13,"caliper_suprailiac_mm":12,"caliper_midaxillary_mm":10,"date":"<日期>"}\'' },
  { wakeWord: '记体脂（外部测量）', scene: '08', kind: 'exec', key: 'calorie.body.composition-add', cli: 'calorie-cmd-read calorie.body.composition-add --params \'{"source":"gym","bodyFatPct":18.5,"date":"<日期>"}\'' },
  { wakeWord: '记围度', scene: '08', kind: 'exec', key: 'calorie.body.measure-add', cli: 'calorie-cmd-read calorie.body.measure-add --params \'{"waistCm":85,"hipCm":95}\'' },
  { wakeWord: '补记体脂', scene: '08', kind: 'exec', key: 'calorie.body.composition-add', cli: 'calorie-cmd-read calorie.body.composition-add --params \'{"source":"gym","bodyFatPct":19,"date":"<日期>"}\'' },
  { wakeWord: '补记围度', scene: '08', kind: 'exec', key: 'calorie.body.measure-add', cli: 'calorie-cmd-read calorie.body.measure-add --params \'{"waistCm":86,"date":"<日期>"}\'' },
  { wakeWord: '看体脂', scene: '08', kind: 'exec', key: 'calorie.view.body-composition', cli: 'calorie-cmd-read calorie.view.body-composition' },
  { wakeWord: '看体脂趋势', scene: '08', kind: 'exec', key: 'calorie.view.body-composition', cli: 'calorie-cmd-read calorie.view.body-composition --params \'{"days":90}\'' },
  { wakeWord: '看围度', scene: '08', kind: 'exec', key: 'calorie.view.body-measure', cli: 'calorie-cmd-read calorie.view.body-measure' },
  { wakeWord: '看围度趋势', scene: '08', kind: 'exec', key: 'calorie.view.body-measure', cli: 'calorie-cmd-read calorie.view.body-measure --params \'{"days":90}\'' },
  { wakeWord: '对比体脂', scene: '08', kind: 'exec', key: 'calorie.view.body-composition-compare', cli: 'calorie-cmd-read calorie.view.body-composition-compare --params \'{"period1Start":"2026-09-05","period1End":"2026-09-05","period2Start":"2026-09-07","period2End":"2026-09-07"}\'' },
  { wakeWord: '对比围度', scene: '08', kind: 'exec', key: 'calorie.view.body-measure-compare', cli: 'calorie-cmd-read calorie.view.body-measure-compare --params \'{"date1":"2026-09-05","date2":"2026-09-07"}\'' },
  { wakeWord: '删体脂', scene: '08', kind: 'exec', key: 'calorie.body.composition-remove', cli: 'calorie-cmd-read calorie.body.composition-remove --params \'{"id":1}\'' },
  { wakeWord: '删围度', scene: '08', kind: 'exec', key: 'calorie.body.measure-remove', cli: 'calorie-cmd-read calorie.body.measure-remove --params \'{"id":1}\'' },
  { wakeWord: '记身材照', scene: '09', kind: 'exec', key: 'calorie.photo.add', cli: 'calorie-cmd-read calorie.photo.add --params \'{"srcPaths":["<照片路径>"],"tag":"正面"}\'' },
  { wakeWord: '记身材照', scene: '09', kind: 'exec', key: 'calorie.photo.add', cli: 'calorie-cmd-read calorie.photo.add --params \'{"srcPaths":["<照片路径>"],"tag":"正面"}\'' },
  { wakeWord: '记身材照', scene: '09', kind: 'exec', key: 'calorie.photo.add', cli: 'calorie-cmd-read calorie.photo.add --params \'{"srcPaths":["<照片路径>"],"tag":"正面"}\'' },
  { wakeWord: '查身材照', scene: '09', kind: 'exec', key: 'calorie.photo.list', cli: 'calorie-cmd-read calorie.photo.list --params \'{"tag":"正面"}\'' },
  { wakeWord: '对比两张照片', scene: '09', kind: 'exec', key: 'calorie.photo.compare', cli: 'calorie-cmd-read calorie.photo.compare --params \'{"id1":1,"id2":2}\'' },
  { wakeWord: '生成身材照GIF', scene: '09', kind: 'exec', key: 'calorie.photo.gif', cli: 'calorie-cmd-read calorie.photo.gif --params \'{"tag":"正面"}\'' },
  { wakeWord: '删身材照', scene: '09', kind: 'exec', key: 'calorie.photo.remove', cli: 'calorie-cmd-read calorie.photo.remove --params \'{"id":1}\'' },
  { wakeWord: '改照片标签', scene: '09', kind: 'exec', key: 'calorie.photo.tag', cli: 'calorie-cmd-read calorie.photo.tag --params \'{"id":1,"op":"set","tag":"晨起"}\'' },
  { wakeWord: '加照片标签', scene: '09', kind: 'exec', key: 'calorie.photo.tag', cli: 'calorie-cmd-read calorie.photo.tag --params \'{"id":1,"op":"add","tag":"晨起"}\'' },
  { wakeWord: '删照片标签', scene: '09', kind: 'exec', key: 'calorie.photo.tag', cli: 'calorie-cmd-read calorie.photo.tag --params \'{"id":1,"op":"remove","tag":"晨起"}\'' },
  { wakeWord: '看体重 vs 摄入(最近 7 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_calorie","window":"7d"}\'' },
  { wakeWord: '看体重 vs 摄入(最近 15 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_calorie","window":"15d"}\'' },
  { wakeWord: '看体重 vs 摄入(最近 30 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_calorie","window":"30d"}\'' },
  { wakeWord: '看体重 vs 摄入(最近 60 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_calorie","window":"60d"}\'' },
  { wakeWord: '看体重 vs 摄入(最近 90 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_calorie","window":"90d"}\'' },
  { wakeWord: '看体重 vs 摄入(最近 180 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_calorie","window":"180d"}\'' },
  { wakeWord: '看体重 vs 摄入(最近 365 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_calorie","window":"365d"}\'' },
  { wakeWord: '看体重 vs 摄入(本周)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_calorie","window":"week_cur"}\'' },
  { wakeWord: '看体重 vs 摄入(本月)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_calorie","window":"month_cur"}\'' },
  { wakeWord: '看体重 vs 摄入(自定义)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_calorie","window":"custom","start":"<开始日期>","end":"<结束日期>"}\'' },
  { wakeWord: '看体重 vs 运动(最近 7 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_exercise","window":"7d"}\'' },
  { wakeWord: '看体重 vs 运动(最近 15 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_exercise","window":"15d"}\'' },
  { wakeWord: '看体重 vs 运动(最近 30 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_exercise","window":"30d"}\'' },
  { wakeWord: '看体重 vs 运动(最近 60 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_exercise","window":"60d"}\'' },
  { wakeWord: '看体重 vs 运动(最近 90 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_exercise","window":"90d"}\'' },
  { wakeWord: '看体重 vs 运动(最近 180 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_exercise","window":"180d"}\'' },
  { wakeWord: '看体重 vs 运动(最近 365 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_exercise","window":"365d"}\'' },
  { wakeWord: '看体重 vs 运动(本周)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_exercise","window":"week_cur"}\'' },
  { wakeWord: '看体重 vs 运动(本月)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_exercise","window":"month_cur"}\'' },
  { wakeWord: '看体重 vs 运动(自定义)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_exercise","window":"custom","start":"<开始日期>","end":"<结束日期>"}\'' },
  { wakeWord: '看体重 vs 蛋白(最近 7 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_protein","window":"7d"}\'' },
  { wakeWord: '看体重 vs 蛋白(最近 15 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_protein","window":"15d"}\'' },
  { wakeWord: '看体重 vs 蛋白(最近 30 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_protein","window":"30d"}\'' },
  { wakeWord: '看体重 vs 蛋白(最近 60 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_protein","window":"60d"}\'' },
  { wakeWord: '看体重 vs 蛋白(最近 90 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_protein","window":"90d"}\'' },
  { wakeWord: '看体重 vs 蛋白(最近 180 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_protein","window":"180d"}\'' },
  { wakeWord: '看体重 vs 蛋白(最近 365 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_protein","window":"365d"}\'' },
  { wakeWord: '看体重 vs 蛋白(本周)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_protein","window":"week_cur"}\'' },
  { wakeWord: '看体重 vs 蛋白(本月)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_protein","window":"month_cur"}\'' },
  { wakeWord: '看体重 vs 蛋白(自定义)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_protein","window":"custom","start":"<开始日期>","end":"<结束日期>"}\'' },
  { wakeWord: '看体重 vs 缺口(最近 7 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_deficit","window":"7d"}\'' },
  { wakeWord: '看体重 vs 缺口(最近 15 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_deficit","window":"15d"}\'' },
  { wakeWord: '看体重 vs 缺口(最近 30 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_deficit","window":"30d"}\'' },
  { wakeWord: '看体重 vs 缺口(最近 60 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_deficit","window":"60d"}\'' },
  { wakeWord: '看体重 vs 缺口(最近 90 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_deficit","window":"90d"}\'' },
  { wakeWord: '看体重 vs 缺口(最近 180 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_deficit","window":"180d"}\'' },
  { wakeWord: '看体重 vs 缺口(最近 365 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_deficit","window":"365d"}\'' },
  { wakeWord: '看体重 vs 缺口(本周)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_deficit","window":"week_cur"}\'' },
  { wakeWord: '看体重 vs 缺口(本月)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_deficit","window":"month_cur"}\'' },
  { wakeWord: '看体重 vs 缺口(自定义)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_deficit","window":"custom","start":"<开始日期>","end":"<结束日期>"}\'' },
  { wakeWord: '看摄入 vs 运动(最近 7 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"calorie_exercise","window":"7d"}\'' },
  { wakeWord: '看摄入 vs 运动(最近 30 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"calorie_exercise","window":"30d"}\'' },
  { wakeWord: '看摄入 vs 运动(最近 90 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"calorie_exercise","window":"90d"}\'' },
  { wakeWord: '看摄入 vs 运动(最近 180 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"calorie_exercise","window":"180d"}\'' },
  { wakeWord: '看摄入 vs 运动(最近 365 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"calorie_exercise","window":"365d"}\'' },
  { wakeWord: '看摄入 vs 运动(自定义)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"calorie_exercise","window":"custom","start":"<开始日期>","end":"<结束日期>"}\'' },
  { wakeWord: '看体重 vs 体脂(最近 7 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_bodyfat","window":"7d"}\'' },
  { wakeWord: '看体重 vs 体脂(最近 30 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_bodyfat","window":"30d"}\'' },
  { wakeWord: '看体重 vs 体脂(最近 90 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_bodyfat","window":"90d"}\'' },
  { wakeWord: '看体重 vs 体脂(最近 180 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_bodyfat","window":"180d"}\'' },
  { wakeWord: '看体重 vs 体脂(最近 365 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_bodyfat","window":"365d"}\'' },
  { wakeWord: '看体重 vs 体脂(自定义)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_bodyfat","window":"custom","start":"<开始日期>","end":"<结束日期>"}\'' },
  { wakeWord: '看体重 vs 围度(最近 7 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_waist","window":"7d"}\'' },
  { wakeWord: '看体重 vs 围度(最近 30 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_waist","window":"30d"}\'' },
  { wakeWord: '看体重 vs 围度(最近 90 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_waist","window":"90d"}\'' },
  { wakeWord: '看体重 vs 围度(最近 180 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_waist","window":"180d"}\'' },
  { wakeWord: '看体重 vs 围度(最近 365 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_waist","window":"365d"}\'' },
  { wakeWord: '看体重 vs 围度(自定义)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_waist","window":"custom","start":"<开始日期>","end":"<结束日期>"}\'' },
  { wakeWord: '看饮水 vs 体重(最近 30 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"water_weight","window":"30d"}\'' },
  { wakeWord: '看饮水 vs 体重(自定义)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"water_weight","window":"custom","start":"<开始日期>","end":"<结束日期>"}\'' },
  { wakeWord: '看健康报告(本周)', scene: '10', kind: 'exec', key: 'calorie.view.health', cli: 'calorie-cmd-read calorie.view.health --params \'{"window":"本周"}\'' },
  { wakeWord: '看健康报告(上周)', scene: '10', kind: 'exec', key: 'calorie.view.health', cli: 'calorie-cmd-read calorie.view.health --params \'{"window":"上周"}\'' },
  { wakeWord: '看健康报告(最近 7 天)', scene: '10', kind: 'exec', key: 'calorie.view.health', cli: 'calorie-cmd-read calorie.view.health --params \'{"window":"7d"}\'' },
  { wakeWord: '看健康报告(最近 30 天)', scene: '10', kind: 'exec', key: 'calorie.view.health', cli: 'calorie-cmd-read calorie.view.health --params \'{"window":"30d"}\'' },
  { wakeWord: '看健康报告(最近 90 天)', scene: '10', kind: 'exec', key: 'calorie.view.health', cli: 'calorie-cmd-read calorie.view.health --params \'{"window":"90d"}\'' },
  { wakeWord: '看健康报告(最近 180 天)', scene: '10', kind: 'exec', key: 'calorie.view.health', cli: 'calorie-cmd-read calorie.view.health --params \'{"window":"180d"}\'' },
  { wakeWord: '看健康报告(最近 365 天)', scene: '10', kind: 'exec', key: 'calorie.view.health', cli: 'calorie-cmd-read calorie.view.health --params \'{"window":"365d"}\'' },
  { wakeWord: '看健康报告(本月)', scene: '10', kind: 'exec', key: 'calorie.view.health', cli: 'calorie-cmd-read calorie.view.health --params \'{"window":"本月"}\'' },
  { wakeWord: '看健康报告(上月)', scene: '10', kind: 'exec', key: 'calorie.view.health', cli: 'calorie-cmd-read calorie.view.health --params \'{"window":"上月"}\'' },
  { wakeWord: '看健康报告(今年)', scene: '10', kind: 'exec', key: 'calorie.view.health', cli: 'calorie-cmd-read calorie.view.health --params \'{"window":"今年"}\'' },
  { wakeWord: '看健康报告(自定义)', scene: '10', kind: 'exec', key: 'calorie.view.health', cli: 'calorie-cmd-read calorie.view.health --params \'{"window":"custom","start":"<开始日期>","end":"<结束日期>"}\'' },
  { wakeWord: '看BMI报告', scene: '10', kind: 'exec', key: 'calorie.report.bmi', cli: 'calorie-cmd-read calorie.report.bmi --params \'{"window":"90d"}\'' },
  { wakeWord: '看TDEE报告', scene: '10', kind: 'exec', key: 'calorie.report.tdee', cli: 'calorie-cmd-read calorie.report.tdee --params \'{"window":"30d"}\'' },
  { wakeWord: '看BMR报告', scene: '10', kind: 'exec', key: 'calorie.report.bmr', cli: 'calorie-cmd-read calorie.report.bmr --params \'{"window":"30d"}\'' },
  { wakeWord: '看蛋白质摄入报告', scene: '10', kind: 'exec', key: 'calorie.report.protein', cli: 'calorie-cmd-read calorie.report.protein --params \'{"window":"30d"}\'' },
  { wakeWord: '看水分摄入报告', scene: '10', kind: 'exec', key: 'calorie.report.water', cli: 'calorie-cmd-read calorie.report.water --params \'{"window":"30d"}\'' },
  { wakeWord: '看综合评分', scene: '10', kind: 'exec', key: 'calorie.report.score', cli: 'calorie-cmd-read calorie.report.score --params \'{"window":"30d"}\'' },
  { wakeWord: '看健康趋势', scene: '10', kind: 'exec', key: 'calorie.report.trend', cli: 'calorie-cmd-read calorie.report.trend --params \'{"window":"90d"}\'' },
  { wakeWord: '看健康报告(含对比)', scene: '10', kind: 'exec', key: 'calorie.report.compare', cli: 'calorie-cmd-read calorie.report.compare --params \'{"window":"7d"}\'' },
  { wakeWord: '看整体趋势(体重+摄入+运动)', scene: '10', kind: 'exec', key: 'calorie.view.multi-trend', cli: 'calorie-cmd-read calorie.view.multi-trend --params \'{"window":"90d","group":"g1","compare":"target"}\'' },
  { wakeWord: '看整体趋势(体重+体脂+围度)', scene: '10', kind: 'exec', key: 'calorie.view.multi-trend', cli: 'calorie-cmd-read calorie.view.multi-trend --params \'{"window":"90d","group":"g2","compare":"target"}\'' },
  { wakeWord: '看整体趋势(饮食+蛋白+纤维)', scene: '10', kind: 'exec', key: 'calorie.view.multi-trend', cli: 'calorie-cmd-read calorie.view.multi-trend --params \'{"window":"90d","group":"g3","compare":"target"}\'' },
  { wakeWord: '看整体趋势(运动+力量+有氧)', scene: '10', kind: 'exec', key: 'calorie.view.multi-trend', cli: 'calorie-cmd-read calorie.view.multi-trend --params \'{"window":"90d","group":"g4","compare":"target"}\'' },
  { wakeWord: '看整体趋势(BMI+体脂+肌肉量)', scene: '10', kind: 'exec', key: 'calorie.view.multi-trend', cli: 'calorie-cmd-read calorie.view.multi-trend --params \'{"window":"90d","group":"g5","compare":"target"}\'' },
  { wakeWord: '看整体趋势(摄入+蛋白+运动)', scene: '10', kind: 'exec', key: 'calorie.view.multi-trend', cli: 'calorie-cmd-read calorie.view.multi-trend --params \'{"window":"90d","group":"g6","compare":"target"}\'' },
  { wakeWord: '看整体趋势(体重+蛋白+缺口)', scene: '10', kind: 'exec', key: 'calorie.view.multi-trend', cli: 'calorie-cmd-read calorie.view.multi-trend --params \'{"window":"90d","group":"g7","compare":"target"}\'' },
  { wakeWord: '看整体趋势(体重+摄入+缺口)', scene: '10', kind: 'exec', key: 'calorie.view.multi-trend', cli: 'calorie-cmd-read calorie.view.multi-trend --params \'{"window":"90d","group":"g8","compare":"target"}\'' },
  { wakeWord: '看整体趋势(体重+摄入+运动+缺口)', scene: '10', kind: 'exec', key: 'calorie.view.multi-trend', cli: 'calorie-cmd-read calorie.view.multi-trend --params \'{"window":"90d","group":"g9","compare":"target"}\'' },
  { wakeWord: '看整体趋势(蛋白+运动)', scene: '10', kind: 'exec', key: 'calorie.view.multi-trend', cli: 'calorie-cmd-read calorie.view.multi-trend --params \'{"window":"90d","group":"g10","compare":"target"}\'' },
  { wakeWord: '看整体趋势(综合多指标)', scene: '10', kind: 'exec', key: 'calorie.view.multi-trend', cli: 'calorie-cmd-read calorie.view.multi-trend --params \'{"window":"90d","group":"g11","compare":"target"}\'' },
  { wakeWord: '看整体趋势(含月度对比)', scene: '10', kind: 'exec', key: 'calorie.view.multi-trend', cli: 'calorie-cmd-read calorie.view.multi-trend --params \'{"window":"60d","group":"comprehensive","compare":"monthly"}\'' },
  { wakeWord: '看整体趋势(含季度对比)', scene: '10', kind: 'exec', key: 'calorie.view.multi-trend', cli: 'calorie-cmd-read calorie.view.multi-trend --params \'{"window":"180d","group":"comprehensive","compare":"quarterly"}\'' },
  { wakeWord: '看整体趋势(含年度对比)', scene: '10', kind: 'exec', key: 'calorie.view.multi-trend', cli: 'calorie-cmd-read calorie.view.multi-trend --params \'{"window":"730d","group":"comprehensive","compare":"yearly"}\'' },
  { wakeWord: '看整体趋势(含目标对比)', scene: '10', kind: 'exec', key: 'calorie.view.multi-trend', cli: 'calorie-cmd-read calorie.view.multi-trend --params \'{"window":"90d","compare":"target"}\'' },
  { wakeWord: '诊断体重波动原因', scene: '10', kind: 'exec', key: 'calorie.view.anomaly', cli: 'calorie-cmd-read calorie.view.anomaly --params \'{"kind":"weight_volatility","window":"90d"}\'' },
  { wakeWord: '诊断体重停滞(含平台期判断)', scene: '10', kind: 'exec', key: 'calorie.view.anomaly', cli: 'calorie-cmd-read calorie.view.anomaly --params \'{"kind":"weight_plateau","window":"90d"}\'' },
  { wakeWord: '诊断体重反弹', scene: '10', kind: 'exec', key: 'calorie.view.anomaly', cli: 'calorie-cmd-read calorie.view.anomaly --params \'{"kind":"weight_rebound","window":"90d"}\'' },
  { wakeWord: '诊断体重下降原因', scene: '10', kind: 'exec', key: 'calorie.view.anomaly', cli: 'calorie-cmd-read calorie.view.anomaly --params \'{"kind":"weight_loss_cause","window":"90d"}\'' },
  { wakeWord: '诊断体重异常点', scene: '10', kind: 'exec', key: 'calorie.view.anomaly', cli: 'calorie-cmd-read calorie.view.anomaly --params \'{"kind":"weight_anomaly","window":"7d"}\'' },
  { wakeWord: '诊断体重vs体脂围度背离', scene: '10', kind: 'exec', key: 'calorie.view.anomaly', cli: 'calorie-cmd-read calorie.view.anomaly --params \'{"kind":"weight_divergence","window":"180d"}\'' },
  { wakeWord: '诊断饮食超标', scene: '10', kind: 'exec', key: 'calorie.view.anomaly', cli: 'calorie-cmd-read calorie.view.anomaly --params \'{"kind":"diet_over","window":"30d"}\'' },
  { wakeWord: '诊断饮食不足', scene: '10', kind: 'exec', key: 'calorie.view.anomaly', cli: 'calorie-cmd-read calorie.view.anomaly --params \'{"kind":"diet_under","window":"30d"}\'' },
  { wakeWord: '诊断营养不均衡(含均衡判断)', scene: '10', kind: 'exec', key: 'calorie.view.anomaly', cli: 'calorie-cmd-read calorie.view.anomaly --params \'{"kind":"diet_unbalanced","window":"30d"}\'' },
  { wakeWord: '诊断饮食结构问题', scene: '10', kind: 'exec', key: 'calorie.view.anomaly', cli: 'calorie-cmd-read calorie.view.anomaly --params \'{"kind":"diet_structure","window":"30d"}\'' },
  { wakeWord: '诊断运动不足', scene: '10', kind: 'exec', key: 'calorie.view.anomaly', cli: 'calorie-cmd-read calorie.view.anomaly --params \'{"kind":"exercise_insufficient","window":"30d"}\'' },
  { wakeWord: '诊断运动过量', scene: '10', kind: 'exec', key: 'calorie.view.anomaly', cli: 'calorie-cmd-read calorie.view.anomaly --params \'{"kind":"exercise_overload","window":"30d"}\'' },
  { wakeWord: '诊断运动类型失衡', scene: '10', kind: 'exec', key: 'calorie.view.anomaly', cli: 'calorie-cmd-read calorie.view.anomaly --params \'{"kind":"exercise_type_imbalance","window":"30d"}\'' },
  { wakeWord: '诊断运动效率(含有效判断)', scene: '10', kind: 'exec', key: 'calorie.view.anomaly', cli: 'calorie-cmd-read calorie.view.anomaly --params \'{"kind":"exercise_efficiency","window":"30d"}\'' },
  { wakeWord: '诊断运动建议(含类型推荐)', scene: '10', kind: 'exec', key: 'calorie.view.anomaly', cli: 'calorie-cmd-read calorie.view.anomaly --params \'{"kind":"exercise_advice","window":"30d"}\'' },
  { wakeWord: '为什么我没瘦', scene: '10', kind: 'exec', key: 'calorie.view.anomaly', cli: 'calorie-cmd-read calorie.view.anomaly --params \'{"kind":"why_not_losing","window":"30d"}\'' },
  { wakeWord: '为什么我瘦太快', scene: '10', kind: 'exec', key: 'calorie.view.anomaly', cli: 'calorie-cmd-read calorie.view.anomaly --params \'{"kind":"why_losing_fast","window":"30d"}\'' },
  { wakeWord: '我的减重速度合理吗', scene: '10', kind: 'exec', key: 'calorie.view.anomaly', cli: 'calorie-cmd-read calorie.view.anomaly --params \'{"kind":"rate_reasonable","window":"30d"}\'' },
  { wakeWord: '我的减肥策略对吗', scene: '10', kind: 'exec', key: 'calorie.view.goal-progress', cli: 'calorie-cmd-read calorie.view.goal-progress --params \'{"window":"30d"}\'' },
  { wakeWord: '我距离目标还差什么', scene: '10', kind: 'exec', key: 'calorie.view.goal-weight', cli: 'calorie-cmd-read calorie.view.goal-weight --params \'{"window":"7d"}\'' },
  { wakeWord: '我这个月做得好的', scene: '10', kind: 'exec', key: 'calorie.view.anomaly', cli: 'calorie-cmd-read calorie.view.anomaly --params \'{"kind":"month_highlights","window":"30d"}\'' },
  { wakeWord: '我这个月需要改的', scene: '10', kind: 'exec', key: 'calorie.view.anomaly', cli: 'calorie-cmd-read calorie.view.anomaly --params \'{"kind":"month_improve","window":"30d"}\'' },
  { wakeWord: '综合健康评估', scene: '10', kind: 'exec', key: 'calorie.view.anomaly', cli: 'calorie-cmd-read calorie.view.anomaly --params \'{"kind":"overall","window":"30d"}\'' },
  { wakeWord: '看蛋白 vs 碳水(最近 7 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"protein_carbs","window":"7d"}\'' },
  { wakeWord: '看蛋白 vs 碳水(最近 30 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"protein_carbs","window":"30d"}\'' },
  { wakeWord: '看蛋白 vs 碳水(最近 90 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"protein_carbs","window":"90d"}\'' },
  { wakeWord: '看蛋白 vs 碳水(自定义)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"protein_carbs","window":"custom","start":"<开始日期>","end":"<结束日期>"}\'' },
  { wakeWord: '看蛋白 vs 脂肪(最近 30 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"protein_fat","window":"30d"}\'' },
  { wakeWord: '看蛋白 vs 脂肪(最近 90 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"protein_fat","window":"90d"}\'' },
  { wakeWord: '看蛋白 vs 脂肪(自定义)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"protein_fat","window":"custom","start":"<开始日期>","end":"<结束日期>"}\'' },
  { wakeWord: '看碳水 vs 脂肪(最近 30 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"carbs_fat","window":"30d"}\'' },
  { wakeWord: '看碳水 vs 脂肪(最近 90 天)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"carbs_fat","window":"90d"}\'' },
  { wakeWord: '看碳水 vs 脂肪(自定义)', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"carbs_fat","window":"custom","start":"<开始日期>","end":"<结束日期>"}\'' },
  { wakeWord: '看钠糖纤维趋势', scene: '10', kind: 'exec', key: 'calorie.view.nutrition-analysis', cli: 'calorie-cmd-read calorie.view.nutrition-analysis --params \'{"window":"7d"}\'' },
  { wakeWord: '看钠糖纤维综合', scene: '10', kind: 'exec', key: 'calorie.view.nutrition-analysis', cli: 'calorie-cmd-read calorie.view.nutrition-analysis --params \'{"window":"7d"}\'' },
  { wakeWord: '看营养建议', scene: '10', kind: 'non-exec', bucket: 'legacy-chain', reason: '命中但不执行：95 键无营养建议形态（view.diet-review／view.health 给数据盘，不给建议条目）。' },
  { wakeWord: '看三大营养交叉(最近 30 天)', scene: '10', kind: 'exec', key: 'calorie.view.diet-review', cli: 'calorie-cmd-read calorie.view.diet-review --params \'{"window":"30d"}\'' },
  { wakeWord: '看三大营养交叉(最近 90 天)', scene: '10', kind: 'exec', key: 'calorie.view.diet-review', cli: 'calorie-cmd-read calorie.view.diet-review --params \'{"window":"90d"}\'' },
  { wakeWord: '看三大营养交叉(自定义)', scene: '10', kind: 'exec', key: 'calorie.view.diet-review', cli: 'calorie-cmd-read calorie.view.diet-review --params \'{"window":"custom","start":"<开始日期>","end":"<结束日期>"}\'' },
  { wakeWord: '预测体重(1 周后)', scene: '10', kind: 'exec', key: 'calorie.view.predict', cli: 'calorie-cmd-read calorie.view.predict --params \'{"horizonDays":7,"window":"14d"}\'' },
  { wakeWord: '预测体重(1 月后)', scene: '10', kind: 'exec', key: 'calorie.view.predict', cli: 'calorie-cmd-read calorie.view.predict --params \'{"horizonDays":30,"window":"14d"}\'' },
  { wakeWord: '预测体重(3 月后)', scene: '10', kind: 'exec', key: 'calorie.view.predict', cli: 'calorie-cmd-read calorie.view.predict --params \'{"horizonDays":90,"window":"14d"}\'' },
  { wakeWord: '预测体重(6 月后)', scene: '10', kind: 'exec', key: 'calorie.view.predict', cli: 'calorie-cmd-read calorie.view.predict --params \'{"horizonDays":180,"window":"14d"}\'' },
  { wakeWord: '预测体重(自定义时间)', scene: '10', kind: 'exec', key: 'calorie.view.predict', cli: 'calorie-cmd-read calorie.view.predict --params \'{"horizonDays":60,"window":"14d"}\'' },
  { wakeWord: '预测体重(自定义目标)', scene: '10', kind: 'exec', key: 'calorie.view.predict', cli: 'calorie-cmd-read calorie.view.predict --params \'{"target":65,"window":"14d"}\'' },
  { wakeWord: '模拟减重(每天-300卡)', scene: '10', kind: 'exec', key: 'calorie.view.predict', cli: 'calorie-cmd-read calorie.view.predict --params \'{"cut_kcal":300,"window":"14d"}\'' },
  { wakeWord: '模拟减重(每天-500卡)', scene: '10', kind: 'exec', key: 'calorie.view.predict', cli: 'calorie-cmd-read calorie.view.predict --params \'{"cut_kcal":500,"window":"14d"}\'' },
  { wakeWord: '模拟减重(每天-700卡)', scene: '10', kind: 'exec', key: 'calorie.view.predict', cli: 'calorie-cmd-read calorie.view.predict --params \'{"cut_kcal":700,"window":"14d"}\'' },
  { wakeWord: '模拟减重(30天减Xkg)', scene: '10', kind: 'exec', key: 'calorie.view.predict', cli: 'calorie-cmd-read calorie.view.predict --params \'{"target_loss":2,"days_target":30,"window":"14d"}\'' },
  { wakeWord: '模拟减重(60天减Xkg)', scene: '10', kind: 'exec', key: 'calorie.view.predict', cli: 'calorie-cmd-read calorie.view.predict --params \'{"target_loss":4,"days_target":60,"window":"14d"}\'' },
  { wakeWord: '模拟减重(90天减Xkg)', scene: '10', kind: 'exec', key: 'calorie.view.predict', cli: 'calorie-cmd-read calorie.view.predict --params \'{"target_loss":6,"days_target":90,"window":"14d"}\'' },
  { wakeWord: '模拟减重(自定义天数减Xkg)', scene: '10', kind: 'exec', key: 'calorie.view.predict', cli: 'calorie-cmd-read calorie.view.predict --params \'{"target_loss":3,"days_target":45,"window":"14d"}\'' },
  { wakeWord: '摄入预测(按当前速率 1 周)', scene: '10', kind: 'exec', key: 'calorie.view.predict', cli: 'calorie-cmd-read calorie.view.predict --params \'{"kind":"calorie_forecast","horizonDays":7,"window":"14d"}\'' },
  { wakeWord: '摄入预测(按当前速率 1 月)', scene: '10', kind: 'exec', key: 'calorie.view.predict', cli: 'calorie-cmd-read calorie.view.predict --params \'{"kind":"calorie_forecast","horizonDays":30,"window":"14d"}\'' },
  { wakeWord: '摄入预测(按当前速率 3 月)', scene: '10', kind: 'exec', key: 'calorie.view.predict', cli: 'calorie-cmd-read calorie.view.predict --params \'{"kind":"calorie_forecast","horizonDays":90,"window":"14d"}\'' },
  { wakeWord: '摄入预测(自定义)', scene: '10', kind: 'exec', key: 'calorie.view.predict', cli: 'calorie-cmd-read calorie.view.predict --params \'{"kind":"calorie_forecast","horizonDays":60,"window":"14d"}\'' },
  { wakeWord: '摄入预测(营养目标达成预测)', scene: '10', kind: 'exec', key: 'calorie.view.predict', cli: 'calorie-cmd-read calorie.view.predict --params \'{"kind":"calorie_goal","window":"30d"}\'' },
  { wakeWord: '摄入预测(卡路里缺口预测)', scene: '10', kind: 'exec', key: 'calorie.view.predict', cli: 'calorie-cmd-read calorie.view.predict --params \'{"kind":"calorie_deficit","window":"30d"}\'' },
  { wakeWord: '摄入预测(摄入稳定性预测)', scene: '10', kind: 'exec', key: 'calorie.view.predict', cli: 'calorie-cmd-read calorie.view.predict --params \'{"kind":"calorie_stability","window":"30d"}\'' },
  { wakeWord: '看每日 6 因素综合', scene: '10', kind: 'exec', key: 'calorie.view.six-factors', cli: 'calorie-cmd-read calorie.view.six-factors --params \'{"date":"今日"}\'' },
  { wakeWord: '今日复盘', scene: '10', kind: 'exec', key: 'calorie.view.diet-review', cli: 'calorie-cmd-read calorie.view.diet-review --params \'{"window":"今日"}\'' },
  { wakeWord: '关闭定时复盘', scene: '10', kind: 'non-exec', bucket: 'out-of-scope', reason: '明确不做（架构规格 docs/calorie-architecture.md:60：定时复盘）；词只保证命中与文案，执行层不承接（t71 O1 同项）。' },
  { wakeWord: '复盘', scene: '10', kind: 'exec', key: 'calorie.view.diet-review', cli: 'calorie-cmd-read calorie.view.diet-review --params \'{"window":"今日"}\'' },
  { wakeWord: '复盘日期范围', scene: '10', kind: 'exec', key: 'calorie.view.diet-review', cli: 'calorie-cmd-read calorie.view.diet-review --params \'{"window":"7d"}\'' },
  { wakeWord: '开启定时复盘', scene: '10', kind: 'non-exec', bucket: 'out-of-scope', reason: '明确不做（架构规格 docs/calorie-architecture.md:60：定时复盘）；词只保证命中与文案，执行层不承接（t71 O1 同项）。' },
  { wakeWord: '本周复盘', scene: '10', kind: 'exec', key: 'calorie.view.diet-review', cli: 'calorie-cmd-read calorie.view.diet-review --params \'{"window":"本周"}\'' },
  { wakeWord: '本年复盘', scene: '10', kind: 'exec', key: 'calorie.view.diet-review', cli: 'calorie-cmd-read calorie.view.diet-review --params \'{"window":"今年"}\'' },
  { wakeWord: '本月复盘', scene: '10', kind: 'exec', key: 'calorie.view.diet-review', cli: 'calorie-cmd-read calorie.view.diet-review --params \'{"window":"本月"}\'' },
  { wakeWord: '查低热量榜', scene: '10', kind: 'exec', key: 'calorie.view.ranking', cli: 'calorie-cmd-read calorie.view.ranking --params \'{"category":"low_calorie","topN":10,"window":"7d"}\'' },
  { wakeWord: '查健康报告', scene: '10', kind: 'exec', key: 'calorie.view.health', cli: 'calorie-cmd-read calorie.view.health --params \'{"window":"7d"}\'' },
  { wakeWord: '查卡路里数据', scene: '10', kind: 'exec', key: 'calorie.view.lint-health', cli: 'calorie-cmd-read calorie.view.lint-health' },
  { wakeWord: '查定时复盘', scene: '10', kind: 'non-exec', bucket: 'out-of-scope', reason: '明确不做（架构规格 docs/calorie-architecture.md:60：定时复盘）；词只保证命中与文案，执行层不承接（t71 O1 同项）。' },
  { wakeWord: '查热量缺口', scene: '10', kind: 'exec', key: 'calorie.view.deficit', cli: 'calorie-cmd-read calorie.view.deficit --params \'{"window":"7d"}\'' },
  { wakeWord: '查热量趋势', scene: '10', kind: 'exec', key: 'calorie.history', cli: 'calorie-cmd-read calorie.history --params \'{"days":7}\'' },
  { wakeWord: '查营养结构', scene: '10', kind: 'exec', key: 'calorie.view.diet-review', cli: 'calorie-cmd-read calorie.view.diet-review --params \'{"window":"7d"}\'' },
  { wakeWord: '查运动分布', scene: '10', kind: 'exec', key: 'calorie.view.exercise', cli: 'calorie-cmd-read calorie.view.exercise --params \'{"window":"7d"}\'' },
  { wakeWord: '查运动贡献', scene: '10', kind: 'exec', key: 'calorie.view.exercise', cli: 'calorie-cmd-read calorie.view.exercise --params \'{"window":"7d"}\'' },
  { wakeWord: '查频繁吃榜', scene: '10', kind: 'exec', key: 'calorie.view.ranking', cli: 'calorie-cmd-read calorie.view.ranking --params \'{"category":"frequent","topN":10,"window":"7d"}\'' },
  { wakeWord: '查食物排行', scene: '10', kind: 'exec', key: 'calorie.view.ranking', cli: 'calorie-cmd-read calorie.view.ranking --params \'{"topN":10,"window":"7d"}\'' },
  { wakeWord: '查高热量榜', scene: '10', kind: 'exec', key: 'calorie.view.ranking', cli: 'calorie-cmd-read calorie.view.ranking --params \'{"window":"7d"}\'' },
  { wakeWord: '查高碳水榜', scene: '10', kind: 'exec', key: 'calorie.view.ranking', cli: 'calorie-cmd-read calorie.view.ranking --params \'{"category":"high_carb","topN":10,"window":"7d"}\'' },
  { wakeWord: '查高蛋白榜', scene: '10', kind: 'exec', key: 'calorie.view.ranking', cli: 'calorie-cmd-read calorie.view.ranking --params \'{"category":"high_protein","topN":10,"window":"7d"}\'' },
];

/** 69 条新拟入口（D-4：键内无同形入口的补入口，唤醒词新拟、不写入冻结表） */
export const NEW_KEY_ROUTES: readonly ExecWakeRoute[] = [
  { wakeWord: '存身材照', scene: '09', kind: 'exec', key: 'calorie.photo.add', cli: 'calorie-cmd-read calorie.photo.add --params \'{"srcPaths":["<照片路径>"],"tag":"正面"}\'' },
  { wakeWord: '移除身材照', scene: '09', kind: 'exec', key: 'calorie.photo.remove', cli: 'calorie-cmd-read calorie.photo.remove --params \'{"id":1}\'' },
  { wakeWord: '设置照片标签', scene: '09', kind: 'exec', key: 'calorie.photo.tag', cli: 'calorie-cmd-read calorie.photo.tag --params \'{"id":1,"op":"add","tag":"晨起"}\'' },
  { wakeWord: '看今日饮食记录', scene: '02', kind: 'exec', key: 'calorie.today', cli: 'calorie-cmd-read calorie.today --params \'{"date":"今日"}\'' },
  { wakeWord: '看目标配置', scene: '06', kind: 'exec', key: 'calorie.view.goal-config', cli: 'calorie-cmd-read calorie.view.goal-config' },
  { wakeWord: '看目标状态', scene: '06', kind: 'exec', key: 'calorie.view.goal-status', cli: 'calorie-cmd-read calorie.view.goal-status' },
  { wakeWord: '看组合分析', scene: '10', kind: 'exec', key: 'calorie.view.combined', cli: 'calorie-cmd-read calorie.view.combined --params \'{"pair":"weight_calorie","window":"7d"}\'' },
  { wakeWord: '看热量缺口', scene: '10', kind: 'exec', key: 'calorie.view.deficit', cli: 'calorie-cmd-read calorie.view.deficit --params \'{"window":"7d"}\'' },
  { wakeWord: '看饮食复盘', scene: '02', kind: 'exec', key: 'calorie.view.diet-review', cli: 'calorie-cmd-read calorie.view.diet-review --params \'{"window":"今日"}\'' },
  { wakeWord: '看健康盘', scene: '10', kind: 'exec', key: 'calorie.view.health', cli: 'calorie-cmd-read calorie.view.health --params \'{"window":"今日"}\'' },
  { wakeWord: '查高热量排行', scene: '02', kind: 'exec', key: 'calorie.view.ranking', cli: 'calorie-cmd-read calorie.view.ranking --params \'{"category":"high_calorie","topN":10,"window":"7d"}\'' },
  { wakeWord: '查食品库', scene: '02', kind: 'exec', key: 'calorie.view.library', cli: 'calorie-cmd-read calorie.view.library' },
  { wakeWord: '搜食品', scene: '02', kind: 'exec', key: 'calorie.view.search', cli: 'calorie-cmd-read calorie.view.search --params \'{"keyword":"鸡胸"}\'' },
  { wakeWord: '看身材照', scene: '09', kind: 'exec', key: 'calorie.photo.list', cli: 'calorie-cmd-read calorie.photo.list --params \'{"tag":"正面"}\'' },
  { wakeWord: '查身材照详情', scene: '09', kind: 'exec', key: 'calorie.photo.detail', cli: 'calorie-cmd-read calorie.photo.detail --params \'{"id":1}\'' },
  { wakeWord: '对比身材照', scene: '09', kind: 'exec', key: 'calorie.photo.compare', cli: 'calorie-cmd-read calorie.photo.compare --params \'{"id1":1,"id2":2}\'' },
  { wakeWord: '做身材照GIF', scene: '09', kind: 'exec', key: 'calorie.photo.gif', cli: 'calorie-cmd-read calorie.photo.gif --params \'{"tag":"正面"}\'' },
  { wakeWord: '看身材照HELP', scene: '09', kind: 'exec', key: 'calorie.help.center', cli: 'calorie-cmd-read calorie.help.center --params \'{"q":"记身材照"}\'' },
  { wakeWord: '查唤醒词', scene: '10', kind: 'exec', key: 'calorie.help.lookup', cli: 'calorie-cmd-read calorie.help.lookup --params \'{"q":"看今日主页"}\'' },
  { wakeWord: '查热量历史', scene: '10', kind: 'exec', key: 'calorie.history', cli: 'calorie-cmd-read calorie.history --params \'{"days":7}\'' },
  { wakeWord: '看体重历史', scene: '03', kind: 'exec', key: 'calorie.view.weight-history', cli: 'calorie-cmd-read calorie.view.weight-history' },
  { wakeWord: '看体重对比', scene: '03', kind: 'exec', key: 'calorie.view.weight-compare', cli: 'calorie-cmd-read calorie.view.weight-compare --params \'{"window":"7d","compareWindow":"prev"}\'' },
  { wakeWord: '看体重复核', scene: '03', kind: 'exec', key: 'calorie.view.weight-review', cli: 'calorie-cmd-read calorie.view.weight-review' },
  { wakeWord: '看波动分析', scene: '03', kind: 'exec', key: 'calorie.view.volatility', cli: 'calorie-cmd-read calorie.view.volatility' },
  { wakeWord: '看体成分', scene: '08', kind: 'exec', key: 'calorie.view.body-composition', cli: 'calorie-cmd-read calorie.view.body-composition' },
  { wakeWord: '看围度记录', scene: '08', kind: 'exec', key: 'calorie.view.body-measure', cli: 'calorie-cmd-read calorie.view.body-measure' },
  { wakeWord: '看训练计划', scene: '05', kind: 'exec', key: 'calorie.view.plan', cli: 'calorie-cmd-read calorie.view.plan' },
  { wakeWord: '看构建向导', scene: '05', kind: 'exec', key: 'calorie.view.plan-wizard', cli: 'calorie-cmd-read calorie.view.plan-wizard --params \'{"plan":{"config":{"title":"减脂4周","start_date":"<开始日期>","user_level":"中手","available_equipment":["瑜伽垫"]},"weeks":[{"week_number":1,"days":[{"day_of_week":1,"sessions":[{"session_label":"上肢","movements":[{"name":"俯卧撑","part":"胸","type":"力量","sets":[]}]}]}]}]}}\'' },
  { wakeWord: '看运动目标', scene: '04', kind: 'exec', key: 'calorie.view.exercise-goal', cli: 'calorie-cmd-read calorie.view.exercise-goal' },
  { wakeWord: '看体重预测', scene: '10', kind: 'exec', key: 'calorie.view.predict', cli: 'calorie-cmd-read calorie.view.predict --params \'{"horizonDays":7,"window":"14d"}\'' },
  { wakeWord: '看异常诊断', scene: '10', kind: 'exec', key: 'calorie.view.anomaly', cli: 'calorie-cmd-read calorie.view.anomaly --params \'{"kind":"diet_over","window":"7d"}\'' },
  { wakeWord: '看禁忌扫描', scene: '05', kind: 'exec', key: 'calorie.view.contraindication', cli: 'calorie-cmd-read calorie.view.contraindication' },
  { wakeWord: '看去重报告', scene: '02', kind: 'exec', key: 'calorie.view.dedupe', cli: 'calorie-cmd-read calorie.view.dedupe' },
  { wakeWord: '看档案视图', scene: '07', kind: 'exec', key: 'calorie.view.profile', cli: 'calorie-cmd-read calorie.view.profile' },
  { wakeWord: '看力量总览', scene: '04', kind: 'exec', key: 'calorie.view.exercise-strength', cli: 'calorie-cmd-read calorie.view.exercise-strength --params \'{"window":"7d"}\'' },
  { wakeWord: '看有氧总览', scene: '04', kind: 'exec', key: 'calorie.view.exercise-cardio', cli: 'calorie-cmd-read calorie.view.exercise-cardio --params \'{"window":"7d"}\'' },
  { wakeWord: '看运动分类占比', scene: '04', kind: 'exec', key: 'calorie.view.exercise-distribution', cli: 'calorie-cmd-read calorie.view.exercise-distribution --params \'{"window":"7d"}\'' },
  { wakeWord: '看运动复盘', scene: '04', kind: 'exec', key: 'calorie.view.exercise-recap', cli: 'calorie-cmd-read calorie.view.exercise-recap --params \'{"window":"7d"}\'' },
  { wakeWord: '看训练计划复盘', scene: '05', kind: 'exec', key: 'calorie.view.exercise-review', cli: 'calorie-cmd-read calorie.view.exercise-review --params \'{"window":"custom","start":"<开始日期>","end":"<结束日期>"}\'' },
  { wakeWord: '看运动消耗趋势', scene: '04', kind: 'exec', key: 'calorie.view.exercise-trend', cli: 'calorie-cmd-read calorie.view.exercise-trend --params \'{"window":"7d"}\'' },
  { wakeWord: '查营养配比', scene: '02', kind: 'exec', key: 'calorie.view.nutrition-ratio', cli: 'calorie-cmd-read calorie.view.nutrition-ratio --params \'{"window":"7d"}\'' },
  { wakeWord: '看营养素明细', scene: '02', kind: 'exec', key: 'calorie.view.nutrition-detail', cli: 'calorie-cmd-read calorie.view.nutrition-detail --params \'{"window":"7d","entry":"detail"}\'' },
  { wakeWord: '看食品来源分布', scene: '02', kind: 'exec', key: 'calorie.view.source-stats', cli: 'calorie-cmd-read calorie.view.source-stats' },
  { wakeWord: '看今日饮水', scene: '02', kind: 'exec', key: 'calorie.view.today-water', cli: 'calorie-cmd-read calorie.view.today-water --params \'{"date":"今日"}\'' },
  { wakeWord: '看批量导入预览', scene: '02', kind: 'exec', key: 'calorie.view.batch-import-preview', cli: 'calorie-cmd-read calorie.view.batch-import-preview --params \'{"items":[{"foodName":"粥","calories":150,"protein":3,"date":"<日期>"}]}\'' },
  { wakeWord: '看热量趋势', scene: '10', kind: 'exec', key: 'calorie.view.calorie-trend', cli: 'calorie-cmd-read calorie.view.calorie-trend --params \'{"window":"7d"}\'' },
  { wakeWord: '查数据健康', scene: '10', kind: 'exec', key: 'calorie.view.lint-health', cli: 'calorie-cmd-read calorie.view.lint-health' },
  { wakeWord: '看整体趋势', scene: '10', kind: 'exec', key: 'calorie.view.long-trend', cli: 'calorie-cmd-read calorie.view.long-trend --params \'{"group":"weight_calorie","window":"30d"}\'' },
  { wakeWord: '看营养分析', scene: '02', kind: 'exec', key: 'calorie.view.nutrition-analysis', cli: 'calorie-cmd-read calorie.view.nutrition-analysis --params \'{"window":"7d"}\'' },
  { wakeWord: '看落地训练进度', scene: '05', kind: 'exec', key: 'calorie.view.process-progress', cli: 'calorie-cmd-read calorie.view.process-progress' },
  { wakeWord: '看复盘报告', scene: '10', kind: 'exec', key: 'calorie.view.review-template', cli: 'calorie-cmd-read calorie.view.review-template --params \'{"window":"7d"}\'' },
  { wakeWord: '看每日六因素', scene: '02', kind: 'exec', key: 'calorie.view.six-factors', cli: 'calorie-cmd-read calorie.view.six-factors --params \'{"date":"今日"}\'' },
  { wakeWord: '看围度向导', scene: '08', kind: 'exec', key: 'calorie.view.measure-wizard', cli: 'calorie-cmd-read calorie.view.measure-wizard' },
  { wakeWord: '看体脂向导', scene: '08', kind: 'exec', key: 'calorie.view.composition-wizard', cli: 'calorie-cmd-read calorie.view.composition-wizard' },
  { wakeWord: '看身材照向导', scene: '09', kind: 'exec', key: 'calorie.view.photo-log-wizard', cli: 'calorie-cmd-read calorie.view.photo-log-wizard' },
  { wakeWord: '看GIF规划器', scene: '09', kind: 'exec', key: 'calorie.view.gif-planner', cli: 'calorie-cmd-read calorie.view.gif-planner --params \'{"tag":"正面"}\'' },
  { wakeWord: '看档案预检', scene: '07', kind: 'exec', key: 'calorie.view.profile-wizard', cli: 'calorie-cmd-read calorie.view.profile-wizard' },
  { wakeWord: '看目标预检', scene: '06', kind: 'exec', key: 'calorie.view.goal-wizard', cli: 'calorie-cmd-read calorie.view.goal-wizard' },
  { wakeWord: '确认定训练计划', scene: '05', kind: 'exec', key: 'calorie.workout.plan-set', cli: 'calorie-cmd-read calorie.workout.plan-set --params \'{"plan":{"config":{"title":"示例计划","start_date":"2026-09-07","user_level":"中手","available_equipment":["瑜伽垫"]},"weeks":[{"week_number":1,"days":[{"day_of_week":1,"sessions":[{"session_label":"上肢","movements":[{"name":"俯卧撑"}]}]}]}]}}\'' },
  { wakeWord: '确认复制训练计划', scene: '05', kind: 'exec', key: 'calorie.workout.plan-copy', cli: 'calorie-cmd-read calorie.workout.plan-copy --params \'{"newTitle":"示例副本"}\'' },
  { wakeWord: '确认定一周计划', scene: '05', kind: 'exec', key: 'calorie.workout.plan-set-week', cli: 'calorie-cmd-read calorie.workout.plan-set-week --params \'{"week":1,"days":[{"dayOfWeek":1,"sessionLabel":"上肢","movements":[{"name":"俯卧撑"}]}]}\'' },
  { wakeWord: '确认加训练动作', scene: '05', kind: 'exec', key: 'calorie.workout.plan-add-movement', cli: 'calorie-cmd-read calorie.workout.plan-add-movement --params \'{"week":1,"dayOfWeek":1,"movement":{"name":"深蹲"}}\'' },
  { wakeWord: '确认定休息日', scene: '05', kind: 'exec', key: 'calorie.workout.plan-set-rest', cli: 'calorie-cmd-read calorie.workout.plan-set-rest --params \'{"week":1,"dayOfWeek":3}\'' },
  { wakeWord: '确认改训练计划', scene: '05', kind: 'exec', key: 'calorie.workout.plan-update', cli: 'calorie-cmd-read calorie.workout.plan-update --params \'{"title":"示例改名"}\'' },
  { wakeWord: '确认改某天训练', scene: '05', kind: 'exec', key: 'calorie.workout.plan-update-day', cli: 'calorie-cmd-read calorie.workout.plan-update-day --params \'{"week":1,"dayOfWeek":3,"newLabel":"下肢＋核心"}\'' },
  { wakeWord: '确认删某天训练', scene: '05', kind: 'exec', key: 'calorie.workout.plan-delete-day', cli: 'calorie-cmd-read calorie.workout.plan-delete-day --params \'{"week":1,"dayOfWeek":3}\'' },
  { wakeWord: '确认改动作', scene: '05', kind: 'exec', key: 'calorie.workout.plan-update-movement', cli: 'calorie-cmd-read calorie.workout.plan-update-movement --params \'{"oldMovement":"硬拉","newMovement":{"name":"杠铃划船"}}\'' },
  { wakeWord: '确认撤销训练计划', scene: '05', kind: 'exec', key: 'calorie.workout.plan-delete', cli: 'calorie-cmd-read calorie.workout.plan-delete --params \'{"confirm":true}\'' },
  { wakeWord: '选身材照', scene: '09', kind: 'exec', key: 'calorie.view.photo-picker', cli: 'calorie-cmd-read calorie.view.photo-picker' },
];

/** 1 条覆盖修复入口（FX-81-5：键失去唯一可跑入口时补的单命令入口） */
export const COVERAGE_REPAIR_ROUTES: readonly ExecWakeRoute[] = [
  { wakeWord: '看目标推荐', scene: '06', kind: 'exec', key: 'calorie.view.goal-recommend', cli: 'calorie-cmd-read calorie.view.goal-recommend --params \'{"profile":"cut"}\'' },
];

/** 全量路由（436 条 SoT ＋ 69 条新拟 ＋ 1 条覆盖修复） */
export const ALL_ROUTES: readonly WakeRoute[] = [...WAKE_ROUTES, ...NEW_KEY_ROUTES, ...COVERAGE_REPAIR_ROUTES];
