import type { Trigger } from './types.js';

/** 07-基础信息：4 唤醒词（SoT scripts/_triggers.py 原样拆分，顺序保留） */
export const SCENE_07_PROFILE: Trigger[] = [
{"category": "基础信息", "wake_word": "设置档案", "desc": "设置基础档案(身高/年龄/性别/活动量)", "main_prompt": {"cli": "calorie-cmd-read calorie.profile.set --params '{\"heightCm\":175,\"age\":30,\"gender\":\"male\",\"activityLevel\":\"moderate\"}'", "text": "请你加载技能 卡路里,执行唤醒词「设置档案」。\n\n我想设置基础档案(身高/年龄/性别/活动量)。如果我没说全,请一项一项问我,并根据我的日常情况推荐合适的活动量。请先出预检确认页给我看(改前值/待写四项/活动量五档),我确认后再写入。交付 HTML 时,文字只回复精简而全面概括的信息,文字不允许超过三句话。\n\n我的身高(cm):____\n年龄:____\n性别(男/女):____\n日常活动情况(选填,用于推荐活动量):____"}, "fill_hints": [], "variants": [], "key": "profile_setup", "name": "设置档案", "subfunction": "设置资料", "output_type": "receipt", "html_template": "templates/crud_receipt.html", "data_source": "calorie-cmd-read calorie.profile.set --params '{\"heightCm\":175,\"age\":30,\"gender\":\"male\",\"activityLevel\":\"moderate\"}'", "prompt_template": "请你加载技能 卡路里,执行唤醒词「设置档案」。\n\n我想设置基础档案(身高/年龄/性别/活动量)。如果我没说全,请一项一项问我,并根据我的日常情况推荐合适的活动量。请先出预检确认页给我看(改前值/待写四项/活动量五档),我确认后再写入。交付 HTML 时,文字只回复精简而全面概括的信息,文字不允许超过三句话。\n\n我的身高(cm):____\n年龄:____\n性别(男/女):____\n日常活动情况(选填,用于推荐活动量):____", "user_intent": "设置基础档案(身高/年龄/性别/活动量)", "data_fields": ["height_cm", "age", "gender", "activity_level", "activity_factor", "created_at"], "depends_on_external": false, "order": 0},
{"category": "基础信息", "wake_word": "设活动量", "desc": "单独设置活动量", "main_prompt": {"cli": "calorie-cmd-read calorie.profile.activity --params '{\"activityLevel\":\"active\"}'", "text": "请你加载技能 卡路里,执行唤醒词「设活动量」。\n\n我要单独设置活动量(久坐/轻度/中度/活跃/高度活跃)。请先出预检确认页给我看(活动量五档与 TDEE 影响/改前值),我确认后再写入。交付 HTML 时,文字只回复精简而全面概括的信息,文字不允许超过三句话。\n\n我的活动量(久坐/轻度/中度/活跃/高度活跃):____"}, "fill_hints": [], "variants": [], "key": "profile_set_activity", "name": "设活动量", "subfunction": "设置资料", "output_type": "receipt", "html_template": "templates/crud_receipt.html", "data_source": "calorie-cmd-read calorie.profile.activity --params '{\"activityLevel\":\"active\"}'", "prompt_template": "请你加载技能 卡路里,执行唤醒词「设活动量」。\n\n我要单独设置活动量(久坐/轻度/中度/活跃/高度活跃)。请先出预检确认页给我看(活动量五档与 TDEE 影响/改前值),我确认后再写入。交付 HTML 时,文字只回复精简而全面概括的信息,文字不允许超过三句话。\n\n我的活动量(久坐/轻度/中度/活跃/高度活跃):____", "user_intent": "单独设置活动量", "data_fields": ["activity_level", "activity_factor", "tdee"], "depends_on_external": false, "order": 1},
{"category": "基础信息", "wake_word": "改档案", "desc": "修改档案中的某个字段", "main_prompt": {"cli": "calorie-cmd-read calorie.profile.update --params '{\"field\":\"heightCm\",\"value\":176}'", "text": "请你加载技能 卡路里,执行唤醒词「改档案」。\n\n我要改档案里的字段(身高/年龄/性别/活动量/备注)。改之前请先确认我原来的值。请先出预检确认页给我看(改前值/改后对照),我确认后再写入。交付 HTML 时,文字只回复精简而全面概括的信息,文字不允许超过三句话。\n\n我要改的字段(允许一行一条,可改多个):\n身高(新值):____\n年龄(新值):____\n性别(新值):____\n活动量(新值):____\n备注(新值):____"}, "fill_hints": [], "variants": [], "key": "profile_update", "name": "改档案", "subfunction": "改资料", "output_type": "receipt", "html_template": "templates/crud_receipt.html", "data_source": "calorie-cmd-read calorie.profile.update --params '{\"field\":\"heightCm\",\"value\":176}'", "prompt_template": "请你加载技能 卡路里,执行唤醒词「改档案」。\n\n我要改档案里的字段(身高/年龄/性别/活动量/备注)。改之前请先确认我原来的值。请先出预检确认页给我看(改前值/改后对照),我确认后再写入。交付 HTML 时,文字只回复精简而全面概括的信息,文字不允许超过三句话。\n\n我要改的字段(允许一行一条,可改多个):\n身高(新值):____\n年龄(新值):____\n性别(新值):____\n活动量(新值):____\n备注(新值):____", "user_intent": "修改档案中的某个字段", "data_fields": ["height_cm", "age", "gender", "activity_level", "note", "bmi", "tdee"], "depends_on_external": false, "order": 0},
{"category": "基础信息", "wake_word": "查档案", "desc": "查看档案及最新体重与身体指标", "main_prompt": {"cli": "calorie-cmd-read calorie.view.profile", "text": "请你加载技能 卡路里,执行唤醒词「查档案」。\n\n我想看自己的完整档案。交付 HTML 时,文字只回复精简而全面概括的信息,文字不允许超过三句话。"}, "fill_hints": [], "variants": [], "key": "profile_view", "name": "查档案", "subfunction": "看档案", "output_type": "result", "html_template": "templates/crud_view.html", "data_source": "calorie-cmd-read calorie.view.profile", "prompt_template": "请你加载技能 卡路里,执行唤醒词「查档案」。\n\n我想看自己的完整档案。交付 HTML 时,文字只回复精简而全面概括的信息,文字不允许超过三句话。", "user_intent": "查看档案及最新体重与身体指标", "data_fields": ["height_cm", "age", "gender", "activity_level", "activity_factor", "weight_kg", "bmi", "bmr", "tdee"], "depends_on_external": false, "order": 0},
];
