import type { Trigger } from './types.js';

/** 01-主页：9 唤醒词（SoT scripts/_triggers.py 原样拆分，顺序保留） */
export const SCENE_01_HOME: Trigger[] = [
{"category": "主页", "wake_word": "看今日主页", "aliases": ["开卡路里", "卡路里面板", "今日卡路里"], "desc": "看今天主页的整体数据,了解今天哪些做得好/差", "main_prompt": {"cli": "python scripts/render_home.py --chain \"1.识别→2.读DB聚合→3.渲染\"", "text": "请你加载技能 卡路里,执行唤醒词「看今日主页」。\n\n我想看今天的主页 dashboard。交付 HTML 时,文字只回复精简而全面概括的信息,文字不允许超过三句话。"}, "fill_hints": [], "variants": [], "key": "home_today_overview", "name": "看今日主页", "subfunction": "看今日主页", "output_type": "result", "html_template": "templates/home_dashboard.html", "data_source": "python scripts/render_home.py --chain \"1.识别→2.读DB聚合→3.渲染\"", "prompt_template": "请你加载技能 卡路里,执行唤醒词「看今日主页」。\n\n我想看今天的主页 dashboard。交付 HTML 时,文字只回复精简而全面概括的信息,文字不允许超过三句话。", "user_intent": "看今天主页的整体数据,了解今天哪些做得好/差", "data_fields": ["today_kpi", "goal_progress", "weekly_trend", "streak_days"], "depends_on_external": false, "order": 0},
{"category": "主页", "wake_word": "看今日饮食概览", "desc": "只看今天饮食维度的完成情况", "main_prompt": {"cli": "python scripts/render_home.py --section diet --chain \"1.识别→2.读DB聚合→3.渲染\"", "text": "请你加载技能 卡路里,执行唤醒词「看今日饮食概览」。\n\n我想看今天饮食 widget。交付 HTML 时,文字只回复精简而全面概括的信息,文字不允许超过三句话。"}, "fill_hints": [], "variants": [], "key": "home_today_diet_overview", "name": "看今日饮食概览", "subfunction": "看今日主页", "output_type": "result", "html_template": "templates/home_dashboard.html", "data_source": "python scripts/render_home.py --section diet --chain \"1.识别→2.读DB聚合→3.渲染\"", "prompt_template": "请你加载技能 卡路里,执行唤醒词「看今日饮食概览」。\n\n我想看今天饮食 widget。交付 HTML 时,文字只回复精简而全面概括的信息,文字不允许超过三句话。", "user_intent": "只看今天饮食维度的完成情况", "data_fields": ["diet_calories", "diet_protein", "diet_goal", "diet_vs_target"], "depends_on_external": false, "order": 1},
{"category": "主页", "wake_word": "看今日运动概览", "desc": "只看今天运动维度的完成情况", "main_prompt": {"cli": "python scripts/render_home.py --section exercise --chain \"1.识别→2.读DB聚合→3.渲染\"", "text": "请你加载技能 卡路里,执行唤醒词「看今日运动概览」。\n\n我想看今天运动 widget。交付 HTML 时,文字只回复精简而全面概括的信息,文字不允许超过三句话。"}, "fill_hints": [], "variants": [], "key": "home_today_exercise_overview", "name": "看今日运动概览", "subfunction": "看今日主页", "output_type": "result", "html_template": "templates/home_dashboard.html", "data_source": "python scripts/render_home.py --section exercise --chain \"1.识别→2.读DB聚合→3.渲染\"", "prompt_template": "请你加载技能 卡路里,执行唤醒词「看今日运动概览」。\n\n我想看今天运动 widget。交付 HTML 时,文字只回复精简而全面概括的信息,文字不允许超过三句话。", "user_intent": "只看今天运动维度的完成情况", "data_fields": ["exercise_burn", "exercise_duration", "exercise_goal", "exercise_vs_target"], "depends_on_external": false, "order": 2},
{"category": "主页", "wake_word": "看今日体重概览", "desc": "只看今天体重维度的状态", "main_prompt": {"cli": "python scripts/render_home.py --section weight --chain \"1.识别→2.读DB聚合→3.渲染\"", "text": "请你加载技能 卡路里,执行唤醒词「看今日体重概览」。\n\n我想看今天体重 widget。交付 HTML 时,文字只回复精简而全面概括的信息,文字不允许超过三句话。"}, "fill_hints": [], "variants": [], "key": "home_today_weight_overview", "name": "看今日体重概览", "subfunction": "看今日主页", "output_type": "result", "html_template": "templates/home_dashboard.html", "data_source": "python scripts/render_home.py --section weight --chain \"1.识别→2.读DB聚合→3.渲染\"", "prompt_template": "请你加载技能 卡路里,执行唤醒词「看今日体重概览」。\n\n我想看今天体重 widget。交付 HTML 时,文字只回复精简而全面概括的信息,文字不允许超过三句话。", "user_intent": "只看今天体重维度的状态", "data_fields": ["latest_weight", "weight_goal_gap", "weight_delta_7d"], "depends_on_external": false, "order": 3},
{"category": "主页", "wake_word": "看今日目标进度", "desc": "看今天 4 项目标(热量/蛋白/饮水/运动)的完成度", "main_prompt": {"cli": "python scripts/render_home.py --section goals --chain \"1.识别→2.读DB聚合→3.渲染\"", "text": "请你加载技能 卡路里,执行唤醒词「看今日目标进度」。\n\n我想看今天 4 项目标(热量/蛋白/饮水/运动)完成度。交付 HTML 时,文字只回复精简而全面概括的信息,文字不允许超过三句话。"}, "fill_hints": [], "variants": [], "key": "home_today_goal_progress", "name": "看今日目标进度", "subfunction": "看今日主页", "output_type": "result", "html_template": "templates/home_dashboard.html", "data_source": "python scripts/render_home.py --section goals --chain \"1.识别→2.读DB聚合→3.渲染\"", "prompt_template": "请你加载技能 卡路里,执行唤醒词「看今日目标进度」。\n\n我想看今天 4 项目标(热量/蛋白/饮水/运动)完成度。交付 HTML 时,文字只回复精简而全面概括的信息,文字不允许超过三句话。", "user_intent": "看今天 4 项目标(热量/蛋白/饮水/运动)的完成度", "data_fields": ["goal_calorie_pct", "goal_protein_pct", "goal_water_pct", "goal_exercise_pct"], "depends_on_external": false, "order": 4},
{"category": "主页", "wake_word": "看本周主页", "desc": "看本周的整体数据总览", "main_prompt": {"cli": "python scripts/render_home.py --period week --chain \"1.识别→2.读DB聚合→3.渲染\"", "text": "请你加载技能 卡路里,执行唤醒词「看本周主页」。\n\n我想看本周 dashboard。交付 HTML 时,文字只回复精简而全面概括的信息,文字不允许超过三句话。"}, "fill_hints": [], "variants": [], "key": "home_week_overview", "name": "看本周主页", "subfunction": "看周期主页", "output_type": "result", "html_template": "templates/home_dashboard.html", "data_source": "python scripts/render_home.py --period week --chain \"1.识别→2.读DB聚合→3.渲染\"", "prompt_template": "请你加载技能 卡路里,执行唤醒词「看本周主页」。\n\n我想看本周 dashboard。交付 HTML 时,文字只回复精简而全面概括的信息,文字不允许超过三句话。", "user_intent": "看本周的整体数据总览", "data_fields": ["week_diet_total", "week_exercise_total", "week_weight_trend"], "depends_on_external": false, "order": 5},
{"category": "主页", "wake_word": "看本月主页", "desc": "看本月的整体数据总览", "main_prompt": {"cli": "python scripts/render_home.py --period month --chain \"1.识别→2.读DB聚合→3.渲染\"", "text": "请你加载技能 卡路里,执行唤醒词「看本月主页」。\n\n我想看本月 dashboard。交付 HTML 时,文字只回复精简而全面概括的信息,文字不允许超过三句话。"}, "fill_hints": [], "variants": [], "key": "home_month_overview", "name": "看本月主页", "subfunction": "看周期主页", "output_type": "result", "html_template": "templates/home_dashboard.html", "data_source": "python scripts/render_home.py --period month --chain \"1.识别→2.读DB聚合→3.渲染\"", "prompt_template": "请你加载技能 卡路里,执行唤醒词「看本月主页」。\n\n我想看本月 dashboard。交付 HTML 时,文字只回复精简而全面概括的信息,文字不允许超过三句话。", "user_intent": "看本月的整体数据总览", "data_fields": ["month_diet_total", "month_exercise_total", "month_weight_trend"], "depends_on_external": false, "order": 6},
{"category": "主页", "wake_word": "看连续记录天数", "desc": "看连续记录天数,获得激励", "main_prompt": {"cli": "python scripts/render_home.py --section streak --chain \"1.识别→2.读DB聚合→3.渲染\"", "text": "请你加载技能 卡路里,执行唤醒词「看连续记录天数」。\n\n我想看我的连续记录。交付 HTML 时,文字只回复精简而全面概括的信息,文字不允许超过三句话。"}, "fill_hints": [], "variants": [], "key": "home_streak_days", "name": "看连续记录天数", "subfunction": "看今日成就", "output_type": "result", "html_template": "templates/home_dashboard.html", "data_source": "python scripts/render_home.py --section streak --chain \"1.识别→2.读DB聚合→3.渲染\"", "prompt_template": "请你加载技能 卡路里,执行唤醒词「看连续记录天数」。\n\n我想看我的连续记录。交付 HTML 时,文字只回复精简而全面概括的信息,文字不允许超过三句话。", "user_intent": "看连续记录天数,获得激励", "data_fields": ["streak_current", "streak_longest"], "depends_on_external": false, "order": 7},
{"category": "主页", "wake_word": "看今日热量预算", "desc": "看今天还剩多少热量可吃", "main_prompt": {"cli": "python scripts/render_home.py --section budget --chain \"1.识别→2.读DB聚合→3.渲染\"", "text": "请你加载技能 卡路里,执行唤醒词「看今日热量预算」。\n\n我想看今天还能吃多少。交付 HTML 时,文字只回复精简而全面概括的信息,文字不允许超过三句话。"}, "fill_hints": [], "variants": [], "key": "home_today_budget", "name": "看今日热量预算", "subfunction": "看今日主页", "output_type": "result", "html_template": "templates/home_dashboard.html", "data_source": "python scripts/render_home.py --section budget --chain \"1.识别→2.读DB聚合→3.渲染\"", "prompt_template": "请你加载技能 卡路里,执行唤醒词「看今日热量预算」。\n\n我想看今天还能吃多少。交付 HTML 时,文字只回复精简而全面概括的信息,文字不允许超过三句话。", "user_intent": "看今天还剩多少热量可吃", "data_fields": ["tdee", "exercise_burn", "intake_today", "remaining_calories", "goal_gap"], "depends_on_external": false, "order": 8},
];
