/** undo-timeline · **样式段（形态 `track` 那一半：一条轨）**（取值一半，装配归 `style.ts`）。
 *
 *  纪律（与本层其余件同一份）：
 *   · 只经 `skinVar()` 读皮肤 —— 组件里**不写** `var(--ilife-…)`（兜底链只许住在 `skin/contract.ts`）；
 *   · 全部规则 scope 在 `.<prefix>page-ui` 之下；不写 `:root`／`!important`、不新增 token 名；
 *   · **宽度只许容器判**：`@container` ＋ 内在尺寸 ＋ `flex-wrap`；本文件不写任何宽度媒体查询。
 *
 *  几何契约（判据钉住）：
 *   · **竖轨是一根通的线**：行与行之间不留缝（`gap: 0`，留白由行的内距承担），
 *     横线**只画在文字那两列上**（画满整行会把竖轨切成一节一节）；首行从圆点起、末行到圆点止。
 *   · **三态不靠颜色**：`is-undoable` 实心点 ／ `is-undone` 空心点 ＋ 动作句删除线 ／
 *     `is-locked` 空心点 ＋ 一道斜杠；再加状态片上的字与按钮上的字——色只是第三重。
 *   · 时刻／读数／状态片**永不 `…` 截断**：长了折行（`overflow-wrap:anywhere`）。
 */
import { skinVar } from '../skin/contract.js';
import {
  UNDO_TIMELINE_CONTAINER,
  UNDO_TIMELINE_NARROW_PX,
  undoTimelineSlot,
  type UndoTimelineSlot,
} from './attrs.js';

/** 换行（仓库口径：不写字面换行转义）。 */
const LF = String.fromCharCode(10);

/** 圆点（12px）的中心离行顶多远（px）：竖轨的首末两端都按它收口。
 *  这个数同时进 `.dot` 的 `top` 与两个 `::before` 的收口长度——三处必须同源（判据断这一条）。 */
const DOT_CENTER_PX = 20;

/** 行内距（px）：**不放在 `.row` 上，放在三格里**——放行上，竖轨（它按网格区拉伸）就够不到内距那一段，
 *  行与行之间会出现 24px 的空档，一根通的线断成一节一节（本件真踩过，看图抓出来的）。 */
const PAD_Y_PX = 12;

/** 形态 `track` 的样式段。恒返回非空 CSS 文本。 */
export function undoTimelineTrackCss(input?: { readonly prefix?: string }): string {
  const p = input !== undefined && input !== null
    && typeof input.prefix === 'string' && input.prefix !== '' ? input.prefix : 'ilife-';
  const root = '.' + p + 'page-ui';
  /** **槽类名**（不带 scope）：写「某槽下的子件」时只许用它——把带 scope 的完整选择器再拼一次，
   *  会拼出 `.…-row .ilife-page-ui .…-say` 这种**永远不命中**的死规则（语法合法、编译不报错）。 */
  const c = (slot: UndoTimelineSlot): string => '.' + undoTimelineSlot(slot, p);
  /** **带 scope 的完整选择器**（一条规则打头用）：`.<page-ui> .<件>-<槽>`。 */
  const s = (slot: UndoTimelineSlot): string => root + ' ' + c(slot);

  return [
    '/* ── 形态 track：一条轨（一列改动） ─────────────────────────────── */',
    /* 行与行之间**不留缝**：留白由行的内距承担，竖轨才是一根通的线。 */
    s('list') + ' {',
    '  display: grid;',
    '  gap: 0;',
    '  min-width: 0;',
    '  padding: 0 14px;',
    '}',
    s('row') + ' {',
    '  display: grid;',
    '  grid-template-columns: 56px 12px minmax(0, 1fr) auto;',
    '  gap: 0 10px;',
    '  align-items: start;',
    '  min-width: 0;',
    '  /* **竖向内距不写在行上**：竖轨按网格区拉伸，行上的内距它够不到（见 `PAD_Y_PX` 的说明）。 */',
    '  padding: 0;',
    '}',
    /* 横线**只画在文字那两列上**（`body`／`act`）：画满整行会把左侧竖轨切成一节一节。 */
    s('row') + ' + ' + c('row') + ' > ' + c('body') + ',',
    s('row') + ' + ' + c('row') + ' > ' + c('act') + ' {',
    '  box-shadow: inset 0 1px 0 ' + skinVar('line') + ';',
    '}',
    s('time') + ' {',
    '  padding: ' + String(PAD_Y_PX + 2) + 'px 0 ' + String(PAD_Y_PX) + 'px;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 700;',
    '  font-variant-numeric: tabular-nums;',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 竖轨：线是 `::before`，圆点才是每一行自己的标记；首行从圆点起、末行到圆点止。 */',
    s('rail') + ' {',
    '  position: relative;',
    '  align-self: stretch;',
    '  width: 2px;',
    '  min-height: ' + String(DOT_CENTER_PX * 2) + 'px;',
    '  margin: 0 auto;',
    '}',
    s('rail') + '::before {',
    '  content: "";',
    '  position: absolute;',
    '  left: 0;',
    '  right: 0;',
    '  top: 0;',
    '  bottom: 0;',
    '  background: ' + skinVar('line') + ';',
    '}',
    s('row') + ':first-child ' + c('rail') + '::before {',
    '  top: ' + String(DOT_CENTER_PX) + 'px;',
    '}',
    s('row') + ':last-child ' + c('rail') + '::before {',
    '  bottom: auto;',
    '  height: ' + String(DOT_CENTER_PX) + 'px;',
    '}',
    /* 只有一行时它同时是首行与末行：上面两条叠加会在圆点下多出一段线头
       ⇒ 这一格直接不出线（首行从圆点起、末行到圆点止，落在同一个点上就是没有线）。 */
    s('row') + ':first-child:last-child ' + c('rail') + '::before {',
    '  display: none;',
    '}',
    /* 圆点三态三形：能撤＝实心强调圆（无文字的点走强调实底）／已撤＝空心细描边／不可撤＝空心＋一道斜杠。 */
    s('dot') + ' {',
    '  position: absolute;',
    '  left: 50%;',
    '  top: ' + String(DOT_CENTER_PX - 6) + 'px;',
    '  width: 12px;',
    '  height: 12px;',
    '  margin-left: -6px;',
    '  box-sizing: border-box;',
    '  border: 2px solid ' + skinVar('line') + ';',
    '  border-radius: 50%;',
    '  background: ' + skinVar('surface') + ';',
    '}',
    s('row') + '.is-undoable ' + c('dot') + ' {',
    '  border-color: ' + skinVar('accent') + ';',
    '  background: ' + skinVar('accent') + ';',
    '}',
    s('row') + '.is-locked ' + c('dot') + '::after {',
    '  content: "";',
    '  position: absolute;',
    '  left: -3px;',
    '  right: -3px;',
    '  top: 50%;',
    '  height: 2px;',
    '  margin-top: -1px;',
    '  transform: rotate(-45deg);',
    /* 这一道斜杠是**图形**，但它也得躲开「拿字色当面」那条禁令 ⇒ 从墨色算出来（`color-mix` 是合法面）。 */
    '  background: color-mix(in srgb, ' + skinVar('ink-3') + ' 78%, ' + skinVar('line') + ');',
    '}',
    s('body') + ' {',
    '  display: grid;',
    '  gap: 3px;',
    '  min-width: 0;',
    '  padding: ' + String(PAD_Y_PX) + 'px 0;',
    '}',
    s('say') + ' {',
    '  min-width: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 700;',
    '  line-height: 1.45;',
    '  overflow-wrap: anywhere;',
    '}',
    /* 已撤销那一条：动作句划掉（**形**），片上说清（**字**）——不是灰掉了事。 */
    s('row') + '.is-undone ' + c('say') + ' {',
    '  color: ' + skinVar('ink-3') + ';',
    '  text-decoration: line-through;',
    '}',
    s('row') + '.is-locked ' + c('say') + ' {',
    '  color: ' + skinVar('ink-2') + ';',
    '}',
    '/* 读数那一行：逐条一枚 `rdg`，**段间只靠列距**（标记里不写分隔符）。 */',
    s('eff') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 2px 12px;',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    s('rdg') + ' {',
    '  display: inline-flex;',
    '  flex-wrap: wrap;',
    '  align-items: baseline;',
    '  gap: 0 6px;',
    '  max-width: 100%;',
    '  min-width: 0;',
    '}',
    s('rlabel') + ' {',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-weight: 600;',
    '  overflow-wrap: anywhere;',
    '}',
    s('from') + ' {',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-variant-numeric: tabular-nums;',
    '  text-decoration: line-through;',
    '  overflow-wrap: anywhere;',
    '}',
    s('arrow') + ' {',
    '  color: ' + skinVar('ink-3') + ';',
    '}',
    s('to') + ' {',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-weight: 700;',
    '  font-variant-numeric: tabular-nums;',
    '  overflow-wrap: anywhere;',
    '}',
    s('note') + ' {',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 状态片／影响片：警告那一档走**描边**不走实底（这一行的焦点只能是右边那枚按钮）。 */',
    s('tag') + ' {',
    '  justify-self: start;',
    '  max-width: 100%;',
    '  padding: 2px 8px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    s('tag') + '.is-warn {',
    '  border-color: color-mix(in srgb, ' + skinVar('warn') + ' 42%, ' + skinVar('line') + ');',
    '  color: ' + skinVar('warn') + ';',
    '}',
    s('act') + ' {',
    '  display: flex;',
    '  flex-direction: column;',
    '  gap: 6px;',
    '  align-items: flex-end;',
    '  min-width: 0;',
    '  padding: ' + String(PAD_Y_PX) + 'px 0;',
    '}',
    s('error') + ' {',
    '  margin: 0;',
    '  max-width: 100%;',
    '  color: ' + skinVar('danger') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '  text-align: right;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 空态：设计过的那一种（不是留白）。 */',
    s('empty') + ' {',
    '  margin: 0;',
    '  padding: 20px 0;',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 就地摊开的那块回滚单：跨满整行，收在自己的行里（它的长相归 `style-impact.ts`）。 */',
    s('pick') + ' {',
    '  display: grid;',
    '  grid-column: 1 / -1;',
    '  margin-top: 10px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('surface-2') + ';',
    '  overflow: hidden;',
    '}',
    '/* `hidden` 必须显式重写：`display:grid` 的优先级高于浏览器默认那条 `[hidden]{display:none}`',
    '   ⇒ 不写这一条，「收起」当场失效（块还在、还能勾）。 */',
    s('pick') + '[hidden] {',
    '  display: none;',
    '}',
    '/* 窄容器（<' + String(UNDO_TIMELINE_NARROW_PX) + 'px）：时刻排到动作句上面、竖轨独占一列、',
    '   按钮占满整行（手指好按）。判的是**本件自己的宽度**（`@container` 按本件声明的容器名），',
    '   不是视口宽度——本件会被嵌进侧栏／面板／卡片。 */',
    '@container ' + UNDO_TIMELINE_CONTAINER + ' (max-width: ' + String(UNDO_TIMELINE_NARROW_PX) + 'px) {',
    '  ' + s('list') + ' {',
    '    padding: 0 10px;',
    '  }',
    '  ' + s('row') + ' {',
    '    grid-template-columns: 12px minmax(0, 1fr);',
    '    gap: 4px 8px;',
    '  }',
    /* 窄档拆成三行（时刻／文字／动作）⇒ 竖向节奏改由**首格的上内距**与**末格的下内距**承担，
       竖轨（它跨这三行）才盖得住整行——不然行与行之间又会空出一段没有线的缝。 */
    '  ' + s('time') + ' {',
    '    grid-column: 2;',
    '    grid-row: 1;',
    '    padding: ' + String(PAD_Y_PX) + 'px 0 2px;',
    '  }',
    '  ' + s('rail') + ' {',
    '    grid-column: 1;',
    '    grid-row: 1 / span 3;',
    '  }',
    '  ' + s('body') + ' {',
    '    grid-column: 2;',
    '    padding: 0 0 4px;',
    '  }',
    '  ' + s('act') + ' {',
    '    grid-column: 2;',
    '    align-items: stretch;',
    '    padding: 0 0 ' + String(PAD_Y_PX) + 'px;',
    '  }',
    '  ' + s('act') + ' > ' + c('bt') + ' {',
    '    width: 100%;',
    '  }',
    /* 窄档那一行占满整幅 ⇒ 错态那句改**左对齐**（右对齐在一块满宽按钮下面读起来是断的）。 */
    '  ' + s('error') + ' {',
    '    text-align: start;',
    '  }',
    /* 横线跟着**首格**走（窄档首格是时刻那格）——宽档那两条在这里让位。 */
    '  ' + s('row') + ' + ' + c('row') + ' > ' + c('body') + ',',
    '  ' + s('row') + ' + ' + c('row') + ' > ' + c('act') + ' {',
    '    box-shadow: none;',
    '    padding-top: 0;',
    '  }',
    '  ' + s('row') + ' + ' + c('row') + ' > ' + c('time') + ' {',
    '    box-shadow: inset 0 1px 0 ' + skinVar('line') + ';',
    '  }',
    '}',
  ].join(LF);
}
