/** undo-timeline · **样式段（回滚单那一半：影响面清单）**（取值一半，装配归 `style.ts`）。
 *
 *  这一半同时长在两个地方：形态 `impact` 的**整张卡**，与形态 `track` 里每一行**就地摊开的那一块**
 *  ——同一份标记、同一份长相（`render.ts` 的 `impactInnerHtml` 只写一遍）。
 *
 *  几何契约（判据钉住）：
 *   · **整行是命中区**（`min-height: 56px` 的 `<label>`）；勾选框的命中盒 44×44，视觉盒 24×24
 *     （原生 `<input>` 铺满命中盒，视觉隐藏走 `opacity: 0`，**不是** `display: none`——那会把键盘可达性一起干掉）；
 *   · **勾上的那一行至少两重非颜色标记**：方块里的对钩 `✓`（字）＋ 行左端 3px 强调侧标（形）；
 *   · 行右端读数（`3 条`）**永不 `…` 截断**；勾不动的行**写出为什么**（不只画一枚灰方块）。
 */
import { skinVar } from '../skin/contract.js';
import {
  UNDO_TIMELINE_CONTAINER,
  UNDO_TIMELINE_GAP_PX,
  UNDO_TIMELINE_NARROW_PX,
  UNDO_TIMELINE_ROW_MIN_PX,
  undoTimelineSlot,
  type UndoTimelineSlot,
} from './attrs.js';

/** 换行（仓库口径：不写字面换行转义）。 */
const LF = String.fromCharCode(10);

/** 形态 `impact`／`track` 共用的回滚单样式段。恒返回非空 CSS 文本。 */
export function undoTimelineImpactCss(input?: { readonly prefix?: string }): string {
  const p = input !== undefined && input !== null
    && typeof input.prefix === 'string' && input.prefix !== '' ? input.prefix : 'ilife-';
  const root = '.' + p + 'page-ui';
  /** **槽类名**（不带 scope）：嵌套选择器只用它（scope 一条里只许出现一次）。 */
  const c = (slot: UndoTimelineSlot): string => '.' + undoTimelineSlot(slot, p);
  /** **带 scope 的完整选择器**（一条规则打头用）。 */
  const s = (slot: UndoTimelineSlot): string => root + ' ' + c(slot);
  const box = root + ' .' + p + 'block-undo-timeline';

  return [
    '/* ── 回滚单：一次改动的影响面清单（形态 impact 的整张卡／track 里摊开的那一块） ── */',
    s('pkh') + ' {',
    '  display: grid;',
    '  gap: 2px;',
    '  padding: 12px 14px;',
    '  min-width: 0;',
    '  border-bottom: 1px solid ' + skinVar('line') + ';',
    '}',
    '/* 单独成件那一张（形态 impact）：头是这一块的面，走次要面，好与列表分开。 */',
    box + '.is-impact > ' + c('pkh') + ' {',
    '  background: ' + skinVar('surface-2') + ';',
    '}',
    s('pkt') + ' {',
    '  min-width: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 700;',
    '  line-height: 1.45;',
    '  overflow-wrap: anywhere;',
    '}',
    s('pkn') + ' {',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    s('picks') + ' {',
    '  display: grid;',
    '  min-width: 0;',
    '}',
    '/* 一行：**整行是 `<label>`**（点这一行的任何地方都算勾/取消），命中区 ≥56px。 */',
    s('item') + ' {',
    '  display: grid;',
    '  grid-template-columns: auto minmax(0, 1fr) auto;',
    '  gap: 2px 10px;',
    '  align-items: center;',
    '  min-height: ' + String(UNDO_TIMELINE_ROW_MIN_PX) + 'px;',
    '  padding: 8px 14px;',
    '  border-top: 1px solid ' + skinVar('line') + ';',
    '  cursor: pointer;',
    '}',
    s('item') + ':first-child {',
    '  border-top: 0;',
    '}',
    '/* 勾上的那一行：底走次要面 ＋ 左端一条 3px 强调侧标（**形**的一重，行内主字仍 `ink`）。 */',
    s('item') + ':has(input:checked) {',
    '  background: ' + skinVar('surface-2') + ';',
    '  box-shadow: inset 3px 0 0 ' + skinVar('accent') + ';',
    '}',
    s('item') + '.is-off {',
    '  cursor: not-allowed;',
    '}',
    '/* 勾选框的**命中盒** 44×44；视觉盒 24×24；原生框铺满命中盒（视觉隐藏不是 `display:none`）。 */',
    s('check') + ' {',
    '  position: relative;',
    '  display: grid;',
    '  place-items: center;',
    '  width: 44px;',
    '  height: 44px;',
    '}',
    s('check') + ' input {',
    '  position: absolute;',
    '  inset: 0;',
    '  margin: 0;',
    '  opacity: 0;',
    '  cursor: pointer;',
    '}',
    s('check') + ' input[disabled] {',
    '  cursor: not-allowed;',
    '}',
    s('box') + ' {',
    '  position: relative;',
    '  width: 24px;',
    '  height: 24px;',
    '  box-sizing: border-box;',
    '  border: 2px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('surface') + ';',
    '}',
    '/* 勾上＝强调**实底** ＋ 一枚对钩（无文字的点／格走强调实底；对钩是图形，不是正文）。 */',
    s('check') + ' input:checked + ' + c('box') + ' {',
    '  border-color: ' + skinVar('accent') + ';',
    '  background: ' + skinVar('accent') + ';',
    '}',
    s('check') + ' input:checked + ' + c('box') + '::after {',
    '  content: "\\2713";',
    '  position: absolute;',
    '  inset: 0;',
    '  display: grid;',
    '  place-items: center;',
    '  color: ' + skinVar('accent-ink') + ';',
    '  font-size: 15px;',
    '  font-weight: 700;',
    '  line-height: 1;',
    '}',
    '/* 勾不动那一档：方块走虚线（**形**），原因写在行里（**字**）——不只画一枚灰方块。 */',
    s('check') + ' input[disabled] + ' + c('box') + ' {',
    '  border-style: dashed;',
    '  border-color: ' + skinVar('line') + ';',
    '  background: ' + skinVar('surface') + ';',
    '}',
    '/* 焦点环画在视觉盒上（原生框是透明的，焦点得看得见）。 */',
    s('check') + ' input:focus-visible + ' + c('box') + ' {',
    '  outline: 2px solid ' + skinVar('accent') + ';',
    '  outline-offset: 2px;',
    '}',
    s('ibody') + ' {',
    '  display: grid;',
    '  gap: 2px;',
    '  min-width: 0;',
    '}',
    s('ititle') + ' {',
    '  min-width: 0;',
    '  color: ' + skinVar('ink') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 700;',
    '  line-height: 1.45;',
    '  overflow-wrap: anywhere;',
    '}',
    s('inote') + ' {',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-style: normal;',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    s('why') + ' {',
    '  min-width: 0;',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-style: normal;',
    '  line-height: 1.6;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 行右端读数：数一档（等宽 ＋ 加粗），**永不 `…` 截断**。 */',
    s('count') + ' {',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 700;',
    '  font-variant-numeric: tabular-nums;',
    '  text-align: right;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 窄容器（<' + String(UNDO_TIMELINE_NARROW_PX) + 'px）：行右端那枚读数排到文字下面',
    '   （挤在右边会把「一句话后果」压成一列孤字）。判的是**本件自己的宽度**。 */',
    '@container ' + UNDO_TIMELINE_CONTAINER + ' (max-width: ' + String(UNDO_TIMELINE_NARROW_PX) + 'px) {',
    '  ' + s('item') + ' {',
    '    grid-template-columns: auto minmax(0, 1fr);',
    '    gap: 2px ' + String(UNDO_TIMELINE_GAP_PX) + 'px;',
    '    padding: 8px 10px;',
    '  }',
    '  ' + s('count') + ' {',
    '    grid-column: 2;',
    '    text-align: left;',
    '  }',
    '  ' + s('pkh') + ' {',
    '    padding: 12px 10px;',
    '  }',
    '}',
  ].join(LF);
}
