/** reminder-setter · **形态 `track`（一天刻度上摆点）的样式段**（本件样式来源的第二份：见 `_style-sources.mjs`）。
 *
 *  为什么拆出来：两档的样式加起来超本包告警线 350 行（拆法先例：`date-range/style-calendar.ts`）。
 *  按件读样式源码的判据一律经 `_style-sources.mjs`，拆出去这半仍在扫面里。
 *
 *  三条形上的口径（判据钉住，数字只写在 `attrs.ts` 一处）：
 *   · **刻度条＝一天那一根尺**：24 格刻度线由 `background-size: calc(100% / 24)` 铺出来（不摆 24 个元素）；
 *   · **一枚点＝一个 44×44 的命中盒**，落点由 `at` 算出的 `place` 写进行内 `left`；两端各让出半个命中盒，
 *     最左／最右那一条也不会顶出刻度条；
 *   · **选中那一条**＝形（圈 ＋ 实心点 ＋ 描边）＋ 字（序号徽章、图例那行加粗）＋ 色（软底／主色），
 *     三样一起变——不只靠颜色（手机与电脑端同时在用）。
 */
import { skinVar } from '../skin/contract.js';
import {
  REMINDER_SETTER_BOX_PX,
  REMINDER_SETTER_DAY_MIN,
  REMINDER_SETTER_GAP_PX,
  REMINDER_SETTER_HOVER_QUERY,
  REMINDER_SETTER_TOUCH_PX,
  reminderSetterSlot,
} from './attrs.js';

/** 换行（仓库口径：不写字面换行转义）。 */
const LF = String.fromCharCode(10);

/** 形态 `track` 的样式段（前缀由调用方给：`reminderSetterCss()` 那一段自己读同一个缺省）。 */
export function reminderSetterTrackCss(p: string): string {
  const root = '.' + p + 'page-ui';
  const sc = (slot: Parameters<typeof reminderSetterSlot>[0]): string => '.' + reminderSetterSlot(slot, p);
  const s = (slot: Parameters<typeof reminderSetterSlot>[0]): string => root + ' ' + sc(slot);
  const touch = String(REMINDER_SETTER_TOUCH_PX) + 'px';
  const gap = String(REMINDER_SETTER_GAP_PX) + 'px';
  /** 尺上每小时一道刻度线（一天 24 道）：格宽＝整条尺的 1/24。 */
  const ticks = String(REMINDER_SETTER_DAY_MIN / 60);
  return [
    '/* reminder-setter（提醒设置 · 形态 track「一天刻度上摆点」）：一天那条刻度上摆着好几条提醒，',
    '   点其中一枚点就改它自己的三个决定；屏上只有四样——刻度、小时数、图例、选中那条的决定面板 */',
    '/* （没有抬头、没有复述那一行：图例那一行就是「现在设的是多少」）。 */',
    '/* 一天那一整块：**宿主那张卡就是「一天这张纸」**（不再套第二层边与投影）。 */',
    s('day') + ' {',
    '  display: grid;',
    '  gap: ' + gap + ';',
    '  min-width: 0;',
    '}',
    '/* 刻度：上面给命中盒留出那一整条高度，底下那 10px 是那条尺本身（由 ::before 铺出来）。 */',
    s('ruler') + ' {',
    '  position: relative;',
    '  padding-top: ' + touch + ';',
    '  min-width: 0;',
    '}',
    '/* 尺＝一条贯穿的基线（24 格刻度线按格宽铺，不摆 24 个元素）。 */',
    s('ruler') + '::before {',
    '  content: "";',
    '  display: block;',
    '  height: 10px;',
    '  border-radius: ' + skinVar('radius-pill') + ';',
    '  background-color: ' + skinVar('edge') + ';',
    '  background-image: linear-gradient(to right, ' + skinVar('line') + ' 0 1px, transparent 1px);',
    '  background-size: calc(100% / ' + ticks + ') 100%;',
    '  background-repeat: repeat-x;',
    '}',
    '/* 一枚提醒点：**命中盒就是这枚 44×44 的按钮**（形是里面的徽章 ＋ 那一枚点）。',
    '   落点由行内 `left` 给（两端各让出半个命中盒）；底边贴着尺的上沿。 */',
    s('dot') + ' {',
    '  position: absolute;',
    '  bottom: 10px;',
    '  display: grid;',
    '  align-content: end;',
    '  justify-items: center;',
    '  gap: 4px;',
    '  width: ' + touch + ';',
    '  height: ' + touch + ';',
    '  padding: 0;',
    '  border: 0;',
    '  background: transparent;',
    '  font-family: ' + skinVar('font') + ';',
    '  cursor: pointer;',
    '  transform: translateX(-50%);',
    '  transition: transform 80ms ease;',
    '}',
    '/* 徽章印序号（图例那一行印同一个号：两处对得起来）。 */',
    s('dot') + ' > b {',
    '  display: grid;',
    '  place-items: center;',
    '  width: 20px;',
    '  height: 20px;',
    '  flex: 0 0 auto;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-pill') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: 11px;',
    '  font-weight: 700;',
    '  font-variant-numeric: tabular-nums;',
    '}',
    '/* 那一枚点本身：没选中时是尺上的一枚圆点（形：实心圆）。 */',
    s('dot') + ' > i {',
    '  display: block;',
    '  width: 18px;',
    '  height: 18px;',
    '  border: 2px solid ' + skinVar('surface') + ';',
    '  border-radius: 50%;',
    '  background: ' + skinVar('line') + ';',
    '}',
    '/* 选中那一条：**形**（点外加一圈描边）＋ **色**（主色实底）＋ **字**（徽章走软底与主色字）。 */',
    s('dot') + '.is-on > i {',
    '  background: ' + skinVar('accent') + ';',
    '  outline: 2px solid ' + skinVar('accent') + ';',
    '  outline-offset: 2px;',
    '}',
    s('dot') + '.is-on > b {',
    '  border-color: ' + skinVar('accent') + ';',
    '  background: ' + skinVar('accent-soft') + ';',
    '  color: ' + skinVar('accent-text') + ';',
    '}',
    '/* 尺下面那几个小时数（0 点起，每 6 小时一格）：弱文字档，等宽数字。 */',
    s('hours') + ' {',
    '  display: flex;',
    '  justify-content: space-between;',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '  font-variant-numeric: tabular-nums;',
    '}',
    '/* 图例：一行一条提醒（宽档按格排开，窄档自然落成一列）。 */',
    s('legend') + ' {',
    '  display: grid;',
    '  grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));',
    /* 行与行之间也留那道缝：图例每一行是**可点件**，相邻 ≥`REMINDER_SETTER_GAP_PX` 是底线。 */
    '  gap: ' + gap + ';',
    '  margin-top: 2px;',
    '  border-top: 1px solid ' + skinVar('line') + ';',
    '  min-width: 0;',
    '}',
    '/* 图例里的一行＝可点件（命中盒不小于触控地板）：点它就是「改这一条」。 */',
    s('lg') + ' {',
    '  display: flex;',
    '  align-items: center;',
    '  gap: ' + gap + ';',
    '  min-height: ' + touch + ';',
    '  padding: 0 2px;',
    '  border: 0;',
    '  border-bottom: 1px solid ' + skinVar('edge') + ';',
    '  background: transparent;',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  line-height: 1.45;',
    '  text-align: left;',
    '  cursor: pointer;',
    '  transition: transform 80ms ease;',
    '  overflow-wrap: anywhere;',
    '}',
    s('lg') + ' > b {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  width: ' + String(REMINDER_SETTER_BOX_PX) + 'px;',
    '  height: ' + String(REMINDER_SETTER_BOX_PX) + 'px;',
    '  flex: 0 0 auto;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-pill') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: 11px;',
    '  font-weight: 700;',
    '}',
    '/* 选中那一条：字重 ＋ 主色序号徽章 ＋ 那道线换成主色（形／字／色三样一起变）。 */',
    s('lg') + '.is-on {',
    '  color: ' + skinVar('ink') + ';',
    '  font-weight: 700;',
    '  border-bottom-color: ' + skinVar('accent') + ';',
    '}',
    s('lg') + '.is-on > b {',
    '  border-color: ' + skinVar('accent') + ';',
    '  background: ' + skinVar('accent-soft') + ';',
    '  color: ' + skinVar('accent-text') + ';',
    '}',
    '/* 选中那一条的三个决定：**这块面板是唯一的焦点**（软底把它框成「正在改的就是这一条」）。 */',
    s('pick') + ' {',
    '  margin-top: 12px;',
    '  padding: 2px 12px 6px;',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('surface-2') + ';',
    '}',
    s('pick') + ' ' + sc('row') + ' {',
    '  padding: 10px 0 12px;',
    '}',
    '@media ' + REMINDER_SETTER_HOVER_QUERY + ' {',
    '  ' + s('dot') + ':hover > i, ' + s('lg') + ':hover {',
    '    border-color: ' + skinVar('accent') + ';',
    '  }',
    '}',
  ].join(LF);
}
