/** reminder-setter · **样式段**（本件唯一的样式来源）。
 *
 *  纪律（与本节其余件同一份）：
 *   · 只经 `skinVar()` 读皮肤 —— 组件里**不写** `var(--ilife-…)`（兜底链只许住在 `skin/contract.ts`）；
 *   · 全部规则 scope 在 `.<prefix>page-ui` 之下（不开本配方的页零命中）；不写 `:root`／`!important`、不新增 token 名；
 *   · **宽度只许容器判**：本件自己声明容器，窄档走 `@container`；媒体查询只判设备能力
 *     （悬停是不是增强、要不要减动效），**一条视口宽度查询都没有**；
 *   · 时间与日期读数**永不截断**：样式段里没有 `text-overflow`／`line-clamp`／`nowrap`（窄档只换行）。
 *
 *  三条形上的口径（判据钉住，数字只写在 `attrs.ts` 一处）：
 *   · 卡加一层 `shadow`（形态 `decisions` 那一档；`paper`／`broadsheet` 的取值本就是 `none`，
 *     那两套的纸面有自己的边与纸纹，不该再浮一层）；
 *   · **三个决定的隔线走发丝线**（`line` 那一档）：弱到 `line` 掺透明那一档在 `neutral` 下几乎看不见，
 *     三块会摊成一片白纸；
 *   · **单选那枚的勾选槽位是固定的** `REMINDER_SETTER_TICK_PX` 宽（未选也留）：勾上时不把档名顶歪，
 *     一排胶囊的左右沿才齐平。
 */
import { skinVar } from '../skin/contract.js';
import {
  REMINDER_SETTER_BOX_PX,
  REMINDER_SETTER_CONTAINER,
  REMINDER_SETTER_GAP_PX,
  REMINDER_SETTER_HOVER_QUERY,
  REMINDER_SETTER_LABEL_PX,
  REMINDER_SETTER_NARROW_PX,
  REMINDER_SETTER_TICK,
  REMINDER_SETTER_TICK_PX,
  REMINDER_SETTER_TOUCH_PX,
  reminderSetterSlot,
  type ReminderSetterSlot,
} from './attrs.js';
import { reminderSetterTrackCss } from './style-track.js';

/** 换行（仓库口径：不写字面换行转义）。 */
const LF = String.fromCharCode(10);

/** 本组件的样式段。恒返回非空 CSS 文本。 */
export function reminderSetterCss(input?: { readonly prefix?: string }): string {
  const p = input !== undefined && input !== null
    && typeof input.prefix === 'string' && input.prefix !== '' ? input.prefix : 'ilife-';
  const root = '.' + p + 'page-ui';
  const box = root + ' .' + p + 'block-reminder-setter';
  /** **槽类名**（带点、不带 scope）：只许用在**同一条选择器的后半截**（如 `row + row` 的第二个 `row`）——
   *  那时整条已经被前半截的 `.<prefix>page-ui` 罩住了，后半截再拼一遍 scope 就会拼出永不命中的死规则。
   *  **逗号列表里的每一段不许用它**：那几段各是一条独立选择器，得各自带上 scope（见下一条）。
   *  注意 `reminderSetterSlot()` 只产**类名本身**（没有那个点），点由这里补。 */
  const sc = (slot: ReminderSetterSlot): string => '.' + reminderSetterSlot(slot, p);
  /** **带 scope 的完整选择器**（一条规则打头用；逗号列表里每一段都用它）。
   *
   *  **选择器列表里每一段都走它**：`s('a') + ', ' + s('b')`。
   *  逗号列表里那几段如果只写槽类名（不带 `.<prefix>page-ui` 那几个字），它们就是**没 scope 的**——
   *  不开本配方的页也会命中（规则漏出去），而判据侧要求「每一条选择器都 scope 在 `.ilife-page-ui` 之下」。 */
  const s = (slot: ReminderSetterSlot): string => root + ' ' + sc(slot);
  const touch = String(REMINDER_SETTER_TOUCH_PX) + 'px';
  const gap = String(REMINDER_SETTER_GAP_PX) + 'px';
  const hover = '@media ' + REMINDER_SETTER_HOVER_QUERY;

  return [
    '/* reminder-setter（提醒设置 · 形态 decisions「一行一个决定」）：什么时候响 ／ 提前多久 ／ 走哪条通知，',
    '   一行只做一个决定；日期与时间走两枚步进键夹一枚读数（手机上点得到，不用精确拖点）。',
    '   屏上只有三层话：它是哪条提醒、三行的可点项、一行复述（旁白与口径句住在 README 里）。 */',
    s('host') + ' {',
    /* 宽度判据的落点：本件是**自己的容器**——嵌进侧栏／面板／卡片时照样按自己的宽度折。 */
    '  container-type: inline-size;',
    '  container-name: ' + REMINDER_SETTER_CONTAINER + ';',
    '  display: block;',
    '  min-width: 0;',
    '  padding: 2px 14px 12px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius') + ';',
    '  background: ' + skinVar('surface') + ';',
    /* 「卡加一层 shadow」：这一档在这一套语言里是真投影；零投影那几套本来就取 none。 */
    '  box-shadow: ' + skinVar('shadow') + ';',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-body') + ';',
    '  line-height: 1.5;',
    '}',
    '/* 抬头：这一组设定在给哪条提醒设（它是什么）。长了换行，不截断。 */',
    s('head') + ' {',
    '  margin: 0;',
    '  padding: 12px 0 2px;',
    '  color: ' + skinVar('ink') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 700;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 一行决定：宽档左标签右控件（标签列宽上限取常量）；窄档在下面折成上下两段。 */',
    s('row') + ' {',
    '  display: grid;',
    '  grid-template-columns: minmax(0, ' + String(REMINDER_SETTER_LABEL_PX) + 'px) minmax(0, 1fr);',
    '  gap: ' + gap + ' 16px;',
    '  padding: 12px 0 14px;',
    '  min-width: 0;',
    '}',
    '/* **三个决定之间**那道隔线走发丝线（`line` 那一档）。',
    '   写 `row + row`：这块卡上恰好两道线（头一条决定不划线，抬头与它是同一条的上下两半）。 */',
    s('row') + ' + ' + sc('row') + ' {',
    '  border-top: 1px solid ' + skinVar('line') + ';',
    '}',
    s('label') + ' {',
    '  grid-column: 1;',
    '  margin: 0;',
    '  align-self: start;',
    '  color: ' + skinVar('ink') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 700;',
    '  overflow-wrap: anywhere;',
    '}',
    s('ctl') + ' {',
    '  grid-column: 2;',
    '  display: grid;',
    '  gap: ' + gap + ';',
    '  min-width: 0;',
    '}',
    '/* 这两排是**同一个东西的两种形状**：单选是胶囊（`tray`／`chip`），多选是方框（`rack`／`check`）。 */',
    s('tray') + ', ' + s('rack') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  gap: ' + gap + ';',
    '  min-width: 0;',
    '}',
    '/* 单选的**一枚胶囊**：命中盒＝胶囊本身（≥触控地板）。',
    '   档名长了换行（不截断），一行放不下就折到下一行。 */',
    s('chip') + ' {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  gap: 6px;',
    '  min-height: ' + touch + ';',
    '  padding: 0 14px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-pill') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '  cursor: pointer;',
    '  transition: transform 80ms ease;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* **勾选槽位固定**（未选也留这么宽）：勾上时不把档名顶歪，一排胶囊的左右沿才齐平。 */',
    s('chip') + '::before {',
    '  content: "";',
    '  display: inline-block;',
    '  width: ' + String(REMINDER_SETTER_TICK_PX) + 'px;',
    '  flex: 0 0 auto;',
    '  text-align: center;',
    '}',
    '/* 选中的那一枚是「有文字的选中面」那一档：软底 ＋ 主色字 ＋ 主色描边（不是实心墨块）。 */',
    s('chip') + '.is-on {',
    '  background: ' + skinVar('accent-soft') + ';',
    '  border-color: ' + skinVar('accent') + ';',
    '  color: ' + skinVar('accent-text') + ';',
    '  font-weight: 700;',
    '}',
    s('chip') + '.is-on::before {',
    '  content: "' + REMINDER_SETTER_TICK + '";',
    '  color: ' + skinVar('accent') + ';',
    '  font-weight: 700;',
    '}',
    '/* 两个步进位并排（时间 ＋ 第一次从）；窄档各自占满一行。 */',
    s('fields') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  gap: ' + gap + ' 16px;',
    '  min-width: 0;',
    '}',
    s('field') + ' {',
    '  display: flex;',
    '  flex-wrap: wrap;',
    '  align-items: center;',
    '  gap: ' + gap + ';',
    '  min-width: 0;',
    '}',
    '/* 步进位的名字走弱文字档（它是这一格的说明，要读得到但不抢读数）。 */',
    s('flabel') + ' {',
    '  color: ' + skinVar('ink-3') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '  overflow-wrap: anywhere;',
    '}',
    s('stepper') + ' {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  gap: ' + gap + ';',
    '  min-width: 0;',
    '}',
    '/* 两枚步进键：44 见方（触控地板），是可点件里最小的一号。 */',
    s('dec') + ', ' + s('inc') + ' {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  justify-content: center;',
    '  width: ' + touch + ';',
    '  height: ' + touch + ';',
    '  flex: none;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  color: ' + skinVar('ink-2') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: 16px;',
    '  line-height: 1;',
    '  cursor: pointer;',
    '  transition: transform 80ms ease;',
    '}',
    s('dec') + ':active, ' + s('inc') + ':active { transform: scale(.98); }',
    '/* 中间那枚读数：**机器读数 `data-ilife-reminder-time／start` 的另一种摆法**，等宽数字、永不截断。 */',
    s('num') + ' {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  min-height: ' + touch + ';',
    '  padding: 0 2px;',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: ' + skinVar('fs-sm') + ';',
    '  font-weight: 700;',
    '  font-variant-numeric: tabular-nums;',
    '  overflow-wrap: anywhere;',
    '}',
    '/* 多选的**一枚方框**：形是方框＋方勾（这条可以多选），与单选的胶囊分得开。 */',
    s('check') + ' {',
    '  display: inline-flex;',
    '  align-items: center;',
    '  gap: ' + gap + ';',
    '  min-height: ' + touch + ';',
    '  padding: 0 14px;',
    '  border: 1px solid ' + skinVar('line') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('surface') + ';',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 600;',
    '  cursor: pointer;',
    '  transition: transform 80ms ease;',
    '  overflow-wrap: anywhere;',
    '}',
    s('check') + '::before {',
    '  content: "";',
    '  width: ' + String(REMINDER_SETTER_BOX_PX) + 'px;',
    '  height: ' + String(REMINDER_SETTER_BOX_PX) + 'px;',
    '  flex: 0 0 auto;',
    '  border: 2px solid ' + skinVar('line') + ';',
    '  border-radius: 3px;',
    '  background: ' + skinVar('surface') + ';',
    '}',
    s('check') + '.is-on {',
    '  background: ' + skinVar('accent-soft') + ';',
    '  border-color: ' + skinVar('accent') + ';',
    '  color: ' + skinVar('accent-text') + ';',
    '  font-weight: 700;',
    '}',
    '/* 勾上那枚方框走**主色实底**（框里只有一枚勾，没有正文级的小字——法条那一档正是为勾准备的）。 */',
    s('check') + '.is-on::before {',
    '  content: "' + REMINDER_SETTER_TICK + '";',
    '  display: grid;',
    '  place-items: center;',
    '  border-color: ' + skinVar('accent') + ';',
    '  background: ' + skinVar('accent') + ';',
    '  color: ' + skinVar('accent-ink') + ';',
    '  font-size: 12px;',
    '  font-weight: 700;',
    '}',
    '/* **全件唯一的读数行**：一行说完现在设的是多少（软底框把「设完是这样」框住）。 */',
    s('read') + ' {',
    '  margin: 12px 0 0;',
    '  padding: 10px 12px;',
    '  border: 1px solid ' + skinVar('accent') + ';',
    '  border-radius: ' + skinVar('radius-sm') + ';',
    '  background: ' + skinVar('surface-2') + ';',
    '  color: ' + skinVar('ink') + ';',
    '  font-family: ' + skinVar('font-num') + ';',
    '  font-size: ' + skinVar('fs-xs') + ';',
    '  font-weight: 700;',
    '  font-variant-numeric: tabular-nums;',
    '  overflow-wrap: anywhere;',
    '}',
    box + ' :focus-visible {',
    '  outline: 2px solid ' + skinVar('accent') + ';',
    '  outline-offset: 2px;',
    '}',
    '/* 悬停只许是增强：沿加深一档（通路始终是点一下）。 */',
    hover + ' {',
    '  ' + s('chip') + ':hover, ' + s('check') + ':hover, ' + s('dec') + ':hover, ' + s('inc') + ':hover {',
    '    border-color: ' + skinVar('accent') + ';',
    '  }',
    '}',
    '@media (prefers-reduced-motion: reduce) {',
    '  ' + s('chip') + ', ' + s('check') + ', ' + s('dec') + ', ' + s('inc') + ' {',
    '    transition: none;',
    '    transform: none;',
    '  }',
    '}',
    '/* 窄容器（本件自己窄于常量那一个宽度）：左标签右控件折成上下两段——标签仍在控件上面，',
    '   一行照样只做一个决定；胶囊两枚一行、方框与两个步进位各占满一行。 */',
    '@container ' + REMINDER_SETTER_CONTAINER + ' (max-width: ' + String(REMINDER_SETTER_NARROW_PX) + 'px) {',
    '  ' + s('row') + ' {',
    '    grid-template-columns: minmax(0, 1fr);',
    '  }',
    '  ' + s('label') + ', ' + s('ctl') + ' {',
    '    grid-column: 1;',
    '  }',
    '  ' + s('chip') + ' {',
    '    flex: 1 1 calc(50% - 4px);',
    '    justify-content: center;',
    '    padding: 0 10px;',
    '  }',
    '  ' + s('check') + ', ' + s('field') + ' {',
    '    flex: 1 1 100%;',
    '  }',
    '  ' + s('check') + ' {',
    '    justify-content: center;',
    '  }',
    '}',
    /* 第二档（`track`）那一段住同目录 `style-track.ts`：两档加起来超告警线，按先例拆出去，
       拼在这里返回——页面只认 `reminderSetterCss()` 这一个样式入口。 */
    reminderSetterTrackCss(p),
  ].join(LF);
}
